### ISSUE TITLE
readValue and socket inputstream (keep alive)

### ISSUE THREAD

**Issue by rockihack** [FasterXML/jackson-databind#1006]
I'm not sure this is the right place but I noticed something odd with java sockets and jackson.
My app sends requests to a rest api using scribe and parses the response with jackson.
I noticed when I use the response inputstream directly with readValue that socket keep alive doesn't work. Basically a connection is reused if the entire inputstream is read and the stream is closed (the result is that the underlying socket is disconnected).

Here is my first attempt which doesn't work:

`final InputStream is = response.getStream();`
`mapper.readValue(is, datamodel);`

First workaround:

`final String body = response.getBody();`
`mapper.readValue(body, datamodel);`

getBody reads the entire stream into a String before parsing.
The downside is that the workaround needs more memory and the allocation rate is high.

I came up with a second workaround:

`mapper.configure(Feature.AUTO_CLOSE_SOURCE, false);`
`final InputStream is = response.getStream();`
`final T result = mapper.readValue(is, datamodel);`
`is.read();`
`is.close();`

The is.read() method always returns -1, but now keep alive works as expected.
Can someone explain how readValue handles inputstreams and maybe give some advice how to do it properly?

**Comment by cowtowncoder** [comment]
@rockihack This would make more sense as a question to a mailing list like `jackson-users`.

But basically `readValue()` will, by default, close the stream after it has read a single root-level JSON value. This may be the whole input but is not necessarily so. It is possible to prevent closing of the stream either via configuration (there is a `JsonParser.Feature` for that, something like `AUTO_CLOSE_INPUT`?); or by constructing `JsonParser` explicitly via `JsonFactory` and passing that: if so, mapper will NOT try to close the parser (and thereby the stream).

I hope this helps in figuring out what you need -- I am not quite sure what you are trying to achieve, but handling of `InputStream` is quite simple. Similar handling also occurs for output with `OutputStream`, regarding closing (or not) of the stream.

**Comment by rockihack** [comment]
Thanks for your answer. I want to achieve a working http keep alive feature.

_But basically readValue() will, by default, close the stream after it has read a single root-level JSON value. This may be the whole input but is not necessarily so._

I understand now that the response inputstream is not fully consumed by readValue,
thats the reason why java cannot reuse the connection and creates a new connection for each request which introduces overhead in the tcp and ssl layer.

**Comment by DrWifey** [comment]
@rockihack Solved error for me! Thank you
