### ISSUE TITLE
JsonProperty.required ignored value type (boolean example)

### ISSUE THREAD

**Issue by nhojpatrick** [FasterXML/jackson-databind#1012]
When using JsonProperty.required it appears to ignore if then value is of the correct data type. Simply the key value was present. This might be as design.

What annotation should I be using to confirm a json property is present and it's value is also present and is of the correct data type? I've tried the below example using [] and {} and "" and those do throw an exception as expected.

In the example below using boolean and null, I would expect an exception to be thrown as the key was present but null was supplied. Or is their another annotation I would be using to confirm the value is present and the right data type? I don't want to use defaultValue as I want the client to explicitly state true or false.

Sample Json
```
{
  "booleanNull": null
}
```

Sample Java Tester
```
import java.io.IOException;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.exc.InvalidFormatException;

public class JacksonBooleanTester {

	@JsonCreator
	public JacksonBooleanTester(@JsonProperty(value = "booleanNull", required = true) final boolean booleanNull) {
	}

	public static void main(final String[] args) throws JsonParseException, JsonMappingException, IOException {
		final String json = "{\"booleanNull\":null}";

		final ObjectMapper mapper = new ObjectMapper();

		try {
			mapper.readValue(json, JacksonBooleanTester.class);

			System.err.println("InvalidFormatException was not thrown as expeted");

		} catch (final InvalidFormatException ife) {
			if ("Can not construct instance of boolean from Null value: only \"true\" or \"false\" recognized"
					.equals(ife.getMessage())) {
				System.out.println("InvalidFormatException was thrown as expeted");

			} else {
				System.err.println("InvalidFormatException was not thrown as expeted");
			}
		}
	}
}
```

**Comment by cowtowncoder** [comment]
Please use mailing lists for asking usage questions.

As to the feature: boolean deserializer probably accepts `null` as `false` value as simple coercion.
I wouldn't think this is related to `required` attribute, but if it is is (that is, exception was thrown if you did NOT specify 'required=true'), that would be a bug.

Otherwise I think there is a feature request for "strict handling of primitives", in which such usage would produce an exception; if not, feel free to add an issue to request this.
