### ISSUE TITLE
ISO8601 format in serialized dates might not be ECMAScript-compatible

### ISSUE THREAD

**Issue by danielfernandez** [FasterXML/jackson-databind#1020]
As of `jackson-databind::2.6.3`, a `java.util.Calendar` or a `java.util.Date` object is serialized in non-timestamp format (i.e. after disabling `SerializationFeature.WRITE_DATES_AS_TIMESTAMPS`) in ISO8601 format and normalized to UTC, which is fine. For example:

```
"2013-01-01T13:30:00.000+0000"
```

The problem is, I'm not really sure this is compatible with the ECMAScript standard, version 6.0 (and older). If we have a look at section **20.3.1.16: Date Time String Format** (see http://ecma-international.org/ecma-262/6.0/#sec-date-time-string-format ), it literally says:

> ECMAScript defines a string interchange format for date-times based upon a simplification of the ISO 8601 Extended Format. The format is as follows: YYYY-MM-DDTHH:mm:ss.sssZ

So it doesn't seem the entire ISO8601 is supported, but only a _simplification_. Which shows when the `Z` in the format above is explained as:

> Z     is the time zone offset specified as "Z" (for UTC) or either "+" or "-" followed by a time expression HH:mm

In my understanding, that might mean the date above, as serialized by Jackson, would not be ECMAScript-valid due to the lack of a colon symbol (`:`), even if it is ISO8601-valid indeed. 

For being valid it would have to be expressed as any of the following two possibilities:

```
"2013-01-01T13:30:00.000Z"
"2013-01-01T13:30:00.000+00:00"
```

This comes from the use at https://github.com/FasterXML/jackson-databind/blob/20a67f73f362bce0d0d93afacec12d30796affa8/src/main/java/com/fasterxml/jackson/databind/util/StdDateFormat.java#L34 of the following date pattern:

``` java
protected final static String DATE_FORMAT_STR_ISO8601 = "yyyy-MM-dd'T'HH:mm:ss.SSSZ";
```

But the problem is that, as stated at the javadoc for `java.text.SimpleDateFormat` (see http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html ), the `Z` format modifier is for **RFC822** format, which is why Java 7 introduced the `X` modified for ISO8601. 

So in Java 7 this should look like:

``` java
protected final static String DATE_FORMAT_STR_ISO8601 = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX";
```

Nevertheless, Jackson 2.6 should still support Java 6, so the transformation (adding the `:`) needs to be done manually :(

As for **why bother** doing this... the JSON specification itself does obviously not say anything about _dates_, because they are not one of the possible types of JSON values. But being the JSON specification so profoundly related to that of ECMAScript from which it borrowed a large part of its syntax, it makes sense to me that date literals are specified in JSON serializations in an ECMAScript-compatible way, at least by default.

Finally, issue #919 seems related to this topic, though deserialization-oriented.

**Comment by cowtowncoder** [comment]
Ok I have to think this through, for multiple reasons.

As to Java 7, Java 2.7 will indeed require Java 7 as baseline so that may become a non-problem.

But if the idea is to change the default format to include colon, that would also be backwards incompatible change. One way to address that could be to add yet another `SerializationFeature`, but ultimately I wonder if that's worth it.

As to individual users, wouldn't it be simple to just change the default `DateFormat` `ObjectMapper` uses, however?

**Comment by danielfernandez** [comment]
> But if the idea is to change the default format to include colon, that would also be backwards incompatible change. 

In the sense that JSON serialized by Jackson *before* and *after* the change would be different yes, this change would break backwards compatibility. So e.g. tests relying on the **literal equality** of serialized JSON could fail.

But JSON serialized by Jackson *before* this change should be deserializable without issues by a version of Jackson that had this change applied, as all possible ISO8601 formats are allowed during deserialization — or at least that's what I infer from the tests linked at #919.

> As to individual users, wouldn't it be simple to just change the default DateFormat ObjectMapper uses, however?

Yes, certainly individual users can specify a different `DateFormat`, though they will only be able to use the correct `X` date-format pattern if they are using Java > 7, and would have to write their own implementation of `DateFormat` if not.

So it's not that being 100% ECMAScript-valid date-wise is not *possible* with Jackson, only that it seems that the default configuration isn't.

**Comment by cowtowncoder** [comment]
@danielfernandez Yes, I understand your point regarding possible vs convenient/optimal.

My concern regarding compatibility however is not so much with Jackson itself (which can indeed read both format like you said), but rather with other systems. It seems there is always some system somewhere that is brittle enough to only accept one of variants and fail on other. And I get to learn all about such systems via bug reports. :-D

Would it be possible for you to send an email to `jackson-dev` list, and ask for input on this issue? I am not against making the change for 2.7, even including changing default output format; but I would like to get some consensus that this is worth the non-trivial risk of breaking someone's system (regardless of that typically being due to brittleness of the system itself).

One other related point, regarding Java 7 compatibility. While Jackson 2.7 moves the baseline, I have tried to make things dynamic enough to degrade gracefully, specifically to support Android. Unfortunate situation with Android seems to be that while tools can support Java 7 language features (partly since they are most syntactic sugar; and partly since Java bytecode gets translated to Dalvik bytecode I think), there is not JDK 7 library support. And that's unfortunate wrt use of `SimpleDateFormat`, where we would need the new formatter.
Obviously this is not the only place where things eventually will need to be decided wrt going forward with JDK or looking back.

**Comment by cowtowncoder** [comment]
@danielfernandez Ok, beyond the part about when we can rely on JDK7 date format support (which unfortunately I think is Jackson 2.8), I am actually interested in knowing if there are existing known problems with this. I am guessing this may be prompted by observed issues? If so, it would be good to have links for further reading, as it more meaningful to consider real problems to solve, compared to potential problems. Similarly when considering downside risk, it is good to point to existing problems as counterweight to potential new problems if behavior was changed.

Another smallish question is hpw Java 8 date time module (jackson-datatype-jsr310) should be handled: it obviously can rely on JDK7 support, but additionally it does not even use old `DateFormat` (I think?). Perhaps it'd make sense to file a separate (but linked) issue for that project?
That could even be tackled earlier, perhaps even for 2.7.

**Comment by danielfernandez** [comment]
@cowtowncoder actually I have no observed issues to report :). As I explained in my message to `jackson-dev`, I noticed this while performing the changes needed for Thymeleaf to adopt Jackson as its default JavaScript serialization strategy for Thymeleaf 3.0.

We already had a custom-made JavaScript/JSON serialization mechanism in place in previous versions, which we will keep in 3.0 as a fallback in case users don't want to add Jackson to their apps for some reason, and our intention is to make both mechanisms produce equivalent output for simple values (text literals, numerals, **dates**…)

And while doing this, we found that the format in which dates were output using our mechanism didn't match Jackson's output, which made some of our existing tests fail. Anyway, we are providing a default `DateFormat` configuration for Jackson in Thymeleaf 3.0 which enables this ECMAScript compatibility, so it's not really a problem for us right now.

Just a discrepancy with the specs, nothing else :)

**Comment by cowtowncoder** [comment]
@danielfernandez Ok. I think it's worth leaving open, and may be considered esp. once JDK support allows (wrt `java.util.Date`)

**Comment by cowtowncoder** [comment]
Ok, not sure there is anything to work explicitly here: I am not against changing default `DateFormat`, but without specific problem to solve I am bit wary of changing behavior -- many regression bugs have been spawned by this.

So: to solve specific issue I have no objections, but until then (reproduction needed) will close.

**Comment by bozaro** [comment]
Suddenly, `2013-01-01T13:30:00.000+0000` **is not a correct ISO 8601** date: it mix basic timezone format and extended date and time format.

Correct value looks like:

2013-01-01T13:30:00.000+00:00 (Extended format)
20130101T133000.000+0000 (Basic format)

So, by default Jackson uses a strange date format, which is very similar to ISO 8601, but it is **not ISO 8601**.
This is very confusing.

**Comment by cowtowncoder** [comment]
@bozaro Please point to ISO-8601 specification to show this is true statement. As you may know, it's a rather complex standard, or maybe more meta-standard describing kinds of things one can use. There is no such thing as "ISO-8601 date" -- just a big set of potential subsets.

**Comment by bozaro** [comment]
Unfortunatelly, I have not access for official ISO-8601:2004 document.

I use: http://www.uai.cl/images/sitio/biblioteca/citas/ISO_8601_2004en.pdf

Chapter 2.3 defines `basic format` and `extended format`:
> ### 2.3.3 basic format
> format of a date and time representation or date and time format representation comprising the minimum number of time elements necessary for the accuracy required 
> 
> ### 2.3.4 extended format
> extension of the basic format that includes additional separators 
> 

Chapter 4.2.5.2 defines `Local time and the difference from UTC`:
> ### 4.2.5.2 Local time and the difference from UTC
> When it is required to indicate local time and the difference between the time scale of local time and UTC, the representation of the difference shall be appended to the representation of the local time following immediately, without space, the lowest order (extreme right-hand) time element of the local time expression.
> The difference between the time scale of local time and UTC shall be expressed in hours-and-minutes, or hours-only independent of the accuracy of the local time expression associated with it.
> The complete representation of the time of 27 minutes and 46 seconds past 15 hours locally in Geneva (in winter one hour ahead of UTC), and in New York (in winter five hours behind UTC), together with the indication of the difference between the time scale of local time and UTC, are used as examples.
> ```
> Basic format:     hhmmss±hhmm     Example: 152746+0100
>                                            152746-0500
>                   hhmmss±hh                152746+01
>                                            152746-05
> Extended format:  hh:mm:ss±hh:mm  Example: 15:27:46+01:00
>                                            15:27:46-05:00
>                   hh:mm:ss±hh              15:27:46+01
>                                            15:27:46-05
> ```
> In these expressions the local time component may be represented with reduced accuracy as defined in 4.2.2.3 or with decimal fraction as defined in 4.2.2.4. 


Chapter 4.3.2 contains example of `Complete representations`:
> The following are examples of complete representations of date and time of day representations:
> ```
> Basic format:     YYYYMMDDThhmmss            Example:  19850412T101530
>                   YYYYMMDDThhmmssZ                     19850412T101530Z
>                   YYYYMMDDThhmmss±hhmm                 19850412T101530+0400
>                   YYYYMMDDThhmmss±hh                   19850412T101530+04
> Extended format:  YYYY-MM-DDThh:mm:ss        Example:  1985-04-12T10:15:30
>                   YYYY-MM-DDThh:mm:ssZ                 1985-04-12T10:15:30Z
>                   YYYY-MM-DDThh:mm:ss±hh:mm            1985-04-12T10:15:30+04:00
>                   YYYY-MM-DDThh:mm:ss±hh               1985-04-12T10:15:30+04 
> ```

I did not found direct indication that you can not mix `basic format` and `extended format`.

But also I did not found any example of mixed formants is ISO 8601:2004 document.

**Comment by challarao** [comment]
> Either basic or extended formats may be used, but both date and time must use the same format. The date expression may be calendar, week, or ordinal, and must use a complete representation.

https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations

**Comment by cowtowncoder** [comment]
Apparently there is a gnarly problem with use (or not) of colon in time offset, and I guess this is the crux of the problem. What makes it nasty in Java is that by default "old" `java.util.Date` / `Calendar` uses different representation than Java 8 date or Joda.

Jackson 2.9.1 did add a direct mechanism in `StdDateFormat`, method `withColonInTimeZone(boolean)` that allows forcing of inclusion of colon, although use of custom format is probably the best way to force it. Due to compatibility problems there will be no change to default serialization for Jackson 2.x.
But we can change it for 3.x.

**Comment by cowtowncoder** [comment]
Fwtw, I filed this:

https://github.com/FasterXML/jackson3-dev/issues/7

to change Jackson 3.0 default serialization.
