### ISSUE TITLE
(2.7.0-rc1): `AnnotationIntrospectorPair.findPropertyInclusion` has a minor bug

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1025]
Looks like said method has a cut'n paste problem, in that it only calls "secondary" introspector's method (twice), thereby accidentally skipping primary. This was found via Hibernate module's test; need to add a direct test in databind as well.

**Comment by cowtowncoder** [comment]
Note: related to https://github.com/FasterXML/jackson-annotations/issues/76 which also prevented code from working.

**Comment by osi** [comment]
ah, cool. i had just found this in wondering why the inclusion stuff in rc1 was wacky :+1:
