### ISSUE TITLE
CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES doesn't work in special case

### ISSUE THREAD

**Issue by snarayanank2** [FasterXML/jackson-databind#1026]
I have a class with a property that looks like this:

```
class User {
  private String uId;
}
```

When I use the ```CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES``` naming strategy, this results in JSON with ```uid```. However, if I change the variable name to ```usId```, it results in ```us_id```. 

In general, it appears that if the first character is lower case and second is upper case, the naming strategy appears to not work as I'd expect. Any way around this?

I'm using ```jackson-databind-2.6.1``` with DropWizard.

**Comment by cowtowncoder** [comment]
To me this sounds like a bug, so a Pull Request for fix (and test that shows the initial problem) would be welcome.

**Comment by cowtowncoder** [comment]
Unfortunately I can not reproduce this problem either with 2.6 branch (pre-2.6.4) or master (2.7.0-rc1), with property id of "uId" -- I get "u_id" as expected. So I think I would need a stand-alone unit test.

One thing to note is that Dropwizard has its own "snake case" annotation, I think, which uses different naming strategy implementation. Perhaps that could be causing the problem?

**Comment by snarayanank2** [comment]
That is interesting! I'm not able to repro it in a standalone fashion. Looks like Dropwizard might be messing things up somewhere. I'll do some more investigation.

**Comment by snarayanank2** [comment]
Actually turns out it doesn't have to do with the variable name, but the getter function. Here's a complete reproduction:

```
 class T1 {
    private String uId;
    public T1() {}
    public T1(String uId) { this.uId = uId; }
    public String getUId() {
      return uId;
    }
    @Override
    public String toString() {
      return "T1 [uId=" + uId + "]";
    }
  }
  
  @Test
  public void testCase() throws IOException {
    T1 x = new T1("hello");
    String json = om.writeValueAsString(x);
    logger.info("json = " + json);
  }
```

This prints out:
```
json = {"uid":"hello"}
```

If I change class T1 to look like this (changed member variable to public and removed getter):
```
  class T1 {
    public String uId;
    public T1() {}
    public T1(String uId) { this.uId = uId; }
    @Override
    public String toString() {
      return "T1 [uId=" + uId + "]";
    }
  }
```

This produces:
```
json = {"u_id":"hello"}
```

Is this expected behavior? What should I name the getter to get the ```u_id``` in json?

**Comment by snarayanank2** [comment]
If I name the getter:
```
    public String getuId() { return uId; }
```

Then I get ```u_id``` in the JSON.

**Comment by snarayanank2** [comment]
So history is that I was using Project Lombok to generate my getters and setters and it looks like it uses a different naming convention for getters. See small print section in this [doc](https://projectlombok.org/features/GetterSetter.html)

Looks like this isn't a Jackson bug after all :) Sorry for the trouble - please feel free to close the issue.

**Comment by cowtowncoder** [comment]
@snarayanank2 No problem. One related thing, for future reference, is that Jackson also has a minor deviation from standard Bean naming (it is lower-casing multiple leading upper-case letters, instead of leaving them as-is -- affects things like "getURL").
If this is what happens here, you may want to enable `MapperFeature.USE_STD_BEAN_NAMING`, which changes the behavior in this regard. I guess it may not be directly related, but might be good thing to be aware of.
