### ISSUE TITLE
Add a way to define property name aliases

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1029]
Although it is possible to use a work-around for accepting alternate property names (by adding secondary setters), it would probably be better to allow an explicit annotation support.
This could be something as easy as:

```
 @JsonProperty(value="name", alias={ "oldName", "anotherOldName" })
```

and would work so that alternative names would be also accepted, but would not be considered the primary name (would not affect serialization for example).

This feature would seem most useful for versioning purposes, to essentially allow for renaming of properties. This is how other formats like Avro handle backwards compatibility.

**Comment by indiascope** [comment]
in My model i try JsonAlias but not working. 

 @JsonAlias({"userFullName","username","fullName"})
     private String userFullName;

    public String getUserFullName() {
        return userFullName;
    }

    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }

in api i got response in fullname key. but always i get userFullName null .if i make any mistake please let me know.

**Comment by cowtowncoder** [comment]
@indiascope Please file a new issue with full code to reproduce the problem -- while snippet above is useful it is not enough to reproduce the problem without specifying input and code to call deserialization.

**Comment by indiascope** [comment]
Thanks for reply. After update project all jackson library to 2.9.0 problem is solved.before update jackson-databind to 2.9.0 jsonAlias not working always get null data.

compile 'com.fasterxml.jackson.core:jackson-databind:2.9.0';
compile 'com.squareup.retrofit2:converter-jackson::2.9.0';
compile 'com.fasterxml.jackson.core:jackson-annotations::2.9.0';

**Comment by cowtowncoder** [comment]
@indiascope Yes, that would make sense as this feature was added in Jackson 2.9, so earlier versions do not support it.

**Comment by sschuberth** [comment]
Is there also a way to configure the alias feature globally, similar to a `PropertyNamingStrategy`, so that **de**serialization accepts multiple property names (like undersorces *and* camel-case)? That would be great for backwards compatibility with existing JSON files when migrating from one naming style to the other.

**Comment by cowtowncoder** [comment]
@sschuberth In future, please ask questions on mailing lists.

But no, there is no mechanism for doing that at this point. Naming strategy does one-way transformation at this point.

I think the idea has merit, though, and since we are working for Jackson 3.0, perhaps interface could be extended to allow production of aliases too? Could you please file an issue here, outlining your idea (and with a ref back to this issue if it makes sense).
