### ISSUE TITLE
After @JsonAutoDetect(fieldVisibility = Visibility.NONE) still serializes the fields

### ISSUE THREAD

**Issue by aandres-medallia** [FasterXML/jackson-databind#1031]
The issue occurs because at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector#_addFields it does the following

```
            boolean nameExplicit = (pn != null);

            if (nameExplicit && pn.isEmpty()) { // empty String meaning "use default name", here just means "same as field name"
                pn = _propNameFromSimple(implName);
                nameExplicit = false;
            }
            // having explicit name means that field is visible; otherwise need to check the rules
            boolean visible = (pn != null);
            if (!visible) {
                visible = _visibilityChecker.isFieldVisible(f);
            }
```

The line `boolean visible = (pn != null);` should be replaced by `boolean visible = nameExplicit;`

**Comment by cowtowncoder** [comment]
Sounds plausible, but it would be great if you could provide code to show an example of where this causes problem.

**Comment by aandres-medallia** [comment]
Sure

```
@JsonAutoDetect(fieldVisibility = Visibility.NONE, getterVisibility = Visibility.PUBLIC_ONLY)
public class Test {
	public String field = "should not be serialized";
	public String getGetter() {
		return "should be serialized";
	}

	public static void main(String[] args) throws JsonProcessingException {
		System.out.println(new ObjectMapper().disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS).registerModule(new JaxbAnnotationModule()).writeValueAsString(new Test()));
	}
}
```

and the output is `{"field":"should not be serialized","getter":"should be serialized"}`
I've just realized that it works properly If you do not register `JaxbAnnotationModule`.

**Comment by cowtowncoder** [comment]
Thanks.

If this works without JAXB annotations module, I suspect the issue is more with differing rules; JAXB module does try to follow JAXB visibility rules.

Looking back at the original suggestion, it is actually not what should be done I think: visibility does not necessarily require explicit name from annotations. Unit test suite also reports 23 failures with the change.

**Comment by cowtowncoder** [comment]
Can not reproduce just with `jackson-databind`; if this is JAXB specific, should file a bug (ideally with unit test) for `jackson-module-jaxb-annotations`.
