### ISSUE TITLE
strange internal NPE for EnumValue Serialization

### ISSUE THREAD

**Issue by tkruse** [FasterXML/jackson-databind#1038]
Hi,
I have no easy way to reproduce available (yet), but I notice this NullPointerException in JacksonAnnotationIntrospector:
```
 public String findEnumValue(Enum<?> value)
    {
        try {
            Field f = value.getClass().getField(value.name());
            if (f != null) {
                JsonProperty prop = f.getAnnotation(JsonProperty.class);

                // NPE here if prop is null

                String n = prop.value();
                if (n != null && !n.isEmpty()) {
                    return n;
                }
            }
        } catch (Exception e) {
            // no such field, or access; neither which we can do much about
        }
        return value.name();
    }
```

While the NPE is caught and ignored, it is not mentioned, and I thought this might be unintended.

EDIT: USing Jackson-databind-2.6.2 on Java 8

**Comment by tkruse** [comment]
My Enum class in Question I can share:
```
public enum ConnectionState {
	online,
	offline,
	unknown
}
```

**Comment by cowtowncoder** [comment]
Code has been changed to not catch general `Exception`, as well as to explicitly check that `prop` is not null. This may already be in 2.6.3; if not, will be in 2.6.4 (it was fixed relatively recently).
