### ISSUE TITLE
Function as JsonNodeType

### ISSUE THREAD

**Issue by jvmlet** [FasterXML/jackson-databind#1041]
Hello
Would you please consider to support `function` as `JsonNodeType` ?
````
{
"add": function(a,b) { return a+b }
}
````
Thanks

**Comment by cowtowncoder** [comment]
Such notation is not valid JSON; and in that sense no I don't think this will be supported, and I do not have personal interest in doing so.

Beyond basic parsing there would also be the question of how it would be exposed; given that it'd be just piece of unquoted text (how would one even know where it ends? there's comma in there), one couldn't really easily tell it apart.

So I think answer would be no, I don't think this will ever be supported.

**Comment by jvmlet** [comment]
Well, the representation could be much smarter than piece of unquoted text- it could be <b>invokable</b> server side js function and  part of JsonFunctionNode  API:
````
String[] getArgumentsNames()
Object invoke(Object ...arguments)
````
that evaluates the function body against SPI configured server side js engine.

The parser simply takes all the content inside function definition ````{}```` as body and splits arguments names inside ````()````:
````
function(coma separated arguments){ FUNCTION BODY}
````

Think about it again ... it could be more useful as it sounds first time.

**Comment by cowtowncoder** [comment]
I am not arguing that there could not be interesting things one could do by adding behavior to data. But I do think it falls well outside what Jackson itself is designed to do.

But if anyone wants to pursue something like that, it should be possible to implement pluggable Tree Models, based on `TreeNode` and `TreeCodec` (factory).
