### ISSUE TITLE
@JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY) does not work on fields

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1043]
(note: moved from https://github.com/FasterXML/jackson-annotations/issues/67)

----

Looks like `JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY` per-property override does not work, unlike its serialization counterpart (`JsonFormat.Feature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED`)

**Comment by cowtowncoder** [comment]
Oddly enough, while other features are supported, implementation for this (beyond exposing value for property) is missing. Due to extensive amount of changes needed, will only go in 2.7.

**Comment by dwybourn** [comment]
Was this ever fixed in 2.7? I'm still seeing this bug in 2.9.1

**Comment by cowtowncoder** [comment]
@dwybourn yes, as per check-in above and closing of this issue it should work.
If not, please file a new issue with reproduction -- I prefer not opening old issues since it makes tracking of fixes more difficult, even if the root cause is same or earlier fix was incomplete.
