### ISSUE TITLE
`@JsonUnwrapped` and `@JsonView` don't work together

### ISSUE THREAD

**Issue by fmerino-indra** [FasterXML/jackson-databind#1046]
Hi,
I'm using 2.6.3 version of jackson-databind. I've made the next example:

```
public enum NodeState implements Serializable {
    OPERATIONAL(0, "OPERATIONAL"),
    DEGRADED(1,"DEGRADED"),
    FAILED(2, "CRITICAL"),
    UNKNOWN(3,"UNKNOWN"),
    STOPPED(4,"STOPPED"),
    UNREACHABLE(5, "UNREACHABLE"),
    PENDING(6,"PENDING")    ;

    @JsonView(View.Tree.class)
    @JsonProperty("stateId")
    private final int state;

    @JsonView(View.Detail.class)
    private final String stateStr;

    NodeState(int type, String typeStr) {
        this.state = type;
        this.stateStr = typeStr;
    }
    public int getState() {
        return state;
    }
    public String getStateStr() {
        return stateStr;
    }
}
public class BaseState implements Serializable {
    @JsonUnwrapped
    @JsonView(View.Tree.class)
    private NodeState nodeState;

    @JsonView(View.Tree.class)  
    private int risk;
    public BaseState(NodeState nodeState, int risk) {
        this.nodeState = nodeState;
        this.risk = risk;
    }
}
```

The View class definition

```
public class View {
    public static class Tree {}
    public static class Detail extends Tree {}
}
```

I use this code in the next way:

```
public static void main(String args[] {
    BaseState state = new BaseState(NodeState.OPERATIONAL, 2);
    ObjectMapper mapper = new ObjectMapper();
    String json = null;
    mapper.disable(MapperFeature.DEFAULT_VIEW_INCLUSION);
    json = mapper.writeValueAsString(state);
    java.lang.System.out.println(json);
}
```

The execution throws the next 

```
java.lang.IllegalStateException: Can not override serializer
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.assignSerializer(BeanPropertyWriter.java:402)
    at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.assignSerializer(UnwrappingBeanPropertyWriter.java:137)
    at com.fasterxml.jackson.databind.ser.impl.FilteredBeanPropertyWriter$SingleView.assignSerializer(FilteredBeanPropertyWriter.java:53)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.resolve(BeanSerializerBase.java:339)
    at com.fasterxml.jackson.databind.ser.SerializerCache.addAndResolveNonTypedSerializer(SerializerCache.java:177)
    at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1166)
    at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:481)
    at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:679)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:107)
    at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3559)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2927)
    at es.fmm.json.Application.run(Application.java:42)
```

If I remove the @JsonUnwrapped annotation from nodeState attribute of BaseState class, it work's with no problem. The output is:

```
{"nodeState":{"stateStr":"OPERATIONAL","stateId":0},"risk":2}
```

Or, if I remove the @JsonView annotation from nodeState attribute of BaseState class, it work's too. The test invocation is:

```
    json = mapper.writerWithView(View.Tree.class).writeValueAsString(state);
    java.lang.System.out.println(json);
```

The output is:

```
{"stateStr":"OPERATIONAL","stateId":0,"risk":2} // With first test
{"risk":2} // With second test
```

Thanks a lot for your help.

**Comment by cowtowncoder** [comment]
I assume it won't make a big difference, but now that 2.7.0-rc2 is out, I wonder if it exhibits the same problem?

**Comment by fmerino-indra** [comment]
Yes, I also checked that version and the result was the same.

**Comment by fmerino-indra** [comment]
Ops, sorry, but ... what about this issue?
Thank you very much!

**Comment by cowtowncoder** [comment]
@fmerino-indra Sorry, haven't had a chance to look into this yet. Will try to see what gives within day or two.

**Comment by reckter** [comment]
Hey, I just stumbled into this problem using jackson-databind version 2.8.1.
The exception I am getting is a bit different though: 
`java.lang.IllegalArgumentException: No converter found for return value of type: class [..].UserDto`

Is there any news on this?

**Comment by cowtowncoder** [comment]
@reckter If exception is different, please file a different issue with description of what is happening, and ideally reproduction. It may be the same thing, but that's not obvious if symptoms are different.

**Comment by reckter** [comment]
@cowtowncoder Just looked at the stacktrace again and saw, that I indeed am getting the same exception as the @fmerino-indra. My Exception just was an effect of using Jackson with Spring-boot-starter-web.
So this is the same issue.

**Comment by cowtowncoder** [comment]
Ok thank you for verifying this.

**Comment by reckter** [comment]
I also found a workaround for this:
Instead of using JsonView, I am now using a MixIn in the ObjectMapper that ignores the relevant fields.
That does work, but it's more work.

**Comment by adhamhf** [comment]
@reckter how are you applying a Mixin to the Enum?  I need to do this too.

**Comment by cowtowncoder** [comment]
Unfortunately I can not reproduce this with any of 2.7, 2.8 or `master` (2.9).
Looking at test case, I don't know why `@JsonUnwrapped` would have any affect on Enum type: they are not serialized like POJOs anyway.

Closing: may be re-opened with failing test case.
