### ISSUE TITLE
Allow use of `@JsonAnySetter` on a Map-valued field, no need for setter

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1047]
It would seem useful to allow use of `@JsonAnySetter` on fields with proper value; `Map` at least should be supported; optionally also `ObjectNode` but that's just icing on cake.

**Comment by islanderman** [comment]
Not quite sure what you mean.  I thought at least for ``Map`` it is already supported.  See https://github.com/FasterXML/jackson-databind/blob/master/src/test/java/com/fasterxml/jackson/databind/access/TestSerAnyGetter.java

**Comment by cowtowncoder** [comment]
Hmmh. Just realized that the implementation has a flaw in that access to `@JsonAnySetter` does not go via `AnnotationIntrospector`, like all Annotation access ought to. Will fix for 2.9, related to also making it possible to disable any-setter mutator.
