### ISSUE TITLE
Endless recursion in TypeIdResolverBase

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#1054]
`TypeIdResolverBase.typeFromId(String)` invokes `TypeIdResolverBase.typeFromId(DatabindContext, String` which invokes the former. This means that the default implementation will lead to endless recursion.

Besides which, shouldn't the implementer be forced implement one of these methods? If so, the documentation should state as such. Why is an implementation provided at all?

**Comment by cowtowncoder** [comment]
@cowwoc The challenge is backwards compatibility and it is basically risky to add any new abstract methods. If both did exist from beginning, yes, one or both should be abstract. If my memory serves me, former was there first, and the goal was to let old implementations be invoked by new code, which calls the second method.

So this is an artifact of versioning, more or less.

As usual, documentation improvements would be very welcome; I'll leave this open so I'll see if I can improve them, unless someone beats me to it.

**Comment by cowtowncoder** [comment]
Improved this system a bit, now will throw explicit exception if not overridden. Might also remove deprecated method later on (maybe in 2.8), but at very least should avoid nastiest fail of all too deep recursion. Thank you for pointing this out; while there was a reason it was done the way it was, I can see why it makes sense to change it.
