### ISSUE TITLE
Custom serialization cleanup

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#1057]
The serialization mechanisms could use a clean-up. Specifically, I suggest addressing the following points:
1. Users can implement an interface for custom serialization (`JsonSerializable`) but are forced to extend an abstract class for custom deserialization (`JsonDeserializer`).
2. Very often, users who implement custom serializer will need a corresponding custom deserializer. Point 1 means that they cannot implement this in the class being serialized.
3. Users are advised to extend `StdSerializer` and `StdDeserializer` for custom serialization/deserialization respectively. If we are going to force users to isolate custom (de)serialization code into a separate class, they should be able to implement a single class for both serialization and deserialization.
4. Nitpicking, `JsonSerializable` and `JsonDeserializer` are not symmetrical (either in name or mechanism). Ideally they should be.

So... ideally I'm looking for two separate interfaces: one for serialization, one for deserialization. Then, I'd want two separate abstract base classes for each implementation. Finally, I'd want a single base class that users can extend that would be used for classes that implement both the serializer and deserializer in one place.

Final suggestion: The Effective Java book talks about a "serialization proxy" design pattern where instead of serializing/deserializing the main class, the developer provides a stand-in class that is safe/easy to serialize and then converts from that class back to the main one. I suggest supporting such a mechanism because although it might not be as performant, it is much easier to implement that the current mechanism (and this is good enough for most cases).

**Comment by cowtowncoder** [comment]
One quick note: `Converter` interface does indeed support serialization/deserialization proxy pattern (if I understand it correctly).

As to other points: to be completely blunt, I am not sure I see enough value for majorly backwards-incompatible changes. If starting from scratch points are valid, and there would have been better ways to design, name things. So it is not that I disagree with any of suggestions, but rather I am not sure there is much worth doing for Jackson 2.x.
At the same time, if Jackson 3.x API work is ever started, these could and should be considered.

**Comment by cowtowncoder** [comment]
One additional note: non-symmetry between `JsonSerializable` and `JsonDeserializer` is a fundamental property -- during serialization instance exists, during deserialization it does not (with exception of new "merge" case to add in 2.9). So that is not accidental difference but reflects underlying real difference: you can not have `JsonDeserializable` in general sense.

**Comment by cowtowncoder** [comment]
Since there are "delegating" serializer/deserializer, base implementations for the same, and even annotation (that allows defining of `Converter`), I think there is enough support for proxying.
