### ISSUE TITLE
Consider possibility of allowing use of `@JsonIgnoreProperties` for POJO values of Collections, Maps

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1060]
Currently it is possible to use `@JsonIgnoreProperties` not only on classes, but also on POJO-valued properties. If so, ignorals are combined with ones that class itself may have.

This can not, however, be used for Collections or arrays, as they have no properties to ignore. But if collection/map contents are POJOs, it would semantically make sense to allow usage for value type (elements), if possible.

It might also make sense to allow similar approach for Map values, but there is the problem with ambiguity, as Map keys can be considered properties, and currently functionality does support ignoral.

**Comment by cowtowncoder** [comment]
And in fact I think this actually already works for `Map`s, ignoring entries as annotated. So it'd only work on arrays, Collections.

**Comment by VenkateshKatabathula** [comment]
I am also getting the same issue while ignoring properties. I get this while using List, I hope this will be allowed in future releases. Good work guys Keep going.

**Comment by cowtowncoder** [comment]
Interesting. Should have actually tested earlier, but this DOES work at least on 2.9.
So: `@JsonIgnoreProperties` annotation on `Collection` or array-valued property should work, as long as POJO type is declared. So no further work needed. If there are gaps please report as new issues.
