### ISSUE TITLE
ObjectMapper.copy() will lose the JsonParser.Feature configuration.

### ISSUE THREAD

**Issue by joson** [FasterXML/jackson-databind#1074]
version: jackson-databind-2.6.1

I found ObjectMapper.copy() will lose the JsonParser.Feature, but keep DeserializationFeature and SerializationFeature well.

Test codes as below:
```java
ObjectMapper mapper1 = new ObjectMapper();

mapper1.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true);
mapper1.configure(JsonParser.Feature.ALLOW_COMMENTS, true);
		
ObjectMapper mapper2 = mapper1.copy();

System.out.println("mapper2.FAIL_ON_UNKNOWN_PROPERTIES:"+mapper2.isEnabled(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES));
System.out.println("mapper2.ALLOW_COMMENTS:"+mapper2.isEnabled(JsonParser.Feature.ALLOW_COMMENTS));
```

It seems to be caused by MappingJsonFactory.copy(), which renew an ObjectMapper._jsonFactory without copying any value.

**Comment by cowtowncoder** [comment]
I can not reproduce this with 2.6 branch (with what will become 2.6.5); settings seem to copied fine.
Are you sure you have 2.6 version of `jackson-core`?

**Comment by joson** [comment]
In my program both core and databind was v2.6.1. I've just test it with v2.6.4 and v2.7.0-rc3, then I found it's fixed. 
Thanks a lot.

**Comment by cowtowncoder** [comment]
@joson Excellent, thank you for verifying this.
