### ISSUE TITLE
Potentially breaking annotation introspection change in 2.7.x

### ISSUE THREAD

**Issue by danielnorberg** [FasterXML/jackson-databind#1076]
jackson-databind 2.7.x seems to have changed how `AnnotationIntrospector#findImplicitPropertyName()` interacts with `@JsonProperty` annotations in abstract types.

I've attempted to put together a minimal repro here:

https://github.com/danielnorberg/jackson-27-annotation-introspection-breakage-repro

https://github.com/danielnorberg/jackson-27-annotation-introspection-breakage-repro/blob/master/src/main/java/test/Repro.java

The above code works when using jackson <= 2.6.4.

I'm not sure if maybe the issue is that I'm misusing `AnnotationIntrospector#findImplicitPropertyName()`, but what I'm trying to achieve is to both derive property names automatically from method names and allow users to explicitly override property names using `@JsonProperty` in the auto-matter library.

https://github.com/danielnorberg/auto-matter/blob/master/jackson/src/test/java/io/norberg/automatter/jackson/Foo.java

https://github.com/danielnorberg/auto-matter#jackson-json-support

**Comment by michaelhixson** [comment]
I feel like this is the same underlying issue as #1077, but I created the separate issue just in case.

**Comment by cowtowncoder** [comment]
I can not think of any related intended changes. Did this problem not occur with 2.7.0 release candidates?

**Comment by cowtowncoder** [comment]
Looks like it failed with `2.7.0-rc1` as well (and probably rc2, rc3). It does look like a bug from the repro class; will try to see what causes.

**Comment by michaelhixson** [comment]
@danielnorberg Do you get the behavior you were expecting if, where you create the `ObjectMapper`, you add this?

```java
.configure(MapperFeature.ALLOW_EXPLICIT_PROPERTY_RENAMING, true)
```

If so, maybe the incompatibility was introduced in https://github.com/FasterXML/jackson-databind/commit/da579e3da706dd2429b90b3d5d35fc62f5bde7f4

**Comment by danielnorberg** [comment]
@michaelhixson no, it still blows up even if I set `ALLOW_EXPLICIT_PROPERTY_RENAMING` to `true`.

**Comment by danielnorberg** [comment]
@cowtowncoder Yeah, I was planning to bisect to try and find the breaking change, but haven't had time to do that yet. Thanks for taking a look! Love jackson btw, not sure what I would do without it =)

**Comment by danielnorberg** [comment]
@michaelhixson @cowtowncoder By bisecting I've narrowed it down to 3243c9f780485794b55587f5bf4bc34467c7b62f. 525bf3ee3e193b060dbf37c026dd057c421a8a4d passes.

**Comment by cowtowncoder** [comment]
@danielnorberg Appreciate your help! I hope to have a look at this later tonight.

**Comment by danielnorberg** [comment]
@cowtowncoder Seems like `SimpleType#getInterfaces(Class<?> cls)` does not return the interfaces that a class implements when constructed by `SimpleType#construct(Class<?> cls)`.

https://github.com/danielnorberg/jackson-27-annotation-introspection-breakage-repro/blob/master/src/main/java/test/ClassUtilTest.java

**Comment by cowtowncoder** [comment]
@danielnorberg Ah! Yes, you should not be calling that method  -- instead, use method `constructType()` from `DeserializationContext` / `SerializerProvider`.

I should probably mark that method `@deprecated`; it can not be implemented in a way that introspection would work. But it should be made clear that method is not to be called unless caller knows exactly what it is doing.

**Comment by danielnorberg** [comment]
@cowtowncoder That seems to resolve my issue. Thanks!

**Comment by cowtowncoder** [comment]
@danielnorberg Thank you for doing the detective work here -- might have taken a while for me actually, as I wouldn't have realized the root cause immediately. I will update javadocs, and deprecate that factory method, since it will not work with 2.7, unlike earlier.

**Comment by danielnorberg** [comment]
@cowtowncoder :beers:
