### ISSUE TITLE
Add back `TypeFactory.constructType(Type, Class)` as "deprecated" in 2.7.1

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1079]
(for background, see http://stackoverflow.com/questions/34721851/spring-4-2-3-and-fasterxml-jackson-2-7-0-are-incompatible)

Due to complete rewrite of type inspection, resolution, changes were necessary to handling.
However, since some of methods removed were public and not deprecated, it would be good to go back and see if it would not be possible to add them back as deprecated in 2.7.1. While this is not as good as noticing the issue for 2.7.0, perhaps it would help reduce friction for upgrades -- it is unfortunate there was a breakage.

Related methods include:

```java
    public JavaType constructType(Type type);
    public JavaType constructType(Type type, TypeBindings bindings);
    public JavaType constructType(TypeReference<?> typeRef);
    public JavaType constructType(Type type, Class<?> context);
    public JavaType constructType(Type type, JavaType context);
```

of which it is likely that 2nd one can not be supported, but others are probably fine to keep, just discarding or ignoring contextual argument.

**Comment by todd-richmond** [comment]
This issue also broke Swagger documentation

**Comment by cowtowncoder** [comment]
@todd-richmond Ok good to know, in case that gets reported separately.
