### ISSUE TITLE
SerializerCache in SerializerProvider does not return previously cached value serializer

### ISSUE THREAD

**Issue by blackfyre512** [FasterXML/jackson-databind#1080]
We came across a performance problem while updating from jackson-databind-2.5.1 to 2.6.4
It looks like the type serializer caching mechanism in ObjectMapper.canSerialize() is not working anymore. Could be a problem with the deprecated TypeKey.

I wrote a short JUnit-Test to show the problem. When running with 2.6.4 it slows down extremely compared to 2.5.1.

```java
import java.util.stream.IntStream;

import org.junit.Test;

import com.fasterxml.jackson.databind.ObjectMapper;

public class CanSerializeTest {

    @Test
    public void canSerializeTest() throws Exception {
        long start = System.currentTimeMillis();
        ObjectMapper objectMapper = new ObjectMapper();
        IntStream.range(0, 100000).boxed().forEach(
                i -> objectMapper.canSerialize(TestBean.class));
        System.out.println(System.currentTimeMillis() - start);
    }

    static class TestBean {
        private String someString;
        private Long someLong;

        public String getSomeString() {
            return someString;
        }

        public void setSomeString(final String someString) {
            this.someString = someString;
        }

        public Long getSomeLong() {
            return someLong;
        }

        public void setSomeLong(final Long someLong) {
            this.someLong = someLong;
        }
    }
}

```

**Comment by cowtowncoder** [comment]
I think I may have fixed this particular problem not long ago, although I can not immediately find the issue number (will add if I find it). It only affected `canSerialize()`, but not actual lookup for serializer when it is used.
Would it be easy to see if `2.7.0` still has the issue? Fix would be there, if I am correct.

**Comment by blackfyre512** [comment]
You are correct, 2.7.0 does not seem to have this issue. We will try using this in our application. Thank you!

**Comment by cowtowncoder** [comment]
Ok, thank you for verifying this.
