### ISSUE TITLE
(2.8) JsonDeserializer.deserialize method signature should not throw two exceptions.

### ISSUE THREAD

**Issue by bkrisler** [FasterXML/jackson-databind#1081]
The current method signature for JsonDeserializer deserialize is:
    public abstract T deserialize(JsonParser p, DeserializationContext ctxt)
        throws IOException, JsonProcessingException;

However JsonProcessingException extends IOException, making the duplicate redundant.

**Comment by cowtowncoder** [comment]
You could argue either way. It is redundant from strict technical sense, but also gives an indication that beyond simple `IOException`, JSON processing exceptions are also thrown. So I am bit torn here as to whether this is or is not useful documentation. I have started removing latter from many/most implementation classes, but have left these for main public API classes.

So I'll have to think more about this aspect.

**Comment by cowtowncoder** [comment]
I'll change that for 2.8 for `JsonDeserializer` and `JsonSerializer`.

**Comment by cowtowncoder** [comment]
Actually, no. I think it makes sense to have both exceptions listed for documentation purposes.
