### ISSUE TITLE
Can not use static Creator factory methods for `Enum`s, with JsonCreator.Mode.PROPERTIES

### ISSUE THREAD

**Issue by dmcwhorter** [FasterXML/jackson-databind#1082]
It does work with JsonCreator.Mode.DELEGATING.

Example types and tests are available here: https://github.com/dmcwhorter/jackson-custom-enum-test

**Comment by dmcwhorter** [comment]
Related thread: https://groups.google.com/forum/#!topic/jackson-user/Yyc_RfTND5M

**Comment by cowtowncoder** [comment]
Implemented by @LokeshN, will be in 2.8.
