### ISSUE TITLE
Minor: NPE possibility in SimpleMixinResolver

### ISSUE THREAD

**Issue by ljnelson** [FasterXML/jackson-databind#1088]
See https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/introspect/SimpleMixInResolver.java#L65

If the source mixins are null, it looks to me like `NullPointerException`s will occur.

**Comment by cowtowncoder** [comment]
Better safe than sorry, thanks!
