### ISSUE TITLE
JSON de serialization issue on GWT RPC calls

### ISSUE THREAD

**Issue by satiagomunez** [FasterXML/jackson-databind#1089]
For the rest calls in GWT, POJO's was annotated as below 
```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@type")
@JsonSubTypes({
		@JsonSubTypes.Type(value = Child1.class),
		@JsonSubTypes.Type(value = Child2.class)
})
public class Parent{
...
}
```

and child as 
```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@type")
public class Child1 extends Parent {
}

```

and in the JSON response in client, we actually get the @type property and also the child fields respectively, but the when we do getClass it returns Parent.class and not the child classes. 

Can you help here.

**Comment by cowtowncoder** [comment]
It would usually make more sense to send usage questions to `jackson-user` list; issue tracker is not a good place for them.

But if you can create a unit test that shows what fails (above definitions look ok as far as they go, nothing obviously off), I can try to see if there is a bug involved, or usage needs to be modified.

**Comment by cowtowncoder** [comment]
I need a reproducible unit test; may be re-opened with one.
