### ISSUE TITLE
Merge functionality of `jackson-module-parameter-names`, dynamically

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1090]
It should be possible to start to add Java 8 support in dynamically in Jackson 2.8, but without requiring use of Java 8 -- if running on JDK 7, things should degrade gracefully.

The simplest piece of functionality to merge in should be that of `jackson-module-parameter-names` (see ../../../jackson-module-parameter-names), as it just adds discovery of parameter names.

Another thing that would go well with this would be a new `MapperFeature`, to allow changing of default handling of 1-parameter creators -- default of "delegating" could be overridable. For this, a separate issue should be filed, if and when implementing this RFE.

**Comment by lpandzic** [comment]
> except that I think it should be easy enough to just merge this completely

I don't understand the except part, you mean embedding the module into jackson databind iteself in form of code instead of autoinjecting the module?

**Comment by cowtowncoder** [comment]
@lpandzic Yes. Add the functionality directly in, instead of registering as a module.

**Comment by lpandzic** [comment]
What about Jdk8Module and JavaTimeModule?

**Comment by cowtowncoder** [comment]
@lpandzic good question. `Jdk8Module` seems small enough that either approach could work. `JavaTimeModule` is big enough that I'd like to keep it separate. But I am still not sure what's the best approach, balancing benefits of easy inclusion via frameworks vs added dependency.

What I am hoping is that getting simplest part out of the way this can be discussed on mailing list.

**Comment by cowtowncoder** [comment]
After thinking about this for a while, I decided this is NOT something I want to pursue for 2.8, either via direct inclusion, or as default module dependency.

For both cases I do not yet trust that the handling of implicit names from constructors will not change observed behavior that works according to (some) users preferences. Automatic inclusion would almost certainly break some usage.

So, ability to register (or not) module is, for now, necessary.

**Comment by apatrida** [comment]
I think you should consider the Java 8 date/time and datatype functionality being auto loaded and in main databind module.  It isn't large and for cases where people don't want large (android) it will drop out with Proguard, and I can't think of much Java 8 code that doesn't use at least one Java 8 datatype.  You basically force every java 8 one to include and register another module, and before that go through the bugs of "why doesn't this work?!?!!"

**Comment by cowtowncoder** [comment]
@apatrida I don't know. Module is big enough to enlarge codebase, and in my perfect world, I'd actually boot out some of existing earlier JDK types into a separate, general JDK module.
But if you want to bring this up on dev mailing list I am open to Vox Populi.

On Android: can Android tools take Java 8 bytecode, produce Dalvik equivalent? I think so? Problem being more with lack of Java 8 types in SDK? If so, dynamic loading should work as well as with Java 7 types.

Also... could perhaps create alternate `ObjectMapper` constructor that'd take some indicator for expected level (maybe just int, "6" for 2.6) which could forcibly prevent attempts of loading extended functionality. This could remove pesky warnings that otherwise litter Android loading.

**Comment by lpandzic** [comment]
For Android currently there are alternatives:
https://github.com/JakeWharton/ThreeTenABP
http://www.threeten.org/threetenbp/.

Note that old Date API will be deprecated possibly even with release of Java 9:
https://bugs.openjdk.java.net/browse/JDK-8065614
https://bugs.openjdk.java.net/browse/JDK-8164898

I agree with @apatrida and I believe the only question about supporting JDK 8 API is when it should be done. The longer we wait, the more it'll be needed.

**Comment by cowtowncoder** [comment]
@lpandzic @apatrida I am open to figuring out a reasonable way to include Java8 Date/Time types.
I think my main concern is not so much Android, come to think of it -- partly because adding dynamically detectable support is quite easy for this case -- and more to do with how to maintain code  base. The only trick (I think) is that the module relies on Java 8 language features (not by necessity, as far as I know, but for convenience, not unreasonably). But that aside...
(well that, and also that `jackson-jr` works on Android and should be kept Android compatible).

I am just worried that size of the source base for Java 8 types is large enough so that it would be nice to keep somehow separate.
At the same time, I do think that if we include functionality automatically, keeping it in separate jar seems unnecessary and just adding one more way things can go wrong.
So: would it be possibly to -- for example -- change build to maven multi-project, but still use a plug-in to create a single jar? If so, I could see some benefit in maybe extracting much of pre-Java8 JDK type handling into separate modules for management (working on IDE), but keeping it all in same result jar.

Also: I'll revive "When do we Java 8" thread on dev list. I know I haven't followed up on earlier myself, but I also think it is important to try to keep discussion alive.

**Comment by lpandzic** [comment]
> So: would it be possibly to -- for example -- change build to maven multi-project, but still use a plug-in to create a single jar? If so, I could see some benefit in maybe extracting much of pre-Java8 JDK type handling into separate modules for management (working on IDE), but keeping it all in same result jar.

It is possible with either Maven Shade or Maven Assembly plugin.

**Comment by apatrida** [comment]
You could also leave it multiple builds as it is now and just make the JDK 8 module a built-in dependency of data-bind, then only the auto-dynamic loader is added to the databind code. 

Really the confusion is the lack of it working out of the box, not the packaging format.

**Comment by cowtowncoder** [comment]
The problem is I don't like the idea of separate jar or necessary auto-registration any more than just including serializers/deserializers into codebase and baking it in.
There is also the chicken-and-egg problem of dependencies with loading, unless auto-discovery was used, or, more likely, just hard-coding class name and using introspection.

Actually I guess this would be problematic no matter what, unless one small glue piece was added that depends on databind and java8 module.

**Comment by cowtowncoder** [comment]
Actually maybe there is something to just adding a simple dependency and registration: but with a minor twist: instead of trying to do it all from `jackson-databind`, `ObjectMapper` -- which has the real problem of cyclic dependency -- could do following:

1. Change `jackson-databind` to multi-module project
2. Add second sub-project like `jackson-java8-databind`, which has dependency to both `jackson-databind` and java8 modules (actually, possibly it could and should directly add support for other java 8 features, `Optional` types, parameter names), and also adds `Java8ObjectMapper` with auto-registration

It could also be possible to use shading for (2) to reduce number of pieces to base `jackson-databind` and then all java8 features, but that's mostly just icing on the cake.

How would this sound? It would still allow use of "classic" `ObjectMapper`. For non-json formats it would either:

1. Expose no change, for simple formats that do not sub-class `ObjectMapper` (cbor, smile at least)
2. Be slightly cumbersome for other formats that do have optional or mandatory sub-type (mandatory for XML, optional for CSV, protobuf etc).

Some other considerations:

- It might not be immediately possible to deprecate java 8 modules, esp. if old ObjectMapper is still needed for some dataformats

**Comment by lpandzic** [comment]
I'm against new type of ObjectMapper - Java8ObjectMapper. We really need to embed java 8 functionality without changing anything for the clients. The only question is whether now is the right moment to do so. For me that was half a year ago, for @apatrida it is now and as more time passes more people will ask for this. :)

**Comment by lpandzic** [comment]
Regarding tehnical details, I'd suggest this should really be embedded into one module, otherwise partition the module by functionality. By that I mean if you want to separate datetime functionality create a new module for all datetime cases including old Date stuff etc, don't partition it by Java Version. You should also consider Java future - Java 9 and modules.

**Comment by cowtowncoder** [comment]
Most likely I'll leave this as-is for time being then. I don't have any personal upside to this, only additional work.

**Comment by cowtowncoder** [comment]
Some more thinking. Perhaps @lpandzic's original idea could work well, with possible minor changes.

One change I am thinking of is whether to try to externalize definition of which of classload-visible modules (we already have SPI via META-INF/services for all modules) should be auto-loaded.
On one hand, explicitly naming in `ObjectMapper` is simple, and probably sufficient for now (and maybe forever). On the other hand using SPI approach (new property, or maybe annotation in `Module` impl class) would be pluggable. This could be useful by allowing modules to be declared as auto-loadable.

On the other hand there is the obvious follow up concern of security. If it is possible to make things auto-loadable this opens up potential security risk; adding a new jar in classpath (via dependencies) can effect changes that would otherwise be impossible to achieve.

One thing I can do easily enough is to add `ObjectMapper` constructors that take `Module`s to register. Follow-up to that could be List/array of `String`s that define module ids of modules to load (via service discovery). Similar mechanism could then be used for default list of modules.

Yet again... it seems like lots of work for something that's really simple to do: specify modules. Jackson is designed to be extensible. One should not fear registering modules, and any framework that does not have a way to do that has a problem, regardless of whether some modules are registered by default or not.
