### ISSUE TITLE
Serialize generic JSON skip wrap

### ISSUE THREAD

**Issue by DanyAsc** [FasterXML/jackson-databind#1097]
I want to serialize my POJO class, when produce output to XML, it work perfect as what I want. But not for the JSON.

My main POJO class
![image](https://cloud.githubusercontent.com/assets/16914869/12608008/596087ac-c4d9-11e5-92ee-82c73806e791.png)

ResultDataRowItemTest class:

![image](https://cloud.githubusercontent.com/assets/16914869/12608012/62649a1e-c4d9-11e5-97c9-bd67841f2bd4.png)

RetUser class :

![image](https://cloud.githubusercontent.com/assets/16914869/12608024/6d64a346-c4d9-11e5-9407-6b764c1ccf0d.png)

Result for the XML:

![image](https://cloud.githubusercontent.com/assets/16914869/12608029/77ccdab0-c4d9-11e5-8493-a49e42e5a360.png)

Here's the result for the JSON :

![image](https://cloud.githubusercontent.com/assets/16914869/12608034/8015acf6-c4d9-11e5-90ed-69ebf51bbc54.png)

The problem is, how to remove object "item" for JSON ? So the result just like XML.

So much thanks before

**Comment by cowtowncoder** [comment]
This is more of a usage question, not a bug or request for enhancement. Please use mailing list (`jackson-user`) for such questions in future.

But as to question: you are specifying use of `@JsonTypeInfo`, in which type name is included as a wrapper JSON Object. If you do not want that, you will either need to remove polymorphic handling, or change to use different method (AS_PROPERTY for example). But if you want to combine "item" and "user", there is no way to do that. Property `item` needs to be found regardless of type; and for polymorphic type itself, id "user" is needed.
