### ISSUE TITLE
Class DOMDeserializer XXE

### ISSUE THREAD

**Issue by answer100688** [FasterXML/jackson-databind#1105]
I use jackson-databind-2.4.2 . And I find class DOMDeserializer create DocumentBuilderFactory . However , if not enabled external entity references  , it could cause Improper Restriction of XML External Entity Reference ('XXE') . I want to know weather it has been modified or not , thank you .

**Comment by cowtowncoder** [comment]
You can check out source code before filing an issue:

http://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.4.2/jackson-core-2.4.2-sources.jar

but no modifications are made for `DocumentBuilderFactory`; default instance is used as is.

**Comment by answer100688** [comment]
thank you for your reply. and I mean the latest version still has this question ? Otherwise , how could I avoid this problem ?

**Comment by cowtowncoder** [comment]
@answer100688 What is the problem?

**Comment by answer100688** [comment]
Improper Restriction of XML External Entity Reference ('XXE')

**Comment by cowtowncoder** [comment]
@answer100688 What do you consider "improper"? That word does not have clear meaning to me in this context.
Enabling expansion by default, or disabling? Both choices can have potential problems: one for security, other for failing expansion that caller would expect to happen, as per XML specification.

**Comment by answer100688** [comment]
yes , I want to disable external entity by default . I think it could avoid XXE .
