### ISSUE TITLE
Security Scan and DOMDeserializer

### ISSUE THREAD

**Issue by jprochas** [FasterXML/jackson-databind#1107]
This is identified as a potential XXE security problem in static analysis. The fix would probably be to add _parserFactory.setExpandEntityReferences(false) into the static block in the class. 
Does this appear to be an actual problem or a false positive? Would setting that setting have a negative impact on some legitimate use-case?

**Comment by cowtowncoder** [comment]
@jprochas Good questions. I would probably err on side of safety, blocking it, and if someone needs to enable it, use custom deserializer.

**Comment by cowtowncoder** [comment]
@jprochas Actually I think this is something to change (defaults that is), I just need to figure out whether it needs to be configurable, and which versions change would be in wrt backwards compatibility.
So I will probably either re-open this with rewording, or create another issue. Thank you for reporting the concern!
