### ISSUE TITLE
@JsonFormat is ignored by the DateSerializer unless either a custom pattern or a timezone are specified

### ISSUE THREAD

**Issue by aseovic** [FasterXML/jackson-databind#1109]
If the user simply specifies `@JsonFormat` annotation with string shape, the shape is ignored and the date is serialized as long:
```java
static class Person
{
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    public Date dateOfBirth;
}
```
gets serialized as:
```json
{"dateOfBirth":1198800000000}
```
I believe the correct behavior should be to write the date as a string in ISO8601 format.

If you agree I will implement the fix and create a PR for it.

**Comment by cowtowncoder** [comment]
@aseovic yes that looks like a bug.
