### ISSUE TITLE
@JsonAppend does not seem to work on mixins

### ISSUE THREAD

**Issue by benson-basis** [FasterXML/jackson-databind#1116]
PR with test case to follow. Version 2.6.2.

**Comment by benson-basis** [comment]
The code uses the value from the value= as an index into an empty map of attributes in AttributePropertyWriter. It's some sort of dynamic behavior that I'm looking for, as if instead of 'value=1.0.0' I'm supposed to say 'value="version"' and then set version=1.0.0 in as a serialization attribute.

**Comment by cowtowncoder** [comment]
@benson-basis ah. My answer on user list was actually incorrect -- indeed `value` refers to attribute that you need to set, and `propName` is the name of JSON property to output.
`TestVirtualProperties` shows actual usage.
