### ISSUE TITLE
Cannot ignore a property that comes in through an `@JsonCreator`

### ISSUE THREAD

**Issue by bimargulies** [FasterXML/jackson-databind#1118]
Version 2.6.3.

If a class is set up to only be constructed via an @JsonConstructor, then you can't ignore a single incoming property. 

It doesn't work to add @JsonIgnore to a setter, since the setters aren't relevant.

It doesn't work to add @JsonIgnoreProperties({"foo"})

to the constructor, even though the doc sort of hints that this will work.

**Comment by cowtowncoder** [comment]
Interesting. Thank you for reporting things.

**Comment by cowtowncoder** [comment]
Just to make sure: do you mean that value will be passed to constructor parameter, even if `@JsonIgnore` is present? (or `@JsonIgnoreProperties`)

**Comment by bimargulies** [comment]
So, with plain @JsonIgnore, I got errors that it could not find a suitable
constructor (presumably because it was trying to find one that would accept
the parameter).

With @JsonIgnoreProperties in the class, it stifled both output and input

With @JsonIgnoreProperties on the constructor, I later discovered that I
spelled it wrong, so I honestly don't know what it does, since I
subsequently gave up and just added the parameter to the ctor.

**Comment by cowtowncoder** [comment]
@bimargulies Ok. I can try to cobble together a test case, just want to try to recreate specific issue you had.

For what it is worth there are some known issues wrt discovery of Json Creator properties -- problem is that handling for those differs from field/method accessors, due to two-level structure (constructor, its parameters), and due to discovery itself happening at distinct phases that are no unfortunately fully synchronized. Chances are this may be producing problems you observe, along others.
This just as background; I will need to rewrite the handling at some point (was hoping for 2.7, did not happen).

Or it could be something simpler too. Test case tends to help hunt down root cause.

**Comment by benson-basis** [comment]
I'll get to it. I've been in London being run ragged.

**Comment by cowtowncoder** [comment]
@benson-basis sorry did not mean to push here -- I am time-crunched myself, vacation starting tomorrow. You have contributed so much value that I do not want to give any impression of pushing for more here.

**Comment by tristanlins** [comment]
Hi there, the issue still seams to be exists.

Here is a minimal junit example:

```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Minimal {

    @JsonPropertyOrder({"id", "name"})
    public static class Immutable {
        @JsonProperty
        private final String name;

        @JsonCreator
        @JsonIgnoreProperties({"id"})
        public Immutable(@JsonProperty("name") String name) {
            this.name = name;
        }

        @JsonProperty
        public String getId() {
            return name.toLowerCase();
        }

        public String getName() {
            return name;
        }
    }

    @Test
    public void testSerializeation() throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();

        Immutable immutable = new Immutable("ACME");
        String json = objectMapper.writeValueAsString(immutable);
        assertEquals("{\"id\":\"acme\",\"name\":\"ACME\"}", json);

    }

    @Test
    public void testDeserialization() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();

        final Immutable immutable = objectMapper.readValue("{\"id\":\"acme\",\"name\":\"ACME\"}", Immutable.class);
        assertEquals("ACME", immutable.getName());
    }

}
```

The `testSerializeation()` succeed, but `testDeserialization()` fails with a `UnrecognizedPropertyException: Unrecognized field "id"`.
Moving `@JsonIgnoreProperties({"id"})` to the class level works only for deserialization. Then the serialization wont work as expected.

The only working solution is to set `@JsonIgnoreProperties(ignoreUnknown = true)` at class level.

**Comment by cowtowncoder** [comment]
@tristanlins your usage of `@JsonIgnoreProperties` seems wrong to me... I assume intention would be that ignoral for type `Immutable`, but for that it has to be added to the class, not constructor.
If added to a getter/setter, it would attach to that value; but there is no defined semantics for adding it to Creator method (constructor). Such usage should probably be removed if possible.

So, usage on class should work; but on constructor it does not.

**Comment by tristanlins** [comment]
If `@JsonIgnoreProperties({"id"})` is used on class level, then the `getId()` method is ignored while serialization. That's not what I expect.
However, if  `@JsonIgnoreProperties(ignoreUnknown = true)` is used then it works as expected.

> Such usage should probably be removed if possible.

In my opinion, that is a valid use case. Maybe also an edge case.
I often use immutable classes when I work with REST Services. In my particular case, I have an ID that is composed of several fields. That is, the ID is relevant to the JSON or REST service. But not for the Java model. So this ID field must be generated during serialization, but can be ignored during deserialization.

I just run into this problem and found this issue.
As already said, using `ignoreUnknown = true` works fine.
If this type of usage is not supported, Jackson may throw an exception when using the annotation on the constructor.

**Comment by cowtowncoder** [comment]
If a property is to be ignored, it will be ignored, serialization and deserialization. But if you want only one or the other, there are `allogSetters` / `allowGetters` to change this to only ignore on one direction.

What I mean by "should be removed" only means that "use of `@JsonIgnoreProperties` does not work for Constructor itself, so do not try to use it", nothing more.
So not saying that what you are trying to do is not valid, just that the way you try to use is not valid and is not supported. It is unfortunate that currently compiler does not prevent this usage; I think this is my bad -- annotation should NOT have `ElementType.CONSTRUCTOR` included as `@Target`.
I will remove this target from 3.0, but for backwards compatibility it unfortunately can not occur in patches.

I hope this clarifies things?

Now. Back to how to do what you want (which I agree is a valid use case), I think combination of `@JsonIgnoreProperties` on class `Immutable`, and then either property `allowGetters`, or explicit `@JsonProperty` on `getId()` should work. Unless I am missing something.

**Comment by tristanlins** [comment]
Sounds plausible, thanks for the explanation.

> or explicit `@JsonProperty` on `getId()` should work. Unless I am missing something.

Unfortunately, this does not work, I had already tried in my example above.

> I think combination of `@JsonIgnoreProperties` on class `Immutable`, and then either property `allowGetters`

`allowGetters` leads to success! Then `@JsonProperty` on getter can be left out. Here is my version:

```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Minimal {

    @JsonPropertyOrder({"id", "name"})
    @JsonIgnoreProperties(value={"id"}, allowGetters=true)
    public static class Immutable {
        @JsonProperty
        private final String name;

        @JsonCreator
        public Immutable(@JsonProperty("name") String name) {
            this.name = name;
        }

        public String getId() {
            return name.toLowerCase();
        }

        public String getName() {
            return name;
        }
    }

    @Test
    public void testSerializeation() throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();

        Immutable immutable = new Immutable("ACME");
        String json = objectMapper.writeValueAsString(immutable);
        assertEquals("{\"id\":\"acme\",\"name\":\"ACME\"}", json);

    }

    @Test
    public void testDeserialization() throws IOException {
        ObjectMapper objectMapper = new ObjectMapper();

        final Immutable immutable = objectMapper.readValue("{\"id\":\"acme\",\"name\":\"ACME\"}", Immutable.class);
        assertEquals("ACME", immutable.getName());
    }

}
```

Thank you again for the patience :-)

**Comment by eustimenko** [comment]
Hello, guys. I have the same [issue](https://stackoverflow.com/questions/49940537/jackson-could-not-ignore-properties).

**Comment by cowtowncoder** [comment]
Not quite sure what could be done here, will close: may be re-filed with up-to-date reproduction against 2.16.0 or later, and specific request for change.
