### ISSUE TITLE
String value omitted from weirdStringException

### ISSUE THREAD

**Issue by benson-basis** [FasterXML/jackson-databind#1120]
2.6.2

Code calls:

```
throw ctxt.weirdStringException(version, String.class, String.format("Incompatible ADM version %s", version));
```

Result:

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.String from String value '[N/A]': Incompatible ADM version 2.0.0
 at [Source: { "version": "2.0.0" }; line: 1, column: 3] (through reference chain: com.basistech.rosette.dm.AnnotatedText["version"])
```

I claim that N/A should be '2.0.0' (the contents of 'version').

**Comment by cowtowncoder** [comment]
Probably. I just need bit more context here (or PR etc).

**Comment by benson-basis** [comment]
@cowtowncoder , doesn't the comparison of the Java code and the exception message leave you unsatisfied? Where does the N/A come from?

I'll set up a PR or at least a pointer to an available test case in the next few days.

**Comment by cowtowncoder** [comment]
@benson-basis At this point I have enough things to work on that while improvements here would be useful, I don't go looking at source code right away. That's all. :)
I do go through backlog every now and then and at that point would figure it out. But I still try to add some comment to indicate I have noticed the filing.

**Comment by benson-basis** [comment]
OK, I get it. I'll see if I can set you up a patch.

**Comment by cowtowncoder** [comment]
Ah. I can see the issue... yes. Will patch it.
