### ISSUE TITLE
JsonAnyGetter ignores JsonSerialize(contentUsing=...)

### ISSUE THREAD

**Issue by pirkogdc** [FasterXML/jackson-databind#1124]
version: 2.7.0

it seems I can use `@JsonSerialize(using=...)` for the whole map, but I can't find working solution to use custom serializer for values only.

**Comment by cowtowncoder** [comment]
Sounds like a bug, missing handling of expected way to customize handling. Thank you for reporting this.

**Comment by cowtowncoder** [comment]
Yes, I can reproduce this.

**Comment by cowtowncoder** [comment]
Finally had time to dig in here. And, even better, this was one of those good old-time bugs that was NOT super difficult to solve in the end. So will be fixed in 2.7.2.
