### ISSUE TITLE
JsonProperty on constructors has effects on Serialization

### ISSUE THREAD

**Issue by mgius** [FasterXML/jackson-databind#1131]
When JsonProperty annotations are present on a constructors arguments this seems to have inconsistent affects on an objects Serialization configuration.  Specifically, when the following is true:

1. A JsonProperty annotation is present on a constructor argument AND
2. The value of that annotation matches the name of a Field on the class (regardless of the name of the argument)

The Serialization configuration of the object is modified in the same way that having the JsonProperty annotation on the Field itself would modify it.  

I think this is a bug for two reasons.  First, I would not expect that a JsonProperty on a constructor argument would have an affect on the Serialization configuration of an object.  And Second, it is incredibly confusing for the annotation to have an affect on Serlialization only when it happens to match up with a field name on the class and not under any other circumstances.

Uploaded the 2.7.1 test case here: https://gist.github.com/mgius/aa4f2a54fbbcd348196a

Tested against Jackson 2.6.3 and Jackson 2.7.1 using java version "1.8.0_45"

**Comment by mgius** [comment]
FWIW: I'm not expecting that having a JsonProperty on a constructor with a Builder makes any sort of sense (it was a legit bug in our code after a refactor) but I find it incredibly odd that this annotation on a constructor has Serialization consequences instead of just Deserialization consequences.

**Comment by cowtowncoder** [comment]
@mgius handling of properties unifies annotations from multiple accessors (setters, getters, fields, constructor parameters). This is mostly to support common case where both are needed; and many users actually prefer only adding annotations in constructor parameters. Others prefer to do that for getters; and some on fields. So the part about annotations for one side affecting the other aspect is a feature, not bug.

If you do not want to serialize property, but do want to deserialize, this can be achieved in couple of ways. One is to use "split" set up, where one accessor is included with `@JsonProperty`, other excluded with `@JsonIgnore`.
Another would be by using "access" property of `@JsonProperty`, like `@JsonProperty(access=Access.WRITE_ONLY)`

Another thing I notice is the use of naming strategy: this should only affect implicitly named properties.
However, used of `@JsonProperty` marks explicit name, one that should not (by default) be modified by naming strategy. In sample case that would mean that only property "someValue" would be recognized. In that sense, shouldn't property naming be done using:

```java
private Model(@JsonProperty("someValue") String matchingArgument) {
}
```

But in the end I am actually not 100% sure what you consider the specific problem, regarding setup.
What would the expected JSON input and output be?

**Comment by mgius** [comment]
I think I may have filed a single issue for two separate confusions.  The first confusion, JsonProperty behavior on a constructor, seems to be intended behavior.  The other is that this behavior seems to be different depending on the value in the JsonProperty. 

I found it confusing that this:

```java
private Model(@JsonProperty("someValue") String matchingArgument) {
}
```

Has different behavior than this:

```java
private Model(@JsonProperty("anotherValue") String matchingArgument) {
}
```

I've added a second file to my gist detailing my confusion about the behavior different between these two annotations.

https://gist.github.com/mgius/aa4f2a54fbbcd348196a#file-jacksonbug2-java

**Comment by cowtowncoder** [comment]
@mgius I'm sorry but I am not sure what the confusion in that gist is about. In one, you are using different names for different pieces (constructor parameter vs field/methods), in one same names. That will affect inference of properties that POJO has, yes. But what is the part that you disagree about?

**Comment by cowtowncoder** [comment]
I am not quite sure what the remaining concern is; that properties are affected by annotations on all related accessors (setters, getters, fields, creator parameters) is intentional; and at most we could try to improve documentation where possible (always a good goal). Beyond this I think a new issue would be needed, if there are specific suggestions for changing behavior.
