### ISSUE TITLE
Distinction between missing JsonTypeId and unrecognized JsonTypeId.

### ISSUE THREAD

**Issue by benbarkay** [FasterXML/jackson-databind#1138]
I am using `JsonTypeId` for document versioning in my use case.

To me, a missing `JsonTypeId` means that the document is not versioned, and belongs to an older version of the software, which I can then deserialize to a known object that will handle the schema. An existing but unrecognized `JsonTypeId` means that the document was edited or created with a software of newer version than the one currently reading the document, thus its schema cannot be reasonably handled by the current, older version software.

Despite that this use case might be a special one, I think that it would be correct to allow for such distinction between missing and unrecognized `JsonTypeId` instead of combining the two situations to mean the same thing by using `defaultImpl`, because these don't mean the same thing.

**Comment by cowtowncoder** [comment]
What would you propose to be done here to support such distinction, from user perspective?
