### ISSUE TITLE
Serializations fails with JaxbAnnotation Introspector and intermediary objects

### ISSUE THREAD

**Issue by jej2003** [FasterXML/jackson-databind#1143]
I have some JAXB annotated classes that I'm using the JaxbAnnotation Intospector with that generally speaking works well, but when I have an intermediary object being created that then has a simple string value I have issues converting to JSON.  A sample snippet demonstrating the problem is shown below.

Should this work or am I misusing something?

The exception is

com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class java.lang.String and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: jackson.DTO["map"]->jackson.Intermediary["entry"]->java.util.ArrayList[0]->jackson.IntermediaryEntry["value"])

`public class TestClass {

    @Test
    public void test() throws Exception {
        DTO d = new DTO();
        d.map = new HashMap<>();
        d.map.put("key", "value");

        ObjectMapper mapper = new ObjectMapper();
        mapper.setAnnotationIntrospector(new JaxbAnnotationIntrospector(mapper.getTypeFactory()));

        mapper.writeValueAsString(d);
    }

    static public class MapAdapter extends XmlAdapter<Intermediary, Map<String, Object>> {

        @Override
        public Intermediary marshal(Map<String, Object> v) throws Exception {
            if(v == null) {
                return null;
            }
            Intermediary i = new Intermediary();
            for(Entry<String, Object> entry : v.entrySet()) {
                i.add(new IntermediaryEntry(entry));
            }

            return i;
        }

        @Override
        public Map<String, Object> unmarshal(Intermediary v) throws Exception {
            Map<String, Object> obj = new HashMap<>();
            if(v != null &&  v.entries != null) {

                for (IntermediaryEntry e : v.entries) {
                    obj.put(e.key, e.value);
                }
            }
            return Collections.unmodifiableMap(obj);
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    static public class Intermediary {
        @XmlElement(name="entry")
        List<IntermediaryEntry> entries;
        public void add(IntermediaryEntry e) {
            if(entries == null) {
                entries = new ArrayList<>();
            }
            entries.add(e);
        }
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    static public class IntermediaryEntry {
        String key;
        @XmlJavaTypeAdapter(PrimitiveStringOrDateAdapter.class)
        Object value;
        public IntermediaryEntry() {

        }
        public IntermediaryEntry(Entry<String, Object> entry) {
            this.key = entry.getKey();
            this.value = entry.getValue();
        }
    }

    static public class PrimitiveStringOrDateAdapter extends XmlAdapter<Object, Object> {
        @Override
        public Object unmarshal(Object v) throws Exception {
            if(v instanceof XMLGregorianCalendar) {
                return  ((XMLGregorianCalendar)v).toGregorianCalendar().getTime();
            }
            return v;
        }

        @Override
        public Object marshal(Object v) throws Exception {
            return v;
        }
    }

    public class DTO {
        @XmlElement
        @XmlJavaTypeAdapter(MapAdapter.class)
        Map<String, Object> map;
    }
}`

**Comment by cowtowncoder** [comment]
@jej2003 Since this sounds like JAXB annotation handling issue, could you please re-file at:

https://github.com/FasterXML/jackson-module-jaxb-annotations/issues

I would move this myself, but github does not seem to have transfer functionality, and it is best if authorship is retained.

**Comment by jej2003** [comment]
Moved, thanks @cowtowncoder
