### ISSUE TITLE
Support escaping slash (solidus) character

### ISSUE THREAD

**Issue by ikeyat** [FasterXML/jackson-databind#1145]
As the following RFC spec says, slash ``/`` (solidus) is a character to be escaped.
https://tools.ietf.org/html/rfc4627
https://tools.ietf.org/html/rfc7159

As discussed [here](http://stackoverflow.com/questions/6817520/escape-forward-slash-in-jackson) some developers want Jackson to support escaping slash character (by default or as an option).
It is necessary when a client is implemented in javascript and need to receive ``</javascript>`` as JSON.

**Comment by cowtowncoder** [comment]
Solidus may be escaped yes. This is possible to do using `CharacterEscapes` interface for custom escaping. Since there are many aspects to escaping that users may want to change, general-purpose extensibility like this seems the best way to go.

What else did you have in mind here?

**Comment by ikeyat** [comment]
In my opinion, escaping solidus should be embedded in Jackson itself as other characters such as reverse solidus ``\`` and quotation mark ``"`` etc...
Of course ``CharacterEscapes`` extension is a good solution for escaping characters that are not specified in RFC.

A similar discussion is found on gson community.
https://github.com/google/gson/issues/356

**Comment by cowtowncoder** [comment]
@ikeyat I disagree. JSON specification specifically does not require escaping of this character, so I do not think Jackson should do that by default. As such I have no plans on changing it to be escaped (in all likelihood changing that would get us a few more bug reports, based on history). Specification merely allows escaping using short notation instead of Unicode escape.

**Comment by cowtowncoder** [comment]
Since `CharacterEscapes` allows users to enforce escaping, and since no additional suggestions have been added for simple improvements, I'll close this issue for now; I don't think adding one-off flags (`JsonGenerator.Feature`) makes sense in this case.

**Comment by ikeyat** [comment]
I was sad for your decision, but I got it.

> JSON specification specifically does not require escaping of this character,

I could not find it in the RFC. I believe solidus should be escaped  but not be escaped conventionally in the real world.
I understood the impact of the default change, so I think ``JsonGenerator.Feature`` approach sounded good for this problem.
