### ISSUE TITLE
Support @JsonValue on enum literals

### ISSUE THREAD

**Issue by Raniz85** [FasterXML/jackson-databind#1148]
To have custom serialisation names for enums using *@JsonValue* we can currently do this:

```
public enum Test {
    FOO("foo"),
    BAR("bar"),
    FOO_BAR("somethingElse");

    private final String representation;

    private Test(String representation) {
        this.representation = representation;
    }

    @JsonValue
    public String getRepresentation() {
        return representation;
    }
}
```

However, I would like to be able to do something like this instead to reduce the amount of code required to implement this:

```
public enum Test {
    @JsonValue("foo") FOO,
    @JsonValue("bar") BAR,
    @JsonValue("fooBar") FOO_BAR;
}
```

Since *@JsonValue* already takes an argument called *value* I guess a new argument would be required to preserve backwards-compatibility, making it `@JsonValue(jsonValue="foo")` instead.

Another option would be to add a new annotation called *@JsonEnumValue* for this specific purpose.

**Comment by cowtowncoder** [comment]
@Raniz85 even better, you can already use `@JsonProperty` that way:

```java
public enum Test {
    @JsonProperty("foo") FOO,
    @JsonProperty("bar") BAR,
    @JsonProperty("fooBar") FOO_BAR;
}
```
