### ISSUE TITLE
UnrecognizedPropertyException thrown on following element, when empty list without <list/> item present

### ISSUE THREAD

**Issue by arberg** [FasterXML/jackson-databind#1151]
Under some apparently special circumstances I'll get the error 

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "central" (class model.Host), not marked as ignorable (4 known properties: "port", "centraler", "name", "url"])
at [Source: java.io.StringReader@307f6b8c; line: 16, column: 2] (through reference chain: model.AppSetup["hosts"]->Object[][0]->model.Host["central"])

when I have XML like this

```xml
<appsetup>
	<hosts>
		<host name="bnr" url="x.x.x.x" port="8080">
			<centraler>
				<central name="BNR Taxa">
					<vehicletypes>
						<vehicletype >
							<capability category="A" name="childseat" />
						</vehicletype>						
						<vehicletype name="largevehicle">
						</vehicletype>
					</vehicletypes>
				</central>
				<central name="BNR Taxa" automatic="true">
				</central>
			</centraler>
		</host>
	</hosts>

```

If the second vehicletype 
1) does not contain an attribute, or 
2) closes like this <vehicletype name="largevehicle"/>, or
3) has a capability <capability category="A" name="childseat" /> or <capability />
then it parses correctly

It is also a requirement that its in a 'centraler' list, if I just parse the 'central' it does not fail, even when I add a tag after vehicletypes that make the above fail earlier. It seems Jackson is in a state where it will fail at the next opening element after parsing the last vehicletype.

I can supply a small test which contains the problem. Its written as an Android junit test, but is self-contained.

I use these libs (I don't know if that might be relevant). Tested on version jackson 2.7.2.

```
    testCompile 'junit:junit:4.12'
    compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:+'
// for pretty print
    compile 'org.codehaus.woodstox:woodstox-core-asl:+'
// does not have pretty print, but still has bug
//    compile 'javax.xml.stream:stax-api:+'

    compile 'com.fasterxml.jackson.core:jackson-core:+'
    compile 'com.fasterxml.jackson.core:jackson-annotations:+'
    compile 'com.fasterxml.jackson.core:jackson-databind:+'
```

Best Alex

**Comment by cowtowncoder** [comment]
Ok. I would need to see Java classes as well, to reproduce the problem.

**Comment by cowtowncoder** [comment]
Also, this really needs to go under https://github.com/FasterXML/jackson-dataformat-xml/issues

**Comment by arberg** [comment]
Thank you for link. I have copied issue to dataformat issue list, added link to sourcecode.
