### ISSUE TITLE
How to deserialize enum which implements generic interface in jackson?

### ISSUE THREAD

**Issue by GoldyMark** [FasterXML/jackson-databind#1157]
> Related question: [How to abstractly deserialize different enum types with Jackson based on common field?](http://stackoverflow.com/questions/29720532/how-to-abstractly-deserialize-different-enum-types-with-jackson-based-on-common)

### Question:
I want a simple way to achieve **custom** serialize / deserialize some enums which implements ``JSONEnum<T>``.

Now, I completed serialize, but fail on deserialize(**look at below codes**).

BTW, I know that ``@JsonValue`` and ``@JsonCreator`` can solve my problem, but TestEnum.java is unmodifiable, I can't add any annotation on it.

---
### Code:

**JSONEnum.java**

    public interface JSONEnum<T> {
        Object toJSON();
    
        T fromJSON(String value);
    }

**TestEnum.java**

    @AllArgsConstructor
    @Getter
    //@JsonDeserialize(using = JSONEnumDeserializer.class)
    public enum TestEnum implements JSONEnum<TestEnum> {
        NONE(-1),
        TYPE1(1),
        TYPE2(2);
    
        private int id;
    
        public static TestEnum getById(int id) {
            for (TestEnum testEnum : values()) {
                if (testEnum.getId() == id) {
                    return testEnum;
                }
            }
            return NONE;
        }
    
        @Override
        public Object toJSON() {
            if (this.equals(NONE)) {
                return null;
            }
            return id;
        }
    
        @Override
        public TestEnum fromJSON(String value) {
            return getById(Integer.valueOf(value));
        }
    }

**JSONEnumSerializer.java**

    public class JSONEnumSerializer<E extends JSONEnum<E>> extends JsonSerializer<JSONEnum<E>> {
        @Override
        public void serialize(JSONEnum<E> value, JsonGenerator jgen, SerializerProvider provider) throws IOException {
            jgen.writeObject(value.toJSON());
        }
    }

**JSONEnumDeserializer.java**

    public class JSONEnumDeserializer<E extends JSONEnum<E>> extends JsonDeserializer<E> implements ContextualDeserializer {
        private E target;
    
        @Override
        public E deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
            return target.fromJSON(p.getText());
        }
    
        @Override
        @SuppressWarnings("unchecked")
        public JsonDeserializer<E> createContextual(DeserializationContext ctxt, BeanProperty property) throws JsonMappingException {
            Class<E> clazz = (Class<E>) ctxt.getContextualType().getRawClass();
            target = clazz.getEnumConstants()[0];
            return this;
        }
    }

**Test.java**

    public class Test {
        @Test
        public void test8() throws IOException {
            Jackson2ObjectMapperFactoryBean bean = new Jackson2ObjectMapperFactoryBean();
    
            HashMap<Class<?>, JsonSerializer<?>> serializers = Maps.newHashMap();
            serializers.put(JSONEnum.class, new JSONEnumSerializer<>());
            bean.setSerializersByType(serializers);
    
            HashMap<Class<?>, JsonDeserializer<?>> deserializers = Maps.newHashMap();
            deserializers.put(JSONEnum.class, new JSONEnumDeserializer<>());
            bean.setDeserializersByType(deserializers);
    
            bean.afterPropertiesSet();
            ObjectMapper objectMapper = bean.getObject();
    
            String type1 = objectMapper.writeValueAsString(TestEnum.TYPE1);
            System.out.println(type1);      // It's ok here, print 1
            TestEnum type2 = objectMapper.readValue("2", TestEnum.TYPE2);
            System.out.println(type2);      // fail, throw Exception.
        }
    }

After trace source code, and I find **line 370** in ``com.fasterxml.jackson.databind.deser.DeserializerCache``, it will judge was not enum type first, and ignore my custom deserializer`(deserializers.put(JSONEnum.class, new JSONEnumDeserializer<>());`).

How to solve this problem?

**Comment by cowtowncoder** [comment]
First of all, having generic parameter for an `Enum` should not make any difference: deserializers are matched (by default) based on type-erased `Class`. So if you have custom deserializer registered for `JSONEnum.class`, that will be used. Similarly, an `enum` implementing an interface will not have any effect either by default (Jackson will only consider enum type) or with respect to choosing custom deserializer.

However, your code does not show how you are registering deserializers so it is difficult to say what is going on. One thing to note is, however, that you MUST register ALL deserializers and serializers before any use -- it is not possible to change registrations after calling `readValue()`. So perhaps this is causing an issue?

**Comment by GoldyMark** [comment]
@cowtowncoder 
Thanks for your reply.

This is my test case, correct?
**Test.java**
```java
HashMap<Class<?>, JsonDeserializer<?>> deserializers = Maps.newHashMap();
deserializers.put(JSONEnum.class, new JSONEnumDeserializer<>());
bean.setDeserializersByType(deserializers);
```

If I uncomment the ``@ JsonDeserialize`` line in **``TestEnum.java``**, no matter register ``JSONEnumDeserializer`` or not, it works fine. 
However, I could not modify **``TestEnum.java``** in my real project. That's why I make a custom deserializer.

**Comment by cowtowncoder** [comment]
@GoldyMark yes, but what does `bean.setDeserializersByType(deserializers);` do? I assume it's defined in `Jackson2ObjectMapperFactoryBean`, and may try to set deserializer when called. If so, code is broken as it would try to add deserializer after using `ObjectMapper`: this will not work, and in practice will just use whatever deserializer was in use first time given type was deserialized.

**Comment by cowtowncoder** [comment]
Also: which Jackson version?

**Comment by GoldyMark** [comment]
@cowtowncoder 
Version: 2.6.1

When I config the JSONEnumDeserializer in Spring, I found that `createContextual ` method only called once. The `target` will be resolved to first `E` type enum and will not changed anymore. 
I'm curious is there a way to get `JavaType` in `deserialize ` method? 

This is my spring config(version:4.2.1.RELEASE):
```xml
        <mvc:annotation-driven conversion-service="conversionService">
        <mvc:message-converters register-defaults="true">
            <bean class="org.springframework.http.converter.json.MappingJackson2HttpMessageConverter">
                <property name="objectMapper">
                    <bean class="org.springframework.http.converter.json.Jackson2ObjectMapperFactoryBean">
                        <property name="serializationInclusion" value="NON_NULL"/>
                        <property name="serializersByType">
                            <map key-type="java.lang.Class">
                                <entry key="com.test.JSONEnum">
                                    <bean class="com.test.JSONEnumSerializer"/>
                                </entry>
                            </map>
                        </property>
                        <property name="deserializersByType">
                            <map key-type="java.lang.Class">
                                <entry key="java.lang.Enum">
                                    <bean class="com.test.JSONEnumDeserializer"/>
                                </entry>
                            </map>
                        </property>
                    </bean>
                </property>
            </bean>
        </mvc:message-converters>
    </mvc:annotation-driven>
```

**Comment by cowtowncoder** [comment]
createContextual() should only be called once per property for which given deserializer is needed: resulting deserializer is then cached for efficiency. There is no point, either, as static information from property can not change.
If you want to retain type, you will need to keep track of it either via constructor (when originally created), or through `createContextual`.

At this point I do not see a problem in Jackson itself: it seems likely that Spring mapping of custom deserializer does not take effect. This is something that Spring component you are using needs to handle somehow; or you need to override/bypass its handling. Jackson does allow registration of deserializer by any type, enum or not.

**Comment by GoldyMark** [comment]
@cowtowncoder 
OK, I continue to study it. Thx.

**Comment by jmayday** [comment]
This seems overcomplicated to me. I'm a little bit surprised, because I thought I need both @JsonValue and @JsonCreator annotations to control serialization/deserialization but I need only @JsonValue.

Consider this code:
```
@AllArgsConstructor
@Getter
public enum TestEnum  {
    NONE(-1),
    TYPE1(1),
    TYPE2(2);

    private int id;

@JsonValue
public int id() {
return id;
}

// leave this if you really need it - but it's not required for deserialization
    public static TestEnum getById(int id) {
        for (TestEnum testEnum : values()) {
            if (testEnum.getId() == id) {
                return testEnum;
            }
        }
        return NONE;
    }

}
```

As you see only @JsonValue is there and both serialization and deserialization works. I'm using Jackson in version 2.6.1

**Comment by cowtowncoder** [comment]
@jmayday Yes, thank you for pointing this out.
Support for using `@JsonValue` also for deserialization was indeed added at some point to reduce duplication; while I can't find the issue (closes I saw was #594) it's been there for a while and definitely in 2.6.

**Comment by arashsoft** [comment]
@GoldyMark, Could you find any solution for your issue? I am facing exact same issue.

**Comment by GoldyMark** [comment]
@arashsoft No, nothing... :-(
