### ISSUE TITLE
-0.0 converts to 0.0 during deserialization

### ISSUE THREAD

**Issue by prachiibm** [FasterXML/jackson-databind#1159]
I am deserializing a simple object which has some values as -0.0, those values get converted to
-0.0 during deserialization.

```java
import java.util.List;

public class TestSet
{
    private String setName;

    List<Object[]> rows;

    public List<Object[]> getRows()  {
        return rows;
    }

    public void setRows(List<Object[]> rows)  {
        this.rows = rows;
    }

    public String getSetName() {
        return setName;
    }

    public void setSetName(String setName) {
        this.setName = setName;
    }
}
```

On serialization every thing is ok, below is the serialized string

```java
String testsetJSON = objectMapper.writeValueAsString(testSet);
```

```json
{"setName":"Test Set","rows":[[-3.677],[-3.677],[-3.677],[-3.677],[-3.677],[-3.677],[-0.0],[-0.0],[-0.0],[-0.0]]}
```

on deserialization 

```java
TestSet testSet2 = objectMapper.readValue(testsetJSON.getBytes("utf-8"), TestSet.class);
```

 all -0.0 get converted to 0.0

Also on examining the node here,i see the -0.0 are converted to 0.0

```java
 JsonNode obn = objectMapper.readTree(testsetJSON.getBytes("utf-8"));
```

```json
{"setName":"Test Set","rows":[[-3.677],[-3.677],[-3.677],[-3.677],[-3.677],[-3.677],[0.0],[0.0],[0.0],[0.0]]}
```

**Comment by cowtowncoder** [comment]
I would need full test case here, given that inexact typing (as `Object`) is used, and it is necessary to know in what form does the input come as. Similarly it is necessary to know how access from tree is made (direct get, or trying to serialize as text?)

**Comment by prachiibm** [comment]
I have a test case in which my incoming dataset contains both double and BigDecimal, if i preserve 
BigDecimal ,the -0.0 change to 0.0, which i know is expected. If i preserve double i lose precision in BigDecimal. Is there a way to preserve both double (-0.0) and
BigDecimal precision?

 public void getDataset() throws UnsupportedEncodingException, IOException
    {
        List<Object[]> testDataSet = new ArrayList<Object[]>();
        Object[] row = new Object[2];
        row[0] = -0.0d;
        row[1] = new BigDecimal(10.0000000000001225686219186172820627689361572265625);
        testDataSet.add(row);

        ObjectMapper objectMapper;
        objectMapper = new ObjectMapper();
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        objectMapper.setNodeFactory(JsonNodeFactory.withExactBigDecimals(true));
        // objectMapper.configure(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS, true);
        objectMapper.configure(DeserializationFeature.USE_BIG_INTEGER_FOR_INTS, true);
        TestSet testSet = new TestSet();
        testSet.setSetName("Test Set");
        testSet.setRows(testDataSet);
        String testsetJSON = objectMapper.writeValueAsString(testSet);
        /* {"setName":"Test Set","rows":[[-0.0,10.0000000000001225686219186172820627689361572265625]]} */
        JsonNode jsonNode = objectMapper.readTree(testsetJSON.getBytes("utf-8"));
        /* {"setName":"Test Set","rows":[[-0.0,10.000000000000123]]} */
        TestSet testSet2 = objectMapper.readValue(testsetJSON.getBytes("utf-8"), TestSet.class);
    }

**Comment by cowtowncoder** [comment]
Jackson does not do any additional conversions beyond using standard mechanisms for converting between `double` and `BigDecimal`, so it seems likely JDK methods do not retain sign for `-0.0d`.
As to preserving both types, there is nothing in a simple array of JSON values to tell which values should be considered `double`, which `BigDecimal`, nor can I think of useful heuristics.

But perhaps you can implement a custom serializer/deserializer for type `Object[]`, to handle logics specific to your use case?

**Comment by cowtowncoder** [comment]
Not sure there is anything I can do wrt Jackson here.
