### ISSUE TITLE
How to get back old way of mapping Properties objects

### ISSUE THREAD

**Issue by ehardy** [FasterXML/jackson-databind#1160]
Hi,

Since jackson-databind 2.6.0, the behaviour for mapping Properties objects has changed, jackson assumes that all the values contained by the Properties object are Strings. Good or bad, our application needs to map Properties objects that can have values of mixed type. If we use Map<String, Object> instead of Properties, everything works fine, but unfortunately we can't make the change easily at this moment. I'm sure there is a way to override the mapper for Properties objects with the mapper for Maps but I can't find how. 

Our code simply calls ObjectMapper.writeValueAsString(properties) and ObjectMapper.readValue(json, Properties.class) at the moment.

Could someone provide guidance? Thanks

Etienne

**Comment by cowtowncoder** [comment]
This would be good question for mailing list (`jackson-user` Google group).

I am of opinion that using key or value type other than `String` for properties is a particularly bad idea, and was not aware of anyone doing that on purpose (I have seen it as a bug before).

But at this point the way to solve that would be to write and register a custom serializer. I am not aware of other ways to change behavior.

**Comment by cowtowncoder** [comment]
FWIW, as per Javadocs:

```
The Properties class represents a persistent set of properties. The Properties can be saved to a stream or loaded from a stream. Each key and its corresponding value in the property list is a string. 
```

so from my perspective, usage with non-key values is not supported, while it is technically possible (I recall having a bug once due to accidental inclusion via `put` method).

**Comment by ehardy** [comment]
I understand that putting something other than Strings as values in a Properties is not the best thing to do, but we're in a bit of bind here, as we can't easily change that at the moment. We had to upgrade from jackson-databind 2.4.0 to 2.7.2 for another issue, that's why we noticed the change in behavior in Jackson when it comes to Properties mapping.

I'll ask the question on the Google group. Thanks

**Comment by cowtowncoder** [comment]
@ehardy One challenge here is that `Properties` is not abstract; otherwise it would actually be easy to map that type to, say, `Map`.

Actually, come to think of that, what might work would be to tag:

```
@JsonSerialize(as=Map.class)
```

next to `Properties` valued property. That should force handling of value as a `Map`, and to use standard `MapSerializer`. There is another related potential problem due to value being assumed `String` so it's not 100% certain that'd work.

Aside from that, with 2.7, your best and perhaps only bet is to register custom serializer.
