### ISSUE TITLE
No clear update path for MapType, MapLikeType, etc.

### ISSUE THREAD

**Issue by nicobn** [FasterXML/jackson-databind#1163]
Commit 07d946c11d447ba88b62d28750a33651c897da29 deprecated multiple static methods, making it impossible to use MapType, MapLikeType, SimpleType, etc. without getting deprecation notices.

What replaces this functionality ? I could not find any documentation nor any mention in the release notes.

The reason I created an "issue" is that ideally, deprecation notices should be accompanied with a link to newer equivalent functionality and/or a link to a documentation page. Once I know what the replacement is, I'll open a pull request to add the comments to the source.

**Comment by cowtowncoder** [comment]
@nicobn Existing API let users directly create `JavaType` subtypes, although preferred and expected method was always to use methods in `TypeFactory`. With rewrite of type resolution in 2.7, it was not possible to reliably support all these methods. So replacements need to go via `TypeFactory` which has (and has had) equivalent `constructMapLikeType(..)` (etc) methods.

Help with javadoc updates would be much appreciated; filing an issue is a good way to raise the issue. I agree in that documentation could use more help, especially if usage of these methods is more widespread than I assumed.

**Comment by cowtowncoder** [comment]
May be reopened with a PR, or suggestions for improvements; I have add some notes in javadocs, and will keep this in mind if I change relevant code.
