### ISSUE TITLE
CoreXMLDeserializers does not handle time-only XMLGregorianCalendars

### ISSUE THREAD

**Issue by rgoldberg** [FasterXML/jackson-databind#1165]
`CoreXMLDeserializers` in 2.7.3 does not handle time-only `XMLGregorianCalendars`.  I assume the same is true for all prior versions.

The default behavior should accept time in addition to datetime, and acceptable values should be constrained by any `@XmlSchemaType` for the property (e.g., when `name = "date"`, then a time component should cause an exception, and when `name = "time"`, then a date component should cause an exception).  Maybe `@XmlSchemaType` support should be in `jackson-module-jaxb-annotations`.

**Comment by cowtowncoder** [comment]
I am open to improvement ideas, PRs, but I do not think I have any interest in using or support `@XmlSchemaType` since it seems specific to XML Schema and requires knowledge of that type system. If time-only Calendar instance can be supported without it, fine.
