### ISSUE TITLE
Accessing format from custom (de)serializer

### ISSUE THREAD

**Issue by rafalkrupinski** [FasterXML/jackson-databind#1168]
Hi

How can JsonDeerializer access `@JsonFormat.pattern` annotation value in its `deserialize` method?

**Comment by cowtowncoder** [comment]
@rafalkrupinski in future please use mailing lists for questions, `jackson-user` in this case.

Deserializers and serializers get access to contextual information by implement `ContextualSerializer` / `ContextualDeserializer` interface: it gets called with `property` through which information may be accessed (method `findPropertyFormat()`).

For serializers that extend `StdSerializer` (which should be pretty much all serializer implementations), there is convenience method `findFormatOverrides(...)` which works with annotations as well as (in future) per-type defaults (planned for 2.8). Same method exists in `StdDeserializer` as well.
