### ISSUE TITLE
Standard Java Coding Conventions

### ISSUE THREAD

**Issue by DeanPoulin** [FasterXML/jackson-databind#1169]
Is there an interest in refactoring the coding style/naming conventions of this project to meet standard Java conventions?

I've noticed many private fields are prefixed with underscores and curly braces are not consistent across classes.

I'm willing to send a huge pull request to refactor both of these, would this be something worth investing my time into or would my PR just be dismissed?

**Comment by cowtowncoder** [comment]
No, thank you for checking with me first.
