### ISSUE TITLE
setPropertyNamingStrategy has no effect when using lombok generated @ConstructorProperties

### ISSUE THREAD

**Issue by Athaphian** [FasterXML/jackson-databind#1179]
We use lombok to generate constructors using the @Value property. The constructors get the @ConstructorProperties annotation containing the original property names. However we also use a naming strategy to convert incoming json from snake case (underscores) to java camel casing.

This works when having getters/setters, but not when using the @ConstructorProperties.

Below is a unit test showing that it does not work:

`import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class JsonNamingTest {

    public static class A {
        private String testField;
        private String a;

        public String getTestField() {
            return testField;
        }

        public String getA() {
            return a;
        }

        public void setTestField(final String testField) {
            this.testField = testField;
        }

        public void setA(final String a) {
            this.a = a;
        }
    }

    public static class B {
        private String testField;
        private String a;

        @java.beans.ConstructorProperties({"testField", "a"})
        public B(String testField, String a) {
            this.testField = testField;
            this.a = a;
        }

        public String getTestField() {
            return testField;
        }

        public String getA() {
            return a;
        }

        public void setTestField(final String testField) {
            this.testField = testField;
        }

        public void setA(final String a) {
            this.a = a;
        }
    }

    // Works
    @Test
    public void testA() throws Exception {

        final ObjectMapper mapper = new ObjectMapper();
        mapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);

        assertEquals("b", mapper.readValue("{\"test_field\":\"test\", \"a\":\"b\"}", A.class).getA());
        assertEquals("test", mapper.readValue("{\"test_field\":\"test\", \"a\":\"b\"}", A.class).getTestField());
    }

    // Fails with UnrecognizedPropertyException
    @Test
    public void testB() throws Exception {

        final ObjectMapper mapper = new ObjectMapper();
        mapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);

        assertEquals("b", mapper.readValue("{\"test_field\":\"test\", \"a\":\"b\"}", B.class).getA());
        assertEquals("test", mapper.readValue("{\"test_field\":\"test\", \"a\":\"b\"}", B.class).getTestField());
    }
}`

**Comment by cowtowncoder** [comment]
Unfortunately semantics of `@ConstructorProperties` are similar to `@JsonProperty`, that is, it is considered to be explicit name to use, not subject to renaming.

Having said that, there is `MapperFeature.ALLOW_EXPLICIT_PROPERTY_RENAMING` (added in 2.7), enabling of which will force renaming, even if name is explicitly given. So you might consider enabling it.

**Comment by Athaphian** [comment]
I'll have a look at the MapperFeature, thanks, didn't know that.
