### ISSUE TITLE
Specify ArrayNode initial capacity

### ISSUE THREAD

**Issue by mveitas** [FasterXML/jackson-databind#1181]
Would it make sense to be able to be able to construct an ArrayNode with a predefined capacity? Looking at the `JsonNodeFactory`, https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/node/JsonNodeFactory.java#L310
, I think it would be reasonable to provide another method that accepts the size a passes that along to the underlying ArrayList implementation.

```
public ArrayNode arrayNode(int size) { return new ArrayNode(this, size); }
```

Here is my use case:
I am using jackson to retrieve the data as JSON from the Salesforce REST API. The calls to the REST API return back the number of records. By default their API only returns back 2000 items at a time and requires you to follow a link to the fetch the next 2000 items. Each time I am calling something like this 
`recordsList.addAll((ArrayNode)tempJson.findValue("records"));` the underlying ArrayList needs to be adjusted.

I am happy to put a PR together, just wanted to see if this was a reasonable suggestion

**Comment by cowtowncoder** [comment]
The only concern I would have is wrt backwards compatibility -- that is, to make sure `JsonNodeFactory` addition does not break existing code. Usually it should be possible to do this by just chaining default implementation of new method to call old method, but I don't remember exact details here.
And I can see the potential benefit here; it may even be possible that in some cases decoders could make use of this implicitly.

So PR would be welcome.
