### ISSUE TITLE
Allow overriding of `transient` with explicit inclusion with `@JsonProperty` and/or way to ignore `transient`

### ISSUE THREAD

**Issue by lhunath** [FasterXML/jackson-databind#1184]
The Java language has the `transient` property which indicates that certain fields should not take part in its Java object serialization framework of which `Serializable` is the hallmark.

Jackson appears to conflate Java's object serialization configuration with its own by forcing all `transient` fields to be excluded from any Jackson serialization. While it is a good idea for the `transient` keyword to provide a hint to Jackson that the field is uninteresting for its own serialization, the problem is really that this behaviour cannot be turned off. It is therefore impossible to include `transient` fields in a Jackson serialization process.

This becomes obvious when the application uses an object for two distinct types of serialization.

Case in point, I want to serialize an object in Android for storage within its `SharedPreferences` by serializing it using Java's object serialization (well supported by `SharedPreferences`).  I also want to serialize this object into JSON for submission to a remote server via HTTP. When I serialize the object into JSON, I need to include a few data points that should not be included in the `SharedPreferences` storage, hence my setting these fields as transient (to exclude them from the latter, Java object serialization). Unfortunately, this makes Jackson ignore them wholesale, even when annotated `@JsonProperty` (which is counter-intuitive - at a glance, one would expect a Jackson-annotated property to override a non-specific language keyword). There is also no way to change the configuration of the Jackson serialization mechanism to stop ignoring the `transient` keyword.

As such, this is a feature request to provide the ability to disable filtering out all `transient` fields from Jackson's serialization process.

**Comment by cowtowncoder** [comment]
Reworded to reflect that a fix could be something like letting `@JsonProperty` override `transient`, or perhaps adding a `MapperFeature` to allow disabling use of `transient`.
Former seems like a better option, but will need to see how implementation works: one challenge is that since `transient` is not annotation, its introspection is done at a deeper level and is more difficult to modify -- anything related to annotation handling is typically easier to deal with.

**Comment by cowtowncoder** [comment]
Quick note: addition of simple accessor matching field will make that property accessible (unless `MapperFeature.PROPAGATE_TRANSIENT_MARKER` is enabled). By default only access via specified field is prevented if so.

I will still investigate to see if there's a relatively easy way to further allow `@JsonProperty` to override `transient` directly.

**Comment by cowtowncoder** [comment]
Turned out to be relatively easy to use "has explicit marker" to override `transient` for field, so now should work better.
