### ISSUE TITLE
java.time.ZonedDateTime no longer converts properly on v2.7.3

### ISSUE THREAD

**Issue by bjornharvold** [FasterXML/jackson-databind#1190]
Here's my test that started failing after upgrading from 2.6.3 to 2.7.3. The string's timezone is not taken into consideration. Can I get a confirmation that this is a new bug?

`
@Test
public void testPlainObjectMapper() throws Exception {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModules(new JavaTimeModule());
    mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
    mapper.enable(SerializationFeature.WRITE_DATES_WITH_ZONE_ID);
    mapper.enable(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT);

    ZonedDateTime zdt1 = ZonedDateTime.now(ZoneId.of("GMT"));
    String zdt1S = mapper.writeValueAsString(zdt1);
    log.info("zdt1S: " + zdt1S);

    ZonedDateTime zdt2 = mapper.readValue(zdt1S, ZonedDateTime.class);
    String zdt2S = mapper.writeValueAsString(zdt2);
    log.info("zdt2S: " + zdt2S);

    log.info("zdt1: " + zdt1.toString());
    log.info("zdt2: " + zdt2.toString());

    assertEquals("Date strings are not equal", zdt1S, zdt2S);
    assertEquals("Zone Ids are not equal", zdt1.getZone(), zdt2.getZone());
    assertTrue("ZonedDateTime are not equal", zdt1.equals(zdt2));
}
`

Logger output:

`
2016-04-10 10:43:17,067 I JacksonConfigTest - zdt1S: 2016-04-10T03:43:17.04Z[GMT]
2016-04-10 10:43:17,076 I JacksonConfigTest - zdt2S: 2016-04-10T03:43:17.04Z[UTC]
2016-04-10 10:43:17,077 I JacksonConfigTest - zdt1: 2016-04-10T03:43:17.040Z[GMT]
2016-04-10 10:43:17,077 I JacksonConfigTest - zdt2: 2016-04-10T03:43:17.040Z[UTC]

org.junit.ComparisonFailure: Date strings are not equal 
Expected :"2016-04-10T03:43:17.04Z[GMT]"
Actual   :"2016-04-10T03:43:17.04Z[UTC]"
`

**Comment by cowtowncoder** [comment]
Since this is related to `jackson-datatype-jsr310`, could you refile over that repo? I would move it but I don't think Github has such functionality.

**Comment by bjornharvold** [comment]
Done
