### ISSUE TITLE
YAML serializer reports wrong exception

### ISSUE THREAD

**Issue by pmogren** [FasterXML/jackson-databind#1199]
When there is a serialization error (such as a StackOverflowError due to cyclical references) the useful exception (a JsonMappingException in this example) which should be reported to the user can be masked by an unhelpful exception that occurs during YAMLGenerator.close(). Only if that exception during close is an IOException will it be ignored. Consider catching and ignoring additional exceptions that may occur during close.

Workaround:
```
        YAMLFactory factory = new YAMLFactory() {
            @Override
            protected YAMLGenerator _createGenerator(Writer out, IOContext ctxt) throws IOException {
                int feats = _yamlGeneratorFeatures;
                YAMLGenerator gen = new YAMLGenerator(ctxt, _generatorFeatures, feats,
                        _objectCodec, out, _version) {
                    @Override
                    public void close() throws IOException {
                        try {
                            super.close();
                        } catch (Exception e) {   // ADDED THIS TRY-CATCH TO FIX EXCEPTION REPORTING
                            throw new IOException(e);
                        }
                    }
                };
                // any other initializations? No?
                return gen;
            }
        };
        mapper = new ObjectMapper(factory);
```

**Comment by cowtowncoder** [comment]
@pmogren Sounds reasonable, although also often difficult to resolve at least before being able to use `addSuppressed()` -- something we may be able to finally do having Java 7 baseline.

Could you re-file this for `jackson-dataformat-yaml`, however, unless handling itself is within `jackson-databind` code?

**Comment by pmogren** [comment]
You got it: https://github.com/FasterXML/jackson-dataformat-yaml/issues/60
FWIW, in practice, I've never benefited from addSuppressed() having been used. Given a choice of receiving the serialization exception or the close exception, I'd prefer the serialization exception.
