### ISSUE TITLE
@JsonTypeInfo usage

### ISSUE THREAD

**Issue by Veske** [FasterXML/jackson-databind#1200]
I am using `@JsonTypeInfo` like  this: 
`@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")`.

And later I map the value under type key to a certain class. Problem is that this `@JsonTypeInfo` annotation is latched on top of a class field. I have a class and a field in that class is a generic so I need this annotation. But the annotation is looking for the type key inside of the field I latched it on but for me the type field is instead in the root class not in the field class. 

So is there a way to override where it tries to look for the property name?

**Comment by cowtowncoder** [comment]
@Veske in general, please ask usage questions on mailing lists. In this case, if you think there is a defect in code, please add actual classes and code in question. I am not sure I fully understand the question with the information provided.

**Comment by Veske** [comment]
It seems what I was looking for was JsonTypeInfo.As.EXTERNAL_PROPERTY. Can close this, sorry for the issue.
