### ISSUE TITLE
treeToValue doesn't handle POJONodes that contain exactly the requested value type

### ISSUE THREAD

**Issue by tommack** [FasterXML/jackson-databind#1208]
I would have expected this test to pass.

    @Test
    public void test_pojonode_assumption() throws Exception {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());

        Duration someHours = Duration.ofHours(4);

        ValueNode pojoNode = objectMapper.getNodeFactory().pojoNode(someHours);

        Duration returnedDuration = objectMapper.treeToValue(pojoNode, Duration.class);

        Assert.assertEquals(someHours, returnedDuration);
    }

Thread: https://groups.google.com/forum/#!topic/jackson-user/TQikhXIOqNU

**Comment by cowtowncoder** [comment]
Ok, I fixed this for the case of root value being `POJONode`. Unfortunately comprehensive handling for cases deeper down in hierarchy is not something that can be done in just one place, at least not currently. I'll have a look at specific case of Java 8 date/time types, but ideally it should be something handled similar to `null`s.
