### ISSUE TITLE
JSON array first element is read always as null, if the element before the array was null

### ISSUE THREAD

**Issue by manuelschwarze** [FasterXML/jackson-databind#1213]
When reading the following simplified JSON structure in I am encountering a serious issue in version 2.7.3:

```
{
  "id": "ABC",
  "totalItems": 1,
  "items": [
    {
      "id": "123",
      "name": "A name",
      "aValueThatIsNull": null,
      "anArrayWithValuesInside": [
        {
          "name": "A name 1",
          "shortName": "XXXX1",
        },
        {
          "name": "A name 2",
          "shortName": "XXXX2",
        },
        {
          "name": "A name 3",
          "shortName": "XXXX3",
        }
      ]
    }
  ]
}
```

The simplified xsd definition for the values I am interested in is:

    <xs:element name="test">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="totalItems" type="xs:int"/>
                <xs:element name="items" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="anArrayWithValuesInside" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="shortName" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

I am getting in my Java class as result for the array named "anArrayWithValuesInside" a List, which has the correct number of items (in this example 3), but the first list element is always incorrectly null. The real item is lost. 

The reason I identified is that it has something to do with the element that appears directly before the array in the JSON structure. If that element is null and it is not part of by xsd definition so that it is not consumed into my Java class, then the bug appears. If it is not null, everything is working fine.

This is a serious bug as we are consuming web services that we do not control, hence we cannot avoid the bug by tweaking the incoming data. The workaround I had to do now is to consume this field "aValueThatIsNull". This is not a good solution, because the web service does not guarantee the order of the fields. Also, if new fields are added by the web service my code may suddenly start failing because of this.

I hope this can be fixed quickly.

**Comment by cowtowncoder** [comment]
What does XSD have to do with this? What is JSON you are using? Classes? 

This tells very little about the issue you have; I'd need an actual reproduction here.

**Comment by cowtowncoder** [comment]
I can not reproduce the issue with information provided, unfortunately. May be reopened with reproduction.

**Comment by manuelschwarze** [comment]
I have looked into this again more careful now and can confirm that this issue is not jackson-databind related. Sorry for filing this by mistake.

**Comment by manuelschwarze** [comment]
The bug I found is actually in MOXy used by Jersey and is already documented here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=475475
