### ISSUE TITLE
Json serialization how to ensure the normal output of 0.00, rather than only 0?

### ISSUE THREAD

**Issue by liuwenfeng554** [FasterXML/jackson-databind#1220]
#Using spring4.0 + 
Json serialization how to ensure the normal output of 0.00, rather than only 0?
to：
 data{
   name:'van';
   number:0.00;
  }

**Whether implemented by means of configuration?**

`<mvc:annotation-driven>
      <mvc:message-converters register-defaults="true">
      <bean class="org.springframework.http.converter.json.MappingJackson2HttpMessageConverter">
           <property name="objectMapper">
                <bean class="org.springframework.http.converter.json.Jackson2ObjectMapperFactoryBean">
                  <property name="featuresToEnable">
                            <array>
                                <util:constant static-field="com.fasterxml.jackson.databind.SerializationFeature.WRAP_ROOT_VALUE" />
                            </array>
                         </property>
                     </bean>
                 </property>
            </bean>
          </mvc:message-converters>
      </mvc:annotation-driven>`

**Comment by cowtowncoder** [comment]
@liuwenfeng554 I don't know anything about spring configuration, but Jackson simply uses JDK output serialization for `int`, `long`, `double` and so on, so it depends on type of property. In general I can not help without seeing actual Java Bean in question; also, your json is incorrectly formatted (missing quotes, wrong quotes etc).

**Comment by cowtowncoder** [comment]
Can't reproduce; may be reopened with stand-alone test case.
