### ISSUE TITLE
JsonMappingException should override getProcessor

### ISSUE THREAD

**Issue by nickbabcock** [FasterXML/jackson-databind#1225]
Currently all `JsonMappingException` will return `null` for `getProcessor` because it does not override the method, even though it has it's own field (`_processor`). Is this intended?

**Comment by cowtowncoder** [comment]
@nickbabcock probably not (I'd have to look to verify but can't think why it would be).

**Comment by cowtowncoder** [comment]
Ok I see the problem. Will fix, see if other subtypes have the same problem.
