### ISSUE TITLE
`java.nio.file.Path` support incomplete

### ISSUE THREAD

**Issue by benson-basis** [FasterXML/jackson-databind#1235]
Just as the subject says.

I'll make a patch for this.

**Comment by benson-basis** [comment]
I'll make a PR eventually.

```
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * 
 */
public class NioPathDeserializer extends JsonDeserializer<Path> {
    @Override
    public Path deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
        if (p.getCurrentToken() == JsonToken.VALUE_NULL) {
            return null;
        } else if (p.getCurrentToken() != JsonToken.VALUE_STRING) {
            throw ctxt.wrongTokenException(p, JsonToken.VALUE_STRING, "The value of a java.nio.file.Path must be a string");
        }
        String uri = p.readValueAs(String.class);
        return Paths.get(uri);
    }
}
```

**Comment by benson-basis** [comment]
Note: the existing class is broken, as it only supports the default file system.

**Comment by cowtowncoder** [comment]
Broken is such a strong word... I'd say limited. :-D

Thanks for the patch, will merge it, and simplify some parts (no need to deprecate existing class as it's renamed version of one from 2.7, so technically new)

**Comment by bimargulies** [comment]
I wrote broken based on trying something with a much older version :-). I agree, of course, with your characterization. Do I have any hope of a 2.7.x?

**Comment by cowtowncoder** [comment]
@bimargulies heh. Broken works as characterisation too.

For 2.7 I can probably cherry-pick something... just need to be more careful. If you want to take a stab that might be fastest.

**Comment by bimargulies** [comment]
When are you thinking that 2.8.0 might appear? If it's soon, I don't need a 2.7.x solution.

**Comment by cowtowncoder** [comment]
@bimargulies really hoping to nail n+1 odds & ends to get 2.8.0.rc1 out soon. Soon here means within 2-3 weeks. And depending on how greedy I am, doing rcs for 2-4 weeks more. There's reasonable chance rc1 will arrive no later than 2.7.5 would; 2.7.4 seems stable enough to last for longer than previous patches.
