### ISSUE TITLE
google play SSL warning

### ISSUE THREAD

**Issue by or-dvir** [FasterXML/jackson-databind#1247]
hi.
i have published my app on the google play store and im getting a warning from google saying something about using an old and unsecured version of SSL.
the warning refers to this page:
https://support.google.com/faqs/answer/6376725

the thing is in my app i am not doing anything related to SSL.
i read online that it's most probably a third party library thats causing the warning, so i am writing this message to all the third party libraries i am using in my app.

are you using SSL in your library in any way? could it be that your library is the cause for this warning?
if so, when can i expect a new version which uses the latest SSL version?

this is important because as the link above mentions:
"Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL"

p.s.
i will post the same question also in the "core" and "annotations" github pages as your "home"/general github page says that issues should be posted within the specific modules, so please don't hate me...

thanks

**Comment by cowtowncoder** [comment]
@or-dvir no, please use mailing lists for this: issue tracker is for reporting problems, not asking for usage question or general information about library.

But as to your question, no, Jackson does NOT directly use SSL for anything; nor am I aware of extension modules that do that. So you should be fine.
