### ISSUE TITLE
JsonNode, how to retrieve a linkedList contained into a JsonNode

### ISSUE THREAD

**Issue by NajlaeElAzzouzi** [FasterXML/jackson-databind#1254]
Hello,
I'm new at the fasterxml Jackson library, in fact I used to work with codehaus (1.x version of the library). to retrieve informations from an InputStream and stock it in a map we used this code :
Map<String, Object> objects = getObjectMapper().readValue(is, Map.class);
(with "is" is the InputStream we get from the response)
now that I'm changing to fasterxml version, I don't know how to do that, I tried to work with a JsonNode instead,:
Map<String, Object> objects = (Map<String, Object>) json.get("_children");
with _children is a LinkedList contained in the JsonNode, and json is the Json we get from the response.

**Comment by cowtowncoder** [comment]
@NajlaeElAzzouzi Usage questions really belong to users mailing list https://groups.google.com/forum/#!forum/jackson-user

But as to usage, your old code should work just fine: use `Map.class` as the type like before. Unless you want tree representation there's no point in asking for it; and the whole point is that internal List representation is not exposed to user code.
