### ISSUE TITLE
How to deserialize a list with only a getter

### ISSUE THREAD

**Issue by davidwbrown** [FasterXML/jackson-databind#1259]
I would like to deserialize some json data into an Object containing a List that only has a getter and no setter. It was generated with wsdl2java. I am using the JsonParser and ObjectMapper. I tried to use a custom de/serializer with no luck.
Is there a way to intercept where it would normally call the setList1(list1) so I could use getList1().addAll(list1)?

Input JSON:
```
{
	"string1" : "String 1",
	"object1" : {
		"string2" : "String 2"
	},
	"list1" : [{
		"string2" : "String 2.1",
		"string2" : "String 2.2"
	}, {
		"string2" : "String 2.3"
	}]
}
```
Mapped Object:
```
	public class Test1 {
		String string1;
		Object1 object1;
		List<Object1> list1;

		public String getString1() {
			return string1;
		}

		public void setString1(String string1) {
			this.string1 = string1;
		}

		public Object1 getObject1() {
			return object1;
		}

		public void setObject1(Object1 object1) {
			this.object1 = object1;
		}

		public List<Object1> getList1() {
			if (list1 == null) {
				list1 = new ArrayList<Object1>();
			}
			return list1;
		}

		public static class Object1 {
			String string2;

			public String getString2() {
				return string2;
			}

			public void setString2(String string2) {
				this.string2 = string2;
			}

		}
	}
```
Results:
```
test1 = {
	"string1" : "String 1",
	"object1" : {
		"string2" : "String 2"
	},
	"list1" : [ ]
}
```

**Comment by cowtowncoder** [comment]
In future, please use mailing lists for usage questions.

As to "use getter as setter", it should work as long `MapperFeature.USE_GETTERS_AS_SETTERS` is set to true. But this is the default setting, so it should just work since you don't have a setter.

Test case `src/test/java/com/fasterxml/jackson/databind/deser/TestSetterlessProperties.java` should show working examples.

**Comment by davidwbrown** [comment]
First time user, sorry about that, where are the mailing lists?
Turns out the original code skipped the property if it was not writeable. Removed it.
Made sure I turned on USE_GETTERS_AS_SETTERS and it works great, thanks.

**Comment by cowtowncoder** [comment]
@davidwbrown Ah should have included the link; google group here:

https://groups.google.com/forum/#!forum/jackson-user

Glad to know things now work -- this is one of lesser known features, added it originally as JAXB used that mechanism for Lists/Maps.
