### ISSUE TITLE
Serialization format of nio Path changed between 2.7.4 and 2.8.0.rc1

### ISSUE THREAD

**Issue by michaelhixson** [FasterXML/jackson-databind#1264]
The JSON serialization of `java.nio.file.Path` changed between 2.7.4 and 2.8.0.rc1, causing a couple of my tests to fail:

```java
public void testRelativePath() throws Exception {
  ObjectMapper mapper = new ObjectMapper();
  Path expected = Paths.get("one/two/three");
  String json = mapper.writeValueAsString(expected);
  Path actual = mapper.readValue(json, Path.class);
  assertEquals(expected, actual);
}

public void testAbsolutePath() throws Exception {
  ObjectMapper mapper = new ObjectMapper();
  Path expected = Paths.get("/one/two/three");
  String json = mapper.writeValueAsString(expected);
  Path actual = mapper.readValue(json, Path.class);
  assertEquals(expected, actual);
}
```

In 2.8.0.rc1 the relative path becomes a "file:///" URI in the JSON string, which is an absolute URI including my current working directory, and then after deserializing it remains an absolute path.  In the second test, the absolute path gets prepended with "C:\" (I'm using Windows).

It turns out I'm not actually serializing `Path` objects anywhere except my tests.  They're leftovers from previous functionality.  So I personally have no problem with simply deleting my tests.

Maybe this change should be called out in the release notes though?  I didn't see anything about it here:  https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8

**Comment by cowtowncoder** [comment]
@michaelhixson good point. It's most likely due #1235 and I will add a note (both in individual updates, and under compatibility issues section).

@benson-basis just an fyi, regarding relative path, if there's anything that could or should be done for backwards compatibility.

**Comment by cowtowncoder** [comment]
Updated release notes pages.

**Comment by benson-basis** [comment]
I'm on vacation, I'll think upon it.
