### ISSUE TITLE
Add equivalent to Include.NON_NULL to DeserializationConfig

### ISSUE THREAD

**Issue by robotdan** [FasterXML/jackson-databind#1269]
When configuring the serialization features of the ObjectMapper, I set the following:

`ObjectMapper objectMapper = new ObjectMapper().setSerializationInclusion(Include.NON_NULL);`

Ideally for my usage I'd like to ignore a null when we de-serialize the JSON payload. This request looks to be similar to #347 but I'd like to just ignore nulls all together.

If there is not a fundamental reason why this feature has not been made available in the DeserializationConfig I'd be interested in taking a stab at an implementation.

**Comment by cowtowncoder** [comment]
Concept of filtering on output is not symmetric, as the set of things in `Include` enum are mostly output-centric. `NON_NULL` is about the only thing that could apply to deserialization.

There is no support for similar filtering on deserialization, and I don't have intention to add any; however, there have been various efforts by null-averse developers to add work-arounds to coerce explicit nulls and/or missing property values into other types.

If a very general "never set explicit `null` value" functionality is wanted, I would be open to `MapperFeature` for that. It would basically be static setting that could be applied during `JsonDeserializer` construction. It could further have per-property override via `@JsonFormat`, and specifically `FormatFeature` thereof.
So, something like `MapperFeature.NEVER_SET_AS_NULL`.

**Comment by robotdan** [comment]
I prototyped this feature using `MappingFeature.NEVER_SET_AS_NULL`.  

Could you review briefly to let me know if this looks more/less inline with how you'd like to see this implemented? 

See commit 9e37d58c65f1ffef7b17c8c4c8e5ebc76a893cb2 on my fork.

You can ignore the changes to `ObjectMapper` and `ObjectReader` I don't think I need them.

Thanks, appreciate any help or feedback you can provide before I continue.

**Comment by cowtowncoder** [comment]
@robotdan Thank you for the idea and protoype!

From that, I have an idea of how to implement this by extending `@JsonSetter`. But in addition to allowing "skipping" of incoming `null`s, it could also allow other behavior like throwing an exception.
I realized that use of `@JsonFormat` would be semantically wrong, since this is not about formatting; so while convenient, not the way to do it.

Anyway, I plan to work on this for 2.9 and thought I'd add a note.

**Comment by robotdan** [comment]
You're welcome. 

I'd be happy to lend a hand if you'd like any help. If you want some early testing of a 2.9 build I would volunteer.

**Comment by cowtowncoder** [comment]
@robotdan absolutely. I'll let you know when I get bit further.

**Comment by cowtowncoder** [comment]
Replaced with #1402.
