### ISSUE TITLE
Map infinite recursion

### ISSUE THREAD

**Issue by f0def** [FasterXML/jackson-databind#1273]
Hi, how to solve infinite recursion issue with this example?

One class that can be embedded in itself via `Map`:
```java
public class Foo {

    public int id;
    public Map<String, Foo> map = new HashMap<>();

    public Foo(int id) {
        this.id = id;
    }
}
```

Test that tries to get the JSON string. But it produce exception `com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion`.
Levels can be any number, not necessarily 2
```java
public class JacksonRecursionTest {

    @Test
    public void testInfiniteRecursion() throws JsonProcessingException {
        Foo parent = new Foo(1);
        Foo child = new Foo(2);
        parent.map.put("child", child);
        child.map.put("parent", parent);

        ObjectMapper objectMapper = new ObjectMapper();
        String json = objectMapper.writeValueAsString(parent);
        assertEquals("{\"id\":1,\"map\":{\"child\":{\"id\":2,\"map\":{\"parent\":{\"id\":1}}}}}", json);
    }
}
```

A formatted result that would like to get. It is seen as recursion stopped at `parent` without `map` property, only `id`
```js
        {
            "id":1,
            "map":{
                "child":{
                    "id":2,
                    "map":{
                        "parent":{
                            "id":1
                        }
                    }
                }
            }
        }
```

I use jackson-databind 2.7.4 and spring framework

**Comment by cowtowncoder** [comment]
A good starting point is to ask usage questions on mailing list:

https://groups.google.com/forum/#!forum/jackson-user

as to solution, given that there is real cycle, your options tend to be either using `@JsonIdentityInfo` for `Foo`, or, if feasible combination of `@JsonManagedReference`/`@JsonBackReference`.
