### ISSUE TITLE
It would be helpful if AnyGetterWriter implemented an interface

### ISSUE THREAD

**Issue by benson-basis** [FasterXML/jackson-databind#1282]
.. so that it was possible to proxy one without circumventing access control.

**Comment by cowtowncoder** [comment]
Could you elaborate slightly? To provide an alternate implementation, but not sure what you mean wrt access control here.

**Comment by benson-basis** [comment]
A person currently could use reflection to circumvent 'protected' on the
fields to, for example, filter out unwanted properties. That is what I
meant.

**Comment by cowtowncoder** [comment]
@benson-basis Right but how would an interface help there?

**Comment by benson-basis** [comment]
I'm not sure. At the time, I thought I could wrap a proxy object around the AnyGetterWriter, but I may have not thought it all the way through. Really, the IgnoreProperties for 'any' is what I am really after, but I don't have time to look into contributing it just now. This may just be a dumb idea.

**Comment by cowtowncoder** [comment]
Ok; I'll close this for now then, focus on getting IgnoreProperties to work (when I find time).
