### ISSUE TITLE
Getting exception when trying to parse nested json array into array of objects

### ISSUE THREAD

**Issue by MostafaNasiri** [FasterXML/jackson-databind#1283]
I have this json string:
`{"id":"1","description":"1","bgSoundId":"1","audio":"Your_Eyes.mp3","title":"1","writer":"1","illustrator":"1","ageCategory":"1","likes":"2","thumbnail":"photo_2016-04-19_22-47-08.jpg","audioUrl":"http:\/\/bketab.ir\/uploads\/Your_Eyes.mp3","thumbnailUrl":"http:\/\/bketab.ir\/uploads\/photo_2016-04-19_22-47-08.jpg","photos":[{"url":"photo_2016-04-19_22-47-08.jpg","second":0}]}`

and i have my Story class:

```
public class Story {
	// Other fields
	private Photo[] photos;
	// rest of the class
} 
```

but when i try to parse the json like this:
`ObjectMapper mapper = new ObjectMapper();
                    Story story = mapper.readValue(result, Story.class);`

i get the following exception:
`JsonMappingException: No suitable constructor found for type [simple type, class ir.sohreco.ghesseyema.model.Photo]`

Any idea?

**Comment by cowtowncoder** [comment]
Yes. Ask usage questions on Jackson user list:

https://groups.google.com/forum/#!forum/jackson-user

But if I had to guess from code -- which for some odd reason is missing definition of `Photo` (despite exception explicitly pointing at problem with that class) -- maybe `Photo` is a non-static inner class and needs to be made `static`. Or, alternatively, does not zero-argument constructure.
