### ISSUE TITLE
Jackson 2.6.x -> 2.7 deserialize generic fails when invoked from Spring controller

### ISSUE THREAD

**Issue by maffelbaffel** [FasterXML/jackson-databind#1287]
I'm just trying to upgrade (Spring 4.3 project) from jackson 2.6.3 to 2.7 and getting a annoying error.

This is my simplyfied project:

Abstract controller class with a http post method which accepts a requestBody of a generic list:
```
public abstract class AbstractController<T extends Entity> {

    @RequestMapping(value = "/", method = POST)
    public void method1(@RequestBody final List<T> entities){
        System.out.println("AbstractController called");
    }
}
```

Controller implementation with a simple Entity class
```
@RestController
@RequestMapping("/impl1")
public class ControllerImpl extends AbstractController<EntityImpl> {
}

```
second controller with method1 overriden
```
@RestController
@RequestMapping("/impl2")
public class ControllerImpl2 extends AbstractController<EntityImpl2> {

    @Override
    public void method1(@RequestBody List<EntityImpl2> entities) {
        System.out.println("ControllerImpl2 called");
    }
}
```

My Entity:
```
public class EntityImpl implements Entity<Integer> {

    private String name;

    public EntityImpl() {
    }

    public EntityImpl(String name) {
        this.name = name;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public void setName(final String name) {
        this.name = name;
    }
}
```

Ok, so this setup works fine with Jackson 2.6.x and Spring 4.2.x, but i need to upgrade to 2.7 because of [this ](https://github.com/FasterXML/jackson-datatype-hibernate/issues/79) issue.
But with 2.7 every post request to "/impl1/" gives me this error:

```
Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Could not read document: Can not construct instance of jackson.entity.Entity, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
     at [Source: java.io.PushbackInputStream@1aa5c56a; line: 1, column: 2] (through reference chain: java.util.ArrayList[0]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of jackson.entity.Entity, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
     at [Source: java.io.PushbackInputStream@1aa5c56a; line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
```

Thought posts to /impl2/ workwith both versions ... but i really dont want to override every method there.

Is there a way to solve this?
I have created a sample project with some pretty easy tests showing this behavior. 
Just run
./gradlew build

If you open gradle.build and remove these lines:
// uncomment both for failing tests!!
    compile "com.fasterxml.jackson.core:jackson-databind:2.7.0"
    compile "org.springframework:spring-webmvc:4.3.0.RELEASE"
Tests are working fine then. (Jackson 2.6 and Spring 4.2 are being used then)

Hope someone can help me here :)

**Comment by maffelbaffel** [comment]
[jackson.zip](https://github.com/FasterXML/jackson-databind/files/349912/jackson.zip)
My sample project showing this error

**Comment by cowtowncoder** [comment]
@maffelbaffel Are you sure you are testing with the latest patch version, 2.7.5? Bugs should always be verified with the last patch, and especially in this case versions 2.7.0 - 2.7.3 had a few issues related to generics (due to complete rewrite of type resolution system) that have been fixed.

**Comment by maffelbaffel** [comment]
Yes, using the latest 2.7.5 gives me the same error. 
Not sure if this is a spring related problem thought.

**Comment by cowtowncoder** [comment]
Unfortunately this does not help me a lot since it includes Spring code, and what I really need is reproduction with Jackson. Otherwise problem may be in Spring handling; and in fact looking at code I think it is due to something in the way Spring uses Jackson. But I don't use Spring myself so I don't know what might be going wrong.

So at this point this does not unfortunately show a problem I could work on.

**Comment by maffelbaffel** [comment]
Ok, thanks for taking the time and looking into the issue :)
I will try posting it at springs jira then.
