### ISSUE TITLE
Add `@JsonIncludeProperties(propertyNames)` (reverse of `@JsonIgnoreProperties`)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1296]
(note: there may already be something for white-listing properties)

In some/many cases it'd be easier to just name properties to include, reverse of `@JsonIgnoreProperties`. And similarly, it should be possible to define baselines by type as well as property overrides; and if ever we support inheritance-merging in class hierarchy, use similar merging strategies (merge vs replace)

**Comment by SUGE2016** [comment]
what is the solution? finally

**Comment by lukaszlenart** [comment]
It would be nice to have something like [this](http://x-stream.github.io/security.html) where I can allow only a given class type hierarchy to be serializable/deserializable without defining all the properties.

**Comment by cowtowncoder** [comment]
@lukaszlenart Huh? I am not sure what you mean. Jackson can use fields as properties as well as getters; visibility level needed is configurable and just defaults to `public`.

**Comment by lukaszlenart** [comment]
Sorry for that :( What I meant is that I would like to allow serialise/deserialise only given classes, create a whitelist not blacklisting as you do now. Something like we have for [XStream](https://github.com/apache/struts/blob/master/plugins/rest/src/main/java/org/apache/struts2/rest/handler/XStreamHandler.java#L83-L111) where only selected classes can be serialised/deserialised to/from XML.

**Comment by cowtowncoder** [comment]
Ok. I guess I understand what you are asking, but not necessarily what the benefit would be.
For common cases, starting with declared root type to deserialize (or type of instance to serialize), then following property types works well. So what would be the benefit of having to whitelist all types accepted? (assuming that would include "well-known" types like `String`, `boolean`/`Boolean`, all number + wrapper types, various `Collection`, `Map` types and so forth).

For what it is worth you could implement something like this by sub-classing `isIgnorableType()` of `[Jackson]AnnotationIntrospector`; it is method called to hande `@JsonIgnoreType` annotation.

Anyway: assuming idea would seem useful, maybe you could file another issue for it as it is distinct from this one. Implementation could be quite simple -- I assume registering a handler, with "simple" implementation (direct type lookup), would suffice.

**Comment by lukaszlenart** [comment]
I thought that I have posted an answer but it's gone :(

Anyway, having a whitelist is far safer than blocking the whole world. This gives more control and allows users precisely filter which classes can serialize/deserialize. 

Your suggestion with overriding `[Jackson]AnnotationIntrospector` won't work because to keep backward compatibility at some point I have to call `super.isIgnoreableType()` which allows any type except those marked with `@JsonIgnoreType`.

I'm going to open an issue to support whitelisting.

Thank you for your work and support!

**Comment by lukaszlenart** [comment]
It would be a nice addition for those who need to expose public APIs.

**Comment by claytonfbell** [comment]
Agree, this would be very useful for exposing public APIs.

**Comment by cowtowncoder** [comment]
Anyone with an itch is totally free to work on this.
Would need to go in 3.0 (new annotations not allowed in patch release), in `master`.

**Comment by sunphy** [comment]
Yes,`@JsonIncludeProperties(propertyNames)` is very useful!

**Comment by nomadus** [comment]
+

**Comment by jhordies** [comment]
I would also love to see this implemented. It would be much safer especially when a developer would add a sensitive field in a referenced class without checking where it could be exposed through an api.

**Comment by ssamayoa** [comment]
I also need @JsonIncludeProperties(propertyNames)
Not only for sensitive fields but also for complex entity objects in which normally you don't need other than  few properties, example:

`
@Entity
public class Customer {
...
private SalesMan salesMan;
...
@ManyToOne
@JsonIncludeProperties({"id", "name"})
public SalesMan getSalesMan() {
  return salesMan;
}
`

**Comment by cowtowncoder** [comment]
Yes, I think this is a highly wanted feature. I hope it could get implemented for 2.10. The big challenge is that by now all the code associated with discovery (and suppression) of properties is rather large and changes in place can easily cause problems in others. This is true especially here as we would be added a complementary system which counteracts main suppression-based mechanisms.

**Comment by yonetmen** [comment]
This will be very useful if implemented. Gonna help us to avoid all those custom serializer classes.

**Comment by nejeoui** [comment]
This will come very handy especially for annotating JPA associations

**Comment by Vynny** [comment]
Would really like this feature! It would help clean up some of my models significantly.

**Comment by anz000** [comment]
I echo the feature request.

**Comment by mihaiqc** [comment]
@JsonIncludeProperties(propertyNames) is a must-have IMO.

**Comment by farthVader91** [comment]
Need this for a usecase that involves isolating PII in the POJO.

**Comment by AkashNeil** [comment]
I agree; this feature will be extremely useful.

**Comment by diegomors** [comment]
Please!!!

**Comment by Sdwz** [comment]
+1

**Comment by biwano** [comment]
+1

**Comment by backoon** [comment]
+1. This will be very useful.

**Comment by sukys-sippulse** [comment]
+1

**Comment by PunKHS** [comment]
+1

**Comment by cowtowncoder** [comment]
At this point it has been established that users would find such annotation/property useful; locking comments as further +1s are just noise.

**Comment by cowtowncoder** [comment]
Being worked on as #2771, planning to get included in 2.12.

**Comment by cowtowncoder** [comment]
Merged; will do a bit of refactoring on naming and perhaps the way related pieces (ignore vs include sets) are handled. Will be included in 2.12.0.

**Comment by cowtowncoder** [comment]
Looks like this may have caused a minor regression with Guava datatype module...

**Comment by cowtowncoder** [comment]
Was included in 2.12.0; outlined as one of 5 "Most Wanted" new features.
