### ISSUE TITLE
Custom deserializer registration using modules do not work for interface types

### ISSUE THREAD

**Issue by diego-martinoia-sky** [FasterXML/jackson-databind#1300]
Say I have an interface:

```
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "__TYPE__")
@JsonSubTypes({
        @JsonSubTypes.Type(value = T1.class, name = "T1"),
        @JsonSubTypes.Type(value = T2.class, name = "T2")
})
public interface EncryptedType {}
```

and classes like

```
@JsonTypeName("T1")
public class T1 implements EncryptedType {...}
```

If I register a custom serializer/deserializer for it using a module

 ```
SimpleModule module = new SimpleModule();
module.addDeserializer(EncryptedType.class, encryptedDeserializer);
module.addSerializer(EncryptedType.class, encryptedSerializer);
 objectMapper.registerModule(module);
```

Then the serializer is correctly used, but the deserializer is not found.

If I instead register the deserializer using the annotation at the Interface level:

```
@JsonDeserialize(using=EncryptedDeserializer.class)
public interface EncryptedType {}
```

Then the custom deserializer is correctly picked up when doing objectMapper.readValue(T1.class).

Debugging in the library, this seems to be because annotation based registrations are checked before reaching this piece of code:

```
@Override
public JsonDeserializer<?> findBeanDeserializer(JavaType type,
   DeserializationConfig config, BeanDescription beanDesc)
  throws JsonMappingException
{
  return (_classMappings == null) ? null : _classMappings.get(new ClassKey(type.getRawClass()));
}
```

inside the SimpleDeserializers.java class. Once there, since the checking is done via getRawClass, it returns the concrete type, while the _classMapping map conrtains a key for the interface (EncrtyptedType) instead.

I feel the discrepancy is relevant because the annotation based method forces the creation of the bean by jackson, and therefore I cannot easily register a custom instance that, for example, I built with spring or whatever.

Is there a workaround?

**Comment by cowtowncoder** [comment]
I will have to think this carefully through, but my initial thinking is that you are right and that registration methods should be similar such that they should override default handling. And as such this seem like a legit bug.

**Comment by diego-martinoia-sky** [comment]
It also seem to prevent me from using a single custom polymorphic deserializer: my idea was to register the custom poly deser in the main objectmapper, then have inside the deserializer a private object mapper that does not know about the customization, and in the deserializer I could do something like

```
//find the concrete type via type field
privateObjectMapper.readValueAs(concreteType.class)
//and then do the things I need
```

this would bc the private om does not know about the custom registration and therefore would deser directly to the concrete type internally.

If I can only register through annotation, those apply to ALL om, and the above mentioned strategy would yield a stackoverflow error because the readValue now would call the custom deserializer method instead and loop infinitely.

Or am I missing something?

**Comment by cowtowncoder** [comment]
@diego-martinoia-sky Actually... deserializer is registered and found fine; the problem is that since this requires polymorphic handling, you need to define method:

    public T deserializeWithType(JsonParser, DeserializationContext, TypeDeserializer);

since that is what gets called in such cases. Default implementation will call `TypeDeserializer`, which tries to handle polymorphic type info; in your case you will not want to do that, but may access settings of `TypeDeserializer` for configuration access.
