### ISSUE TITLE
Javadoc for jackson-databind 2.8

### ISSUE THREAD

**Issue by sdeleuze** [FasterXML/jackson-databind#1306]
Could it be possible to publish the Javadoc for `jackson-databind` 2.8 at http://fasterxml.github.io/jackson-databind/javadoc/2.8/ like the 2.7 is at http://fasterxml.github.io/jackson-databind/javadoc/2.7/ ?

**Comment by cowtowncoder** [comment]
Yes. I thought I had done it, but apparently not. Will do.
