### ISSUE TITLE
EnumMap keys not using enum's `@JsonProperty` values unlike Enum values

### ISSUE THREAD

**Issue by MichaelChambers** [FasterXML/jackson-databind#1322]
Based on these issues:
https://github.com/FasterXML/jackson-databind/issues/677
https://github.com/FasterXML/jackson-databind/issues/1148
https://github.com/FasterXML/jackson-annotations/issues/96

I implemented @JsonProperty for my enum constants and they show up nicely when they are property values. But I also have an EnumMap which uses the enum, and it's generated JSON uses the original enum names for the keys and not the JsonProperty values.

Using 2.8.1 (in spring boot 4.3.2)

Thanks!

**Comment by cowtowncoder** [comment]
Thank you for reporting this.

**Comment by cowtowncoder** [comment]
Ok, looks like use of `@JsonValue` works at least. Next checking `@JsonProperty` part.

**Comment by cowtowncoder** [comment]
I can reproduce this, and can see the problem. Fix will take a while, need to add Enum-specific key serializer. Not particularly difficult to do but... some work.
