### ISSUE TITLE
ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT not supported

### ISSUE THREAD

**Issue by laran** [FasterXML/jackson-databind#1323]
I'm finding that empty arrays are not being converted to null as this feature suggests they should. Empty arrays are being returned as empty arrays, not as null when this feature is enabled.

[This line](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/std/ObjectArrayDeserializer.java#L217) seems to be the culprit.

No time right at the moment to create a patch. Will take a look at some point if possible.

Using Jackson 2.8.1. This issue has not been reported specifically. Other issues related to handling of arrays/nulls has. But not the fact that this specific feature is not properly supported.

**Comment by cowtowncoder** [comment]
Maybe you are misunderstanding meaning of this feature? It is not designed to change empty JSON array into `null` value for `Object[]` valued property.

There are 2 unit tests that verify that `[ ]` does coerce into `null` POJO or `Map` value, so I think I would need a unit test or code snippet to show case where handling fails, if you think behavior is not correct.

**Comment by cowtowncoder** [comment]
Actually 2.9.0 has many improvements in this are so that feature should work for much wider set of types.
