### ISSUE TITLE
Boolean parsing with `StdDeserializer` is too slow with huge integer value

### ISSUE THREAD

**Issue by pavankumar-parankusam** [FasterXML/jackson-databind#1324]
JSON Version 2.6.5 and later

We tried a use case to provide a big chunk of numbers to the boolean value in JSON.
Eg. 
{
  isRead: 1010101010101010101010101010101010101010101010101010101010101010101 //(big chunk of numbers, length of 97000 digits, truncated for readibility)
}

This takes a lot more time to parse isRead value to boolean datatype. 
The problem is when it tries to determine the JsonParser.getNumberType() in method StdDeserializer._parseBoolean.

The JsonParser.getNumberType() calls ends up in ParserBase._parseSlowInt where it create a BigInteger object with provided value. This BigInteger creation takes a long time to parse a numbers of length 97000 digits.

This big integer object is created just to detect the valid number type and it is discarded.
For a boolean parsing, can we not be more strict and say the length of the digits should be only 1.
Then we can avoid all this heavy parsing of value with BigInteger.

As the parsing takes more than 10 seconds, we end up in Denial of Service situation.

**Comment by cowtowncoder** [comment]
Thank you for reporting this. I'll have to think of whether there would be a good solution for this case.

Quick question: is this for simple databind usage, where expected type is `boolean` or `Boolean`, and you are not directly using accessors? (if you were, you could use different check to only accept actual JSON true/false).

**Comment by pavankumar-parankusam** [comment]
Yes it is slow in parsing for simple databind usage where expected type is boolean or Boolean.

**Comment by pavankumar-parankusam** [comment]
@cowtowncoder Hi, Any update on this issue?

**Comment by cowtowncoder** [comment]
No, haven't had time to work on this.

**Comment by cowtowncoder** [comment]
Note: PR is #1405.

**Comment by cowtowncoder** [comment]
Hmmh. Ok, I'll use the idea from PR, although I have some concerns about effects on other formats where this probably slows things down. However, this coercion should not be very common so probably it's ok, protecting against rare case of malicious (?) big-int.
