### ISSUE TITLE
New @JsonPOJO(getPrefix="get", setPrefix="set") annotation

### ISSUE THREAD

**Issue by tetv** [FasterXML/jackson-databind#1325]
New enhancement: Adding a new annotation `@JsonPOJO(getPrefix="get", setPrefix="set")` to customise the get and set property prefix that Jackson is expecting by default, identical to the withPrefix feature on `@JsonPOJOBuilder` annotation.

**Comment by cowtowncoder** [comment]
Closing in favor of #2674.
