### ISSUE TITLE
Disable Jackson mapper for a particular annotation

### ISSUE THREAD

**Issue by yamsellem** [FasterXML/jackson-databind#133]
With Jackson, it's easy to disable all annotations for a given `ObjectMapper`. Is there a way to only disable one given annotation?

``` java
// disable all
ObjectMapper mapper = new ObjectMapper()
mapper.disable(MapperFeature.USE_ANNOTATIONS);

// disable one?
ObjectMapper mapper = new ObjectMapper()
mapper.disable(@JsonIgnore);
```

Using `@JacksonAnnotationsInside`, I've defined a custom Jackson annotation and I only want it to be used in certain circumstances.

**Comment by mjball** [comment]
If you're not using Jackson 2.6 yet, this annotation introspector seems to work well for disabling a specific annotation (`@JsonUnwrapped` in this case; other annotations not tested):

```java
class IgnoreJsonUnwrappedAnnotationInspector extends JacksonAnnotationIntrospector {
  @Override
  public NameTransformer findUnwrappingNameTransformer(AnnotatedMember member) {
    return null;
  }
}
```

**Comment by desoss** [comment]
Is there any solution to this problem with the newest Jackson versions?

**Comment by yawkat** [comment]
yes, the AnnotationIntrospector api still allows you to hook into annotation analysis.
