### ISSUE TITLE
Remove final modifier from Standard Implementation

### ISSUE THREAD

**Issue by driverpt** [FasterXML/jackson-databind#1330]
Is it possible to remove final Modifiers from Standard Implementation Classes, e.g.: StringDeserializer.

For example, the only thing i want to do is augment the result from that serializer. Like for example, if it's an empty string, just return Null.

**Comment by cowtowncoder** [comment]
It is technically possible, but in this particular case I would just suggest you re-implement it. Removal would be possible for 2.9, and with release cycle that will take a while.

**Comment by cowtowncoder** [comment]
Removed `final` from 2.9.0.
