### ISSUE TITLE
JSONInclude(Include.NON_DEFAULT) does not work for boolean if default value is True

### ISSUE THREAD

**Issue by JFulgoni** [FasterXML/jackson-databind#1331]
Jackson version 2.7.4

I found an issue upon creating an POJO, where the JSON returned by ObjectMapper.writeValueAsString(), that the annotation JSONInclude(Include.NON_DEFAULT) doesn't work if the default value for a boolean is true. I believe that the PropertyBuilder class is using the default value for the boolean primitive (false) as the default, instead of the value used in the POJO's defauly constructor.

I uploaded an [example here](https://github.com/JFulgoni/Java-Practice/blob/master/DefaultSerializeTest.java) which illustrates the problem further.

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Your explanation makes sense.
I hope to look into this problem soon, but there is bit of a backlog for bugs, so I just wanted to mention that I saw the report and it seems to contain enough information to reproduce the problem.

**Comment by JFulgoni** [comment]
Sounds good. Thanks for the quick response!

**Comment by cowtowncoder** [comment]
Actually, sorry, I was wrong. Behavior is as intended, as of 2.7 and later.

Meaning of `NON_DEFAULT` is bit different depending on where it is used:

1. When used as class annotation for a POJO, it specifies use of property values from default POJO instance -- so in your case, expected values would be `true` and `false`.
2. When used as global per-type default (2.8 only feature), or for individual property, default value for that type is used: in case of `boolean` it is `false` (and for `Boolean`, `Boolean.FALSE`)

This is document in javadocs for `JsonInclude.Include` enumeration.

Behavior was changed to accommodate related fix for definition of `NON_EMPTY` which with 2.6 included `0` for numbers: for 2.7 "emptiness" was more strictly defined to only include empty `Collection`s, `Map`s, arrays and `String`s. `NON_DEFAULT`, however could now be used to exclude default-valued scalar types.

So: this is a behavioral change and not a bug. Apologies for confusion.
