### ISSUE TITLE
IndexOutOfBoundException on enum by index deserialization

### ISSUE THREAD

**Issue by fizmax** [FasterXML/jackson-databind#1333]
You get index out of bound exception during deserialization of enum by index if you provide index equal to number of Enum elements. Even if `READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE` is enabled.

Fixed in https://github.com/FasterXML/jackson-databind/pull/1332 with some tests.

**Comment by fizmax** [comment]
Should be fixed in 2.7.7

**Comment by zEvg** [comment]
@cowtowncoder,
Any plans to release `2.8.x` (`2.8.2`?) with this fix ?

**Comment by cowtowncoder** [comment]
@zEvg Yes, 2.8.2 should be released this week, since 2.7.7 was just released.

**Comment by zEvg** [comment]
@cowtowncoder, thanks!
