### ISSUE TITLE
Wiki: JacksonTreeModel page is missing.

### ISSUE THREAD

**Issue by sirtobey** [FasterXML/jackson-databind#1336]
Hello guys

I am a little confused about this wiki page about JacksonTreeModels:

https://github.com/FasterXML/jackson-databind/wiki/JacksonTreeModel
 
All content I get is 
> eee
and the commit history seems to fail to load. There are only a few commits, adding and removing content I cannot look at.

Can someone clear this us? Is there a chance to get the content back? Thanks

**Comment by cowtowncoder** [comment]
That wiki page was part of experimental automated import (from real FasterXML wiki). I'll delete it, thanks!
