### ISSUE TITLE
Dynamic deserialization filtering

### ISSUE THREAD

**Issue by reda-alaoui** [FasterXML/jackson-databind#1352]
Hello,

In our project we need to be able to dynamically filter on serialization and deserialization some properties based on current user clearances.

It seems there is no way to do that for deserialization.

Could it be implemented? With @JsonFilter maybe?

Regards

**Comment by cowtowncoder** [comment]
@reda-alaoui Excellent questions for the mailing list. But not so much for issue tracker.

**Comment by reda-alaoui** [comment]
Hello @cowtowncoder , 
in fact, this was a feature request.

I admit that my message was not clear enough.

I know that @JsonFilter only works from Java to JSON.
Can we modify Jackson to make it work from JSON to Java?

Regards

**Comment by cowtowncoder** [comment]
@reda-alaoui I am open to ideas of how it might work, but the immediate problem is that the API itself is design on serialization and would not work as-is for deserialization.

So the challenge would be suggesting how system should work, from user perspective.
