### ISSUE TITLE
JsonSerializer needs extra field information

### ISSUE THREAD

**Issue by hbprotoss** [FasterXML/jackson-databind#1354]
I have a class like this

```
class A {
    @SomeAnno()
    private SomeType field;
}
```

and a registered JsonSerializer with type `SomeType`

```
private class DateJsonSerializer extends JsonSerializer<Object> {

	@Override
	public void serialize(Object value, JsonGenerator gen, SerializerProvider serializers) throws IOException, JsonProcessingException {
		
	}
}
```

My question is: how can I get the `@ SomeAnno` in method `serialize `?

**Comment by cowtowncoder** [comment]
@hbprotoss Please use mailing lists for usage questions:

https://groups.google.com/forum/#!forum/jackson-user

the answer to the specific question is "you can not"; this is not the right place to access that information. But for follow-up discussion of how to achieve what you trying to do (which is doable, just not using this approach) let's use mailing list.
