### ISSUE TITLE
UnrecognizedPropertyException  - ignore by default?

### ISSUE THREAD

**Issue by ericn37** [FasterXML/jackson-databind#1365]
Version used:
com.fasterxml.jackson.core:jackson-annotations:2.7.0
com.fasterxml.jackson.core:jackson-core:2.7.1
com.fasterxml.jackson.core:jackson-databind:2.7.1

Every time the server introduces a new property and it hasn't been communicated to me, my app breaks due to this exception.
Shouldn't all the properties be ignored by default?
For example, a User class has "name" and "gender" and it has been working fine. Why should my app break when the server returns a new property "religion" for example?

**Comment by cowtowncoder** [comment]
@ericn37 This is an issue tracker, not a discussion forum. Please use mailing list (`jackson-user` Google group) for usage questions, or philosophical discussion on whether or not behavior for unmappable properties should throw exception, or quietly swallow and likely cause harder to diagnose failures.
