### ISSUE TITLE
Add `MapperFeature.INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES` to allow disabling use of `@ConstructorProperties` as explicit `@JsonCreator` equivalent

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1371]
One challenge with frameworks like Lombok, auto-values and Immutables is that they often automatically (or at least by default) add ~~JDK7~~ JDK6 `@ ConstructorProperties ` annotation for constructor(s). This makes sense, in general, but may be problematic for Jackson since as of 2.8 that is equivalent to specifying `@JsonCreator`, which may not always be what is intended.

One thing that can help resolve issues is to add a new `MapperFeature`, enabled by default, that determines whether `@ ConstructorProperties ` means same as explicit `@JconCreator` (enabled) or not (disabled). If not, parameter names are still available as implicit names, and explicit `@JsonCreator` may be used.

Note that this requires #1369 as well.

**Comment by tsabirgaliev** [comment]
@cowtowncoder can this be backported to 2.8 branch? 2.9 is not released, and this caveat is causing  headaches with Lombok, and is not very easy to identify

**Comment by cowtowncoder** [comment]
@tsabirgaliev Unfortunately it being an API addition it can not be backported.

**Comment by electrum** [comment]
The issue description and release notes seem to typo, as the annotation is `@ConstructorProperties`, not `@CreatorProperties`. Also, it was introduced in JDK 6, not 7.

**Comment by cowtowncoder** [comment]
@electrum thank you, I will fix title. But as to JDK... wow. You are right, javadocs do confirm it was in JDK 6. Not sure how I misread that, but it was added in JDK 7 module.

**Comment by electrum** [comment]
Thanks, I see you updated the tittle, but there are a couple other references in the description, too.
