### ISSUE TITLE
Ignore custom serializer in root

### ISSUE THREAD

**Issue by reinaldo-besen** [FasterXML/jackson-databind#1397]
Hello,

I would suggest improvement, the option to disregard the application of specific serializer on the type of the object when it is the root.

Example:

```
class MyClass
{
    String field;
    MyClass reference;
}
```

```
SimpleModule module = new SimpleModule();
module.addSerializer(MyClass.class, new CustomSeserializer());
MyClass o = new MyClass();
mapper.writeValueAsString(o);
```

In this scenario I wish the object to be serialized without using the custom serializer, it is the root object, but that the field use the serializer.

I know the fact that via annotation in the field is a way to solve, but this setting is applied via runtime programming and must apply to all properties of type.

Now I resolved this situation by creating a custom serializer generic testing if the root is to call or not the specific serializers.

The suggestion is to create a global setting in SerializationFeature class to set this setting.

Thanks for your help.

**Comment by cowtowncoder** [comment]
Ok, I think I understand the request.

I don't know if there is an easy way to achieve this, since serializer/deserializer resolution system has no knowledge of context, to make this determination. But perhaps there is a way; if I can think of something I will add notes here.

From custom serializer it would actually be possible to determine, since `createContextual()` will be called with `null` as `BeanProperty` argument.

**Comment by Krivda** [comment]
just if somebody happen to be here, i've implemented this idea in this way

`public abstract class RootAwareBeanSerializer<T> extends BeanSerializerBase {

// skipped boilerplate

    public void serialize(Object bean, JsonGenerator jgen,
                          SerializerProvider provider) throws IOException {

        if (bean == null || !this.javaType.isTypeOrSubTypeOf(bean.getClass()))
        {
            @SuppressWarnings("unchecked")
            T object = (T) bean;

            jgen.writeStartObject();
            if (this.isRoot) {
                serializeRoot(object, jgen, provider);
            } else {
                serializeNonRoot(object, jgen, provider);
            }
            jgen.writeEndObject();
        }
    }


    protected abstract void serializeNonRoot(T bean, JsonGenerator jgen, SerializerProvider provider) throws IOException;

    public void serializeRoot(T bean, JsonGenerator jgen, SerializerProvider provider) throws IOException {

        serializeFields(bean, jgen, provider);
    }

    @Override
    public JsonSerializer<?> createContextual(SerializerProvider provider, BeanProperty property) throws JsonMappingException {

        // property == null is a criterion for serialization's root object
        if (property == null) {

            JsonSerializer ser = super.createContextual(provider, property);
            if (ser instanceof RootAwareBeanSerializer) {
                ((RootAwareBeanSerializer) ser).markAsRoot();
            }
            return  ser;
        } else {
            return super.createContextual(provider, property);
        }
    }

    private void markAsRoot() {
        isRoot = true;
    }
`

**Comment by cowtowncoder** [comment]
No plans to implement this, closing.
