### ISSUE TITLE
Deserializer collections field with pre-existing values

### ISSUE THREAD

**Issue by reinaldo-besen** [FasterXML/jackson-databind#1398]
I suggest as an improvement, be able to perform the deserialization of a pre-existing object, considered the fields that are collections, where it was possible to define a key to the collection object, and it was still possible to pass a specific comparator for the type of collection, and with this key pattern was possible to recover the existing record in the collection and deserialize the existing record, instead of adding a new record in the collection, or have the ability to set an interceptor to carry out this work to find the record and return to be used by CollectionDeserializer.

At the moment I decided this scenario creating a specialization of ColletionDeserializer class, overwriting and replicating code, which in each Jackson version update will have to revise the code to keep compativilidade, and recording it as specific deserializer collections through the module confguration by setting one BeanDeserializerModifier.

```
module.setDeserializerModifier(new BeanDeserializerModifier()
		{			
		  @Override
		    public JsonDeserializer<?> modifyCollectionDeserializer(DeserializationConfig config,
		            CollectionType type, BeanDescription beanDesc, JsonDeserializer<?> deserializer) 
		    {
				if(deserializer instanceof CollectionDeserializer)
				{
					return new CustomCollectionDeserializer((CollectionDeserializer)deserializer);
				}
				else
				{
					return deserializer;
				}
		    }
		});
````

Thanks for your help.

**Comment by cowtowncoder** [comment]
I plan to implement #1399 for 2.9, and I think that would cover this? (just created the issue -- have discussed the idea on `jackson-dev` list earlier).

**Comment by cowtowncoder** [comment]
Assuming #1399 would cover this, closing.
