### ISSUE TITLE
Add support for `@JsonSetter(merge=OptBoolean.TRUE`) to allow "deep update" 

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1399]
Currently existing values of properties are not taken into consideration, with the rare case of "setterless-getters" where this is done for `Collection` types if no setter exists.
But it would be useful to allow this for `Map`s and POJOs as well.

Proposed mechanism is to allow use of:

```java
public class POJO {
    @JsonSetter(merge=OptBoolean.TRUE)
    public List<String> names = new ArrayList<>();
    {
         names.add("first");
    }
```

In addition to per-property annotation, it should also be possible to specify "config overrides" using:

    objectMapper.configOverrides(MyPOJO.class)
         .setter(JsonSetter.Value.from(.....));

which would specify default merge/no-merge settings for properties of specified type.
It would probably also make sense to allow setting fully global default, similar to ability to set "serializationInclusion" global defaults (with `JsonInclude.Value`).

**Comment by cowtowncoder** [comment]
Initial implementation now exists, supporting POJOs, `Collection`s, `Map`s, reference types.

**Comment by heruan** [comment]
Any docs on how to test this?

**Comment by cowtowncoder** [comment]
@heruan at this point the best way I think is to search for unit tests with `@JsonSetter(merge=`.

**Comment by Tetradeus** [comment]
Wouldn't it be nice to have an option to enable setting null values at merge path ? Ref #1437 

```java

    // Also: nulls better not override
    public void testBeanMergingWithNull() throws Exception
    {
        Config config = MAPPER.readerForUpdating(new Config(5, 7))
                .readValue(aposToQuotes("{'loc':null}"));
        assertNotNull(config.loc);
        assertEquals(5, config.loc.a);
        assertEquals(7, config.loc.b);
    }

```

What if I really want to be able to set null for loc ? assertNull(config.loc);

Thanks for your reply.

**Comment by cowtowncoder** [comment]
@Tetradeus Please file a new issue; this one is closed. We can discuss details as part of that.
