### ISSUE TITLE
`@JsonFormat.pattern` is ignored for `java.sql.Date` valued properties

### ISSUE THREAD

**Issue by sangpire** [FasterXML/jackson-databind#1407]
Hi 
thank you for share a awesome library.

I am using version 2.6.7.
Here is failed test which shows that `@JsonFormat` is ignored `pattern` attribute.

``` java
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Test;
import java.sql.Date;
import static org.junit.Assert.assertEquals;

public class JsonFormatTest {

    public class Person {
        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy.mm.dd")
        public Date dateOfBirth;
    }

    @Test
    public void JsonFormatPatternTest() throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();
        Person i = new Person();
        i.dateOfBirth = Date.valueOf("1980-04-14");
        assertEquals("{\"dateOfBirth\":\"1980.04.14\"}", objectMapper.writeValueAsString(i));
    }
}
```

And the results of running the test:

```
org.junit.ComparisonFailure: 
Expected :{"dateOfBirth":"1980.04.14"}
Actual   :{"dateOfBirth":"1980-04-14"}
```

I don't know exactly the reason.
But I have a doubt in a line of code.
https://github.com/FasterXML/jackson-databind/blob/2.6/src/main/java/com/fasterxml/jackson/databind/ser/std/SqlDateSerializer.java#L36

Which method ignored the `customFormat` param.

Thank you.

**Comment by cowtowncoder** [comment]
Yes, it is likely that handling of `java.sql.Date` is missing some of newer features, and support should be added.

**Comment by sangpire** [comment]
@cowtowncoder If you agree I will implement the fix and create a PR for it, after work 😅

**Comment by cowtowncoder** [comment]
@sangpire that would be great! Let me know if you need help with sample code; existing `java.util.Calendar` handling should work as base, or (de)serializer(s) from Joda module.

**Comment by sangpire** [comment]
Sorry for annoying messages;;

**Comment by Orion-irrational** [comment]
Find the answer here https://tankauth-playful65.github.io/animated69/
