### ISSUE TITLE
3.x: Add proper typing for `TypeReference` usage in `ObjectMapper` API

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1424]
(from #1423)

Looks like `ObjectMapper` API (and perhaps `ObjectReader` too) omits type-variable matching with `TypeReference`. This would make sense to change, but is likely to cause some source-compatibility issues (not binary), so perhaps do this in 3.0 and not earlier.

**Comment by silmeth** [comment]
It seems to be fixed since 2.10 (even though this issue is labelled as 3.x).

**Comment by cowtowncoder** [comment]
@silmeth Thank you, yes I think this was done #2196.
