### ISSUE TITLE
Problem with `TypeFactory. constructSimpleType()` with generic types; regression from 2.6.x to 2.7.x

### ISSUE THREAD

**Issue by mguillet** [FasterXML/jackson-databind#1443]
Hi,

We were using a custom id resolver implementing ```TypeIdResolver``` to deserialize json looking like:

```json
{
  "_type": "int",
  "_id": "eb3c0a9d-5b7c-4f69-a6ee-7a746082a1e8",
  "deleted": false,
  "value": {
     "date": 134567890,
     "content": 42,
     "authorId": "someGuyId"
  }
}
```
Into instance of the class ```GenericValue<Integer>``` that looks like this:
  
```java
// GenericValue.java

public class GenericValue<Value> {
  
  public String _id;
  
  public boolean deleted;
  
  public WrappedValue<Value> value;

}
 
// WrappedValue.java
public class WrappedValue<Value> {
  
  public Instant;
  
  public Value content;
  
  public String authorId;

}
 ```
Here is our implementation of ```TypeIdResolver.typeFromId```

```java
public JavaType typeFromId(DatabindContext context, String id) {
  Class<?> clazz;
  if (id.equals("int")) {
    clazz = ConcreteInteger.class;
  } else if (id.equals("string")) {
    clazz = ConcreteString.class;
  } else {
    throw new IllegalArgumentException("Don't know how to map " + id + " type object");
  }

  return context.getTypeFactory().constructSimpleType(baseType.getRawClass(), new JavaType[]{context.getTypeFactory().uncheckedSimpleType(clazz)});
}
```

Since this issue is quite important for my work, I created a repository with an example that worked with versions 2.6.x and doesn't work anymore in 2.7.x.

We must be doing something wrong that was allowed in 2.6.x and not anymore in 2.7.x but I can't figure out what it is.

Here's the repo address: https://github.com/Melusyn/jackson-polymorphic-regression 

Reproducing the issue is simple, just run ```mvn test``` and you'll see tests failing.

Thanks!

Tried with these versions:
- 2.7.0, 2.7.8, 2.7.9-SNAPSHOT (fails)
- 2.8.4, 2.8.5-SNAPSHOT (fails)
- 2.6.x (works)

**Comment by cowtowncoder** [comment]
Thank you for reporting this. 2.7 did a complete rewrite of type resolution system so breakage is probably due to that. I agree that it is possible that something may have happened to work formerly, but does not due to more rigorous resolution of type variables; regardless, it is unfortunate that your code broke.

I hope to have time to investigate this soon.

**Comment by mguillet** [comment]
Thanks!

BTW, I can change my code easily if I'm doing something forbidden in 2.7+. I just don't know how...

**Comment by cowtowncoder** [comment]
@mguillet ok good. I don't see anything obviously wrong with code above, so I need to check out project. Should be easy enough to find what is needed.

**Comment by mguillet** [comment]
Thanks a lot for your help!

I'll see if I can upgrade easily to 2.8.x: we're relying a lot on Vert.x which currently uses 2.7.x. I doubt this would be too much trouble.

I'll keep you posted!

**Comment by cowtowncoder** [comment]
Ok, closing now assuming this suffices. At this point chance of updates for 2.7 is diminishing and I hope 2.7.9 shall be the last version, so update to 2.8 would be good if at all possible.

**Comment by mguillet** [comment]
Everything seems to work great with 2.8.4. I'm closing the issue.

Thanks a lot for your help!

**Comment by cowtowncoder** [comment]
Ok good!
