### ISSUE TITLE
UnrecognizedPropertyException occurs non-deterministically

### ISSUE THREAD

**Issue by ckolnik** [FasterXML/jackson-databind#1448]
Here are the classes we have for deserializing JSON that is received from a REST service.

The error we see is:

> com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "key" (class java.util.Optional), not marked as ignorable (0 known properties: ])
at [Source: [B@7b78631d; line: 1, column: 17] (through reference chain: {our-package-name}.GetResponse["item"]->java.util.Optional["key"])

```
@Data
@RequiredArgsConstructor
public class GetResponse {
    @NonNull private final Optional<Item> item;

    @JsonCreator
    private GetResponse(@JsonProperty("item") Item item) {
        this(Optional.ofNullable(item));
    }

    /* json getters for optional args */

    @JsonGetter("item")
    private Item getRawItem() {
        return item.orElse(null);
    }
}

@Getter
@RequiredArgsConstructor(access = PRIVATE)
@EqualsAndHashCode(exclude = "value")
public class Item {

    private final String key;
    private final Map<String, Object> value;

    @Builder
    @JsonCreator
    public static Item of(
            @JsonProperty("key")   String key,
            @JsonProperty("value") Map<String, Object> value
    ) {
        if (StringUtils.isNullOrWhitespace(key)) {
            throw new IllegalInputException("Item - key must be non-null and non-empty!");
        }

        if (value == null) {
            throw new IllegalInputException("Item - value must be non-null!");
        }

        if (value.isEmpty()) {
            throw new IllegalInputException("Item - value must not be empty! If you want to delete, " +
                                            "don't put an empty value, call the Delete API.");
        }

        return new Item(key, value);
    }
}

//ObjectMapper
final ObjectMapper mapper = new ObjectMapper().configure(MapperFeature.USE_ANNOTATIONS, true);

//Deserialization
final GetResponse result = (GetResponse) this.mapper.readValue(postData, GetResponse.class);
```

Sample JSON that causes the issue but doesn't cause the issue when we created a unit test no matter what we do.

String format:

`"{\"item\":{\"key\":\"1/1/foo/man,shoo/bar\",\"value\":{\"category\":\"Blurb\",\"something\":\"hello\",\"mid\":1,\"priority\":23,\"payload\":\"helloworld/blahblahblah+XL+interestingdata/moreinterestingdata+V+value\",\"sid\":123456789,\"valueType\":\"mytype\",\"someId\":\"1234567890/1/ABCDEFGH/U123456,UPOLHYU/2016-0927T00:00Z\",\"ANOTHER_VALUE\":\"OIUPYT,QWERTY\",\"aType\":\"sometype\",\"additionalIdentifiers\":[\"GHYTUIOD\",\"GBNYERT,MNJGKHI\"],\"val\":\"GJEURIOSPF\",\"effectiveDate\":1474934400000}}}"`

JSON:

`{
  "item": {
    "key": "1/1/foo/man,shoo/bar",
    "value": {
      "category": "Blurb",
      "something": "hello",
      "mid": 1,
      "priority": 23,
      "payload": "helloworld/blahblahblah+XL+interestingdata/moreinterestingdata+V+value",
      "sid": 123456789,
      "valueType": "mytype",
      "someId": "1234567890/1/ABCDEFGH/U123456,UPOLHYU/2016-0927T00:00Z",
      "ANOTHER_VALUE": "OIUPYT,QWERTY",
      "aType": "sometype",
      "additionalIdentifiers": [
        "GHYTUIOD",
        "GBNYERT,MNJGKHI"
      ],
      "val": "GJEURIOSPF",
      "effectiveDate": 1474934400000
    }
  }
}`

Jackson versions:
Jackson-annotations  2.8.x;
Jackson-core = 2.8.x;
Jackson-databind = 2.8.x;

The problem is that this only happens like 1/30 times on application startup and once a host starts up and has the issue it continues to have the issue. If we restart the host the issue appears to go away.

Are there issues with Lombok constructors and JsonCreator that could be causing this? Are Optionals causing an issue? Any help is appreciated.

**Comment by cowtowncoder** [comment]
That sounds like a tricky problem. From symptoms it sounds as if a deserializer was being used before it was fully completed (there are multiple phases in initialization of a deserializer, due to need to resolve possible cyclic dependencies). I am not aware of specific pathways where this should or was known to happen, but it certainly like somehow this was possible.

I don't know of specific issues wrt `Optional` either, or static factory (creator) methods.

On reproduction: best change would probably be a stand-alone class with main method, with multiple threads. But if this is due to initialization, it should happen with the first call of one of threads.

One other minor problem is that I think error message is misleading, wrt class where this occurs.
As far as I can see that should be reported as `Item`.

Could you also share bit more of stack trace, if you still have it?

**Comment by ckolnik** [comment]
Stack trace. Incomplete but I can get more if it would help.

`at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:833)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1096)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1467)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1445)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)`

Of note, the deserialization is happening in a heavily parallelized bunch of tasks where we fetch data from different services. Is there a way for us to force the initialization at startup?

We are sharing the object mapper between a lot of different spring beans where the REST accessing and deserialization occurs. Should we create an object mapper for each of the accessors?

**Comment by cowtowncoder** [comment]
@ckolnik Thanks. I realized that the trace probably won't quite give info what I was hoping, since presumably deserializer access is now complete, and not in call path any more.

I think it should be possible to force early initialization; only thing needed is to make sure that the specific deserializer in question gets exercised; and doing this before any real concurrent usage may occur.
This should work around the problem.
So, feed bit of fake json to trigger initialization and caching of deserializers and things should work.
Obviously this should not be necessarily at all but... at least it'd allow working through the issue for now.

**Comment by ckolnik** [comment]
Thanks for the quick responses. When you say I should feed fake json to trigger initialization at ObjectMapper construction time should I do it for all of the specific classes (i.e. GetResponse, Item, etc.)  that we are deserializing or will any json suffice?

**Comment by cowtowncoder** [comment]
@ckolnik it has to be for classes that trigger the problem; each deserializer is cached separately. However, it should not be necessary for "child" types; that is, anything that is directly referenced by, say, `GetResponse` class, should have deserializer fetched as well. So I would start by root type, and that should suffice. As to mock json, simple `{ }` may suffice, and you can (temporarily) enable `ignore all unknown properties` if you do not normally enable it.

**Comment by cowtowncoder** [comment]
Can not reproduce; falls in general class of similar sounding issues, so I suspect that somehow set of recognized properties is changed to not include expected entries. But without reproduction not much to follow on. I do keep this in mind however.

As to work-arounds: use of separate `ObjectMapper`s does help, but really should not be necessary. Perhaps `ThreadLocal` would make sense.

As to forcing pre-creation: any code that uses serializers/deserializers during startup, before multi-threaded access should work. Just need to make sure recursive types gets handled (some lookups are dynamic, esp. for serialization). This might help.
