### ISSUE TITLE
JsonFormat doesn't use TimeZone#getDefault()

### ISSUE THREAD

**Issue by artemik** [FasterXML/jackson-databind#1452]
Bug.
Jackson: 2.8.4

As it's said in the JsonFormat annotation java docs, Jackson will use TimeZone#getDefault() if no timezone specified in the annotation value, but it doesn't, until this default timezone is set to the object mapper used.

**Comment by cowtowncoder** [comment]
I need to fix the javadocs; UTC is the default, not default timezone. Thanks.
Will need to re-file at annotations since that's where javadocs live.

**Comment by cowtowncoder** [comment]
Moved to: https://github.com/FasterXML/jackson-annotations/issues/106

**Comment by artemik** [comment]
@cowtowncoder Thanks.
