### ISSUE TITLE
`@JsonAnyGetter` should be allowed on a field

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1458]
(follow-up from https://github.com/FasterXML/jackson-annotations/issues/107)

Would be nice to allow use of `@JsonAnyGetter` on fields too; javadocs already claim this is possible.
So should add support for allowing that. Note that the counterpart, `@JsonAnySetter` does allow use on field already.

**Comment by cowtowncoder** [comment]
While not trivial to implement, this seems like something moderately challenging to implement -- but something users would like to see.

**Comment by dominikrebhan** [comment]
Hi, 

I would like to take this issue. I already lookup up in the code and I think it should be done within the classes @JsonAnyGetter, BasicBeanDescription and  POJOPropertiesCollector. The outgoing type of AnnotatedMember is already present and it should be simply extendable for fields.

Best regards.

**Comment by cowtowncoder** [comment]
@dominikrebhan Go for it! This would be a good improvement.

I think you'll want to start with 2.12 branch (3.0 is too far out, `master` is tracking that). I just released 2.12.0-rc1, but there is still time -- and if it needs to go against 2.13 due to timing I can help.

**Comment by dominikrebhan** [comment]
I added the first pull requests. Could you please take a look at a first glance?

**Comment by cowtowncoder** [comment]
PR looks good; added notes wrt cla, happy to merge!

**Comment by cowtowncoder** [comment]
Was merged, will be in 2.12.0.
