### ISSUE TITLE
com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer#deserialize tries to add values to unmodifiable list returned from an object's getter.

### ISSUE THREAD

**Issue by hknbh** [FasterXML/jackson-databind#1466]
I have a getter which returns an unmodifiable string list (Collections.unmodifiableList) and while deserializing a JSON response, StringCollectionDeserializer throws an UnsupportedOperationException because it tries to add values to this list. I think this is particular for Strings because I have other getters which return some other typed unmodifiable lists and I have no problem at all.

**Comment by cowtowncoder** [comment]
Without actual reproduction I can't be sure, but I strongly suspect you do not have a setter or matching field, and thereby the only way to add anything would be to call `add`. This is as designed, and it is your responsibility to make sure list is mutable. There isn't any reliable way to detect JDK's immutable lists; and even if there was, you haven't provided any way to override it.
You can, however, prevent any usage of getters "as setter" by disabling `MapperFeature.USE_GETTERS_AS_SETTERS`: if so, you'll get an exception indicating the problem.

Anyway: if above suggestion is not correct (disabling feature has no effect), I'd need a reproduction to see what is going on, with Java classes used and deserialization call, and sample JSON.

**Comment by hknbh** [comment]
I was missing a setter to keep the class immutable. Adding a setter resolves the problem indeed.

Closing the issue since it is invalid.
