### ISSUE TITLE
Explicit property is not deserialized when parent has shadowing fields (with Proguard - dangerous)

### ISSUE THREAD

**Issue by ndori** [FasterXML/jackson-databind#1469]
Hi,
I'm an android developer and I'm using Proguard and Jackson in my production app.

I came across a bug which was amplified by Proguard obstruction. 

I'll give you the full example so you can check it.

    public class MainActivity extends AppCompatActivity { @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        try {
            A a = objectMapper.readValue("{\n" +
                    "  \"Type\": \"B\",\n" +
                    "  \"Hello\": \"hello\",\n" +
                    "  \"World\": \"world\",\n" +
                    "  \"Other\": \"other\"\n" +
                    "}", A.class);
            Log.e("debug", "a.getStr()=" + a.getStr() + " a.getOther()=" + a.getOther());
            Log.e("debug", " is instaceof b:" + (a instanceof B));
        } catch (Exception e) {
            Log.e("debug", "error", e);
        }

    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "Type",defaultImpl = A.class, visible = false)
    @JsonSubTypes({
            @JsonSubTypes.Type(value = B.class, name = "B")
    })
    public static class A {
        @JsonProperty("Hello")
        private String str;

        public String getStr() {
            return this.str;
        }

        @JsonProperty("Other")
        private String other;

        public String getOther() {
            return other;
        }
    }

    public static class B extends A {
        @JsonProperty("World")
        public String str;
    }}

I used logs for easy debugging, 
In this scenario a.getStr() will return "null". I would expect it to be "hello".

This is not the expected behaviour, shadowing is allowed (even if discharged) by java,
if we will remove the  FAIL_ON_UNKNOWN_PROPERTIES line it will throw an error as it did not managed to deserialize "Hello"

This problem is a real one, and that because most of android developers use ProGuard.

In my original code, there was no shadowing, there was a "hello" field in class A, and a "world" field in class B.
However proguard changed both of their names to "a", and that because it is valid in Java and should not cause any problem.

So you can understand how this issue can become very real, moreover as proguard is not usually used in debug flavor this problem will be really hard to find and fix.

My workaround was to change the "hello" to be a protected field, this way proguard will give them different names, but this can actually happen with every private field!

Another workaround might be to explicitly tell proguard to keep all the classes that uses Jackson as is, but for my taste it is a bad workaround that will force one to constantly update the proguard config file.

I will be happy to add any other information you might need.

Tnx, Nitzan

**Comment by cowtowncoder** [comment]
First things first: I would suggest enabling `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES`: disabling it will hide problems making it much more difficult to find out the problem.
In this case, for example, it's very likely that something is mismatching. Users tend to disable this setting without quite understanding what it does.

Use of masking variables (ones with same name) seems like a bad idea to me: I am not quite sure why you are doing that. But if you do, it would make more sense to have a setter method (which may be `private` if you don't want it to be called) as method overriding works much more reliably than relying on specific field instance being used.

As to which field should be used: in case of overrides, it should be that field from sub-class; but due to complexity of name shadowing and annotations it is somewhat hard to reason about.

**Comment by ndori** [comment]
> First things first: I would suggest enabling DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES: disabling it will hide problems making it much more difficult to find out the problem.
In this case, for example, it's very likely that something is mismatching. Users tend to disable this setting without quite understanding what it does.

I do understand what it does, and I do it on purpose and relays on it. 
the main reason is backward compatibility without the need of managing versions: 
let's say we have an object person:
`class person { public String name;}`
so the json will only send the "name" keyValue.
however on the next version we want to add last name as well, so the new object will be
`class person { public String name; public String lastName;}`
and the new json will also send "lastName" keyValue, but if I will not use  DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES , than the older version will break.
I can make sure to send in each version only the "used" attributes, but that's in my taste not a very good way to solve this as it is very un-robust, I prefer to send "extra" data.

this can get complicated even more if I send this Json to several different platforms which I might add "optional" KeyValues that only some platforms might care about.

In the end, I prefer to send one consistent Json to all the platforms and versions, and not manage it.   

> Use of masking variables (ones with same name) seems like a bad idea to me: I am not quite sure why you are doing that. But if you do, it would make more sense to have a setter method (which may be private if you don't want it to be called) as method overriding works much more reliably than relying on specific field instance being used.

I've actually written what happened here. I'm not masking variables, it happens by ProGuard, which is a tool of obstruction that is widely used in the Android World:

> This problem is a real one, and that because most of android developers use ProGuard.

In my original code, there was no shadowing, there was a "hello" field in class A, and a "world" field in class B.
However proguard changed both of their names to "a", and that because it is valid in Java and should not cause any problem.

So you can understand how this issue can become very real, moreover as proguard is not usually used in debug flavor this problem will be really hard to find and fix.

**Comment by cowtowncoder** [comment]
@ndrori ok, good luck solving the issue. I don't have time to figure out name-shadowing caused by a 3rd party tool.
