### ISSUE TITLE
Unable to override default collection serializer isEmpty

### ISSUE THREAD

**Issue by Roleek** [FasterXML/jackson-databind#1470]
I am using version 2.8.4. I am trying to have more fine control on what is considered empty than what is provided by JsonInclude.Include.NON_EMPTY.  (NON_DEFAULT does not work for my specific case.) Somehow BeanSerializerModifier never gets CollectionSerializer as "serializer" argument to modifySerializer. Though it gets IntegerSerializer, LongSerializer, BooleanSerializer, StringSerializer. It does not make sense to me. I only get BeanSerializer in addition to the listed above. Is there a way to override default CollectionSerializer isEmpty method?
That is the code.
```
SerializerFactory serializerFactory = BeanSerializerFactory
                    .instance
                    .withSerializerModifier(new MySerializerModifier());
        objectMapper.setSerializerFactory(serializerFactory);
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
        
public class MySerializerModifier extends BeanSerializerModifier {
       @Override
       public JsonSerializer<?> modifySerializer(SerializationConfig config, BeanDescription beanDesc, JsonSerializer<?> serializer) {
           if (serializer instanceof CollectionSerializer) {
               return new JacksonContextResolver.SerializerWrapper((JsonSerializer<Object>) serializer) {
                   @Override
                   public boolean isEmpty(SerializerProvider provider, Object value) {
                       return value == null;
                   }
               };
           }

           if (serializer instanceof BooleanSerializer) {
               return new JacksonContextResolver.SerializerWrapper((JsonSerializer<Object>) serializer) {
                   @Override
                   public boolean isEmpty(SerializerProvider provider, Object value) {
                       return value == null || !((Boolean) value);
                   }
               };
           }
           return serializer;
       }
   }

   public class SerializerWrapper extends JsonSerializer<Object> {
       protected final JsonSerializer<Object> defaultSerializer;

       public SerializerWrapper(JsonSerializer<Object> defaultSerializer) {
           this.defaultSerializer = defaultSerializer;
       }

       @Override
       public void serialize(Object value, JsonGenerator gen, SerializerProvider serializers) throws IOException, JsonProcessingException {
           defaultSerializer.serialize(value, gen, serializers);
       }
   }

   public class SerializerWrapper extends JsonSerializer<Object> {
       protected final JsonSerializer<Object> defaultSerializer;

       public SerializerWrapper(JsonSerializer<Object> defaultSerializer) {
           this.defaultSerializer = defaultSerializer;
       }

       @Override
       public void serialize(Object value, JsonGenerator gen, SerializerProvider serializers) throws IOException, JsonProcessingException {
           defaultSerializer.serialize(value, gen, serializers);
       }
   }

**Comment by Roleek** [comment]
There is method modifyCollectionSerializer.

**Comment by cowtowncoder** [comment]
Correct.

Also, with 2.8, it may be more convenient to use the new "config overrides" approach:

```java
        mapper.configOverride(List.class)
            .setInclude(JsonInclude.Value.construct(JsonInclude.Include.NON_EMPTY, null));
```

where overrides need to be for nominal (declared) type of the property (meaning it may sometimes be necessary to register multiple ones).
But you can also specify inclusion both for `value` (`List`) -- first argument -- and `contents` (second argument), similar to annotation.

**Comment by Roleek** [comment]
Thank you for the advice. Though, in my case, I need to have the same behavior for all collections. As far as I understand this overrides serialization for specific class and won't work for subclasses of the class.

**Comment by cowtowncoder** [comment]
@Roleek It's somewhere in between, as it depends on how serializer access information. In case of `List` it should apply to all standard JDK `List` implementations, but not necessarily for 3rd party ones (like Guava immutable Lists) since it requires support from serializer itself.

I mention this for sake of completeness, whatever works best for you makes sense.

**Comment by Roleek** [comment]
@cowtowncoder, Thanks. Good to know.
