### ISSUE TITLE
Incorrect schema generation for `ByteArraySerializer`

### ISSUE THREAD

**Issue by rlhagen** [FasterXML/jackson-databind#1471]
Byte arrays are serialized as a Base64 encoded string but the schema returns an integer array type for JSON.  Looks like this was introduced with this commit...

https://github.com/FasterXML/jackson-databind/commit/4a97f183bc30120ecd9deca20ffd28c834d4950f#diff-69eafe4d22a0f413f6f40bf42021b34b

According to the comments in the code, it looks like someone is attempting to convey the schema in terms of Java instead of leaving the schema in terms of the JSON language.  It is a JSON String so the schema should be a string for a Java byte [].  It is up to the binding library to map JSON data types to data types for that particular language.  Not adhering to this will break binding libraries for other programming languages.

**Comment by cowtowncoder** [comment]
JSON Schema is such a piece of shit unfortunately. :-(

As to specific thing I don't know. If there is a way to indicate physical type (String) and intended logical type (byte array), that would be optimal.

The specific reason for the change is/was not related to JSON Schema generation, but to make it possible to use introspection callbacks (which are used also for JSON Schema, but not only for that -- despite naming of types that might suggest this) and get knowledge of intended logical type.
So further changes would need to achieve both goals; JSON Schema generation of type expected, and passing of actual model types in Java.

**Comment by rlhagen** [comment]
JSON schema does not make any sense in my book.  If you want a strict language then use XML.  But unfortunately we have some people that expect the equivalent of an XML schema for JSON.  

So are you saying this is just a bug in Jackson JSON Schema module?  Because it is certainly returning the wrong schema.

**Comment by cowtowncoder** [comment]
@rlhagen I was about to say yes, this is most likely. But then I realized one thing: perhaps you are using the old method where `JsonNode` is generated, instead of `jackson-module-jsonSchema`? That system is obsolete and deprecated, but should remain operable during 2.x. If your problem is here, it may be easier to fix. Conversely most testing has gone to try to make module work better.
So you may also want to see if using module could work for you, beyond this particular issue.

I would still love to have a snippet of code showing usage, expected outcome. That would make it easier to fix it.

And also thank you for reporting the issue. While I find it frustrating to deal with JSON Schema, it is something that should work as expected.

**Comment by rlhagen** [comment]
@cowtowncoder, I really appreciate your time on this issue.  I am using the `jackson-module-Schema` and at some point I tried the deprecated methods you suggested and got the same result.  I have attached a Maven project with the minimal code.

[json-schema-generator.zip](https://github.com/FasterXML/jackson-databind/files/646506/json-schema-generator.zip)

I expect the `payload` field to be a string and not an int[].  JSON Schema is fairly limited in expression so I think the best you can do is define a Java byte[] as a JSON string with a regex for base64 encoded.  Something like below...

`{
  "type" : "object",
  "id" : "urn:jsonschema:com:ingenu:Application:Pojo",
  "properties" : {
    "payload" : {
      "type" : "string",
      "pattern" : "^\s*(?:(?:[A-Za-z0-9+/]{4})+\s*)*[A-Za-z0-9+/]*={0,2}\s*$"
    }
  }
}`

The pattern would only be needed for validation and that is not needed in the short term.

**Comment by cowtowncoder** [comment]
At this I have to say I don't know what to do here. I am not happy with the idea of logical byte array being represented as `String` without some means to convey that it is actually base64-encoded.
And yet I don't know how to get that across. Also worth of note is that change itself was necessary to support generation of useful Protobuf and Avro schemas (with respective data format modules), so it is not as simply as undoing change.

**Comment by cowtowncoder** [comment]
Not sure what could be done here, closing.
