### ISSUE TITLE
Method name starting with 'is_...' is adding as a property in Json while converting plain java object to json

### ISSUE THREAD

**Issue by dipak-pawar** [FasterXML/jackson-databind#1472]
I have a java class as follows:
```
public class MyValue {
  public boolean isValue(){
    return true;
  }
}
```
While converting it to Json using following code:
```
ObjectMapper mapper = new ObjectMapper();
mapper.writeValueAsString(new MyValue());
```
*Actual Result*
It is displaying `{"value": true}`

*Expected Result*
It should display `{}`. 

Is this assumption method name starting with `is` should be added as a property in json while implementing library?
 
I am using `jackson-databind:2.6.4` version

**Comment by cowtowncoder** [comment]
Yes. Boolean-returning `isXxx()` methods are indeed designed to be "is-getters" and work this way.
