### ISSUE TITLE
How to make Long type field serialization to Stirng type without annotation

### ISSUE THREAD

**Issue by LaineyC** [FasterXML/jackson-databind#1477]
```java 
public class Domain{

        @JsonSerialize(using = ToStringSerializer.class)
        private Long id;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }
}
```
just can be format as {"id":"3123123213213213121"}
but i don't want to do it
i want to format another way that only java code (no annotation)
```java
        ObjectMapper objectMapper = new ObjectMapper();
        // ......
        //code here
        //maybe can register Domain type, then implements a interface about Domain property
        // ......
        Domain domain = new Domain();
        domain.setId(3123123213213213121L);
        objectMapper.writeValueAsString(domain);
```
who can help me,  thanks!!!

**Comment by cowtowncoder** [comment]
Just to make sure I understand: you would like to force serialization of a number-valued (like `Long`) property as a JSON String, instead of JSON number?

**Comment by LaineyC** [comment]
@cowtowncoder I want to force serialization of a number-valued (like Long) property as a JSON String!(not through annotation)

**Comment by cowtowncoder** [comment]
@LaineyC There is `JsonGenerator.Feature.WRITE_NUMBERS_AS_STRINGS`, enabling of which will do what you ask.
