### ISSUE TITLE
Ability to ignore keys when deserializing maps

### ISSUE THREAD

**Issue by moodysalem** [FasterXML/jackson-databind#1479]
I'm using [JSOG](https://github.com/jsog/jsog) as my ID generator, and I have some classes that I'd like to serialize/deserialize that contain Maps of enums to other classes.

e.g.
```
@JsonIdentityInfo(generator = JSOGGenerator.class)
public class Game extends Event {
    public enum Side {
        home, visitor
    }

    private Map<Side, GameSide> sides;

    public Map<Side, GameSide> getSides() {
        return sides;
    }

    public void setSides(Map<Side, GameSide> sides) {
        this.sides = sides;
    }
}

public class GameSide {
    // ...
}
```

Serialization works-I get an object that has the appropriate Side keys and GameSide values

However, when the client is serializing back to JSOG to send to the server, it treats the map like any other object and adds an `@id` key with a string value to the map, e.g. `"@id":"239"`.

 Jackson chokes on this because 1. the key is not a valid enum value and 2. the value cannot be deserialized to a GameSide.

I tried registering a custom deserializer for the first issue

```
    public static class Deserializer extends KeyDeserializer {
            @Override
            public Object deserializeKey(String key, DeserializationContext ctxt) throws IOException {
                try {
                    return Side.valueOf(key);
                } catch (Exception e) {
                    return null;
                }
            }
        }
```

However returning `null` does not exclude the key from the map and the `GameSide` is still deserialized, which causes an error because the value is the `@id` of the map. I need a way to say skip this key on the map in my KeyDeserializer or a property on the `@JsonDeserialize` annotation (e.g. `ignoreUnknownKeys` similar to `ignoreUnknownProperties` for maps)

**Comment by moodysalem** [comment]
I think after reading over this a simple solution would be to skip the key if null is returned, though I don't know if there are any real use cases to having a null map key since that's not valid JSON

**Comment by moodysalem** [comment]
I think I was able to work around this by defining a `@JsonSetter` for the property sides using a value class for the single argument, with the FAIL_ON_UNKNOWN_PROPERTIES configuration set to false (so the `@id` would be ignored)

If I had free text keys for my map, I could probably do something similar with `@JsonAnySetter`

```
public class Game extends Event {
    public enum Side {
        home, visitor
    }

    private Map<Side, GameSide> sides;

    public Map<Side, GameSide> getSides() {
        return sides;
    }

    public void setSides(Map<Side, GameSide> sides) {
        this.sides = sides;
    }

    public static class HomeVisitorSides {
        private final GameSide home, visitor;

        public HomeVisitorSides(@JsonProperty("home") GameSide home, @JsonProperty("visitor") GameSide visitor) {
            this.home = home;
            this.visitor = visitor;
        }

        public GameSide getHome() {
            return home;
        }

        public GameSide getVisitor() {
            return visitor;
        }

        public Map<Side, GameSide> toMap() {
            final Map<Side, GameSide> sides = new HashMap<>();
            if (getHome() != null) {
                sides.put(Side.home, getHome());
            }
            if (getVisitor() != null) {
                sides.put(Side.visitor, getVisitor());
            }
            return sides;
        }
    }

    @JsonSetter("sides")
    public void _setSidesDeserializationWorkaround(final HomeVisitorSides sides) {
        if (sides == null) {
            this.sides = null;
        } else {
            this.sides = sides.toMap();
        }
    }
 
}
```

**Comment by moodysalem** [comment]
Sorry to post so much here-the above solution isn't quite the same because I can't tell the difference in the deserialized object between an object that has null values for its Side keys and the absence of the entirely key

**Comment by cowtowncoder** [comment]
I think `@JsonIgnoreProperties` should work for named keys, with Maps?

**Comment by moodysalem** [comment]
What if my keys are strings though? Deserialization of the value will still fail if it's a class, and worse it would put the `@id` key in the map if the value were a `String`.

**Comment by moodysalem** [comment]
I would prefer the ability to specify a key deserializer that returns null for `@id` and for the map deserializer to skip deserialization if the key is null

**Comment by cowtowncoder** [comment]
Unfortunately I don't think it is generally true that `null` is invalid key value, so it would not quite work as universal marker. In addition `KeyDeserializer` interface is simply not designed to support concept of skipping: or put another way, it is not responsible for choosing behavior other than converting from JSON key into Java Map key.
So I am not sure if there is a clean way to support filtering by key at this level.

As to:

    What if my keys are strings though? Deserialization of the value will still fail if it's a class, and worse it 
    would put the @id key in the map if the value were a String.

I am not quote sure what you mean. JSON keys are always Strings. And with respect to `@JsonIgnoreProperties`, if that mechanism was used, ignoral would only be based on JSON String key, and matching JSON value would be ignored without attempting to bind it into Java type.

**Comment by moodysalem** [comment]
How would you serialize a null key though? Seems like something Jackson might not need to support since you can't represent it with valid JSON. 

Wrt my question, I mean what if my java model, not the JSON, has string keys instead of enums. Eg. Rather than Map<Side,GameSide> I'd have Map<String,GameSide> in which case the string value for the "@id" key would fail to deserialize to a GameSide object. 

If my Map were Map<String,String>, I would still want some way to skip the "@id" key during deserialization even if it can be deserialized.

**Comment by moodysalem** [comment]
Actually, I'd like if I could just apply the `JsonIdentityInfo` annotation to the `Map`!

**Comment by cowtowncoder** [comment]
Not quite sure what would be expected at this point: I think filing a new issue for specific ask (if any) would make sense at this point.

**Comment by cowtowncoder** [comment]
@moodysalem Yeah, maybe filing a simple "support `@JsonIdentityInfo` for Maps" makes sense.
May be tricky to support, but it's good to list things that would be good have.
