### ISSUE TITLE
How to dynamically serialize property values

### ISSUE THREAD

**Issue by LaineyC** [FasterXML/jackson-databind#1481]
HTTP API URL as 
www.xxx.com/api?idFormat=number
www.xxx.com/api?idFormat=string

```java 
public class Dto{
    private Long id;
}
```
if idFormat==number, id property serialization to number“{“id”:123456789}”
if idFormat==string, id property serialization to string “{“id”:"123456789"}”

------

HTTP API URL as 
www.xxx.com/api?dateFormat=number
www.xxx.com/api?dateFormat=string

```java 
public class Dto{
    private Date date;
}
```
if dateFormat==number, date property serialization to number“{date:1483200000000}”
if dateFormat==string, date property serialization to string “{date:"2017-01-01 00:00:00"}”

------

who can help me,  thanks!!!

**Comment by cowtowncoder** [comment]
Usage questions should be sent to user list:

    https://groups.google.com/forum/#!forum/jackson-user
