### ISSUE TITLE
Add DeserializationFeature.FAIL_ON_MISSING_PRIMITIVE_PROPERTIES

### ISSUE THREAD

**Issue by DVMaslov** [FasterXML/jackson-databind#1482]
Consider pojo:
```
class Entity {
    @Getter
    private long id;
}
```
Already exists `DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES`. It prevent situation when json contains same` {"id":null}`, but if "id" property just missing, in field silent set default value - 0.

It seems logical add `DeserializationFeature.FAIL_ON_MISSING_PRIMITIVE_PROPERTIES`.

**Comment by GeorgiPetkov** [comment]
This issue is quite old and at least with the latest version 2.12.0 this is working as requested by the reporter (and I guess can be closed now).

I saw this issue while looking for duplicates of the following bug: https://github.com/FasterXML/jackson-databind/issues/2977

**Comment by cowtowncoder** [comment]
Thank you @GeorgiPetkov -- not sure how I missed this one when cleaning up old issues.
