### ISSUE TITLE
Add support for [de]serializing `boolean`/`Boolean` as character (i.e. Y or N)

### ISSUE THREAD

**Issue by jwilmoth** [FasterXML/jackson-databind#1491]
Converting some older data formats means serializing & deserializing Java's boolean fields into "T" and "F" characters. This post (http://stackoverflow.com/questions/26827343/jackson-serialize-boolean-to-1-0-instead-of-true-false) describes a custom serializer, but I believe there's value in including a couple additional serializers with the library itself.

**Comment by cowtowncoder** [comment]
No plans to change that currently: custom (de)serializers are the way to do it.
