### ISSUE TITLE
JsonNode.toString() needs clear Javadoc

### ISSUE THREAD

**Issue by 2is10** [FasterXML/jackson-databind#1492]
Looks like `JsonNode.toString()` always returns the corresponding JSON string without any whitespace. It would be helpful to state this in [its Javadoc](https://fasterxml.github.io/jackson-databind/javadoc/2.2.0/com/fasterxml/jackson/databind/JsonNode.html#toString()). Sometimes it's convenient to use this method directly (e.g. in tests).

**Comment by cowtowncoder** [comment]
Just to make sure: do you mean that it has no indentation (no white space separating tokens)?

**Comment by 2is10** [comment]
That’s right, the JSON has no whitespace between tokens. That’s just fine, and just a minor detail.

What this issue is about is the fact that the method’s Javadoc currently only says:

> Note: marked as abstract to ensure all implementation classes define it properly.

If `JsonNode.toString` is intended to return a valid JSON string (and callers can rely on that), then its Javadoc should say so.

**Comment by cowtowncoder** [comment]
@2is10 Agreed. And in fact `toString()` is NOT to provide useful json output: it should never be used for anything other than simple diagnostics. In a way it would perhaps have been better to output something obviously not-JSON. The reason `toString()` is not to be used for serialization is since it has no access to useful context; all serialization should be done via `JsonGenerator`.

And this should indeed be explained Javadoc.

**Comment by cowtowncoder** [comment]
@2is10 Um, you seem to have (accidentally?) included a link to javadocs of a rather old Jackson versions, 2.2. Later versions (2.8 and 2.7 at least) least contain updated explanation.

**Comment by 2is10** [comment]
Thanks. Sorry, we’re using 2.6.4, which didn’t have the new Javadoc. 2.2.0 was just what Google returned.

I’ll take your word for it, but I’m actually a little perplexed and curious about what context is necessary to format a JsonNode as JSON (whitespace aside). I see and understand your perspective about wanting to avoid conflating {{.toString()}} with JSON formatting, but why not have a simple method (e.g. {{JsonNode.toJson()}}) that does produce valid, whitespace-free JSON for developer convenience (e.g. in tests)? Thanks in advance.

**Comment by cowtowncoder** [comment]
@2is10 As per javadocs, seeming simplicity of `JsonNode.toJson()` will hide real problems.
Either it would be very inefficient (if creating and dumping `ObjectMapper`, or, perhaps `JsonFactory` each and every time), or leads to unintended retention of static mapper or factory.
Basic premise being that `JsonGenerator` knows how to actually write valid JSON, and this should not be duplicated (what with escaping).

This is also why there are no convenience methods to avoid passing or constructing `ObjectMapper`: stateful singletons are dangerous for general usage (but not necessarily specific usage where user knows exact scope and life-cycle; that is, app-developer can easily do it, lib-developer not so).

So I think users can easily implement suitable convenience methods.

I hope this helps.

**Comment by 2is10** [comment]
@cowtowncoder Thanks, that was helpful, but I’m still unclear what `JsonGenerator`, etc. provide above and beyond what `.toString()` already does. Are you saying that the quoting/escaping that the existing `.toString()` methods do is unreliable (doesn’t always produce valid JSON)?

I find that a little surprising, since the `.toString()` methods appear to have been written carefully with quoting/escaping in mind.

**Comment by cowtowncoder** [comment]
@2is10 no problem. I guess back in the day I wasn't sure how far to go with this, and I wish I really had only output simple identifier of node type or something. While quoting/escaping is certainly possible to make work right, there's no end to various improvements, and my experience has been that if output is useful as JSON, users start using it, and over time start asking for all the features that generator has: indentation, configurability of escaping, number precision; possible non-standard features (ability to print names unquoted); interoperability features like quoting numbers too... generator has quite a few features that are used by someone somewhere.

I do agree in that it would be useful to be able to use `toString()`, and especially so from unit tests.

**Comment by 2is10** [comment]
@cowtowncoder I see. It’s your library—I can certainly accept and respect your design choices. Thanks for all of your fantastic work!
