### ISSUE TITLE
Util method to validate if a string is JSON-able

### ISSUE THREAD

**Issue by ssdeep** [FasterXML/jackson-databind#1495]
A simple util  that can check if a given string is a valid json or not.
features
- boolean isValidJSON(String json)
- multiple keys cannot share the same name in an object scope. eg. {"foo": "value1", "foo": "value2"}
- other cases that can be updated on each release of specification.

Can be inside object mapper or be its own thing.

**Comment by cowtowncoder** [comment]
You can already do something like:

     mapper.readTree(string);

and probably want to enable `JsonParser.STRICT_DUPLICATE_DETECTION` for duplicate checks.

So what benefits would an additional method have?

**Comment by dgrahn** [comment]
@cowtowncoder If this was implemented in a way which checked for valid JSON, but didn't do anything with it, it could conceivably be quicker than mapping.
