### ISSUE TITLE
Cache POJO's structure

### ISSUE THREAD

**Issue by raderio** [FasterXML/jackson-databind#1509]
Usually we write
`User user = mapper.readValue(json, User.class);`

But in application usually these classes(User.class, ...) are the same, so everytime I read User json, library scans class to see what is the structure of class.
Maybe it will be better to scan these classes on mapper creation, and store this structure in cache, and it will be no necessary to scan everytime.

**Comment by cowtowncoder** [comment]
Jackson fully caches resulting serializers, deserializers, as long as you reuse `ObjectMapper` which is responsible for caching (or rather has references to entities that do).
What makes you think there is additional scanning for each use?

**Comment by raderio** [comment]
So, cache is thread safe? It use synchronized?

**Comment by cowtowncoder** [comment]
@raderio Yes, it is thread-safe for concurrent access as necessary to support full concurrent usage via `ObjectMapper`, `ObjectReader` and `ObjectWriter`.

For further questions please use mailing lists.
