### ISSUE TITLE
`jackson-databind:2.8.6` depends on `jackson-annotations:2.8.0`

### ISSUE THREAD

**Issue by agebhar1** [FasterXML/jackson-databind#1510]
`jackson-databind:2.8.6` depends on `jackson-annotations` where its version 2.8.0 is managed in `jackson-parent:2.8`

[jackson-databind:2.8.6 pom.xml +44](/FasterXML/jackson-databind/blob/jackson-databind-2.8.6/pom.xml#L44:L54)
```
  <dependencies>
    <!-- Builds on core streaming API; also needs core annotations -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.8.6</version>
    </dependency>
  ...
```
[jackson-parent:2.8 pom.xml +62](/FasterXML/jackson-parent/blob/jackson-parent-2.8/pom.xml#L62:L91)
```
 <properties>
    <version.jackson.annotations>2.8.0</version.jackson.annotations>

    <!-- 02-Oct-2015, tatu: Jackson 2.4 and above are Java 6 (earlier versions Java 5);
          Jackson 2.7 and above Java 6 (with exception of `jackson-core`/`jackson-annotations` still Java 6)
      -->
    <javac.src.version>1.7</javac.src.version>
    <javac.target.version>1.7</javac.target.version>
    <javac.debuglevel>lines,source,vars</javac.debuglevel>

    <!-- Versions for other dependencies -->
    <version.junit>4.12</version.junit>

    <!--
     | For automatically generating PackageVersion.java. Your child pom.xml must define
     | packageVersion.dir and packageVersion.package, and must set the phase of the
     | process-packageVersion execution of maven-replacer-plugin to 'generate-sources'.
    -->
    <packageVersion.template.input>${basedir}/src/main/java/${packageVersion.dir}/PackageVersion.java.in</packageVersion.template.input>
    <packageVersion.template.output>${generatedSourcesDir}/${packageVersion.dir}/PackageVersion.java</packageVersion.template.output>

  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-annotations</artifactId>
        <version>${version.jackson.annotations}</version>
      </dependency>
  ...
```

But [jackson-annotations:2.8.6](/FasterXML/jackson-annotations/tree/jackson-annotations-2.8.6) is available. Is this intended?

**Comment by cowtowncoder** [comment]
@agebhar1 Yes, it is intended. All 2.8.x versions of annotations are identical, no changes are made. My own preference would be to only release versions like 2.7 and 2.8, but user community indicated they prefer option of using full version to match with `jackson-core`, `jackson-databind`.
So the compromise is that all these versions of annotations are released, but there are no changes -- differences is cosmetic.
Now, as to why is there no change in dependency? There's one fewer dependency to change when releasing, as version comes from parent pom, and parent pom is mostly update for minor versions, like 2.8 (and not for every patch).

Having said all that, the new recommendation is to start using `jackson-bom` to get versions.
This will further encapsulate individual version dependencies into general patch-version.
So dependence to `jackson-bom` version `2.8.6` should get you full version set for all standard jackson components, from annotations to core, datatypes, dataformats and other standard modules.

**Comment by agebhar1** [comment]
Thanks @cowtowncoder - got it!

**Comment by mjustin** [comment]
@cowtowncoder — Note that the jackson-bom still specifies the 2.8.0 version of jackson-annotation in [its POM](https://github.com/FasterXML/jackson-bom/blob/2.8/pom.xml#L35).  In fact, it explicitly uses "jackson.annotations.version" for that, rather than "jackson.version" like the rest of the properties.

**Comment by cowtowncoder** [comment]
@mjustin Yes. That is the intention, I really do not want to ever use anything other than .0. There are no changes, and I hope to eliminate patch version of annotations altogether from Jackson 3.x
