### ISSUE TITLE
Exception while deserializing

### ISSUE THREAD

**Issue by bytesrus** [FasterXML/jackson-databind#1517]
I first saw this problem with version 2.5 and have seen some related issues to this exception.  I am currently running 2.8.6 and still see the issue.  Everything that I have read related to this says that it is caused by invalid json, however, the json that I am attempting to read in was written out by Jackson using the same java classes.  That is why I am really confused by this.  It is a hierarchical table and every level is an extension of the same abstract class.  I am running into this issue with the final level in the table.  If I take out the bottom level, the error moves up to the new bottom level.  Insights on how to get around this would be much appreciated.

 "href": "http://localhost:7206/Diff",
   "errors":    [
      "(was java.lang.UnsupportedOperationException) (through reference chain: com.pojos.level1[\"level2collection\"]->java.util.ArrayList[0]->com.pojos.level2[\"level3collection\"]->java.util.HashMap$Values[0]->com.pojos.level3[\"level4collection\"]->java.util.HashMap$Values[0]->com.pojos.level4[\"level5collection\"]->java.util.HashMap$Values[0])",
"com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:388)","com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:360)",
"com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:308)",
"com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)",
"com.fasterxml.jackson.databind.deser.impl.SetterlessProperty.deserializeAndSet(SetterlessProperty.java:127)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)",
"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)",
"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)",
"com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1089)",
"com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:289)",
 "com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)",  "com.fasterxml.jackson.databind.deser.impl.SetterlessProperty.deserializeAndSet(SetterlessProperty.java:127)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)",
"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)",
"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)",
"com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1089)",
"com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:289)",
"com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)",
"com.fasterxml.jackson.databind.deser.impl.SetterlessProperty.deserializeAndSet(SetterlessProperty.java:127)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)",
"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)",
"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)",
"com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1089)",
"com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:289)",
"com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)",
"com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)",
"com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:499)",
"com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178)",
"com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)",
"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)",
"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)",
"com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1089)",
"com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63)",
"com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)",
"com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2740)",
"com.nagrastar.specto.streamDiff.rest.v1.generic.GenericTableComparator.diffTable(GenericTableComparator.java:48)",
"com.nagrastar.specto.streamDiff.rest.v1.StreamDiffServlet.diff(StreamDiffServlet.java:275)",
"sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
"sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
"sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
"java.lang.reflect.Method.invoke(Method.java:498)",
"com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)",
"com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)",
"com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)",
"com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)",
"com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)",
"com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)",
"com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)",
"com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)",
"com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)",
"com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)",
"com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)",
"com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)",
"com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)",
"com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)",
"javax.servlet.http.HttpServlet.service(HttpServlet.java:790)",
"org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)",
"org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)",
"org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)",
"org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)",
"org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)",
"org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)",
"org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)",
"org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)",
"org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)",
"org.eclipse.jetty.server.Server.handle(Server.java:497)",
"org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)",
"org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)",
"org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)",
"org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)",
"org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)",
"java.lang.Thread.run(Thread.java:745)"

**Comment by cowtowncoder** [comment]
I don't mean to be blunt but how on earth could I figure out this without knowing WHICH CLASSES you are using?

**Comment by bytesrus** [comment]
Hey Tatu, I was hoping that the classes in the errors would be enough since I am not able to directly post the code for security reasons.  I will clean the code and post some snippets on Monday that will hopefully help.  Thanks.

**Comment by cowtowncoder** [comment]
Unfortunately stack trace only shows place where original exception was rethrown, and the original exception type (`UnsupportedOperationException`). I suppose it could mean that somehow an immutable Collection was being used and attempt made to add entries during deserialization or something, but that is never being down by databind intentionally. So more information is unfortunately needed.

**Comment by bytesrus** [comment]
OK, I have uploaded a few classes that should give you an idea of what we are doing.  If there is anything else you need to see let me know.

Json is written using a call to mapper.writerWithDefaultPrettyPrinter().writeValue(fopjoson, levels);
Json is read back in later and fails using a call to mapper.readValue(new File(sourceFile, tableClass);

[JsonClasses.zip](https://github.com/FasterXML/jackson-databind/files/755328/JsonClasses.zip)

**Comment by bytesrus** [comment]
This is what the json that is written out and read back in looks like. 

{
  "@class" : "com.pojos.TableLevel1",
  "attributes" : null,
  "descriptors" : [ ],
  "tableLevel2" : [ {
    "@class" : "com.pojos.TableLevel2",
    "level2id" : 1,
    "attributes" : null,
    "descriptors" : [ ],
    "tableLevel3" : [ {
      "@class" : "com.pojos.TableLevel3",
      "level3id" : 1,
      "attributes" : null,
      "descriptors" : [ ],
      "tableLevel4" : [ {
        "@class" : "com.pojos.TableLevel4",
        "level4id" : 1,
        "attributes" : {
          "@class" : "com.pojos.TableLevel4Attributes",
          "level4id1" : 7,
          "level4Id2" : [ 1, 2, 3 ],
          "level4Id3" : 10,
        },
        "descriptors" : [ ],
        "tableLevel5" : [  {
          "@class" : "com.pojos.TableLevel5",
          "level5Id" : 1,
          "attributes" : {
            "@class" : "com.pojos.TableLevel5Attributes",
            "level5id1" : 1,
            "level5id2" : 2,
          },
          "descriptors" : [ ],
        } ]
      } ]
    } ]
  } ]
}

**Comment by bytesrus** [comment]
I figured out the issue.  It is not an error with Jackson.  There was a missing setter for the collection that jackson needed to deserialize.  Sorry to waste anyones time.

**Comment by cowtowncoder** [comment]
@bytesrus Ok I am glad your problem is now resolved! Not problem at all wrt filing an issue, that's perfectly fine and you provided information I asked. It did seem like a possibly tricky problem.
