### ISSUE TITLE
DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES ignored during deserialisation

### ISSUE THREAD

**Issue by ttrifonov** [FasterXML/jackson-databind#1523]
I am using Jackson-Databind 2.8.6 (latest release as for now). I have the following code:

```
public static final ObjectMapper OBJECT_MAPPER = new ObjectMapper()
             .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```
When trying to deserialize JSON to an object: `OBJECT_MAPPER.readValue(jsonString), myClass)`, I get ```com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "myType"```

```at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)```

Looking at the source code, I see there is a check for the `FAIL_ON_UNKNOWN_PROPERTIES` just few lines  before the line that raises the Exception. But it seems it doesn't pass.

Reverting to ver. 2.7.9 works fine. Seems to be an issue with 2.8 only.

**Comment by cowtowncoder** [comment]
@ttrifonov Unfortunately this is not enough to give much indication of the problem. What I'd need is a reproduction of the problem; just explaining symptoms does not help figuring out what is happening.
A simple unit test would be the best fix. And yes, 2.8.6 is the latest release.

**Comment by eau-de-la-seine** [comment]
Hi @ttrifonov , it may happen when your `ObjectMapper` field is `static` and you do your configuration in your constructor. Here a tip for initializing your `ObjectMapper`:
```
private static ObjectMapper mapper = new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```
Or use a `static` block.
