### ISSUE TITLE
Jigsaw support

### ISSUE THREAD

**Issue by lpandzic** [FasterXML/jackson-databind#1536]
There was some talk about jigsaw support on google group but I'd like to formalize it as a feature request in this issue.

**Comment by lpandzic** [comment]
I've managed to modularize and build jackson-databind, jackson-core and jackson-annotations with jdk9 and also successfully tested integration against an example module which uses jackson-databind module.
There are some rough edges that require further research but I believe this is doable, even with Java 7 as a target (so those jars can behave both as regular jars and modules, depending on the runtime and whether on classpath or module path).

**Comment by cowtowncoder** [comment]
Would this require more substantial changes than, say, support for OSGi modules (which only needed Maven build support)?

**Comment by lpandzic** [comment]
https://github.com/FasterXML/jackson-core/pull/358
https://github.com/FasterXML/jackson-annotations/pull/117
The only issue I have right now is compiling source to JDK 7 target. New release flag doesn't seem to work with maven compiler plugin.

**Comment by lpandzic** [comment]
I've added some comments to https://github.com/FasterXML/jackson-annotations/pull/117 which apply to all 3 PR's.
There are 2 issues remaining:
- Travis doesn't support JDK9 EA with Jigaw - https://github.com/travis-ci/travis-ci/issues/7397
- backwards compatibility build.

**Comment by cowtowncoder** [comment]
Ok thank you. Apologies for slow follow-up; just released `2.9.0.pr1` and trying to go through bug backlog.

**Comment by cowtowncoder** [comment]
As per discussion on annotations, core, I don't think this can be done before JDK 9 is required.
But at very least would wait until Java 8, which is for Jackson 3.0; flagging as such for now.

**Comment by lpandzic** [comment]
Hello, sorry for long delay. It should be doable on Java 7 but I'd also wait for 3.0.0 and Java 8 before doing this.

**Comment by cowtowncoder** [comment]
Closing since there's also #1542
