### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by X-Fix** [FasterXML/jackson-databind#1539]
I'm not too clued up on the intricacies of dependencies so I'm just gonna report my findings and hope you can make sense of it all

I'm running a Spring Boot (1.4.1.RELEASE) server on Heroku which uses (including others) the spring-boot-starter-thymeleaf library.
Earlier today (about 15:00PM GMT+2) I pushed to Heroku and (later) noticed the following logs

> remote:        Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.0.pr1/jackson-databind-2.9.0.pr1.pom
> remote:        Download https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.9.0.pr1/jackson-bom-2.9.0.pr1.pom
> remote:        Download https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.9.pr1b/jackson-parent-2.9.pr1b.pom
> remote:        Download https://repo1.maven.org/maven2/com/fasterxml/oss-parent/28/oss-parent-28.pom
> remote:        Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.0.pr1/jackson-databind-2.9.0.pr1.jar

...which I guess was the dependencies automatically updating as the dependant libraries don't specify a version. The problem was that even though the build succeeded, the boot-up failed with the following printout

> Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
> Caused by: java.lang.IllegalArgumentException: Unable to instantiate factory class: org.springframework.boot.env.EnvironmentPostProcessor
> 	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:142)
> 	at org.springframework.core.io.support.SpringFactoriesLoader.loadFactories(SpringFactoriesLoader.java:93)
> 	at org.springframework.boot.context.config.ConfigFileApplicationListener.loadPostProcessors(ConfigFileApplicationListener.java:174)
> 	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:164)
> 	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:154)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
> 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
> 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
> 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:337)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
> 	at com.rethink.ApiApplication.main(ApiApplication.java:12)
> 	... 5 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
> 	at org.springframework.core.io.support.SpringFactoriesLoader.instantiateFactory(SpringFactoriesLoader.java:139)
> 	... 19 more
> Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
> 	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:50)
> 	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:292)
> 	at org.springframework.boot.json.JacksonJsonParser.<init>(JacksonJsonParser.java:37)
> 	at org.springframework.boot.json.JsonParserFactory.getJsonParser(JsonParserFactory.java:42)
> 	at org.springframework.boot.cloud.CloudFoundryVcapEnvironmentPostProcessor.<init>(CloudFoundryVcapEnvironmentPostProcessor.java:105)
> 	... 24 more
> Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.annotation.JsonMerge
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 29 more

Looking directly into the jackson-databind library my IDE was complaining about not being able to resolve various variable references. I eventually managed to solve the issue by adding the following in the "dependencies" section of my build.gradle file.

`compile('com.fasterxml.jackson.core:jackson-databind:2.8.3'){force=true}`

I'm pretty rookie about this stuff and like I just said I found a fix, I just figured if this is something you can fix you'd want to know about it :)

P.S. I tried updating to Spring Boot 1.5.1.RELEASE (although I see now it should've been 1.5.2...) to see if that solved the issue but I got a slightly different but still similar exception when I booted up the server. I haven't tried updating Spring Boot to any other version though

**Comment by Niels-P** [comment]
I have the same issue.

**Comment by cowtowncoder** [comment]
This is due to old version of annotations (2.8.x or earlier) being included with newer (2.9.0.pr1) version of databind. Jackson jars themselves specify dependency versions correctly via parent poms (and starting with 2.9, mostly using `jackson-bom`), but most likely something overrides those versions.

One minor change for `2.9.0.pr2` that might help will be:

https://github.com/FasterXML/jackson-databind/issues/1545

to try to promote dependency used by `jackson-databind` to specify it directly instead of via parent pom. I don't know if that would help, since the way Maven handles transitive dependencies is not always easy to deduce.

At this point I don't know of anything to do on Jackson side and suspect Spring Boot devs might be able to help.
