### ISSUE TITLE
EnumMapDeserializer assumes a pure EnumMap and does not support EnumMap derived classes

### ISSUE THREAD

**Issue by lgoldstein** [FasterXML/jackson-databind#1544]
When attempting to de-serialize a class that is derived from an _EnumMap_, the `EnumMapDeserializer` is invoked (unless I provide my own) - e.g.:
```java
public class Foo extends EnumMap<MyEnum, SomeValue> {
   public Foo() {
        super(MyEnum.class);
   }
}

Foo expected = ...create and initialize an instance...
ObjectMapper mapper = new ObjectMapper();
String json = mapper.writeValueAsString(expected);
Foo actual = mapper.readValue(json, Foo.class);   // ClassCastException - EnumMap cannot be case to Foo...
```
The problem (as far as I was able to diagnose) lies in the
```java
protected EnumMap<?,?> constructMap() {
    return new EnumMap(_enumClass);
}
```
However, the de-serializer already has enough information about the *actual* class being de-serialized via the constructor provided map type:
```java
public EnumMapDeserializer(JavaType mapType, KeyDeserializer keyDeserializer, JsonDeserializer<?> valueDeser, TypeDeserializer valueTypeDeser) {
   ...
}
```
Therefore, it can create the correct (derived) _EnumMap_. Actually, in the constructor it could use flexible code to automatically detect the construction method to be used:
```java
public EnumMapDeserializer(JavaType mapType, KeyDeserializer keyDeserializer, JsonDeserializer<?> valueDeser, TypeDeserializer valueTypeDeser) {
    ...
    Class<?> targetMapType = mapType.getRawClass();
    Constructor<...> ctor = ...check if it has a default constructor... (which enumMap does not have)...
    if (ctor does not exist) {
         ctor = ...check if it has a constructor with the enum class type...
    }
    if (ctor does not exist) {
        throw ...exception - no suitable constructor found...
   }
}

protected EnumMap<?,?> constructMap() {
    if (use ctor with enumClass) {
         return ctor.newInstance(_enumClass);
    } else {
        return ctor.newInstance();
    }
}
```
Please note that if the original class extends (e.g.) _HashMap_ then the above de-serialization code succeeds.

**Comment by cowtowncoder** [comment]
Sounds like a problem, and most likely because creator information is not retained unlike with default/standard `MapDeserializer`.

**Comment by lgoldstein** [comment]
Indeed, but as I have indicated, I believe the solution is simple - all the data is available to re-construct the correct type.

**Comment by cowtowncoder** [comment]
@lgoldstein Right, access to type is not a problem; it definitely is passed. What is needed is the wiring via `ValueInstantiator` to make things work appropriately by also supporting `@JsonCreator`. This is probably not a major undertaking, and has been in a few other places over time.

**Comment by cowtowncoder** [comment]
Bit bigger patch than I hoped, and requires internal api changes, so will be in 2.9.0(.pr2), but now supports full(er) range of options with `@JsonCreator` and/or `@JsonValueInstantiator`.
And of course simple case of no-args (default) constructor as well.
