### ISSUE TITLE
JsonIdentityInfo causes objects to be serialized as Ids, and then cant deserialize them

### ISSUE THREAD

**Issue by ks1974in** [FasterXML/jackson-databind#1549]
Hi,
What happens is that when I serialize an array of objects annotated with JsonIdentityInfo, with UUID generator, objects which are encountered again are serialized as IDs [UUIDs] , which is correct.However, deserialization fails to convert these objects from string /uuid to orignial object and I am left with Strings. which causes the problems.

The input json is at

https://github.com/ks1974in/DeserializationTestForJson/blob/master/input.json

I asked this question on  on disqus and the link to the project src is below. It contains the succeeding and failing unit tests. 
https://github.com/ks1974in/DeserializationTestForJson.git

I have also asked this question on stackoverflow at http://stackoverflow.com/questions/42288780/jsonidentityinfo-causes-objects-to-be-serialized-as-ids-and-then-cant-deseriali
but have not received any response. I am wondering whether I should file a bug report. 

No answers on google groups either.

Please help. I am stuck with this issue for over 15 days now. 
sincerely,
Sagar Kapadia

Jackson version :2.8.6

**Comment by cen1** [comment]
This is a known issue: https://github.com/FasterXML/jackson-databind/issues/372

**Comment by cowtowncoder** [comment]
I don't think there is quite enough information to assume it's same as #372.

Repro project seems to have some issues -- `mvn test` does not run tests; some tests assume existence of local files (`/home/sagar/json/input.json`), swallow exceptions.

But at least running from IDE there is one failure which I think is relevant, related to combination of default typing and object id, so I'll see if that could shed light here.

**Comment by cowtowncoder** [comment]
Unfortunately I can only see that the first entry of the array differs, but not what exactly is going wrong, so I can't really do much more. A simpler self-contained test with fewer and smaller types would be helpful.

**Comment by ks1974in** [comment]
Sure, i will provide that

**Comment by cowtowncoder** [comment]
No reproduction, closing.
