### ISSUE TITLE
Unexpected behavior with `@JsonInclude(JsonInclude.Include.NON_EMPTY)` and `java.util.Date` serialization

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1550]
(note: moved from https://github.com/FasterXML/jackson-annotations/issues/111 by @ stefan-huettemann )

Is this really what is intended? I would consider this a bug.

I see unexpected behavior using `@JsonInclude(JsonInclude.Include.NON_EMPTY)` with `java.util.Date` serialization.

Setting a `Date` to `1970-01-01` results in an empty JSON object since `NON_EMPTY` seems to consider `1970-01-01` as empty (`0` time stamp value) where as I consider `1970-01-01` a perfectly valid `NON_EMPTY` value ;)

Consider this code:
```
public class TestJacksonJsonFormat {

    public static void main(String[] args) throws JsonProcessingException {

        final ObjectMapper theObjectMapper = new ObjectMapper();
        final TestDTO theTestDTO = new TestDTO();

        theTestDTO.setDate(new Date(0));  // set to "1970-01-01"
        System.out.printf("1970-01-01: %s\n", theTestDTO.getDate());
        System.out.printf("Serialized: %s\n", theObjectMapper.writeValueAsString(theTestDTO));

        theTestDTO.setDate(new Date(1));  // set to "1970-01-01T00:00:00.001+0000"
        System.out.printf("1970-01-01 + 1 msec: %s\n", theTestDTO.getDate());
        System.out.printf("Serialized: %s\n", theObjectMapper.writeValueAsString(theTestDTO));

    }

    @JsonInclude(JsonInclude.Include.NON_EMPTY) // Note: works with NON_NULL
    private static class TestDTO {

        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSZ", timezone = "UTC")
        private Date date;

        Date getDate() {
            return date;
        }

        void setDate(final Date aDate) {
            date = aDate;
        }
    }
}
```

Note: setting `disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)` does not change the effect.

**Comment by cowtowncoder** [comment]
Note: only implementing for 2.9 due to backwards compatibility concerns (these have traditionally been brittle things to change). Both `java.util.Date` and `java.util.Calendar` will now NOT be considered empty, ever, but `NON_DEFAULT` will filter out instances with timestamp of `0L`.

**Comment by drahkrub** [comment]
a short note for all who ran into the same problem as me: also a value of `01:00:00` for `java.sql.Time` is filtered out with `NON_DEFAULT` ...
