### ISSUE TITLE
`JsonMappingException` with polymorphic type and `JsonIdentityInfo` when basic type is abstract

### ISSUE THREAD

**Issue by acm073** [FasterXML/jackson-databind#1551]
Hi,

I just came across this issue: when deserializing a polymorphic type from just the type id, deserialization fails when the base class is abstract.

In more detail:
The type hierarchy:

    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY,
        property = "@class")
    public abstract class Vehicle {
        private String vehicleId;
        public String getVehicleId() { return vehicleId; }
        public void setVehicleId(String vehicleId) { this.vehicleId = vehicleId; }
    }

    public class Car extends Vehicle {
        private int numberOfDoors;
        public int getNumberOfDoors() { return numberOfDoors; }
        public void setNumberOfDoors(int numberOfDoors) { this.numberOfDoors = numberOfDoors; }
    }

The type that holds a vehicle:

    public class VehicleOwner {
        @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "vehicleId")
        @JsonIdentityReference(alwaysAsId = false)
        private Vehicle ownedVehicle;
        public Vehicle getOwnedVehicle() { return ownedVehicle; }
        public void setOwnedVehicle(Vehicle ownedVehicle) { this.ownedVehicle = ownedVehicle; }
    }

Test code:

    @Test
    public void testSerializeDeserialize() throws IOException {
        Car c = new Car();
        c.setVehicleId("123");
        c.setNumberOfDoors(2);
        // both owners own the same vehicle (car sharing ;-))
        VehicleOwner v1 = new VehicleOwner();
        v1.setOwnedVehicle(c);
        VehicleOwner v2 = new VehicleOwner();
        v2.setOwnedVehicle(c);

        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.enable(SerializationFeature.INDENT_OUTPUT);
        String serialized = objectMapper.writeValueAsString(asList(v1, v2));
        System.out.println(serialized);

        VehicleOwner[] deserialized = objectMapper.readValue(serialized, VehicleOwner[].class);
        assertEquals(2, deserialized.length);
        assertEquals(deserialized[0].getOwnedVehicle(), deserialized[1].getOwnedVehicle());
    }

Serialization result (as expected, first instance is fully serialized, second one just by ID):

    [ {
      "ownedVehicle" : {
        "@class" : "Car",
        "vehicleId" : "123",
        "numberOfDoors" : 2
      }
    }, {
      "ownedVehicle" : "123"
    } ]

Deserialization FAILS:
`com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (VALUE_STRING), expected FIELD_NAME: missing property '@class' that is to contain type id  (for class Vehicle)`

However, when the "abstract" modifier is removed from the `Vehicle` class, the test succeeds.

**Comment by acm073** [comment]
Update: the problem only occurs when a member of a polymorphic type is annotated, not when the polymorphic type itself is annotated. E.g. in the above example, if the `@JsonIdentityInfo` annotation is moved from the field in `VehicleOwner` to the `Vehicle` class, the test case works even if the base class is abstract.

**Comment by cowtowncoder** [comment]
Yes, I can reproduce this. Hoping to look into fix soon.

**Comment by cowtowncoder** [comment]
Ah. Most likely need to add `createContextual()` for `AbstractDeserializer`: without this, only class annotations would be considered. If so, need to try to refactor code a bit as well to share handling between `BeanDeserializerBase` and `AbstractDeserializer`.

**Comment by cowtowncoder** [comment]
Ok... so this is bit tricky. On one hand, it is easy enough to fix handling, mostly: contextualization just has to check and resolve Object Id information from property. This is now done, both for `master` and `2.8`.

But the bad news is that at this point it is NOT possible to support property-annotation for property-valued Object Id on polymorphic type. So specific test case will not work; other mechanisms (UUID, sequence) will work.

The problem here is that `AbstractDeserializer` does not retain information about properties it has, as they are never needed; actual properties of sub-types are handled by their respective deserializers.
It may be possible to refactor things for `2.9` so that properties were available until contextualization, and can the be discarded. I'll see if this is doable.

**Comment by cowtowncoder** [comment]
Was able to fix by keeping track of properties, dropping only at contextualization. Passes tests.
