### ISSUE TITLE
jackson-databind 2.9.0-pr1 breaks builder deserialization

### ISSUE THREAD

**Issue by stevenschlansker** [FasterXML/jackson-databind#1557]
For a Builder like,
```java
@AutoValue
@JsonDeserialize(builder = AutoValue_Restaurant.Builder.class)
@JsonNaming(PropertyNamingStrategy.UpperCamelCaseStrategy.class)
public abstract class Restaurant {
    Restaurant() { }

    @JsonProperty("RID")
    public abstract long getRID();

    @AutoValue.Builder
    @JsonNaming(PropertyNamingStrategy.UpperCamelCaseStrategy.class)
    @JsonPOJOBuilder(withPrefix="set")
    public abstract static class Builder {
        @JsonProperty("RID")
        public abstract Builder setRID(long rid);
    }
}
```

This code worked with 2.8 branch, but updating the 2.9.0-pr1 (to test out https://github.com/FasterXML/jackson-databind/issues/1402) breaks it.  It seems that commit https://github.com/FasterXML/jackson-databind/commit/e45279370ee9d3977776159c6f23d67f05379613 changed the default behavior of `AnnotationInspector#findPOJOBuilderConfig()` to returning a default value rather than `null`.

We end up with a `ParameterNamesAnnotationIntrospector` stacked on top of a `JacksonAnnotationIntrospector`.  Previously, `AnnotationIntrospectorPair#findPOJOBuilderConfig` would try the former, get null, then fallback to the latter.  Now it gets a bogus empty configuration from the former and never gets the correct configuration from the latter.

**Comment by stevenschlansker** [comment]
Ugly hack workaround:

```diff
diff --git a/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotationIntrospectorPair.java b/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotationIntrospectorPair.java
index 408f2c9..6afe3de 100644
--- a/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotationIntrospectorPair.java
+++ b/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotationIntrospectorPair.java
@@ -705,7 +705,7 @@ public class AnnotationIntrospectorPair
     @Override
     public JsonPOJOBuilder.Value findPOJOBuilderConfig(AnnotatedClass ac) {
         JsonPOJOBuilder.Value result = _primary.findPOJOBuilderConfig(ac);
-        return (result == null) ? _secondary.findPOJOBuilderConfig(ac) : result;
+        return (result == null || result == JsonPOJOBuilder.Value.empty()) ? _secondary.findPOJOBuilderConfig(ac) : result;
     }
     
     // // // Deserialization: method annotations
```

**Comment by cowtowncoder** [comment]
I'd love to fix this, but I would need a reproduction that does not rely on auto-value lib itself: generated sources are ok but ideally simpified example.

**Comment by cowtowncoder** [comment]
Fixed via @stevenschlansker 's patch, will be in 2.9.0.pr2.
