### ISSUE TITLE
Equals across BigInteger and BigNumber values

### ISSUE THREAD

**Issue by mspiegel** [FasterXML/jackson-databind#1561]
When using the deserialization features USE_BIG_DECIMAL_FOR_FLOATS and USE_BIG_INTEGER_FOR_INTS, an integer node and a decimal node with the same mathematical value will return false when tested for equality.

I have a branch that has implemented the deserialization feature USE_BIG_DECIMAL_FOR_INTS. this feature allows JSON floating point numbers and JSON integral numbers to be tested for equality without loss of precision.

**Comment by mspiegel** [comment]
Another way to solve this is to implement the deserialization feature USE_BIG_DECIMAL instead of USE_BIG_DECIMAL_FOR_INTS. USE_BIG_DECIMAL would force promotion to BigDecimal for all numeric values.

USE_BIG_DECIMAL would take precedence over the flags USE_BIG_DECIMAL_FOR_FLOATS, USE_BIG_INTEGER_FOR_INTS and USE_LONG_FOR_INTS.

**Comment by cowtowncoder** [comment]
Just to make sure: are you talking about `JsonNode` equality? Or something else?

**Comment by mspiegel** [comment]
Yup. I'm writing a variation of a JSON schema validator and I need to test
whether two JSON objects are equal according to the JSON schema definition:
"...both are numbers, and have the same mathematical value;"

I think my work around for now is to write a pass that converts
BigIntegerNodes to DecimalNodes.

**Comment by cowtowncoder** [comment]
Ok makes sense. I think what you really want is this method in `JsonNode`:

    public boolean equals(Comparator<JsonNode> comparator, JsonNode other) ...

which was added in 2.6, and designed to allow configurable comparisons.
At this point I think that trying to implement "universal equality" for nodes via standard `equals()` override is a losing cause, not worth the effort. There are many reasons, from possibly conflicting goals (performance vs exact semantics; loose vs strict equality) to some practical limitations, most notable the fact there is no context to carry (that is: none of configuration, including Features, is accessible within method!).

But I hope the method I listed makes it easier to implement suitable equality comparison logic.

**Comment by mspiegel** [comment]
Oops I didn't describe my problem correctly. I actually want to generate a
Set of JsonNode objects and then test that I don't insert duplicate values
into the set. That's why I need the equals() consistent with hashcode().

I can convert BigInteger nodes to BigDecimal nodes for now.

I'm actually on the fence whether the benefits of USE_BIG_DECIMAL_FOR_INTS
are worth the maintenance of adding the new feature. I'm kind of partial to
adding the feature USE_BIG_DECIMAL because conceptually it lines up with
JSON numbers as mathematical numbers. But I also know that USE_BIG_DECIMAL
is slightly more complicated to implement than USE_BIG_DECIMAL_FOR_INTS.


On Mar 17, 2017 6:41 PM, "Tatu Saloranta" <notifications@github.com> wrote:

Ok makes sense. I think what you really want is this method in JsonNode:

public boolean equals(Comparator<JsonNode> comparator, JsonNode other) ...

which was added in 2.6, and designed to allow configurable comparisons.
At this point I think that trying to implement "universal equality" for
nodes via standard equals() override is a losing cause, not worth the
effort. There are many reasons, from possibly conflicting goals
(performance vs exact semantics; loose vs strict equality) to some
practical limitations, most notable the fact there is no context to carry
(that is: none of configuration, including Features, is accessible within
method!).

But I hope the method I listed makes it easier to implement suitable
equality comparison logic.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FasterXML/jackson-databind/issues/1561#issuecomment-287488952>,
or mute the thread

**Comment by mspiegel** [comment]
Sometimes at night I miss the obvious things. I'm pretty sure that using a TreeSet of JsonNodes and providing a comparator would accomplish what I want.

**Comment by mspiegel** [comment]
Confirmed. I can use a TreeSet and write my own comparator but it's a pain. It's less code to write a pass and convert all the BigIntegers to BigDecimals.

**Comment by cowtowncoder** [comment]
@mspiegel Ah! Thank you for explaining this. Makes sense.

Going forward, I think that perhaps configuration would be best aimed at allowing customization of how `JsonNode` trees are built to (more) canonical form. This aspect could be easier to configure in general -- there is already `JsoNodeFactory`, for one, although I am not sure if that'd be sufficient -- and in general it could expose more complex settings than simple feature flags.

Come to think of that, you can probably extend default `JsonNodeFactory` and do conversion on the fly there, register it for `ObjectMapper`. That might be the simplest route at the moment.

**Comment by mspiegel** [comment]
Thanks! Closing this for now.
