### ISSUE TITLE
Jackson seems to be trimming strings????

### ISSUE THREAD

**Issue by willpugh** [FasterXML/jackson-databind#1569]
Hmm.  I'm seeing an issue where Jackson seems to be trimming string values.  In my case, I'm using a custom deserializer, so I don't know if this happens for all strings or not.

I tracked the issue down to this line in FromStringDeserializer ~ line 116

if (text.length() == 0 || (**text = text.trim()**).length() == 0) {
    // 04-Feb-2013, tatu: Usually should become null; but not always
    return _deserializeFromEmptyString();
}

This seems to be the root cause for my issue.  My custom deserializer derives from FromStringDeserializer.  I can work around it, by changing my code to:
```
@Override
  protected StringParameter _deserialize(String value, DeserializationContext ctxt)
      throws IOException {
    String newValue = ctxt.getParser().getValueAsString();
    // Do stuff with newValue instead of value
  }
```

However, seems like this may be worth fixing, since it seems this could cause subtle bugs.

**Comment by cowtowncoder** [comment]
First things first: what exactly is your problem here? I don't see anything to fix at this point.

Note that `FromStringDeserializer` is something used internally, and has its own operating rules, mostly for scalars where surrounding whitespace is not meaningful. If it is for you, don't use it.
I can add javadocs to indicate that trimming is done for the class to make sure developers know.

**Comment by willpugh** [comment]
Ah.  If this is by design, would be nice to add Javadoc.

My use case is very similar to what you are doing here, so I re-used the class.  It was a while ago when I wrote it, so not sure why I thought `FromStringDeserializer` was in bounds to re-use, but likely it was because I saw it in the same package as StdDeserializer (which the Javadoc says to use).

If this is out-of-bounds I can re-write something to suit my needs.

Thanks.

**Comment by cowtowncoder** [comment]
@willpugh Yes agreed, this should be documented. On reuse... it's kind of tough call really; it's not that it should not be reused, just that it probably only makes sense if usage is for scalars where surrounding white-space is incidental and not meaningful.

I will improve javadocs and then close this: thank you for suggesting this!

**Comment by cowtowncoder** [comment]
Noted couple of other things deserializer does automatically; empty String (after trimming) calls different method (which by default returns `null` for convenience), and scalars other than String are coerced automatically as well. Single-array unwrapping is also supported if enabled (via `DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS`).
