### ISSUE TITLE
`Enum` key for `Map` ignores `SerializationFeature.WRITE_ENUMS_USING_INDEX`

### ISSUE THREAD

**Issue by SolaKun** [FasterXML/jackson-databind#1570]
Version: latest 2.8

Failing unit tests added here:
https://github.com/SolaKun/jackson-databind/commit/6e095f75edd1de3eb33be5950c56d562bd6d584a

Only java.util.Map test case provided, but doesn't work with EnumMap as well..

**Comment by cowtowncoder** [comment]
Just to make sure I understand: this is when keys are `Enum`s, not when values are `Enum`s?

**Comment by SolaKun** [comment]
yes
