### ISSUE TITLE
Can't figure out how to download

### ISSUE THREAD

**Issue by jessebarnum** [FasterXML/jackson-databind#1576]
Every other Java library I've ever used has a simple way to download a compiled jar. I tried for a few minutes with Jackson, but not worth the time. Giving up and switching to gson. Also there are lots of links to this broken URL: http://wiki.fasterxml.com/JacksonHome

It's a shame, because I can tell from the docs that a lot of effort has gone into the project, it just totally fails in terms of actually getting started.

**Comment by jjware** [comment]
I am not affiliated with the Jackson project, but as a software engineer, I would wonder why you are looking to download a compiled jar file. For a majority of open source project libraries, the intention is for the consumer to either pull the library from a dependency management system (such as Maven in the case of Java), or compile the source code yourself (especially for projects that involve unmanaged code).

**Comment by cowtowncoder** [comment]
@jessebarnum Yes, as per @jjware assumption is that at this point in time most Java developers use a build system that can access artifacts from Maven repository.

Now, as to locating repository for those who prefer manual access to pre-built jar.... Link to git project wiki:

https://github.com/FasterXML/jackson-databind/wiki

is included in project README but perhaps not as prominent as it should be.
Main wiki page has links to some of the versions, but in general you can get URLs from that.
