### ISSUE TITLE
`DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT` does not prevent coercion of "" into `Integer`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1588]
(follow-up from #1095)

It looks like `master` (for 2.9) does not yet work wrt wrappers like `Integer`: disabling of `DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT` does not produce exception as expected.

**Comment by gkozyryatskyy** [comment]
+1
