### ISSUE TITLE
Provide freeze method for ObjectMapper to make it immutable

### ISSUE THREAD

**Issue by quaff** [FasterXML/jackson-databind#1593]
Since ObjectMapper is designed as thread safe and use shared instance is recommended, It is necessary to provide a method make it immutable after initialized, It can prevent errors caused by unexpected modification by others. and I'm not sure should have a unfreeze method.
```
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
objectMapper.freeze(); 
objectMapper.enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES); //should throw exception
```

**Comment by cowtowncoder** [comment]
I appreciate your suggestion, but I do not think this is the right way to go about things.
Ideally (?) we would use a Builder for constructing mapper, and only construct instance later on.
While I have seen libraries use switch for mutable/immutable, I have not been impressed by this design.

We could consider such a change for Jackson 3.x.

**Comment by quaff** [comment]
What I wanted is immutable, I'm not insist of using switch, but I think it's convenient for legacy code, just add one line code without other changes.

**Comment by cowtowncoder** [comment]
Actually 3.0 will make `ObjectMapper` immutable, as per

https://github.com/FasterXML/jackson3-dev/issues/3

using builder-style creation. So... it will happen, finally. :)
Will probably create a new issue for databind (if one does not exist) to add more details, so closing this.
