### ISSUE TITLE
provide a way to validate against the json schema

### ISSUE THREAD

**Issue by ffang** [FasterXML/jackson-databind#1596]
It would be great that Jackson can provide a feature to validate the JSON payload against the JSON schema, like the fge lib can do.

**Comment by cowtowncoder** [comment]
@ffang This is not something that belongs in `jackson-databind`, I think, but if there is a way to plug it in as part of either `JsonParser` operation (via delegate I think?) that could be nice new module.

I think it would make sense to re-file this at:

https://github.com/FasterXML/jackson-future-ideas/issues/

given that it does not (IMO) belong here, nor should it be embedded part of `jackson-core`.

**Comment by ffang** [comment]
Thanks @cowtowncoder! 
Created an issue there
https://github.com/FasterXML/jackson-future-ideas/issues/14
