### ISSUE TITLE
Implement "deepUpdatingReader" for ObjectMapper

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#160]
(note: originally at http://jira.codehaus.org/browse/JACKSON-679 moved here)

------

Although there already exists "ObjectMapper.updatingReader()" to allow merging of multiple JSON sources, it only implements shallow merge; such that there is no real merging beyond first level of properties. It would be useful to allow deep merges, if possible.

Besides obvious merging of Object properties, there are some interesting questions like:

* If and how to merge arrays? (at least define whether 'null' or empty array would override existing non-null/non-empty arrays)
* Would it be possible to merge objects of different type (probably not) -- what to do with conflict?

It might make sense to expose some kind of ConflictResolver abstraction to deal with such problems.

**Comment by KIC** [comment]
A new annotation would be brilliant since you could control object creation for each property. Still looking forward to get this feature. Thanks

**Comment by vishy1214** [comment]
@cowtowncoder, I am using readerForUpdating to merge the json to the object. I see only the first level merge going thru, for all the inner/ nested relationships a new instance is getting created in the object instead of merging the data. Is this anyway related to the discussion in this thread ?

**Comment by cowtowncoder** [comment]
Yes. This issue is for asking functionality to do multi-level merge, by adding ability to call a getter (or access field value) first, see if property has a non-null value, and if so use that object to update instead of constructing a new one. Currently no such handling exists, and all values are constructed from scratch.

**Comment by vishy1214** [comment]
do you see this as an enhancement that might get addressed in one of the next coming releases ?

**Comment by cowtowncoder** [comment]
@vishy1214 Yes, I still hope this may get addressed in future, in some form.

**Comment by fromi** [comment]
Hi, instead of a new annotation, what about something like that?
```java
@JsonDeserialize(strategy = MERGE)
```
I might try to create a pull request if I find some time.

**Comment by cowtowncoder** [comment]
@fromi That is a possibility too, thank you for suggestion. My only concern here is just that annotations do not merge; that is, you will override any and all settings of `@JsonDeserialize`. That may or may not matter, in general, but for `@JsonDeserialize` number of properties has been growing.
Still, as long as access is via usual `AnnotationIntrospector` approach, it should be easy enough to handle.
One option, wrt value, is also whether to use explicit enum (like `JsonDeserialize.Strategy`) or new `OptBoolean` from `jackson-annotations`: either way, it should be possible to choose between "merge", "no-merge" and "use-default" (i.e. do not specify with annotation)

Also: I think it makes sense to have a `MapperFeature` that allows defaulting handling to `MERGE` -- this is what above-mentioned "use-default" would then use. Some users will probably simply want to try merging in all cases; whereas others have no use for it, and overhead (even if minor) it adds.

Wrt timing: I think this is something that would be important to get working for 2.7; 2.6 is being finalized now (last RC went out few days ago).

**Comment by CrisLi** [comment]
Is there any plan to implement the deep merge in new release? We really want to the ObjectMapper.readerForUpdating() has deep merge functionality.

**Comment by cowtowncoder** [comment]
@CrisLi Plans, yes, actual concrete plan, no. I hope to achieve this by adding support for specific "merge mode" annotation, which would allow indicating POJO fields to use merging, instead of overwrite.
If and when that works, it would be possible to use same mechanism for global mechanism, for defaulting to merging instead of ovewrite.

If all goes well (... yeah right) I would find time to implement this for 2.8. It has been on a todo list for most important new features list probably through the whole 2.x development, so it is not a forgotten feature. Just one that turns out to be quite tricky to implement throughout handler hierarchy.

**Comment by Labi0** [comment]
Any temporary work around for the "deepReaderForUpdating" feature?

**Comment by cowtowncoder** [comment]
@Labi0 None that I know of, although one could probably implement setters that would explicitly merge existing and new value; this could work recursively up the hierarchy.

**Comment by cowtowncoder** [comment]
Actually; will implement this via #1050; no new method required. Will however require annotation, and/or way to define global default.
