### ISSUE TITLE
Serializing locale with underscore, not standard hyphen

### ISSUE THREAD

**Issue by akoshman** [FasterXML/jackson-databind#1600]
There were an issue with deserializing locales https://github.com/FasterXML/jackson-databind/issues/1344

But there is still a problem that during serialization Jackson is executing toString() method for locale. According to the official javadoc, toString() must be used for debug purposes. I think it is better to use toLanguageTag() for the serialization since it produces locale represenation with a hyphen as a delimiter:

https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html

**Comment by cowtowncoder** [comment]
Ok that sounds plausible I guess.

My main concern here is the backwards compatibility, as usual; if change can be made in a compatible way

**Comment by cowtowncoder** [comment]
For what it is worth, there is currently no dedicated serializer for `Locale`; it does use default `ToStringSerializer`.

**Comment by michaelkrog** [comment]
I experience this is an issue as well in our setup with mixed .NET and Java services.

.NET default is to use a Hyphen and there some of our services expect a Hyphen. Developing a Java-client against these services requires a custom serializer.

**Comment by paolobazzi** [comment]
+1 for solving this issue. As workaround we added a custom implementation of the ToStringSerializer using Locale.toLanguageTag()

Could Backward-compatibility be added using a new serialization property or a JsonFormat annotation?

**Comment by cowtowncoder** [comment]
@paolobazzi At this point I think the fix needs to go in 3.0, for better or worse. Features are bit coarse-grained for this (I know there are a few datatype-specific ones, but ideally would try to avoid that); and they'd need to go in a new minor version anyway. But 2.9 is likely the last 2.x version.

**Comment by paolobazzi** [comment]
Thanks for solving this issue! 
Is there an idea when Release 3.0 will be available?

Cheers, Paolo

**Comment by cowtowncoder** [comment]
@paolobazzi No idea unfortunately at this point. Big changes still going on so we are far from even the first pre-release version. At earlier, if I had to guess, July/August; but might be closer to end of 2018.

**Comment by paolobazzi** [comment]
Thanks for your information!
