### ISSUE TITLE
jackson-bom-2.8.8.1 should be released at the same time as jackson-databind-2.8.8.1

### ISSUE THREAD

**Issue by t-tsutsumi** [FasterXML/jackson-databind#1611]
If not, it will be difficult to use the latest Jackson library on projects using jackson-bom.

Note: This is a premise that it is possible to simultaneously use jackson-databind-2.8.8.1 and other Jackson libraries (version 2.8.8).

**Comment by cowtowncoder** [comment]
@t-tsutsumi yes, the definition of minor version is that patch version are fully interoperable. Micro-patch (one with 4th digit) is meant for critical fixes that are released out of regular release cycle.

The reason why I disagree with benefits of spending time to release a bom release for this is just that although only `jackson-databind` has a patch now, it is technically possible we could (have to) release other components. There is no full release to specify versions for. So I think users would simply choose `2.8.8`, and override version for `jackson-databind` (and/or others for if micro-patches were released).

**Comment by t-tsutsumi** [comment]
@cowtowncoder Thanks for your response. I agree with your careful thoughts.

**Comment by cowtowncoder** [comment]
@t-tsutsumi Also: forgot to say -- thank you for suggesting this, I can see why this would seem sensible thing to do this, and it is better to suggest and discuss than assume it can't be done or such. This is how we can improve the project.
