### ISSUE TITLE
Portable extensibility: A way to configure a Module that gets loaded automatically

### ISSUE THREAD

**Issue by roguexz** [FasterXML/jackson-databind#1617]
Version: 2.6.3

Consider the following scenario,

    [Framework]
    public interface UberType<T extends UberType<T>> { ... }
    public abstract class UberTypeImpl<T> implements UberType<T> {...}

    [Module 1]
    public interface A extends UberType<A>{...}
    public class AImpl extends UberTypeImpl<A> implements A {...}

    [Module 2]
    public interface B extends UberType<B>{}
    public class BImpl extends UberTypeImpl<B> implements B {...}

Instead of defining `@JsonSerialize(as = interface)` & `@JsonDeserialize(as = implementation)` on the interface definition, is there a way to load a `Module` definition either by a factory lookup or a service-provider style lookup (because I don't control the ObjectMapper creation).

Something like,

    [Framework]
    META-INF/services/com.fasterxml.jackson.databind.Module
        > My custom module definition

Please let me know if this capability already exists or is it likely to be considered as an enhancement.

**Comment by cowtowncoder** [comment]
I think `ObjectMapper.findAndRegisterModules(...)` does this: it uses SPI metadata like you describe, and standard Jackson modules do include this for modules that may be registered (there is also separate SPI metadata for dataformat modules that allows in theory pluggable formats as well).

**Comment by roguexz** [comment]
👍 I can work with that for now. Thank you.
