### ISSUE TITLE
Getting reference object as Null, when converting json list to pojo class object.

### ISSUE THREAD

**Issue by vallabvs** [FasterXML/jackson-databind#1623]
Class A:

```java
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")    
public class UserMain { 
    private int id;
    private Serializable userId;    
    private UserMain parentUser;    
    //getters and seetter ...
```

Class B

```java
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")    
public class UserDetail {    
    private int id;
    private Serializable firstName;
    private Serializable lastName;
    private Serializable password;
    //getters and seetter
```

JSON String (containing List):

```java
[[{"@id":1,"id":2,"userId":"Test1","parentUser":1}],[{"@id":2,"id":3,"firstName":"firstName","lastName":"lastName","password":"password","userMain":1}]]
```

Convert to List to POJO classes:

```java
mapper.registerModule(new Hibernate4Module());
mapper.registerModule(new IdentifiableDeserializableModule())

        try {
           List resultList = mapper.readValue(stringParam,List.class);                  
           List<UserMain> object1 = mapper.convertValue(resultList.get(0),new TypeReference<List<UserMain>>(){});
           List<UserDetail> object2 = mapper.convertValue(resultList.get(1),new TypeReference<List<UserDetail>>(){});
            System.out.println(object1 .get(0).getParentUser().getId()); //ok                
           System.out.println(object2.get(0).getUserMain().getId()); // This is null                  
       } catch (Exception e) {               
       }
```

Getting reference object (object2.get(0).getUserMain().getId()) as NULL , what is missing..

**Comment by cowtowncoder** [comment]
Some questions:

1. Which version of Jackson
2. Can this be reproduced without Hibernate module? (and what does `IdentifiableDeserializableModule` do -- is that relevant)

If this can not be reproduced with additional modules, issue should go under Hibernate module.
If it's not needed can just simplify the test.

**Comment by vallabvs** [comment]
Hi,
1. Iam using 2.8.1 version
2. I can reproduce without hibernate module or IdentifiableDeserializableModule
3. The IdentifiableDeserializableModule is     

 ```
/** Jackson module to deserialize java.io.Serializable class. */
public class IdentifiableDeserializableModule extends SimpleModule {    
        private static final long serialVersionUID = 1L;
	        public IdentifiableDeserializableModule() {
                addDeserializer(Serializable.class, new StringDeserializer());
}
```
The null value is causing , the second list object does not contain the reference object when conversion. The actual object  contain in the first list object.

**Comment by cowtowncoder** [comment]
@vallabvs Thank you for the update!

On version: please always test with latest patch version (of the minor version you have) -- here that'd be 2.8.8. It's very frustrating to find that the problem has been fixed (often happens although not in majority of cases), and patch versions are API compatible so change itself should be trivial and simple to make for testing (I would also argue for using latest patch, but there may some constraints on that imposed by local sw development practices or dependencies).

**Comment by cowtowncoder** [comment]
Oh. Looking at the test itself, I am not sure what it actually attempts to do... but I don't think that can work as code suggests. Id references must be resolved in the document, and here there are two separate fragments -- while input document contains two sub-arrays, those are separately bound to `List<Object>` values, and there's nothing to combine them later on.

First array should still work (and apparently does) as the `@id` refers to object itself (i.e. simple cycle); but the second document contains reference to object with id `1` which does not exist there.

So unless I misunderstand the intent here, this is not a case that is or will be supported.

**Comment by vallabvs** [comment]
Hi Cowtowncoder,

Thank you for your time.

For workaround i used Set Interface for child objects and converting to a single object.

```
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id") 
public class UserMain {	
	private int id;
	private Serializable userId;	
	private UserMain parentUser;	
	Set<UserDetail> userDetailSets =  new HashSet<UserDetail>(0);
 //getters and seetter ...
```

**Comment by cowtowncoder** [comment]
Glad you got this working!
