### ISSUE TITLE
Don't print to error stream about failure to load JDK 7 types

### ISSUE THREAD

**Issue by Villane** [FasterXML/jackson-databind#1628]
In version 2.7.x, it is supposedly usable on Java 6, since Java 7 types are loaded dynamically. However, what is the reasoning for printing to error stream "WARNING: Could not load ..." when running on Java 6? If Jackson 2.7 in general still works with Java 6, I don't want my application error stream to be polluted just for fun - my tests may actually be expecting a clean error stream!

**Comment by cowtowncoder** [comment]
@Villane Did you even try to figure out what was going on? It's not printed directly to error stream, nor for fun. It is logging a warning using java.util.logging.

**Comment by Villane** [comment]
I beg to differ, please check the 2.7 branch, as I'm talking about 2.7.x. It clearly has System.err.println usages:

https://github.com/FasterXML/jackson-databind/blob/2.7/src/main/java/com/fasterxml/jackson/databind/ext/OptionalHandlerFactory.java

**Comment by cowtowncoder** [comment]
@Villane Ok. Then this is incorrect. I thought it was using java.util.Logger. Thank you for reporting this.

**Comment by cowtowncoder** [comment]
Ah ok. So, Jackson 2.7 did indeed only use System.err. 2.8 change to use java.util.logging for Java 7 classes. But there was one other place (for DOM `Node` and `Document` types) where `System.err` was used, will fix that.

Will also backport in 2.7, although it is not certain if new versions from that branch will be released.
