### ISSUE TITLE
JsonSerializer need to validate is a Collection is empty in "isEmpty()"

### ISSUE THREAD

**Issue by dcbasso** [FasterXML/jackson-databind#1632]
After I Customize some Serialization Objects using the **extends StdSerializer** and customizing some Collections using List (**extends StdSerializer<List**), the serializator always keep the collection in serialized JSON, even when the Collection was empty.
To fix it I needed to make a @override in each implementation of **extends StdSerializer<List**, and set this:

```
@Override
    public boolean isEmpty(SerializerProvider provider, List<Variety> value) {
        return ((value == null) || (value.isEmpty()));
    }
```

We could do a better implementation to it, change the "isEmpty()" from JsonSerializer , as my suggestion:

```
/**
     * Method called to check whether given serializable value is
     * considered "empty" value (for purposes of suppressing serialization
     * of empty values).
     *<p>
     * Default implementation will consider only null values to be empty.
     *<p>
     * NOTE: replaces {@link #isEmpty(Object)}, which was deprecated in 2.5
     * 
     * @since 2.5
     */
    public boolean isEmpty(SerializerProvider provider, T value) {
        if (value != null) {
            if (value instanceof Collection) {
                return ((Collection) value).isEmpty();
            }
            return false;
        }
        return true;
    }

```
I think this code will solve all problems to everyone how extends StdSerializer using a Collection as the GenericType.

**Comment by dcbasso** [comment]
Im make a local branch and I could not commit this to my local branch.
I got this error:

```
remote: Permission to FasterXML/jackson-databind.git denied to dcbasso.
fatal: unable to access 'https://github.com/FasterXML/jackson-databind.git/': The requested URL returned error: 403
```

Please anyone can give a permission to make my commit?
thanks a lot! I will commit in a new branch and after commit I will make the pull request, if accept my pull is good to me.
thanks a lot.

**Comment by cowtowncoder** [comment]
The usual way is to fork project, using github UI, and then create a Pull Request (PR). You can not push branches directly to this project, as that is only available for project committers with access: but you do not need that for forking and Pull Requests. PRs can then be approved and merged by committers, after reviewing them.

But in this case, as per my other notes, I do not think this change makes sense.

**Comment by dcbasso** [comment]
Thanks no problem.
We already discuss this in another issues.
Thanks for your time.
