### ISSUE TITLE
`ObjectReader.at()` with `JsonPointer` stops after first collection

### ISSUE THREAD

**Issue by strmer15** [FasterXML/jackson-databind#1637]
Jackson versions: 2.8.7/2.8.8/2.9.0.pr3

I'm currently trying to enable a scheme like this, via YAML, for environment specific configuration:

```
_default_:
  value1: "dev_value"

production:
  value1: "prod_value"
```

I'm trying to do this by creating an ObjectReader and using `ObjectReader.at("/_default_")` or, more generally, `ObjectReader.at("/" + ENV_NAME)` method calls.

This works great when combined with 'readerForUpdate' to create environment-specific overrides against specific configuration POJOs.  However, I've found that the following breaks:

```
_default_:
  set1:
    - one
    - two
  set2:
    - three
    - four
```

In that case, calling `ObjectReader.at("/_default_").readValue(yamlString)` returns an object that has a null value for 'set2'.  I initially thought this was an issue with the YAML parser itself, but found the same issue with the JSON parser.

Test Case:

```
public class JsonPointerTest {

    @Test
    public void testJsonPointer() throws Exception {
        final String json = "{\n\"wrapper1\": {\n" +
                "  \"set1\": [\"one\", \"two\", \"three\"],\n" +
                "  \"set2\": [\"four\", \"five\", \"six\"]\n" +
                "},\n" +
                "\"wrapper2\": {\n" +
                "  \"set1\": [\"one\", \"two\", \"three\"],\n" +
                "  \"set2\": [\"four\", \"five\", \"six\"]\n" +
                "}\n}";

        final TestObject testObject = new ObjectMapper().readerFor(TestObject.class).at("/wrapper1").readValue(json);

        Assert.assertNotNull(testObject);

        Assert.assertNotNull(testObject.getSet1());
        Assert.assertTrue(!testObject.getSet1().isEmpty());

        Assert.assertNotNull(testObject.getSet2());
        Assert.assertTrue(!testObject.getSet2().isEmpty());
    }

    public static class TestObject {
        private Set<String> set1;
        private Set<String> set2;

        public Set<String> getSet1() {
            return set1;
        }

        public void setSet1(Set<String> set1) {
            this.set1 = set1;
        }

        public Set<String> getSet2() {
            return set2;
        }

        public void setSet2(Set<String> set2) {
            this.set2 = set2;
        }
    }
}

```
Seems like the parser is exiting early after the first array value?  I've tested this with 2.8.8 and 2.9.0.pr3 and both fail the test case.

**Comment by cowtowncoder** [comment]
That does sound like a bug, unless I missed something.
If so, it is most likely due to a problem with underlying stream filtering implementation, which does have at least one open issue (https://github.com/FasterXML/jackson-core/issues/330), and possibly others not reported yet.

**Comment by rfoltyns** [comment]
I've just patched it [here](https://github.com/rfoltyns/jackson-core/commit/6f6bbb83aa4b1c7319c35500a25e38c3f163a997). Please have a look.

**Comment by cowtowncoder** [comment]
Excellent; I added the test which now passes with the patch. Both will be in `2.9.0.pr4`
