### ISSUE TITLE
Duplicate fields are silently ignored in BeanDeserializer

### ISSUE THREAD

**Issue by abar-or** [FasterXML/jackson-databind#164]
Hello,

I am using Jackson release 2.0.2 . BeanDeserializer implementation silently ignores Field duplicates in line 541:

            SettableBeanProperty creatorProp = creator.findCreatorProperty(propName);
            if (creatorProp != null) {
                // Last creator property to set?
                Object value = creatorProp.deserialize(jp, ctxt);

    Line 541:
       if (buffer.assignParameter(creatorProp.getPropertyIndex(), value)) {
                    jp.nextToken(); // to move to following FIELD_NAME/END_OBJECT

There is no way currently to override this behavior and throw an error.  I suggest to check if the buffer already contains value in this property index and then allow to throw an exception.  Perhaps add a new annotation to trigger this behavior. 

Appreciate your feedback. 

Best Regards,
Amir Bar-Or

**Comment by cowtowncoder** [comment]
`JsonParser.Feature.STRICT_DUPLICATE_DETECTION` was added in Jackson 2.3.
This could/should be used for finding duplicates, as necessary.

Note that support for this varies between data formats: for JSON, CBOR, Smile it should work without problems; with other formats support may be incomplete or miss. If so, please file issues for specific data format module.
