### ISSUE TITLE
No leading '.' when serializing polymorphic classes using JsonTypeInfo.Id.MINIMAL_CLASS

### ISSUE THREAD

**Issue by oli-d** [FasterXML/jackson-databind#1640]
Serializing polymorphic types using JsonTypeInfo.Id.MINIMAL_CLASS always leaves a leading '.' in front of the simpleClassName. As a simple example, let's assume I have the following class structure:

Base class Message:

```
@JsonTypeInfo(use=JsonTypeInfo.Id.MINIMAL_CLASS,
                include = JsonTypeInfo.As.PROPERTY,
                property = "type")
public class Message {
}

```

and sub class Error:
```
public class Error extends Message {
    public final String code;
    public final String details;

    @JsonCreator
    public Error(@JsonProperty("code") String code, @JsonProperty("details") String details) {
        this.code = code;
        this.details = details;
    }
}

```

So serializing an error to a String results something like this:

`{"type":".Error","code":"some code","details":"some details"}`

Since the beauty of JSON is its comprimise between compactness and readability, I would really love to see 

`type="Error"` (without leading '.')

instead of

`type = ".Error"`

since it would be much, much nicer to read.

**Comment by cowtowncoder** [comment]
This is intentional and necessary to distinguish between case of sub-class being in same package as base class (in which case parent package is used), vs case of class not belong to a package (that is, directly in root package).
Original choice was to leave dot out for more common case of there being package, I think.

Either way this is a feature that can not be changed at this point, due to backwards compatibility.

**Comment by oli-d** [comment]
Thanks for commenting on this and the explanation. But why not make super classes look "nice" and eventual sub classes "ugly" by e.g. adding a '$' in front of the simpelClassName? 

What removing the '.' would give is the ability to very conveniently implement APIs / services using JSON objects. Cross platform. 

If e.g. a JavaScript client would want to create and send an `Error` message to my Java service, it could simply construct a - very naturally looking - JSON object:

```
{
  type: "Error",
  code: "some code",
  details: "some details"
}
```

and on the Java side, I wouldn't have to do anything, I could simply use the object mapper to read the incoming String.

Of course, there are workarounds, but they come with maintaining a set of constants that map a magic `type` value in a message to the desired class. Out of the box, as proposed, it would be MUCH nicer...

Anyways, thanks again for looking into this.

**Comment by cowtowncoder** [comment]
One additional thing to note: for prettier types, it often makes more sense to use `@JsonTypeName`, instead of relying on class names. This is bit more work, but is more flexible and robust as it removes explicit binding between classes and type names. Anyway, just a thought.
