### ISSUE TITLE
JacksonJaxbJsonProvider enum serialization/deserialization change between versions

### ISSUE THREAD

**Issue by flenzi** [FasterXML/jackson-databind#1644]
Have a jaxrs service using the JacksonJaxbJsonProvider. Using the 
><dependency>
>    <groupId>com.fasterxml.jackson.core</groupId>
>    <artifactId>jackson-databind</artifactId>
>     <version>2.4.5</version>
></dependency>
The enum serialization is made with the name if the enum, according the documentation this is right.
http://static.javadoc.io/com.fasterxml.jackson.core/jackson-databind/2.4.5/com/fasterxml/jackson/databind/SerializationFeature.html#WRITE_ENUMS_USING_TO_STRING

Now that I to the version 2.8.7, it is being made with the ToString. Checking the docs there are no changes http://static.javadoc.io/com.fasterxml.jackson.core/jackson-databind/2.8.7/com/fasterxml/jackson/databind/SerializationFeature.html#WRITE_ENUMS_USING_TO_STRING and it should be disable by default.

**Comment by cowtowncoder** [comment]
@flenzi I'd need to see a reproduction, ideally unit test, to understand the exact usage. Default should indeed be to use just `enum.name()`, unless configuration overrides or annotations are used.
If reproduction can only rely on JAXB annotations module that'd be great; if not, then with jax-rs provider but ideally no external dependencies (like framework that embeds it).

Note that this issue most likely belongs to either `jackson-module-jaxb-annotations` or `jackson-jaxrs-providers` (and not core databind). But I can re-create it as necessary (or you can if you want to).

**Comment by flenzi** [comment]
For whay I'm seeing the com.fasterxml.jackson.jaxrs.json.JacksonJaxbJsonProvider doesn't care about the configuration, I made something like

> public final class CustomJacksonJaxbJsonProvider extends JacksonJaxbJsonProvider {
> 
>     public CustomerJacksonObjectMapper() {
>         super();
>         this.configure(DeserializationFeature.READ_ENUMS_USING_TO_STRING, false);
>         this.configure(SerializationFeature.WRITE_ENUMS_USING_TO_STRING,false);
>         this.configure(SerializationFeature.INDENT_OUTPUT,true);
>     }
> }

But it seems JacksonJaxbJsonProvider uses @XmlEnumValue no matter what configuration it has.

**Comment by flenzi** [comment]
Ended up changing the @XmlEnumValue in my enums
