### ISSUE TITLE
JsonMappingException when used with Jersey EntityFilteringFeature

### ISSUE THREAD

**Issue by amichair** [FasterXML/jackson-databind#1645]
Using jersey-container-servlet 2.25 and jersey-media-json-jackson 2.25 (which uses jackson 2.8.4).

The application ResourceConfig includes:
```java
// gzip support
register(EntityFilteringFeature.class);
EncodingFilter.enableFor(this, GZipEncoder.class);
// jackson serializer
register(JacksonFeature.class);
// application classes
packages("com.example");
```

if only one of JacksonFeature or EntityFilteringFeature is used, everything is ok. But when both are used together, Jackson serialization fails with

>JsonMappingException: Can not resolve PropertyFilter with id 'java.util.LinkedHashMap'; no FilterProvider configured

There are a few similar issues reported in e.g. stackoverflow, with very elaborate workarounds. The workaround I found is modifying the custom ObjectMapper used in the application to use a no-op filter:

```java
SimpleFilterProvider filterProvider = new SimpleFilterProvider();
filterProvider.setDefaultFilter(new SimpleBeanPropertyFilter.SerializeExceptFilter(Collections.emptySet()));
mapper.setFilterProvider(filterProvider);
```

So it seems like adding gzip support to a jersey+jackson application breaks jackson.

I'm not 100% sure the issue is with Jackson rather than Jersey, but since both the exception and the workaround are on the Jackson side, I'll point the finger here for now :-)

**Comment by cowtowncoder** [comment]
It definitely seems to be something Jersey is misconfiguring wrt filters: possibly dropping definitions.
But I don't see what else Jackson can do if a value type specifies filter to use, but none is configured.

**Comment by amichair** [comment]
Thanks for the quick response. I opened an issue with Jersey at https://github.com/jersey/jersey/issues/3574.

**Comment by cowtowncoder** [comment]
@amichair No problem, wish I could have been of more help.
