### ISSUE TITLE
Give Custom Deserializers access to the resolved target Class of the currently deserialized object

### ISSUE THREAD

**Issue by Laures** [FasterXML/jackson-databind#165]
Jackson resolves the target class for a json object using parameter/property types, annotations, json properties or a parameter in the object mapper.

please give custom deserializers easy access to this information. currently it is nearly impossible to create a deserializer that works for multiple types. the only way would be to implement "contextualdeserializer" and access the bean property which is very complicated.

**Comment by taypo** [comment]
I don't understand how this will work? Do we have way to create deserializers without type information and then use `getContextualType()` inside the deserializer implementation?

**Comment by cowtowncoder** [comment]
@taypo Not quite. You will need to implement `ContextualDeserializer` interface (just method `createContextual()`) and construct an instance that knows the target type -- either via `BeanProperty` passed (if available) or using method in `DeserializationContext` mentioned.
