### ISSUE TITLE
Convenience overload(s) for ObjectMapper#registerSubtypes

### ISSUE THREAD

**Issue by chrylis** [FasterXML/jackson-databind#1653]
`ObjectMapper` provides the `registerSubtypes()` methods to help with polymorphic deserialization, but the signatures are varargs-only. I'm using the Reflections library, which returns `Set<Class<?>>` from various queries, and I can imagine some similar circumstances where the user would want to provide a collection of types. Would it be sensible to add an overload `registerSubtypes(Collection<Class<?>>)`?

**Comment by cowtowncoder** [comment]
Sure, that sounds reasonable.
