### ISSUE TITLE
Infinite recursion when deserializing a class extending a Map, with a recursive value type.

### ISSUE THREAD

**Issue by newkek** [FasterXML/jackson-databind#1658]
Hello, I am using jackson-databind 2.8.8, and have a class with an unusual definition (extending a Map, where the values are of the type of the same class). It seems like I am facing an infinite recursion issue.

To reproduce you can re-use or inspire from the class defined [here](https://github.com/apache/tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/step/util/Tree.java).

Then, when executing the following code:

```java
        Tree t = new Tree("hello", new Tree("world"));

        ObjectMapper om = new ObjectMapper();
        final TypeResolverBuilder<?> typer = new StdTypeResolverBuilder()
                .init(JsonTypeInfo.Id.CLASS, null)
                .inclusion(JsonTypeInfo.As.PROPERTY)
                .typeProperty(GraphSONTokens.CLASS);
        om.setDefaultTyping(typer);

        String res = om.writeValueAsString(t);
        Object tRead = om.readValue(res, Tree.class);
```

When calling `readValue()` the mapper throws a `StackOverflowException` , here's the stacktrace:
```
java.lang.StackOverflowError
	at org.apache.tinkerpop.shaded.jackson.databind.type.MapLikeType.equals(MapLikeType.java:305)
	at org.apache.tinkerpop.shaded.jackson.databind.type.ResolvedRecursiveType.equals(ResolvedRecursiveType.java:110)
	at org.apache.tinkerpop.shaded.jackson.databind.type.MapLikeType.equals(MapLikeType.java:305)
	at org.apache.tinkerpop.shaded.jackson.databind.type.ResolvedRecursiveType.equals(ResolvedRecursiveType.java:110)
	at org.apache.tinkerpop.shaded.jackson.databind.type.MapLikeType.equals(MapLikeType.java:305)
	at org.apache.tinkerpop.shaded.jackson.databind.type.ResolvedRecursiveType.equals(ResolvedRecursiveType.java:110)
	at org.apache.tinkerpop.shaded.jackson.databind.type.MapLikeType.equals(MapLikeType.java:305)
	at org.apache.tinkerpop.shaded.jackson.databind.type.ResolvedRecursiveType.equals(ResolvedRecursiveType.java:110)
	at org.apache.tinkerpop.shaded.jackson.databind.type.MapLikeType.equals(MapLikeType.java:305)
[...]
```

Looking briefly into the code, it seems like because of the recursive definition of the class, the [equals](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/type/MapLikeType.java#L305) call in `MapLikeType` may never get out of this loop. Any idea?

Thanks.

**Comment by newkek** [comment]
This also occurs with 2.8.7 fwiw.

**Comment by cowtowncoder** [comment]
I think I'd need a reproduction here (code above gets close. Most likely `ResolvedRecursiveType` just has to indicate it's only equal to itself, to avoid the problem. I'll see if I can use pieces above to do the repro.

**Comment by newkek** [comment]
Ok, thanks. As I mentioned above you can copy-paste the `Tree` class I linked (it doesn't have any external dependency) and then just execute the code in the snippet to reproduce.

**Comment by cowtowncoder** [comment]
Unfortunately I seem unable to reproduce this with trivial setup... something in there is not re-creating self-recursive type (or comparing equality). Will keep on trying, maybe I can crack this.

**Comment by cowtowncoder** [comment]
Ok. And now I am actually able to produce a `ResolvedRecursiveType`, but without hitting StackOverflow.

So, unfortunately I will need some help reproducing the failure.

**Comment by newkek** [comment]
Thank you for checking.

I am confused about "And now I am actually able to produce a `ResolvedRecursiveType`" - did that happen when you used the `Tree` class I linked earlier?
This really seems to be caused by a class being *both* recursive, and an extension of a Map, like that Tree class.

**Comment by newkek** [comment]
Was able to confirm with other people - when trying to run the exact example I explained - that they run into the issue too.

**Comment by cowtowncoder** [comment]
@newkek At this point I need a self-contained test. I was unable to make equality test fail for `ResolvedRecursiveType`, as described: this does not mean there is no problem, just that there was something in the result (perhaps call sequence, state, context) that did not give the SOE.

So: explaining an example is not of use. I need specific code.

**Comment by newkek** [comment]
Alright, so I pushed a self-contained test case over here: https://gist.github.com/newkek/d8998836dcdba91cc92bf5d03d46aea7

*Important:* After more tests, I think it seems like the issue has nothing to do with what I expected. You see that in the `Tree` I included in the test class, there is a method:
```java
public List<Tree<T>> getLeafTrees()
```
That method is never called, and it doesn't do anything in this code snippet. **However**, it turns out that if I rename the method, or remove the word "get" in the beginning of it, **I do not get the SOE anymore**. Do you think that this could be due to some kind of "getter research" mechanism in the Jackson code by any chance?

Please let me know if you manage to reproduce, and thanks for looking into it.

**Comment by cowtowncoder** [comment]
Much appreciated, thank you!
