### ISSUE TITLE
MapLikeType.getKeyType and getContentType are not returning the real generic types of the Map, but java.lang.Object in 2.7.5 and above version

### ISSUE THREAD

**Issue by ras165** [FasterXML/jackson-databind#1666]
In Jackson 2.6.1,  MapLikeType.getKeyType  used to return the real generic types but when upgrading to 2.7.5 it is returning java/lang.Object.  This is breaking our existing code when trying to upgrade to version - 2.7.5. Please help on this.

**Context:**

The problem is when Jackson is calling modifyMapLikeSerializer. MapLikeType.getKeyType and getContentType are not returning the real generic types of the Map, but java.lang.Object.

Please see the sample Java Code for same:
```
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.databind.BeanDescription;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationConfig;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.ser.BeanSerializerModifier;
import com.fasterxml.jackson.databind.type.MapType;

public class Test {

    public static void main(String[] args) throws Exception {
        System.out.println("Testing with an EmptyMap:");
        validate(null);
        System.out.println();
        System.out.println("Testing with a real Map:");
        validate(Collections.singletonMap("Foo", 123));
    }

    public static void validate(Map<String, Integer> map) throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        MySimpleModule myModule = new MySimpleModule();
        mapper.registerModule(myModule);
        MyClass myClass = new MyClass(map);
        System.out.println(mapper.writeValueAsString(myClass));
        System.out.println(myModule.getKeyType());
        System.out.println(myModule.getValueType());
    }

    public static class EmptyMap extends HashMap<Object, Object> {

        private static final EmptyMap INSTANCE = new EmptyMap();

        @SuppressWarnings("unchecked")
        public static <K, V> Map<K, V> get() {
            return (Map<K, V>) INSTANCE;
        }

    }

    public static class MyClass {

        public Map<String, Integer> field;

        public MyClass() {
            this.field = EmptyMap.get();
        }

        public MyClass(Map<String, Integer> field) {
            this.field = field == null ? EmptyMap.get() : field;
        }

        public Map<String, Integer> getField() {
            return field;
        }

        public void setField(Map<String, Integer> field) {
            this.field = field == null ? EmptyMap.get() : field;
        }

    }

    public static class MySimpleModule extends SimpleModule {

        public final MyBeanSerializerModifier myBeanSerializerModifier;

        public MySimpleModule() {
            this.myBeanSerializerModifier = new MyBeanSerializerModifier();
            this.setSerializerModifier(myBeanSerializerModifier);
        }

        public Class<?> getKeyType() {
            return myBeanSerializerModifier.getKeyType();
        }

        public Class<?> getValueType() {
            return myBeanSerializerModifier.getValueType();
        }

    }

    public static class MyBeanSerializerModifier extends BeanSerializerModifier {

        public Class<?> keyType;
        public Class<?> valueType;

        public Class<?> getKeyType() {
            return keyType;
        }

        public Class<?> getValueType() {
            return valueType;
        }

        @Override
        public JsonSerializer<?> modifyMapSerializer(SerializationConfig config, MapType mapType, BeanDescription beanDesc, JsonSerializer<?> serializer) {
            this.keyType = mapType.getKeyType().getRawClass();
            this.valueType = mapType.getContentType().getRawClass();
            return super.modifyMapSerializer(config, mapType, beanDesc, serializer);
        }

    }

}
```

Running the above code with Jackson 2.6.1 produces following output - 

Testing with an EmptyMap:
{"field":{}}
class java.lang.String
class java.lang.Integer

Testing with a real Map:
{"field":{"Foo":123}}
class java.lang.String
class java.lang.Integer

Running the same code with Jackon 2.7.5 is producing following output - 
Testing with an EmptyMap:
{"field":{}}
class java.lang.Object
class java.lang.Object

Testing with a real Map:
{"field":{"Foo":123}}
class java.lang.String
class java.lang.Integer

**Comment by cowtowncoder** [comment]
First: could you please verify with LATEST patch version of 2.7 (2.7.9)? I find it really frustrating when sometimes reports are against bugs that have already been fixed. And given that 2.7 had new rewritten type resolution system, patches had a few fixes.

**Comment by ras165** [comment]
I have tried to run the same Test.java using 2.8.3 version also but the result is still same (just like 2.7.5) - 

Testing with an EmptyMap:
{"field":{}}
class java.lang.Object
class java.lang.Object

Testing with a real Map:
{"field":{"Foo":123}}
class java.lang.String
class java.lang.Integer

**Comment by cowtowncoder** [comment]
This gets complicated enough so that I don't quite know what happens, but one thing to note is that `EmptyMap` is parameterized as `Map<Object,Object>`, which may be why resolved type has those as parameters. Type resolution may try to refine declared field type, but has incompatible assignments as real value claims to be of that type.

Not sure if change of `EmptyMap` declaration to use type variables instead would change anything, just adding notes that may help troubleshoot.

Another possibility, and perhaps more likely to work, would be to add 

```java
@JsonSerialize(typing=Typing.STATIC)
```

which should force use of declared type of property, regardless of more specific implementation.

**Comment by ras165** [comment]
Tried both the option and none of them seems to work.

**Comment by ras165** [comment]
@cotowncoder, the behavior of  MapLikeType.getKeyType is different in version 2.7.5+. Is it likely to get fixed in coming release of Jackson.

**Comment by cowtowncoder** [comment]
@ras165 I don't know what exactly is going on, and have no plans on tackling this. So most likely newer behavior will continue to be the way.
