### ISSUE TITLE
Clarifications about optional Date/Time fields

### ISSUE THREAD

**Issue by brenuart** [FasterXML/jackson-databind#1667]
Here is an excerpt from the ISO8601 norm (source: https://en.wikipedia.org/wiki/ISO_8601 - sorry could not find any official source) - in _General Principles_ it says:
> (1) Date and time values are ordered from the largest to smallest unit of time: year, month (or week), day, hour, minute, second, and fraction of second. (...) This allows dates to be naturally sorted by, for example, file systems.
> (2) Each date and time value has a *fixed number of digits* that must be padded with leading zeros.
> (3) For reduced accuracy, *any number of values may be dropped* from any of the date and time representations, but in the order from the least to the most significant.

BTW, you will notice (1) is guaranteed only if (2) and (3) are respected...

Lets focus on the _optional_ fields.

As per comments in the code, I understand the StdDateFormat allows for optional `millis` and `seconds`. Although it does it correctly for millis, its behavior is not coherent for the secods as shown in the examples below:

- `2000-01-02T03:04+01:00` --> Ok
- `2000-01-02T03:04Z` --> Failure
- `2000-01-02T03:04` --> Failure

This can be easily fixed... However I wonder why `millis` and `seconds` are optional and not `hours` and `minutes`? Or maybe it is the opposite? So the question is: _*what is the desired behavior_*? 
- none are optional
- only `millis` is optional
- `seconds` and `millis` (<-- what seems to be the current design goals as per code comments)
- `minutes`, `seconds` and `millis` are optional
- all time fields are optional

Note the last case is already supported by means of the "date only" format. But then the same question arises for the date fields... None are currently optional.

The StdDateFormat is heavily based on `java.text.SimpleDateFormat`. Unfortunately this parser does not support optional fields. If we want to support them, we have to pre-parse the input string to detect the missing fields and fill them with a default value before it is sent to the SimpleDateFormat. If we want them _all_ optional, we end up parsing the entire string and split it into its constituent parts. We will have reimplemented most of what the SimpleDateFormat is supposed to do for us... Although everybody will be happy if we get rid of it (lol), I don't think it is wise to go that road...

IMHO we'd better to limit the number of optional fields to the minimum. Even better if they are adjacent and "close to the end of the string". 

My opinion on the subject is motivated by the following facts:
- As of today, `millis` are optional and its works ok in every tested scenarios. People are likely to rely on it. We should probably keep them optional to avoid breaking things...
- As explained above, `seconds` is more questionable as only one form is currently accepted. We won't break anything by making it optional in all cases (ie. fix current behavior). The drawback is it makes the parser a bit more complex and harder to maintain.
- The "date only" form (`yyyy-MM-dd`) is widely used and the only way to accept _LocalDate_ representations with `java.util.Date`

Conclusion: `millis` and `seconds` should be optional + all time fields can be omitted altogether. This is apparently the current desired behavior - we just need to fix it.

**Comment by cowtowncoder** [comment]
Ok, so first things first: I am pretty sure that accepting of missing seconds (for example) is a side-effect of too loose checks -- code tries to ensure valid cases work, but does not spend much effort up front in detecting invalid cases. Instead, value is handed to `SimpleDateFormat`, which seems to be more lenient than I'd expect.

Now: to me, optional things would be:

1. Milliseconds (but not other time values)
2. Timezone/offset information

So it's ok to only provide date; or date and time (but not fractional seconds; or if fractions, less than 3).

We could perhaps also allow seconds to be optional if it makes sense: this seems relatively simple to implement (depending on how it's done).

I am playing with simple regex right now which can express these easily; just having slight problems making `Calendar` not barf on something missing... :)

**Comment by brenuart** [comment]
Should we close this issue since you rewrote most of the `StdDateFormat` ?

**Comment by cowtowncoder** [comment]
@brenuart yes, thank you.
