### ISSUE TITLE
`@JsonAnySetter` deserialization fails with parameter names module

### ISSUE THREAD

**Issue by vpavic** [FasterXML/jackson-databind#1672]
Starting with Jackson release `2.9.0.pr1` deserialization of `@JsonAnySetter` fails when `ParameterNamesModule` is registered.

The following sample demonstrates the problem:

```gradle
apply plugin: 'java'

ext {
	jacksonVersion = '2.9.0.pr4'
}

repositories {
	jcenter()
}

dependencies {
	compile "com.fasterxml.jackson.core:jackson-databind:$jacksonVersion"
	compile "com.fasterxml.jackson.module:jackson-module-parameter-names:$jacksonVersion"

	testCompile 'junit:junit:4.12'
	testCompile 'org.assertj:assertj-core:3.8.0'
}
```

```java
public class AnySetterRegressionTests {

	@Test
	public void deserialization() throws Exception {
		String content = "{ \"info1\":\"value1\", \"info2\":\"value2\" }";
		ObjectMapper objectMapper = new ObjectMapper();
		objectMapper.registerModule(new ParameterNamesModule());
		BaseClientDetails clientDetails = objectMapper.readValue(content, BaseClientDetails.class);
		Map<String, Object> additionalInfo = clientDetails.additionalInformation;
		assertThat(additionalInfo).hasSize(2);
		assertThat(additionalInfo.get("info1")).isEqualTo("value1");
		assertThat(additionalInfo.get("info2")).isEqualTo("value2");
	}

	@JsonInclude(JsonInclude.Include.NON_DEFAULT)
	@JsonIgnoreProperties(ignoreUnknown = true)
	static class BaseClientDetails {

		private final Map<String, Object> additionalInformation = new HashMap<>();

		@JsonAnySetter
		public void addAdditionalInformation(String key, Object value) {
			this.additionalInformation.put(key, value);
		}

	}

}
```

The test passes either when `ParameterNamesModule` is not registered, or when Jackson release `2.8.9` is used.

This was originally reported as spring-projects/spring-boot#9553.

**Comment by cowtowncoder** [comment]
Thank you for reporting the problem. This actually kind of belongs under parameter-names module, although the problem may be within databind... hard call. So it's fine as is for now, I can move the issue if need be.

One suggestion please do not enable `ignoreUnknown` for test case (unless it is specifically relevant to bug) -- it is known to hide problems, and is the main reason why it is not enabled by default.
I don't know if that matters here, but I mention it for future reference.

**Comment by cowtowncoder** [comment]
Surprise surprise: removing "ignore unknown" yields an exception, which suggests that `@JsonAnySetter` is not found. :)

**Comment by cowtowncoder** [comment]
Interesting. So the root cause was a problem with newly (2.9) added `AnnotationIntrospector.hasAnySetter()` default implementation, which returned `Boolean.FALSE` instead of `null` like it should. And then AI by parameter-names module extended this, claiming no method is marked as any-setter; and having precedence over standard `JacksonAnnotationIntrospector`.

Good thing we catched this before 2.9.0 -- thank you for reporting it!

**Comment by vpavic** [comment]
Thanks for quick resolution @cowtowncoder!
