### ISSUE TITLE
FEATURE: a self-contained ObjectMapper jar / lightweight derivative of jackson-databind, possibly in core?

### ISSUE THREAD

**Issue by sunnygleason** [FasterXML/jackson-databind#1686]
Hi,

First off, thank you so much for Jackson, it is a key foundation
component of all the services I build!

As such, I was recently reviewing the size of dependencies for
a small service, and realized that jackson-databind, at 1.2MB,
is 33% of the total application size.

My code only really uses ObjectMapper.readValue(String,
LinkedHashMap.class) and ObjectMapper.writeValueAsString();
I imagine there's a reasonable portion of the ObjectMapper API
that is useful for a ton of use cases.

This made me wonder -- would it be useful to put together a
micro jar derivative of ObjectMapper that is very easy for utility
situations? (If it's super small, it might even fit into jackson core?)...

In any event, I'd be interested in building/contributing this if you
think it's a good idea. Thank you again so much!

Sincerely,

-Sunny Gleason

**Comment by cowtowncoder** [comment]
You probably haven't seen this yet? :)

https://github.com/FasterXML/jackson-jr/

It should do what you want, and added code for `jr-objects` is less than `jackson-core`.
There are other optional goodies (like tiny read-only tree model), but for simple `Map`/`List` -- and even (real) Beans this gets down to bit over 300 kB.
Plus it's been around for a few releases and should be stable.

It also has one thing that does not exist in core or databind: composers, for convenient JSON generation.

**Comment by sunnygleason** [comment]
Wow, this is awesome, thank you so much -- can't believe it came out 3 years ago, where was I?

Random question: why did you drop the T readValue(String, Class<T>) API?
Because it generated cast warnings anyway?

In any event, this gets the deps down to ~360k - pretty awesome!

Thank you again,

-Sunny

PS: what are you building right now that I'm going to ask for in 3Y? :)

**Comment by cowtowncoder** [comment]
Well `JSON` does have `public <T> T beanFrom(Class<T> type, Object source)`. Unless you mean databind? But if so, no `readValue()` methods have been removed. So I am probably misunderstanding this part.

On features... every time, before planning for a  "minor" version, I think I'll run out of things I want to implement. Every time I find that I won't: typically I implement maybe 50% of what I planned, and another batch of things I didn't. And then tend to figure out new things I really really want to implement; sometimes my own ideas, as or more often ideas others mention directly or (way more often) indirectly, by pointing out omission.

For 2.9 I am adding some cool stuff, mostly to support "Configuration" use case: ability to do deep merging; configurable handling of `null`s (set / ignore / convert-to-empty). Also plenty of support for more complex formats with their schemas (avro schema handling for example).
Oh and better support for type ids (also partly to help with Avro, but not just that).
And starting to think of what should be changed with 3.0, most likely there won't be 2.10 (but who knows for sure).

If I had more time, better focus, I'd also write my "Jackson book" (I have outline, Intro). :-)
