### ISSUE TITLE
Deserialization fails for `java.nio.file.Path` implementations when default typing enabled

### ISSUE THREAD

**Issue by Dissem** [FasterXML/jackson-databind#1688]
Deserialization of a map that contains a Path fails when default typing is enabled on the object mapper. If Typing is not enabled, the object will be deserialized as String which isn't very helpful either.

The problem comes from Jackson storing the class information as `sun.nio.fs.UnixPath`, but checking for `java.nio.file.Path` in `Java7SupportImpl#getDeserializerForJavaNioFilePath(Class<?> rawType)`, but I wouldn't know which part should get fixed.

Here's a test to show the issue:

```
@Test
public void testPathInMapRoundtrip() throws Exception
{
    Path input = Paths.get("/tmp", "foo.txt");
    Map<String, Object> map = new HashMap<>();
    map.put("file.path", input);

    ByteArrayOutputStream out = new ByteArrayOutputStream();

    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.enableDefaultTyping();

    objectMapper.writeValue(out, map);

    TypeReference<HashMap<String,Object>> typeRef = new TypeReference<HashMap<String,Object>>() {};
    Map<String, Object> p = objectMapper.readValue(new ByteArrayInputStream(out.toByteArray()), typeRef);

    assertEquals(map, p);
}
```

(I'm using version 2.8.9)

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Yes, problem is as you describe. There are couple of possible fixes here; either by using looser check on deserialization (to sort of downgrade type), or to do similar downgrade during type id serialization.
I'll have to think about how to go about this: latter seems like bit better idea, and is used for some cases already.

**Comment by cowtowncoder** [comment]
Fixed so that it should work for default `Path` implementation: slightly concerned that handling not exactly good for cases where other implementations used -- but since those wouldn't have worked previously without custom (de)serializer, or `@JsonCreator` annotation I think risk should not be great.

Anyway: what happens now is that type id is declared as simple `java.nio.path.Path`, regardless of subtype.
