### ISSUE TITLE
Add support for data versioning

### ISSUE THREAD

**Issue by wheredevel** [FasterXML/jackson-databind#169]
http://jira.codehaus.org/browse/JACKSON-108
resubmitting the original feature request by Tatu Saloranta

One interesting idea re-purposed from another json data binding library is allowing some method of versioniong data to include in serialization and/or deserialization.

Basically, it might be possible to add simple annotations, associated with properties (accessor methods now; fields in future), which can be used to exclude certain properties if expected data version is below (or perhaps above?) specified threshold.

That is: properties could declare version in which they were introduced (or deprecated if need be); and ObjectMapper could be told which data format version to expect. Based on these, serializer/deserializer could handle/expect different set of properties.

Question of where the version should come from should be solved: simplest possibility is to assume it is external to data (metadata passed with method calls, or configured with system), but it could also be possible to configure inlining of such information.
This feature could be important for longer-living web service implementations; and make it safer to add (or in due time, remove) properties to objects being passed.

**Comment by jonpeterson** [comment]
For a while I've wanted a model versioning feature in Jackson, so I recently sat down and wrote one. Hopefully this helps any Googlers who stumble in here.

https://github.com/jonpeterson/jackson-module-model-versioning

**Comment by cowtowncoder** [comment]
@jonpeterson Thank you for sharing this!

**Comment by cowtowncoder** [comment]
No plans to implement and quite general description of the ask: may be re-filed if there is more concrete plan
(or if there's PR to implement).
