### ISSUE TITLE
JsonNode.decimalValue() returns BigDecimal.ZERO unexpectedly

### ISSUE THREAD

**Issue by morrica** [FasterXML/jackson-databind#1702]
Version: 2.8.8
JsonNode.decimalValue() returns BigDecimal.ZERO unexpectedly when the value of the node is in quotes, i.e. `{"foo":"1.2546875"}`. This is problematic because most APIs requiring high precision decimals quote all decimal values to ensure no rounding occurs during a conversion to float.

I understand that the value in quotes is not technically a numeric type so perhaps this behavior is intentional. However, if that is the case, it would make much more sense to throw an exception or return null rather than returning a completely invalid value that will not be caught quickly during development. Also, no note on the behavior of the method is included in it's javadocs, making using it inappropriately an easy mistake to make.

Currently, the way to retrieve the value of a high precision float from an API would be something like this:
`BigDecimal val = new BigDecimal(node.asText())`. I propose that if the value of the json is quoted `JsonNode.decimalValue()` should return the same value. If the quoted content is not parsable as a `BigDecimal`, `decimalValue()` should return null or throw an exception. In no case should it return a `BigDecimal` that doesn't properly represent the actual json content.

If changing the current behavior is an issue for backwards compatibility reasons, I would suggest depricating `decimalValue()` and replacing it with an `asBigDecimal()` method.

I imagine this issue probably also occurs with `JsonNode.bigIntegerValue()`, although I have not investigated that.

Thank you for you time,
Cavan Morris

**Comment by cowtowncoder** [comment]
@morrica Thank you for reporting this; behavior sounds wrong.

Would it be possible to provide brief code snippet, just to make 100% sure I can reproduce it.
There are many different ways to get to a tree model, and access, so I just want to make sure I'll follow one you are observing.

**Comment by morrica** [comment]
Sure. I think the below should do it.

```
package issue1702;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.math.BigDecimal;

/**
 * Created by morrica on 7/14/17.
 */
public class Issue1702 {

    public static void main(String[] args) throws IOException {

        ObjectMapper objectMapper = new ObjectMapper();

        String json = "{\"foo\":\"1.12645897\", \"bar\":1.12645897}";

        JsonNode node = objectMapper.readValue(json, JsonNode.class);

        BigDecimal foo = node.path("foo").decimalValue();
        BigDecimal bar = node.path("bar").decimalValue();

        System.out.println("foo = " + foo);
        System.out.println("bar = " + bar);
    }
}

```

**Comment by cowtowncoder** [comment]
Thanks!

**Comment by cowtowncoder** [comment]
Actually looking at `JsonNode` API, this works as intended (see for example javadoc for `doubleValue()`). Unfortunately javadocs are missing for `decimalValue()` and `bigIntegerValue()`.
Intent with these methods is that value returned for non-numeric nodes is the empty/default value: and for coercions, "asXxx()" needs to be called instead. But unfortunately only "asInt()", "asDouble()", "asBoolean()" exist: no counterpart yet added for `BigDecimal` or `BigInteger`.

It could be argued that an exception should be thrown instead, but changing API at this point (within 2.x) is not something we may do.

So: if JSON String to `BigDecimal` coercion is needed, code has to handle that explicitly, at this point.
