### ISSUE TITLE
Same properties are parsed multiple times when variable name is capitalized and JsonProperty annotated

### ISSUE THREAD

**Issue by dentych** [FasterXML/jackson-databind#1713]
I have created a repo for this bug. See here: https://github.com/dentych/jackson-bug

In short terms, the issue is that variables in caps (e.g. MAT) that is annotated with JsonProperty("MAT") will be in the serialized JSON string twice.

The example output from my reproduction:
The POJO "MyCollection":
```java
class MyCollection {
    @JsonProperty("MAT")
    private MAT MAT = null;
    @JsonProperty("DAR")
    private DAR DAR = null;
    @JsonProperty("someString")
    private String someString = null;

    public MAT getMAT() {
        return MAT;
    }

    public void setMAT(MAT MAT) {
        this.MAT = MAT;
    }

    public DAR getDAR() {
        return DAR;
    }

    public void setDAR(DAR DAR) {
        this.DAR = DAR;
    }

    public String getSomeString() {
        return someString;
    }

    public void setSomeString(String someString) {
        this.someString = someString;
    }
}
```

**MAT** and **DAR** are two simple POJOs that includes a propery "String name". Each have getter and setters for the string.

When parsed, the following is output:

```
value =
{
  "mat": {
    "name": "MAT object"
  },
  "dar": {
    "name": "DAR object"
  },
  "MAT": {
    "name": "MAT object"
  },
  "DAR": {
    "name": "DAR object"
  },
  "requestedBFE": "101262"
}
```

As you can see, **MAT** and **DAR** are both present as they should, but there's also a **mat** and a **dar** that should *not* be present.

**Comment by cowtowncoder** [comment]
Could you please expand a bit on this -- I realize there is a repo, and I will look into it once I have time, but it could speed up process to have, say, POJO in question included here: this could indicate why name introspection considers there to be more properties than you think there should be.

**Comment by dentych** [comment]
Hey @cowtowncoder .

I have expanded the issue description with the POJO I'm parsing to JSON. It should be clear that there are too many items in the resulting JSON string from that.

**Comment by cowtowncoder** [comment]
@dentych thank you!

One quick suggestion: can you try enabling `MapperFeature.USE_STD_BEAN_NAMING`? It seems that you may be observing one small but important deviation that Jackson name mangling has, compared to JDK bean name handling: `getDAR()` will either yield `dar` (Jackson default) or `DAR` (JDK bean naming).
Deviation was not intentional but since it was the behavior before 2.5, it is still the default for backwards compatibility. But I think something to change for 3.0.

**Comment by dentych** [comment]
@cowtowncoder Using `MapperFeature.USE_STD_BEAN_NAMING` made it output the correct values and only once each.

**Comment by cowtowncoder** [comment]
@dentych Thank you for verifying. This is the recommended way to deal with this situation then -- for Jackson 3.0 we can and will change the defaults as well, to avoid having to configure mapper this way.
