### ISSUE TITLE
readValue(CharSequence)

### ISSUE THREAD

**Issue by mikaelstaldal** [FasterXML/jackson-databind#1714]
It would be useful if `ObjectMapper` and `ObjectReader` had overloaded `readValue` methods for `CharSequence`, and maybe also a range of a `CharSequence` (similar to what they have for `byte[]`).

**Comment by cowtowncoder** [comment]
I don't think I want to add yet more overloads for `ObjectMapper` (combinatory explosion), but I guess it could work for `ObjectReader`.
Now: these would just call `sequence.toString()` (creating new `JsonParser` implementation that takes `CharSequence` would be major task; or, alternatively `CharSequenceReader` which while doable probably wouldn't be worth the hassle). But maybe worth it, simple dispatching, saves some code?

**Comment by mikaelstaldal** [comment]
If the implementation would just to `CharSequence.toString()`, then it may not be worth it.
