### ISSUE TITLE
Jackson Mapper setTimeZone Not Working

### ISSUE THREAD

**Issue by gursahibexp** [FasterXML/jackson-databind#1717]
Jackson Version: 2.8.8 
Using Joda DateTime Object

When I don't send any timezone information. Jackson parses the Joda Date time and converts it to the JVM's timezone instead of UTC. But the setTimeZone comment says something else

` /**
     * Method for overriding default TimeZone to use for formatting.
     * Default value used is UTC (NOT default TimeZone of JVM).
     */
 public ObjectMapper setTimeZone(TimeZone tz){..}
    `

**Comment by cowtowncoder** [comment]
Since this is related to Joda datetime types, could you please re-file at:

https://github.com/FasterXML/jackson-datatype-joda/issues

as `jackson-databind` does not handle them (has no control over deserialization).
