### ISSUE TITLE
YAMLMapper deserialising empty strings and empty document ("---")

### ISSUE THREAD

**Issue by i11** [FasterXML/jackson-databind#1718]
Hi there,

I'm using `2.8.9` version  trying to deserialise an empty string and an empty document, and I am not sure if it's expected behaviour to get `JsonMappingException` for the first case and `null` object for the second.

Since `value` field is nullable I would expect to get an object with `null` `value` field back. Are there any options I need to enable/disable to change observed behaviour?

Thanks!

Consider the test bellow:
```
public class YamlDeserializationTest {

  private YAMLMapper yaml;

  @Before
  public void setUp() {
    yaml = new YAMLMapper(new YAMLFactory());
  }

  @Test
  public void testEmptyString() throws IOException {
    final Pojo pojo = yaml.readValue("", Pojo.class);
    System.out.println("Pojo: " + pojo);
  }

  @Test
  public void testEmptyDocument() throws IOException {
    final Pojo pojo = yaml.readValue("---", Pojo.class);
    System.out.println("Pojo: " + pojo);
  }

  public class Pojo {

    @Nullable
    private String value;

    @JsonCreator
    public Pojo(@Nullable String value) {
      this.value = value;
    }
  }
}
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this issue.

Since it relates to YAML functionality it belongs under:

https://github.com/FasterXML/jackson-dataformats-text/issues

Could you please re-create issue there? I would move it if github had such functionality, but as far as I know there isn't anything to do that.

**Comment by cowtowncoder** [comment]
Since this issue does not belong here, closing; may be recreated (if not already created) for `jackson-dataformats-text`, as per earlier note.
