### ISSUE TITLE
ObjectMapper.registerModules(Iterable<Module> modules) should be covariant

### ISSUE THREAD

**Issue by gregturn** [FasterXML/jackson-databind#1719]
**Version:** 2.9.0
**Description:**
Registering custom modules (say an extension of `SimpleModule`) via `ObjectMapper.registerModules(Iterable<Module>)` requires a cast like:

```
Collections.<Module>singletonList(new MyCustomModule())
```
...because the generic type signature is _invariant_.

If the signature was made covariant so that it read `ObjectMapper.registerModules(Iterable<? extends Module>)`, then it would accept any collection of modules that extends `Module`.

Since the code consuming this `Iterable` is merely a Java 5 for-each iterator, this change should have no effect on backward compatibility.

```
public ObjectMapper registerModules(Iterable<? extends Module> modules)
    {
        for (Module module : modules) {
            registerModule(module);
        }
        return this;
    }
```
This would allow removal of these ugly cast calls in client code while also dodging the need to load up a type safe `Collection` via some for-each loop or Java 8 stream, just to side step the cast.

**Comment by cowtowncoder** [comment]
True, this would probably be binary compatible, which is key requirement.
Thank you for suggestion.

In practice this will probably need to go in the next minor version just because 2.9.0 was just released 2 days ago.
