### ISSUE TITLE
Integer bounds verification when calling `TokenBuffer.getIntValue()`

### ISSUE THREAD

**Issue by newkek** [FasterXML/jackson-databind#1729]
Hello,

Using the `TokenBuffer` API I have noticed some unexpected behaviour wrt to 32 bit integers limits when deserializing a constructed `TokenBuffer`. It seems like when calling `getIntValue()` where the number value is bigger than the Java integer (32bit) limit might produce a wrong result instead of throwing an exception saying the number is too big. When not using a `TokenBuffer` parser, but when an implementation of `ParserBase` is used, I get some expected exceptions saying `Numeric value ... out of range of int`.

Here's a `TokenBuffer` example:

```java
TokenBuffer tb = new TokenBuffer(new ObjectMapper(), false);
tb.writeNumber("-4294967295");

JsonParser jp = tb.asParser();
jp.nextToken();

System.out.println("jp.getIntValue() = " + jp.getIntValue());
// returned value is 1
```
_(using a recent 2.9.1-SNAPSHOT build)_

However as you can [see here](https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/base/ParserBase.java#L646), `ParserBase.getIntValue()` tries to convert the int, which if not valid fails, and throws the expected exception of int overflow.

Thanks.

**Comment by cowtowncoder** [comment]
That does sound like a flaw: I think behavior should be identical. One can not rely on generator side of `TokenBuffer` to guard against it as it is possible to add a `long`  or `BigInteger` and try to read as `int`.

Thank you for reporting this.
