### ISSUE TITLE
TypeParamStash Fails To Detect Bindings of Inner Class

### ISSUE THREAD

**Issue by HeXetic** [FasterXML/jackson-databind#1732]
The inner TypeParamStash class of com.fasterxml.jackson.databind.type.TypeBindings, which attempts to discover the generic type parameters of a passed-in Class, does not work properly when dealing with an inner class that is wrapped inside a generic outer class.

The clearest example of this problem is when attempting to serialize the Java standard library inner class HashMap<K,V>$Values. Jackson fails to determine the actual type of the Values entries, because getTypeParameters() on the Values class returns an empty list -- the type parameters are actually in HashMap, the enclosing class.

Here's a simple example showing how getTypeParameters does not return what you might expect it to return:

```
import java.util.AbstractCollection;
import java.util.Iterator;

public class Outer<V>
{
    public class Inner extends AbstractCollection<V>
    {
        public int size() { return 0; }
        public Iterator<V> iterator() { return null; }
    }

    public Inner getInner() { return new Inner(); }

    public static void main (String[] args)
    {
        Outer<String> e = new Outer<>();
        System.out.println (e.getInner ().getClass ().getTypeParameters ().length);
        System.out.println (e.getInner ().getClass ().getEnclosingClass ().getTypeParameters ().length);
    }
}
```

The first call to getTypeParameters returns an empty list, because Inner itself has no type parameters. But the second call returns the single parameter for Outer, which is actually being used for the AbstractCollection.

**Comment by cowtowncoder** [comment]
I think I would need code that actually exhibits problems Jackson has, through `TypeFactory`.
Code above only uses reflection to show underlying JDK introspection, which is relevant, but does not reproduce problem.

**Comment by psivolob** [comment]
I have the same problem:
Try to execute the following code. 
```TypeFactory typeFactory = new ObjectMapper().getTypeFactory();
        CollectionType collectionType = typeFactory.constructCollectionType(Collection.class, Integer.class);

//trying to create a map with integers as values. However it returns Object as a content type
        Map<String, Integer> map = new HashMap<>();
        CollectionType newType = (CollectionType)typeFactory.constructSpecializedType(collectionType, map.values().getClass());
        System.out.println(newType.getContentType().getRawClass());

//now wrap Map.values() output with Collections.unmodifiableCollection() and it works!!!!????
        newType = (CollectionType)typeFactory.constructSpecializedType(collectionType, Collections.unmodifiableCollection(map.values()).getClass());
        System.out.println(newType.getContentType().getRawClass());
```

**Comment by cowtowncoder** [comment]
@psivolob I don't think your example is valid: `map.values().getClass()` does not seem like it would retain much type information due to type erasure. It'd be a `Collection`, but it may or may not contain any type parameterization -- it all depends on how that particular implementation class has been defined (if it is generic, no type information can be found; if it is bound there is).

I am not sure if it'd be the same problem as what @HeXetic has; it is hard to say from just descriptions.

**Comment by cowtowncoder** [comment]
Can not reproduce the issue at this point. May be re-opened with a unit test with assertions to show expected result, how it differs from actual.
