### ISSUE TITLE
JsonFormat date validation

### ISSUE THREAD

**Issue by raderio** [FasterXML/jackson-databind#1733]
```
@JsonFormat(pattern = "yyyy-MM-dd", shape = JsonFormat.Shape.STRING)
Date birthday;

```
If we send "2000-11-123" it must throw `JsonMappingException` exception, at the moment it parses to a date.

**Comment by cowtowncoder** [comment]
Which version of Jackson?

Also, assuming 2.9.0, there is no property `lenient`, disabling of which will make `SimpleDateFormat` more strict:

    @JsonFormat(..... lenient = OptBoolean.FALSE)

since it is `SimpleDateFormat` that handles actual configurable parsing.

**Comment by raderio** [comment]
Yes, 2.9.0, it works with lenient, thanks.
BTW, why this is not by default?

**Comment by cowtowncoder** [comment]
@raderio If I remember correctly, lenient parsing is the default setting for `SimpleDateFormat` and setting was chosen to try to avoid breakage with existing code. For Jackson 3.0 I think strict parsing would make more sense as the default however.
