### ISSUE TITLE
Change in behavior for ObjectWriter and setSerializationInclusion(JsonInclude.Include.NON_EMPTY) between 2.8.9 and 2.9.0

### ISSUE THREAD

**Issue by mattnworb** [FasterXML/jackson-databind#1736]
I've found a change in behavior in ObjectWriter when serializationInclusion is set to JsonInclude.Include.NON_EMPTY between version 2.8.9 and 2.9.0 that I wanted to check to see if it was intentional.

The application creates an ObjectMapper instance with the default serializationInclusion behavior, and an ObjectWriter based off of the ObjectMapper but with `setSerializationInclusion(JsonInclude.Include.NON_EMPTY)`. 

A particular function is given a complex POJO object and passes it through `objectWriter.writeValueAsString()`, and then deserializes that String back into a `Map<String, Object>` with `objectMapper.readValue(str, map type reference)`. Then the Map is passed through `objectWriter.writeValueAsString()`.

After upgrading from 2.8.9 to 2.9.0, I noticed that one of the fields in the complex POJO, which has a series of nested fields which serializes into an empty object (`{}`), is no longer included in the output of `objectWriter.writeValueAsString()`.

Below is a test case that reproduces this behavior: with 2.8.9, both test cases pass, but in 2.9.0 the `testStringToMapToString` test fails. 

I am just curious if this change is intentional? It sounds like it may be related to #1444.

```java

import static com.fasterxml.jackson.databind.MapperFeature.SORT_PROPERTIES_ALPHABETICALLY;
import static com.fasterxml.jackson.databind.SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import java.util.Map;
import org.junit.Test;

public class JsonTest {

  private final ObjectMapper objectMapper = new ObjectMapper()
      .configure(SORT_PROPERTIES_ALPHABETICALLY, true)
      .configure(ORDER_MAP_ENTRIES_BY_KEYS, true);

  private final ObjectWriter objectWriter = objectMapper
      .setSerializationInclusion(JsonInclude.Include.NON_EMPTY)
      .writer();

  private final TypeReference<Map<String, Object>> mapTypeReference =
      new TypeReference<Map<String, Object>>() {
      };

  private final String json = "{\"a\":\"b\",\"foo\":{\"bar\":{\"baz\":{\"bat\":{}}}}}";

  @Test
  public void testStringToMapToString() throws Exception {
    final Map<String, Object> map = objectMapper.readValue(json, mapTypeReference);
    assertTrue(map.containsKey("foo"));
    assertEquals(json, objectWriter.writeValueAsString(map));
  }

  @Test
  public void testStringToJsonNodeToString() throws Exception {
    final JsonNode jsonNode = objectMapper.readTree(json);
    assertTrue(jsonNode.has("foo"));
    assertEquals(json, objectWriter.writeValueAsString(jsonNode));
  }
}
```

**Comment by cowtowncoder** [comment]
Ok, looking at code and input in question, yes, this works as expected.

What happens here is two-fold:

1. With 2.9, distinction between two criteria for inclusion ("value" and "contents") is implemented, and `setSerializationInclusion()` assigns both as `NON_EMPTY`
2. When contents are checked for emptiness, recursively, even outermost `Map` value is considered empty and thereby excluded.

If you wanted to use settings that should behave same as 2.8, you can instead use method `setDefaultPropertyInclusion`, like so:

    mapper.setDefaultPropertyInclusion(JsonInclude.Value.construct(Include.NON_EMPTY,
            Include.ALWAYS);

which would only exclude `Map`s that are strictly empty, without considering whether contents therein might also be "empty".

In hindsight perhaps existing method `setSerializationInclusion` should instead have only set "value" part of inclusion, but not changed "contents". This would not have changed observed behavior. But I did not realize this at a time, and thought that new behavior is more likely what users would want.

**Comment by mattnworb** [comment]
Thank you very much for the detailed explanation! I think I understand this change better now. 

I would agree that the new behavior is more likely what users want in most cases. The application I am dealing with is making some strange assumptions about what NON_EMPTY would mean IMHO.

Thanks again @cowtowncoder !
