### ISSUE TITLE
Deserializing AutoValue properties that are @Memoized

### ISSUE THREAD

**Issue by cjlint** [FasterXML/jackson-databind#1738]
Jackson version: 2.9.0
AutoValue version: 1.4.1

I have an AutoValue class with a derived property which I want to appear in the serialization output, so I mark it as `@JsonProperty`. It is also potentially expensive so I mark it with AutoValue's `@Memoized` annotation. Serialization works fine, however I want to make sure that Jackson doesn't "set" the derived property when deserializing an object, because that wouldn't make much sense.

Jackson won't "set" the derived property if it is a primitive type, which is expected behavior. But strangely, it _will_ set the property if it is a boxed type.

Take the following classes for example:

```
@AutoValue
public abstract class PrimitiveValues {
    @JsonProperty
    public abstract int a();
    @JsonProperty
    @Memoized
    public int aPlusOne() {
        return a() + 1;
    }

    @JsonCreator
    public static PrimitiveValues create(@JsonProperty("a") int a) {
        return new AutoValue_PrimitiveValues(a);
    }
}
```
```
@AutoValue
public abstract class BoxedValues {
    @JsonProperty
    public abstract Integer a();
    @JsonProperty
    @Memoized
    public Integer aPlusOne() {
        return a() + 1;
    }

    @JsonCreator
    public static BoxedValues create(@JsonProperty("a") Integer a) {
        return new AutoValue_BoxedValues(a);
    }
}
```

And application code showcasing the bug: 
```
public class MainClass {
    public static void main(String[] args) throws Exception {
        final PrimitiveValues examplePrimitive = PrimitiveValues.create(1);
        final BoxedValues exampleBoxed = BoxedValues.create(1);
        final ObjectMapper mapper = new ObjectMapper();
        final String jsonWithBogusMemoizedValue = "{\"a\":1, \"aPlusOne\":42}";

        System.out.println(mapper.writeValueAsString(examplePrimitive)); // prints {"a":1,"aPlusOne":2} as expected
        System.out.println(mapper.writeValueAsString(exampleBoxed));     // prints {"a":1,"aPlusOne":2} as expected

        final PrimitiveValues deserializedPrimitive = mapper.readValue(jsonWithBogusMemoizedValue, PrimitiveValues.class);
        final BoxedValues deserializedBoxed = mapper.readValue(jsonWithBogusMemoizedValue, BoxedValues.class);
        System.out.println(deserializedPrimitive.aPlusOne());   // prints 2 as expected
        System.out.println(deserializedBoxed.aPlusOne());       // prints 42
    }
}
```

Removing the `@Memoized` annotation results in expected behavior across the board. Although another strange quirk is that if I remove the `@Memoized` annotation, I need to annotate the class with `@JsonIgnoreProperties(ignoreUnknown = true)` in order for deserialization to work, which in retrospect seems like it should be required with or without the `@Memoized` annotation.

I'm not sure if this is a Jackson bug or an AutoValue bug per se.

**Comment by cowtowncoder** [comment]
Unfortunately I do not know how AutoValue library works here -- my understanding is that it generates implementation classes (either straight to bytecode or source code generation) -- and do not know how this might occur from that end.
So I think I would suggest filing this for AutoValue (or asking on support forum).

Jackson does not know anything about `@Memoized`, unless some extension is written to pass it (via `AnnotationIntrospector` usually).

**Comment by cjlint** [comment]
Ah, I see that the AutoValue generated class is different in primitive vs. boxed:
```
@Generated("com.google.auto.value.extension.memoized.MemoizeExtension")
final class AutoValue_PrimitiveValues extends $AutoValue_PrimitiveValues {
  private volatile int aPlusOne;

  private volatile boolean aPlusOne$Memoized;

  AutoValue_PrimitiveValues(int a$) {
    super(a$);
  }

  @Override
  @JsonProperty
  public int aPlusOne() {
    if (!aPlusOne$Memoized) {
      synchronized (this) {
        if (!aPlusOne$Memoized) {
          aPlusOne = super.aPlusOne();
          aPlusOne$Memoized = true;
        }
      }
    }
    return aPlusOne;
  }
}
```
```
@Generated("com.google.auto.value.extension.memoized.MemoizeExtension")
final class AutoValue_BoxedValues extends $AutoValue_BoxedValues {
  private volatile Integer aPlusOne;

  AutoValue_BoxedValues(Integer a$) {
    super(a$);
  }

  @Override
  @JsonProperty
  public Integer aPlusOne() {
    if (aPlusOne == null) {
      synchronized (this) {
        if (aPlusOne == null) {
          aPlusOne = super.aPlusOne();
          if (aPlusOne == null) {
            throw new NullPointerException("aPlusOne() cannot return null");
          }
        }
      }
    }
    return aPlusOne;
  }
}
```

So Jackson is setting the generated `aPlusOne` value in both cases, but AutoValue also checks the `aPlusOne$Memoized` value in the primitive type example, which is why it recomputes the correct value in that case. I see now that this isn't really a bug and the only way to prevent this is to add `@JsonIgnoreProperties(value = {"aPlusOne"}, allowGetters = true)` to the class (and potentially also ignore the `aPlusOne$Memoized` field if your memoized property is primitive)

Gonna go ahead and close this.
