### ISSUE TITLE
@JsonIgnore @JsonProperty cannot be annotated on the same field

### ISSUE THREAD

**Issue by beihaifeiwu** [FasterXML/jackson-databind#1740]
like the code below:
```java
    @JsonIgnore
//    @JsonProperty("Door")
    private Doors doors;
```
if uncomment the @JsonProperty then it will behave like nothing is annotated, Is this the purpose ?

**Comment by athirupathisc** [comment]
@beihaifeiwu , you should ask questions on the groups

https://groups.google.com/forum/#!search/jackson-users

Please use the issues only to report legitimate issues or feature requests. Did you read the suggestions before opening the issue ?

**Comment by cowtowncoder** [comment]
I agree with @athirupathisc. I don't quite understand the question as is; but in general you really should not add both annotations -- semantics are not clear to anyone reading code (which one has precedence?).
