### ISSUE TITLE
KotlinReflectionInternalError while serializing Cloneable object

### ISSUE THREAD

**Issue by colinrtwhite** [FasterXML/jackson-databind#1741]
Hi, I get the following exception when trying to serialize a **Java** object which implements java.lang.Cloneable:

`kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unknown origin of protected open fun clone(): kotlin.Any defined in kotlin.Cloneable[SimpleFunctionDescriptorImpl@f7fb227] (class kotlin.reflect.jvm.internal.impl.descriptors.impl.SimpleFunctionDescriptorImpl)`

I'm using the Jackson Kotlin module, databind, core, and annotations - all at 2.9.0. The issue doesn't occur on 2.8.9. Since there weren't any changes in the Kotlin module 2.8.9 -> 2.9.0, I'm guessing this is a databind issue.

I'll see if I can make a project that reproduces the issue and upload it in a few mins.

**Comment by cowtowncoder** [comment]
This sounds like a Kotlin (module) problem, so should go in:

https://github.com/FasterXML/jackson-module-kotlin/issues

(I would move it but I don't think Github has a way to transfer issues unfortunately)

**Comment by colinrtwhite** [comment]
Sounds good - I've moved the issue to [here](https://github.com/FasterXML/jackson-module-kotlin/issues/88).
