### ISSUE TITLE
StdDateFormat: accept and truncate millis larger than 3 digits

### ISSUE THREAD

**Issue by brenuart** [FasterXML/jackson-databind#1745]
Java8 is likely to produce datetimes with nanosecond precision: the millis part may therefore be larger than 3 digits.

Unfortunately, Jackson's StdDateFormat fails to parse datetimes when the so-called millis have more than 3 digits - hence breaking interoperability between systems build upon these two technologies.

Although the standard `java.util.Date` supports only millis precision, JodaTime accepts datetimes serialized with nano-precision and truncate it to the first three digits. I think it would be nice if the StdDateFormat does the same...

**Comment by cowtowncoder** [comment]
I would be open to patch for this. Initially I was concerned about possible confusion between rounding and truncation; but if truncation is the usual default we should go with that.
And so it seems reasonable to allow some amount of leniency here for interoperability.

**Comment by brenuart** [comment]
Need a PR or do you handle it yourself ?

**Comment by cowtowncoder** [comment]
@brenuart I can handle it eventually but PR would speed things up (sometimes I fix things quickly, other times take longer hard to know). If you want to do PR that'd be great -- I think this is for `2.9` only. I can do quick review and merge.

**Comment by brenuart** [comment]
I know how hard it is to maintain such an OSS project ;-)
I'll try to find an hour or two in the next couple of days to submit a PR for this...

BTW, why do you say "this is for `2.9` only"? Do you have plans to get rid of `StdDateFormat` in `2.x`?

**Comment by cowtowncoder** [comment]
@brenuart What I meant is that 2.9 has rewritten version, so earlier branches would need separate patch (no objections to that, just bit more work -- and not sure how many releases of 2.8.x will be made).
No plans to eliminate `StdDateFormat` at this point, although 2.9 may well be last 2.x version (followed by 3.0).

**Comment by cowtowncoder** [comment]
Now allowing up to 9 digits -- can change, or even remove limit, but I think there's some benefit to sanity checking. But if there is some legit usage to, say, 12 or 15, let me know.
