### ISSUE TITLE
Validation in Jackson

### ISSUE THREAD

**Issue by raderio** [FasterXML/jackson-databind#1747]
Feature request

Since Jackson is validating if field is not null, if it match by regular expression, may be it can also validate other case, such as:
- NotBlank, string is not empty
- Size, number should be between interval
- Past, if date string is in past or now, useful for birthday validation
- etc

In this case we will have validation in one place, at the moment validation is done in 2 steps, Jackson validation, and other validation(example: javax validation).
This will improve how errors will be generated, all validation errors should be collected at once, in one level.

**Comment by TheNilesh** [comment]
This won't be a good idea as it will create a dependency with javax.validation. It violates the [limitation on dependencies](https://github.com/FasterXML/jackson-databind#limitation-on-dependencies-by-core-components).

**Comment by raderio** [comment]
I propose to make Jackson annotations, and not to use javax.validation

**Comment by cowtowncoder** [comment]
Validation is explicitly out of scope for core Jackson so nope. Java Bean Validation API exists, as do other libraries.

Adding hooks to help write extensions or modules is fine however.

**Comment by raderio** [comment]
But you already validate for null and for regexp by `@JsonFormat`

**Comment by cowtowncoder** [comment]
@raderio I agree that line between full validation and other checks can be ambiguous and vague.  And `null` may be incidentally prevented in some cases; type matching is checked for some types (for coercion of Strings to numbers for example). But `format` property of `@JsonFormat` is passed for deserializers to use for data conversion.
It is also true that with `2.9` it is possible to block use of `null`s via `@JsonSetter`s `nulls` / `contentNulls` properties.

Maybe I should clarify this more that I don't want to define and implement general-purpose validation system in core Jackson. But:

1. I am ok with some limited input verification for value types (like contents of Strings where applicable) for specific cases
2. I am ok with "existence" checks, too, if they can be supported for non-creator properties.
3. I would be fine with adding hooks for extension modules to handle validation, as well as hosting such implementation for FasterXML

Does this make more sense? I am not against validation, just don't want a new major functionality area implemented by core library.

**Comment by raderio** [comment]
@cowtowncoder thanks. I agree, hooks will be a compromise.
