### ISSUE TITLE
StdDateFormat: performance improvement of '_format(..)' method

### ISSUE THREAD

**Issue by brenuart** [FasterXML/jackson-databind#1749]
The `_format(..)` method creates a new `GregorianCalendar` instance for every invocation. Performance would be better if the calendar is reused across invocations just like what is done with the `DateFormats`.

Without this optimisation, the performance are roughly the same as the `SimpleDateFormat`. With the optimisation, the `StdDateFormat` becomes 300% faster...

**Comment by cowtowncoder** [comment]
Ok good to know, thank you for measuring it. It sort of makes sense as almost everything to do with date/time handling appears to be.... rather expensive. Need to figure out proper way to achieve that but hopefully is doable.

**Comment by brenuart** [comment]
Check the PR ;-)

**Comment by cowtowncoder** [comment]
Ah! Only catching up on updates :)
