### ISSUE TITLE
How to customize my item's name in List on serializing List<T> to xml

### ISSUE THREAD

**Issue by s-mop** [FasterXML/jackson-databind#1761]
here is the code in  com.fasterxml.jackson.dataformat.xml.ser.XmlSerializerProvider._startRootArray(ToXmlGenerator, QName)
by jackson-dataformat-xml-2.8.9

```
protected void _startRootArray(ToXmlGenerator xgen, QName rootName) throws IOException
    {
        xgen.writeStartObject();
        // Could repeat root name, but what's the point? How to customize?
        xgen.writeFieldName("item");
    } 
```

and this codes let my xml string look like this :
`<root><item><width>...`

how can i replcace the 'item' with other words?

**Comment by cowtowncoder** [comment]
Two problems here:

1. Issues related to XML handling should go in `jackson-dataformat-xml` issue tracker
2. Usage questions, however, should go to mailing list: https://groups.google.com/group/jackson-user/ -- issue trackers are for reporting issues and requesting new features.

Beyond this, you should NOT try writing root-level `List`, `Map` or array values: this is not supported usage: it does work to some degree, but often not the way you want, and some aspects (polymorphic items) do not work.
Root-level value should be POJO, even if just for wrapping List/Map/array.
