### ISSUE TITLE
jackson-databind 2.9.1 is using jackson-annotations 2.9.0

### ISSUE THREAD

**Issue by dejan2609** [FasterXML/jackson-databind#1763]
**_Prologue / related:_** #1545 (_Add explicit `jackson-annotations` dependency version for `jackson-databind`_)

**_Note (for the sake of clarity):_** git diff between jackson-annotations 2.9.0 and 2.9.1 tags seems inessential (however, that may not be the case for a future versions): https://github.com/FasterXML/jackson-annotations/compare/jackson-annotations-2.9.0...jackson-annotations-2.9.1

**_Steps to reproduce:_** 
> **_git clone ```https://github.com/FasterXML/jackson-databind.git```_**
> **_cd jackson-databind_**
> **_git checkout jackson-databind-2.9.1_**
> **_mvn dependency:tree  -Dincludes=com.fasterxml.jackson.core_**
> ```
> [INFO]
> [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jackson-databind ---
> [INFO] com.fasterxml.jackson.core:jackson-databind:bundle:2.9.1
> [INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
> [INFO] \- com.fasterxml.jackson.core:jackson-core:jar:2.9.1:compile
> [INFO] ------------------------------------------------------------------------
> ```
> (or for much more detailed report: _**mvn help:effective-pom -Doutput=Effective-POM.txt**_)

**Comment by cowtowncoder** [comment]
I have explained multiple times my reasoning of why .0 annotations are used. This is not a flaw.
With 3.0, I will change it so we will only release 3.0, 3.1 and so on (unless there are bugs to fix).
But until then, best thing is to ignore other patches, except for users who insists on using same version.
