### ISSUE TITLE
@JacksonInject results in "no _valuedeserializer assigned" error

### ISSUE THREAD

**Issue by tomaszchabinka** [FasterXML/jackson-databind#1769]
In my code I have class A, that contains as a field `List<InterfaceB> list`; I deserialize A from Json stored in ElasticSearch; with default constructor (`public A ();`) everything works fine, but when I try to use constructor with @JacksonInject (`public A(@JacksonInject C c);`) error "no _valuedeserializer assigned" with "through reference chain A["list"] information is shown.

**Comment by cowtowncoder** [comment]
A reproduction needed, along with version number.

**Comment by tomaszchabinka** [comment]
Actually looks like I wrongly described this bug - `@JsonManagedReference`, not inheritance is responsible for problem: 

Reproduction: https://gist.github.com/tomaszchabinka/0e7780b3d3b93d3a93b668e93ac94194
Version number: 2.8.9

Looks like it's solved in 2.9.1 (hadn't have a possibility to check this), sorry for problem.

**Comment by cowtowncoder** [comment]
Ah. Yes, I do recall issues with `@JsonManagedReference` in the past. Thank you follow up.
