### ISSUE TITLE
JacksonAnnotationIntrospector methods should return Object instead of Class

### ISSUE THREAD

**Issue by miguelocarvajal** [FasterXML/jackson-databind#177]
Currently the findSerializer method returns an Object that allows a serializer to be instantiated with a custom constructor. However, findDeserializer returns a Class instead. I think both of these should return an Object so a deserializer can be instantiated as needed.

**Comment by smaant** [comment]
Hi @cowtowncoder , it seems weird but findDeserializer still returns `Class<? extends JsonDeserializer<?>>` ([sources] (https://github.com/FasterXML/jackson-databind/blob/7785dff4647ac4e9e6675ca118ae97106225d23d/src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java#L659)).
Is it intentionally or a bug? I have the same reason as @miguelocarvajal to have Object there.
