### ISSUE TITLE
Greeting and something about contributing code for Performance Enhancement in com.fasterxml.jackson.databind

### ISSUE THREAD

**Issue by xinzhg** [FasterXML/jackson-databind#1776]
Hi guys,

During the usage of Jackson-core library. I found the com.fasterxml.jackson.databind.TextNode,toString() is our hot path method. It was called hundreds of thousands of times. Then, I improve the performance of it, which saves more space in dram. I think it will help other people who are using the Jackson-databind library. So, I was wondering how can I contribute my code to Jackson-databind.

Thanks,
Xin

**Comment by cowtowncoder** [comment]
Thank you for contributing this! After looking at suggestions, I will unfortunately have to decline -- code path in question should not be used for performance critical usage (in fact, it should never be used for JSON serialization, only for diagnostics), and as such simplicity is more valuable than optimization by unrolling.
