### ISSUE TITLE
Corrupted maven-metadata.xml on maven central for Jackson 1.x (`jackson-mapper-asl`) breaks version range resolution

### ISSUE THREAD

**Issue by christianbalzer** [FasterXML/jackson-databind#1779]
The maven-metadata.xml file on maven central for jackson-mapper-asl is broken, causing maven's version range resolution to fail for the artifact. (jaclson-databind apparently replaces it, hence me raising the bug here.) I realise that the artifact identifiers have been changed, but could you please push a corrected version of maven-metadata for the old identifiers to maven central?

For information how to publicise a change of artifact identifiers, if needed, see here: http://maven.apache.org/ref/3.5.0/maven-model/maven.html#class_relocation

This issue is related to https://github.com/FasterXML/jackson-core/issues/407

**Comment by cowtowncoder** [comment]
Since this is for Jackson 1.x, issue should go under:

https://github.com/FasterXML/jackson-1

Main challenge wrt trying to push a new version (1.9.14) is that 1.x did not use Maven for build but Ant with maven task. And whether that still works with Nexus is unknown.
