### ISSUE TITLE
Exception while converting object to byte array:Out of memory Error

### ISSUE THREAD

**Issue by AshwathIyer** [FasterXML/jackson-databind#1782]
when i try to convert big Java object to a byte array , i get the below exception

Caused by: java.lang.OutOfMemoryError: Java heap space 
	at com.fasterxml.jackson.core.util.ByteArrayBuilder.toByteArray(ByteArrayBuilder.java:123)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3103)

**Comment by marvin-we** [comment]
I am not a jackson developer, but I think it will be hard for them if you only provide that few information.

In general you should be able to solve this issue by increasing the memory your application is allowed to use by settings "-XmxYOURVALUE" - e.g. -Xmx6g to allow you application to consume up to 6 gb of RAM.

**Comment by cowtowncoder** [comment]
Right: OOME is a result of trying to use more memory than is available, and choices include allocating more memory or possible serializing value into `OutputStream` (or `File`) and NOT trying to fit it all in memory. There is no magic here; if result should be held in a byte array there must be enough for that array as well as intermediate work space. Latter part will be at least as big as the eventual result, so to output json of, say, 100 megabytes, there will need to be at least bit over 200 megabytes of free heap space in addition to the original source object.
