### ISSUE TITLE
NoClassDefFoundError/ExceptionInInitializerError on Android 2.3.3 and Jackson 2.9.0

### ISSUE THREAD

**Issue by johnjohndoe** [FasterXML/jackson-databind#1802]
I discovered a `NoClassDefFoundError`/`ExceptionInInitializerError` when I run [this Android app](https://github.com/johnjohndoe/Umweltzone) in the following environment:

- Samsung GT-I9000
- Android 2.3.3 (API level 8, Froyo)
- no Google Play Services installed
- `com.fasterxml.jackson.core:jackson-databind:2.9.0 - 2.9.2`
- crash happens for `DEBUG` and `RELEASE` builds

Here is the excerpt which causes the crash. The full source code can be found [here](https://github.com/johnjohndoe/Umweltzone/blob/4da721846ad4c9bca030fc1167aff3d8754abb72/Umweltzone/src/main/java/de/avpptr/umweltzone/utils/ContentProvider.java#L111-L114) (commit: `4da721846ad4c9bca030fc1167aff3d8754abb72`).

``` java
111 SimpleModule module = new SimpleModule();
112 module.addDeserializer(Circuit.class, new CircuitDeserializer());
113 ObjectMapper objectMapper = new ObjectMapper(); // <-- crash
114 objectMapper.registerModule(module);
```

The following stacktrace is generated when I open the `FaqActivity` from the toolbar menu:

``` java
java.lang.ExceptionInInitializerError
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:577)
    at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480)
    at de.avpptr.umweltzone.utils.ContentProvider.getContent(ContentProvider.java:113)
    at de.avpptr.umweltzone.utils.ContentProvider.getContent(ContentProvider.java:98)
    at de.avpptr.umweltzone.utils.ContentProvider.getFaqs(ContentProvider.java:68)
    at de.avpptr.umweltzone.faqs.FaqActivity.onCreate(FaqActivity.java:40)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)
    ...
Caused by: java.lang.ExceptionInInitializerError
    at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.<clinit>(BasicDeserializerFactory.java:49)
    ... 19 more
Caused by: java.lang.NoClassDefFoundError: com.fasterxml.jackson.databind.util.ClassUtil
    at com.fasterxml.jackson.databind.PropertyName.<init>(PropertyName.java:66)
    at com.fasterxml.jackson.databind.PropertyName.<clinit>(PropertyName.java:29)
    ... 20 more
```

# Findings
- The crash can be reproduced with the `system-images;android-10;google_apis;x86` emulator image (Android 2.3.3, Google APIs)
- The crash does **not** occur when I use` jackson-databind:2.8.10`.
- The crash does **not** happen on another device: Nexus 5, Android 6.0.1, Google Play Services installed.
- The crash does **not** occur on Android 4.1, API level 16 (tested with `system-images;android-16;google_apis;x86` emulator).

# Related issues
- [#216 - ExceptionInInitializerError for Android API level 8](https://github.com/FasterXML/jackson-databind/issues/216)

**Comment by cowtowncoder** [comment]
And just to make sure: class `ClassUtil` does exist in jar used (and package built, used)?
I guess such exception is often result of a failure in static initializer so perhaps that doesn't tell much yet.

**Comment by johnjohndoe** [comment]
> And just to make sure: class ClassUtil does exist in jar used (and package built, used)?

Do you mean in `jackson-databind-2.9.0.jar`? Yes, if I unpack the .jar I find `ClassUtil.class` in `com/fasterxml/jackson/databind/util`. Same for v.2.9.1 and v.2.9.2.

**Comment by cowtowncoder** [comment]
@joelittlejohn Looking at:

https://developer.android.com/about/dashboards/index.html

I think that the root cause is that this old Android version does not include method `emptyIterator` from `java.util.Collections`, which was added in JDK 1.7.
This is actually sort of dup of #1134 (assuming root cause is indeed the same), but since 2.9 requires JDK 7 baseline, it is not a bug but limitation wrt Android SDK with which Jackson 2.9 may be used.

Looking at:

https://developer.android.com/reference/java/util/Collections.html#emptyIterator()

limit appears to be "API level 19".

**Comment by joelittlejohn** [comment]
@johnjohndoe :point_up:

**Comment by johnjohndoe** [comment]
Thank you for the explanation. Are you going to backport this? If v.2.9.x will no longer support these JDK / Android versions this notice should get a prominent place in the docs.

**Comment by cowtowncoder** [comment]
Well this has been mentioned, announced and included as a warning for 2.8 release:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8

so it's not news per se. Unfortunately however feedback loop between Jackson project and Android developers (I don't think anyone on core team develops on Android unfortunately) has been... well, high-latency one. You have been very helpful and I appreciate that.

But yes, it should be prominently included in 3.0 notes. Ideally based on solid information and tests done by someone who develops on Android.

As to backporting: if someone wants to work on this and verify necessary changes, I will work with that person and merge PR(s) as necessary. I just do not have either time or experience to do it on my own, to properly verify fixes (much less automate it).

**Comment by johnjohndoe** [comment]
Thank you again for pointing me to the release notes.

I am not sure if backporting is very much worth the effort since Android apps tend to raise their minimum SDK level more and more. Google themselves dictates this because they [raise version](https://developers.google.com/android/guides/releases#february_2017_-_version_102) in widely used libraries such as _Google Play Services_ library. The other question which has to be answered by each app individually is how many users are actually still using devices with older Android versions.

Once thing I would be interested in is if you are planning to release 2.8.x versions if **security issues** or **major bugs** are discovered which apply to this minor version?

**Comment by cowtowncoder** [comment]
@johnjohndoe Yes, there's diminishing return on back-porting, and Google does tend to push for newer versions (since older versions are costly to support for them too).

And yes, security issues are a class of problems for which new versions are theoretically possible for even otherwise closed branches. 2.8 is not yet officially closed, however, and I suspect I will be doing full 2.8.11 release at some point. Beyond this, micro-patches are a possibility.
As to major bugs, perhaps, depends on type of bug in question. I don't think I have done that yet for a closed minor branch (unlike security patch or two), but I would not rule that out.
