### ISSUE TITLE
enableDefaultTyping behave differently in deserialization with only concrete classes

### ISSUE THREAD

**Issue by Rapster** [FasterXML/jackson-databind#1808]
Jackson version: 2.8.10

Basically, I have this deserialization:
```java
TransferPhysicalPublishInfo info = mapper.readValue(getClass().getResourceAsStream("/feeds/TransferPhysicalTransferInfo.json"),
                TransferPhysicalPublishInfo.class);
```

TransferPhysicalPublicInfo look like this:
```java
public final class TransferPhysicalPublishInfo {

    private TransferPublishHeader header;
    private List<TransferPublishLine> lines;
    private List<TransferPublishLine> electronicLines;
   
    // ...
}
```

The rest is very simple pojo. It works pretty well if I don't specify particular feature. But, when it comes to [enable default typing](https://fasterxml.github.io/jackson-databind/javadoc/2.2.0/com/fasterxml/jackson/databind/ObjectMapper.html#enableDefaultTyping())

I have this error:
```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_ARRAY), expected VALUE_STRING: need JSON String that contains type id (for subtype of java.util.List)
 at [Source: java.io.BufferedInputStream@1dde5b0a; line: 159, column: 15] (through reference chain: spark.editions.services.info.TransferPhysicalPublishInfo["lines"])
```
lines is defined as `"lines": []` in JSON file

IMO, enabling default typing should not alter default deserialization (when it's not needed of course, in this case, i don't use any inheritance but at some point, classes name will need to be written in json)

**Comment by cowtowncoder** [comment]
I am not sure what you mean "default deserialization" here: rules of default typing are followed as specified. Without argument default typing uses rule `DefaultTyping.OBJECT_AND_NON_CONCRETE` which -- as name implies -- applies to `java.lang.Object` and all non-concrete (abstract classes, interface) types. `List` is such type.
All determination is and must be done based just on static information (class declarations), and code does not know whether something may or may not be necessary based on data, or class hierarchies (JVM does not know if there might be subtypes or not).

So if this rule is not what you want, you may want to:

* Choose different collection type (`ArrayList`, for example, is concrete)
* Choose different rule, or, if none is good enough, specify your own ("setDefaultTyping", need to implement `TypeResolverBuilder<?>`)
* Override polymorphic definition that applies with `@JsonTypeInfo`

**Comment by AJ-89** [comment]
@Rapster How did you resolve this?

**Comment by cowtowncoder** [comment]
Would need a reproduction for the actual problem (and not description with bits of code); may be re-opened with one (that fails against 2.12).
