### ISSUE TITLE
FEATURE : ObjectMapper readtree to support ignore fields/nodes

### ISSUE THREAD

**Issue by ykshinde** [FasterXML/jackson-databind#1821]
With ODATA 2 and jackson-databind 2.4
Challenge:
We do read the dynamic Json to the JsonNode, this works fine. SAP Gateway ODATA 2 implementation do not support metadeta ignore flag, and due to Metadata information, ObjectNode instance consumes lots of memory.

FEATURE : Add ignoreTag support for the JsonNode. It can be either implemented in JsonNodeDeserializer OR can introduce new JsonParser (Currently we have workaround with custom JsonParser).

**Comment by cowtowncoder** [comment]
Tree representation is meant to represent "native" JSON, without extra processing, so it is purposefully handled without additional processing.
General purpose filtering is possible already with `FilteringParserDelegate` and matching `TokenFilter` (one implementation being `JsonPointerBasedFilter`), although it is not necessarily trivial to use.
Given this, I don't have personal interest in working on extending functionality in this direction.

But I will leave this open in case someone has good ideas of API and is willing to implement soemthing.

**Comment by leojh** [comment]
for an example of how to do what @cowtowncoder https://stackoverflow.com/questions/53131427/jsonnode-comparison-excluding-fields

**Comment by cowtowncoder** [comment]
Thank you for sharing this @leojh!
