### ISSUE TITLE
`ObjectReader.readValue(JsonNode)` does not work correctly with polymorphic types, value to update

### ISSUE THREAD

**Issue by basmastr** [FasterXML/jackson-databind#1831]
There seems to be a difference in behavior of `ObjectReader::readValue(JsonNode)` and `ObjectReader::readValue(String)`. In particular I've found a difference in how they treat the combination of `@JsonUnwrapped` and `@JsonSubTypes` and a custom deserializer. I am attaching two minimal test cases. They are identical but one uses `ObjectReader::readValue(JsonNode)` (and fails) and the other one uses `ObjectReader::readValue(String)` and passes.
Tested on version 2.9.2.

[unwrappedSubtypesBug.zip](https://github.com/FasterXML/jackson-databind/files/1483046/unwrappedSubtypesBug.zip)

**Comment by cowtowncoder** [comment]
I hope to have time to look into this. One thing to keep in mind is that Tree Model is meant to be exact representation of the content, without transformations, and is explicitly different than POJOs.
So more like "untyped" structure of `List`s and `Map`s, for which unwrapping is not applied (unwrapping requires existence of properties, concept that is POJO-specific, not applicable to Maps or `ObjcetNode`s).
Similarly polymorphic handling isn't really applicable either, with minor exceptions (like POJO property declared as `Object` should be able to handle `JsonNode` values if polymorphic handling is enabled).

**Comment by cowtowncoder** [comment]
Ok. This is interesting... usage seems correct. And using `jsonNode.traverse(mapper)` instead of `jsonNode` works. So something does seem wrong here.

**Comment by cowtowncoder** [comment]
Ok. So the problem is not so much use of `String` or `JsonNode` in itself, but rather how `JsonNode` is traversed: it is passed `ObjectCodec`, which in this case is `ObjectReader`.
That is fine in itself but reader is configured with object to update, which causes problems.
I'll need to see if there is a way to easily clear "object to update" for this particular use.

**Comment by cowtowncoder** [comment]
Fixed for `2.9.3` (and was actually already working for `master, 3.0.0-SNAPSHOT).
