### ISSUE TITLE
JavaFX Observable collections support

### ISSUE THREAD

**Issue by omega09** [FasterXML/jackson-databind#1833]
Similar to #536.

JavaFX uses observable collections such as [ObservableList](https://docs.oracle.com/javase/9/docs/api/javafx/collections/ObservableList.html),[ObservableSet](https://docs.oracle.com/javase/9/docs/api/javafx/collections/ObservableSet.html) and [ObservableMap](https://docs.oracle.com/javase/9/docs/api/javafx/collections/ObservableMap.html). The instantiation of these types is via static factory methods [FXCollections#observableArrayList](https://docs.oracle.com/javase/9/docs/api/javafx/collections/FXCollections.html#observableArrayList--) and the like. Since there is no empty constructor, deserialization of a property defined as

    ObservableList<Object> list = FXCollections.observableArrayList();

will fail. Since JavaFX is part of the JDK I believe it is adequate to provide internal support for these datatypes; and since developers cannot annotate these classes, to my understanding the only solution is to configure the deserializing mapper object somehow.

Can support be added (if help is needed with the JavaFX side I'm here) and what is the preferred workaround at the moment?

Tested on 2.9.0.

**Comment by cowtowncoder** [comment]
When was JavaFX added? How many classes are involved? Do you have a link to tutorial (I have never used these classes).

Typically larger new sets of JDK-added functionality have been (and will be added) in datatype module. In case of Jackson 2.x, only Java 7 types may be supported directly by databind; there are 3 modules for various Java 8 aspects (parameter name supports; Java 8 date/time; other Java 8 types like `Optional`).

**Comment by omega09** [comment]
> When was JavaFX added?

In java 8.

> How many classes are involved?

These interfaces:
[ObservableList](https://docs.oracle.com/javase/9/docs/api/javafx/collections/ObservableList.html), [ObservableSet](https://docs.oracle.com/javase/9/docs/api/javafx/collections/ObservableSet.html), [ObservableMap](https://docs.oracle.com/javase/9/docs/api/javafx/collections/ObservableMap.html), [ObservableFloatArray](https://docs.oracle.com/javase/9/docs/api/javafx/collections/ObservableFloatArray.html), [ObservableIntegerArray](https://docs.oracle.com/javase/9/docs/api/javafx/collections/ObservableIntegerArray.html), and possibly the last two's superinteface [ObservableArray](https://docs.oracle.com/javase/9/docs/api/javafx/collections/ObservableArray.html). The utility class [FXCollections](https://docs.oracle.com/javase/9/docs/api/javafx/collections/FXCollections.html) contains all the static instantiation methods `FXCollections.observableXxx()`.

> Do you have a link to tutorial

This is the part about [JavaFX collections](https://docs.oracle.com/javase/8/javafx/collections-tutorial/collections.htm).

What's the verdict?

**Comment by cowtowncoder** [comment]
If someone wants to tackle this as either part of:

    https://github.com/FasterXML/jackson-modules-java8/

and specifically

    https://github.com/FasterXML/jackson-modules-java8/tree/master/datatypes

I can help. I do not have personal interest or time to work on this any time soon, but many of extensions have been contributions (like the whole awesome Java 8 date/time module).
So perhaps this issue can help anyone looking for extra work to do to find it.

**Comment by omega09** [comment]
I don't mind having a look at it this weekend. What does it involve? Is there similar code I can look at?

**Comment by cowtowncoder** [comment]
Since these seem to be collection types, perhaps looking at `jackson-datatypes-collections` might make sense: one of implementations there (hppc, guava, pcollections). These are bit trickier to implement than scalar (simple, POJO) types.
Java 8 datatype and date-time modules may not be as useful since latter has lots of domain-specific (date/time handling) stuff, and former mostly deals with `Optional` type (referential type).

What is needed is typically just a module that registers a set of `JsonDeserializer` and `JsonSerializer` implementations, and then those serializers, deserializers.
