### ISSUE TITLE
Json conversion error - invalid Json is converted without JsonParseException

### ISSUE THREAD

**Issue by ukr15** [FasterXML/jackson-databind#1845]
If a JsonString is invalid but contains a valid substring, no JsonParseException is issued.

`String invalidJson =  "{\n    \"foo\": {\n    \"baz\" : \"bazValue\",\n    \"bar\" : \"barValue\"}\n    },\n     \"bla\" : [ \"a\" , \"b\", \"c\"],\n     \"xxx\" : 0.3\n}";
Map map = new ObjectMapper().readValue(invalidJson,Map.class);`

results in a valid Map {foo={baz=bazValue, bar=barValue}}
There is a simple reproducer attached
[JacksonTest.zip](https://github.com/FasterXML/jackson-databind/files/1513849/JacksonTest.zip)

**Comment by cowtowncoder** [comment]
This is actually not a bug but feature. Jackson by default only reads as much content as is needed to bind to target you request. This is necessary mostly to allow root-level value sequences, although in those cases values are separated by optional white space, not commas.

But with 2.9 you can set `DeserializationFeature.FAIL_ON_TRAILING_TOKENS` to make mapper verify that all tokens are consumed: that is, read the whole stream. This should catch this particular problem. So you probably want to enable this feature.

**Comment by simplylizz** [comment]
Sorry, but IMHO this is a terrible feature. Should parsing be really so fault-tolerance by default? It could cause very confusing bugs.

Is there is a way to *fix* this feature for 2.8.6?

**Comment by cowtowncoder** [comment]
No backporting for new features is allowed by versioning.
If you want to catch the problem you are free to construct parser, call bind methods with parser, then advance with `nextToken()`, verify you get `null` without parse exception.
