### ISSUE TITLE
Missing support for multiple yaml documents in a single file.

### ISSUE THREAD

**Issue by hemanik** [FasterXML/jackson-databind#1848]
yaml spec v1.2 contained information about files with multiple documents:
http://www.yaml.org/spec/1.2/spec.html

> YAML uses three dashes (“---”) to separate directives from document content. This also serves to signal the start of a document if no directives are present. Three dots ( “...”) indicate the end of a document without starting a new one, for use in communication channels.

Example:
```
# Ranking of 1998 home runs
---
- Mark McGwire
- Sammy Sosa
- Ken Griffey

# Team ranking
---
- Chicago Cubs
- St Louis Cardinals
```
Example with ` ...`:
```
---
time: 20:03:20
player: Sammy Sosa
action: strike (miss)
...
---
time: 20:03:47
player: Sammy Sosa
action: grand slam
...
```
The above mentioned structures are not supported by object mapper at the moment.

**Comment by cowtowncoder** [comment]
Please file YAML specific issues under `jackson-dataformats-text`: this module only handlers format-independent functionality. Handling of multiple logical documents is supported, at high level, by `ObjectMapper` (or more specifically, by `MappingIterator` created via `ObjectReader`).
But it is possible `YAMLParser` might not handle multi-document input, even if `SnakeYAML` (which is used as decoder) may support it.

**Comment by cowtowncoder** [comment]
Refiled at: https://github.com/FasterXML/jackson-dataformats-text/issues/66
