### ISSUE TITLE
Custom StdSerializer used for more types than registered

### ISSUE THREAD

**Issue by Johanneke** [FasterXML/jackson-databind#1849]
We have an issue with a custom StdSerializer that is used for more types than it is registered for. This was tested on 2.8.9.

The error we get is:
`com.fasterxml.jackson.databind.JsonMappingException: java.lang.String cannot be cast to com.example.Translation (through reference chain: com.example.MyObject["keywords"])`
It looks like the `Map<String, Translation>` serializer is also used for a `Map<String, String>`. Our setup is described below:

Object to map:

```java
public class MyObject {
  private Map<String, String> keywords = new HashMap<>();
  private Map<String, Translation> translations = new HashMap<>();
  ...
}
```

Custom serializer:

```java
public class TranslationsSerializer extends StdSerializer<Map<String, Translation>> {
  protected TranslationsSerializer(JavaType type) {
    super(type);
  }
  @Override
  public void serialize(Map<String, Translation> translations, JsonGenerator jgen, SerializerProvider provider) throws IOException {
  ...
  }
}
```

ContextResolver:

```java
@Provider
public class JacksonObjectMapperProvider implements ContextResolver<ObjectMapper> {
  private final ObjectMapper mapper;
  public JacksonObjectMapperProvider() {
    mapper = new ObjectMapper();
    MapType translationsType = mapper.getTypeFactory().constructMapType(Map.class, String.class, Translation.class);
    SimpleModule translationsModule = new SimpleModule();
    translationsModule.addSerializer(new TranslationsSerializer(translationsType));
    mapper.registerModule(translationsModule);
  }
  @Override
  public ObjectMapper getContext(Class<?> type) {
    return mapper;
  }
}
```

**Comment by Johanneke** [comment]
I'm guessing it might have something to do with https://github.com/FasterXML/jackson-databind/issues/1807

**Comment by cowtowncoder** [comment]
I hope to find time to verify -- fix for #1807 is only in `2.8` branch for `2.8.11` so it would exhibit there.

**Comment by cowtowncoder** [comment]
Actually, no, it is because you are using `SimpleModule`, which only uses "type erased" type (`Class`) for matching (via `SimpleSerializers` handlers).
This means that it will indeed be used for all `Map<?>` types.
This should be documented better; I'll add a note in Javadocs for `SimpleModule`.

To register (de)serializer(s) for generic types you will need to implement `Module` directly (or override `setupModule()` of `SimpleModule`), and register serializers using custom version of `Serializers` that only returns your serializer for specific `Map` signature.

**Comment by Johanneke** [comment]
Ah, didn't know that. Do you know if there is an example of such a setup somewhere? I can only find SimpleModule examples on google...

**Comment by cowtowncoder** [comment]
No problem.
