### ISSUE TITLE
Jackson-Databind newest release - Does it update struts to version 2.5.14.1?

### ISSUE THREAD

**Issue by strutyourstuff** [FasterXML/jackson-databind#1856]
Is there any documentation on the newest release of the newest Jackson-Databind also updating Struts (by The Apache Software Foundation)? 
You know, because that one time earlier in 2017 where Equifax reported they had that breach and blamed not updating struts and all that.

**Comment by cowtowncoder** [comment]
Jackson does not use Struts for anything; there are no dependencies whatever.
