### ISSUE TITLE
Performance Impact of using static Object Reader and Object Writer [Multi Threaded] 

### ISSUE THREAD

**Issue by souravabhijith** [FasterXML/jackson-databind#1858]
Our application involves heavy conversions from InputStream to ObjectNode and ObjectNode to JsonString.

We are using these 3 objects across application . (The same objects, as per the guidelines your wiki provided ,re-use as much as possible).

`

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    private static final ObjectReader OBJECT_READER = OBJECT_MAPPER.readerFor(ObjectNode.class);

    private static final ObjectWriter OBJECT_WRITER = OBJECT_MAPPER.writerFor(ObjectNode.class).with(JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN);
`

Actually ObjectMapper is only used to create ObjectReader and ObjectWriter, and ObjectReader is used to convert strings/inputstream into a ObjectNode. and ObjectWriter is used to write to Outputstream or get jsonString.

From our load runs it looks like ObjectReader is taking around 0.2ms to create a ObjectNode from 60KB String for a single-threaded run but its taking around 3-5 ms sometimes if we use around 20 threads concurently trying to create ObjectNodes. 

My question here is 
-> I know ObjectReader and ObjectWriter are thread safe. Will that cause any efficiency issues in our scenario where high load is expected. 
-> Does creation of ObjectReader and ObjectWriter everytime for every call give any perf benefit ?

-> Does creation of ObjectMapper itself for every call give any perf benefit, or the cost of creating the objectMapper will shadow the benefit it might give.

Are there any other things I can do to make jackson faster under load. (To convert to json and back to string)

**Comment by cowtowncoder** [comment]
Go to https://groups.google.com/forum/#!forum/jackson-user
