### ISSUE TITLE
Issue handling unknown/unmapped Enum keys

### ISSUE THREAD

**Issue by remya11** [FasterXML/jackson-databind#1859]
Hi,

Trying to deserialize a JSON string using jackson-databind Objectmapper which has a set of Enum attributes within it, but ends up in InvalidFormatException. 

This happens when an unknown attribute, which is not defined in the enum comes in the JSON. 

```java
    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE);
    objectMapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
    objectMapper.setSerializationInclusion(Include.NON_NULL);
   objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

But, deserialization (objectMapper.readValue(jsonText, .class);) throws an  error. "Test" is the unknown attribute that comes in the JSON String to be deserialized.

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type com..* from String "Test": not a valid representation, problem:(com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type com.... from String "Test": not one of values excepted for Enum class: [ ]
```

Sample of JSON String would look like this.

```java
String jsonText="{\"cartId\":\"31028\",\"userId\":\"106784\",\"attributes\":{\"count\":\"1\",\"amount\":\"10\",\"email\":\"N\",\"Test\":\"No\",\"phone\":\"N\"}}";
```

The JSON maps to a Cart class, which holds these attributes as a Map. 

```java
public class Cart {
  private String cartId;
  private String userId;
  private Map<Attributes,String> attributes;
}
```

Attributes map to the Enum, as given below.

```java
public enum Attributes {
  Count(0),
  Amount(1),
  Email(2),
  Phone(3);

  private final int value;
  private Attributes(int value) {
    this.value = value;
  }
  public int getValue() {
    return value;
  }
}
```

Also tried adding this configuration 

    objectMapper.configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL, true);

This resulted in the Unknown attribute key to be deserialized as null. (i.e., instead of Test=No, it gets deserialized as null=No). So, when a new attribute - say, 'Test' comes in the Json, it would be good if the mapper can ignore that field and proceed with de-serializing the remaining fields that has a match in the Enum, rather than throwing the exception.

**Comment by remya11** [comment]
Hi, 

Could you please let me know when this fix could be available?

Regards,
Remya

**Comment by cowtowncoder** [comment]
@remya11 if and when someone has time and interest to work on this.

**Comment by cowtowncoder** [comment]
Ok working on this. One quick note: if you declare map as `EnumMap`, things actually work the way you'd like when `DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL` is enabled.
When type is basic `Map` the problem is that `null` is valid key value.

Handling of "as default" is not working so I will try to fix that, but I will not change the way key handling works for simple `Map`.

Note that you could also consider custom `Map` sub-class that would simply change `put` method to ignore attempts to add entries with `null` as key.

**Comment by cowtowncoder** [comment]
So: handling `READ_UNKNOWN_ENUM_VALUES_AS_NULL` not changed as it was working as specified (but handling subtly different for `EnumMap`). Fixed handling so that EnumKeyDeserializer honors `READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE` as well.

**Comment by isuribb** [comment]
Tried using the "READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE "  with the JsonEnumDefaultValue annotation. It worked for the type Enum as expected. Then we have another issue where we are using a Map<Enum,String> object in our Bean class which didnot get resolved with above. When tried debugging, noticed the following code is going inside the class, EnumResolver since we a . It would be good if we can handle the same default value handling done in EnumDeserializer class , on this class as well so that we can use the default value we have defined. Appreciate a quick response.. Thank you.

StdKeyDeserializer : 
        @Override
        public Object _parse(String key, DeserializationContext ctxt) throws IOException
        {
            if (_factory != null) {
                try {
                    return _factory.call1(key);
                } catch (Exception e) {
                    ClassUtil.unwrapAndThrowAsIAE(e);
                }
            }
            EnumResolver res = ctxt.isEnabled(DeserializationFeature.READ_ENUMS_USING_TO_STRING)
                    ? _getToStringResolver(ctxt) : _byNameResolver;
            Enum<?> e = res.findEnum(key);
            if ((e == null) && !ctxt.getConfig().isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL)) {
                return ctxt.handleWeirdKey(_keyClass, key, "not one of values excepted for Enum class: %s",
                        res.getEnumIds());
                // fall-through if problems are collected, not immediately thrown
            }
            return e;
        }

**Comment by cowtowncoder** [comment]
As per comment on the new issue, note that you do need to use `EnumMap` as type, not `Map`.
Latter does not work, and will not work, without custom key handler.

**Comment by isuribb** [comment]
Thanks All... We went with a custom deserilizer and defaulting to a custom value and it resolved our issue. EnumMap also was not an option due to thrift model is not supporting any custom maps except map and tree map.

**Comment by bsaptarshi** [comment]
> Thanks All... We went with a custom deserilizer and defaulting to a custom value and it resolved our issue. EnumMap also was not an option due to thrift model is not supporting any custom maps except map and tree map.

isuribb,
Can you share the solution you implemented? I am facing a similar issue and would like to get my eye on a likewise solution. Thanks!

**Comment by Chaya56** [comment]
In a Springboot project i create an ObjectMapper (Spring-boot 2.6.3, Jackson-databind: 2.13.1). I want to deserialize Json object with unknown enum key so i activate : READ_UNKNOWN_ENUM_VALUES_AS_NULL parameters, it's not working via Spring bean configuration or yaml configuration.

Spring bean configuration
```
    @Bean
    @Primary
    public ObjectMapper objectMapper() {
        return new ObjectMapper()
                .enable(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL);
    }
```
OR
Spring YAML configuration
```
spring:
  jackson:
    deserialization:
      read_unknown_enum_values_as_null: true
```


Testing configuration, Deserialization context feature is always to false ! and this is this configuration used in StdKeyDeserializer class.
```
    @Autowired
    ObjectMapper objectMapper;

    @Test
    public void testOM() {
        //TRUE
        assertTrue(objectMapper.isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL)); 
        //TRUE
assertTrue(objectMapper.getDeserializationConfig().isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL));  
        //FALSE ??
assertTrue(objectMapper.getDeserializationContext().isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL));  
    }
```

The concerned line is https://github.com/FasterXML/jackson-databind/blame/279d2001db6435ea1e92c48d9e796baa74403dd7/src/main/java/com/fasterxml/jackson/databind/deser/std/StdKeyDeserializer.java#L399

What's wrong with configuration ? How can we get this objectMapper.getDeserializationContext().isEnabled(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL) to TRUE ?
