### ISSUE TITLE
2.1.x: JsonNodeDeserializer returns Java null instead of a NullNode on deserialization: on purpose?

### ISSUE THREAD

**Issue by fge** [FasterXML/jackson-databind#186]
Link:

http://stackoverflow.com/questions/15293697/how-to-deserialize-json-null-to-a-nullnode-instead-of-java-null

I needed it because for my JSON Patch implementation, it is perfectly legal to replace/add/test for a JSON null value.

But `JsonNodeDeserializer` returns `null` by default instead of a `NullNode`. Not sure whether this was meant, or whether changing it would break existing code etc.

Patches for master and 2.1 provided it was not meant to be this way:
- https://github.com/fge/jackson-databind/commit/ea08ca2fe4aaf5ece01d42e281cdfa7d12890c81 (2.1).

UPDATE: master not affected, therefore 2.2.x not affected. Bisected.

**Comment by codecracker2014** [comment]
Hi @cowtowncoder after upgrading jackson from 2.2.2 to 2.7.7 for my project i'm facing issue due to change in deserialization of null into "null" string. Earlier it was deserializing it to null String object. Is there some configuration to achieve it.
