### ISSUE TITLE
problem from transfer xml to json

### ISSUE THREAD

**Issue by ldw85** [FasterXML/jackson-databind#1874]
Out program need to transfer xml to json .We hear that Jackson is very efficient. But the problem maybe is that JsonParse cannot correctly recognize array in xml. For example: 
The xml is: 
`<Response><CustID>1300000428</CustID><CompID>1100000324</CompID><Items><Item><Sku_ProductNo>sku_0004</Sku_ProductNo><Wms_Code>1700386977</Wms_Code><Sku_Response>T</Sku_Response><Sku_Reason></Sku_Reason></Item><Item><Sku_ProductNo>0005</Sku_ProductNo><Wms_Code>1700386978</Wms_Code><Sku_Response>T</Sku_Response><Sku_Reason></Sku_Reason></Item></Items></Response>`
The corresponding json We need json is :
{"CustID":"1300000428","CompID":"1100000324","Items":{"Item":[{"Sku_ProductNo":"sku_0004","Wms_Code":"1700386977","Sku_Response":"T","Sku_Reason":""},{"Sku_ProductNo":"0005","Wms_Code":"1700386978","Sku_Response":"T","Sku_Reason":""}] }}
However, actually, we get json like this: 
{"CustID":"1300000428","CompID":"1100000324","Items":{"Item":{"Sku_ProductNo":"sku_0004","Wms_Code":"1700386977","Sku_Response":"T","Sku_Reason":""},"Item":{"Sku_ProductNo":"0005","Wms_Code":"1700386978","Sku_Response":"T","Sku_Reason":""}}}

And then , Our Program is : 
StringWriter w = new StringWriter();  
        JsonParser jp = xmlMapper.getFactory().createParser(xml);  
        JsonGenerator jg = objectMapper.getFactory().createGenerator(w);  
        while (jp.nextToken() != null) {  
            jg.copyCurrentEvent(jp);  
        }  
        jp.close();  
        jg.close();  
        return w.toString();  

I think the problem come from JsonParser, can you fix it?

**Comment by cowtowncoder** [comment]
This needs to be filed for `jackson-dataformat-xml`: databind does not deal with any aspects of XML handling.

Also note that XML module only supports data-binding use; Streaming API and Tree Model usage is not supported -- it may work to some degree, but there are no guarantees. Streaming API, specifically, only works to support databinding built on top of it.

As to arrays in XML: there is no natural construct in XML to distinguish difference between Objects and Arrays, so without additional external information, all XML elements are exposed as Objects (and their properties); there is no way to reliably detect something that should be seen as array, except that databind can provide hint at expected type (for Java `Collection`s and arrays).
