### ISSUE TITLE
JsonParser.readValueAsTree() works in incorrect way

### ISSUE THREAD

**Issue by MarenkovSergey** [FasterXML/jackson-databind#1876]
Hello. In the following code example

```
ObjectMapper mapper = new XmlMapper();

     String map = "<map>\n" +
                   "   <entry>\n" +
                   "       <key>1</key>\n" +
                   "       <value/>\n" +
                   "   </entry>\n" +
                   "   <entry>\n" +
                   "       <key>2</key>\n" +
                   "       <value/>\n" +
                   "   </entry>\n" +
                   " </map>";
TreeNode root =  mapper.getFactory().createParser(map).readValueAsTree();
```
root.toString() returns json:
{"entry":{"key":"2","value":null}} but it should be:
{"entry":{"key":"1","value":null}, "entry":{"key":"2","value":null}}

I think the problem come from JsonParser, can you please fix it?

**Comment by cowtowncoder** [comment]
Uh no. This is XML specific problem so would need to be filed there.

However: this is not a bug but unsupported feature: Tree Model (`TreeNode`) is not supported with XML backend. This is document on XML module's README: some features work, others not.
And specifically there is no way to represent duplicates: as you can see, your XML content has duplicates. Only one may ever be included; in practice it's the last one.
