### ISSUE TITLE
Ignoring field only on Serialization

### ISSUE THREAD

**Issue by mazkozi** [FasterXML/jackson-databind#1884]
Hi,

I am using Jackson 2.8.0 and I have a field that shouldn't be serialized, but should be deserialized. I tryied `@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)`, it didn't work. I tried solution given in [http://www.davismol.net/2015/03/21/jackson-using-jsonignore-and-jsonproperty-annotations-to-exclude-a-property-only-from-json-deserialization/#comment-41303](url) it didn't work either. 
As a last resort, I tried `@JsonIgnoreProperties(value="field", allowSetter=true)`, no luck there too.
I spent almost a day googling, but didn't succeed. 

Can you please help me out in sorting out the issue?

**Comment by cowtowncoder** [comment]
First things first: why are you using `2.8.0`, when there are many, MANY later patch versions with numerous fixes? Try first with latest release (2.8.11) and see if that helps.
(NOTE: this is even mentioned in boilerplate instructions for filing issues!!!!)
Both approaches you mention should work.

If up-to-date patch version does not help, then please include exact code you are using, to replicate the problem you see.

**Comment by mazkozi** [comment]
HI @cowtowncoder. I use spring boot and I guess v2.8.0 came with the version of spring boot I use. I did override it with jackson v2.9.3 and test it. Faced same issue. I will try with 2.8.11 and let you know if issue still present.

Thank you.

**Comment by mazkozi** [comment]
I tried with v2.8.11 and I still don't get it resolved. Below is my java object. This is hibernate entity object that I serialize using jackson. I am using junit test rest template to invoke my rest controller that returns this entity object.

PN: I have changed the name of class and fields. However, retained annotations if that is required for your analysis.

`@Entity
@Table(name = "my_model")
//@JsonIgnoreProperties(value="assessment", allowSetters=true)
public class MyModel extends AbstractBaseModel implements BaseModel {

    @Null(groups = ValidateOnCreate.class)
    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    private String myId;

    //@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY )
    @JoinColumn(name = "parent_id", nullable = false)
    private Parent parent;    

    @NotNull(groups = {ValidateOnCreate.class, ValidateOnUpdate.class})
    @ValidString(values = {"Draft", "Complete"}, groups = {ValidateOnCreate.class, ValidateOnUpdate.class},
            message = "is invalid. Valid values are ['Draft', 'Complete']")
    @Column(name = "trigger", nullable = false, length = 20)
    private String trigger;

    public String getMyId() {
        return myId;
    }

    public void setMyId(String myId) {
        this.myId = myId;
    }
    
    @JsonIgnore
    public Parent getParent() {
        return parent;
    }

    @JsonProperty
    public void setParent(Parent parent) {
        this.parent = parent;
    }

    public String getTrigger() {
        return trigger;
    }

    public void setTrigger(String trigger) {
        this.trigger = trigger;
    }
}`

**Comment by cowtowncoder** [comment]
Ok; if Hibernate is used in any way, problem may belongs under `jackson-datatype-hibernate`, since there are quite a few things that need special handling.

What I would need is a reproduction, ideally small unit test. That could settle the question of whether Hibernate is relevant here as well: chances are it is, but if not it is much easier to tackle.

**Comment by mazkozi** [comment]
Ok. Below is the sample code of my spring boot application that can be used to replicate the issue. If I comment out the Jackson annotation in MyModel class, it works fine.

**Parent**

`import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "parent")
public class Parent {

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    private String id;

    @Column(name = "name", nullable = false, length = 20)
    private String name;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}`

**MyModel**

`import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

@Entity
@Table(name = "my_model")
public class MyModel {

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    private String myId;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY )
    @JoinColumn(name = "parent_id", nullable = false)
    private Parent parent;

    @Column(name = "trigger", nullable = false, length = 20)
    private String trigger;

    public String getMyId() {
        return myId;
    }

    public void setMyId(String myId) {
        this.myId = myId;
    }

    @JsonIgnore
    public Parent getParent() {
        return parent;
    }

    @JsonProperty
    public void setParent(Parent parent) {
        this.parent = parent;
    }

    public String getTrigger() {
        return trigger;
    }

    public void setTrigger(String trigger) {
        this.trigger = trigger;
    }
}`

**REST Controller:**

`import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/mymodel")
public class MyModelController {

    @GetMapping()
    public ResponseEntity<MyModel> getMyModel() {
        Parent parent = new Parent();
        parent.setId("123");
        parent.setName("test");

        MyModel myModel = new MyModel();
        myModel.setMyId("123");
        myModel.setTrigger("trigger");
        myModel.setParent(parent);

        return new ResponseEntity<>(myModel, HttpStatus.OK);
    }
}
`

**JUnit Test:**

`import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

//My springboot application
import au.th.api.assessment.AssessmentsApplication;
import au.th.api.assessment.jackson.MyModel;

@RunWith(SpringRunner.class)
@ContextConfiguration(classes = AssessmentsApplication.class)
@ActiveProfiles(value = "unit-test")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public class MyModelTest {

    @Autowired
    private TestRestTemplate restTemplate;

    @Test
    public void test_getMyModel() {
        ResponseEntity<MyModel> responseEntity = restTemplate.getForEntity("/mymodel", MyModel.class);
        MyModel myModel = responseEntity.getBody();
        assertThat(myModel.getParent()).isNotNull();
    }
}
`

**Comment by cowtowncoder** [comment]
@mazkozi  I appreciate your taking time to do this, but unfortunately it is not quite what I was hoping for. Use of Hibernate will make it impossible to know if Hibernate was causing this; and use of Spring Boot is another dependency I really don't want to try to debug. It is quite common that some reported issues have been due to framework using different `ObjectMapper` than one developer had configured. These are avoided when there is no framework included.

What I was hoping was a simple case of constructing POJO (with model annotated as described), and seeing how property that should not be included in serialization was.

**Comment by mazkozi** [comment]
Ok. You can use the below junit test class with the models pasted above to replicate the issue. Hope this is what you are looking for.

```
public class MyModelTest {

    private MyModel myModel;

    @Before
    public void setup() {
        Parent parent = new Parent();
        parent.setId("123");
        parent.setName("test");

        myModel = new MyModel();
        myModel.setMyId("123");
        myModel.setTrigger("trigger");
        myModel.setParent(parent);
    }

    @Test
    public void test_getMyModel() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.writeValue(new File("my_model.json"), myModel);
    }
}
```

**Comment by mazkozi** [comment]
I tried without the framework (hibernate/spring/rest) and it works fine. :(. What should be the solution for me now?

**Comment by cowtowncoder** [comment]
@mazkozi I would try to further see if it might Hibernate-specific; if not, it's about configuring `ObjectMapper`. I think it is bit more likely something in Hibernate handling of Objects (it does some proxying for lazy-loading and such I think) is causing issues here.
On the other hand if it's about framework that is probably easier to solve.
