### ISSUE TITLE
Add configurability to make Jackson deserialize empty objects (`{ }`) as `null`s

### ISSUE THREAD

**Issue by iuppal** [FasterXML/jackson-databind#1885]
We are in course of switching to Jersey 2.x and now planning to use Jackson (2.9.2) as default JSON Serializer/Deserializer for JSON request/responses in our APIs. After upgrading, we have run into an issue, where with Jersey 1.x, for a given property of Object type, sending an empty JSON object value was treated as NULL in our system. But now post Jackson upgrade,  we are seeing that the property value is not received as NULL, but rather an initialized object with its member fields initialized to default values. This is breaking a lot of functional pieces in our code, which were earlier relying on a NULL value being sent for a property, which was sent as an empty Object in API request

We figured out that Jackson Deserialization already offers the following two configurations for Arrays and Strings, where empty values gets unmarshalled as NULL. These are

ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT 
ACCEPT_EMPTY_STRING_AS_NULL_OBJECT 

The question is why there is no such configuration for Objects. e.g something like ACCEPT_EMPTY_OBJECT_AS_NULL_OBJECT. Support for this configuration OR similar mechanism would really help solve our usecase and help us move forward with our Upgrade. 

We also evaluated the option of wiring a custom JsonDeserializer as depicted here https://stackoverflow.com/questions/40366524/how-to-tell-jackson-to-ignore-empty-object-during-deserialization/40366833#40366833

However, this would be a tedious effort for us, as the current JSONDeserializer semantics require a separate deserializer for each Type and we have over 100 Request objects across 6 versions of our API.

It would be really helpful to offer a simple configuration based semantics to help address this issue. Looking forward to the response.

**Comment by cowtowncoder** [comment]
Jackson has never supported coercion of empty JSON Objects into `null`s, so I don't know what could have implemented such logic.

There is no current configuration to try to handle this in specific way, and there are no plans for such transformation. Unfortunately trying to implement such conversion is particularly difficult since whereas `null` is a single token, and requires no reading from stream for anything more, detecting sequence of `START_OBJECT` followed by `END_OBJECT` with no content can not be done without buffering (which is extra complexity and cost). It is something that individual deserializers would need to check and handle appropriately.

I will leave this issue open as an RFE for implementing something to support the use case in case someone has good ideas of how it could be done.
Another thing, besides implementation itself, is the question of API, whether it could be improved from global `Feature` (although actually `@JsonFormat` does support application of similar features on per-property basis, so this may not be huge problem).

**Comment by iuppal** [comment]
Thanks @c0nscience for your quick response. So, in nutshell, your recommendation would be to create custom JSON Deserializer, right ? And that would require us to create and register each such Jeserializer separately all Object type properties in every Request object. That would be some work and doesn't look like a scalable approach to take. 

Also, I did not follow your comment on >> _whether API could be improved from global Feature_. Can you please provide some more context. 

As last resort, if there is no simple configuration based mechanism available, we might have to explore switching to some other JSON marshall/unmarshall libraries (e.g I read about GSON), though I am not sure if even they would be solving this problem or not.

**Comment by cowtowncoder** [comment]
On registration of deserializers: usually they are registered by type; there is no simple way to register deserializers for properties. Although latter can be achieved by custom `AnnotationIntrospector`, to mimic the way `@JsonDeserialize(using=...)` works.
And yes, it is quite a bit of work.

As to API, it's probably not worth discussing now; I was just thinking out aloud regarding how to enable such handling, if it was implemented. That is separate from implementing it.

**Comment by yay** [comment]
I guess, calling `replace("{}", "null")` on the JSON string before parsing it is the most obvious and dead simple workaround.

**Comment by GabrielBB** [comment]
> I guess, calling `replace("{}", "null")` on the JSON string before parsing it is the most obvious and dead simple workaround.

What if you have:

```
{
 code: "{}"
}
```

**Comment by cowtowncoder** [comment]
One other note: 2.12 does have new "CoercionConfig" system used for coercions; unfortunately case of JSON Object to POJO is not coercion (as input shape and target type are compatible already).

If I was to try to make this work via extensions, #2045 could allow this (specifically "post-deserialize" callback) if it was implemented.
But of existing functionality, I think that use of Builder-pattern might work (see `@JsonPOJOBuilder`): builder could return `null` if no properties were set.

**Comment by cowtowncoder** [comment]
At this point I don't think there are plans to support such automatic change: use of Builder-style pattern and custom logic is expected.

**Comment by MOsalik** [comment]
> I guess, calling `replace("{}", "null")` on the JSON string before parsing it is the most obvious and dead simple workaround.

what if we have nested objects and could be array of objects in that case it would become complex
