### ISSUE TITLE
Allow use of `@JsonFormat(with=JsonFormat.Feature.ACCEPT_CASE_INSENSITIVE_PROPERTIES)` on Class

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1886]
(note: follow-up from #1851)

Currently `@JsonFormat` features, and specifically `Feature.ACCEPT_CASE_INSENSITIVE_PROPERTIES`, does not apply if annotated via class. Like:

```java
    @JsonFormat(with={ JsonFormat.Feature.ACCEPT_CASE_INSENSITIVE_PROPERTIES })
    static class Role {
        public String ID;
        public String Name;
    }
```

whereas similar setting with `mapper.configOverrides(class)` does work.

It would probably make sense to allow annotation on class too, having lower precedence than config override, but higher than general one.

**Comment by JavierSegoviaCordoba** [comment]
up

**Comment by giltroymeren** [comment]
Issue still exists with version 2.9.0

**Comment by cowtowncoder** [comment]
@JavierSegoviaCordoba @giltroymeren I am confused wrt your comments: this is an open issue, not marked as fixed, so how would it not be an issue any more? There is no need to add markers for "still not working".

**Comment by macfarla** [comment]
@cowtowncoder looking closer at this it looks like you've added support at the class level but not at the property level, is that right? And if so, do you plan to add property level support?

**Comment by cowtowncoder** [comment]
@macfarla No, I don't think there is support for just one case-insensitive property, and there are no plans to do that.
You can file a new request if you want, in case someone had time and interest to implement it.

**Comment by macfarla** [comment]
Thanks @cowtowncoder I have found another way to do what I need :)

**Comment by kupci** [comment]
@macfarla Just in case others have same issue, the `JsonAlias` solved the issue (in referenced bug) for you?

**Comment by cowtowncoder** [comment]
Ah, yes, `@JsonAlias` seems often useful.

And as a sidenote: the reason for no support for single-property case-insensitivity is the technical implementation: lookup for all properties is via data structure that does either strict, or case-insensitive. So there is no way to distinguish this on per-property basis, as of yet.

**Comment by bipul-git** [comment]
is ACCEPT_CASE_INSENSITIVE_PROPERTIES working now for properties?

**Comment by cowtowncoder** [comment]
@bipul-git It can be applied on individual properties with `@JsonFormat`, yes.
