### ISSUE TITLE
Per-type config override "JsonFormat.Shape.OBJECT" for Map.Entry not working 

### ISSUE THREAD

**Issue by mcortella** [FasterXML/jackson-databind#1895]
Hi, after updating from a 2.0.x version of jackson to 2.9.2 we faced an issue with the serialization of Map.Entity as reported also here #565. One of the proposed solution to have a backward-compatibility to versions prior to 2.5, as a default, is this one:

`ObjectMapper mapper = new ObjectMapper();
			mapper.configOverride(Map.Entry.class).setFormat(JsonFormat.Value.forShape(JsonFormat.Shape.OBJECT));`

But unluckly is not working. There is a way to fix that or have a similar solution without using annotations?

Thanks.

**Comment by cowtowncoder** [comment]
Hmmmh. #1419 states it does not work for property. But it should work as type override.

**Comment by cowtowncoder** [comment]
Ok, with added test I can see configOverride does not, indeed, work: only class annotation (direct or mix-in does). So there's a bug to fix.
