### ISSUE TITLE
FEATURE: Allow typed attributes / services

### ISSUE THREAD

**Issue by thomaseizinger** [FasterXML/jackson-databind#1896]
I am currently using the Attribute-Concept to pass a `LinkFactory` to a `VirtualBeanPropertyWriter` that is used via `JsonAppend`.

Here is an example:

    public class ExpenseLinksPropertyWriter extends VirtualBeanPropertyWriter {

        public ExpenseLinksPropertyWriter() {
        }

        public ExpenseLinksPropertyWriter(BeanPropertyDefinition propDef, Annotations contextAnnotations, JavaType declaredType) {
            super(propDef, contextAnnotations, declaredType);
        }

        @Override
        protected Object value(Object bean, JsonGenerator gen, SerializerProvider prov) throws Exception {

            final ExpenseLinkFactory expenseLinkFactory = (ExpenseLinkFactory) prov.getAttribute(ExpenseLinkFactory.class.getName());

            return new HashMap<String, String>() {{
                put("delete", expenseLinkFactory.createLinkToExpense((Expense) bean).toString());
            }};
        }

        @Override
        public VirtualBeanPropertyWriter withConfig(MapperConfig<?> config, AnnotatedClass declaringClass, BeanPropertyDefinition propDef, JavaType type) {
            return new ExpenseLinksPropertyWriter(propDef, null, type);
        }
    }

As you can see, I am using the class name as the key and then casting the value back to the factory in order to call it.

1) It would be nice if the Object inside the `value`-method would be typed.
2) While this works perfectly fine, it would be nice to have a proper API for doing these kind of things. So what I actually want to do is, passing an instance of an object to my ObjectWriter that is later accessible during the serialization, just like the attributes are.
A quick solution would be to add an API to `ContextAttributes` that required a `Class<T>` to be passed in as the key (instead of string) and automatically casts the result back to `T`. This would make the usage nicer. It would be even better though, if there would be a way to properly get this depenency into the `VirtualBeanPropertyWriter` through some kind of IoC-mechanism.
But I guess this would require a dedicated API for specifying some sort of `InstanceProvider<T>` on the ObjectWriter / -Reader that is used during the creation of a `VirtualBeanPropertyWriter`-instance in order to inject the dependencies.

Thoughts?

**Comment by cowtowncoder** [comment]
I am not sure I understand proposal in its entirety, but to be completely honest I would like to keep complexity of tracking of user provided things to minimum. And as such, Context Attributes seem to fulfill enough use cases without complicated management.

But perhaps someone could implement a module that would add dependency injection convenience for things like this?

**Comment by cowtowncoder** [comment]
I am not sure how to proceed here; closing.
