### ISSUE TITLE
element type error for array type

### ISSUE THREAD

**Issue by yinchuanwang** [FasterXML/jackson-databind#1900]
version 2.8.9 .    
repro steps in scala:     
```
case class Test(value:Seq[Double]) 

val str = "{ \"value\" : [ \"1\", \"2\" ]}"

val defaultObjectMapper = new ObjectMapper() with ScalaObjectMapper

defaultObjectMapper.registerModule(DefaultScalaModule)

val obj = defaultObjectMapper.readValue(str, classOf[Test])

```

The value of class Test is a sequence of type Double, however, it can be successful to deserialize a json string which actually contains a array of type string.     

It is expected that a deserialize exception should be thrown.

**Comment by cowtowncoder** [comment]
Please re-file at `jackson-module-scala` as it is about Scala types: core databind does not directly support Scala types.

**Comment by yinchuanwang** [comment]
re-file at the jackson-module-scala, so close this one.

**Comment by cowtowncoder** [comment]
Thank you!
