### ISSUE TITLE
FEATURE: Inject variable specific values into Converter/Deserializer.

### ISSUE THREAD

**Issue by 0megaD** [FasterXML/jackson-databind#1909]
This is a simple feature proposal, though since I'm not a Jackson expert I might have overseen some existing functionality.

I currently receive a JSON that contains many nested objects that are all the same type (String -> Number), the keys may differ however.

What I want to do is write one simple Converter/Deserializer that can handle all the various nested objects by injecting a value into the converter.

As an example, take the following json:

```
{
	"temp": {
		"c": "1",
		"f": "20"
	},
	"pressure": {
		"a": "1",
		"millibar": "1000"
	}
}
```

If I had a class containing both a 'temperatureInFahrenheit' and 'pressureInMillibar' variable without wanting to wrap them, I would need to create two converters/deserializers, one that handles the "f" in temp, and one that handles the "millibar" in pressure.

What would be useful is if I could inject a value that I could use to determine what type of nested object I'm handling, allowing me to then grab the appropriate key. Something like:

```
@JsonProperty("temp")
@JacksonInject(values = "Pressure")
@JsonDeserialize(convert = MyConverter.class)
```
Then inside the converter I could do:
```
    @Override
    public Double convert(Map<String, Double> value) {
        if(injectedValue == "Pressure") return value.get("millibar")
        if(injectedValue == "Temperature") return value.get("f")
    }
```

I'm sorry if there's a way to do this already, the main reason I posted this is because I'm getting some really wonky funky json at work which will be flattened in the future, but I'm looking for a pragmatic way to handle the various cases until then.

**Comment by cowtowncoder** [comment]
I think there may be an existing mechanism for this -- for deserializers that implement `ContextualDeserializer`, method `createContextual()` should be called, passing `BeanProperty` along. This property object gives access to annotations on property for which deserializer is being used. So perhaps try and see if that works first?

**Comment by 0megaD** [comment]
Thanks! This was exactly what I was looking for. Doesn't seem to be compatible with converters, but this will do for now. 

I will consider this closed now as the initial issue has been solved. I do have one last question though: Is there a way to make this work with converters?

**Comment by cowtowncoder** [comment]
@0megaD Currently converters are located via `AnnotationIntrospector` method `findSerializationConverter()` (and `findDeserializationConverter()`), which simply returns either `Class` to instantiate, or instance (for custom instrospectors). Default `BeanDeserializer` will ask for one and use it, if necessary. So you could probably sub-class `JacksonAnnotationIntrospector` to implement alternate handling.

But there is no contextualization for `Converter`s at this point. I have been thinking of doing something like that, as per:

https://github.com/FasterXML/jackson3-dev/issues/9

for Jackson 3.x, will add a note.
