### ISSUE TITLE
Allow serialization of `BigDecimal` as String, using `@JsonFormat(shape=Shape.String)`, config overrides

### ISSUE THREAD

**Issue by cen1** [FasterXML/jackson-databind#1911]
When REST API is consumed by JavaScript, in order to prevent the loss of precision, BigDecimal is normally passed as a string. While adding a custom serializer is easy, I think this is a very common case and warrants an out of the box SerializationFeature.

**Comment by cowtowncoder** [comment]
This is bit too granular thing, at this point, as I would hope to avoid adding new non-general `SerializationFeature`s. But there is `@JsonFormat` already, with `shape` property (`Shape.STRING`) that should work.

It may be used on specific properties, but also via "configOverrides" for type; something like

    mapper.configOverrides(BigDecimal.class).
       .setFormat(JsonFormat.Value.forShape(JsonFormat.Shape.STRING));

If this does not yet work (it requires support from serializer), it should be added.
I'll leave this open for verification if anyone has time.

**Comment by cen1** [comment]
That seems reasonable enough. I'll test on monday and come back.

**Comment by cowtowncoder** [comment]
@cen1 Thanks. And thank you for reporting this; I agree that this is important use case for javascript clients.

**Comment by cowtowncoder** [comment]
Ok while conversion does work for primitive types, it is not yet supported for `BigInteger` or `BigDecimal`. Needs to be added.

**Comment by hashhar** [comment]
@cowtowncoder I cannot see anywhere what method is called on the BigDecimal to convert it to a string? Is it `toPlainString()`, `toString()` or `toEngineeringString()`?

**Comment by cowtowncoder** [comment]
@hashhar what are you trying to achieve, specifically? Method will be either in`jackson-core` (at low-level `JsonGenerator` implementation), or within `jackson-databind`. In latter case, it'd be in `BigDecimalAsStringSerializer` defined as inner class of `NumberSerializer`.

**Comment by hashhar** [comment]
I want to control how the BigDecimal gets converted into a string when using the `JsonFormat.Shape` support. For some BigDecimals I might want to use `toPlainString()` (think while dumping into a CSV) while for some I might be okay with `toString()/toEngineeringString()`.

**Comment by cowtowncoder** [comment]
Ok. Yes, at some point it may make sense to write a custom serializer: with `createContextual()` you have access to configuration and annotation information, including format settings.

**Comment by chosegood** [comment]
I've configured the following

```
jackson:
  serialization-inclusion: "USE-DEFAULTS"
  generator:
    WRITE_BIGDECIMAL_AS_PLAIN: true
  deserialization:
    USE_BIG_DECIMAL_FOR_FLOATS: true

```

In the sample application referenced above the following test passes

 ```
 @Test
    fun jacksonRetainsPrecision() {
        val objectMapper = embeddedServer.applicationContext.getBean(ObjectMapper::class.java)

        val initialDataset = mapOf<String, Any?>(
                "string" to "string",
                "bigDecimal" to BigDecimal("888.7794538169553400000")
        )

        val writeValueAsBytes = objectMapper.writeValueAsBytes(initialDataset)
        val responseDataset = objectMapper.readValue<Map<String, Any?>>(writeValueAsBytes)
        assertThat(responseDataset, equalTo(initialDataset))
    }
```

The following test fails
```
    @Test
    fun micronautRetainsPrecision() {
        val objectMapper = embeddedServer.applicationContext.getBean(ObjectMapper::class.java)
        val httpClient = HttpClients.createDefault()

        val initialDataset = mapOf<String, Any?>(
                "string" to "string",
                "bigDecimal" to BigDecimal("888.7794538169553400000")
        )

        val postRequest = HttpPost(embeddedServer.uri.resolve("/bug"))
        postRequest.setHeader(HttpHeaders.CONTENT_TYPE, ContentType.APPLICATION_JSON.toString())
        postRequest.entity = GzipCompressingEntity(EntityTemplate { out -> objectMapper.writeValue(out, initialDataset) })

        httpClient.execute(postRequest, BasicResponseHandler())

        val getRequest = HttpGet(embeddedServer.uri.resolve("/bug"))
        val getResponse = httpClient.execute(getRequest, BasicResponseHandler())
        val responseDataset = objectMapper.readValue<Map<String, Any?>>(getResponse)
        assertThat(responseDataset, equalTo(initialDataset))
    }

```
