### ISSUE TITLE
supporting for $id , $ref and $values?

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [FasterXML/jackson-databind#1920]
Hi,Is there a way for supporting $id , $ref and $values in jackson deserializing component?

**Comment by cowtowncoder** [comment]
Please ask usage questions on mailing list in future:

https://groups.google.com/group/jackson-user/

But guessing at what you are trying to ask I think what you want is `@JsonProperty` annotation to indicate name to use in JSON, to match to property in Java class.
