### ISSUE TITLE
Handling timezone depending upon the server timezone.

### ISSUE THREAD

**Issue by aishwaryajeevarathinam** [FasterXML/jackson-databind#1926]
After going through this https://github.com/FasterXML/jackson-databind/issues/275 , i got it that timezone can be set to our local timezone accordingly.. But i dont want to mention the "timezone = IST" directly in my @JsonFormat.. I need to set the timezone depending on the server timezone.. Iam using Jboss 6.4 and i tried adding "JAVA_OPTS = -Duser.timeZone = IST" in my standalone.conf file. After restarting the server its taking the same GMT timezone. Is there is any way to set the timezone depending upon the server timezone?

**Comment by cowtowncoder** [comment]
@aishwaryajeevarathinam you may have misunderstood concept of issue tracker. This is not a mailing list or user discussion forum. Do not send usage question here.
Proper place is:

https://groups.google.com/forum/#!forum/jackson-user
