### ISSUE TITLE
JsonCreator is overwritten by buffered properties

### ISSUE THREAD

**Issue by rupert654** [FasterXML/jackson-databind#1927]
This problem occurs in 2.8.0 but I've also verified it occurs in the latest version 2.9.4.

The issue is specifically when the JSON property does not match the POJO field name and there is another JSON property which does match the POJO field name:

Consider this JSON:

```json
{
  "id": "incorrect value",
  "name": "correct value"
}
```

and this POJO:

```java
public class Foo {
  private final String id;

  @JsonCreator
  public Api(@JsonProperty("name") final String id) {
    this.id = id;
   }

  public String getId() {
    return id;
  }
}
```

I would expect Foo.getId() to return "correct value" but it does not. If you place a breakpoint in the constructor, you will see that it does get called, and with "correct value".

However, Jackson appears to contain some logic to buffer property values as it parses the JSON. Since it sees "id" and also notices that `Foo` has a property id, it adds this to the `_buffered` field inside `PropertuyValueBuffer`. Then after creation (and despite the field being final!), the field is overwritten with the buffered id.

Thus the field ends up being set to "correct value", and then "incorrect value".

A workaround is to duplicate the @JsonProperty on the field name also as follows:

```java
public class Foo {
  @JsonProperty("name")
  private final String id;

  @JsonCreator
  public Api(@JsonProperty("name") final String id) {
    this.id = id;
   }

  public String getId() {
    return id;
  }
}
```

You could also choose a field name that does not conflict with the JSON api fields but this not future proof and could mean that your code breaks unexpectedly, purely due to a new field conflicting with your field name.

This problem is quite awkward to debug if you aren't expecting it and I feel that the finality of the field should be respected by Jackson.

**Comment by cowtowncoder** [comment]
First things first: if you do not want `final` fields to ever be used as setters, you want to disable

    MapperFeature.ALLOW_FINAL_FIELDS_AS_MUTATORS

(which defaults to `true`, that is, enabled).

The main reason this is enabled by default is that some users rely on JVM oddity, wherein final fields may actually be set via reflection for some time after construction. Presumable this is to make JVM serialization work. I agree in that this is bit unexpected, but given existing usage changing behavior to defaulting can not be done until 3.0.

Alternatively, note that you can just add `@JsonIgnore` on `id` field. If you still want to retain `id` on deserialization, you can additionally add `@JsonProperty` on `getId()` -- this "split" annotation is handled as expected. Conversely, if you only use one or the other then explicit annotation is taken to apply to "whole" property: so either both are ignored, or both included.
And finally, yes, your work-around also works: it points to Jackson that field and constructor parameter are related to the same logical property.
