### ISSUE TITLE
[Q] How to wrap single POJO with array

### ISSUE THREAD

**Issue by bademux** [FasterXML/jackson-databind#1930]
Hello,
Can you please help me to find solution how to wrap POJO with array (create singletonArray).
Unfortunatly StdDelegatingSerializer leads to expected infinite loop:
```java
public OUT convert(IN value){
 return new Object[]{value}
}
```
Is there any smart generic way to solve my problem or per-type custom serializers is the only way? 

thanks.

**Comment by cowtowncoder** [comment]
No, this is not a ask you question forum. There is a user mailing list:

https://groups.google.com/forum/#!forum/jackson-user

which you could have googled easily.
