### ISSUE TITLE
Excluding empty objects from serialization

### ISSUE THREAD

**Issue by serpro69** [FasterXML/jackson-databind#1934]
Let's say I have following data class that has a child data class:

```
data class Parent(
    val name: String? = null,
    val age: Int? = null,
    val child: Child? = null
) {

    data class Child(
        val name: String? = null,
        val age: Int? = null
    )
}
```
then this:
```
    val child = Parent.Child()
    val parent = Parent(name = "Dad", age = 49, child = child)
    val print = ObjectMapperConfigurator.get().writerWithDefaultPrettyPrinter().writeValueAsString(parent)
    println(print)
```
will give me: 
```
{
  "name" : "Dad",
  "age" : 49,
  "child" : { }
}
```
However I want to avoid having child serialized with empty body.
and my object mapper config is as follows:
```
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true)
        objectMapper.configure(DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES, true)
        objectMapper.configure(DeserializationFeature.READ_ENUMS_USING_TO_STRING, true)
        objectMapper.configure(SerializationFeature.WRITE_ENUMS_USING_TO_STRING, true)
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL)
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY)
```

I've also tried adding @JsonInclude annotation on top of data classes and assigning them for properties - result is the same. 

Jackson version is 2.9.4

**Comment by jedi-tester** [comment]
A bit more experimenting and I've found that excluding empty child object when instantiating parent class works fine:
```
    val parent = Parent(name = "Dad", age = 49)
    val print = ObjectMapperConfigurator.get().writerWithDefaultPrettyPrinter().writeValueAsString(parent)
    println(print)
```
I wonder if there is any native way to exclude an empty object from being serialized.

**Comment by iliassk** [comment]
@cowtowncoder Is there any plans to add a native way of excluding the serialization of empty objects in Jackson ?

**Comment by cowtowncoder** [comment]
@iliassk One other thing to note is that exclusion of "default" values should allow this, as long as POJO implements `equals()` properly: if POJO was `NON_DEFAULT` class annotation, then POJO-valued properties are checked same as everything else: an instance is constructed using 0-argument constructor, and this instance is compared to (non-null) value, and value is excluded if they equal.

There is also the newish option of "custom" filter for `@JsonInclude`, see:

https://medium.com/@cowtowncoder/jackson-2-9-features-b2a19029e9ff

which does allow any kind of logic you want.

There are no current plans aside from these options however: amount of work involved in implementing various strategies is practically unlimited so I'd prefer to cap it by allowing extension by others at this point.
But I am always open to suggestions on possible techniques for new features.

**Comment by asarkar** [comment]
> One other thing to note is that exclusion of "default" values should allow this

Can you show how to do it for the example classes in the question?

**Comment by cowtowncoder** [comment]
@asarkar Not sure as that's in Kotlin, but you'd add `@JsonInclude(Include.NON_DEFAULT)` for property `child`. And ensure that equality works so that something like

    assertEquals(new Child(), new Child())

holds true.

**Comment by asarkar** [comment]
@cowtowncoder I had tried what you said in Java, but no luck. I'll post a [MCVE](https://stackoverflow.com/help/mcve).

**Comment by cowtowncoder** [comment]
@sergio-igwt @asarkar  I would need a pure Java (no Kotlin/Scala, no Lombok) reproduction of the case where exclusion does not work when using `NON_DEFAULT`, and where value does properly implement `equals()` (also needs to have no-args constructor, but that need not be public, protected, private work fine)

**Comment by asarkar** [comment]
@cowtowncoder I think the requirement to "properly implement `equals`" is impractical. For a large object, that means checking each and every field manually. What is being asked here is that if the user has configured the serializer to exclude empty objects, Jackson should check if each field = default value, either explicitly set, or as defined by the type system, and don't include an object in the JSON where all fields are set to default. Of course, there are instances when this behavior isn't desirable, and that's for the user to decide. If they always want this behavior, they'll set it on the `ObjectMapper`; otherwise, they'll set it on the class.

**Comment by cowtowncoder** [comment]
@asarkar that is the way it works, and I do not have personal interest in changing that behavior at this point.
If you are interested in it, you may consider working a patch to improve behavior to your liking.

**Comment by drekbour** [comment]
This caused me a lot of bother today. Emitting `{}` for an empty/default child object is unacceptable when the output is a delta publication (for which `{}` says "remove all existing data"). Ugly workaround involved 

    @JsonInclude(value = Include.CUSTOM, valueFilter = NonNullSpecialFilter.class)

but I'm not happy with it because custom filter has no access to Jackson's metadata about the properties so is hard-coded to a certain usecase
