### ISSUE TITLE
What is JsonFile class in README.md

### ISSUE THREAD

**Issue by ttpro1995** [FasterXML/jackson-databind#1936]
I wonder what is JsonFile class in readme.md
(import what ? ) 

```
// First: write simple JSON output
File jsonFile = new JsonFile("test.json");
```

**Comment by cowtowncoder** [comment]
@ttpro1995 Seriously? What the fuck is wrong with you people adding USAGE QUESTIONS on ISSUE TRACKER?!?!?!?!
