### ISSUE TITLE
@JsonRawValue uses not only annotated method but all fileds too

### ISSUE THREAD

**Issue by aint** [FasterXML/jackson-databind#1938]
Hello,

I've faced some strange issue with `@JsonRawValue` annotation that duplicates fields in a response while `@JsonValue` works as expected.

So, let's consider some simplified POJO 

```java
@JacksonXmlRootElement(localName = "result")
public class PostSdkLicenseResponse implements Response {

    private final StatusCodeType status;
    private final String errorDetails;
    private final String errorCode;
    private final String errorMessage;

    @JsonRawValue
    @Override
    public String toString() {
        return String.format("%s%s%s%s",
            XmlUtils.addSomeAttrib(errorCode, "errorCode", false, true, true),
            XmlUtils.addSomeAttrib(errorDetails, "errorDetails", false, true, true),
            XmlUtils.addSomeAttrib(errorMessage, "errorMessage", false, false, true),
            XmlUtils.addSomeAttrib(status, "status", false, false, true)
        );
    }

}
```

which serialized to the following XML response

```xml
<result xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
    <errorCode/> 
    <errorDetails/>
    <errorMessage/>
    <status>Success</status>
    <errorCode i:nil="true" xmlns="" />
    <errorDetails i:nil="true" xmlns="" />
    <errorMessage xmlns="" />
    <status xmlns="">Success</status>
</result>
```

It looks like `@JsonRawValue` uses not only annotated method but all fileds too. And there is no such problem with `@JsonValue` annotation. 

Tested on 2.8.11.1 and 2.9.4.

Cheers.

**Comment by cowtowncoder** [comment]
This is misunderstanding, then. Although names are similar, intents are different: `@JsonRawValue` is NOT a specialization of `@JsonValue`. I can see how this is confusing: in hindsight, perhaps it should have been named something different like `@JsonAsRaw` or `@JsonRaw`.

So: it is simply a marker that a property should be embedded exactly as-is, presumably having been already encoded in format in question (json, xml).

Given this, code works as meant to be, although naming can imply different logic.

**Comment by aint** [comment]
@cowtowncoder Thank you for clarifying this issue. It really make sense now. 

But anyway, could you please advise me how to achieve a response with all these custom attributes? I tried to ignore all fields with `Visibility.NONE ` but this approach breaks Swagger. I would appreciate any help.

**Comment by cowtowncoder** [comment]
@aint That is odd: if there are just `private` fields and no getters, fields should not be output as properties. But perhaps something somewhere changes default visibility levels to allow even `private` fields?

So: with that class definition it should only output one property; in this case it'd be named `toString` (you can change name with `@JsonProperty`, or XML annotation equivalent).

**Comment by aint** [comment]
It just skipped all these getters and setters. 

But anyway, thank you for help and your great lib.

And finally, there is my solution for someone else  interested in this topic who stumbles upon this issue
```java
public class LegacyXmlSerializer extends JsonSerializer<Response> {
    @Override
    public void serialize(Response value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
        gen.writeRawValue(value.toString());
    }
}
```

**Comment by cowtowncoder** [comment]
@aint Ok glad it works. Based on your original report, I think I'll file a new feature request to ensure that combination of `@JsonValue` and `@JsonRawValue` either works as-is, or if not, maybe add something like new property in `@JsonValue` to allow "output as raw". Latter might make more sense.
