### ISSUE TITLE
@JsonProperty(required = true) on fields

### ISSUE THREAD

**Issue by D3v01dZA** [FasterXML/jackson-databind#1942]
I fell into the trap a couple of days ago when using a required property on field level without going through a @JsonCreator - which is the expected behaviour as specified in the JavaDoc on that field. Is there a particular reason why this isn't implemented yet, I had a look through the code and for the simple case (BeanDeserializer#vanillaDeserialize) it seems as though there could be a list/array of required properties that are run through after deserialization is done? With little knowledge of the codebase that information could be contained on the BeanPropertyMap since it seems to be the authority on what properties a bean may have?

**Comment by cowtowncoder** [comment]
For discussions and usage questions, please use mailing lists. Issue tracker is a lousy place for those.

As to requiredness, there is an existing issue, RFE, for adding that. Simple answer is that it is rather complicated to implement, esp. efficiently. It adds maintenance logic for keeping track of what has been seen (which means code and time overhead; with creators this was mostly needed anyway), and it has to be piped through `BeanDeserializer`. Problem is not that of knowing which properties are required (metadata is easy enough to access) but bookkeeping and avoiding overhead, complexity, where feature not used.
Hope is to tackle this in 3.0; conversely will not happen for 2.x.
