### ISSUE TITLE
what's the difference between 2.9 and 2.8 version

### ISSUE THREAD

**Issue by soockie** [FasterXML/jackson-databind#1943]
Sorry, if the question is stupid, pls excuse me, i am a new to use jackson components. 
So, anyone can tell me the answers?
- I  wanna know what's the difference between 2.9 and 2.8 version.
- And why released the two version series at the same time？

**Comment by cowtowncoder** [comment]
I can tell you the difference between Issue Tracker and Mailing List. Latter is for asking question like this:

https://groups.google.com/forum/#!forum/jackson-user

I am happy to answer the question there, but please do not abuse issue trackers as support forum.
