### ISSUE TITLE
progaurd

### ISSUE THREAD

**Issue by rasoolta** [FasterXML/jackson-databind#1944]
hi
when i use proguard in application i get this warning
Warning: com.example.rasoolta.instalike.instagram4android.requests.InstagramCheckUsernameRequest: can't find referenced class java.beans.ConstructorProperties
and more warning instagram4android.* can't find referenced class java.beans.ConstructorProperties

i use -ignorwarning then build app

when this app send request to instagram is forceclose

How to fix the problem

**Comment by cowtowncoder** [comment]
Please do not use issue tracker for usage questions. Even TEMPLATE THAT YOU APPARENTLY FAILED TO READ says that Usage Questions should go to

https://groups.google.com/forum/#!forum/jackson-user
