### ISSUE TITLE
Jackson adjusts date even though date format doesn't contain timezone

### ISSUE THREAD

**Issue by kst83** [FasterXML/jackson-databind#1946]
For some reason jackson adjusts the date, even though the date format doesn't contain  the timezone.
E.g.
```@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss")```

Binds a string of "2018-02-15T11:43:00" to a Date of "2018-02-15 12:43:00" on my local system.
Shouldn't jackson be neutral on the timezone if it is not explicitly provided?
Is it possible to configure the current version of jackson to follow the expected behavior (Date of "2018-02-15 11:43:00" in above case)

**Comment by cowtowncoder** [comment]
@kst83 Please note that `java.util.Date` does not contain any timezone information: it is a timestamp, and its interpretation unfortunately depends on some external information.

Aside from that, description of the issue alone is not sufficient: what is needed is a reproduction to show in code your problem.

**Comment by kst83** [comment]
The code is part of a big project and also uses Spring Integration, so I can't just post it as an example.
All I want is getting the exact same date as in the json string, ignoring any timezone information.
Is this really not possible with jackson?

**Comment by kst83** [comment]
I've seen some testing examples, so I've written a few lines in that style:
```        
        ObjectMapper mapper = new ObjectMapper();
        Date date = mapper.readValue("\"1970-01-01T00:00:00.000\"", java.util.Date.class);
```

The resulting date is 1970-01-01 01:00:00 on my system, I expected it to be 1970-01-01 00:00:00.

**Comment by cowtowncoder** [comment]
@kst83 I am not sure you quite understand my comment: value of `java.util.Date` literally do not have timezone information -- they do not "know" timezone you might want to use. There is absolutely nothing retained even if incoming String did have timezone: this timezone is used for calculations but then dropped. If you want to retain it, you are better off with Joda or Java 8 date/time values which do retain this information.

As to configuration, yes, those are the ways to force use of specific timezone for serialization.
There is third way via `ObjectMapper.configOverrides(Date.class).setFormat(....)`, which allows assigning specific formats for all instances of `Date`. But I am guessing you do want it applied to all types anyway.

**Comment by kst83** [comment]
I don't want to retain timezone information. I just want the deserialized Date to have exactly the same values as the string, completely ignoring the timezone problem.
Can configOverrides be used for deserializion too? Or is it just for serialization?

**Comment by cowtowncoder** [comment]
@kst83 That is the exact same value: value is 64-bit `long`, see `getTime()` method and verify values.

`Date` does not have specific String representation any more than timezone assignment. One can write textual representation, with formatting and timezone.

At this point I think you really need to learn more about Java Date handling -- I have given pointers that should help.

**Comment by kst83** [comment]
Somehow I get the feeling we are talking about different things.

I'm doing the following:

I execute the code above (cited here again):

```
        ObjectMapper mapper = new ObjectMapper();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
        df.setTimeZone(TimeZone.getDefault());
        mapper.setDateFormat(df);
        Date date = mapper.readValue("\"1970-01-01T00:00:00.000\"", java.util.Date.class);
```

Then I pause for debugging and point the mouse over the variable "date" to show the mouse over hint of its values. It shows that the hour of the date is set to 01 instead of the 00 written in the code.
Is this really the intended behaviour?

**Comment by cowtowncoder** [comment]
@kst83 I don't think you are listening. `java.util.Date` does not have concept of hours, minutes or any other components. It is a wrapper around 64-bit values. Your IDE may choose to construct a `Calendar` from it to try to be helpful. 

There are many cases where just printing out strings (or looking at Strings your tools show you) does not help unless you are understand what transformations are being done for you, and I find it frustrating to talk when you seem unwilling to learn about these aspects.

**Comment by kst83** [comment]
Sorry, I didn't understand that. I thought the IDE shows the internal structure of the data.
So basically even if I write a unit test that compares the deserialized Date with a Date generated by the applying the SimpleDateFormat parse function to the same String, it might be ok if they don't match up.
Guess I'll really have to look up more documentation on this topic.

**Comment by cowtowncoder** [comment]
@kst83 Right. `Date` itself only contains very specific timepoint. `Calendar` then contains parts -- or, even better, Java 8 and Joda libraries that contains "zoned" date/time values that have this information. Name `Date` is pretty misleading.

**Comment by qianlong** [comment]
Just for people who are searching the same issue and have reached this ticket, if your date is such like a birthday, and you don't care about the timezone and timestamp at all, you'd better use LocalDateTime or LocalDate instead of Date.

**Comment by fernandaa** [comment]
I had the same problem using a Date to string into my API

 I was sending in my request:
        {
        myDate: "2023-05-16T15:22"
        }

contract:
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm", timezone = "UTC")
	@ApiModelProperty(value = "Fecha", example = "yyyy-MM-dd")
	private Date myDate;

But it was changing to CST timezone, so the easy way for my was: nevermid how the json was deserialized I am using this auxiliar format to get the exactly date string of the request to without timezone:

      SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
      dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
    
      dateFormat.format(myDate) //using this wherever when I need the string date

I don't know if this is a good practice but works

**Comment by yawkat** [comment]
@fernandaa you should avoid using java.util.Date, if you were using LocalDateTime this would not be an issue.

**Comment by cowtowncoder** [comment]
@fernandaa Thank you for sharing your work-around.

One quick note: `java.util.Date` literally has no timezone associated with it: it is just a wrapper around 64-bit `long` timestamp. So nothing can change timezone of `Date` values since it has none. So it's all about how you use `Date` values (if you do; as per @yawkat it's better avoided).

**Comment by Marcono1234** [comment]
Adding to what has been said above:
The confusion here might come from the fact the even though `java.util.Date` has no timezone data, the output of `Date.toString()` uses your default timezone for displaying purposes (which is then likely also shown while debugging). But this is really only for displaying purposes; `Date.getTime()` will show you that regardless of your local default timezone the data will be the same.
Here is an example:
```java
Date date = new Date(0);

TimeZone.setDefault(TimeZone.getTimeZone("CET"));
System.out.println(date); // Thu Jan 01 01:00:00 CET 1970

TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
System.out.println(date); // Thu Jan 01 00:00:00 UTC 1970
```

So this is just another reason why, as mentioned above, you should avoid `java.util.Date` and prefer the `java.time.*` classes.

**Comment by cowtowncoder** [comment]
@Marcono1234 Exactly.
