### ISSUE TITLE
Abstract types children parsing issues - mixins?

### ISSUE THREAD

**Issue by miaaaooow** [FasterXML/jackson-databind#1950]
If this is not an "issue", please ignore it, but I am struggling for days to fix it and in vain.

**Short version:** 
Do mixins support abstract types (and can they resolve problems for children parsing)?

**Long version:**

We use generated object types from a schema via ``xcj``. Hence, **we don't have flexible control over the serialized types' definitions**. We also use JAXB annotations.

Then, we use Jackson Faster XML for deserialization of objects of the above types. Unfortunately, when we deserialize abstract classes, we get an exception:

    com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of 
    com.x.y.z.AnstractType: abstract types either need to be mapped to concrete types, 
    have custom deserializer, or contain additional type information at 
    [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@2989b3db; 
    line: 1, column: 625] (through reference chain: com.x.y.z.TypeA["type-b-prop"]->
    com.x.y.z.TypeB["type-c-prop"]->java.util.ArrayList[0]->
    com.x.y.z.TypeC["abstract-type-prop"]->java.util.ArrayList[0])

The above is solved easily for a *single* child of the abstract class by adding a mixin:

    @JsonTypeInfo(defaultImpl = ChildType.class, use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
    static class AbstractTypeMixIn {
    }
and registering it in the object mapper:

    objectMapper = new ObjectMapper();
    objectMapper.addMixIn(AbstractType.class, AbstractTypeMixIn.class);
    ...
    objectMapper.registerModule(new JaxbAnnotationModule()); 
   
This works like a charm when a single class is inheriting the abstract one. What about multiple children? Is it possible to use mxins to fix this issue? If not - what else? Is support of such functionality planned?

**Comment by cowtowncoder** [comment]
In future, please ask usage questions on mailing list:

https://groups.google.com/forum/#!forum/jackson-user

as to mixins -- they work equivalent to taking all annotations from mixin class (and its supertypes), attache them on target class/interface. If annotations from that class are used, then mixin works.
If not, they won't. No code is added from mixin-class, only annotations.

If I understand the question correctly, the answer is "yes, number of subtypes does not matter".
Jackson considers annotations hierarchically, so annotations from supertypes are visible to subtypes unless overridden.

**Comment by miaaaooow** [comment]
Thanks for taking the time to answer it. (Btw, maybe update the link from the new issue creation disclaimer message, because "search" gave me groups about "Michael Jackson". I would totally join them, but still, I think it was not the point ;))

We solved the issue finally, by extending both the request and response object mappers with mixins, adding ``@type `` for the abstract classes' subclasses.

**Comment by cowtowncoder** [comment]
@miaaaooow glad you were able to figure it out. Link to mailing lists is actually on the template for issues, for future reference, so you probably briefly saw it... :-D

**Comment by miaaaooow** [comment]
Not exactly:
    https://groups.google.com/forum/#!search/jackson-users
vs the real one:
    https://groups.google.com/forum/#!forum/jackson-user
Try the first one, it is not very informative if you don't know the list actually exists.

**Comment by cowtowncoder** [comment]
Ah. Yes, first one is not a good link, wil fix that.
