### ISSUE TITLE
`ObjectMapper.convertValue()` forces conversion to BigDecimal in 2.8.7 

### ISSUE THREAD

**Issue by ayushgp** [FasterXML/jackson-databind#1958]
I am trying to upgrade Jackson to 2.8.7 from 2.6.1. I am encountering the following issue. When I use an `ObjectMapper.convertValue` to convert a `Object` to map in 2.6.1 with values earlier used to return `Double` for `BigDecimal` values as well. This behaviour changed for 2.8.7, as in this case it is forced converted to a `BigDecimal`. 

I tried disabling the `DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS` but its not working for me. Not really sure how to proceed with this as sticking to `BigDecimal` will cause breaking changes across many modules. 

Thanks!

**Comment by cowtowncoder** [comment]
I would need a test case to show exactly what is happening and what you would expect to happen instead. I do not doubt there is a problem, but I have learnt that if I try to write test case from description there's about 50% chance I miss something. :)

**Comment by ayushgp** [comment]
A project I'm working on has this issue. When I tried extracting this code, it works fine. Sorry for the trouble, should've looked deeper and tested a smaller code with it. 

But I still do have a question. Somehow the code I'm working on has the `ObjectMapper.convertValues` convert the `BigDecimal` values to `Double`s in version2.6.1 and when I upgrade it to 2.8.7 it resorts to keeping bigdecimals as bigdecimals. How can I keep the old behaviour using some config? Maybe somehow using the `JsonNodeFactory`?

**Comment by cowtowncoder** [comment]
@ayushgp I don't know how that should happen: it sounds like 2.6 had a flaw in design as ideally the intent is to retain representations, and in particular not lose potential accuracy or magnitude by coercing from `BigDecimal` to `Double`.
