### ISSUE TITLE
Empty javadoc JARs on Maven for jackson-databind 2.9.2, 2.9.3 and 2.9.4

### ISSUE THREAD

**Issue by cromoteca** [FasterXML/jackson-databind#1960]
`jackson-databind-2.9.1-javadoc.jar` has size 4962109. After that, size drops to a few kilobytes.

See http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.1/ and subsequents

**Comment by cowtowncoder** [comment]
Hmmh. Ok, thank you for reporting. Not sure what changed there; will need to see what went wrong, and why javadoc task failure (assuming that's it) did not stop the process.

**Comment by cowtowncoder** [comment]
I _think_ I figured this out; was related to problems with lint settings from parent poms: setting only available for Java 8, but that did NOT prevent Maven build somehow (as part of maven release plugin).
Anyway, should be back working now.
