### ISSUE TITLE
Jackson Custom Naming Conventions Link Broken

### ISSUE THREAD

**Issue by ipropper** [FasterXML/jackson-databind#1963]
I think these links are broken?

https://github.com/FasterXML/jackson-databind/wiki/JacksonCustomNamingConvention
https://github.com/FasterXML/jackson-databind/wiki/JacksonMixinAnnotations
https://github.com/FasterXML/jackson-databind/wiki/JacksonTreeModel

They don't have any documentation

**Comment by cowtowncoder** [comment]
These were auto-created/-migrated from older wiki. Will delete empty ones.
