### ISSUE TITLE
Provide JsonParser.readAsValue(ResolvedType)

### ISSUE THREAD

**Issue by krichter722** [FasterXML/jackson-databind#1966]
Since `JsonParser.readAsValue(Class)` and `readAsValue(TypeReference)` delegate to `ObjectCodec.readValue(JsonParser, Class/TypeReference)` this should be not a problem to implement. This would solve issues with runtime type erasure like [this one described at stackoverflow.com](https://stackoverflow.com/questions/49213606/bypass-runtime-type-erasure-for-generic-map-serializer).

I wanted to get started on this feature, but can't because of #1965 .

**Comment by cowtowncoder** [comment]
Moved to https://github.com/FasterXML/jackson-core/issues/456 -- I implemented this earlier; makes sense.
