### ISSUE TITLE
Why not set the default DeserializationConfig to DeserializationContext in the constructor of ObjectMapper?

### ISSUE THREAD

**Issue by ajoezhou** [FasterXML/jackson-databind#1969]
It always get NullPointerException when call some methods like ObjectMapper.findRootValueDeserializer before call ObjectMapper.readValue.
It would be convenient for me if it can link the java type to Serializer/Deserializer and cache it before the reading/writing.

```
ObjectMapper om = new ObjectMapper();
JavaType mapType = TypeFactory.defaultInstance().constructMapType(MyMapClass.class, String.class, Object.class);
DeserializationContext ctxt = om.getDeserializationContext();
JsonDeserializer<Object> myTypeDeserializer = ctxt.findRootValueDeserializer(mapType);  // NullPointerException 
```

**Comment by cowtowncoder** [comment]
Do not use `DeserializatonContext`: it is not for application code to try to get. That's not what it is for. It must be provided by mapper, properly initialized for the operation (readValue).
And specifically, you should not try to access deserializers or serializers that way.

**Comment by ajoezhou** [comment]
Thank you very much for your reply.
So those public methods are not for application use, hope  these would be hided by

1. Access level modifiers like protected or package-private
2. Or module system of Java 9

**Comment by cowtowncoder** [comment]
It would be great if there was a good mechanism to make it easier to hide access. This is not always easy to do with Java as there is no good mechanism for hiding dependencies. Java 9, in particular, can not be used for foreseeable future as project does not require use of Java 9.

But I fully agree in that it is good to work hard to avoid exposing things that "have no user-serviceable parts" to users.
