### ISSUE TITLE
JaxbAnnotationIntrospector ignores @XmlJavaTypeAdapter to setter Serializable type

### ISSUE THREAD

**Issue by christianocarrilho** [FasterXML/jackson-databind#1971]
Olá bom dia! Sorry ... english is not my language

Estou tentando fazer funcionar um projeto Web com Jersey 2.x com suporte a Json usando Jaxb-Jackson.
Estou mandando em anexo o projeto de laboratório que fiz para exemplificar o problema.
De forma resumida está acontecendo o seguinte:

- Por necessidade, tenho uma classe que tem um atributo do tipo Long mas seu método setter é passado como Serializable. Fiz um adapter para converter o valor para Long. Configurei o servidor Jersey para utilizar o Jackson com Jaxb. Porém quando vou consumir meu RESTful Resource dá erro na deserialização do valor. Fiz uma modificação no método JaxbAnnotationIntrospector.checkAdapter invertendo o teste if (adaptedType.isAssignableFrom(typeNeeded)) para if (typeNeeded.isAssignableFrom(adaptedType)) e funcionou, mas do contrário como está implementado o teste de Long.isAssignableFrom(Serializable) dá falso e o adapter não é carregado. Isto pode ser considerado um bug ou está faltando alguma configuração que não fiz?

- Estou utilizando servidor JavaEE Payara 174 com Java 8_161.

Obrigado.
[jaxb-jersey.zip](https://github.com/FasterXML/jackson-databind/files/1816043/jaxb-jersey.zip)

**Comment by cowtowncoder** [comment]
Jackson JAXB annotation introspctor bugs should go in:

https://github.com/FasterXML/jackson-modules-base/issues

but I hope reproduction does not rely on Jersey.
