### ISSUE TITLE
The property named "aType" is serialized to "atype".

### ISSUE THREAD

**Issue by jearton** [FasterXML/jackson-databind#1975]
## Code for demo:
```java
@Data
public class DemoBean {

    private String aType;

    private String aaType;

    public static void main(String[] args) throws JsonProcessingException {
        DemoBean bean = new DemoBean();
        System.out.println(new ObjectMapper().writeValueAsString(bean));
    }
}
```

## Expected output: 
```
{"aaType":null,"aType":null}
```

## Actual output: 
```
{"aaType":null,"atype":null}
```

**Comment by cowtowncoder** [comment]
This is not enough to reproduce the problem. From annotation `@Data` I suspect you might be using something like Lombok? If so, a reproduction without Lombok dependency would be required -- it is ok to use equivalent set of annotations, or whatever is needed, but Lombok dependency itself can not be used (for a few reasons).
(note: use of Lombok in code should be fine, we just do not debug processing outside of Jackson, done by other frameworks, except in cases where there is explicit jackson module that adds support, and this is not the case here)

**Comment by jearton** [comment]
My mistake! It is a bug of Lombok. The getter method of 'aType'  should be 'getaType()'，but Lombok generates it into 'getAType()'.
