### ISSUE TITLE
Using @JsonUnwrapped annotation in builderdeserializer hangs in infinite loop

### ISSUE THREAD

**Issue by roeltje25** [FasterXML/jackson-databind#1978]
We are using a builder to deserialize a bean and one of the properties is annotated with a @JsonUnwrapped annotation. The code hangs in BuilderBasedDeserializer.java in method deserializeWithObject in the loop starting on line 307. The code of that loop differs significantly from the code i see in master where the loop starts on line 340. The 2.9.4 version of the loop that I am using hangs as there seems to be no end token. p.nextToken() returns null indicating the last token was consumed but this value is not checked making the loop stuck for eternity... 

I guess the code in master improves on the behavior in the 2.9 branch. Perhaps this should be merged to 2.9?

Thanks in advance for any fix.

**Comment by cowtowncoder** [comment]
Master is for Jackson 3.0, so simple merging is probably not possible.
But if you have a simple reproduction I could definitely improve handling is applicable.
Test would obviously be valuable against regressions, and is not covered currently (as per your seeing the problem).

**Comment by roeltje25** [comment]
Ok.

So I worked a bit to get a minimalistic example. It seems the crucial part is combining:
* JsonUnwrapped(prefix)
* Property based creator in builder

Please find attached a zip with all needed files. run the Processor class and it will hang infinitely.

If somebody would let me know how to import databind in eclipse I would have tried to get it into a junit test, but this should illustrate the issue. @
[issue-1978-testcase.zip](https://github.com/FasterXML/jackson-databind/files/1837803/issue-1978-testcase.zip)

**Comment by cowtowncoder** [comment]
Thank you! I hope to add changes for 2.9.5, sounds like a nasty situation and best avoided :)

**Comment by roeltje25** [comment]
Well, the thing is we have a data model which has to be reconciled with
many different data files, in json, xml and csv formats with difderent
fields. New external formats for import are added regularly.... This leads
us to use the mixins + builders setup to minimize the effort to create a
new interface.

Thanks for the effort!



Op do 22 mrt. 2018 20:44 schreef Tatu Saloranta <notifications@github.com>:

**Comment by cowtowncoder** [comment]
@roeltje25 What I meant by "best avoided" was reference to infinite-loop occurring, not configuration that (currently) triggers it. Just in case that was ambiguous. So even if there was configuration that couldn't work, it should be signaled with better mechanism.

**Comment by cowtowncoder** [comment]
Changed to prevent infinite loop, but I think this is just a side-effect, so created #1979 for hopefully figuring that out. I think buffering is either missing `JsonToken.END_OBJECT`, or possibly something is advancing tokens incorrectly.
But first things first.
