### ISSUE TITLE
Change `Locale` handling to use static methods `toLanguageTag()` and `forLanguageTag`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#1982]
(note: follow up for #1948)

It seems that static methods of `Locale`:

* `toLanguageTag()` (for serialization)
* `forLanguageTag(String)` (for deserialization)

would work better than existing logic, so let's see if we can use those.

Since this is potentially breaking change, regarding backwards compatibility, it can not go in a patch version (2.9.x), but needs to go in 3.0.

**Comment by cowtowncoder** [comment]
Hmmh. Ok, trouble.

On plus side, serialization already uses `toLanguageTag()`: no change needed.

On downside, `forLanguageTag()` does NOT accept underscore at all, it seems, just hyphen.
So it is not really an improvement.

Not sure if there is anything to do... back to the old drawing board.

**Comment by cowtowncoder** [comment]
Have to shelve for now.

**Comment by takeseem** [comment]
I hope you can support, because of our app and server are use Java's System and use Jackson json protocol.
