### ISSUE TITLE
ObjectMapper not able to parse an Integer correctly from a DataInput

### ISSUE THREAD

**Issue by vietj** [FasterXML/jackson-databind#1985]
The following code produces an `EOFException`

```
mapper.readValue((DataInput) new DataInputStream(new ByteArrayInputStream("42".getBytes())), Integer.class);
```

unlike

```
mapper.readValue(new ByteArrayInputStream("42".getBytes()), Integer.class)
```

**Comment by cowtowncoder** [comment]
Unfortunately there is no way to resolve this because `DataInput` has no mechanism for reliably detecting end of input.

What you may want to do is to append a white-space after content as this will allow decoding to determine boundary and return value.
