### ISSUE TITLE
`MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUM` does not work for `Enum` keys of `Map`

### ISSUE THREAD

**Issue by Myp3ik** [FasterXML/jackson-databind#1988]
Using 2.9.5 version libraries.
Works on simple fields, but no on the keys of the map.
Example:
```
public class Test {
    public void test() throws IOException {
        String value = "{" +
                "  \"Works\" : 1," +
                "  \"SomeMap\" : {" +
                "    \"One\" : 1," +
                "    \"Two\" : 2 +
                "  }" +
                "}";
        ObjectMapper mapper = new ObjectMapper();
        mapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);
        mapper.readValue(value, A.class);
    }
}

class A {
    @JsonProperty
    private Integer works;
    @JsonProperty
    private Map<MyEnum, Integer> someMap;
}

enum MyEnum {
    @JsonProperty("one") ONE,
    @JsonProperty("two") TWO
}
```

Two fields are successfully deserialized:  "works" and "someMap", but insides of a map are not.

> 
> com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `com.test.MyEnum` from String "One": not a valid representation, problem: (com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type `com.test.MyEnum` from String "One": not one of values excepted for Enum class: [one, two]
>  at [Source: (String)"{  "Works" : "",  "SomeMap" : {    "One" : "",    "Two" : ""  }
> }"; line: 1, column: 36]
>  at [Source: (String)"{  "Works" : "",  "SomeMap" : {    "One" : "",    "Two" : ""  }
> }"; line: 1, column: 36] (through reference chain: com.test.A["SomeMap"])
>

**Comment by cowtowncoder** [comment]
Ok. So basically case-insensitivity does not work for Map keys that are `Enum`s.

**Comment by Myp3ik** [comment]
Yes, sorry about that.

**Comment by XakepSDK** [comment]
Aliases also doesn't work.

**Comment by cowtowncoder** [comment]
@XakepSDK if there is another problem with case-sensitivity, please file another issue, with example (it does sound straight-forward but just in case).

**Comment by XakepSDK** [comment]
@cowtowncoder `JsonAlias` doesn't work for enum values, when these values are map keys. Should i fill another issue?

**Comment by tyrantkhan** [comment]
@cowtowncoder 
I can confirm that use of @JsonAlias now works for enum values (even in Maps), but the issue originally reported in this ticket (ACCEPT_CASE_INSENSITIVE_PROPERTIES) still does not work for enum values inside Maps. 

Let me know if a separate feature request ticket is necessary -- or if we can continue to utilize this ticket for that. 

Thanks.

I've tested the following code on the latest version of jackson:

```
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.util.Map;

public class EnumIgnoreCaseMapTest {
  static class FooHolder {

    enum TestEnum {
      FOO_BAR,
      FOO_BAZ
    }

    Map<TestEnum, Number> holder;
    TestEnum holder2;

    public Map<TestEnum, Number> getHolder() {
      return this.holder;
    }

    public void setHolder(Map<TestEnum, Number> holder) {
      this.holder = holder;
    }

    public TestEnum getHolder2() {
      return this.holder2;
    }

    public void setHolder2(TestEnum holder2) {
      this.holder2 = holder2;
    }


  }


  public static void main(String[] args) throws IOException {
    ObjectMapper objectMapper = new ObjectMapper()
        .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
        .enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS)
        .enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES)
        .enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES)
        .enable(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT);

    String json = "{\"holder\":{\"foo_bar\": \"4\"}}";
    String json2 = "{\"holder2\":\"foo_bar\"}";
    FooHolder foo2 = objectMapper.readValue(json2, FooHolder.class);
    FooHolder foo = objectMapper.readValue(json, FooHolder.class);
    String goop = "goo";
  }
}
```
