### ISSUE TITLE
serialization feature: sort scalars first

### ISSUE THREAD

**Issue by elreydetodo** [FasterXML/jackson-databind#1989]
I have found that reading JSON objects (as a person) is much easier if the scalar values (numbers, strings, booleans) are serialized _before_ any array or object members. The reason is that arrays and sub-objects can have arbitrary size when pretty-printed, and that just makes it harder to figure out what location I'm looking at in the object. Depth gets hard to gauge the more levels deep the object gets. The tech writing group at my company has actually started formatting our code samples this way prior to public publishing.

I'd really like to have a serialization feature `MapperFeature.SORT_SCALARS_FIRST` so the object mapper can do this automatically for me without having to manually list the order of all the members (i.e. without using `@JsonPropertyOrder`). I would probably combine it with `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` in practice, so ideally don't make them incompatible. It would be very nice if `@JsonPropertyOrder` could have an attribute added to trigger this feature like it does for alphabetical sorting.

For example:
```
{
    "foo": "bar",
    "otherField": 123,
    "someField": true,
    "alpha": [
        "foo": true
    ],
    "extra": {
        "a": b"
    }
}
```

In that example, the scalar fields at the top are alpha-sorted, and the non-scalar fields below are also alpha-sorted.

Note that there is a similar ask in the comments of #518 to be able to use `@JsonPropertyOrder` to specify final properties in addition to final ones.

**Comment by cowtowncoder** [comment]
Thank you for suggestion.

I think this is something you will probably have to implement via `BeanSerializerModifier`, which gets callback `orderProperties()` that is meant to allow custom ordering.

One thing that could perhaps work from databind end would be ability to register custom strategies for sorting. That would have to be for 3.x.

**Comment by cowtowncoder** [comment]
I don't think there are any plans to implement something like this, as first-class feature (vs. ability to plug in `BeanSerialializerModifier` which may reorder properties as it sees fit). Closing.
