### ISSUE TITLE
XSD file defined an enum with a space in it.  EnumResolver cannot resolve.

### ISSUE THREAD

**Issue by windbender** [FasterXML/jackson-databind#1996]
I use xjc to generate a java enum from the following XSD ( and it's linked sub xsd's )

XSD:
https://graphical.weather.gov/xml/DWMLgen/schema/DWML.xsd

Specifically the generated enum ends up being:

```
@XmlType(name = "srsNameType")
@XmlEnum
public enum SrsNameType {

    @XmlEnumValue("WGS 1984")
    WGS_1984("WGS 1984");
    private final String value;

    SrsNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SrsNameType fromValue(String v) {
        for (SrsNameType c: SrsNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
```

So this Enum has name:"WGS_1984"  (note underscore)  while it has value "WGS 1984"

It appears as there may be some confusion between "name" and "value" within

EnumResolver.constructFor()

such that it cannot resolve this enum when given "WGS 1984" because enum resolver has everything in the map stored as "WGS_1984" as though it was coded to name and not value.

changing  DeserializationFeature.READ_ENUMS_USING_TO_STRING appears to have no effect.

Code to cause problem:

```
package com.example;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.ResponseHandler;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;

import java.io.IOException;

public class NWSSkyCoverClient {

    public static void main(String[] args) {
        try {
            NWSSkyCoverClient c = new NWSSkyCoverClient();
            c.getForecast(38.99,-77.01);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public void getForecast(double lat, double lon) throws IOException {
        CloseableHttpClient httpclient = HttpClients.createDefault();
        try {
            HttpGet httpget = new HttpGet("https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdXMLclient.php?lat="+lat+"&lon="+lon+"&product=time-series&sky=sky");

            System.out.println("Executing request " + httpget.getRequestLine());

            // Create a custom response handler
            ResponseHandler<String> responseHandler = new ResponseHandler<String>() {

                @Override
                public String handleResponse(
                        final HttpResponse response) throws ClientProtocolException, IOException {
                    int status = response.getStatusLine().getStatusCode();
                    if (status >= 200 && status < 300) {
                        HttpEntity entity = response.getEntity();
                        return entity != null ? EntityUtils.toString(entity) : null;
                    } else {
                        throw new ClientProtocolException("Unexpected response status: " + status);
                    }
                }

            };
            String responseBody = httpclient.execute(httpget, responseHandler);
            XmlMapper xmlMapper = new XmlMapper();
            xmlMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
//            xmlMapper.enable(DeserializationFeature.READ_ENUMS_USING_TO_STRING);

            generated.Dwml value = xmlMapper.readValue(responseBody,generated.Dwml.class);
            System.out.println(value);
            System.out.println(responseBody);
        } finally {
            httpclient.close();
        }
    }
}

```

**Comment by cowtowncoder** [comment]
Thank you for reporting this. XSD is not part of the immediate problem (as Jackson doesn't use it), but sounds like there is some sort of disconnect.

One thing here is that reproduction is not quite valid since it uses another service to create XML, and that does not necessarily mean flaw -- test needs to either include exact XML to map against, or use Jackson for both writing and reading XML. Round-tripping is what is guaranteed, not necessarily compatibility with other frameworks.
Still, it sounds like there could be a problem with enum name handling. Could even be a problem with JAXB annotations module.

**Comment by windbender** [comment]
Yeah, I only bring it up because something that is "valid" XSD  becomes a nonfunctional  XML parser.  I believe that the generated class does the right thing since you can see the correct (per XSD ) enum value.   The problem is that EnumResolver doesn't connect that value up properly.  I'm hoping an expert on this class can evaluate.  It seemed to me that there wasn't a lot of variable naming clarity in that class since I saw places where "values" were assigned to "names".

It may also be that the class IS correct, but perhaps there needs to be a new DeserializationFeature which knows how to properly handle this corner case.

**Comment by cowtowncoder** [comment]
@windbender right, and it's good background information too.

But one problem you have is that you are not registering JAXB Annotations module. Jackson does not automatically use JAXB annotations, but you can enabled support via `jackson-module-jaxb-annotations`. Some frameworks include that by default.
So in your test, `@XmlEnumValue` is not recognized and hence alternate name not considered.

Also: this issue would actually belong in `jackson-dataformat-xml` (or if proven to be due to JAXBAnnotationINtrospector, under `jackson-modules-base`). But let's first see if adding introspector solves the issue.

**Comment by windbender** [comment]
And behold, adding:
```
+             xmlMapper.registerModule(new JaxbAnnotationModule());
````
allowed the whole thing to get further!   Thanks.

Now we're off topic (according to the title above) I'm finding that this chunk of the XML:

```
 <production-center>Meteorological Development Laboratory<sub-center>Product Generation Branch</sub-center></production-center>
```

throws exception:

```
java.io.IOException: Expected END_ELEMENT, got event of type 1
	at com.fasterxml.jackson.dataformat.xml.deser.XmlTokenStream.skipEndElement(XmlTokenStream.java:180)
	at com.fasterxml.jackson.dataformat.xml.deser.FromXmlParser.nextToken(FromXmlParser.java:558)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:271)
...
```

the XSD for that is:

```
    <xsd:complexType name="production-centerType" mixed="true">
       <xsd:sequence>
          <xsd:element name="sub-center" type="xsd:string" minOccurs="0" maxOccurs="1" />
       </xsd:sequence>
    </xsd:complexType>
```

So here we have a problem where the xsd indicates mixed="true"  and the resulting java class is annotated with @XmlMixed, but for some reason it won't deserialize.  ideas ?

**Comment by cowtowncoder** [comment]
@windbender Mixed content is not support by XML module. So that will not really work.

However, Exception is not very useful and should probably indicate the issue better.
Do you have class used for that part of code? I would like to at least improve error messaging -- lack of support for mixed content is a known issue and I think there should be another issue filed for that
(regardless of whether it might ever be supported or not, never say never).

**Comment by windbender** [comment]
Also, in my case, I'd be happy with some sort of a non-terminal warning.  So if the system optionally continue in this situation and NOT parsing the text bit in the "mixed" content that would totally work for me. (  DeserializationFeature.continue_on_xmlmixed )

**Comment by cowtowncoder** [comment]
@windbender Problem is not so much not having annotation or such, but that there isn't any natural mapping from that kind of XML infoset into Java POJOs. So introducing concept is one thing, and then figuring out how that'd map to object is another.

It is of course possible to build additional extra constructs to hold and/or expose such text, but I suspect is that when mixed content has significant structural meaning, it may be time to use XML-centric tools... but that's just my opinion.
