### ISSUE TITLE
"Duplicate property" issue should mention which class it complains about

### ISSUE THREAD

**Issue by OndraZizka** [FasterXML/jackson-databind#1999]
When Jackson 2.9.5 complains about "duplicate property", it does give no reference to the specific class.
If you have hundreds of generated models, it's quite tedious to find out.
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
Duplicate creator property "id" (index 0 vs 1)
 at [Source: (String)"{
  "description": "patched description"}"; line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionExc
```
I assume it happens with other errors too, at least I found in forums: "Could not find creator property with name 'id'" and some more.

Btw, it started with version 2.9.2 - it did not complain before (I assume that was a bug).

Source: 
https://github.com/FasterXML/jackson-databind/blob/f42b0dcf247b3abeab77a785548a4e7e6500909b/src/main/java/com/fasterxml/jackson/databind/deser/impl/CreatorCollector.java

**Comment by cowtowncoder** [comment]
Not catching the problem is likely a flaw that was fixed, yes.

It would be great to improve error message here, and I hope to have time to look into this.
One challenge is that sometimes not enough information is included: but I hope this is not the case here. Another smaller concern is that changing exception messages is a (minor) change of observed API (in a way), and can theoretically break existing code if it assumes rigid message to match.

But first things first: checking if information is available; would seem likely it is for class.

**Comment by cowtowncoder** [comment]
@OndraZizka I know you mentioned actual code that triggers this somewhere but would it be possible to have sample code here too? I'd like to reproduce the problem in a unit test.

**Comment by OndraZizka** [comment]
Sure, for instance, below.
The relevant bits are
```
    @AllArgsConstructor
    ...
       @JsonIgnore Long id;
       @JsonProperty("id") String roomUid;
```

Full class:
```
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.joda.ser.DateTimeSerializer;
import lombok.*;
import lombok.experimental.FieldDefaults;
import org.joda.time.DateTime;

import java.util.List;

@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "opened",
        "closed",
        "attendees"
})
public class RoomDto {

    @JsonIgnore
    Long id;
    @JsonProperty("id")
    String roomUid;

    @JsonProperty("opened")
    @JsonSerialize(using = DateTimeSerializer.class)
    DateTime opened;
    @JsonProperty("closed")
    @JsonSerialize(using = DateTimeSerializer.class)
    DateTime closed;
    @JsonProperty("attendees")
    List<LegacyAttendeeDto> attendees;
}
```

**Comment by OndraZizka** [comment]
I think we use default ObjectMapper but if it didn't show up, I'll check if there's some special config in effect.

**Comment by cowtowncoder** [comment]
@OndraZizka Thank you. 

Unfortunately I don't think I can yet reproduce the problem as constructors are missing, along with annotations. Anything related to Lombok has to be expanded as no tests can rely on Lombok (it is one of dependencies I explicitly rule out), so result of its class processing need to be expanded, to the degree they are relevant. In this case I think it may add `@ConstructorProperties` annotation at least, as well as setters/getters.

But I think I may be able to add implied annotations and constructor.

**Comment by OndraZizka** [comment]
Here you go. This is what IDEA Lombok plugin's "delombok" produces:

```
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.joda.ser.DateTimeSerializer;
import java.util.List;
import lombok.AccessLevel;
import lombok.experimental.Accessors;
import lombok.experimental.FieldDefaults;
import org.joda.time.DateTime;

@Accessors(chain = true)
@FieldDefaults(level = AccessLevel.PRIVATE)
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "opened",
        "closed",
        "attendees"
})
public class RoomDto {

    @JsonIgnore
    Long id;
    @JsonProperty("id")
    String roomUid;
    @JsonProperty("opened")
    @JsonSerialize(using = DateTimeSerializer.class)
    DateTime opened;
    @JsonProperty("closed")
    @JsonSerialize(using = DateTimeSerializer.class)
    DateTime closed;
    @JsonProperty("attendees")
    List<LegacyAttendeeDto> attendees;

    public RoomDto()
    {
    }

    public Long getId()
    {
        return this.id;
    }

    public String getRoomUid()
    {
        return this.roomUid;
    }

    public DateTime getOpened()
    {
        return this.opened;
    }

    public DateTime getClosed()
    {
        return this.closed;
    }

    public List<LegacyAttendeeDto> getAttendees()
    {
        return this.attendees;
    }

    public RoomDto setId(Long id)
    {
        this.id = id;
        return this;
    }

    public RoomDto setRoomUid(String roomUid)
    {
        this.roomUid = roomUid;
        return this;
    }

    public RoomDto setOpened(DateTime opened)
    {
        this.opened = opened;
        return this;
    }

    public RoomDto setClosed(DateTime closed)
    {
        this.closed = closed;
        return this;
    }

    public RoomDto setAttendees(List<LegacyAttendeeDto> attendees)
    {
        this.attendees = attendees;
        return this;
    }
}
```

**Comment by cowtowncoder** [comment]
@OndraZizka thank you. I hope to spend time on this today, will let you know if I can repro it on my own.
