### ISSUE TITLE
Deserialization issue with `@JsonIgnore` and `@JsonCreator` + `@JsonProperty` for same property name

### ISSUE THREAD

**Issue by jskierbi** [FasterXML/jackson-databind#2001]
Issue originally found on jackson-module-kotlin: https://github.com/FasterXML/jackson-module-kotlin/issues/124. Issue reproducible with Java code.

Entity class:
```java
static public class Foo {
  @JsonIgnore 
  public String query;

  @JsonCreator
  @ConstructorProperties("rawQuery")
  public Foo(@JsonProperty("query") String rawQuery) {
    query = rawQuery;
  }
}
```

Fails this test:
```java
Foo deserialized = new ObjectMapper().readValue("{\"query\": \"bar\"}", Foo.class);
assertEquals("bar", deserialized.query);
```

**Comment by cowtowncoder** [comment]
One quick note: example is ambiguous, and I wonder if it should fail -- first constructor is given two different names ("rawQuery", "query"), and it is not clear as to which one should be used.
It would be possible to think of "query" as being more specific, being on parameter, whereas "rawQuery" is associated with constructor itself.

So maybe it's just matter of clarifying that this is indeed the proper annotation precedence...

**Comment by jskierbi** [comment]
That is my thinking. Exact same behaviour without additional ctor props annotation is triggered in Kotlin: ```data class Foo(@JsonProperty("query") rawQuery: String)``` (with jackson-module-kotlin) - I would expect "query" to have precedence over ctor parameter name

Actual behaviour is here: https://github.com/FasterXML/jackson-databind/blob/f350b20fe087a7b93640c011249a39d1f0ecee2f/src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java#L481-L482

Named ctor param name is reported as implicit property name, thus property initially gets "rawQuery" name upon discovery, then is renamed to "query" in rename phase. When same property exists in the class with `@JsonIgnore` annotation, "query" property gets into ignored, then rename phase changes "rawQuery" property into "query", but originally ignored "query" stays in the ignored. My idea is to unignore new name of property during rename phase.

What do you think?

**Comment by cowtowncoder** [comment]
@jskierbi In case of constructor parameter/argument this is fully defined since that is consider "implicit" name, similar to name detected from "getX()": explicit annotation does have precedence.
Same is not as clear between annotations (for example, if same accessor has both `@JsonIgnore` and `@JsonProperty`, which one wins? Ignoral, I think, but that's judgment call).
However, coupled with "closer" scope I could see how it can be resolved.
