### ISSUE TITLE
Multiple naming strategies for deserialization

### ISSUE THREAD

**Issue by gotson** [FasterXML/jackson-databind#2006]
I am using Jackson ObjectMapper in the context of a Spring application, where the mapper is injected, and dealing with various JSONs from AWS.

The problem with AWS' JSONs is that [they don't follow the same naming convention](https://docs.aws.amazon.com/lambda/latest/dg/eventsources.html).
Some are using UpperCamelCase, while others are using kebab-case.

I know the ObjectMapper supports different naming strategies, however i can't find a way to use multiple strategies at the same time for deserialization only (we need only one for serialization, of course).

Is there a way to configure the ObjectMapper to handle multiple naming strategies for deserialization?

**Comment by cowtowncoder** [comment]
First of all: as instructions SPECIFICALLY mention, this is issue tracker, not a Q&A forum.
In future please use mailing lists for questions.

That said...
One way that allows that is to use `@JsonNaming` annotation for classes, instead of (or in addition to) default setting. Since all annotation discovery happens through `AnnotationIntrospector.findNamingStrategy()`, it is also possible to implement custom introspector (often sub-type of `JacksonAnnotationIntrospector`) to use alternate logic: use of annotations is not required.

Hope this helps.

**Comment by gotson** [comment]
Sorry about posting here, i'll pay attention next time (and the site is blocked by my corporate proxy also).

Thanks for the details, however this doesn't help when deserializing into classes I don't own and cannot modify.

Wouldn't it be possible to enhance the ObjectMapper to use various naming strategies, and try them in order until finding one that works ?

**Comment by cowtowncoder** [comment]
@gotson No, that's not how naming strategies work. They are not used dynamically when binding but only when serializer/deserializer is constructed, working on implicit pojo property name. As such there must be one-to-one correspondence between external name and pojo name.

As to modifying value classes: this is not necessary when overriding `AnnotationIntrospector` as I suggested. Or, alternatively, by using mix-in annotations which may be attached to any type.

**Comment by gotson** [comment]
@cowtowncoder thanks for the details, now i get what you were saying and managed to do what i wanted with MixIns

**Comment by cowtowncoder** [comment]
@gotson Ok excellent. I realize it is not easy to know internal limitations from outside, and I can relate to complexities of data structures with mismatched naming conventions. So it's good you were able to resolve the problem using facilities that are available.

**Comment by Praytic** [comment]
@gotson I'm very curious how you've done this with mix-ins. Do you mind to share an example?

**Comment by amidukr** [comment]
> @gotson I'm very curious how you've done this with mix-ins. Do you mind to share an example?

I guess he made something like this: https://www.tutorialspoint.com/jackson_annotations/jackson_annotations_mixin.htm#

It would work if no way to put annotations on existing class in some third party library.

**Comment by MikkelHJuul** [comment]
I've been spending some time on this recently, because I wanted to mirror a spring-like lenient approach to naming conventions when deserializing. That is naming convention is not stable; any convention is acceptable.

It's not a simple thing because the internals use type checks. And the API does not even support injection directly, here's what I found.

```
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.cfg.MapperConfig;
import com.fasterxml.jackson.databind.deser.*;

import java.util.ArrayList;
import java.util.List;

public final class WithAliasesDelegate implements ValueInstantiators {

    private static final PropertyNamingStrategies.NamingBase[] strategies =
        new PropertyNamingStrategies.NamingBase[] {
            (PropertyNamingStrategies.NamingBase) PropertyNamingStrategies.KEBAB_CASE,
            (PropertyNamingStrategies.NamingBase) PropertyNamingStrategies.SNAKE_CASE,
            (PropertyNamingStrategies.NamingBase) PropertyNamingStrategies.UPPER_SNAKE_CASE,
            (PropertyNamingStrategies.NamingBase) PropertyNamingStrategies.UPPER_CAMEL_CASE,
            (PropertyNamingStrategies.NamingBase) PropertyNamingStrategies.LOWER_CAMEL_CASE
    };

    @Override
    public ValueInstantiator findValueInstantiator(DeserializationConfig config, BeanDescription beanDesc, ValueInstantiator defaultInstantiator) {
        return new Inner(defaultInstantiator);
    }

    private final static class Inner extends ValueInstantiator.Delegating {
        Inner(ValueInstantiator delegate) {
            super(delegate);
        }

        // inject aliases onto SettableBeanProperty
        @Override
        public SettableBeanProperty[] getFromObjectArguments(DeserializationConfig config) {
            var propsFromDelegate = super.getFromObjectArguments(config);
            var finalProps = new ArrayList<SettableBeanProperty>();
            for (var prop : propsFromDelegate) {
                var aliases = new ArrayList<PropertyName>();
                for (var strat: strategies) {
                    var alias = strat.translate(prop.getName());
                    if (!alias.equals(prop.getName())) {
                        aliases.add(new PropertyName(alias));
                    }
                }
                if (!aliases.isEmpty()) {
                    if (prop instanceof CreatorProperty cp)
                        finalProps.add(new CreatorPropDelegateWithAliases(cp, aliases));
                } else
                    finalProps.add(prop);
            }
            return finalProps.toArray(SettableBeanProperty[]::new);
        }

    }

    /**
     * This must extend CreatorProperty, and all its with-er methods overwritten to make sure they still return the implementation that has an alias
     */
    private static final class CreatorPropDelegateWithAliases extends CreatorProperty {

        private final List<PropertyName> aliases;


        protected CreatorPropDelegateWithAliases(CreatorProperty src, List<PropertyName> aliases) {
            super(src, src.getFullName());
            this.aliases = aliases;
        }

        protected CreatorPropDelegateWithAliases(CreatorPropDelegateWithAliases src, PropertyName name) {
            super(src, name);
            this.aliases = src.aliases;
        }

        public CreatorPropDelegateWithAliases(CreatorPropDelegateWithAliases creatorPropDelegateWithAliases, JsonDeserializer<?> deser, NullValueProvider nvp) {
            super(creatorPropDelegateWithAliases, deser, nvp);
            this.aliases = creatorPropDelegateWithAliases.aliases;
        }

        @Override
        public List<PropertyName> findAliases(MapperConfig<?> config) {
            var parent = super.findAliases(config);
            var all = new ArrayList<>(aliases);
            all.addAll(parent);
            return all;
        }

        /**
         * have to implement all with-er methods
         * @param newName Name to use for the new instance.
         */
        @Override
        public SettableBeanProperty withName(PropertyName newName) {
            return new CreatorPropDelegateWithAliases(this, newName);
        }

        @Override
        public SettableBeanProperty withValueDeserializer(JsonDeserializer<?> deser) {
            if (_valueDeserializer == deser) {
                return this;
            }
            NullValueProvider nvp = (_valueDeserializer == _nullProvider) ? deser : _nullProvider;
            return new CreatorPropDelegateWithAliases(this, deser, nvp);
        }

        @Override
        public SettableBeanProperty withNullProvider(NullValueProvider nva) {
            return new CreatorPropDelegateWithAliases(this, _valueDeserializer, nva);
        }
    }
 
    private static final ObjectReader reader;

    static {
        var mapper = JsonMapper.builder()
            .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
            .enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS)
            .build();

        //this is the way to inject another DeserializationFactory which is also not default
        var otherFact = mapper.getDeserializationContext().getFactory().withValueInstantiators(
            new WithAliasesDelegate()
        );

        reader = new ObjectMapper(mapper.getFactory(), null, new DefaultDeserializationContext.Impl(otherFact)).readerFor(RecorderConfig.class);
    }
}
```
