### ISSUE TITLE
objectMapper.enableDefaultTyping puts class name with package name in JSON

### ISSUE THREAD

**Issue by EXPEpbansal** [FasterXML/jackson-databind#2010]
I've complex (nested and custom classes) object to be serialized and deserialized. 

`objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.PROPERTY);`

Now, after deserializing it says -

`Class com.hello.www.domain.entities.foo.domain.impl.FProduct not subtype of [simple type, class com.hello.www.domain.entities.trip.dto.models.FProduct]`

This is assuming the classes at serialization would be present in same package while deserialization, which could not be true. 

PS: I used 'enableDefaultTyping' because we have interfaces with multiple implementations, and we need to have polymorphic deserialization.

**Comment by EXPEpbansal** [comment]
Serialized Json looks like -
 `{"@class":com.hello.www.domain.entities.foo.domain.impl.FProduct","flightTrip":{".....`

and we use deserialized version models at - com.hello.www.domain.entities.trip.dto.models.FProduct

**Comment by cowtowncoder** [comment]
I am not sure what the bug here would be. If you use default typing, then class names are used. This is how it works.

If you want to use logical type names, you need to use `@JsonTypeInfo` annotation. Default typing only allows use of class name since there is no guarantee otherwise that subtypes could be located.

**Comment by EXPEpbansal** [comment]
Do you mean using '@**JsonTypeInfo** annotation' in serialized classes (com.hello.www.domain.entities.foo.domain.impl.FProduct)? Actually we don't want to edit the file being used for serialization, and we are willing to modify models (dtos) used for deserialization. Will **this** work given the condition I have? @cowtowncoder

**Comment by cowtowncoder** [comment]
@EXPEpbansal you can attach `@JsonTypeInfo` using mix-in annotation too: it is only needed in the base class, as well (in fact it should not be used on subtypes). But annotation must be available on both serialization and deserialization, if Jackson is used for both -- type id is not included on serialization without it, nor expected on deserialization.

Also note that use of default typing is a security risk if you accept untrusted content (i.e. you do not control side that generates json):

    https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062

which is not the case unless `@JsonTypeInfo` is used on generic base type like `java.lang.Object`.
