### ISSUE TITLE
Deprecation in TypeSerializer undocumented

### ISSUE THREAD

**Issue by krichter722** [FasterXML/jackson-databind#2025]
All deprecated method in `com.fasterxml.jackson.databind.jsontype.TypeSerializer` are missing an explanation why they've been deprecated and which alternative method or more complex idiom should be used instead.

**Comment by cowtowncoder** [comment]
On replacement, before updating javadocs, suffice it to say that all `writeXxxTypePrefixYyy()` variants need to be replaced by `writeTypePrefix`, and `writeXxxTypeSuffixYyy()` similarly with `writeTypeSuffix()`.
And that former arguments are to be combined in `WritableTypeId` value object usually constructed with `typeId()` factory methods.
Finally, return value from `writeTypePrefix(...)` call should be passed to `writeTypeSuffix(...)` to keep small set of state that was formerly missing.

Above just if anyone finds this issue before javadocs are changed and published.

Rationale for replacements is more complicated and not necessarily something that is easy to explain in javadocs (above and beyond what class javadoc already says:

    NOTE: version 2.9 contains significant attempt at simplifying interface,
    as well as giving format implementation (via {@link JsonGenerator}) more
    control over actual serialization details.

but here are some more bullet points:

1. Giving more control to lower-level abstractions (`JsonGenerator`) by:
    * passing more information, contained in `WritableTypeId`
    * allowing generator to modify information, as well as retain state (property `extra`) between prefix and suffix calls
2. Allow easier extension of properties to pass in future, if necessary
3. Remove menagerie of different but related methods (related to 2 above)
