### ISSUE TITLE
Add caseInsensitive option to @JsonSubTypes 

### ISSUE THREAD

**Issue by buremba** [FasterXML/jackson-databind#2026]
Following up our [previous discussion](https://groups.google.com/forum/#!topic/jackson-user/CwPpArHj0jo) with @cowtowncoder I think that it would be useful to have the case-insensitive option for subtypes. The workaround is not that easy.

**Comment by cowtowncoder** [comment]
I _think_ this was implemented by #1983 (to be included in 2.11.0, available in 2.11.0.rc1 pre-release). One has to enable:

    MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES

and should then work.
