### ISSUE TITLE
Security issue with default typing, another reported potential gadget type

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2032]
(note: this is a placeholder and more details will be added after fix added, and ideally CVE allocated)

A new potential gadget type has been reported, possibly affecting databind up to and including `2.9.5`, `2.8.11.1`, `2.7.9.3` (as well as earlier minor versions). Type is from iBatis library.

**Comment by cowtowncoder** [comment]
Fixed for:

* 2.9.6
* 2.8.11.2
* 2.7.9.4 (if such version released)

**Comment by Boaz20** [comment]
@cowtowncoder  - When do you think 2.9.6 will be released?

**Comment by cowtowncoder** [comment]
@Boaz20 have been hoping to get "any day now" -- with good luck, by end of the week. But unfortunately I have been extremely busy (new job, house remodeling :) ).

**Comment by Boaz20** [comment]
@cowtowncoder  - thanks for the follow-up - much appreciated.

**Comment by cowtowncoder** [comment]
Fix included in

* 2.7.9.4
* 2.8.11.2

which were just released and will be included in

* 2.9.6

as soon as we get it finalized -- being full release it is a bigger process than micro-patches.
