### ISSUE TITLE
Json Marshalling glitch when using variables in camel case with first word being just "e"

### ISSUE THREAD

**Issue by mvettosi** [FasterXML/jackson-databind#2037]
I'm sorry for the weird title but it's the best I could understand from it.

When a bean being serialized in json has some properties named in camel case when the first word is just "e" (in my case, eTokenLibFilePath, eTokenSerial, eTokenSigningKeyAlias, eTokenTlsClientAlias, eTokenSlot and eTokenPin), these properties are included in the json string no matter what annotation is applied, and the key used is the variable name with the letter following "e" being lowercase.

Some examples:
@ JsonProperty
```
    @JsonProperty("eToken.lib.file.path")
    @Value("${eToken.lib.file.path:}")
    private String eTokenLibFilePath;
```
This produces the following entries in the result json:
```
"eToken.lib.file.path": "/usr/lib/libeTPkcs11.so"
"etokenLibFilePath": "/usr/lib/libeTPkcs11.so"
```

@ JsonIgnore
```
    @JsonIgnore
    @Value("${eToken.pin:}")
    private String eTokenPin;
```
This only inserts the bugged entry:
```
"etokenPin": "Tt123456"
```

The same glitch can be reproduced with any word instead of "Token" (i.e.: eBoken, eTest) but not with other starting letters (like aToken).

My temporary workaround is to rename the properties from eTokenX to etokenX, which seems to solve the problem entirely.

Env background:
Jackson Databind 2.8.8
Spring Boot 2.0.2
Lombok 1.16.18 (Only using @ Getter and @ Setter annotations)

**Comment by cowtowncoder** [comment]
@mvettosi Pretty sure you can thank Lombok for this, in some form or another. :-/

What is needed is the expanded class definition after Lombok processing. My guess is that it generates constructor, with named parameters (`@ConstructorParameters`), and that those names do not match with field names.
