### ISSUE TITLE
java.lang.NoSuchMethodError While accessing latest version of "data-bind"

### ISSUE THREAD

**Issue by BaluBabu** [FasterXML/jackson-databind#2041]
As i am new to JAVA, Im using jPaskit library and there is dependency with jackson-databind and after upgrading pom.xml version '2.2.3' to  '24.5/2.6.2' and created jar which is successful. and i can see the below error while access Jar file can you please help me to fix this issue. and Which version of the jackson-databind is having the below method.
**java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ser.impl.SimpleFilterProvider.addFilter(Ljava/lang/String;Lcom/fasterxml/jackson/databind/ser/impl/SimpleBeanPropertyFilter;)Lcom/fasterxml/jackson/databind/ser/impl/SimpleFilterProvider;**

**Comment by cowtowncoder** [comment]
You need to make sure that you are deploying with consistent versions. Try to figure out which version jPaskit requires. 
Javadocs from:

https://github.com/FasterXML/jackson-databind/wiki

can tell you more about additions.

Good luck!
