### ISSUE TITLE
Eager fetch not working accordingly

### ISSUE THREAD

**Issue by koww** [FasterXML/jackson-databind#2046]
I'm using Jackson databind 2.9.4 with some hibernate class. One of the class is like:

`
@Entity
public class MyClass implements Serializable {

    @Transient
    private final static long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(
            /* Omitted */
    )
    private List<Attribute1> attribute1s = new ArrayList<>();

    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, mappedBy = "patch")
    private List<Attribute2> attribute2s = new ArrayList<>();

    public MyClass() {
    }
}
`
The object mapper is like below:

`
private ObjectMapperAccess() {
        this.objectMapper = new ObjectMapper();

        /*
         * Generic configuration
         */
        this.objectMapper.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.NONE);
        this.objectMapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        this.objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.PROPERTY);

        /*
         * Configure deserialization features
         */
        this.objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        this.objectMapper.configure(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES, false);

        /*
         * Register mixins
         */
        this.objectMapper.addMixIn(Throwable.class, ThrowablelMixin.class);
        this.objectMapper.addMixIn(StackTraceElement.class, StackTraceElementMixin.class);
    }

`

The @ManyToMany field could be correctly deserialized with eager fetch while the @OneToMany field will always fail at deserialization with eager fetch. 

What is the cause of the different behavior here? And what can I do to make them both work? Or any workaround on this

**Comment by cowtowncoder** [comment]
Could you please refile at `jackson-datatype-hibernate`, as this functionality is handled there, not in core databind.
(unless this can reproduced without external dependencies that is -- but Hibernate is quite specialized thing )

**Comment by cowtowncoder** [comment]
Needs to move to different repo as per above note.
