### ISSUE TITLE
Circular dependency of JSON is not resolving

### ISSUE THREAD

**Issue by aamitsingh** [FasterXML/jackson-databind#2053]
Class:

```java
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "uniqueID")
final public class TestNode {
    private final String uniqueID;
    private final TestNode testNode; //Circular dependency
}
```

main:

```java
private final ObjectMapper objectMapper = new ObjectMapper();
objectMapper.writeValue(JsonOutputFile, TestNode.class); // Write object to file
```

*If I use JsonIdentityInfo then while writing the object to file in I get results 
{ "uniqueID": "1", "testNode": "1"}

*If I do not use JsonIdentityInfo then I get correct JSON, i.e. testNode is correct but I get following error in that:

'Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: ["testNode"] ...'

I'm using the following version: Jackson: 2.9.0, Java: 8, Spring: 4.3

**Comment by cowtowncoder** [comment]
First of all, I would try out latest patch for minor revision you have, `2.9.5`.

Second: code above only shows serialization, and stack trace does not give any context on where exception is thrown. I am guessing exception would occur when trying to read `TestNode` value?
