### ISSUE TITLE
Infinite recursion with Circular dependency (ManyToMany) using `@JsonIgnoreProperties`

### ISSUE THREAD

**Issue by rudolfgrauberger** [FasterXML/jackson-databind#2062]
## Scenario/Initial situation
I would like to serialize the following model to JSON.

![author_book_m_to_n](https://user-images.githubusercontent.com/12803598/41297852-5fe051ba-6e60-11e8-89de-a5cb1c30250f.png)

I have a book, the book have one or more authors and vice versa.

I try this with following versions:

- jackson-databind: 2.8.8
- jackson-annotations: 2.8.0

and 

- jackson-databind: 2.9.5
- jackson-annotations: 2.9.5

## Expectation

What i expect after serialisation to json, is from ...

- ... the point of view of Author

```JSONLD
{  
   "name":"NoName Author",
   "books":[  
      {  
         "name":"My Book",
         "publicationDate":1288303200000
      }
   ]
}
```
- ... the point of view of Book 
```JSONLD
{  
   "name":"My Book",
   "publicationDate":1288303200000,
   "authors":[  
      {  
         "name":"Author"
      }
   ]
}
```
If I understood JsonIgnoreProperties correctly, my following source code should do just that

Author:

```java
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

// If he comes across a property called this he should ignore it
// When tracking the reference, it encounters the "authors" property/getter 
// in the Book class and should then ignore it.
@JsonIgnoreProperties("authors") 
public class Author {
    private String name;

    private Set<Book> books = new HashSet<Book>();

    public Author(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public Set<Book> getBooks() {
        return books;
    }

    public void addBook(Book book) {
        // Avoids endless circular calls
        if (!books.contains(book)) {
            books.add(book);
            book.addAuthor(this);
        }
    }
}
```

Book:

```java
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

// If he comes across a property called this he should ignore it
// When tracking the reference, it encounters the "books" property/getter
// in the Authors class and should then ignore it.
@JsonIgnoreProperties("books")
public class Book {
    private String name;
    private Date publicationDate;

    private Set<Author> authors = new HashSet<Author>();

    public Book(String name, Date publicationDate) {
        this.name = name;
        this.publicationDate = publicationDate;
    }

    public String getName() {
        return name;
    }

    public Date getPublicationDate() {
        return publicationDate;
    }

    public Set<Author> getAuthors() {
        return authors;
    }

    public void addAuthor(Author author) {
        // Avoids endless circular calls
        if (!authors.contains(author)) {
            authors.add(author);
            author.addBook(this);
        }
    }
}
```

## My Tests

```java
import com.example.Entities.Author;
import com.example.Entities.Book;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringRunner;

import static org.assertj.core.api.Assertions.*;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

@RunWith(SpringRunner.class)
public class ExampleApplicationTests {

	@Test // Serialize Author
	public void testSerializeAuthorWithCircularDependenciesToJson() throws ParseException, JsonProcessingException {
		String testDate = "29-10-2010";
		DateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
		Date date = formatter.parse(testDate);

		Author author1 = new Author("NoName Author");
		Book book1 = new Book("My Book", date);
		author1.addBook(book1);


		ObjectMapper mapper = new ObjectMapper();
		String json = mapper.writeValueAsString(author1);


		assertThat(json).isEqualTo("{\"name\":\"NoName Author\",\"books\":[{\"name\":\"My Book\",\"publicationDate\":1288303200000}]}");
	}

	@Test // Serialize Book
	public void testSerializeBookWithCircularDependenciesToJson() throws ParseException, JsonProcessingException {
		String testDate = "29-10-2010";
		DateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
		Date date = formatter.parse(testDate);

		Author author1 = new Author("NoName Author");
		Book book1 = new Book("My Book", date);
		author1.addBook(book1);
		String json = null;

		ObjectMapper mapper = new ObjectMapper();
		json = mapper.writeValueAsString(book1);

		assertThat(json).isEqualTo("{\"name\":\"My Book\",\"publicationDate\":1288303200000,\"authors\":[{\"name\":\"NoName Author\"}]}");
	}
}
```
	
**Result for testSerializeAuthorWithCircularDependenciesToJson:** 
`com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.util.HashSet[0]->com.example.Entities.Book["authors"]->java.util.HashSet[0]->...`

**Result for testSerializeBookWithCircularDependenciesToJson:** 
`com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.util.HashSet[0]->com.example.Entities.Book["authors"]->java.util.HashSet[0]->...`

Is this error already known, or am I doing something wrong?

**Comment by cowtowncoder** [comment]
I think there may be a misunderstanding here, with respect to scope of `@JsonIgnoreProperties` definition: it only affects properties of the POJO type (when used on class), or, properties of value type of POJO property (when added on property accessor).
So test case as presented has annotations that have no effect; annotations are sort of "wrong way around" -- `Author` type does not have `authors` property to ignore (`Book` has), and `Book` does not have `books` (`Author` has).

But you could add those annotations on property `books` (in `Author`) and `authors` (of `Book`) and this may do what you want, if I understand this correctly.
In that case, ignoral only applies to values specifically reached by said property, and not all `Book` or `Author` values.

**Comment by Silox** [comment]
Following this as I have the same issue. Only occurs when my Books & Authors as HashSets though. If I change the HashSets to Lists, my result is as expected (meaning that the JSON-representation only goes one level deep).

**Comment by cowtowncoder** [comment]
At this point I do not see an actual problem being reproduced: the original test seems to assume that `@JsonIgnoreProperties` effects properties recursively -- it does not. It affects properties of annotated class (when added on class), or, of value (Map, POJO, List) of annotated property.

Closing as this works as designed, unless I misunderstood the problem.
