### ISSUE TITLE
Distinguish null from empty string for UUID deserialization

### ISSUE THREAD

**Issue by leonshaw** [FasterXML/jackson-databind#2066]
For UUID deserialization, empty string is mapped to `null` by FromStringDeserializer. So something like `{"parent_uuid": null}` can't be distinguished from `{"parent_uuid": ""}`. From the view of a strict API, the latter is an error.
It would be good to add some feature like "STRICT_STRING_VALUE", that FromStringDeserializer does not trim or shortcut empty strings so that UUID deserializer could report the error.
This may be an opposite feature of #768 ACCEPT_EMPTY_STRING_AS_NULL_OBJECT.

**Comment by cowtowncoder** [comment]
Ok. What do you think would make most sense for empty String in strict mode? Exception would seem like my first choice, although there is also the"empty" UUID, which you'd get from "all zeroes".

It would also be possible to consider `MapperFeature.ALLOW_COERCION_OF_SCALARS` here: disabling of which could prevent use of empty String... also semantically there is the question of whether this really is coercion.

Now: from practical perspective, behavior change can not be made in 2.9 patch versions, since it would likely break some processing somewhere (even if behavior for default settings was unchanged, unless new feature was added, which in turn should not be done in a patch).
On plus side I am planning to do one more 2.x, 2.10, so this could get in.

**Comment by leonshaw** [comment]
I prefer to throw exception. All-zero UUIDs should be supplied explicitly, to be "strict".
I think it's different from coercion. Because string is already the representation of UUID, it's just normal parsing and there's nothing special of empty string than any arbitrary strings.
Good to hear it could go in 2.10. Thanks.

**Comment by cowtowncoder** [comment]
So: there is `@JsonFormat(lenient=OptBoolean.FALSE)` (and matching config override), so I think that should be the mechanism. Will see if I have time to actually work on this.

**Comment by shahaf-sameach** [comment]
hi, new contributor :) can I try this one?

**Comment by cowtowncoder** [comment]
@shahaf-sameach Absolutely! Trickiest part might just be figuring out how to get information on all parts of leniency settings: sources at `less src/main/java/com/fasterxml/jackson/databind/deser/std/DateDeserializers.java` seem to be main reference at this point.

To be more exact, there are 3 levels of leniency settings:

1. `ObjectMapper.setDefaultLenience(Boolean)` (default is effectively `Boolean.TRUE`)
2. Per-type config overrides: `mapper.configOverride(UUID.class).setFormat(....)`
3. Per-property override with `@JsonFormat` annotation

so the trick is to figure out combination of effective setting. An example can be found from `DateDeserializers` class I mention above:

```java
        @Override
        public JsonDeserializer<?> createContextual(DeserializationContext ctxt,
                BeanProperty property)
           throws JsonMappingException
        {
            final JsonFormat.Value format = findFormatOverrides(ctxt, property,
                    handledType());

            if (format != null) {
...
}
```

so you would add this method in `UUIDDeserializer` to allow for changing setting (and `boolean` field in `UUIDDeserializer` itself to keep track).

And then finally, tests to verify that new handling works. Place to add tests would be

    src/test/java/com/fasterxml/jackson/databind/deser/jdk/JDKStringLikeTypesTest.java

I hope this helps!

**Comment by cowtowncoder** [comment]
I am thinking of actually tackling this as part of much bigger change -- #2728 -- and removing "good first issue" tag since approach I proposed here is not needed.

**Comment by cowtowncoder** [comment]
I will start working on this issue, based on new `CoercionConfigs` feature (as mentioned above).

**Comment by cowtowncoder** [comment]
So, implemented using new "CoercionConfigs" system; test `CoerceMiscScalarsTest` has full verification for `UUID` as well as other types. Default behavior in 2.12 NOT changed.

To make coercion from empty String fail only for UUID, you can use:

```java
ObjectMapper mapper = ...;
mapper.coercionConfigFor(UUID.class).setCoercion(CoercionInputShape.EmptyString,
    CoercionAction.Fail);
```

or to change handling of most similar scalar types:

```java
ObjectMapper mapper = ...;
mapper.coercionConfigFor(UUID.class).setCoercion(LogicalType.OtheScalar),
    CoercionAction.Fail);
```

or, even, if you really want, prevent it by most types (unless overridden by more-specific setting:

```java
ObjectMapper mapper = ...;
mapper.coercionConfigDefaults().setCoercion(LogicalType.OtherScalar),
    CoercionAction.Fail);
```

Alternatively you can use `CoercionAction.AsNull` to allow coercion to `null`, or, `CoercionAction.AsEmpty` to get "all-zeroes" UUID constructed.
