### ISSUE TITLE
Problema no parser de XML

### ISSUE THREAD

**Issue by wesley** [FasterXML/jackson-databind#2069]
Pessoal,

Em uma integração estou recebendo o XML abaixo:

`<service type="AAA">
	<type>BBB</type>
	<other>CCC</other>
</service>`

Para representar esse XML. criei a classe abaixo:

`@JacksonXmlRootElement(localName = "service")
public class Service {

	@JacksonXmlProperty(localName = "type", isAttribute = true)
	private String type1;

	@JacksonXmlProperty(localName = "type")
	private Type type2;

	@JacksonXmlProperty(localName = "other")
	private String other;

	...
} `

Porém estou com problema, onde diz haver conflito entre os atributos "type":

`com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "type": br.com.xxx.Service#setType1(1 params) vs br.com.xxx.Service#setType2(1 params)
 at [Source: (StringReader); line: 1, column: 1]`

Alguém sabe a solução para isso?

**Comment by cowtowncoder** [comment]
Unfortunately I am not fluent in.... portuguese? But I think this is mis-filed, aside from language, and should go under `jackson-dataformat-xml`
