### ISSUE TITLE
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.testing.FeedItem

### ISSUE THREAD

**Issue by AxeemHaider** [FasterXML/jackson-databind#2075]
I'm using jackson to read and write object into local json file.
It successfully read and write value. But problem is when I read value from file. and assign it to my object it give me an error.

> java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.testing.FeedItem

I know the reason of error because to read value from file jackons use LinkedHashMap So, LinkedHashMap can not cast to object(FeedItem)

Here is what I'm using.

**PostFeed**

  ```
public class PostFeed{
       private String name;
       private List<FeedItem> feeditemList;
       // other code getter setter etc
  }
```
**Reading Value from File**

```
ObjectMapper objectMapper = new ObjectMapper();
PostFeed postFeed = objectMapper.readValue(offlinePrivateFeed, PostFeed.class);

FeedItem feedItem = postFeed.getFeedList().get(0); // Error
```

**Write Value to local File**

```
     ObjectMapper objectMapper = new ObjectMapper();
     objectMapper.writeValue(Utils.getOutputJsonFile("private-feed"), postFeed);
```

**FeedItem**

```
public class FeedItem{
     private String name;
     private int badge;
     private Boolean allow;

     // other code getter setter etc
  }
```
**Here is how JSON File look like**

```
{
 "feedName": "test123",
 "time" : "7-7-1994",
 "feedList": [
  {
   "name": "feedItemName",
   "badge": 4,
   "allow": false
  },
  {
   "name": "feedItemName",
   "badge": 1,
   "allow": true
  },
  {
   "name": "feedItemName",
   "badge": 2,
   "allow": false
  }

  ]

}
```

Can you please let me know how can I solve this ?

**Comment by cowtowncoder** [comment]
Class definitions look reasonable and I do not see any immediate problem.
But I can not reproduce the issue without stand-alone unit test: that would be needed to figure out what is happening.

Test should use a relatively new Jackson version: for example 2.9.6 or 2.8.10. Doing that might also uncover possible fixes (that is, if test fails on older version, upgrade would be needed).

**Comment by cowtowncoder** [comment]
Need a reproduction; closing but may be opened with a (unit) test.

**Comment by lukeZhangMengxi** [comment]
Hi, I got the same issue. Could I get some instructions on how to add the unit test?

**Comment by cowtowncoder** [comment]
@lukeZhangMengxi Existing unit tests are under `src/test/main` and you may be able to find something similar to use as a base. Typically failing unit tests are located under folder "failing".
You can use branch `2.11` as the base (default branch, `master`, is for developing 3.0), although differences are not huge and I can move tests across branches if necessary.

**Comment by lukeZhangMengxi** [comment]
> @lukeZhangMengxi Existing unit tests are under `src/test/main` and you may be able to find something similar to use as a base. Typically failing unit tests are located under folder "failing".
> You can use branch `2.11` as the base (default branch, `master`, is for developing 3.0), although differences are not huge and I can move tests across branches if necessary.

Great! I will probably look into that on the weekends.
