### ISSUE TITLE
jackson-databind maven artifact does not depend on the same version of jackson-annotations

### ISSUE THREAD

**Issue by bondolo** [FasterXML/jackson-databind#2076]
Current builds (and for several prior releases) depend on 2.9.0 rather than the same version as themselves. This causes issues if a project explicitly depends on the annotations artifact and also uses the maven enforcer "DependencyConvergence" rule. The enforcer will fail the build because of version mismatch between the version the project is referencing (2.9.5 in my case) and the version that jackson-databind is referencing (2.9.0)

**Comment by cowtowncoder** [comment]
This is FAQ and fully intentional. All 2.9.x artifacts refer to jackson-annotations 2.9.0. With 3.x, we will drop patch number from annotations since no changes are allowed within minor release for annotation package.

**Comment by bondolo** [comment]
Thank you. This will resolve the issue.
