### ISSUE TITLE
NPE when visiting StaticListSerializerBase

### ISSUE THREAD

**Issue by WorldSEnder** [FasterXML/jackson-databind#2079]
I am using jackson 2.7 but when looking through the code, the issue will most likely remain after upgrading.

The problem has it's roots here https://github.com/FasterXML/jackson-databind/blob/54dc16297ee22b2b1680717d7536fa22a6c13727/src/main/java/com/fasterxml/jackson/databind/ser/std/StaticListSerializerBase.java#L94-L96

If the visitor returns `null` from `expectArrayFormat` (as for example by inheriting from `JsonFormatVisitorWrapper.Base`) then a `NullPointerException` will be raised from the following places https://github.com/FasterXML/jackson-databind/blob/db69efde6cbb283e6e02039a24d6879e2468a358/src/main/java/com/fasterxml/jackson/databind/ser/impl/IndexedStringListSerializer.java#L53-L55 https://github.com/FasterXML/jackson-databind/blob/db69efde6cbb283e6e02039a24d6879e2468a358/src/main/java/com/fasterxml/jackson/databind/ser/impl/StringCollectionSerializer.java#L55-L58.

**Comment by cowtowncoder** [comment]
It would be great to have a unit test to reproduce this (and guard against regression), but I agree that compared to other handlers this probably should check for nulls.
