### ISSUE TITLE
MapperFeature.IGNORE_MERGE_FOR_UNMERGEABLE jdoc says default is disabled but it is ENABLED

### ISSUE THREAD

**Issue by elonderin** [FasterXML/jackson-databind#2081]
this is the code

>     /**
>      * Setting that determines what happens if an attempt is made to explicitly
>      * "merge" value of a property, where value does not support merging; either
>      * merging is skipped and new value is created (<code>true</code>) or
>      * an exception is thrown (false).
>      *<p>
>      * **Feature is disabled** by default since non-mergeable property types are ignored
>      * even if defaults call for merging, and usually explicit per-type or per-property
>      * settings for such types should result in an exception.
>      *
>      * @since 2.9
>      */
>     IGNORE_MERGE_FOR_UNMERGEABLE(true)

**Comment by cowtowncoder** [comment]
Thank you for reporting this, fixed Javadoc to state correct default.
