### ISSUE TITLE
`ReferenceType` does not expose valid containedType

### ISSUE THREAD

**Issue by nbauernfeind** [FasterXML/jackson-databind#2091]
Filing an issue per discussion on the mailing list titled "ReferenceType no bindings."

It feels like it would be useful if ReferenceType's containedType(0) returns the actual reference type. This feels more consistent with how Collection and Map contained types behave.

You'd suggested that you'll look into it perhaps for v2.10 or v3.0.

**Comment by cowtowncoder** [comment]
Looks like `getContentType()` returns type, but `TypeBindings` are indeed empty.
Will postpone until 2.12, likely, since 2.11.0 about to be released.
