### ISSUE TITLE
Null inclusion bug in Jackson 2.9.6

### ISSUE THREAD

**Issue by Warchant** [FasterXML/jackson-databind#2092]
I am using `compile("com.fasterxml.jackson.core:jackson-databind:2.9.6")`

I use the same ObjectMapper to serialize the same key-value structure parsed as tree from string (JSON) and a groovy object. This ObjectMapper includes only non-null values:
``` 
.setSerializationInclusion(JsonInclude.Include.NON_NULL)
```

When I serialize **from object**, it does NOT include null value - *as expected*
When I serialize **from JsonNode (tree)**, it INCLUDES null value - *bug?*

I wrote a small groovy example using `testCompile("org.spockframework:spock-core:1.1-groovy-2.4")
`:

```groovy
package jackson
 
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.databind.ObjectMapper
import spock.lang.Specification
 
class ObjectMapperTest extends Specification {
    def "should not include nulls"() {
        given:
        def json = '''
               {
                   "a": {},
                   "b": [],
                   "c": "",
                   "d": 0,
                   "e": null
               }
       '''
 
        def obj = [
                "a": [:],
                "b": [],
                "c": "",
                "d": 0,
                "e": null
        ]
 
        def jsonMapper = new ObjectMapper()
                .setSerializationInclusion(JsonInclude.Include.NON_NULL)
        def tree = jsonMapper.readTree(json)
 
 
        when:
        def a1 = jsonMapper.writeValueAsString(tree)
        def a2 = jsonMapper.writeValueAsString(obj)
 
        then:
        a1 == a2
    }
}
```

Result:
```
Condition not satisfied:

a1 == a2
|  |  |
|  |  {"a":{},"b":[],"c":"","d":0}
|  false
|  9 differences (75% similarity)
|  {"a":{},"b":[],"c":"","d":0(,"e":null)}
|  {"a":{},"b":[],"c":"","d":0(---------)}
{"a":{},"b":[],"c":"","d":0,"e":null}

Expected :{"a":{},"b":[],"c":"","d":0}

Actual   :{"a":{},"b":[],"c":"","d":0,"e":null}
```

**Comment by cowtowncoder** [comment]
This is as expected: `null` means literal Java (JVM) `null` values, `NullNode` of `JsonNode` is not `null` in that sense. 

In addition, `JsonNode` is taken to be literal expression of your intent so filtering is not applied, in general -- filtering is focused on POJO handling (and to `Map`s and other containers).

**Comment by bovenson** [comment]
> This is as expected: `null` means literal Java (JVM) `null` values, `NullNode` of `JsonNode` is not `null` in that sense.
> 
> In addition, `JsonNode` is taken to be literal expression of your intent so filtering is not applied, in general -- filtering is focused on POJO handling (and to `Map`s and other containers).

Facing the same problem. Agree to `JsonNode` is taken to be literal expression of intent, so JsonNode.toString should keep null field (wrappered by NullNode). But, object mapper which specified JsonInclude.Include.NON_NULL option should skip NullNode when serialize JsonNode, because `null` value in json string means literal Java (JVM) `null` values for Java.  

In contrast, gson's behavior is more reasonable

```
String s = "{\n" +
                "  \"did\": \"did\",\n" +
                "  \"type\": \"type\",\n" +
                "  \"data\": {\n" +
                "    \"value\": \"valule\",\n" +
                "    \"d\": null,\n" +
                "    \"list\": [\"A\", null, \"B\"]\n" +
                "  }\n" +
                "}";
        Gson gson = new Gson();
        JsonObject jo = gson.fromJson(s, JsonObject.class);
        System.out.println(gson.toJson(jo));
        System.out.println("-");
        System.out.println(jo.toString());

// output
{"did":"did","type":"type","data":{"value":"valule","list":["A",null,"B"]}}
-
{"did":"did","type":"type","data":{"value":"valule","d":null,"list":["A",null,"B"]}}
```

By the way, when i try to skip NullNode through configuration, `new SimpleModule().addSerializer(NullNode.class, new NullNodeAdapter())` seems doesn't work.
