### ISSUE TITLE
Map with Integer is not working, with String works

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [FasterXML/jackson-databind#2094]
I have this object:

```
public class Data {

    private Map<Integer, Item> itemMap = new HashMap<>();

    @JsonAnyGetter
    public Map<Integer, Item> any() {
        return itemMap;
    }

    @JsonAnySetter
    public void set(final Integer id, final Item item) {
        itemMap.put(id, item);
    }
}
```

If I use this: `Item item = objectMapper.readValue(new URL(url), ItemDto.class).getData().any().get(item_id);`

I got this error: 

> Invalid 'any-setter' annotation on method 'set()': first argument not of type String or Object, but java.lang.Integer at [Source: (URL); line: 1, column: 1]

If I change all from Integer to String, it is working.

Is it a Jackson limitation or I am failing?

**Comment by 1329555958** [comment]
you can see the comments at [JsonAnySetter](https://github.com/FasterXML/jackson-annotations/blob/d5ca5c85c816b6e768618c3aabfa8c5a516abdd5/src/main/java/com/fasterxml/jackson/annotation/JsonAnySetter.java)
`two-argument method (first argument name of property, second value to set)`
the first method is the name of property ,so it must be `String`, you can convert it to `Integer` in your `set` method if you can make sure it is `Integer`
