### ISSUE TITLE
@JsonRawValue does not work in jackson 2.9.6

### ISSUE THREAD

**Issue by MarenkovSergey** [FasterXML/jackson-databind#2106]
Hello,

In our project we faced with problem with @JsonRawValue when we migrate from jackson 2.8.8 to jackson 2.9.6.

Example program:
import com.fasterxml.jackson.annotation.JsonRawValue;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;

public class JacksonTest {

    public static class Bean
    {
        @JsonRawValue
        private String rawValue;

        public Bean(String rawValue) {
            this.rawValue = rawValue;
        }

        public String getRawValue() {
            return rawValue;
        }

        public void setRawValue(String rawValue) {
            this.rawValue = rawValue;
        }
    }

    public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper mapper = new XmlMapper();
        mapper.enable(SerializationFeature.INDENT_OUTPUT);
        System.out.println(mapper.writeValueAsString(new Bean("rawValue")));
    }
}

In jackson 2.8.8 output was

`<Bean>rawValue</Bean>`

But in jackson 2.9.6 it 

`<Bean><rawValue>rawValue</rawValue></Bean>`

In @JsonRawValue javadoc i see:
/** Marker annotation that indicates that the annotated method
 or field should be serialized by including literal String value
 of the property as is, without quoting of characters.

Can you please fix this bug? In breaks jackson backward compatibility

**Comment by MarenkovSergey** [comment]
If you will not fix this issue, please tell how to achieve this behavior? Is @JsonValue suitable for this?

**Comment by cowtowncoder** [comment]
It seems to me that 2.9 behavior is correct here. I think you may be seeing effects of fix #232 here.

However: I suspect that you may be looking for `@JsonValue` annotation instead? Its use would use value of property as serialization of the whole value; whereas `@JsonRawValue` only applies to value of property itself. Naming is bit confusing as "value" has different semantics.
