### ISSUE TITLE
ObjectNode.setXxx() methods have wrong return type

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#212]
Intent behind 'set()' (and related) methods, added in 2.1, was to improve chainability.
Unfortunately return type was left as `JsonNode`, which makes these unchainable. It ought to be `ObjectNode`; but this change would be binary incompatible signature change.

Perhaps overloaded variants would work? If so, those could be added, and old ones deprecated (and eventually removed).

**Comment by cowtowncoder** [comment]
Will close this to clean up old issues -- it may be re-filed as 3.0 feature or something, but unlikely to be worked on for 2.x.

**Comment by quiram** [comment]
In case it helps, chainability can be obtained if one explicitly states the type of `T` like this:
```
obNode.<ObjectNode>set("a", node1)
    .<ObjectNode>set("b", node2)
    .set("c", node3);
```

which doesn't do much to help readability, but it may be useful on certain scenarios.
