### ISSUE TITLE
Cannot unserialize "[12345,[5391.9,0,-1]]" without writing a custom deserializer

### ISSUE THREAD

**Issue by jmcklondonuk** [FasterXML/jackson-databind#2137]
There is an issue with ObjectMapper.readValue(). It throws an Exception instead of mapping the input.
The input should be mapped to int channelId followed by an array of Data where Data is an array comprising of 3 items: double price, int count, double amount.
 
    public static void main(String args[]) throws IOException {
        String jsonInput = "[17847,[5391.9,0,-1],[5392.9,1,-2]]";
        ObjectMapper mapper = new ObjectMapper();
        ChannelData result = mapper.readValue(jsonInput, ChannelData.class);
    }

    @JsonFormat(shape = JsonFormat.Shape.OBJECT)
    public static class ChannelData {
        // this doesn't work
        private Integer channel;  
        // this doesn't work
        private List<Data> data;

        public ChannelData() {

        }

        public ChannelData(int channel, List<Data> data) {
            this.channel = channel;
            this.data = data;
        }

        public int getChannel() {
            return channel;
        }

        public void setChannel(int channel) {
            this.channel = channel;
        }

        public List<Data> getData() {
            return data;
        }

        public void setData(List<Data> data) {
            this.data = data;
        }
    }

    @JsonFormat(shape = JsonFormat.Shape.ARRAY)
    public static class Data {
        private Double price;

        private Integer count;

        private Double amount;

        public Data() {
        }

        public Data(Double price, Integer count, Double amount) {
            this.price = price;
            this.count = count;
            this.amount = amount;
        }

        public Double getPrice() {
            return price;
        }

        public void setPrice(Double price) {
            this.price = price;
        }

        public Integer getCount() {
            return count;
        }

        public void setCount(Integer count) {
            this.count = count;
        }

        public Double getAmount() {
            return amount;
        }

        public void setAmount(Double amount) {
            this.amount = amount;
        }
    }

**Comment by cowtowncoder** [comment]
Isn't this wrong:

```java
@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public static class ChannelData {
```

since format except that to use `Shape.ARRAY`, not OBJECT?
