### ISSUE TITLE
UnknownPropertyHandler infinite loop

### ISSUE THREAD

**Issue by Tomrap** [FasterXML/jackson-databind#2138]
There is an issue with method handleUnknownProperty in DeserializationProblemHandler class.

There is an infinite recursion while handling unknown properies when the unknown property is a list.

Specifically when there is one unknown list property and one known property defined in json file.

Below test gets stuck in the handleUnknownProperty method.

 

 
    @Test
    public void unknownProperty() throws IOException {

        ClassLoader classLoader = getClass().getClassLoader();

        File file = new File(classLoader.getResource("UnknownProperty.json").getFile());

        ObjectMapper objectMapper = customObjectMapper();

        objectMapper.readValue(file, PersonalDetails1.class);

    }

 

 

    public ObjectMapper customObjectMapper() {
           return new ObjectMapper()

                .setPropertyNamingStrategy(PropertyNamingStrategy.UPPER_CAMEL_CASE)

                .setSerializationInclusion(JsonInclude.Include.NON_NULL)

                .configure(SerializationFeature.INDENT_OUTPUT, true)

                .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)

                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

                .addHandler(unknownPropertyLogger())

                .setTimeZone(TimeZone.getTimeZone("UTC"))

                .configure(JsonParser.Feature.ALLOW_COMMENTS, true)

                .registerModule(new JavaTimeModule()

                );

     }

 

    private DeserializationProblemHandler unknownPropertyLogger() {

        return new DeserializationProblemHandler() {

            @Override

            public boolean handleUnknownProperty(DeserializationContext ctxt, JsonParser p, JsonDeserializer<?> deserializer, Object beanOrClass, String propertyName) {

                return true;

            }

        };

    }

               

    public class PersonalDetails1 {

                private List<CustomerCountry1> Countries;

    }

    public class CustomerCountry1 {

                private String type;
    }

               
UnknownProperty.json:

 

    {
      "GovernmentIdentifiers": [{

      }

      ],

      "Countries": [{

        "type": "ABC"

      }

      ]
    }

**Comment by Tomrap** [comment]
There is an issue with method handleUnknownProperty in DeserializationProblemHandler class.

There is an infinite recursion while handling unknown properies when the unknown property is a list.

Specifically when there is one unknown list property and one known property defined in json file.

Below test gets stuck in the handleUnknownProperty method.

 

 

@Test

    public void unknownProperty() throws IOException {

 

        ClassLoader classLoader = getClass().getClassLoader();

        File file = new File(classLoader.getResource("UnknownProperty.json").getFile());

        ObjectMapper objectMapper = customObjectMapper();

        objectMapper.readValue(file, PersonalDetails1.class);

    }

 

 

    public ObjectMapper customObjectMapper() {

        return new ObjectMapper()

                .setPropertyNamingStrategy(PropertyNamingStrategy.UPPER_CAMEL_CASE)

                .setSerializationInclusion(JsonInclude.Include.NON_NULL)

                .configure(SerializationFeature.INDENT_OUTPUT, true)

                .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)

                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

                .addHandler(unknownPropertyLogger())

                .setTimeZone(TimeZone.getTimeZone("UTC"))

                .configure(JsonParser.Feature.ALLOW_COMMENTS, true)

                .registerModule(new JavaTimeModule()

                );

    }

**Comment by cowtowncoder** [comment]
Thank you for reporting the problem, providing test case.

One quick question: which version did you test with?

**Comment by Tomrap** [comment]
Tested with version 2.9.6

**Comment by cowtowncoder** [comment]
Oh. Actually, the problem is with handler: it does not advance the token stream.
The proper way in this case would be to simply skip it:

```java
    @Override
    public boolean handleUnknownProperty(DeserializationContext ctxt, JsonParser p, JsonDeserializer<?> deserializer, Object beanOrClass, String propertyName) {
        p.skipChildren();
        return true;
    }
```

but this is not done by code that calls handler.

**Comment by roman-sinyakov** [comment]
The issue was fixed only for the root level and it still exists for the nested levels:
```
{  
   "Countries": [{  
      "type": "ABC",  
       "GovernmentIdentifiers": [{  
       }]  
    }  
  ]  
}  
```

**Comment by cowtowncoder** [comment]
@roman-sinyakov please file a new issue, with reproduction.
