### ISSUE TITLE
@JSONProperty for a field 'is_deleted' is serialized as `_deleted`

### ISSUE THREAD

**Issue by maruthi-adithya** [FasterXML/jackson-databind#2142]
Hi,
      I am using Jackson 2.9.5. I have an Entity Structure Like this.
```
@Entity
@Data
public class PersonEntity {
 
      @JsonProperty("is_deleted")
      private boolean is_deleted;

}
```
On Deserialization,  there are 2 fields.
```
{
   "_deleted" : "true",
   "is_deleted":"true"
}
```
Setting any 1 of the above from REST Client sets the value for the field `is_deleted`.

Suppose, I tweak my value a little bit and change my Entity as
```
@Entity
@Data
public class PersonEntity {
 
      @JsonProperty("is_deleted")
      private boolean isDeleted;

}
```

Again I get 2 fields on serialization,
```
{
   "deleted" : "true",
   "is_deleted":"true"
}
```
Setting any any 1 of the above from REST Client sets the value for the field `isDeleted`.

However, when I change this field without the **is** part, 

```
@Entity
@Data
public class PersonEntity {
 
      @JsonProperty("is_deleted")
      private boolean deleted;

}
```
there is only 1 field that is correctly serialized as `is_deleted`.

I use Lombok for getters and setters. May I know the reason for this ambiguity? @cowtowncoder

**Comment by maruthi12** [comment]
@cowtowncoder Any additional data required for this?

**Comment by maruthi-adithya** [comment]
Is any additional data required for this? @cowtowncoder

**Comment by ales-bulko** [comment]
Hello Maruthi,
I did not encounter this issue. Ensure you don't have getter, or any method that is returning isDeleted value. If so, anotate it with @JsonIgnore to exclude it from resulted json.

**Comment by WellingR** [comment]
Try adding
```
lombok.copyableAnnotations += com.fasterxml.jackson.annotation.JsonProperty
```
to your lombok.config file.  This will ensure that the generated getters and setters will also receive the `@JsonProperty` annotation

**Comment by cowtowncoder** [comment]
Thank you @WellingR ! 

I will close this issue as I do not see anything that can be done on Jackson side, but I hope this comment helps in working around such issue on Lombok side.
