### ISSUE TITLE
setSerializationInclusion(Include.NON_EMPTY) not excluding Nulls in arrays.

### ISSUE THREAD

**Issue by Daisuke88** [FasterXML/jackson-databind#2143]
Hello!

I've tested a few ways to  remove Null values in my java object from my output file (Json).
However, there seems to be some that are missed.

I've tried the following:
  objectMapper.setSerializationInclusion(Include.NON_NULL);
  objectMapper.setSerializationInclusion(Include.NON_EMPTY);
  @JsonInclude(Include.NON_NULL);

These have removed around 2150 nulls from the output file.
However, the results still have some that are present in the form of:
        "Order1" : [ null, null, null, null, null, null ],
        "Order2" : [ null, null, null, null, null, null ],

Is this an existing issue?
My assumption is that I've used the wrong implementation of Include, but wanted to check with current issues as well.

**Comment by cowtowncoder** [comment]
This is by definition: `null` exclusion does not apply to contents arrays or `Collection`s, only to values of `Map`s or POJOs. There is currently no way to do such exclusion.

**Comment by cowtowncoder** [comment]
@Daisuke88 This is bit un-intuitive part of API. It would be nice to figure out a way to allow such suppression, but arrays/Lists are bit different wrt usage than Maps (index by position, not key), and so it is not possible to add exclusion without significant change to behavior.

**Comment by Daisuke88** [comment]
ok thanks @cowtowncoder !
