### ISSUE TITLE
Add `JsonNode.optional(String name)` and `JsonNode.optional(int index)` to be able to get an Optional `JsonNode`

### ISSUE THREAD

**Issue by burdoto** [FasterXML/jackson-databind#2145]
**NOTE**: considered part of [JSTEP-3](https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-3)

-----

So I had this idea of how nice it would be to have a getter method that returns an optional JsonNode, like `#path(String name)` does, but when returning an Optional, it would be simpler to only use a node when its actually present, or handle cases that its not present in.

Current Solution:
```java
this.guild = data.has("guild_id") ? discord.getServer(data.get("guild_id").asLong()) : null;
```

With optional nodes:
```java
this.guild = data.getOptional("guild_id").map(node -> discord.getServer(node.asLong())).orElse(null);
```
In this scenario, the difference is counter intuitive, because I can use a ternary-if in this case.
See this scenario:
Without the addition:
```java
        long afkChannelId = data.path("afk_channel_id").asLong(-1);
        if (afkChannel == null || afkChannel.getId() != afkChannelId) {
            afkChannel = afkChannelId == -1 ? null : discord.getChannelCache()
                    .getOrRequest(afkChannelId, afkChannelId);
            traits.add(AFK_CHANNEL);
        }
```
With the addition:
```java
        Optional<JsonNode> node = data.getOptional("afk_channel_id");
        if (afkChannel == null || node.map(idN -> idN.asLong() == afkChannel.getId()).orElse(false)) {
            afkChannel = node.map(json -> discord.getChannelCache().getOrRequest(json.asLong(), json.asLong())).orElse(null);
        }
```
I think this scenario could show why the addition could be helpful.
If this idea gets approved and it is wished for; I could work on a PR myself.

**Comment by burdoto** [comment]
I am already aware of the missingnode technique, I just feel that my optional-variant is missing.
What if you're trying to get an optional int node, and set it to null if it's not there?
You can't pass `null` to the `#asInt(int)` method, as primitives cannot be really "null" in that kind of sense
yet you might want to have it be `null` if it's unavailable.
With the optional variant you could do ```java
node.optional("uses").orElse(null)
```
Where with the current version, the smallest solution to this is to use a ternary with `node.has("uses")`,which also means you have to either store the node of "uses" or access it at least twice

**Comment by burdoto** [comment]
Parallel to that, what about a method `orNull()` that either gets the actual value of the node or null?

**Comment by cowtowncoder** [comment]
I don't think I want `asIntOrNull()` since that opens doors to combinatorial explosion (for different types).
Back to optional: there are `asInt(defaultValue)` and similar variants that should cover use cases.

But perhaps adding simple `optional(key)` and `optional(index)` would make sense for inter-operability: there are many Java APIs (streaming most notably) that would benefit, and adding that would be trivial.

**Comment by burdoto** [comment]
Question:
Is there a way to use 3.x before release already?

**Comment by JooHyukKim** [comment]
Lemme start this one if no one has started?
Seems like a good start for picking up JSTEP-3

Wrt implementation details, would be one PR seems okay? Including following tasks

- Add `JsonNode.optional(String name)` and `JsonNode.optional(int index)`
- Add appropriate implementations in subclasses
- Write `optional()` tests in the one isolated class. We may try find default-test-class for each JsonNode-subclasses but idk.

**Comment by cowtowncoder** [comment]
Sounds good. The only (?) open question -- which I should have noted here -- is the naming.
While `optional()` is a reasonable possibility, I think there are 2 possible alternatives to consider:

* `opt()` -- shorter, if that matters, comparable to `get()` and `path()` (which this new method is similar to)
* `getOpt()` -- same length, but would be grouped next to `get()` in Javadocs (and IDE auto-completion), which might be desireable.

WDYT @JooHyukKim, @pjfanning, @yawkat ?

**Comment by JooHyukKim** [comment]
Hmmm I was actually 50/50 on 'getOptional()' vs 'optional()'. Atm I am more concerned about users complaining about lack of intuitiveness ("what does opt mean?") rather than method name being too long. But I'm open to other suggestions as well.

But with the current PR I chose to follow the title.

**Comment by cowtowncoder** [comment]
Makes sense. Let's see what others think.

Also creating some more issues for simple work:

* https://github.com/FasterXML/jackson-databind/issues/4867: `JsonNode.asOptional()`

**Comment by burdoto** [comment]
it should be put into consideration that a method name `getOptional` would be relevant for property scanners and property based DSLs, such as groovy

**Comment by JooHyukKim** [comment]
@burdoto Good point, traditional get-ter names are too easily exposed literally anything...
+1 on not adding `getXxx` prefix.

**Comment by JooHyukKim** [comment]
Also I just realized this change is going into 2.19 as well... meaning coming up with best name is quite important.

**Comment by cowtowncoder** [comment]
Ok yes, I think going with `optional()` makes sense.
