### ISSUE TITLE
2.9.x Breaks Backwards Compatibility - Multiple Issues Reported

### ISSUE THREAD

**Issue by EarthCitizen** [FasterXML/jackson-databind#2148]
Reviewing the issues there are multiple cases of 2.9.x breaking backwards compatibility with 2.8 and previous:

#2147
#2134
#2111
#2136
#2100

2.9 should, by contract of semantic versioning, have backwards compatibility with all previous minor versions.

According to https://semver.org, minor version changes should:

> MINOR version when you add functionality in a backwards-compatible manner

**Comment by cowtowncoder** [comment]
Please do not file such issues; if you want to discuss changes, mailing lists is the place.

**Comment by EarthCitizen** [comment]
I may be overlooking that, but where would I find the information on those mailing lists?
