### ISSUE TITLE
[idea] Add method #arrayNode(Collection) to acquire a pre-filled array node from a Collection

### ISSUE THREAD

**Issue by burdoto** [FasterXML/jackson-databind#2151]
The title says it all already

Basically the idea is to have a method to create a prezsized, filled array node from any kind of collection. 
I have a similar implementation in this file 

  
  ~~https://github.com/CrystalShardDiscord/CrystalShard/blob/development/src/main/java/de/kaleidox/util/helpers/JsonHelper.java~~ (dead link, scroll down) already, it might be a good thing to have for some people.

Analogue to that, I thought about the #objectNode and the #nodeOf method from that class I linked.

**Comment by cowtowncoder** [comment]
@burdoto That links seems to be dead?

**Comment by burdoto** [comment]
@cowtowncoder im afraid I forgot to update it after updating.
New link is https://github.com/CrystalShardDiscord/CrystalShard/blob/development/src/main/java/de/kaleidox/crystalshard/util/helpers/JsonHelper.java
