### ISSUE TITLE
Add `JsonMapper` to replace generic `ObjectMapper` usage

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2153]
Due to problems with trying to override builder factory for `ObjectMapper`, and introduction of JSON-specific format features (`JsonReadFeature`, `JsonWriteFeature`), it is necessary to introduce separate `JsonMapper`, to be used instead of `ObjectMapper`.
With this (and related Smile, CBOR additions), there will now be format-specific mapper subtype for all formats. `ObjectMapper` will still exist, and may even be instantiated (more so with 2.10, less with 3.x), but usage should move over to specific mappers for 3.x.

**Comment by JooHyukKim** [comment]
Try looking for some sort of copy method in ObjectMapper @IEnoobong

**Comment by IEnoobong** [comment]
@JooHyukKim thanks, there's one but it doesn't return a `JsonMapper`

**Comment by cowtowncoder** [comment]
Just cast it: return type of `copy()` in `ObjectMapper` has to be plain `ObjectMapper`, but if you call it on `JsonMapper`, it'll be copied as `JsonMapper`.

But also note that as things are, there is no additional functionality in `JsonMapper` over `ObjectMapper` (but there are other format-specific subtypes that obviously behave differently).

I could add a co-variant override in `JsonMapper` tho, which would help here.

**Comment by IEnoobong** [comment]
Thanks @cowtowncoder 

I did this

```java
  public JsonMapper httpObjectMapper() {
    var copy = (JsonMapper) objectMapper.copy();
    return copy.rebuild()
        .propertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
        .enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS)
        .enable(EnumFeature.WRITE_ENUMS_TO_LOWERCASE)
        .build();
  }
```

But getting this error

```Caused by: java.lang.ClassCastException: class com.fasterxml.jackson.databind.ObjectMapper cannot be cast to class com.fasterxml.jackson.databind.json.JsonMapper (com.fasterxml.jackson.databind.ObjectMapper and com.fasterxml.jackson.databind.json.JsonMapper are in unnamed module of loader 'app')```

**Comment by cowtowncoder** [comment]
Ok, please file an issue with full reproduction

**Comment by cowtowncoder** [comment]
Cannot reproduce the issue with 2.17, fwtw.

**Comment by IEnoobong** [comment]
@cowtowncoder thanks for your response, the issue rather is `JsonMapper` is a super class of `ObjectMapper` not a subclass hence `ObjectMapper` cannot be cast to `JsonMapper` which is what I was trying to do.

**Comment by JooHyukKim** [comment]
I see what your problem is now. I don't see direct way of copying.
Maybe we could add `new JsonMapper(ObjectMapper)` for such use case? 🤔

**Comment by JooHyukKim** [comment]
I see what your problem is now. I don't see direct way of copying.
Maybe we could add new JsonMapper(ObjectMapper) for such use case? 🤔
WDYT @cowtowncoder ?

**Comment by cowtowncoder** [comment]
> @cowtowncoder thanks for your response, the issue rather is `JsonMapper` is a super class of `ObjectMapper` not a subclass hence `ObjectMapper` cannot be cast to `JsonMapper` which is what I was trying to do.

No. `JsonMapper` is a sub-class, `ObjectMapper` super class.
But correct, you cannot cast `ObjectMapper` that is not `JsonMapper` into `JsonMapper`.

Next time please include some code actually evaluate what you are trying to do -- that makes misunderstandings less likely.

**Comment by cowtowncoder** [comment]
@JooHyukKim No; I thought about that in the past, but things get rather complicated quickly in 2.x, wrt configuration. It would be very difficult to ensure everything is properly copied.

We could consider this for 3.0 where things are bit cleaner as `ObjectMapper` subtypes are immutable.
