### ISSUE TITLE
ExceptionInInitializerError for Android API level 8

### ISSUE THREAD

**Issue by friederbluemle** [FasterXML/jackson-databind#216]
Hi,

After upgrading to 2.2.1 the app crashes when calling new ObjectMapper() with the following exception:
05-08 23:06:21.004: E/AndroidRuntime(367): FATAL EXCEPTION: Thread-12
05-08 23:06:21.004: E/AndroidRuntime(367): java.lang.ExceptionInInitializerError
05-08 23:06:21.004: E/AndroidRuntime(367):  at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:438)
05-08 23:06:21.004: E/AndroidRuntime(367):  at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:364)

It works fine for newer Android API levels, but because we still need to support API level 8 we had to revert the library version to 2.1.4
Any idea why this is happening and if there is a workaround/fix?

Thanks,
Frieder

**Comment by johnjohndoe** [comment]
@cowtowncoder Can you please point me to where the Android API level restriction is documented?

**Comment by cowtowncoder** [comment]
@johnjohndoe I don't think anything has been written within Jackson repos. Would live to add links to external resources if anyone finds -- I do not have an opportunity to work an Android at work so I can't help a lot here, but at least I could curate documentation.
