### ISSUE TITLE
StringIndexOutOfBoundsException with empty string

### ISSUE THREAD

**Issue by joaoe** [FasterXML/jackson-databind#2166]
**The problem**

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
  at java.lang.String.charAt(String.java:658)
  at com.fasterxml.jackson.databind.util.StdDateFormat._parseDate(StdDateFormat.java:405)
  at com.fasterxml.jackson.databind.util.StdDateFormat.parse(StdDateFormat.java:358)
```

**The testcase**

```
public class MyTestCase {
  public static void main(String[] args) throws ParseException {
    new StdDateFormat().parse("");
  }
}
```
**Expected**
A `ParseException` instead

**The location** 
`dateStr.charAt(0)`
https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/util/StdDateFormat.java#L368

**Suggestion**
Perhaps replace it with `dateStr.startsWith("-")`

**Comment by cowtowncoder** [comment]
`StdDateFormat` is not a class that anyone outside of jackson core should be using, so I am bit curious as to how you bumped into it? It's not a good thing to NPE on empty String, of course, just interested in knowing how this came up.

**Comment by joaoe** [comment]
> I am bit curious as to how you bumped into it?

1. https://www.baeldung.com/jackson-serialize-dates
```
ObjectMapper mapper = new ObjectMapper();
mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
mapper.setDateFormat(new ISO8601DateFormat());
```

2. in `ISO8601DateFormat.java`
```
@deprecated Use {@link com.fasterxml.jackson.databind.util.StdDateFormat} instead
```

I'd actually prefer if `ISO8601DateFormat` was not deprecated or if `StdDateFormat` allowed for strict parsing. Because right now, `StdDateFormat` also accepts dates only (year-month-day) and timestamps as strings.

**Comment by cowtowncoder** [comment]
Actually what I meant was usage: users are never expected to use `StdDateFormat` directly -- and Jackson itself should not attempt to parse empty String with it. So I was hoping for a reproduction that used Jackson public API directly: `StdDateFormat` is considered internal implementation detail and not part of public API. It is also not meant as general-purpose `DateFormat` implementation for anyone to use outside Jackson.

As to `ISO8601DateFormat`: it is not clear why it was ever added, as Jackson does not use it, and similar to `StdDateFormat`, it was not intended to be exposed as general-purpose `DateFormat`. It is unfortunate it was included at all.

Having said that: use of alternate, custom `DateFormat` instances is perfectly fine and supported. It is just not intention that Jackson's internal implementation be used as base classes.

**Comment by joaoe** [comment]
Ok, what is the official way to trigger strict parsing of ISO dates ?

**Comment by cowtowncoder** [comment]
@joaoe Depends on what specifically you mean by strict parsing: one way is to specify custom `DateFormat`, set its leniency to false.

It is also possible to use

    @JsonFormat(lenient = OptBoolean.FALSE)

for specific properties, to effectively call `setLenient(false)` on `DateFormat` that is used for that field.
Further, config override can be applied to type:

   mapper.configOverrides(Date.class)
      .setFormat(JsonFormat.Value.forLeniency(false));

which is then same as adding equivalent annotation on all `Date` valued properties.
