### ISSUE TITLE
SqlDateSerializationTest.testSqlDateConfigOverride is time zone sensitive

### ISSUE THREAD

**Issue by tbartley** [FasterXML/jackson-databind#2178]
Executing SqlDateSerializationTest.testSqlDateConfigOverride in time zones with offset > 0 (e.g. Australia where I am at +10:00) fails because, unlike testPatternWithSqlDate above it in the same test class, it doesn't tell the object mapper to use the system's default time zone instead of UTC.

It fails with the error:

  SqlDateSerializationTest.testSqlDateConfigOverride:106->BaseTest.assertEquals:198 expected:<"1980+04+1[4]"> but was:<"1980+04+1[3]">

Setting mapper's time zone to system default resolves the issue. I'll submit a PR.

**Comment by cowtowncoder** [comment]
I think this was fixed, closing.
