### ISSUE TITLE
SqlDateSerializer does not obey SerializationConfig.Feature.WRITE_DATES_AS_TIMESTAMPS

### ISSUE THREAD

**Issue by BrentDouglas** [FasterXML/jackson-databind#219]
This can result in inconsistent serialization of date depending on their origin.

**Comment by cowtowncoder** [comment]
One relevante note: as of Jackson 2.6, it is possible to use `@JsonFormat(shape=JsonFormat.Shape.NUMBER)` to force serialization of `java.sql.Date`s as timestamps. Plan is to also allow some way to define per-type format defaults, to allow overriding global defaults.

I am still not sure whether the global default itself should be changed, leaving this issue open.

**Comment by cowtowncoder** [comment]
And with Jackson 2.8, it is possible to specify "config overrides", using `ObjectMapper.configOverrides().setFormat()`.

But perhaps we could actually change defaults for 2.9, finally.

**Comment by PatrickGotthard** [comment]
Hi, is this the correct config to restore the default behaviour of 2.8.x in 2.9.x?
```
final ObjectMapper mapper = new ObjectMapper();
mapper.configOverride(java.sql.Date.class).setFormat(JsonFormat.Value.forPattern("yyyy-MM-dd"));
```

**Comment by cowtowncoder** [comment]
@PatrickGotthard For example, although use of `shape` does allow switching between number/String representation. Setting of pattern does implicitly also choose `String` so yes that should work.

**Comment by cowtowncoder** [comment]
@bkrieger Sounds plausible. Could you please file a new issue, so it's easier to track fixes.

**Comment by bkrieger** [comment]
Done, https://github.com/FasterXML/jackson-databind/issues/2064.

**Comment by kokliang** [comment]
Would this be considered a breaking change or incompatibility migrating from jackson-databind 2.8 to 2.9?
