### ISSUE TITLE
Partial updates

### ISSUE THREAD

**Issue by raderio** [FasterXML/jackson-databind#2198]
Is it possible to add support for partial updates like in https://medium.com/workflowgen/graphql-mutations-partial-updates-implementation-bff586bda989

The main idea is that in JavaScript are value like `undefined`.
So, you can check if a parameter was not provided and do not update the field in database.

**Comment by cowtowncoder** [comment]
Please do not use issue tracker for asking usage questions. That is what mailing lists (https://groups.google.com/forum/#!forum/jackson-user) and gitter (https://gitter.im/FasterXML/jackson-databind) -- for example -- are for.

**Comment by raderio** [comment]
`Optional` fits ok with our case. Just need another thing https://github.com/FasterXML/jackson-databind/issues/2200
