### ISSUE TITLE
How to convert JsonNode to ObjectNode

### ISSUE THREAD

**Issue by ekko100120** [FasterXML/jackson-databind#2199]
I  want to partly modify  some field value in a json file without  entity class , so i have to use JsonNode to convert to ObjectNode.
 but when i attempt to do this way, it throw a exception:`Caused by: java.lang.ClassCastException: com.fasterxml.jackson.databind.node.TextNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode
`

so how can i resolve this problem,or is there any other method to partly update json file without  entity class

**Comment by cowtowncoder** [comment]
Great question to ask on a proper forum, like

https://groups.google.com/forum/#!forum/jackson-user

or

https://gitter.im/FasterXML/jackson-databind
