### ISSUE TITLE
Question: nullable & optional/required marks

### ISSUE THREAD

**Issue by raderio** [FasterXML/jackson-databind#2200]
Can we represent that a field is non-nullable & optional?
this mean, or we send a data for the field, or just do not send the field in request, null is not allowed.
`{"foo": "bar", "baz": true}` is allowed
`{"baz": true}` is allowed, because is optional
`{"foo": null, "baz": true}` is NOT allowed, because is non-nullable

Basically `null` has the meaning of "this property existed before, and I want to nullify its value". If there's no value, or the value needs not change (for requests, for example), it just shouldn't be sent.

**Comment by cowtowncoder** [comment]
In future, please use mailing list (https://groups.google.com/forum/#!forum/jackson-user) or Gitter for questions; and issue tracker for reporting issues or requesting new features.

But yet, it is possible to add special handling for `null`s for given field: see `@JsonSetter(nulls = Nulls.FAIL);` -- unit tests show usage, and it is explained a bit on:

https://medium.com/@cowtowncoder/jackson-2-9-features-b2a19029e9ff

This was added in Jackson 2.9.

**Comment by raderio** [comment]
I mean may be to add a new property in `@JsonProperty`? Just like `required`, to add new one `nullable`.

**Comment by raderio** [comment]
They do not overlap, required means it should be present in json, nullable means it can have null as value.
