### ISSUE TITLE
Fail on unknown property with Class inheritance is not working 

### ISSUE THREAD

**Issue by danieldonev** [FasterXML/jackson-databind#2206]
Hello,
**Setup**
I have this in my `application.properties`

`spring.jackson.deserialization.fail-on-unknown-properties=true`

I have Parent abstract class `DTO` and multiple classes which are extending it.

**The problem:**
When I add extra JSON property to child class - Jackson is NOT throwing an exception.

When I add extra JSON property to another class, which is NOT a subclass of DTO - Jackson is throwing an exception.

Any idea why Jackson if behaving like that in my case ?

**Comment by cowtowncoder** [comment]
First of all: sub-classing should not have effect on global settings with Jackson ObjectMapper.

This sounds like a Spring usage/configuration question, so you may want to start with Spring group of some kind.

If not, what would be needed here is a reproduction, with code (ideally unit test) that does not use Spring. That helps isolate problem to Jackson side.
With that code I could probably explain what is happening.

I hope this helps.

**Comment by danieldonev** [comment]
The problem is coming from `ResourceSupport` which my DTO implements. And apparently HATEOAS is having their own ObjectMapper settings, which ignore the one in application.properties.

Thank you for the help.

**Comment by cowtowncoder** [comment]
@danieldonev that makes sense, thank you for updating the issue.

**Comment by cowtowncoder** [comment]
@danieldonev Not sure what you are referring to? `2.9.8` was just released, but what issue are you thinking of?
