### ISSUE TITLE
Reconsider "ISO8601" deprecation or provide ECMAScript 5 ISO8601 Subset Format

### ISSUE THREAD

**Issue by rcollette** [FasterXML/jackson-databind#2207]
From Wikipedia (not the RFC but by this point one would hope it is representative), ISO8601 UTC date times (offset of zero) can be represented with:

>An offset of zero, in addition to having the special representation "Z", can also be stated numerically as "+00:00", "+0000", or "+00"

However, the ECMAScript5 spec states that date serialization is based on a subset of the ISO8601 standard with Z being used for UTC and +00:00 format being the only numeric format used for other zones.  

See:
https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15
https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.5.43
https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.5.44

This explains some of the confusion in
https://github.com/FasterXML/jackson-databind/issues/1624

And while UTC (offset zero) can be represented with the various "zero" forms according to ISO8601 and some browsers may correctly parse the full ISO8601 standard (I believe Chrome does), from a practical perspective browsers are still in use that only serialize UTC dates that have a Z and will fail with other zero offset formats.   This is one specific user-agent that I have on hand but I have seen others, that fail (IE 11?)
>Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.34 (KHTML, like Gecko)

The preferred serialization format for UTC in Chrome.. as seen from the Chrome console
```
JSON.stringify(new Date)
""2018-12-13T05:38:43.273Z""
```

And for this reason we continue to use the deprecated ISO8601DateFormat.

```
    @Bean
    public ObjectMapper getObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        // setup the ISO8601 output format with the trailing Z instead of hour difference to support Connect+
        // this is compatible with default Jackson Date deserialization
        mapper.registerModule(new JavaTimeModule());
        mapper.registerModule(new Jdk8Module());
        mapper.setTimeZone(TimeZone.getTimeZone("UTC"));
        SimpleModule module = new SimpleModule();
        module.addDeserializer(Locale.class, new LocaleDeserializer());
        module.addSerializer(Locale.class, new LocaleSerializer());
        mapper.registerModule(module);
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        mapper.setDateFormat(new ISO8601DateFormat());
        // enforce order of properties to provide consistent ETags
        mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
        return mapper;
    }
```
It would be helpful to have some format whether it is the existing one, some particular configuration of the standard format, or something entirely new that makes the Z preferred when serializing a UTC date (something like EcmaScript5ISO8601Subset if it is not entirely accurate to call it ISO8601).

**Comment by plokhotnyuk** [comment]
@rcollette use `java.time.Instant` for that `Z`

**Comment by rcollette** [comment]
We definitely use Instant for anything new but it's not reasonable for an organization to have to replace all Date usage with Instant.

Now if by deprecated, this means the project will be carrying the existing format so long as Java does, then that's fine, this is a moot issue and it can be closed.   Explaining that intent somewhere might be helpful to allay the concerns others may have with this.

If on the other hand the intent is to actually remove it prior to Java removing it, then my concern remains.

JSON date serialization has been wrought with confusion and ambiguity historically.   If nothing else, documenting how the ECMAScript subset scenario is satisfied might not be bad, whether that is through documentation or unit tests.   I wasn't able to find the use of Instant in the project at all, nor was I able to find a unit test where the Z form of UTC/zero offset serialization is an expectation (it's possible I skipped over it by accident, I searched on "z" and because tz is everywhere there are quite a few of them).   

So my impression, write or wrong, is that a fairly standard use case from the browser perspective is not called out in any way and that generally continues the confusion.

As an individual, I can obviously work around this by preserving the original formatter in my own code base if need be.   Generally projects have an interest in addressing the concerns of their users so I present this for discussion.

**Comment by cowtowncoder** [comment]
@rcollette  If you want to keep using `ISO8601DateFormat`, feel free to copy the code, and keep using it.
The reason for removal was that it was not used by databind at all, and I was puzzled as to why it was there, and why it was added originally (as far as I know it literally was never linked to main date/time types).

It is unfortunate that users found it, and I assume there has been external documentation suggesting its use.

Now: if request was for specific feature -- I know it is included in description , but as separate "There should be a way to do X" -- I'd have no problem considering that. I just do not want to add another not-integrated `DateFormat`. There should be better ways for configuration, either via format strings, or feature(s).

**Comment by rcollette** [comment]
Thanks @cowtowncoder .   I'll give the feature request wording a go when I get a moment.
