### ISSUE TITLE
How recursively update embedded objects on deserialization into existed object instead of rewrite it?

### ISSUE THREAD

**Issue by human453453467** [FasterXML/jackson-databind#2213]
I'll show you an example:

valueToUpdate: (readerForUpdating)
```
class Person{
    String name;      //"Michael"
    Address address;
}

class Address{
    String street;    //"Kitano"
    Integer home;     //5
}
```
source: (readValue)
```
{
    name: "Bob"
    address: {
                 street: "Abbey Road"
                 //!!! there is no 'home' value !!! 
             }
}
```
and as a result i want get:
```
class Person{
    String name;      //"Bob"
    Address address;
}

class Address{
    String street;    //"Abbey Road"
    Integer home;     //5 - !!! the value remains the same !!!
}
```

Can I get similar functionality using Jackson? What do I need to use? I can close this issue by myself. I only need clues for find needed objects.

**Comment by cowtowncoder** [comment]
Check out:

https://medium.com/@cowtowncoder/jackson-2-9-features-b2a19029e9ff

section about "Merging". There is new `@JsonMerge` annotation, as well as alternate settings, which allow deep merging which I think you are looking for.

And in future, please use Jackson mailing lists or Gitter.

**Comment by human453453467** [comment]
@cowtowncoder 
Thank you very much!
