### ISSUE TITLE
`DeserializationProblemHandler.handleUnknownTypeId()` returning `Void.class`, enableDefaultTyping causing NPE

### ISSUE THREAD

**Issue by MeyerNils** [FasterXML/jackson-databind#2221]
Returning Void.class from com.fasterxml.jackson.databind.deser.HandleUnknowTypeIdTest.testDeserializationWithDeserializationProblemHandler().new DeserializationProblemHandler() {...}.handleUnknownTypeId(DeserializationContext, JavaType, String, TypeIdResolver, String) is causing a NPE in jackson 2.9. I'll provide a pull request illustrating the issue in a test.

**Comment by cowtowncoder** [comment]
Thank you for reporting this! I'll have a look.
