### ISSUE TITLE
@JsonSerialize bug - not handling interfaces properly.

### ISSUE THREAD

**Issue by bmiddleb** [FasterXML/jackson-databind#2224]
jackson 2.9.6
spring-boot 2.0.5

[JacksonSerializationBugExampleCode.zip](https://github.com/FasterXML/jackson-databind/files/2753453/JacksonSerializationBugExampleCode.zip)

I have a JavaBean called Everything that contains 3 fields and implements interfaces IF1, IF2, and IF3. I am controlling access so that IF1 exposes all 3 fields, IF2 exposes 2 fields, IF3 exposes 1 field. 

In the following code, I create a ResponseEntity using IF2. However, Jackson **serializes using the scope of the underlying class** although it was handed type IF2. This is a bug. 

  @GetMapping("t2")
  @ResponseBody
  public ResponseEntity<IF2> getIF2() {
    **IF2 if2** = new Everything();
    return new ResponseEntity<>(**if2**, HttpStatus.OK);
  } // Doesn't return IF2, returns Everything

It doesn't make sense for any method to be handed a type and arbitrarily choose to work on the underlying implementation class rather than limiting itself to the type specified. This is like passing an argument of type List and coding as though I got an ArrayLIst.

@JsonSerialize appears to be a way of working around this bug. However, it also doesn't work correctly. For example, in this case, only the first interface listed in Everything's "implements" clause is used to serialize regardless of whether you specify another interface in that clause.

In order to deal with these 2 design defects I have to create a view description class, circumventing the purpose of using interfaces, and clutter up everything with annotations.

**Comment by cowtowncoder** [comment]
I would need a stand-alone reproduction not relying on Spring code (and especially not Lombok -- I don't debug Lombok issues): this to isolate where the problem arises.
One to note, in particular, is that Jackson can only handle annotations in types it is passed (values): but if, for example, you annotate a REST endpoint, it is up to Spring (or whatever framework handles binding there) to pass any information as Jackson is typically only passed value taken or returned, and not information on method that is called by framework.
