### ISSUE TITLE
Type id not provided on `Double.NaN`, `Infinity` with `@JsonTypeInfo`

### ISSUE THREAD

**Issue by C-B-B** [FasterXML/jackson-databind#2236]
When using polymorphic serialisation with @JsonTypeInfo, e.g. on a Collection of Objects, the type information is sent with the values to ensure correct deserialisation. Doubles (and others like Strings) don't get their types included given they are considered the default deserialisation type. This causes problems for Double.NaN, Double.POSITIVE_INFINITY and Double.NEGATIVE_INFINITY as they get deserialised into strings rather than Double.

Would it make sense to include the type for these three Double values to ensure they can also be correctly deserialised (I tested that the deserialisation works correctly if the type is included in the data)?

(Using 2.9.8)

Thanks!
CBB

**Comment by C-B-B** [comment]
Thanks @cowtowncoder .
For reference, started a [discussion](https://groups.google.com/forum/#!topic/jackson-user/oKsEJPs1Joo) in the forum on an intermediate workaround, as well as a repro of the issue.

**Comment by antoinetran** [comment]
Hi @cowtowncoder , is-it possible to have the same fix related to Float? Or is-it already working? Thank you!

**Comment by antoinetran** [comment]
Oh, I can see that this is already fixed for float, I believe.
I use 
```
	<dependency>
		<groupId>com.fasterxml.jackson.core</groupId>
		<artifactId>jackson-databind</artifactId>
		<version>2.9.8</version>
	</dependency>
```
and Float.NaN gets serialized as:
`["[[F",[["[F",["NaN"`
and gets deserialized as Float.NaN, so this is good.  I should try with Double later.
