### ISSUE TITLE
Add new `JavaType` to support container-like, Iterable types (like `Stream`)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2246]
So: it seems like things like `Iterator`, `Iterable`, `Stream` should be recognized as special `JavaType` of their own, similar to `ReferenceType`. Whether this new type should be considered `CollectionLike` or at least "container type" is an open question -- probably at least latter.

**Comment by cowtowncoder** [comment]
Looks like this was a duplicate for #3950 (add `IterationType`) -- while that was never, it is marked as implemented in release notes so let's close this one.

**Comment by OrangeDog** [comment]
N.B. `Iterable` was never added: #4443
