### ISSUE TITLE
Feature Request: Add getParent() to JsonNode

### ISSUE THREAD

**Issue by BELUGABEHR** [FasterXML/jackson-databind#2250]
When using ObjectMapper#getTree(), I would like to have a getParent() capability on the JsonNode so that if I am traversing a tree, and find a node of interest (validation), I can output the full path to the node:

root.person.info.age
or
/person/info/age
or
depth: 3 would also be helpful

**Comment by cowtowncoder** [comment]
Unfortunately this is not possible as parent linkage does not exist. Design decision early on was to avoid double-linkage (parent and children), as trade-off would be to have heavier state, more complicated synchronization, and inability to share nodes (with child-linkage some nodes -- `NullNode`, boolean true/false, "missing" node -- are singletons).

So, although I agree that if possible that would be nice, this can not be implemented without complete rewrite of node system, and that is not something I think makes sense.
