### ISSUE TITLE
Jackson-Kotlin-Module is broken due to Recent Databind build

### ISSUE THREAD

**Issue by deeyes24** [FasterXML/jackson-databind#2262]
Hi ,
The latest Jackson Kotlin module found here https://github.com/FasterXML/jackson-module-kotlin is broken with Compilation Errors. 

When I tried to build that project, it does not compile due to changes in com.fasterxml.jackson.databind
package.
The _Module_  class which defines the _SetupContext_ interface used to have a setMixInAnnotations  but the latest build does not have that.

Also, the  _AnnotationIntrospector_ used to have a **hasCreatorAnnotation** but it does not have that now.  

Also, the **ObjectMapper** class (from the latest build) seems not to have the registerModule method.

Please advise about these changes and how to fix them in Jackson Kotlin Module

**Comment by cowtowncoder** [comment]
@deeyes24 you will probably want to build from `2.10` or `2.9` branches, depending on what kinds of changes you are thinking. `master` is for Jackson 3.0.0, not due release for months. Any fixes to 2.9.x releases would need to go in `2.9` (and merged forward to 2.10, master), and changes for upcoming 2.10.0 into `2.10` branch.

Kotlin module itself needs work to be able to work with 3.x but that is bigger change: changes are major and backwards-incompatible regarding how mapper instances are configured (using new ObjectMapper.Builder approach). Builders will be added in 2.10 too, so some of codebase may be upgraded in 2.10.

**Comment by cowtowncoder** [comment]
I fixed some of the issues, but `master` is still missing couple of things. But this is something for Kotlin module maintainers to work with, so I'll close issue here -- 3.0 is meant to be API incompatible (or conversely, need for incompatible changes drove decision to change).
