### ISSUE TITLE
Jackson is mangling Int field names or omitting them entirely.

### ISSUE THREAD

**Issue by macdanny** [FasterXML/jackson-databind#2264]
I am not sure if this is a -databind issue or a -kotlin issue.

Jackson seems to be misbehaving when confronted with Int fields. I have three instances representing two different failures. I believe they are all related and so am reporting them in a single issue.

Case 1: Field being omitted by Jackson.

    data class AuthenticationRequest(
      @JsonProperty("providerURL") val providerUrl: String,
      @JsonProperty("UserName") val userName: String,
      @JsonProperty("Password") val password: String,
      @JsonProperty("ip") val ip: String,
      @JsonProperty("isMobile") val mobile: Int
    )

The preceding data class works propertly. However if the name of the "mobile" field is siwtched to "isMobile", Jackson will omit it from the output. At first I thought it was because the convention for JavaBeans is that "isXxx" fields are booleans and this is an Int ... now I am not sure. In any case, I had to rename it to a value different from the value of the @JsonProperty attribute in order for the serialization to work. I also tried omitting the annotation but the effect was the same as if the annotation and the field were both named "isMobile". This is how it looks:

    {"providerURL":"██","UserName":"██","Password":"██","ip":"0.0.0.1"}

Case 2: Field names being mangled by Jackson.

    data class ListRequest(
      @JsonProperty("AuthToken") val authToken: String,
      @JsonProperty("drModifications") val drModifications: DateRange?,
      @JsonProperty("filters") val filters: List<ListRequestFilter>,
      @JsonProperty("nFirstRow") val firstRow: Int,
      @JsonProperty("nRows") val rows: Int,
      @JsonProperty("sorting") val sorting: List<ListRequestSort>,
      @JsonProperty("ProjectID") val projectId: String
    )

The preceding class works. However if the "firstRow" field is renamed to "nFirstRow", or the "rows" field is renamed to "nRows", Jackson mangles the names when serializing. "nFirstRow" becomes "nfirstRow" and "nRows" becomes "nrows". In addition to renaming the fields, it also changes their order in the serialized output -- it moves them to the end, after the other fields. I tried omitting the annotation but as with the first case, it did not make any difference to the behaviour. This is how for example it is serializing if the "rows" field is renamed to "nRows" ... I have only adjusted the formatting to make it easier to see:

    {
      "AuthToken": "",
      "drModifications": {"Start": null,"End": null},
      "filters": [],
      "nFirstRow": 0,
      "sorting": [{"FieldName": "ID","Direction": "Ascending"}],
      "ProjectID": "",
      "nrows": 50
    }

It seems as though Jackson is allowing its own naming rules to override the annotations if they agree with the field names. It should not be doing that. If the annotation is present, Jackson should look no further when deciding how a field should be named when serialized.

These are my Jackson versions. I have also tried 2.9.7 with no change in behaviour.

./jackson-annotations-2.9.8.jar
./jackson-core-2.9.8.jar
./jackson-databind-2.9.8.jar
./jackson-datatype-joda-2.9.8.jar
./jackson-module-kotlin-2.9.8.jar

The entirety of my use case is that I am invoking a REST API provided by someone else. I am using Retrofit for this purpose. This is how the moving parts are being assembled:

    val okHttpClient =
      OkHttpClient.Builder()
        .callTimeout(Duration.ofSeconds(10L))
        .readTimeout(Duration.ofSeconds(10L))
        .addInterceptor(HttpLogger.interceptor)
        .build()
    val jackson = ObjectMapper()
      .registerModule(JodaModule())
      .registerKotlinModule()
    val retrofit =
      Retrofit.Builder()
        .client(okHttpClient)
        .baseUrl(normalizeApiUrl(providerUrl))
        .addConverterFactory(JacksonConverterFactory.create(jackson))
        .build()

**Comment by cowtowncoder** [comment]
99% certain this is Kotlin module issue, as there are reports that "isXxx()" convention (core Jackson only considers that to indicate `xxx` if type is `boolean` / `Boolean`) has issues. So would make sense to move issue under `jackson-module-kotlin`.

Alternatively if it can be reproduce with Java-only test I can have a look; but I am not aware of any issues like this for Java usage (none reported, ever, as far as I remember).

**Comment by cowtowncoder** [comment]
Needs to be refiled for `jackson-module-kotlin` if an issue does not exist (but make sure to verify: there are many issues wrt "is-getters" over there).
