### ISSUE TITLE
Allow TypeModifiers to discover where they are in the type resolution pipeline (superclass, superinterface)

### ISSUE THREAD

**Issue by phillipuniverse** [FasterXML/jackson-databind#2266]
I am trying to achieve a scenario where the `ObjectMapper` wants to read a particular type, and a `TypeModifier` swaps out that type with the one that I want. I am using Jackson 2.9.7.

Here is an example of what I am trying to achieve:

```java
public void TypeModifierTests {
    @Test
    public void jacksonDeserializesAsSubtype_concrete()
            throws JsonParseException, JsonMappingException, IOException, JSONException {
        SomeInterface domain =
                new ObjectMapper().registerModule(new TypeFactoryOverridesModule())
                        .readValue(new JSONObject()
                                .put("parentProperty", "parentValue")
                                .put("childProperty", "childValue")
                                .toString(),
                                Superclass.class);

        assertEquals(Subclass.class, domain.getClass());
        assertEquals("Overridden", ((Subclass) domain).getParentProperty());
        assertEquals("childValue", ((Subclass) domain).getChildProperty());
    }

    @RequiredArgsConstructor
    static class TypeFactoryOverridesModule extends SimpleModule {
        @Override
        public void setupModule(SetupContext context) {
            Map<Class<?>, Class<?>> overrides = new HashMap<>();
            overrides.put(Superclass.class, Subclass.class);
            context.addTypeModifier(new OverridesTypeModifier());
        }
    }


    @Data
    private static class Superclass {
        private String parentProperty;
    }

    @Data
    @EqualsAndHashCode(callSuper = true)
    private static class Subclass extends Superclass {
        private String childProperty;

        @Override
        public String getParentProperty() {
            return "Overridden";
        }
    }
}
```

When I deserialize `Superclass`, I want to actually resolve this type as `Subclass`.

I thought that the best way to achieve this was to create a `TypeModiier`, and whenever I see `Superclass`, return a `JavaType` for `Subclass` instead. Here's the `TypeModifier` (you can probably already spot the issue):

```java
public class OverridesTypeModifier extends TypeModifier {

    private final Map<Class<?>, Class<?>> overrides = new HashMap<>();

    public OverridesTypeModifier(Map<Class<?>, Class<?>> overrides) {
        this.overrides = overrides;
    }

    @Override
    // results in a StackOverflowException
    public JavaType modifyType(JavaType type,
            Type jdkType,
            TypeBindings context,
            com.fasterxml.jackson.databind.type.TypeFactory typeFactory) {
        if (type.getClass().isAssignableFrom(SimpleType.class)) {
            Class<?> rawClass = type.getRawClass();
            Class<?> overridden = overrides.get(type.getRawClass());

            // no configured override, we're fine to return
            if (overridden == null) {
                return type;
            } else {
                return typeFactory.constructType(overridden);
            }
        }
        return type;
    }

}
```

I am invoking `typeFactory.constructType()` because manual construction of `SimpleType` and friends is documented to be highly discouraged (and in most cases you can't do it). However, the `TypeFactory` goes through the `TypeModifier` pipeline to resolve super types and super interfaces, invoking my `TypeModifier` over and over, like this:

1. Check with the `TypeModifier` to get the type for `Superclass`
2. The `TypeModifier` instructs the `TypeFactory` to construct a type for `Subclass` (since it's in my overrides)
3. The `TypeFactory` determines the superclasses of `Subclass`, which is `Superclass`
4. `TypeFactory` re-invokes `_fromAny()` on `Superclass`
5. This checks with the `TypeModifier`s to construct a type for `Superclass` (again)
6. etc etc

In my `TypeModifier` if I could see if I was trying to resolve a parent class (and not the original type) I could stop the recursion and not consult the `TypeFactory` again for the superclass resolution.

**Comment by cowtowncoder** [comment]
Quick answer: this is not what `TypeModifier` was designed to be used for (if I understand your use case correctly).
`TypeModifier` is used to allow supporting "map-like" and "collection-like" types that languages like Scala (or, datatype libraries, sometimes); or to similarly detect `ReferenceType`s like `Optional`.

For changing actual type to use for deserialization, better approach is to either register deserializer that produces subtype, or, if nominal type is abstract type, provide abstract type mapping using `Module` (this is for example for `Map` -> `LinkedHashMap` mapping works: you can override this mapping easily).

**Comment by phillipuniverse** [comment]
Ah ha, ok got it, thanks for the clarification.

Likely that this might have been better suited for the Google Group then (I debated back and forth) but I appreciate the response regardless.

I did actually resolve my issue with a deserializer relatively painlessly. Here's what I did:

```java
public class OverridingAwareDeserializer extends StdDeserializer {

    private static final long serialVersionUID = 1L;
    private final Class<?> convertTo;

    /**
     * Creates the deserializer for the original deserialized from, and converts it into `convertTo`
     * 
     * @param originallyFrom the type that originally gets introspected and used as a key in the
     *        {@code typeFactory}
     * @param convertTo the class that this deserializer should actually read into
     */
    @SuppressWarnings("unchecked")
    protected TypeFactoryAwareDeserializer(Class<?> originallyFrom, Class<?> convertTo) {
        super(originallyFrom);
        this.convertTo = convertTo;
    }

    @SuppressWarnings("unchecked")
    @Override
    public Object deserialize(JsonParser p, DeserializationContext ctxt)
            throws IOException, JsonProcessingException {
        // Parse this object node into a Jackson tree
        ObjectCodec codec = p.getCodec();
        log.debug(String.format("Overriding Jackson deserialization from %s to %s", handledType(), convertTo));
        return codec.readValue(p, convertTo);
    }
}
```

In the module that I made to register it, that's where I passed in the map of overrides, looped through and registered the deserializers:

```java
public class OverridingAwareDeserializerModule extends SimpleModule {

    private static final long serialVersionUID = 1L;

    @SuppressWarnings("unchecked")
    public TypeFactoryAwareDeserializerModule(Map<Class<?>, Class<?>> overrides) {
        overrides.entrySet()
                .forEach(e -> addDeserializer((Class<Object>) e.getKey(),
                        new TypeFactoryAwareDeserializer(e.getKey(), e.getValue())));
    }

}
```

@cowtowncoder thanks for the quick response and thanks for all you do in supporting Jackson, an _essential_ part of the Java ecosystem!

**Comment by cowtowncoder** [comment]
@phillipuniverse Ah. Glad you figured out! And thank you for the compliments too :)
