### ISSUE TITLE
Renaming names with single letter words (x_coordinate)

### ISSUE THREAD

**Issue by NZhuravlev** [FasterXML/jackson-databind#2267]
## Version
2.8.11.1

## Problem

Renaming names with single letter words. For example `xCoordinate` which will be translated to `xcoordinate` (snake case).  
As far as I understood, the problem is that Java naming convention doesn't have clear instructions on acronyms and abbreviations, thus they could be called as usual words like `UrlBuilder` or capital cased like `URLBuilder`. Tokenization in the later case can't be ideal without the lexical analysis. Treating few capital letters in a row as one word means loosing single letter words though. Would be nice to have a way to customize this.  `use_std_bean_naming` doesn't help in that case.

## Possible solutions

* `lower_case_acronyms` (name stated here just for example) `MapperFeature`. `false` by default for backwards compatibility. States, that acronyms in names are used purely with only the leading letter being capital. Thus, in case of two capital letters in a row we are dealing with single letter word.

* New `PropertyNamingStrategy` which is AFAIU is worse solution, because this naming strategy isn't new, but it's a valid way of solving the problem.

**Comment by cowtowncoder** [comment]
First of all, I would need a unit test to show exactly what you mean: is this about fields or getters/setters? And if latter, what names are you trying to map to what?

Also: it could be that `MapperFeature.USE_STD_BEAN_NAMING` is relevant here.

**Comment by NZhuravlev** [comment]
@cowtowncoder as I already mentioned in the issue discussion - 
`use_std_bean_naming` solves nothing. 

Example, your pojo has `xCoordinate` field. Expected behaviour - `xCoordinate` mapped to `x_coordinate` with the PropertyNamingStrategy.SNAKE_CASE. In reality you get `xcoordinate` (independent of `
MapperFeature.USE_STD_BEAN_NAMING`)

**Comment by cowtowncoder** [comment]
Ok. True, STD_BEAN_NAMING only affects name-mangling of getters/setters; field names are passed as-is.

But I can not reproduce the problem on 2.9 by modifying `TestNamingStrategyStd` (no new fixes will be going in 2.8 except theoretically critical security patches). So I would need an actual test case -- something that points EXACT nature of the problem, and would have saved us time here.
