### ISSUE TITLE
@JsonPropertyOrder not being honored

### ISSUE THREAD

**Issue by paninics** [FasterXML/jackson-databind#2268]
Jackson version: 2.9.8

Here's a simplistic version of how to reproduce the problem. Let's say we've the following java classes:

```java
public class Base {
    protected Map<String, String> map = new HashMap<>();
}


public class Address extends Base {
    public String getAddressId() {
        return map.get("addressId");
    }

    public void setAddressId(String id) {
        map.put("addressId", id);
    }
}


@JsonPropertyOrder({ "map", "address"})
public class Person extends Base {
    private Address address = new Address();

    public String getPersonId() {
        return map.get("personId");
    }

    public void setPersonId(String id) {
        map.put("personId", id);
    }

    public Address getAddress() { return address; }
}
```
And then we do the following:

```java
ObjectMapper mapper = new ObjectMapper();
Person person = new Person();
person.setPersonId("1");
person.getAddress().setAddressId("2");
System.out.println(mapper.writeValueAsString(person));
```

The output we get is:

`{"address":{"addressId":"2"},"personId":"1"}`

even though the `@JsonPropertyOrder` specifies that the map be serialized first. The expected output is:

`{"personId":"1","address":{"addressId":"2"}}`

Note - We do NOT have a `get()` method for the `map` object in the `Base` class. Doing so, will introduce additional nesting and repetition as shown below. 

`{"map":{"personId":"1"},"address":{"map":{"addressId":"2"},"addressId":"2"},"personId":"1"}`

And lastly, another behavior that I would like to point out - not sure if it is a bug or by design. Let's add `@JsonIgnore` to the `map`. The serialized output still contains the values from the map. In summary, it does not matter the tag that is associated with the `map` object since it appears to be disregarded.

**Comment by paninics** [comment]
After experimenting a bit, it appears that one has to specify in the `@JsonPropertyOrder` the actual keys that are present in the map i.e. as per the above example it would be:

```java
@JsonPropertyOrder({ "personId", "address"})
```

Not sure if the above is by design, or the problem stated originally is a bug. Nevertheless, it solves the problem.

**Comment by cowtowncoder** [comment]
Correct: property order affects logical properties POJO has -- and since there is no `map` property (there is a field, but unless that field is directly serialized it has no effect), that part is essentially ignored.
