### ISSUE TITLE
Register a custom EnumSerializer to overwrite the default EnumSerializer

### ISSUE THREAD

**Issue by gembin** [FasterXML/jackson-databind#227]
Create a custom CustomEnumSerializer, and add it to a SimpleModule as following:

public class CustomEnumSerializer extends StdScalarSerializer<Enum>{
    //... custom code here
}

public class MySimpleModule extends SimpleModule{
    public void setupModule(SetupContext context) {
        addSerializer(Enum.class,new CustomEnumSerializer());
    }
}
and finally objectMapper.registerModule(new MySimpleModule());

But, currently, the CustomEnumSerializer dose not overwrite the default one.

**Comment by maxkremer** [comment]
I could really use this functionality but can't seem to figure  out how. Is there any documentation or example code anywhere?

**Comment by cowtowncoder** [comment]
@maxkremer Does `SimpleModule` registration not work for you then? It works just like any other custom serializer.

**Comment by maxkremer** [comment]
@cowtowncoder yes it does. Sorry for the dumb question. Looking at the test code helped me to understand how this work. Thanks

**Comment by cowtowncoder** [comment]
@maxkremer no problem; glad you figured it out. Documentation is not as well organized as it should be, so I can understand it not being obvious.
