### ISSUE TITLE
Add basic Java 9+ module info

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2273]
As per title: use Moditect plug-in to generate, included `module-info.java`, compile in jar.

**Comment by piyshl-s** [comment]
2.10.0 is not available in maven repo. When we can expect it in meven repo?

**Comment by cowtowncoder** [comment]
@piyshl-s once it is released, I am still working on couple of last issues that need to get in, in particular #2195. I hope the first pre-release/release-candidate could go out in month (late May 2019).
