### ISSUE TITLE
InvalidDefinitionException: Cannot construct instance of enum, problem: argument type mismatch

### ISSUE THREAD

**Issue by aint** [FasterXML/jackson-databind#2277]
Hi there,

I've encountered some strange bug related to enum deserialization. It only occurs if enum has a property with the same name as a factory method's param. Just take a look at the following simplified example:

```java
@RestController
public class Controller {

    @GetMapping("/test")
    public void test(@RequestBody Request request) { }

    public static class Request {
        private Enum field;
        // getters/setters
    }

    public enum Enum {
        FIRST(1), SECOND(2);

        private final int value;
       // getter and constructor

        @JsonCreator
        public static Enum valueOf(int value) {  // param has the same name as a property
           return FIRST;
        }
    }
}

// request example 
curl -X GET http://localhost:8080/test \
     -H 'Content-Type: application/json' \
     -d '{ "field": 1 }'
```

So a property has name `value` and a factory method's parameter named `value` as well.
In this case `com.fasterxml.jackson.databind.exc.InvalidDefinitionException Cannot construct instance of 'com.example.demo.Enum', problem: argument type mismatch` will be thrown. 

If we rename either the property or the method param then all works as expected. 

I tried to debug a little and here is my finding:
`FactoryBasedEnumDeserializer` parses input value as string because its `_deser` is null that leads to invoking the creator method `valueOf(int)` with wrong arg type. 
I can't exactly figure out why `_deser` is null. Looks like because `BasicDeserializerFactory` takes a param name of annotated method and looks for its getters/fields. `paramDef.couldSerialize()` evaluates to true as we have a property with the same name. All this leads to using `SettableBeanProperty` and not initialized `_deser`.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/3179252/54381651-f884c400-4696-11e9-9a41-32540550e5b6.png">

Please find a little demo app [attached](https://github.com/FasterXML/jackson-databind/files/2967403/jackson-bug-demo.zip).

I managed to reproduce this bug on Jackson 2.9.0, 2.9.1, 2.9.7, 2.9.8 versions.

**Comment by cowtowncoder** [comment]
Ok. One thing you might want to try is to explicitly set `mode` property of `@JsonCreator` to... I think `Mode.DELEGATING` here. It sounds like auto-detection for potentially ambiguous case is reaching wrong conclusion.

**Comment by aint** [comment]
Hi @cowtowncoder,
Yeah `Mode.DELEGATING` fixes the issue. Thanks a lot.

**Comment by aint** [comment]
Also I noticed that removing `@JsonCreator` fixes the issue too.

**Comment by cowtowncoder** [comment]
@aint yes, without annotation a small group of 1-arg constructors (int, long, String, boolean, double) may be discovered (there's visibility setting to prevent that, but by default), and those are always delegating.

I will close the ticket since although handling is not ideal (it's not stable wrt whether parameter names are included in bytecode, whether java8 module registered etc etc), there is not much that can be done with Jackson 2.x to change any of this. Plan is to change logic in 3.0 to be more stable, but we are not there yet.
