### ISSUE TITLE
RFE: global or class level support for fields prefix

### ISSUE THREAD

**Issue by bringyou** [FasterXML/jackson-databind#2278]
In some code guidlines, fields are required to have some prefix(e.g.  the "m" in [AOSP](https://stackoverflow.com/questions/2092098/why-do-most-fields-class-members-in-android-tutorial-start-with-m) and the underscores in jackson souce codes and we developers are required to follow these ), 
so our data class will look like these
```java
public class User {
  private Long mId;
  public void getId() {
    return mId;
  }
  public void setId(Long id) {
    mId = id;
  }

}
```
At this case, the `mId` field must be annotated by the `JsonProperty("id")`, if not , jackson will recognize `mId` and `id` as two properties. That's ok if we have few fields or few classes. But it really pains when we have to mark all fields in all class those have the prefix. After searching documents, I found there is a workaround -- insert a `AnnotationIntrospector` by registering a custom module(some hardcode here)
```java
class PrefixIntrospector extends JacksonAnnotationIntrospector {
    private static final Pattern M = Pattern.compile("\\bm([A-Z]).*");

    private static String doTrans(Annotated a) {
        if (!(a instanceof AnnotatedField)) {
            return null;
        }
        AnnotatedField f = (AnnotatedField) a;
        String name = f.getName();
        Matcher matcher = M.matcher(name);
        if (matcher.find()) {
            String start = matcher.group(1).toLowerCase();
            if (name.length() > 2) {
                return start + name.substring(2);
            }
            return start;
        }
        return null;
    }

    @Override
    public String findImplicitPropertyName(final AnnotatedMember m) {
        String parent = super.findImplicitPropertyName(m);
        if (parent != null) {
            return parent;
        }
        return doTrans(m);
    }

    @Override
    public PropertyName findNameForDeserialization(final Annotated a) {
        PropertyName parent = super.findNameForDeserialization(a);
        if (parent != null) {
            return parent;
        }
        String newName = doTrans(a);
        return newName == null ? null : PropertyName.construct(newName);
    }

    @Override
    public PropertyName findNameForSerialization(final Annotated a) {
        PropertyName parent = super.findNameForSerialization(a);
        if (parent != null) {
            return parent;
        }
        String newName = doTrans(a);
        return newName == null ? null : PropertyName.construct(newName);
    }
}
```
That works for me, but let's go further, could there be a global config or class level annotation for this case? Maybe an annotation like these:
```java
// a global config
public ObjectMapper newMapper() {
  ObjectMapper mapper = new ObjectMapper();
  mapper.configure(FIELDS_PREFIX, "m");
  return mapper;
}

// or class level annotation
@FiledsStyle(prefix="m")
public class User {
  private Long mId;
  private String mName;
  // omits getters and setters
}
```
If there is a feature already here and I didn't find, I am sorry for wasting your time. At last, thanks for reading

**Comment by cowtowncoder** [comment]
You may want to look into Jackson naming strategy support. F.ex:

   https://www.baeldung.com/jackson-advanced-annotations

(search for `@JsonNaming`)

You can either use existing `PropertyNamingStrategy` implementations, or define custom ones, but this is mechanism designed to support something like what you are trying to achieve.

**Comment by bringyou** [comment]
@cowtowncoder thank you for replying. But the `PropertyNamingStrategy` may not work, the documents there say it is designed for

>  Class that defines how names of JSON properties ("external names") are derived from names of POJO methods and fields ("internal names"),in cases where they are not auto-detected and no explicit annotations exist for naming

IMO, it converts the "external names" to "internal names" (or opposite) but not for accessors and fields (like the field `_id` and it's setter `setId(long)`). 
Sorry if I didn't make it clearly

**Comment by bringyou** [comment]
In the `POJOPropertiesCollector`, `_renameUsing` is called after `_removeUnwantedProperties`. Maybe the order of methods calling can be changed? If then, `PropertyNamingStrategy` can work for this scene.
```java
protected void collectAll()
    {
        LinkedHashMap<String, POJOPropertyBuilder> props = new LinkedHashMap<String, POJOPropertyBuilder>();
        _addFields(props);
        _addMethods(props);
        _addCreators(props);
        _addInjectables(props);

        _removeUnwantedProperties(props);

        for (POJOPropertyBuilder property : props.values()) {
            property.mergeAnnotations(_forSerialization);
        }
        
        _removeUnwantedAccessor(props);
        _renameProperties(props);

        // And use custom naming strategy, if applicable...
        PropertyNamingStrategy naming = _findNamingStrategy();
        if (naming != null) {
            _renameUsing(props, naming);
        }

        for (POJOPropertyBuilder property : props.values()) {
            property.trimByVisibility();
        }

        if (_config.isEnabled(MapperFeature.USE_WRAPPER_NAME_AS_PROPERTY_NAME)) {
            _renameWithWrappers(props);
        }
        
        _sortProperties(props);
        _properties = props;
        _collected = true;
    }
```

**Comment by cowtowncoder** [comment]
@bringyou `PropertyNamingStrategy` does work for accessors (internal/external names stand for "names in JSON" (external) and "logical POJO property names" (internal); Latter are derived from fields, getters/setters, constructor parameters). But perhaps you mean that it only applied at logical property level, meaning that it requires matching of naming pattern for fields and accessors?
Given the example, true, names would not match.

As to changing the order of calls: no, the ordering is quite specifically crafted to support existing functionality so it can not be changed without very good reason for doing so.

So If naming strategy does not work, I think your approach by sub-classing `AnnotationIntrospector` makes sense.

I can see how some sort of "field naming strategy" could be useful for your particular case, but I am not sure how generally useful this would be. Especially as this is the first time this has been suggested.

**Comment by bringyou** [comment]
@cowtowncoder thanks. BTW, starting point is that I have some codes that will do something while deserializing -- by registering a custom module, which depends on the annotation(defined by myself) marked on the field, but I couldn't get them, then I found `mId` and `id` will be recognized as two different properties, only to add `JsonProperty` to the field or move such annotation to accessors will work. So I wonder if there is a way to consider fields and accessor as same, then I posted it.
Hope it isn't a X-Y problem.

**Comment by cowtowncoder** [comment]
No plans to tackle this, closing.

**Comment by avandermeyden** [comment]
If you want the `PROPAGETE_TRANSIENT_MARKER` to work, the workaround presented in this solution is incorrect.  You really only need to override the `findImplicitPropertyName` as if you return anything but null from the other two the code thinks you have an actual annotation, and ignores the `transient` marker.
