### ISSUE TITLE
Trailing zeros are stripped even from integer BigDecimals (600 converted to 6E+2)

### ISSUE THREAD

**Issue by kuzmiigo** [FasterXML/jackson-databind#228]
Connected to issue #80.

Using jackson-databind 2.1.4.

By default, `JsonNodeFactory` does not use exact `BigDecimal`s and strips their trailing zeros (see `numberNode(BigDecimal v)`). It's all fine for internal processing (and good for comparison), but the problem appears when serializing to JSON, as decimals like `600.00` (or just `600`) become `6E+2`. It happens because `BigDecimal.stripTrailingZeros()` stips all zeros, not from fractional part only.

For example, I need to parse JSON, add some fields and output JSON again. If the original JSON has prices like `600.00`, the resulting JSON will have `6E+2`, which is quite weird.

One solution could be to preserve `_cfgBigDecimalExact` flag from `JsonNodeFactory` in `DecimalNode`. If `_cfgBigDecimalExact` is false, then use `BigDecimal.toPlainString()` instead of `toString()` for serialization. It skips trailing zeros from decimal part only. Compare:

```
Json (string) : 600.00
BigDecimal:
    toString: 600.00, toPlainString: 600.00,
    scale: 2, unscaledValue: 60000, precision: 5
After strip:
    toString: 6E+2, toPlainString: 600,
    scale: -2, unscaledValue: 6, precision: 1

Json (string) : 600
BigDecimal:
    toString: 600, toPlainString: 600,
    scale: 0, unscaledValue: 600, precision: 3
After strip:
    toString: 6E+2, toPlainString: 600,
    scale: -2, unscaledValue: 6, precision: 1
```

For now, I just use

``` java
ObjectMapper om = new ObjectMapper();
om.setNodeFactory(JsonNodeFactory.withExactBigDecimals(true));
```

to avoid automatic stripping (it's the simplest way I've found). I guess I can apply `BigDecimal.stripTrailingZeros()` if necessary for comparison.

**Comment by vg123** [comment]
how can i remove trailing zeros from a integer in c++.
please give out any efficient method.
