### ISSUE TITLE
`JsonProperty.Access.READ_ONLY` fails with collections when a property name is specified

### ISSUE THREAD

**Issue by Yona-Appletree** [FasterXML/jackson-databind#2283]
Very similar issue to #1805, but when a property name is specified and `MapperFeature.USE_GETTERS_AS_SETTERS` is enabled:

    static class Foo {
        @JsonProperty(value = "list", access = JsonProperty.Access.READ_ONLY)
        List<Long> getList() {
            return Collections.unmodifiableList(Arrays.asList());
        }
    }

Fails with `com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.UnsupportedOperationException) (through reference chain: com.fasterxml.jackson.databind.deser.ReadOnlyDeserWithNameTest$Foo["list"]->java.util.Collections$UnmodifiableRandomAccessList[0])`

Here's the test:

    private final ObjectMapper MAPPER = jsonMapperBuilder().configure(MapperFeature.USE_GETTERS_AS_SETTERS, true).build();

    public void testReadOnly() throws Exception
    {
        String payload = "{\"list\":[1,2,3,4]}";
        Foo foo = MAPPER.readValue(payload, Foo.class);
        assertTrue("List should be empty", foo.getList().isEmpty());
    }

**Comment by cowtowncoder** [comment]
Thank you for reporting this. I hope to have a look relatively soon.

**Comment by Yona-Appletree** [comment]
I went ahead and did my best at fixing this myself and put in a new test and pull request. I'm sure it's not quite up-to-par, but hopefully it can help you get started.

**Comment by cowtowncoder** [comment]
Relatively soon was not to happen, but issue is on W-I-P/TODO list at https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress
 (fwtw)

**Comment by cowtowncoder** [comment]
Added (failing) unit test from #2284, to make it easier to solve this, whether by using (parts of) PR or not.

**Comment by cowtowncoder** [comment]
I _think_ I managed to fix this along with #2118 and #2719, for 2.12.0 (fix in `2.12` branch)
