### ISSUE TITLE
keySerializer is null inside MapSerializer

### ISSUE THREAD

**Issue by XakepSDK** [FasterXML/jackson-databind#2286]
Jackson version: 2.9.8
My code:
```java
MapType mapType = serializers.getTypeFactory()
        .constructMapType(Map.class, String.class, DownloadInfo.class);
gen.writeFieldName("classifiers");
serializers.findValueSerializer(mapType)
        .serialize(value.getClassifiers(), gen, serializers);
gen.writeEndObject();
```
when serializer reaches this code and `value.getClassifiers()` isn't empty map, it throws this exception:
```
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:781) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33) ~[jackson-databind-2.9.8.jar:2.9.8]
	at dk.xakeps.tlib.advanced.library.AdvancedLibrarySerializer.serialize(AdvancedLibrarySerializer.java:31) ~[tlib-1.1-SNAPSHOT.jar:1.1-SNAPSHOT]
```
https://github.com/FasterXML/jackson-databind/blob/2.9/src/main/java/com/fasterxml/jackson/databind/ser/std/MapSerializer.java#L780-L785

**Comment by XakepSDK** [comment]
Oh, i should use contextualized serializer, `findTypedValueSerializer` method should be used instead of `findValueSerializer`.

**Comment by XakepSDK** [comment]
I would like if someone can answer me how can i get proper `BeanProperty` for `findTypedValueSerializer` method.
I just don't have google account.

**Comment by cowtowncoder** [comment]
Yes, `null` problem is due to lack of contextualization. `BeanProperty` is available when (de)serializers are constructed by `Module`s; it is not typically available when serialization itself is called.

But what is needed here is a bit more complete example of what you are trying to achieve, and not so much specific methods you think you need to call.

**Comment by XakepSDK** [comment]
I just want to serialize non-generic POJO with some collections and regular POJOs. Nothing special like enterprise containers or DI.
Also, would be good to support jackson's serialization include system, at this moment i check manually, if collection/pojo is empty or null.
All serializers/deserializers looks like this:
https://gist.github.com/XakepSDK/0ef35c8d2e653818110a6a94abe17c0f

Some are located using `JsonSerialize` and `JsonDeserialize` annotations
Some deserializers/serializers registered using `SimpleModule`.
They need some Registry-like service to work(place where i store enum-like objects)
