### ISSUE TITLE
Custom Serializer omit null values

### ISSUE THREAD

**Issue by CEikermann** [FasterXML/jackson-databind#2288]
We are currently facing a problem when overwrite the default serializer of jackson 2.8.11 (included via play framework 2.6.13). 

**Goal**
Our goal is, we want to call the class right before the serialization in order to reset certain fields conditionally to null based the actual value of the class itself. So we can hide the values of these fields conditionally

**Idea**
Our idea is, we overwriting the default serializer and calling the class in the serialize method right before passing it back to the defaultSerializer.

**Problem**
But when we are overwrite the default serializer, all null values of that class will be omitted even if we set JsonInclude to always.

**Howto reproduce?**
ObjectMapper:
```        
SimpleModule module = new SimpleModule();
module.setSerializerModifier(new BeanSerializerModifier() {
    @Override
    public JsonSerializer<?> modifySerializer(SerializationConfig config, BeanDescription desc, JsonSerializer<?> serializer) {
        if (TestClass.class.isAssignableFrom(desc.getBeanClass())) {
            return new TestSerializer((JsonSerializer<TestClass>)serializer);
        }

        return serializer;
    }
});

final ObjectMapper mapper = Json.newDefaultMapper()
    .setSerializationInclusion(JsonInclude.Include.ALWAYS)
    .registerModule(module)
    .enable(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS)
    .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
    .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
``` 

TestSerializer:
``` 
public class TestSerializer extends JsonSerializer<TestClass> {

    private JsonSerializer<TestClass> defaultSerializer;

    public TestSerializer(JsonSerializer<TestClass> serializer) {
        defaultSerializer = serializer;
    }

    @Override
    public void serialize(TestClass value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
        defaultSerializer.serialize(value, jgen, provider);
    }

    @Override
    public JsonSerializer<TestClass> unwrappingSerializer(NameTransformer unwrapper) {
        return defaultSerializer.unwrappingSerializer(unwrapper);
    }

    @Override
    public JsonSerializer<TestClass> replaceDelegatee(JsonSerializer<?> delegatee) {
        return defaultSerializer.replaceDelegatee(delegatee);
    }

    @Override
    public JsonSerializer<?> withFilterId(Object filterId) {
        return defaultSerializer.withFilterId(filterId);
    }

    @Override
    public void serializeWithType(TestClass value, JsonGenerator gen, SerializerProvider serializers, TypeSerializer typeSer) throws IOException {
        defaultSerializer.serializeWithType(value, gen, serializers, typeSer);
    }

    @Override
    public Class<TestClass> handledType() {
        return defaultSerializer.handledType();
    }

    @Override
    public boolean isEmpty(TestClass value) {
        return defaultSerializer.isEmpty(value);
    }

    @Override
    public boolean isEmpty(SerializerProvider provider, TestClass value) {
        return defaultSerializer.isEmpty(provider, value);
    }

    @Override
    public boolean usesObjectId() {
        return defaultSerializer.usesObjectId();
    }

    @Override
    public boolean isUnwrappingSerializer() {
        return defaultSerializer.isUnwrappingSerializer();
    }

    @Override
    public JsonSerializer<?> getDelegatee() {
        return defaultSerializer.getDelegatee();
    }

    @Override
    public Iterator<PropertyWriter> properties() {
        return defaultSerializer.properties();
    }

    @Override
    public void acceptJsonFormatVisitor(JsonFormatVisitorWrapper visitor, JavaType type) throws JsonMappingException {
        defaultSerializer.acceptJsonFormatVisitor(visitor, type);
    }
}
``` 

TestClass:
``` 
public class TestClass {
    private String text;
    private Long number;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Long getNumber() {
        return number;
    }

    public void setNumber(Long number) {
        this.number = number;
    }
}
``` 

Execution:
``` 
TestClass data = new TestClass();
data.setText("test")

mapper.valueToTree(data);
``` 

**Expected Result**
``` 
{
    "text": "test",
    "number": null,
}
``` 

**Actual Result**
``` 
{
    "text": "test",
}
``` 

When we are changing the modifySerializer to not return the TestSerializer, null values are returning as expected and we get the expected result

Maybe someone already experienced similar behaviour and knows how to tackle this :)
We looking forward to any hint which could help us out here

**Comment by CEikermann** [comment]
We could solve the issue by ourself.

The root cause is, that the null serializer is empty at https://github.com/FasterXML/jackson-databind/blob/2.8/src/main/java/com/fasterxml/jackson/databind/ser/BeanPropertyWriter.java#L669

We could solve this be setting the null serializer as annotation for the fields:
@JsonSerialize(nullsUsing = NullSerializer.class)

**Comment by cowtowncoder** [comment]
@CEikermann Ok, one thing I was to suggest after seeing this is that a common problem with delegating (de)serializers is that they do not delegate 2 very important calls:

1.  `Resolvable[De]Serializer` method `resolve()` (called on instance, used for resolving cyclic dependencies) -- less common problem, relevant mostly for POJO handling
2. `Contextual[De]`Serializer` method `createContextual()` (called on instance, either returns  `this` as is OR creates a new differently constructed instances MUST NOT modify `this` as that instance is typically shared) -- this is typically what causes problems with missing initialization on (de)serializer calls are delegated to.

Note, too, that in (2) case rule that (de)serializer must create new instance if settings change also applies to custom (de)serializer if instance it delegates to changes.

It may make sense to have check out `StdDelegatingSerializer` which I think has an example.

**Comment by adrianboimvaser** [comment]
@cowtowncoder @CEikermann I'm running into the same problem.  Adding `@JsonSerialize(nullsUsing = NullSerializer.class)` to every field that could have a null value is too much. Is there any cleaner solution for this?

**Comment by cowtowncoder** [comment]
@adrianboimvaser I don't know what "same problem" here refers to.

**Comment by adrianboimvaser** [comment]
> @adrianboimvaser I don't know what "same problem" here refers to.

Here is my code:

```
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.ArrayList;
import java.util.List;

@JsonSerialize(using = MySerializer.class)
public class MyPOJO {

    @JsonIgnore // Serialized by MySerializer and deserialized by setCustomField
    private List<CustomFieldValue> customFieldValues;

    public List<CustomFieldValue> getCustomFieldValues() {
        return customFieldValues;
    }

    public void setCustomFieldValues(List<CustomFieldValue> customFieldValues) {
        this.customFieldValues = customFieldValues;
    }

    @JsonAnySetter // Only to be used by JSON deserialization
    public void setCustomField(String name, Object value) {
        if (customFieldValues == null) {
            customFieldValues = new ArrayList<>();
        }
        CustomFieldValue customFieldValue = new CustomFieldValue();
        customFieldValue.setName(name);
        customFieldValue.setValue(value);
        customFieldValues.add(customFieldValue);
    }
}
```

```
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.ser.BeanSerializerFactory;

import java.io.IOException;

public class MySerializer extends JsonSerializer<MyPOJO> {

    @Override
    public void serialize(MyPOJO value, JsonGenerator generator, SerializerProvider provider) throws IOException {

        generator.writeStartObject();

        JavaType javaType = provider.constructType(value.getClass());
        BeanDescription beanDescription = provider.getConfig().introspect(javaType);
        JsonSerializer<Object> serializer =
                BeanSerializerFactory.instance.findBeanOrAddOnSerializer(provider, javaType, beanDescription, false);
        serializer.unwrappingSerializer(null).serialize(value, generator, provider);

        if (value.getCustomFieldValues() != null) {
            for (CustomFieldValue customFieldValue : value.getCustomFieldValues()) {
                generator.writeObjectField(customFieldValue.getName(), customFieldValue.getValue());
            }
        }

        generator.writeEndObject();
    }
}
```

```
objectMapper.setSerializationInclusion(JsonInclude.Include.ALWAYS);
```

When I serialize an instance of `MyPOJO` all null values are omitted.

**Comment by cowtowncoder** [comment]
Well, this:

```java
 BeanSerializerFactory.instance
```

is something you should never use, do not use it. There should be methods in `SerializerProvider` (or possible `SerializationConfig`) that give you access to default serializers, but static factory instance should only be used Jackson internally as default setting (actually `SerializerFactory` itself should only be interacted with by Jackson core at this point)./

But other than that, please file a new issue with above example (plus definition of `CustomFieldValue`) if you have a problem reproducible with 2.11.2. It may not be related to the original problem but I do not usually reopen closed issues as that complicates release notes, gets confusing when figuring when specific issue was fixed.

**Comment by adrianboimvaser** [comment]
@cowtowncoder I'm sorry, I'm dumb, I just need `@JsonAnyGetter`, I don't need a custom serializer.

**Comment by cowtowncoder** [comment]
@adrianboimvaser Ah. Yes, that is true (or `@JsonCreator` taking `Map` could also work). Glad you figured it out!
