### ISSUE TITLE
Serialize-as-array feature enhancement request: add metadata column array

### ISSUE THREAD

**Issue by lukegh** [FasterXML/jackson-databind#229]
It would be nice if serialization via <b>@JsonFormat(shape = JsonFormat.Shape.ARRAY)</b> would support optional generation of a metadata columns array, along with the actual data array. More exactly, the serialization process would be able to produce an additional array listing the names of the columns, in the same order as they appear in the data array.

For example, given the following classes:
```java
	public class Report {

	    @JsonFormat(shape = JsonFormat.Shape.ARRAY)
	    public ArrayList<Book> report;

	    public Report() {
	    	this.report = new ArrayList<Book>();
	    	this.report.add(new Book("Jonathan Swift", "Travels into Several Remote Nations of the World, in Four Parts. By Lemuel Gulliver, First a Surgeon, and then a Captain of several Ships", "Benjamin Motte", null, 1726, 256));
	    	this.report.add(new Book("Lewis Carroll", "Alice's Adventures in Wonderland", "Macmillan", null, 1865, 88));
	    	this.report.add(new Book("George Orwell", "Animal Farm: A Fairy Story", "Secker and Warburg", "978-0-452-28424-1", 1945, 112));
	    }

	    private class Book {
			public String author;
			public String title;
			public String publisher;
			public String isbn;
			public int year;
			public int pages;
	        
	        public Book(String author, String title, String publisher, String isbn, int year, int pages) {
	            this.author = author;
	            this.title = title;
	            this.publisher = publisher;
	            this.isbn = isbn;
	            this.year = year;
	            this.pages = pages;
	        }
	    }
	}
```

Currently (as of Jackson 2.2), serializing an instance of Report will produce:
```json
"report": [[
    "Jonathan Swift", "Travels into Several Remote Nations of the World, in Four Parts. By Lemuel Gulliver, First a Surgeon, and then a Captain of several Ships", "Benjamin Motte", null, 1726, 256
], [
    "Lewis Carroll", "Alice's Adventures in Wonderland", "Macmillan", null, 1865, 88
], [
    "George Orwell", "Animal Farm: A Fairy Story", "Secker and Warburg", "978-0-452-28424-1", 1945, 112
]]
```

This proposed enhancement would allow one to produce something like:
```json
"report": {
    "columns": ["author", "title", "publisher", "isbn", "year", "pages"],
    "data": [[
        "Jonathan Swift", "Travels into Several Remote Nations of the World, in Four Parts. By Lemuel Gulliver, First a Surgeon, and then a Captain of several Ships", "Benjamin Motte", null, 1726, 256
    ], [
        "Lewis Carroll", "Alice's Adventures in Wonderland", "Macmillan", null, 1865, 88
    ], [
        "George Orwell", "Animal Farm: A Fairy Story", "Secker and Warburg", "978-0-452-28424-1", 1945, 112
    ]]
}
```

Ideally, specifying the extended serialization format (i.e. that includes a metadata array) would be supported via the same @JsonFormat annotation, perhaps via two new optional properties (e.g. "metaDataArray" and "dataArray"), that would become available for the <b>@JsonFormat(shape = JsonFormat.Shape.ARRAY)</b> annotation.

To generate the JSON example above (with the "columns" metadata array and the "data" data array), one would then specify:
```java
@JsonFormat(shape = JsonFormat.Shape.ARRAY, metaDataArray = "columns", dataArray = "data")
public ArrayList<Book> report;
```

Of course this can be obtained currently with existing functionality, but would be nice to have integrated into the serialize-as-array feature at some point.
Thanks!

**Comment by cowtowncoder** [comment]
I don't think this feature will be implemented; on one hand, `@JsonFormat` is meant to be general-purpose, so adding array-specific properties is unlikely, and second, I am not quite sure it would be possible to modify existing functionality to work as suggested.
Custom (de)serializer is more likely way to achieve this.
