### ISSUE TITLE
Create tutorial on how to use Builders and Jackson

### ISSUE THREAD

**Issue by feinstein** [FasterXML/jackson-databind#2291]
I can't find an official documentation on how to use the Builder pattern and Jackson, just some tutorials on the web.

**Comment by cowtowncoder** [comment]
@feinstein Now added by @Hassan-Elseoudy -- very useful addition, thank you for suggesting it.

**Comment by feinstein** [comment]
My pleasure.

**Comment by feinstein** [comment]
The tutorial seems very simple.... Is it all there's to it, or are there more specific cases missing that would be nice to be included?

**Comment by Hassan-Elseoudy** [comment]
@feinstein It's that simple as it looks, but also it depends on your implementation for Builder design pattern, I used the standard way of Implementing the Builder pattern.
I'm also interested to know If there are specific cases there you want to be included.

**Comment by feinstein** [comment]
There has been some time since I don't use Jackson, but I remember having issues with some corner cases, let me check on some old code and get back to you.

**Comment by cowtowncoder** [comment]
One thing to note: since this is on README, I think concise overview makes sense. More advanced cases should probably go on separate Wiki page -- but whether that should on `jackson-databind` or under `jackson-docs` I am not sure. If @Hassan-Elseoudy (or anyone else) could provide longer version, I can help getting access rights -- but I don't think wiki changes can be made as a PR?

**Comment by Hassan-Elseoudy** [comment]
@cowtowncoder I agree with you, I think this issue is done for now, For advanced examples we can discuss in Wikis or somewhere else.

**Comment by feinstein** [comment]
Agreed.

**Comment by Hassan-Elseoudy** [comment]
@feinstein @cowtowncoder I guess you need to close the issue :))

**Comment by feinstein** [comment]
@Hassan-Elseoudy as far as I understand we agreed that the quick start is good but more elaborate examples are needed, probably on a wiki format.

**Comment by Hassan-Elseoudy** [comment]
Ah, okay I thought you’ll close this and open a new specific issues with specific needs rather this general one.

No worries.

**Comment by cowtowncoder** [comment]
I am fine either way; will actually go ahead and create new one, close this.

**Comment by cowtowncoder** [comment]
Created #2898 for follow-up.
