### ISSUE TITLE
Jackson compatibility between 2.3.3 and any version 2.5.4+

### ISSUE THREAD

**Issue by brentryan** [FasterXML/jackson-databind#2294]
We've noticed that some applications that are using older versions of jackson serialize/deserialize data differently and are not compatible with other applications who do the same thing but are on newer versions of jackson 2.5.4+.

It seems as though the behavior changed and is a breaking change from possibly this commit:
https://github.com/FasterXML/jackson-databind/commit/44067903e49d78027438db90f08ec35dabac838c#diff-642048ef65486f82fe209d804dd937ff

The Implementation of `EnumDeserializer.FactoryBasedDeserializer.deserialize` for 2.5.4 doesn’t check if it is integer type and always use string as constructor parameter (edited) 
```public Object deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
            Object value;
            if(this._deser != null) {
                value = this._deser.deserialize(jp, ctxt);
            } else {
                JsonToken curr = jp.getCurrentToken();
                if(curr != JsonToken.VALUE_STRING && curr != JsonToken.FIELD_NAME) {
                    value = jp.getValueAsString();
                } else {
                    value = jp.getText();
                }
            }

            try {
                return this._factory.invoke(this._valueClass, new Object[]{value});
            } catch (Exception var6) {
                Throwable t = ClassUtil.getRootCause(var6);
                if(t instanceof IOException) {
                    throw (IOException)t;
                } else {
                    throw ctxt.instantiationException(this._valueClass, t);
                }
            }
        }```
While in 2.3.3 the same method looks like this, note if _inputType is Integer, an integer will be passed as constructor parameter
        ```public Object deserialize(JsonParser jp, DeserializationContext ctxt)
            throws IOException, JsonProcessingException
        {
            // couple of accepted types...
            Object value;
            if (_inputType == null) {
                value = jp.getText();
            } else  if (_inputType == Integer.class) {
                value = Integer.valueOf(jp.getValueAsInt());
            } else  if (_inputType == Long.class) {
                value = Long.valueOf(jp.getValueAsLong());
            } else {
                throw ctxt.mappingException(_enumClass);
            }
            try {
                return _factory.invoke(_enumClass, value);
            } catch (Exception e) {
                Throwable t = ClassUtil.getRootCause(e);
                if (t instanceof IOException) {
                    throw (IOException) t;
                }
                throw ctxt.instantiationException(_enumClass, t);
            }
        }
```

If this is indeed an expected breaking change, then shouldn't jackson versioning have been changed to 3.x at this point instead of 2.5.4? Please clarify what the expectations were around this change with regards to backwards compatibility of this library?

**Comment by cowtowncoder** [comment]
Both 2.3 and 2.5 are very old versions by now, so I don't know what may have happened there.
And in general reproduction of the problem is more useful than pointing specific code changes; changes are usually for fixing some other problem or adding a new feature.
It is likely change was unintentional

But if there is specific behavioral problem with the new(er) version, you can change the description here, add a unit test showing the actual problem you are facing, instead of trying to explain it. Or create a new one. I can then explain what I think is the expected behavior, and whether is to be considered a fix to formerly broken behavior, or breakage.

**Comment by brentryan** [comment]
Here's a sample project that demonstrates the issue with a workaround/fix we're looking to add until all our applications can be updated together.

https://github.com/cvent/jackson-compatibility-test

If you run "mvn test" it will fail.

If you uncomment this mixin then re-run the test it will work again:
https://github.com/cvent/jackson-compatibility-test/blob/master/enum-deserializer-test-databind-296/src/test/java/TestTimeZone296.java#L19

The json being deserialized is example json that was serialized and handled properly by jackson 2.3.3 but broke in later versions like 2.5.4.

There might not be much you can do about this other then make sure that 2.9.9+ future versions know how to work with JSON that was serialized out by older versions. Let me know what you think.

**Comment by brentryan** [comment]
This seems to be a bug with an older version of dropwizard FuzzyEnumModule and not something specific to jackson.

**Comment by cowtowncoder** [comment]
@brentryan ah. That sort of makes sense, as that had fairly elaborate handling I think. But odd, also, as I thought DW had quite extensive test suite.

But good that you figured out and shared in case others bump into it.
