### ISSUE TITLE
security risk in 2.9.8

### ISSUE THREAD

**Issue by doublefishlily** [FasterXML/jackson-databind#2300]
enableDefaultTypingAsProperty may expose a security hole.  Jackson contains a pre-defined black list for blocking known cases, new ones are found over time so that at any given time there may be unblocked attack vectors. Is there a better way to fix it completely?

**Comment by cowtowncoder** [comment]
@doublefishlily Please do not use issue tracker for asking questions: that is what discussion groups are for:

https://groups.google.com/forum/#!forum/jackson-user

as to the question: yes, do not enable default typing if this is problematic.
