### ISSUE TITLE
READ_ENUMS_USING_TO_STRING doesn't support null values

### ISSUE THREAD

**Issue by andersonbd1** [FasterXML/jackson-databind#2309]
The test added in EnumDeserializationTest.java fails w/out the fix in EnumResolver.java.

https://github.com/FasterXML/jackson-databind/pull/2307/files

**Comment by andersonbd1** [comment]
pull request for the fix is here:
https://github.com/FasterXML/jackson-databind/pull/2307

**Comment by andersonbd1** [comment]
issue posted to facebook-java-business-sdk as well:
https://github.com/facebook/facebook-java-business-sdk/issues/235

**Comment by cowtowncoder** [comment]
But is it even legal to return `null` from `toString()`?

I guess I could instead throw an exception to indicate bad return value. I am not sure I'm comfortable coercing `null` into "", although that is a reasonable suggestion in general.

**Comment by andersonbd1** [comment]
@cowtowncoder - any word on this?  I'm not saying my solution is the best/most correct, but can you introduce a way to make the failing test (that I demonstrate) work?

**Comment by cowtowncoder** [comment]
@andersonbd1 I haven't had time to look but I'll add this to my todo list for another glance. Thank you for reminder.

**Comment by andersonbd1** [comment]
Thanks @cowtowncoder .  I just got a reply from facebook here - https://github.com/facebook/facebook-java-business-sdk/issues/235#issuecomment-528703172

Sounds like they're more concerned about supporting gson.

**Comment by cowtowncoder** [comment]
@andersonbd1 that makes sense wrt Facebook, they don't really need to worry about json handling performance. :)

But regardless I am interested in Jackson side of things.
