### ISSUE TITLE
Unnecessary MultiView creation for property writers

### ISSUE THREAD

**Issue by manuel-hegner** [FasterXML/jackson-databind#2311]
https://github.com/FasterXML/jackson-databind/blob/1ff8ea3487b523ea04edd9caf1db70c93ff1ec99/src/main/java/com/fasterxml/jackson/databind/ser/BeanSerializerFactory.java#L567

I think getViews can also return an empty array (at least it does in my afterburner usecase) which should be handled the same as null, and not create a MultiView wrapper.

**Comment by cowtowncoder** [comment]
Ok this may have been changed at some point, will check it out when I have time.

**Comment by cowtowncoder** [comment]
Thank you again for pointing this out -- added in 2.10.0 (not backporting only to minimize any risk of possible breakage, as this is more an optimization).
