### ISSUE TITLE
New constant READ_ENUMS_USING_VALUE_OF is needed

### ISSUE THREAD

**Issue by rossbu** [FasterXML/jackson-databind#2313]
Issue demo Gist:  [EnumValueDemo](https://gist.github.com/rossbu/e58f5b2689cfcadeea7500d091c5d719)

ISSUE DESCRIPTION: 
firstly, Given below xsd schema :
```
  <xs:simpleType name="localetype">
     <xs:restriction base="xs:string">
         <xs:enumeration value="en_US" />
         <xs:enumeration value="de_DE" />
     </xs:restriction>
 </xs:simpleType>
```

 The 1st convention/standard to define locale Names are based off ISO 639 standard. which is Language Name ( lower cases) and Region Name ( Upper cases)
[language-identifiers](http://www.i18nguy.com/unicode/language-identifiers.html)
 
Next When Generating java object by tools like xjc or maven plugins like jvnet jaxb2, which follows the 2nd convention as below, which is to UPPERCASE all vars in enum class.
```
enum Localetype {
    EN_US("en_US"),
    DE_DE("de_DE");
    ....
 }
```
then after initialization of enum class. it is (approximately) like saying below in jvm.
```
 class extends ENUM {
    public static final Localtype EN_US= new Localtype("en_US");
    public static final Localtype DE_DE = new Localtype("de_DE");
    ...
 }
```
The schema is used by all customers/developers for ERP integration ( from different orgs). using xsd schema for both JSON and XML data communication. 

Now Json comes like this {"languagelocale" : "en_US"}  and fails the deserialization no matter READ_ENUMS_USING_TO_STRING true or false. 
The workaround is to define code injection to 'ugly' inject the code to overwrite toString in enum class as below and enable READ_ENUMS_USING_TO_STRING as true.
```
 enum Localetype {}
    EN_US("en_US"),
    DE_DE("de_DE");
    ...
     // code injection as below
     @Override
     public String toString() {
        return this.value();
     }
 }
```
This approach is discussed on stackoverflow: [JAXB Code Inject into Enum Class
](https://stackoverflow.com/questions/24276404/jaxb-code-inject-into-enum-class/55857970#55857970)

So if it can introduce a new tag **READ_ENUMS_USING_FROM_VALUE** or **READ_ENUMS_USING_VALUE_OF**(prefered, and false by default) that can directly return the value() of each Enum 'instance', that would fix this issue. 
Side notes: There are many other USECASES that define enum with different value than names such as 
` ALT("alt"), COORDS("coords"), SHAPE("shape"), TARGET_IMAGE("targetImage");`

**Comment by rossbu** [comment]
the program might have to reflectively check the params in the constructor for valueof to return. such as enumclass (string name, int age, ...). which means this valueof() should return either 1 value or N values based on number of params in the constructor.  also suggest supporting lambda expression in the api, so that we can specify the 'valueof()' functions in various circumstances.

**Comment by cowtowncoder** [comment]
@rossbu First things first: have you tried using `@JsonValue` annotation on method that produces string you want to use? That is not only used as serialization but is also deserialized from correctly.
In your case it might be as simple as

```java
 @Override
 @JsonValue
 public String toString() {
    return this.value();
 }
```

**Comment by rossbu** [comment]
@cowtowncoder as I have mentioned above, we did figure out to override toString method to return the expected value ( with or without the @jsonvalue, but it's a side story) , the main issue here is When you  got into the software integrations with other 'xml-backed's system, like using jvnet jaxb2 ( or other maven xsd/xml plugins ) by other teams/orgs for xml serialization/deserilization, it does not add  @jsonvalue or overrides toString() or any json related attributes, because those are not XML/XSD developers concern, they only focus on the objects itself. ( pure pojo or xml-annotated pojo).   so adding/overriding toString() method becomes a 'hack' injection to the pojo, that's why I draw the team attention that as data binding, it should control the value or name String by introducing a new flag READ_ENUMS_USING_VALUE_OF . so the enum can return the real value instead of names of the variables in this case: en_US.

**Comment by cowtowncoder** [comment]
Ok. Even after re-reading, I am not sure exactly what was being asked. While background information is useful, it would be most useful so show example of how code should work wrt simple declaration (emulating what JAXB generates etc).

What exists without annotations is to use either:

* `Enum.name()` (default)
* `Enum.toString()`

as the id to map to/from.

Since `Enum.valueOf(...)` uses `name()` for lookup, I am not sure what exactly is missing.
