### ISSUE TITLE
Option to de-serialize map key into map value objects 

### ISSUE THREAD

**Issue by oberlies** [FasterXML/jackson-databind#2321]
With the `@JsonManagedReference` & `@JsonBackReference` annotation, there is the possibility to deserialize context into objects. The same should be possible for map keys, e.g. with a new annotation `@JsonMapKey`.

Example JSON:
```
{
    "domains": {
        "ldap": {
            "users": {
                "fwalther": {
                    "firstName": "Fritz",
                    "lastName": "Walther"
                },
                // ...
            }
        }
    },
    // ...
}
```
Model classes:
```
public class Domain {
    @JsonManagedReference
    private Map<String, User> users;

    public Map<String, User> getUsers() {
        return users;
    }
}

public class User {
    @JsonBackReference
    private Domain domain;

    @JsonMapKey // new annotation to get the key from the enclosing map
    String userId;

    private String firstName;
    private String lastName;

    // ... getters
}
```
When deserializing the JSON above into this model, `userId` shall have the value "fwalther".

Currently, the `@JsonMapKey` annotation can be implemented via a custom deserializer modifier – see https://stackoverflow.com/a/55953495/1523648 – but it would be good if the functionality could be available by default in the Jackson library.

**Comment by cowtowncoder** [comment]
Thank you for s and including link so anyone who wants such functionality can use custom deserializer as suggested.

I don't think I will want to pursue adding such a feature, but I will leave this open in case someone else has time and interest.

**Comment by oberlies** [comment]
Yes, this was the idea :-)  I suppose that this would in fact only be a minor improvement, given the low number of votes here and on the [corresponding stackoverflow question](https://stackoverflow.com/questions/42763298/jackson-keep-references-to-keys-in-map-values-when-deserializing).

Thanks for keeping the feature request open though - because I think that a built-in solution could still be better than my [custom solution](https://stackoverflow.com/a/55953495/1523648). For example, `@JsonMapKey` could also be automatically excluded from serialization to JSON, like `@JsonBackReference` is.

**Comment by cowtowncoder** [comment]
No plans to implement this. If someone wants to do a PR that is fine, may reopen the issue, but closing since there are hundreds of other issues to tackle.

**Comment by heruan** [comment]
@oberlies any chance to get a PR for this?
