### ISSUE TITLE
JSON Deserialization fails if a required module is registered after first usage of ObjectMapper

### ISSUE THREAD

**Issue by santam85** [FasterXML/jackson-databind#2328]
Since the ObjectMapper uses a cache for (de)serializers, during normal use an ObjectMapper can potentially reach a state where even if all the required (de)serializers have been registered, the (de)serialization fails because the previously resolved and cached (de)serializers are being used.

This can become an issue when the mapper is configured by a 3rd party library that doesn't allow to configure a list of modules during the initialization phase. I believe it can be resolved in this specific case by clearing the (de)serializers cache upon registration of a new module.

Jackson version: 2.9.8

Attached a little Maven project with a simple reproduction scenario, check the comments in the 
code for details: [jacksonmoduletest.zip](https://github.com/FasterXML/jackson-databind/files/3183663/jacksonmoduletest.zip)

This works:
```
[...]
mapper.registerModule(...);
mapper.readValue("{pojoWithOnlyDefaultTypes}", Pojo.class);
mapper.readValue("{pojoWithAlsoCustomTypes}", Pojo.class);
[...]
```

This doesn't:

```
[...]
mapper.readValue("{pojoWithOnlyDefaultTypes}", Pojo.class);
mapper.registerModule(...);
mapper.readValue("{pojoWithAlsoCustomTypes}", Pojo.class); // Throws exception
[...]
```

**Comment by cowtowncoder** [comment]
This works as designed: all configuration must be completed before any use. This includes registration of any and all modules -- they MUST occur before any and all use (readValue(), writeValue()).

Simple clearing of caches might or might not work, keeping in mind that concurrent use is already possible (so synchronization would be needed).

Jackson 3.0 does change behavior in such a way that this problem does not exist: all configuration happens during building stage, but Jackson 2.x unfortunately can not address.
(2.10 does add builder() approach to help make this easier to see, but it won't prevent existing usage for compatibility reasons).

I am open to documentation improvements.

**Comment by santam85** [comment]
> 
This works as designed: all configuration must be completed before any use. This includes registration of any and all modules -- they MUST occur before any and all use (readValue(), writeValue()).
--
I suspected that was the case; if there's no clear disclaimer about this in the documentation, I would suggest adding it!

**Comment by cowtowncoder** [comment]
I think the general idea is mentioned, but I am sure documentation can be improved to make this clearer. I hope to find places to improve, but if you or anyone else has good ideas for specific places to add I am open always to improvements.

**Comment by santam85** [comment]
It's indeed well explained here: https://github.com/FasterXML/jackson-databind/wiki/Mapper-Features
