### ISSUE TITLE
After using lombook, json is converted into an object, and some fields cannot be converted.

### ISSUE THREAD

**Issue by hj819748949** [FasterXML/jackson-databind#2330]
Is a getter, setter method generated by lombook, because the getter generated by lombook, setter method and eclipse generated getter, setter method name is a little different, but I look at the source code of jackson found that jackson in the generation of json entity attribute name is through setter The method name interception operation obtained, there is a case difference in the generated json attribute name. I tested alibaba fastjson, google gson, generated json, whether it is gelipse generated getter, setter, or lombook generated getter , setter , generated json is the same, but jackson is different in the case of two kinds of getter, setter

Since fastjson is the default json parsing framework for spring, if the following example appears, the backend will receive less data.

for example :

```java
import java.io.Serializable;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class LUser implements Serializable
{
	private static final long serialVersionUID = 2524357019179494943L;

	private String tEst;
	
	private String tDate;
	
	private String ttttttDate;
	
}
```

```java
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/json")
public class JsonController
{
	/**
	 * test
	 * @param user
	 * @return
	 */
	@PostMapping("/test")
	public LUser test(@RequestBody LUser user)
	{
		// user Some fields have not been passed over
		return user;
	}
}
```

If I send a post request to the test method, the requested data json is

```
{
      "tEst": "aa",
      "tDate": "bbbb",
      "ttttttDate": "cccc"
}
```

If I send a post request to the test method, the requested data json is

```
{
      "tEst": "aa",
      "tDate": "bbbb",
      "ttttttDate": "cccc"
}
```

The background did not receive tEst, tDate data, ttttttDate data received normally, I also tried to set the parameter MapperFeature.USE_STD_BEAN_NAMING, but it is not useful, if I set the spring json converter to alibaba fastjson, google gson, all data can be Normal reception

_Originally posted by @hj819748949 in https://github.com/FasterXML/jackson-databind/issues/2327#issuecomment-492514584_

**Comment by cowtowncoder** [comment]
What I need to help is a test case that does not use either Lombok or Spring framework.
This because I do not want to end up debugging integration aspects from these libraries/frameworks; and extracting Jackson-specific part helps find out where the issue is.
It also helps adding regression tests in case where problem is found: Jackson test suite tries to avoid adding external dependencies as well.

That usually means figuring out exactly what Lombok generates, using that, and then extracting similar logic from Spring end points.
Sometimes this is non-trivial amount of work but in this case would probably not be too complex.

**Comment by mxmlnglt** [comment]
@hj819748949 no need to open a new issue here; all you had to to was to explain a bit further your previous case #2327.

@cowtowncoder I put a detailed comment there: https://github.com/FasterXML/jackson-databind/issues/2327#issuecomment-496541516
