### ISSUE TITLE
about jackson Serialization

### ISSUE THREAD

**Issue by 1397649957** [FasterXML/jackson-databind#2356]
hello in jackson 2.8.11.2 i get this 
![image](https://user-images.githubusercontent.com/35563513/59667361-32f78300-91e9-11e9-8265-d0967e74a32a.png)
why not json string

**Comment by cowtowncoder** [comment]
Please use mailing list (https://groups.google.com/forum/#!forum/jackson-user) or Gitter group (https://gitter.im/FasterXML/jackson-databind) for usage questions. Also include some details, screen shot is not of much use without knowing what code is invoked and how.
