### ISSUE TITLE
Enum EnumDeserializer not work for deserialize from enum name

### ISSUE THREAD

**Issue by GitHanter** [FasterXML/jackson-databind#2359]
I have two services, and one service serialize enum by name, and another service consume the json, and deseirilize from it. But I get a error "value not one of declared Enum instance names: [1, 2, 3, 4]".

 I tried on version 2.9.8 and 2.9.9, both are not work. But version 2.5.4 is work.

The features I turn on 
ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.findAndRegisterModules();
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        objectMapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
        objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        objectMapper.configure(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS, false);
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        objectMapper.registerModule(new JavaTimeModule());

**Comment by cowtowncoder** [comment]
I would need a full reproduction of the issue: description is not enough to see what exactly is happening.
