### ISSUE TITLE
HttpMessageNotWritableException: Could not write JSON: Infinite recursion (StackOverflowError); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Infinite

### ISSUE THREAD

**Issue by jpfss** [FasterXML/jackson-databind#2363]
The version infomation as fowllows :
One, the "spring-boot-starter-data-jpa"' with version as follows:
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
    <version>2.1.5.RELEASE</version>
</dependency>
```
Two,the springBoot contains the jackson-databind‘s version is jackson-databind-2.9.8.

It hanppens  in my program.  I have a lot of information for this case。I use the "spring-boot-starter-data-jpa" with the version "2.1.5.RELEASE" .In SrpingMVC ,the annotions names "@RestController" and "@ResponseBody" uses this json-lib .I have tried to use the annation named "@JsonIgnore" and It works well.
But In my Business ,the relationship In one Object contains many “OneToOne” and “ManyToMany” wih Double-side.I can't ignore the single side in Double side 。How do I  to deal with it?

I have seen many people hanpens this problem  in Google  and I fonund that many solution order to avoid this problem。I think about that can we resolve this problem？

**Comment by cowtowncoder** [comment]
Please send usage questions to discussion group at:

    https://groups.google.com/forum/#!forum/jackson-user

with enough information to show the actual problem (description above won't be enough to help).
Issue tracker is for reporting bugs, requesting features.
