### ISSUE TITLE
`@JsonAlias` doesn't work with AutoValue

### ISSUE THREAD

**Issue by toadzky** [FasterXML/jackson-databind#2378]
I am using Google AutoValue library to define some polymorphic json data type. We are renaming one of the getters for the class and we want to have the old name work so it's easier to migrate. The class looks like this:

```java
@AutoValue
@JsonTypeName("user")
public abstract class UserEventContext implements EventContext {

     public abstract String getId();

    public abstract String getPartitionId();

    public abstract String getAccountId();

    public abstract Optional<String> getDeviceId();

    @JsonCreator
    public static UserEventContext create(@JsonProperty("partitionId") String partitionId,
            @JsonProperty("accountId") String accountId,
            @JsonProperty("id") @JsonAlias("userId") String userId,
            @Nullable @JsonProperty("deviceId") String deviceId) {
        return new AutoValue_UserEventContext(userId, partitionId, accountId, Optional.ofNullable(deviceId));
    }
}
```

The `@JsonAlias` on the 3rd parameter is ignored and the AutoValue constructor throws an error because the argument is null. 

I dug through the bean deserializer code and it looks like the problem is that the aliases never get registered because it's an abstract class.

**Comment by cowtowncoder** [comment]
First things first: have you verified that this would work if alias was not used? Mostly asking to rule out possibility that usage does not work at all (since factory methods are bound only to specific type and not used by sub-classes).

**Comment by toadzky** [comment]
Yes, it works correctly if the json string has the key from the `@JsonProperty` annotation instead. I have a whole bunch of classes doing this same thing, this is the first one where we are trying to evolve the API in a  backwards compatible way instead of just breaking things.

**Comment by cowtowncoder** [comment]
Ok, finally have time to look into this again.

One more suggestion: moving `@JsonAlias` to matching getter might work better.

I will try to come up with a test case, without using auto-values.

**Comment by cowtowncoder** [comment]
Unfortunately unable to reproduce with simple factory-method-as-creator, so will a reproduction (without additional libraries or generation -- I think auto-values has a way to show sources so that should work).

**Comment by toadzky** [comment]
I tried with the alias annotation on the getter, still fails with the same error. Here's the generated class from AutoValue, minus equals/hashcode/toString:

```java
final class AutoValue_UserEventContext extends UserEventContext {

  private final String id;

  private final String partitionId;

  private final String accountId;

  private final Optional<String> deviceId;

  AutoValue_UserEventContext(
      String id,
      String partitionId,
      String accountId,
      Optional<String> deviceId) {
    if (id == null) {
      throw new NullPointerException("Null id");
    }
    this.id = id;
    if (partitionId == null) {
      throw new NullPointerException("Null partitionId");
    }
    this.partitionId = partitionId;
    if (accountId == null) {
      throw new NullPointerException("Null accountId");
    }
    this.accountId = accountId;
    if (deviceId == null) {
      throw new NullPointerException("Null deviceId");
    }
    this.deviceId = deviceId;
  }

  @Override
  public String getId() {
    return id;
  }

  @Override
  public String getPartitionId() {
    return partitionId;
  }

  @Override
  public String getAccountId() {
    return accountId;
  }

  @Override
  public Optional<String> getDeviceId() {
    return deviceId;
  }
}
```

**Comment by cowtowncoder** [comment]
Ok thank you. I am surprised creator method actually gets used, due to being in super class.
But I hope to have a look at this soon-ish, now that this should reproduce the problem.

**Comment by toadzky** [comment]
the `@JsonTypeName` is on the parent class, so that's the type it tries to deserialize it as. the `@JsonCreator` is on the same class as teh `@JsonTypeAlias` so it makes sense why it would find it. jackson isn't trying to create an instance of the autovalue generated class, it's just invoking the `@JsonCreator` factory method with `null`. based on my debug stepping through, it's not even looking at the generated class.

**Comment by cowtowncoder** [comment]
Whether `@JsonTypeName` is used or not depends on whether polymorphic handling is enabled, and if it is, how are types found; but for polymorphic deserialization things happen in 2 steps: first, information for relevant base type is processed (to know info for subtypes etc), and then when type id is resolved, deserializer for actual implementation is located. But even in latter case, annotations are "flattened" from full type hierarchy. Not sure if that is relevant but thought I'll write it down to help me think this through :)

Now, one known issue with Jackson 2.x is that handling of "regular" properties, and those from Creator, is somewhat split, and there are certain cases where information is not available in fully resolved form. This is due to auto-detection of Creator methods having bit of chicken-and-egg problem (some auto-discovery relies on correlation between Creator parameter name annotations, annotations on field/getter/setter).

So there are some possible gotchas. But I'll need to go through the process to see what is going on.

But back to my earlier question:

    One more suggestion: moving @JsonAlias to matching getter might work better.

Does that make any difference?

**Comment by cowtowncoder** [comment]
Ok, I can reproduce the problem locally.

**Comment by cowtowncoder** [comment]
Also: no, moving `@JsonAlias` to getter does NOT resolve the issue.

**Comment by cowtowncoder** [comment]
Hmmh. Ok, so I see where this happens, and I can make the test pass. What concerns me slightly is that I do not know why alias information from Creator (or, if added, from getters) does not end up in `BeanPropertyMap`, but forcing one check to pass aliases can get introspected to make things work.

So I will do that and worry about the (possibly) bigger issue later on; perhaps with 3.0 rewrite of property introspection logic.

**Comment by toadzky** [comment]
Awesome, thanks for digging into it. When I dug it, it looked like the
reason it wasn't trying to introspect it was that the type of the result is
an abstract class.
