### ISSUE TITLE
JsonSubTypes doesn't work with mixin

### ISSUE THREAD

**Issue by Omicronius** [FasterXML/jackson-databind#2379]
Dear jackson community,

I faced the issue/feature request that was described in https://github.com/FasterXML/jackson-core/issues/465 and closed after a while. The goal is to have the ability to add/override JsonSubTypes mapping in mixin.

Version 2.9.9

```
class Animal {
  private String type;
}
```
`class Cat extends Animal { }`
```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({@JsonSubTypes.Type(value = Cat.class, name = "cat")})
abstract class SubTypesMixin { }
```
```
  @Test
  public void mixinsShouldWorkWithSubtypesAnnotations() throws IOException {
    // given
    String json = "{\"type\":\"cat\"}";
    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.addMixIn(Animal.class, SubTypesMixin.class);

    // when
    Animal animal = new ObjectMapper()
        .readerFor(Animal.class)
        .readValue(json);

    // then
    assertEquals(animal.getClass(), Cat.class);
  }
```

If I was not very opinionated in finding the answer, could you please give an advice or workaround for the issue. Thank you in advance.

Regards.

**Comment by cowtowncoder** [comment]
(note: moved under `jackson-databind` as this is not related to streaming api, `jackson-core`)

@Omicronius I think test is broken: it is configuring an `ObjectMapper` properly, but then not using that mapper but a newly created `ObjectMapper` with no configuration? If it did use first mapper I think things should work as expected.

**Comment by cowtowncoder** [comment]
Will need a working test case, may be reopened if reproducible.
