### ISSUE TITLE
MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token

### ISSUE THREAD

**Issue by gMan1990** [FasterXML/jackson-databind#2381]
### Question: how to ignore this error like
`DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES`

### Demo:
```JAVA
@Getter
public class Demo {
  private ArrayList<Data> data;
}

// read success
new ObjectMapper().readValue("{\"data\":[]}", Demo.class);

// read error: MismatchedInputException
new ObjectMapper().readValue("{\"data\":{}}", Demo.class);
// how to ignore error, just set the data to null
```

**Comment by cowtowncoder** [comment]
Please send usage questions to mailing list (https://groups.google.com/forum/#!forum/jackson-user) or Gitter (https://gitter.im/FasterXML/jackson-databind). Issue tracker is for reporting problems, bugs, contributing improvements.
