### ISSUE TITLE
Serialize to multiple aliases

### ISSUE THREAD

**Issue by mjustin** [FasterXML/jackson-databind#2383]
I have an API that is read by an existing client, and I would like to rename a field on the API.  I want to serialize the value under both the new name and the previous name so that existing clients will continue to work while they are migrated to use the new field name.  This is simple enough to do by adding an additional getter with the new name; however, I wonder if a `@JsonAlias`-style approach would be worth adding to Jackson to do this automagically (`@JsonAlias` only works for deserialization).

Related issue: #1029 (aliases for deserialization)

**Comment by cowtowncoder** [comment]
At interface level, this could be indicated by a new property of `@JsonAlias` I suppose (either general `mode` (read/write, read, write)), or `OptBoolean` flag to enable writing out.

**Comment by mjustin** [comment]
@cowtowncoder Not sure how far you want to generalize this, but would you want to support a single property having different read-only and write-only aliases?

If so and this were implemented by adding an annotation-level flag, would that mean we'd also need to mark `@JsonAlias` as `@Repeatable`?  I suppose alternatively there could be different arrays of properties within `@JsonAlias` for the read aliases & write aliases.

**Comment by cowtowncoder** [comment]
Hmmh. Good question. I don't remember details of how much difference internal API allows wrt alias definitions (that is, how much rework needed to decouple).
One possibility actually would be to instead of boolean/enum flag to simply allow addition of something like

```java
@JsonAlias(value = { ... for deser }, writeAlso = { ... for ser ... } )
```

(or whatever better property name we could come up with)

which would then allow separate sets.

Then again it might instead make sense to add a new annotation altogether, since while somewhat related, adding "duplicate" output is not quite the same as aliases.

**Comment by NurmukhametovAlexey** [comment]
@cowtowncoder, just stumbled upon similar use case in our project. Is this feature still welcome? If so I can try to implement it. The last comment is pretty old so if anything has changed in terms of the preferred solution - please let me know.

**Comment by cowtowncoder** [comment]
@NurmukhametovAlexey if possible to implement cleanly, sure. I am slightly worried about potential complexity from both usage (annotations to add/change) and -- more likely -- internal complexity. But not against the idea itself.

**Comment by cowtowncoder** [comment]
No current plans to implement; closing. May be re-opened if someone has itch and contributes PR.
