### ISSUE TITLE
`TreeTraversingParser.getLongValue()` incorrectly checks `canConvertToInt()`

### ISSUE THREAD

**Issue by RabbidDog** [FasterXML/jackson-databind#2393]
version 2.10.0.pr1

https://github.com/FasterXML/jackson-databind/blob/6a88bc882b464234bab5d5c67709ddab61f5015c/src/main/java/com/fasterxml/jackson/databind/node/TreeTraversingParser.java#L315

should check for canConvertToLong(). Instead checks for canConvertToInt() and throws "JsonMappingException"

**Comment by cowtowncoder** [comment]
Good catch, thank you for reporting!
