### ISSUE TITLE
fasterxml.com has links that still point to Codehaus :(

### ISSUE THREAD

**Issue by paul-hammant** [FasterXML/jackson-databind#2399]

**Comment by cowtowncoder** [comment]
In future, please indicate specific information. I do not doubt there may be leftover instances, but general "there are dangling links over there" is not very actionable.

Fasterxml.com site itself needs to be shut down too, but I don't think I have access. I'll ping Paul.

**Comment by paul-hammant** [comment]
http://fasterxml.com/projects.html has four main links. jackson, Staxmate and Woodstox all link to Codehaus.

**Comment by cowtowncoder** [comment]
@paul-hammant Thanks.
