### ISSUE TITLE
Allow serialization of Enums as JSON Objects

### ISSUE THREAD

**Issue by rveloso** [FasterXML/jackson-databind#24]
Hi,

Any way to treat enums as pojos when serializing them as json? Right now i have to implement yet another class to do the mapping for each enum. Was looking for a jsonmapper.writeValueasString(enum.values()) type of solution...

No such support, except for custom serializers.

So far I hadn't thought it useful to treat enums as POJOs (wrt
serializing properties), mostly because deserialization would be hard
to make work right. But now that I think about it, serialization-only
use case may make some sense.

There is actually even an annotation that could be used to define
this: @JsonFormat.
Maybe something like:

@JsonFormat(shape=Shape.OBJECT)
public enum MyEnum { .... }

so that all that is needed is... well, checking that annotation,
constructing BeanSerializer.

If this would work, can you add a github issue for this? It is in fact
kind of use case for which this annotation was added (currently only
used for configuring Date/Time types in 2.0)

-+ Tatu +-

**Comment by jgribonvald** [comment]
Hello,

Is the override working ? or should we create a JsonDeserializer to pass the toString() value of the enum in property class ?

**Comment by cowtowncoder** [comment]
@jgribonvald I am not sure an issue was created. I think there was one fix to enum + JsonFormat handling however, so it is worth verifying before filing one.

**Comment by jgribonvald** [comment]
Ok I have it, this is working with 2.5 version, but not in 2.4 version provided with last spring boot 1.2.3.

**Comment by remya11** [comment]
Hi,

I am facing an issue with JSON string deserialization, which contains a set of Enum attributes. Whenever an unknown enum attribute comes in, objectMapper.readValue(jsonString,<>.class) throws as InvalidFormatException. 

com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `com.*` from String "Unknown": not a valid representation, problem: (com.fasterxml.jackson.databind.exc.InvalidFormatException) Cannot deserialize Map key of type `com.**.Attribute` from String "Test": not one of values excepted for Enum class: [ ]

These are my settings for ObjectMapper. 
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE);
        objectMapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
        objectMapper.setSerializationInclusion(Include.NON_NULL);
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

I was using jackson-databind version 2.6.3, but just tried upgrading to 2.9.3, but still getting the error.  Could you please let me know if there are any additional properties that I need to set in the configuration?

Thanks!

**Comment by cowtowncoder** [comment]
Please send usage question on mailing list; or, if you have a new issue to report, please file a new issue.
Discussions on closed issues is not a good way to deal with these.
