### ISSUE TITLE
CHANGELOG / release notes

### ISSUE THREAD

**Issue by paul-hammant** [FasterXML/jackson-databind#2401]
https://github.com/FasterXML/jackson-databind/search?q=2.9.9.2&type=Issues
 
.. is where I learn what may have been in 2.9.9.2 and what was a perhaps vulnerability. I mean GitHub tells me that my jackson-databind using projects have vulns, but not what upgrades remediate them. It could do in the future I guess, but off I went to the Jackson project to look for more info and there isn't any. At least none thats prominent. GH has a releases/tags tab, that some projects use for release notes too.  Some projects have something akin to a CHANGES.txt file. Some put that manually in the README or wiki. I think it'd be a useful addition. Then also, looking at 2.10.0.pr1 it is not clear whether that's what I should have upgraded to (versus 2.9.9.2) for the same reason.

- Paul

**Comment by cowtowncoder** [comment]
What exactly is the issue you are reporting here?

Discussions are better for discussion groups:

https://groups.google.com/forum/#!forum/jackson-user

But release notes are here:

https://github.com/FasterXML/jackson/wiki/Jackson-Releases

and for 2.9 specifically:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9

**Comment by paul-hammant** [comment]
My bad, releases is linked to from the README
