### ISSUE TITLE
ObjectMapper config method (type MapperFeature) deprecation / documentation error

### ISSUE THREAD

**Issue by gibbonsj** [FasterXML/jackson-databind#2402]
In version 2.10.0.pr1 the following code is deprecated:

>
> ObjectMapper om = new ObjectMapper();
> om.configure(MapperFeature.PROPAGATE_TRANSIENT_MARKER, true);
> 

The documentation suggests using the following:

>
> ObjectMapper.builder().disable(...)
>

but the builder function is not present. Not sure if this is related to #1954 or documentation drift. Any information or workaround about how to enable a MapperFeature in 2.10.0.pr1 would be appreciated.

**Comment by Alanscut** [comment]
hi, #1954 is not yet released. it shows in master branch: 
`release-notes/VERSION`:
![image](https://user-images.githubusercontent.com/21104054/62405709-4745e280-b5d3-11e9-8bd7-56b3da80cb79.png)

**Comment by cowtowncoder** [comment]
Quick note: in addition to 3.0 vs 2.10 (which is true for many things -- builder() pattern actually was backported in 2.10), documentation should point to

    JsonMapper.builder()

since although at some point the idea of adding builder on`ObjectMapper` was considered it was difficult if not impossible to make it work properly with format-specific subtypes.

**Comment by gibbonsj** [comment]
Thank you @cowtowncoder and @Alanscut.

Using JsonMapper worked. I will keep the issue open for tracking the documentation change per @cowtowncoder's comment above.

Pre-2.10.0 w/ ObjectMapper:

>
> ObjectMapper om = new ObjectMapper();
> om.setSerializationInclusion(Include.NON_NULL);
> om.configure(MapperFeature.PROPAGATE_TRANSIENT_MARKER, true);
>

2.10.0 w/ JsonMapper:

>
> JsonMapper jm = JsonMapper.builder()
>                .configure(MapperFeature.PROPAGATE_TRANSIENT_MARKER, true)
>                .serializationInclusion(Include.NON_NULL)
>                .build();
>
