### ISSUE TITLE
How to emulate GSON's registerTypeHierarchyAdapter

### ISSUE THREAD

**Issue by XakepSDK** [FasterXML/jackson-databind#2406]
GSON has way to register deserializer or serializer as "root" for all subclasses.
E.g. i register deserializer for `Component` interface and GSON will use that deserializer for all implementations of `Component`
How can i achieve this with jackson?

Sorry, i can't ask at google groups, google keeps saying that i can't use my phone number to register account for whatever reason.

**Comment by cowtowncoder** [comment]
Ah ok thank you for ref. for Google groups. Another good place is Gitter (https://gitter.im/FasterXML/jackson-databind).

As to Jackson, if registering for specific nominal base type (that is, type that is declared as type of property) is not enough, what you need to do is to define `Module` (`SimpleModule` usually enough), and register implementation `Deserializers` (not that 's'): it has callbacks for locating deserializer, and you can use whatever logic you want, including checking that type is subtype of what you want to match. Basic implementation (`SimpleDeserializers`) does exact match and would not work in that case, but you can override `findBeanDeserializer(....)`.

**Comment by XakepSDK** [comment]
Thank you. It works now.
