### ISSUE TITLE
`valueToTree()` during serialization (via `SerializerProvider()`)

### ISSUE THREAD

**Issue by XakepSDK** [FasterXML/jackson-databind#2411]
Currently i have this serializer code:
```java
if(value.hasStyling()) {
    JsonNode jsonNode = JacksonComponentSerializer.MAPPER.valueToTree(value.style());
    if (jsonNode.isObject()) {
        Iterator<Map.Entry<String, JsonNode>> fields = jsonNode.fields();
        while (fields.hasNext()) {
            Map.Entry<String, JsonNode> next = fields.next();
            gen.writeFieldName(next.getKey());
            gen.writeTree(next.getValue());
        }
    }
}
```
Can we have some way to convert object to TreeNode without static access to mapper?

**Comment by XakepSDK** [comment]
Still required, as found approach doesn't fit for all serializers, only for some.

**Comment by cowtowncoder** [comment]
This is difficult thing to support, since `valueToTree()` (or conversions in general) are sequences of serialization-then-deserialization, and serialization side does not have support for deserialization (nor is there linkage back to `ObjectMapper` from serializer).
But I agree that ability to perform such conversions for serialization (and deserialization) is useful.

In short term, a work-around is to use `getCodec()` method of `JsonGenerator` that is passed to `serialize()`: that can be used to call conversion methods.

**Comment by cowtowncoder** [comment]
Then again, maybe worth thinking through... since serialization into `TokenBuffer` is easy and exists, so perhaps it'd be possible to have some sort of short-cut and then applicable without fully configured `JsonNode` deserializer.

**Comment by cowtowncoder** [comment]
Ugggggh. The missing piece for otherwise simple implementation is lack of `JsonNodeFactory` from `SerializerProvider` (and `SerializationConfig`).
So to implement this, would need to solve that problem first.

**Comment by cowtowncoder** [comment]
Hmmh. Ok, while 3.0 does give access to `JsonNodeFactory`, there is the secondary problem: `readTree()` used within `ObjectMapper` does everything by the book, creating `DeserializationContext` and this does not exist on serialization-only side of things.
And this access to deserialization things is not just a theoretical problem but there is one problem wrt `BigDecimal` handling, reads; as well as possibility of custom `JsonNode` (or subtype) deserializers.

One possible way forward would be to have alternative shortcut between `JsonNode` and `TokenBuffer` (constructing former from latter, passing in `JsonNodeFactory`. I'll see if that is doable as that seems reasonable, for now.

**Comment by cowtowncoder** [comment]
Still need to add testing for "embedded" variant (one accessed via `SerializerProvider`); refactored implementation of `valueToTree()` in `ObjectMapper` (and one added in `ObjectWriter`) are tested.
