### ISSUE TITLE
Allow for Builder Mixins

### ISSUE THREAD

**Issue by markphelps** [FasterXML/jackson-databind#242]
According to the comments on the usergroup forum post: http://jackson-users.ning.com/forum/topics/deserialize-with-mix-in-annotations-and-builder-pattern, it is possible to allow for builder mixins:

"Ah. So the problem really is that mix-in processing is not being used for builders -- I forgot that this is one limitation. Not a fundamental one, however, it would be technically possible to add support for mix-ins for builder types too. If that sounds useful, feel free to file an RFE at jackson-databind project issue tracker."

Can this be implemented please? The comment goes on to say that there is a workaround: 

"All annotation access by Jackson is via AnnotationIntrospector, originally to support alternative annotation sets (JAXB), but it also serves as general alternative to use of annotations. Not a superbly convenient one but quite powerful."

..however after some searching and trial and error I am not able to get this to work. Any tips would be greatly appreciated.

**Comment by cowtowncoder** [comment]
Not 100% sure any more what exactly was being requested. At this point I think what would be needed is a simple example of intended value and builder types with annotations to show what does not but should work. I'll close this for now; may be reopened with such example.
