### ISSUE TITLE
Block one more gadget type (no CVE allocated yet)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2420]
Similar to other Unbounded Polymorphic Type (default typing, usually) vulnerabilities, one was reported against CXF JAX-RS implementation. Details to be added once specific class added to deny-list.

**Comment by cowtowncoder** [comment]
Block added, will be included in:

* 2.9.10
* 2.10.0.pr2 (and final 2.10.0)

also backported in 2.8 branch but not sure if any more releases for 2.8 will be made.

**Comment by jdelta-RBS** [comment]
@cowtowncoder Assuming this affects 2.7.9.6, 2.8.11.4, and 2.9.9.3, correct?

**Comment by cowtowncoder** [comment]
@jdelta-RBS Correct.

**Comment by yangqi1210** [comment]
@cowtowncoder Does this affect 2.9.9.2 ?

**Comment by jdelta-RBS** [comment]
> @cowtowncoder Does this affect 2.9.9.2 ?

If 2.9.9.3 is affected, 2.9.9.2 is going to be as well.

**Comment by OwenMoriarty-JNJ** [comment]
What needs to happen for a CVE to be assigned?

**Comment by cowtowncoder** [comment]
Someone needs to request id, or find an existing id that was requested and allocated.
I do not have plans to go with the request process at this point.
