### ISSUE TITLE
MixIn annotation not working with class-level annotation such as @JsonTypeInfo

### ISSUE THREAD

**Issue by vinz243** [FasterXML/jackson-databind#2425]
From #2379  with version 2.9.9 but corrected to reproduce the test case

```java
class Animal {
  private String type;
}

class Cat extends Animal { }

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({@JsonSubTypes.Type(value = Cat.class, name = "cat")})
abstract class SubTypesMixin { }


  @Test
  public void mixinsShouldWorkWithSubtypesAnnotations() throws IOException {
    // given
    String json = "{\"type\":\"cat\"}";
    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.addMixIn(Animal.class, SubTypesMixin.class);

    // when
    Animal animal = objectMapper.readerFor(Animal.class).readValue(json);

    // then
    assertEquals(animal.getClass(), Cat.class);
  }
```

**Comment by Alanscut** [comment]
I tested it with your test case and found that it can pass.
The MixIn configuration doesn't work in #2379  because it recreated a `ObjectMapper`.
```java
    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.addMixIn(Animal.class, SubTypesMixin.class);
    Animal animal = new ObjectMapper()  // not the objectMapper which has registered a MixIn annotation
        .readerFor(Animal.class)
        .readValue(json);
```

**Comment by vinz243** [comment]
That's weird, I get this issue with different classes but similar structure. I would need to investigate. Which version were you using?

**Comment by Alanscut** [comment]
version:2.9.9 and 2.10.0.pre
and test in mac and win7.
<img width="624" alt="1" src="https://user-images.githubusercontent.com/21104054/63277903-cc6e0e80-c2d8-11e9-9aa2-2130308304fa.png">

**Comment by vinz243** [comment]
While trying to reproduce I just realized it was in a different class, and that the RestTemplate used was another instance... My mistake

**Comment by cowtowncoder** [comment]
Ok, thank you for follow up!

**Comment by paroxayte** [comment]
This is a real problem outside of any errant test cases. JsonSubType mixins definitely do not work. I can provide a simple reproducible case if need be.

**Comment by cowtowncoder** [comment]
@paroxayte There are no existing test cases to indicate a known problem, so if you do have a test case, please file a new issue with test.
