### ISSUE TITLE
Provide a DeserializationProblemHandler that sends stuff to JsonAnySetter

### ISSUE THREAD

**Issue by sixcorners** [FasterXML/jackson-databind#2427]
Could we get an implementation of DeserializationProblemHandler that sends weird strings to the JsonAnySetter field included with the project? Is that possible to do and would that be a good idea?
What I'm trying to do is parse things into fields but if they can't be parsed then leave them alone essentially by leaving them in the JsonAnySetter field.

**Comment by cowtowncoder** [comment]
Hmmh. I'd have to think about this.

On one hand, yes, providing useful functionality makes sense. But on the other hand it should be part of good API, and what I do not want to do is to have a general list of things that users need to separately register ("util classes").
That is, I do not want to include such handles in `jackson-databind`: however, having a separate library, repository, with common implementations, might make sense (there are some caveats with these too of course, regarding usability).

The main challenge is that I don't think there is existing "jackson-databind-utils" or "jackson-commons" project to use. This might be something to bring up on `jackson-dev` mailing list?

**Comment by sixcorners** [comment]
k. I'll put it somewhere else for now if I successfully make something. Thanks for the consideration.

**Comment by cowtowncoder** [comment]
@sixcorners Ok. Thank you for bringing this up tho: I feel there is need for something to help community share useful things, even if they don't cleanly integrate with databind.
