### ISSUE TITLE
Change `ObjectMapper.valueToTree()` to convert `null` to `NullNode`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2430]
It looks like `valueToTree()` method will currently simple return `null` if `null` is passed.
For many other conversions this makes sense, but in case of `JsonNode`, it would make more sense to return `NullNode`.

**Comment by asnare** [comment]
Interestingly, I think this change leads to a subtle behaviour change when combined with Jdk8Module. We have a test for a `@JsonCreator` method that has an `Optional<JsonNode>` parameter. Prior to this change a field that wasn't present would get mapped to `Optional.empty()`, whereas now it gets mapped to `Optional.of(NullNode)`.

I guess it's splitting hairs, but previously this meant it was possible to differentiate between an attribute that was missing entirely and one that was present but with `null` assigned. Now they seem to be treated as exactly equivalent. (Is this correct?)

**Comment by cowtowncoder** [comment]
@asnare Hmmh. So, two things should not be directly related: `treeToValue()` has specific handling where `null` from `JsonParser` is received. It should not be used by code that handles `@JsonCreator` values: that should just get `null`. I do agree that `Optional<JsonNode` from null token should become `Optional.empty()`, and not `Optional.of(nullNode)`. Question then is... why did behavior change?

IF you can easily reproduce this, could you please file an issue against `jackson-modules-java8`?
