### ISSUE TITLE
Bug when read two times from ObjectMapper - Spring Boot. Jackson 2.10.0.pr1

### ISSUE THREAD

**Issue by luizlucca** [FasterXML/jackson-databind#2435]
Hello guys. I'm using spring-boot on my project and I wrote a deserializer for a class
```java
public class MyDeserializer extends JsonDeserializer<MyClass> {

    @Autowired
    private ObjectMapper objectMapper;

    @Override
    public MyClass deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
        try {
            String result = objectMapper.readValue(p, String.class);
            if (StringUtils.isNullOrEmpty(result)) {
                return new MyClass();
            } else {
                return objectMapper.readValue(p, MyClass.class);
            }
        } catch (Exception e) {
            log.error("[ERROR] Deserialize error", e);
            throw new JsonDeserializerException();
        }
    }
}
```

The version above has a error because i invoke objectMapper.readValue(p, MyClass.class) twice; --it's a bug???

if i change to:

```java
public class MyDeserializer extends JsonDeserializer<MyClass> {

    @Autowired
    private ObjectMapper objectMapper;

    @Override
    public MyClass deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
        try {
            String result = objectMapper.readValue(p, String.class);
            if (StringUtils.isNullOrEmpty(result)) {
                return new MyClass();
            } else {
                return objectMapper.readValue(result, MyClass.class); //----- I change p TO result here!!!
            }
        } catch (Exception e) {
            log.error("[ERROR] Deserialize error", e);
            throw new JsonDeserializerException();
        }
    }
}
```

With **objectMapper.readValue(p, MyClass.class)** (second time), jackson ignore the conversion to MyClass and return null. With  **objectMapper.readValue(result, MyClass.class)** (second time) it works.

**Comment by cowtowncoder** [comment]
What exactly are you trying to achieve here? I don't think I actually understand your use case (and from that, code itself does not make full sense).

As in: what kind of JSON, what is the problem wrt standard deserializer.

Couple of pointers to help: ideally you should NOT use `objectMapper` at all: `DeserializationContext` should have methods you need.

Second: if you are just trying to read JSON String value, `JsonParser` is the object you usually use (check `p.getCurrentToken()` for type, `p.getText()` to get String value).

But fundamentally it matters a lot what kind of JSON content you are thinking: can it be either String OR Object? Or just String always? If latter, is that String JSON-encoded "JSON in JSON"?

**Comment by luizlucca** [comment]
It's a businnes rule.
Yes, using `p.getText()` works to get only the text. But MyClass is a complex class with list of another objects (that contains another objects).

The Seriazer (not problem with serializer) and deserializer use:
`......`
`@JsonDeserialize(using = StringToMessageDataDeserializer.class)`
`private MyClass data;`
`.......`

The problem is:

-  I need to deserialize text inside a variable to a MyClass. The text of variable that hit our API is a JSON from external partner.

- Exists a businnes rule that, if the text is not parseable to json and is "", the flow should continue.

- Any other case is error, ie 
--"{ bla: ble " -> parse error.
--";" -> error

I need to use the mapper twice:
- first to verify some attibutes
- then, decide if there is a normal flow or an error

**Comment by luizlucca** [comment]
It works:
`String result = objectMapper.readValue(p,String.class); // should handle a string json`
`return objectMapper.readValue(result, MyClass.class); //here, return instance of MyClass.` 

It not works:
`return objectMapper.readValue(result, MyClass.class); //direct conversion to an instance of MyClass fails`

MyClass has all the necessary get / set and constructors.

**Comment by cowtowncoder** [comment]
@luizlucca Could you give me a specific example of JSON input as well as HOW does conversion fail. It is not enough to say "it fails" -- there are many ways in which things can fail.

And as to code, this:

```
String result = objectMapper.readValue(p, String.class);
```

will ONLY read a JSON String value, not JSON object or anything else. This is why I am asking.

**Comment by luizlucca** [comment]
Hello @cowtowncoder. Because compliance i don't have permission to exposes the class as is. But I changed the names and here is the problem:
```
 **----------------- JSON -----------------**
{
   ...
   "data": "{\"processable\":false}"
   ...
}

 **----------------- AnotherClass -----------------**
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class AnotherClass{

    @JsonDeserialize(using = MyDeserializer.class)
    private MyClass data;
}

 **----------------- MyClass -----------------**
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class MyClass{
    private Boolean processable;
}

**------------ Deserializer ------------**
@Slf4j
public class MyDeserializer extends JsonDeserializer {
    @Autowired
    private ObjectMapper objectMapper;

    @Override
    public Object deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
        try {
            //if remove this, object is mappead as null
            String result = objectMapper.readValue(p,String.class); 
            // i need to use result here. objectMapper.readValue(p, MyClass.class) does not works.
            return objectMapper.readValue(result, MyClass.class);
        } catch (MismatchedInputException me) {
            log.error("Deserialize error", me);
            return new MyClass(); //Business rule here. If text is
        } catch (Exception e) {
            log.error("Deserialize error", e);
            throw new JsonDeserializerException();
        }
    }
}```

Sorry by don't have permission to expose the real classes. The code above help you to understant the problem?

Big hug!

**Comment by cowtowncoder** [comment]
Thank you -- I understand that sharing exact classes and data is not always possible.
I'll have a look, this should help.

**Comment by cowtowncoder** [comment]
Ok. So, first things first: you are trying to map this value (as an example), with `MyDeserializer`:

```
{"processable":false}
```

and that can not (and should not) be attempted to bind as Java `String`. It is a JSON Object, and deserialization attempt should fail: `ObjectMapper.readValue(p, String.class)` ought to complain.
In worst case, it might actually read "processable" as the value. So that is not something that should work, unless your JSON value is String. It does not just read any JSON content and somehow retain it as JSON, it processes JSON String value, resolving escapes and so on.

But if you do not know the type (could be JSON Object, String, `null`), you can read it as `JsonNode` easily:

```java
    JsonNode stuff = p.readValueAsTree();
    // OR
    JsonNode stuff = ctxt.readValue(p, JsonNode.class);
```

Second: once you have that value, you and either read from it -- you can create `JsonParser` out of `JsonNode` with:

    JsonParser nodeParser = stuff.traverse();

to do another `readValue()` (or, call methods on it). Or, if you have an `ObjectMapper`, you can call `ObjectMapper.treeToValue()` to convert value: this is essentially similar to writing contents, reading back in.

So, you might want to try something like:

```java
JsonNode json = p.readValueAsTree();
if (json.isObject()) {
    return ctxt.readValue(json.traverse(), MyClass.class);
}
// otherwise... return something else?
```

I hope this helps.

**Comment by cowtowncoder** [comment]
As to the original question: since reading from `JsonParser` typically consumes input (advances token stream), no, it is not possible to read same content twice: instead, content read must be re-processed.
So in given example reading it first as `String` is one way to do it.
For other usage ideas, discussion group:

https://groups.google.com/forum/#!forum/jackson-user

is a good follow-up forum.

**Comment by unoexperto** [comment]
@luizlucca Did you come up with solution to your use-case ? I'm facing exact problem.

**Comment by unoexperto** [comment]
Well, it ended up being much harder than it could be. Took me over a day to figure this out. For those who'll come here from Google search:

```
class ObjectFromJsonStringDecoder<T>(private val defaultDeserializer: JsonDeserializer<*>, private val clazz: Class<T>) : StdDeserializer<T>(clazz), ResolvableDeserializer {
    @Suppress("UNCHECKED_CAST")
    override fun deserialize(p: JsonParser, ctxt: DeserializationContext): T {
        val mapper = p.codec as ObjectMapper
        val parser = mapper.factory.createParser(p.valueAsString)
        mapper.deserializationConfig.initialize(parser)
        while (parser.currentToken == null)
            parser.nextToken()
                    ?: throw MismatchedInputException.from(p, clazz,
                            "No content to map due to end-of-input")

        val value: T = defaultDeserializer.deserialize(parser, ctxt) as T
        return value
    }

    override fun resolve(ctxt: DeserializationContext) {
        (defaultDeserializer as ResolvableDeserializer).resolve(ctxt)
    }
}

    val simpleModule = SimpleModule()
    simpleModule.setDeserializerModifier(object : BeanDeserializerModifier() {
        override fun modifyDeserializer(config: DeserializationConfig, beanDesc: BeanDescription, deserializer: JsonDeserializer<*>): JsonDeserializer<*> {
            if (beanDesc.beanClass == LogMessage::class.java)
                return ObjectFromJsonStringDecoder(deserializer, LogMessage::class.java)
            else
                return super.modifyDeserializer(config, beanDesc, deserializer)
        }
    })

    mapper.registerModule(simpleModule)
```

Where `LogMessage` is class that is encoded as string with serialized json in it.
