### ISSUE TITLE
Using @JsonCreator with enum couse no error on incompatible types 

### ISSUE THREAD

**Issue by kgonia** [FasterXML/jackson-databind#2437]
Hi,

I have ENUM with method @JsonCreator annotation on method.

```
    @JsonCreator
    public static AccountType safeValueOf(final String string) {
          //some logic
    }

```

This enum is used as one of fields in some class, let his name be Payload.

```
    @NotNull
    private AccountType accountType;
```

Everything works fine when body of request has string as accountType fields like this:

```
{
...
"accountType" : "some_string",
...
}
```

But problems occur when someone tries to send incorrect data like list 

```
{
...
"accountType" : ["some_string"],
...
}
```
Then, instead of throwing error MismatchedInputException Jackson call annotated method with null parameter.

Is it supposed to work that way? Can I ensure that only string will be treat as valid param?

My jackson version: core: 2.9.8

**Comment by cowtowncoder** [comment]
@kgonia Unfortunately this is not quite enough to say what is going on, but I don't think that is expected behavior. So more details of how value is read would be needed.

**Comment by kgonia** [comment]
@cowtowncoder Should I add test case in project repo or create separate project with showcase ?

**Comment by cowtowncoder** [comment]
@kgonia project repo, or even just copy-paste class here if simple enough. Full project also works but I like concise tests where possible.
