### ISSUE TITLE
Map with enum keys not using custom JsonSerializer<Enum<?>>

### ISSUE THREAD

**Issue by joca-bt** [FasterXML/jackson-databind#2440]
I've defined a custom `JsonSerializer<Enum<?>>`. When serializing plain enum fields it works fine but when serializing map fields whose keys are enums my custom serializer is not being picked up to serialize the map keys.

```
public class Constants<T extends Enum<T>> {
    private final Map<T, List<Object>> constants;

    public Constants(Class<T> enumType) {
        this.constants = new EnumMap<>(enumType);
    }
...
}

@JsonComponent
public class EnumSerializer extends JsonSerializer<Enum<?>> {
    @Override
    public void serialize(Enum<?> value, JsonGenerator generator, SerializerProvider provider) throws IOException {
        generator.writeString(value.name().toLowerCase());
    }
}
```

I'm using Jackson 2.9.9 on a Spring Boot 2.1.7 service.

**Comment by cowtowncoder** [comment]
Key serializers and deserializers must be registered separately from regular value (de)serializers.
For key deserialization there is separate `KeyDeserializer`, although for serialization implementation is just `JsonSeriializer`, but needs to be registered separately as underlying write method to use is different -- so your implementation would not actually work (need to use `writeFieldName()`).

Example above seems to rely on framework to do registration, so I am not sure how it needs to be changed, however. Registration can not rely on `JsonSerializer` type, unfortunately (as per above, you typically need different impl for value and key serializers)

**Comment by joca-bt** [comment]
How can I register it with standard Jackson? I don't find any `writeFieldName()` in http://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/JsonSerializer.html.

**Comment by cowtowncoder** [comment]
Usually registration is done via `Module`: there is `SimpleModule` implementation with method `addKeySerializer()`. Module itself is registered with `ObjectMapper.registerModule()`.

`writeFieldName()` refers to method in `JsonGenerator` to call: you can find examples from, say:

     src/main/java/com/fasterxml/jackson/databind/ser/std/StdKeySerializers.java

I hope this helps.

**Comment by joca-bt** [comment]
Do you mean
http://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/Module.SetupContext.html#addKeySerializers-com.fasterxml.jackson.databind.ser.Serializers-
+
http://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/ser/Serializers.html#findMapSerializer-com.fasterxml.jackson.databind.SerializationConfig-com.fasterxml.jackson.databind.type.MapType-com.fasterxml.jackson.databind.BeanDescription-com.fasterxml.jackson.databind.JsonSerializer-com.fasterxml.jackson.databind.jsontype.TypeSerializer-com.fasterxml.jackson.databind.JsonSerializer-
?

Because `findMapSerializer` is not being called.

**Comment by cowtowncoder** [comment]
Should not need to override `findMapSerializer()`, since serializers/deserializers are composed recursively; Map (de)serializer is either given key/value deserializer during construction, or it looks them up from `createContextual()` (or in some cases dynamically). Simply registering via `addKeySerializer()` of `SimpleModule` OR if writing more customized module, register via `SetupContext.addKeySerializers()`.

For low-level registration you can have a look at `SimpleKeyDeserializers` implementation which is what `SimpleModule` uses.

**Comment by joca-bt** [comment]
I've managed to do it, however it's not very easy to figure it out from the documentation. Thanks for the tips. Here's the code (customizing serializers to write enum in lowercase):

```
@Component
public class JsonConfiguration extends Module {
    @Override
    public String getModuleName() {
        return getClass().getName();
    }

    @Override
    public void setupModule(Module.SetupContext context) {
        context.addKeySerializers(new EnumKeySerializers());
    }

    @Override
    public Version version() {
        return Version.unknownVersion();
    }

    public static class EnumKeySerializers extends com.fasterxml.jackson.databind.ser.Serializers.Base {
        @Override
        public JsonSerializer<?> findSerializer(
                SerializationConfig config,
                JavaType type,
                BeanDescription description) {
            if (type.isEnumType()) {
                return new Serializers.EnumKeySerializer();
            } else {
                return null;
            }
        }
    }
}

public class Serializers {
    @JsonComponent
    public static class EnumSerializer extends JsonSerializer<Enum<?>> {
        @Override
        public void serialize(Enum<?> value, JsonGenerator generator, SerializerProvider provider) throws IOException {
            generator.writeString(value.name().toLowerCase());
        }
    }

    public static class EnumKeySerializer extends JsonSerializer<Enum<?>> {
        @Override
        public void serialize(Enum<?> value, JsonGenerator generator, SerializerProvider provider) throws IOException {
            generator.writeFieldName(value.name().toLowerCase());
        }
    }
}
```

**Comment by cowtowncoder** [comment]
Thank you fr sharing the workaround.

With `@JsonComponent`, I assume this is for use by specific framework?

One last note: with `Enum`s, you can also use `@JsonValue` to indicate serialization, so another way would have been to change Enum values:

```java
public enum LCEnum {
    A, B, C;

    @JsonValue
    public String serializeAs() { return name().toLowerCase(); }
}
```

**Comment by joca-bt** [comment]
The `@Component` and `@JsonComponent` are Spring Boot annotations. We have a lot of enums, that's why we went with custom serializer vs `@JsonValue`.

**Comment by cowtowncoder** [comment]
Makes sense, just wanted to verify annotations in case others find the issue (to know what they are for).
And yes, with larger number custom serializer makes sense.
