### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/cfg/MapperBuilder

### ISSUE THREAD

**Issue by RicardoPoleo** [FasterXML/jackson-databind#2444]
I'm using a third-party library that happens to use Jackson-databind but, while I'm running it, this error appears:

```
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.cfg.MapperBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211]
```

I have been searching that .jar like there is no tomorrow, to add it to the library but, for some reason, I'm not able to find it.

If you guys are using or know where to find it, I would very much appreciate if you guys share it.

Thank you very much!

**Comment by cowtowncoder** [comment]
It is part of upcoming 2.10 release of `jackson-databind`, with maven group id of `com.fasterxml.jackson.core`. But you must be using a pre-release version somehow (2.10.0.pr1 or .pr2 or 2.10.0-SNAPSHOT).

**Comment by RicardoPoleo** [comment]
You were right, I was trying with the pre-release .pr2, change the version to a more stable one and everything worked like a charm!

Once again, Thank you very much!

I'm closing this issue since that was enough for my problem

**Comment by cowtowncoder** [comment]
np!
