### ISSUE TITLE
Make Serializers/Deserializers Serializable (i.e. implement Serializable)

### ISSUE THREAD

**Issue by lfrittelli** [FasterXML/jackson-databind#2452]
When using the support for JSR310 LocalDateTime I've noticed that even though JavaTImeModule is serializable, the Serializsers themselves are not.

This is an issue with using jsr310 enhanced ObjectMappers over streaming platforms such as Apache Flink as these require that all entities participating in the pipeline are suitable for serialization.
Looking at the source code for several serializers (e.g. LocalDateTimeSerializer) it would appear that the class is suitable for serialization, but the marker interface is missing.

Would you please consider adding this support?

**Comment by cowtowncoder** [comment]
I think this is same as:

https://github.com/FasterXML/jackson-modules-java8/issues/111

(and issue definitely would belong under that repo)

and although attempt was made to make module serializable, there is what seems like a fundamental problem wrt underlying JDK 8 formatter functionality, unfortunately. I would love to fix this, but not sure how it could be achieved.

So, closing this one, comments to be added on the other issue.
