### ISSUE TITLE
`Nulls` property metadata ignored for creators

### ISSUE THREAD

**Issue by XakepSDK** [FasterXML/jackson-databind#2458]
I'm using jackson databind 2.9.9.3.
I'm trying to deserialize object with creator. I've set
```
objectMapper.setDefaultSetterInfo(JsonSetter.Value.construct(Nulls.AS_EMPTY, Nulls.AS_EMPTY))
```
But jackson tries to put null instead of empty set in my constructor.

I debugged jackson and found, that jackson calls `BasicDeserializerFactory#constructCreatorProperty` to get constructor argument property(class `CreatorProperty`).
This class holds `ProperyMetadata`, which is used later to handle `Nulls` value.

`PropertyMetadata` constructed using `PropertyMetadata.construct` method (line 1066 in source code in IDE or https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java#L930 in current)

This call does not fill `_valueNulls` and `_contentNulls`. Looks like JsonSetter annotation and defaults are completely ignored for constructor arguments.

Is this intended? How can i prevent jackson from putting nulls in my contructor?

**Comment by cowtowncoder** [comment]
It sounds like a bug. What would be super useful is a simple unit test to show the problem, might be easy to fix.

**Comment by XakepSDK** [comment]
https://gist.github.com/XakepSDK/ed57a991510848f19aebc4ebff535ef0

**Comment by cowtowncoder** [comment]
Thanks!

**Comment by cowtowncoder** [comment]
Ok, so looks like `NullValueProvider` for `SettableBeanProperty` is not considered during checking of values by `PropertyValueBuffer` in `getParameters()` where null-check for `DeserializationFeature.FAIL_ON_NULL_CREATOR_PROPERTIES` is made.

It looks like there is already a loop for checking "missing" properties, which seems like the place to do call for `NullValueProvider`... I'll see if I can find a way to get NVP for property.

**Comment by cowtowncoder** [comment]
Ok. Looks like wiring of above is actually quite easy: `PVB._findMissing()` has all the info. But unfortunately `NullValueProvider` assigned is just the deserializer, not empty value provider, so something else is not properly wired I think.

This is pretty severe shortcoming as it looks like case of null-value conversion is only tested via setter/field, but not constructor parameters. Clear oversight from 2.9 tests for the new feature.

**Comment by cowtowncoder** [comment]
Looks like somehow `CreatorProperty` is missing `PropertyMetadata.getValueNulls()`, from `resolve()` of deserializer associated with property: this is different from `MethodProperty` receiving same info somehow. Creator properties are created using different code path than other kinds, but obviously should not matter in this respect.

**Comment by cowtowncoder** [comment]
Ok. I think I see what is happening. It is in fact due to different construction paths.

For non-creator properties, `POJOPropertyBuilder` instance (per property, managed by `POJOPropertiesCollector`) handles collection of `PropertyMetadata`, and finds necessary pieces. For creator properties (`CreatorProperty`), `PropertyMetadata` is collected in `BaseDeserializerFactory.constructCreatorProperty()`. Latter was not augmented with access to merge-info it seems, and needs to be.
