### ISSUE TITLE
Version scheme used by project

### ISSUE THREAD

**Issue by pzygielo** [FasterXML/jackson-databind#2476]
Unfortunately version scheme used by this project makes tools to recognize version [2.10.0](https://github.com/FasterXML/jackson-databind/releases/tag/jackson-databind-2.10.0) as not higher than [2.10.0.pr3](https://github.com/FasterXML/jackson-databind/releases/tag/jackson-databind-2.10.0.pr3) (for example snyk classifies this just-released 2.10.0 as not solving [467015](https://app.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-467015), and maven-enforcer also considers .pr3 release as higher version, and [versions-maven-plugin](http://www.mojohaus.org/versions-maven-plugin/) suggests:
```
[INFO] --- versions-maven-plugin:2.7:display-dependency-updates (default-cli)  @ ... ---
[INFO] artifact com.fasterxml.jackson.core:jackson-core: checking for updates ...
[INFO] The following dependencies in Dependency Management have newer versions:
[INFO]   com.fasterxml.jackson.core:jackson-core ......... 2.10.0 -> 2.10.0.pr3
```
).

**Comment by cowtowncoder** [comment]
This is unfortunate. When selecting qualifier to use, I was assuming Maven and tooling would use same logic for `pr` as for `rc` (as an example).
We will change qualifier to use for later minor versions, but since `pr1` - `pr3` are out now, there isn't much we can do. There will be `2.10.1` soon if history is any prediction (there is usually big influx of bug reports for `.0` versions...), which will sort as expected, at least.

But FWTW, we are aware of (some of) the issues regarding choice of qualifier. I just wish users had reported this when `2.9` was released as naming scheme was used back then too (and over time a few variants were attempted; `RC`, `rc` -- `pr` was selected over `rc` since these are not release candidates but pre-release alpha/beta/gamma style "close but not exactly").

Anyway: thank you for reporting the issue. We will use better versioning scheme in future.

**Comment by cowtowncoder** [comment]
I also need to somehow indicate that CVE mentioned IS NOT applicable to 2.10 -- as per CVE definition rules, it not being available with default settings (`ObjectMapper.enableDefaultTyping()`, now deprecated in 2.10, is needed), and I will try my best to ensure none (of this type) are marked applicable against ANY 2.10 versions.
Block list additions will be accepted, but not 2.10 (and beyond) applicability.

**Comment by pzygielo** [comment]
> same logic for `pr` as for `rc` (as an example).

I'm not sure it's the cause, but checking https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/ shows difference - as (some) previous `rc`, `RC`releases use dash to separate version from qualifier, while `pr3` is 4th dotted component.

Thanks for checking and considering change.

**Comment by pzygielo** [comment]
> > > same logic for `pr` as for `rc` (as an example).
> > 
> > I'm not sure it's the cause, but checking https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/ shows difference - as (some) previous `rc`, `RC`releases use dash to separate version from qualifier, while `pr3` is 4th dotted component.
> > 
> > Thanks for checking and considering change.

So it seems _dotted_ `pr` [shall be recognized](https://maven.apache.org/pom.html#Version_Order_Specification) in similar way:
> A transition between digits and characters is equivalent to hypen [...]

but I'll have to re-study this section :grin:

**Comment by cowtowncoder** [comment]
I saw a good document: 

https://octopus.com/blog/maven-versioning-explained

that sheds some light here.

One note: I did use "2.7.0-rc1" at some point, but unfortunately OSGi does not work with such version numbers; this is why we changed to all-dot separation. But use of qualifier (I think that is the term) was based on incomplete understanding: use of "m" for "milestone" would have worked better.

**Comment by cowtowncoder** [comment]
Created follow-up as: #2479

**Comment by GedMarc** [comment]
Should it be rc lowercase or uppercase? I've seen both now on maven while researching on this

**Comment by pzygielo** [comment]
> Should it be rc lowercase or uppercase? I've seen both now on maven while researching on this

I guess due to https://github.com/apache/maven-artifact/blob/ab6be5e8c9d05f20dd37f813063482493788d1e9/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java#L331:
```java
    public final void parseVersion( String version )
    {
        this.value = version;

        items = new ListItem();

        version = version.toLowerCase( Locale.ENGLISH ); // <<<
```

case does not matter for ordering:
```
$ java -jar maven-artifact-3.6.2.jar 1.rc-1 1.RC-1
Display parameters as parsed by Maven (in canonical form) and comparison result:
1. 1.rc-1 == 1.rc-1
   1.rc-1 == 1.RC-1
2. 1.RC-1 == 1.rc-1
```
