### ISSUE TITLE
updateValue nulls unrelated fields when updating hierarchical structures

### ISSUE THREAD

**Issue by dodie** [FasterXML/jackson-databind#2477]
I bumped into the following with `com.fasterxml.jackson.core:jackson-databind:2.9.9`.

I have the following classes:

```java
public class Person {
    private String name;
    private Address address;
    // getters-setters
}

public class Address {
    private String city;
    private String country;
    // getters-setters
}
```

When I try to update the `city` property of the `address` field of a `Person`  with `updateValue`, it nulls the unrelated `country` field.

```java
assertThat(original.address.getCountry(), not(nullValue()));
Map<String, Object> updates = Map.of("address", Map.of("city", "London"));
Person updated = objectMapper().updateValue(original, updates);
assertThat(original.address.getCountry(), not(nullValue())); // <- address.city modified as expected, but address.country is nulled
```

Is there a way to preserve unrelated values in these cases?

Note, that the same scenario works as expected with `Map`:

```java
Map<String, Object> original = /* map containing address.country */;
Map<String, Object> updates = Map.of("address", Map.of("city", "London"));
assertThat(((Map)original.get("address")).get("country")), not(nullValue())); // not null value, as expected
```

**Comment by cowtowncoder** [comment]
It would be good to get full reproduction, but I may know what is going on here without it,

Note that `updateValue()` by default only does "shallow" merge: it will replace values of main level properties, but does not attempt to merge values container.

At least not by default: Jackson 2.9 does add support for full merging:

https://medium.com/@cowtowncoder/jackson-2-9-features-b2a19029e9ff

using new `@JsonMerge` annotation, or one of alternatives (config override for types).
This could be used to make example work, I think, the way you want.

**Comment by dodie** [comment]
Hey @cowtowncoder ,

thanks for the pointers! Based on the post you've linked I [created some tests](https://github.com/dodie/working-with-structured-data-in-java/blob/master/src/test/java/hu/advancedweb/datamapper/DeepMergeTest.java) to try deep merging. By specifying `mapper.setDefaultMergeable(true)`, it indeed works like a charm.

Thank you,
David

**Comment by cowtowncoder** [comment]
Great! Thank you for the update.
