### ISSUE TITLE
Change pre-release versioning scheme for Jackson 2.11

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2479]
One thing we have learned from 2.10 release process is that use of `pr` qualifier does not work well with Maven ecosystem. Looking at:

https://octopus.com/blog/maven-versioning-explained

the problem can be explained by there being a number of "well-known" qualifier with specific semantics, but `pr` not being one of them -- so it ends up getting sorted "after" other qualifiers. This is unfortunately exactly what we do not want.

With 2.11 let's use something else: maybe `m` for "milestone" builds, or `a`/`alpha` etc.

**Comment by jorsol** [comment]
If hyphen apparently can not be used in OSGi, just keep using the dot since it should work almost the same:
```
Display parameters as parsed by Maven (in canonical form) and comparison result:
1. 2.11.0.m3 == 2.11.0.milestone-3
   2.11.0.m3 < 2.11.0
2. 2.11.0 == 2.11
   2.11.0 > 2.11.0-m3
3. 2.11.0-m3 == 2.11-milestone-3 
```

You can make your a simple test using: `java -jar $MAVEN_HOME/lib/maven-artifact-3.6.2.jar 2.11.0 2.11.0.m2` to check what works for you, just pass the versions as parameters.

**Comment by cowtowncoder** [comment]
@jorsol thank you for information! I was thinking dot should work, but just worth mentioning as context. And yes, using recognized qualifier makes the expected difference, now that there is a better list of which ones are recognized.

**Comment by cowtowncoder** [comment]
As per Totally Scientific Twitter Poll conducted via `@fasterxml`, of 3 choices:

1. `2.11.0.alpha1`
2. `2.11.0.rc1`
3. `2.11.0.m1`

Choice (2) was crowd favorite with 75% vote ratio.

So we will go with `2.11.0.rc1`.
