### ISSUE TITLE
BeanDeserializerBuilder Protected Factory Method for Extension

### ISSUE THREAD

**Issue by vjkoskela** [FasterXML/jackson-databind#2487]
In #1870 we were able to switch from creating custom builder deserializers using encapsulation to using inheritance. This greatly simplified our code and allowed it to move from `com.fasterxml` into our package (since we no longer required access to package private methods). (Thank you!)

The next step in allowing builder deserializers to be customized would be to simplify their creation in [BeanDeserializerBuilder.java#L442](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializerBuilder.java#L442).

Our custom builder deserializer has a corresponding builder deserializer builder, but currently we need to override the entire `buildBuilderBased` method in our class when all we want to change is the type of builder deserializer created. Since our builder deserializer is a subclass of `BeanDeserializerBuilder` it has a constructor which accepts _at least_ the same arguments as `BeanDeserializerBuilder`. 

For our use case at least, delegating the construction of `BeanDeserializerBuilder` to a separate protected ("factory") method would decouple the logic in `buildBuilderBased` from the type of builder deserializer created. 

Further generalizations would be possible by registering the type of builder to be created although I am unclear on the ROI of such a change and how it fits architecturally with the project.

Let me know what you think! I can definitely submit a patch for the simple refactoring of `BeanDeserializerBuilder`, but I'm curious if you have some insight into how to make this more flexible.

Jackson Version: 2.10.0

**Comment by cowtowncoder** [comment]
Too bad this did not quite make it in 2.10.0, but I hope to make 2.11 dev cycle much shorter than 2.10, release candidates getting released by Dec 2019.

**Comment by cowtowncoder** [comment]
Oh, also: yes, further simplifications would also be welcome, targeted for 2.11.
Support for builder-based construction is becoming more and more important so it'd be good to improve Jackson's handling. I haven't had time to focus on it myself so really appreciate your help here.

**Comment by cowtowncoder** [comment]
Decided that since this is backwards-compatible after all, I can (and did) add this in 2.10 for 2.10.1.
So the "official" addition is in 2.11(.0), but it will technically be included in 2.10.1 and after.

**Comment by vjkoskela** [comment]
Thank you! If you have some thoughts on strategies for builder deserializer generalization please let me know.

**Comment by cowtowncoder** [comment]
Definitely, will do!
