### ISSUE TITLE
Unresolved jackson depdencies when building dependent code with JDK8

### ISSUE THREAD

**Issue by stappe44** [FasterXML/jackson-databind#2494]
Seems like there is an issue with OSGI bundle with jackson-databind 2.10.0 bundling it as dependency fails to load jackson modules when built using JDK 8.

When using maven bundle plugin with JDK8 upto Jackson version 2.9.10, bundle gets built correctly and all the dependencies are loaded correctly. After upgrading to 2.10.0, i ran into dependency resolution issues with OSGI bundle.

Unresolved requirement: Import-Package: javax.xml.bind
-> Export-Package: javax.xml.bind; bundle-symbolic-name="com.module.restapi"; bundle-version="9.1.9.SNAPSHOT"; version="2.3.2"; uses:="javax.xml.bind.annotation.adapters,javax.xml.bind.attachment,javax.xml.namespace,javax.xml.stream,javax.xml.transform,javax.xml.validation,org.w3c.dom,org.xml.sax"
com.module.restapi [185]
Unresolved requirement: Import-Package: javax.activation; version="[1.2.0,2.0.0)"

**Comment by cowtowncoder** [comment]
Dup of #2490
