### ISSUE TITLE
asText(): NullNode vs. MissingNode

### ISSUE THREAD

**Issue by jakajancar** [FasterXML/jackson-databind#25]
```
scala> MissingNode.getInstance().asText()
res12: java.lang.String = ""

scala> NullNode.instance.asText()
res13: java.lang.String = null
```

Is it expected that MissingNode returns ""?

**Comment by bozaro** [comment]
NullNode.asText() { return "null"; }

**Comment by bozaro** [comment]
Не используйте asText()

**Comment by bozaro** [comment]
Или на край asText(null)

**Comment by cowtowncoder** [comment]
Anyone reading this issue: if you would prefer to see a String value (most likely either "" or "null"), please file a new issue with the request for change. Such could be considered for Jackson 3.0.
