### ISSUE TITLE
Add a way to configure caches Jackson uses

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2502]
(note: follow up on #2456 )

Currently most of caching Jackson does internally (for reusing things like serializers, deserializers, to avoid re-resolving some generic types and so on) is internally defined with settings that can not be changed. But it would make sense to expose an interface, like cache provider, that could be changed to override either some parameters (sizes for default caches) or even cache implementations if that matters. This would also allow things like instrumentation  (for cache hit rates) and using time-based eviction, dynamic sizing and so on.

Known caches are in:

* `DeserializerCache` (added via #4101)
* `SerializerCache` (added via #4111)
* `TypeFactory` (added via #4115)
* `RootNameLookup` (small -- probably no need to configure)
* `JacksonAnnotationIntrospector` (`_annotationsInside`) -- (tiny, likely no need to configure either)

Some modules may add their own caches as well although not many do; and so configuration of those can be separate from databind.

**Comment by cowtowncoder** [comment]
Marking as "most-wanted" as this tends to come up occasionally, esp. wrt Scala module.

**Comment by pjfanning** [comment]
If there is a rewrite of LRUMap, maybe [ConcurrentLinkedHashMap](https://github.com/ben-manes/concurrentlinkedhashmap/blob/master/src/main/java/com/googlecode/concurrentlinkedhashmap/ConcurrentLinkedHashMap.java) could be copied into jackson-databind. LRUMap is currently based on ConcurrentHashMap but ConcurrentLinkedHashMap allows for an eviction policy that would allow one in, one out semantics once maxEntries is reached.

**Comment by cowtowncoder** [comment]
Merge #3531 which is related but not necessarily 100% what this is so leaving open.

**Comment by cowtowncoder** [comment]
No problem -- thank you for update @JooHyukKim !

I am thinking of soon closing 2.16 branch from new features but we can definitely make sure this gets completed, at least wrt SerializerCache (the main remaining important cache -- I don't think `TypeFactory` matters nearly as much).

**Comment by cowtowncoder** [comment]
@JooHyukKim Let's close this -- I don't think other listed caches are worth worrying about in general. Can tackle if someone finds them problematic.
And I think I already added an entry for this issue in release notes.
Big achievement!
