### ISSUE TITLE
StackOverflowError with ResolvableDeserializer

### ISSUE THREAD

**Issue by facboy** [FasterXML/jackson-databind#2505]
`jackson-databind` version: 2.9.9.3

I suspect this is because i have the following `Deserializer`:

```
class ValueDeserializer extends StdDeserializer<Value> implements ResolvableDeserializer {
    ...

    @Override
    public void resolve(DeserializationContext ctxt) throws JsonMappingException {
        valueDeserializer = ctxt.findContextualValueDeserializer(ctxt.constructType(Value.class), null);
    }
```

and `Value` has

```
@JsonDeserialize(using = ValueDeserializer.class)
public abstract class Value {
...
```

and `DefaultDeserializationContext.deserializerInstance(Annotated ann, Object deserDef)` is not checking for 'incomplete' deserializers at line 235 in the way that `DeserializerCache._createAndCache2(DeserializationContext ctxt, DeserializerFactory factory, JavaType type)` does at line 292.

**Comment by cowtowncoder** [comment]
Yes, this code is categorically wrong. `resolve()` is usually not to be implemented by custom (de)serializers; but if it is, it should neither try to look up deserializer for type it registered itself (guess what will be returned....), nor try to contextualize deserializer.

What are you trying to do here?

**Comment by facboy** [comment]
hum...it's a self-referencing type, in that one of the subtypes of value is List<Value>.  i suppose i could break that subtype out into a separate serializer.

**Comment by cowtowncoder** [comment]
@facboy that could be related, but Jackson should be able to resolve recursive types just fine into `JavaType`. Such types are not uncommon, `Enum` class definitions have that for example.

I think that code above probably needs to be changed to either:

1. Use `createContextual()` instead of `resolve()`, or
2. Use `BeanDeserializerModifier` to get access to "original" deserializer.

If deserializer is NOT registered for type, I am thinking you'd first try (1).

However, it'd make sense to include more of stack trace.

**Comment by cowtowncoder** [comment]
Ok. I guess that is inconclusive, unfortunately, as that does not show the loop.
But use of `findContextualValueDeserializer()` from `resolve()` can easily do that with types that have cyclic references. It really should not be called there: resolve() is designed specifically to handle loops by doing minimal amount of fetching first, and then at a later point calling `createContextual()`.
It may use "non-contextualizing" find methods, and that would avoid loop.
But I am not sure you should use `resolve()` at all.

**Comment by facboy** [comment]
That's the loop there:
```
	at com.byhiras.delta.jsonpatch.ValueDeserializer.resolve(ValueDeserializer.java:42)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.deserializerInstance(DefaultDeserializationContext.java:235)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findDeserializerFromAnnotation(DeserializerCache.java:427)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:326)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:444)
	at com.byhiras.delta.jsonpatch.ValueDeserializer.resolve(ValueDeserializer.java:42)
```

but i have realised belatedly that this is rather silly, as in the places where I need to use `ValueDeserializer` i can just use `this`.  who knows what i was thinking.  staring at code too much.

**Comment by cowtowncoder** [comment]
@facboy :)

Ok good, just glad it works.
