### ISSUE TITLE
Create a Security Policy

### ISSUE THREAD

**Issue by JLLeitschuh** [FasterXML/jackson-databind#2508]
In order to prevent researchers from publicly disclosing vulnerabilities straight onto the issue tracker here, it would probably be a good idea if an official security policy was created for this organization.

You can read more about creating a security policy here:
 - https://help.github.com/en/articles/adding-a-security-policy-to-your-repository
- https://github.com/FasterXML/jackson-databind/security/policy

Protip: If you add the policy to a new GitHub reo called `.github` it will apply this policy to all other projects under this org.

**Comment by cowtowncoder** [comment]
I already added note on security disclosure on https://github.com/FasterXML/jackson but I am sure there are things to improve. Thank you for links, I'll read them when I have time!

**Comment by cowtowncoder** [comment]
Created SECURITY.md as suggested.
