### ISSUE TITLE
Sub-optimal exception message when failing to deserialize non-static inner classes

### ISSUE THREAD

**Issue by mark--** [FasterXML/jackson-databind#2520]
When I try to deserialize an Object which contains an non-static inner class the following error occurs:
<pre>
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException:
Cannot construct instance of `outerclass$innerclass` (although at least one Creator exists):
can only instantiate non-static inner class by using default, no-argument constructor
</pre>

I am using version 2.10.0.

In the last line 'non-static' must be 'static'.

**Comment by cowtowncoder** [comment]
Thank you for reporting this, will fix.

**Comment by cowtowncoder** [comment]
Actually. No, that is not true. This specifically refers to non-static inner classes (static ones can be instantiated using other mechanism).

But I will try to improve wording to make meaning clear, so it's a good report still. :)
