### ISSUE TITLE
Please block two more gadget types(ehcache)

### ISSUE THREAD

**Issue by UltramanGaia** [FasterXML/jackson-databind#2521]
In jackson-databind 2.9.10, you have ban two gadget type ("net.sf.ehcache.transaction.manager.DefaultTransactionManagerLookup" and "net.sf.ehcache.hibernate.EhcacheJtaTransactionManagerLookup"). 
We found another two gadget types to bypass it. (follow up for #2387,#2460)
We have just sent you a mail.

**Comment by cowtowncoder** [comment]
Forgot to check first, so there's #2526.
