### ISSUE TITLE
Ignored property names in BasicBeanDescription not populated propertly

### ISSUE THREAD

**Issue by odrotbohm** [FasterXML/jackson-databind#2531]
If you call `BeanDescription.getIgnoredPropertyNames()` before a call to `….getProperties()`, it returns an empty list. It looks like the list is populated in `BasicBeanDescription._collectIgnorals()` that is triggered by the aforementioned method transitively as well as `getAnyGetter()` etc. However, the actual accessor method does not trigger the calculation which is misleading.

**Comment by cowtowncoder** [comment]
I would need a test case to show the problem, since I'd need to see usage. There are couple of supported ways of getting `BeanDescription` and those should trigger proper calculation; but manual construction (just as an example) would not be supported mechanism.

**Comment by odrotbohm** [comment]
Try this:

```java
@Test
public void testname() {

	ObjectMapper mapper = new ObjectMapper();
	DeserializationConfig config = mapper.getDeserializationConfig();
	ClassIntrospector introspector = config.getClassIntrospector();

	JavaType type = config.getTypeFactory().constructType(Example.class);

	BeanDescription description = introspector.forDeserialization(config, type, config);

	description.findAnySetterAccessor();

	assertThat(description.getIgnoredPropertyNames()).containsExactly("readOnlyProperty");
}

static class Example {
	public @JsonProperty(access = Access.READ_ONLY) String readOnlyProperty;
}
```

If you comment out `description.findAnySetterAccessor()`, the assertion will fail. I.e. you first need to trigger some other method that transitively calls `_collectIgnorals` as `getIgnoredPropertyNames()` doesn't trigger it itself.

**Comment by cowtowncoder** [comment]
Ok, so, while one can technically do it, that is not supported access pattern: all introspection needs to via either context object (SerializerProvider / DeserializationContext), or config (SerializationConfig / DeserializationConfig). By-passing that may or may not work and is not supported. This just as a disclaimer: if modifying above example will still fail with one of those, however, that seems like legit problem.

I just want to verify this first, as the expected usage of `BeanDescription` for the most is actually by receiving one constructed by `jackson-databind` and offered through callbacks in `Serializers` and `Deserializers` (registered using `Module` interface).

**Comment by cowtowncoder** [comment]
I think usage here is not supported: introspection calls need to go via context (`DeserializationContext` / `SerializerProvider`) objects, ideally through `ObjectMapper`.
Closed.
