### ISSUE TITLE
Why have not READ_ENUMS_USING_TO_INDEX? 

### ISSUE THREAD

**Issue by fy-kenny** [FasterXML/jackson-databind#2546]
AT

I have set `WRITE_ENUMS_USING_TO_INDEX = true, `
but I have not found `READ_ENUMS_USING_TO_INDEX` in class `DeserializationFeature`.

* How Can I set a global config to deserialize Enum from ordinal?

I sugguest we need a global config conveniently

**Comment by fy-kenny** [comment]
It cannot deserialize int to enum type from request qeury string, because it treated int as String.

it works when I use request body, it treated as int.

if you have time, I hope you could make framework to support deserialize ordinal to enum type from request query string by set jackson global config automatically.
e.g: READ_ENUMS_FROM_REQUEST_PARAM OR READ_ENUMS_USING_TO_INDEX  OR READ_ENUMS_USING_ORDINAL or  enums.read:[QUERY_STRING, REQUEST_PARAMS, FROM_ORDINAL, FROM_INDEX, FROM_STRING, FROM_NAME, FROM_TO_STRING]
then pass one by one util it success.

if it is supported already, please let me know how so resolve it, thanks a lot.


Thx
kenny

**Comment by cowtowncoder** [comment]
In future, please send (usage) question on mailing list:

https://groups.google.com/forum/#!forum/jackson-user

But as to your question: have you actually tried default operation, of reading from index? That should already work.

**Comment by cowtowncoder** [comment]
Ah, noticed the part of

    It cannot deserialize int to enum type from request qeury string, because it treated int as String.

If so, this can not be made to work: you will need a custom deserializer if you want to coerce from a String that happens to be number into index.
