### ISSUE TITLE
WRITE_DURATIONS_AS_TIMESTAMPS default value overriden in 2.9? 

### ISSUE THREAD

**Issue by dmandalidis** [FasterXML/jackson-databind#2549]
Just faced a strange issue with jackson-2.10.1. I have an object mapper with:

```
.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
```

In 2.9.x all `Duration` fields were serialized to their textual representation (e.g. PT10S) without me explicitly disabling `SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS`. Switching to 2.10, all `Duration` fields have started to be serialized with their numeric representation (e.g. 0.0) which according to javadoc was somehow expected since `WRITE_DURATIONS_AS_TIMESTAMPS` is enabled by default. 

With 2.10, I have to explicitly disable `SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS` to restore the previous behaviour. 

Not a real problem though, but I 'm wondering what has changed between 2.9.x and 2.10.x

**Comment by cowtowncoder** [comment]
`Duration` handling is provided via Java 8 date/time module from:

https://github.com/FasterXML/jackson-modules-java8

and I think what you are seeing is fix for:

https://github.com/FasterXML/jackson-modules-java8/pull/75

This was not mentioned on release notes for some reason so I added a mention there:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10
