### ISSUE TITLE
(3.x) Rewrite Annotation introspection methods for Enum handling

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2550]
The way Enum introspection works via `AnnotationIntrospection` in 2.x is fragmented and results in multiple passes along related but unconnected pieces; first for primary names, then for default values, and then for aliases. Since information is mostly the same it would make sense to change handling to be at slightly higher level, combination logical pieces.

It would either make sense to combine everything into just one combo method, or, possible two:

1. Method that just discovers all accessors (in case of Enums, `Field`s), return as ordered List or array of `AnnotatedField`s
2. Method that given result of (1) will further determine names, aliases, and possible default value

One additional benefit from rewrite is that it could allow supporting mix-in override: in 2.x mix-ins do not work for Enums as far as I understand code (since it by-passes `AnnotatedField` and directly operates on basic JDK `Field` instances instead).

**Comment by JooHyukKim** [comment]
Should we consider this as resolved?

**Comment by cowtowncoder** [comment]
Yeah, I'll close. Thanks!
