### ISSUE TITLE
Check `WRAP_EXCEPTIONS` in `CollectionDeserializer.handleNonArray()`

### ISSUE THREAD

**Issue by stewe** [FasterXML/jackson-databind#2560]
`CollectionDeserializer.handleNonArray` should evaluate `DeserializationFeature.WRAP_EXCEPTIONS` before it wraps the exception into a `JsonMappingException`.

https://github.com/FasterXML/jackson-databind/blob/959b6a1dcea71e641a163b9a0be6bce2ee9dd7c4/src/main/java/com/fasterxml/jackson/databind/deser/std/CollectionDeserializer.java#L346

**Comment by cowtowncoder** [comment]
Sounds reasonable, hope to fix in 2.10 patch.
