### ISSUE TITLE
Deserialization fails when using @JsonTypeIdResolver and @JsonCreator

### ISSUE THREAD

**Issue by sguillope** [FasterXML/jackson-databind#2588]
- Jackson version: 2.10.2
- Reproducible with Java and Kotlin

---

We've encountered a deserialization issue which we were able to isolate in a sample project. This was initially encountered in our Kotlin codebase which uses data classes but we were able to reproduce with a Java sample as well so it's not Kotlin specific.

We have a model class that uses a custom `@JsonTypeIdResolver` to tell Jackson what type to use to deserialize one of the fields based on the value of another field. Here's an example:

Kotlin class:
```kotlin
data class Pet(
    // discriminator field used by AnimalTypeIdResolver
    val type: String,

    @JsonTypeInfo(
        use = Id.NAME,
        include = JsonTypeInfo.As.EXTERNAL_PROPERTY,
        property = "type"
    )
    @JsonTypeIdResolver(AnimalTypeIdResolver::class)
    val animal: Animal
)
```
and its Java equivalent:
```java
public class Pet {
    private final String type;

    @JsonTypeInfo(
            use = JsonTypeInfo.Id.NAME,
            include = JsonTypeInfo.As.EXTERNAL_PROPERTY,
            property = "type"
    )
    @JsonTypeIdResolver(AnimalTypeIdResolver.class)
    private final Animal animal;

    @JsonCreator
    public Pet(@JsonProperty("type") String type,
               @JsonProperty("animal") Animal animal) {
        this.type = type;
        this.animal = animal;
    }
}
```

The deserialization fails if the JSON contains another field not mapped in the model and if it is located before the `type` field
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: 
Missing external type id property 'type'
 at [Source: (BufferedInputStream); line: 6, column: 3] (through reference chain: com.atlassian.Pet["animal"])
```

So deserializing the following JSON fails:
```json
{
  "animal": {
  },
  "ignoredObject": {
    "someField": "someValue"
  },
  "type": "cat"
}
```
while the following JSON works fine:
```json
{
  "type": "cat",
  "animal": {
  },
  "ignoredObject": {
    "someField": "someValue"
  }
}
```

Here are the 2 sample projects with the failing and passing tests:
- Java: https://github.com/sguillope/jackson-external-property-bug
- Kotlin: https://github.com/sguillope/jackson-external-reference-kotlin-bug

When stepping through the code it looks like [`BeanDeserializer#deserializeUsingPropertyBasedWithExternalTypeId`](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java#L1094) stops parsing after encountering and fully parsing the `ignoredObject` field as the loop ends up evaluating an `END_OBJECT` token.

**Comment by cowtowncoder** [comment]
Thank you for reporting this issue, and esp. providing Java-only reproduction -- it is easier to troubleshoot than Kotlin-based one and eliminates possibility of Kotlin module having something to do with the issue.

**Comment by cowtowncoder** [comment]
Ok, I bumped into different problem when using 2.11, and after some investigation I _think_ this is same as #2610 and if so, fixed in 2.10.3.
I was able to make test pass by adding `@JsonIgnoreProperties(ignoreUnknown = true)` on `Pet.java`.

I will close it assuming this is the case, but if not, please re-open.

**Comment by sguillope** [comment]
Thanks @cowtowncoder for the follow-up, that's a good workaround 👍

Although I suppose ideally we shouldn't have to use `@JsonIgnoreProperties(ignoreUnknown = true)` at all, especially if `FAIL_ON_IGNORED_PROPERTIES` is off.

**Comment by cowtowncoder** [comment]
@sguillope If `FAIL_ON_IGNORED_PROPERTIES` is disabled it should also pass, but test didn't have that. If that approach does not work, this issue may be reopened.

**Comment by sguillope** [comment]
Actually my bad, you're right, I should have re-tested before commenting... And also I meant `FAIL_ON_UNKNOWN_PROPERTIES` (not `FAIL_ON_IGNORED_PROPERTIES`) but it all works as expected, thanks heaps 👍
