### ISSUE TITLE
Fix documentation on convertValue()

### ISSUE THREAD

**Issue by Logic-32** [FasterXML/jackson-databind#2590]
#2220 changed `ObjectMapper.convertValue()` to always (de)serialize values instead of trying to intelligently return an object if it doesn't need converted but the documentation still suggest it is trying to be intelligent.  Can the docs be updated to reflect current behavior?

Ref: https://github.com/FasterXML/jackson-databind/blob/0d17325546ca5e17dec5f85ea24132fd03205683/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L2072

**Comment by cowtowncoder** [comment]
Good point, yes.

**Comment by cowtowncoder** [comment]
Updated javadocs for `ObjectMapper` in 2.10.
