### ISSUE TITLE
@JsonProperty required =true is not throwing any exception

### ISSUE THREAD

**Issue by gauravarora90** [FasterXML/jackson-databind#2591]
My response is : 

```
{
"status":"OK",
"message":"Sent Successfully!!"
}

```
and my model class is as follows. However, my response from retrofit API is not throwing any exception for the required fields.

```
public class LoginUserResponse {
    private String otp;

    private String userType;

    @JsonCreator
    public LoginUserResponse(@JsonProperty(value = "otp", required = true) String otp,
                                   @JsonProperty(value = "userType", required = true) String userType) {
        this.otp = otp;
        this.userType = userType;
    }

    public String getOtp() {
        return otp;
    }

    public void setOtp(String otp) {
        this.otp = otp;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }


}
```

**Comment by cowtowncoder** [comment]
That does seem wrong. One thing to do, still, would be to add bit of code to make this a stand-alone test to ensure it is a problem with Jackson handling and not framework -- sometimes what happens it that some frameworks either use specific settings, or do something else that causes issues (f.ex Hibernate's use of code generation has sometimes caused annotations to be missing).
It is even possible that frameworks in some cases swallow exceptions (admittedly rare but has happened).

If you could do that and show resulting code (snippet is fine), as well as include `jackson-databind` version, I'l be happy to look to see why no exception is thrown.

**Comment by cowtowncoder** [comment]
I can not reproduce the issue: test I wrote based on given class, input, will throw expected exception

    Missing required creator property 'otp' (index 0)
