### ISSUE TITLE
StackTraceElement w/ >= Java 9 doesn't deserialize properly

### ISSUE THREAD

**Issue by michaelcdillon** [FasterXML/jackson-databind#2593]
Using `ObjectMapper` to serialize and then deserialize a `StackTraceElement` results in an instance with null values for `classLoaderName`, `moduleName`, and `moduleVersion`. Those elements are present in the serialized form, but then do not make it into the instance supplied by 
`readValue("...", StackTraceElement.class)`.

Versions:
- Java: >= 9, using `11.0.4`
- Jackson-Databind: `2.10.2`

Example Test Case:
    
    @Test
    public void testStackTraceElementIsSerializableAfterJava9() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        StackTraceElement element = new StackTraceElement(
            "testClassloader",
            "testModule",
            "module-version",
            "com.test.DeclaringClass",
            "firstMethod",
            "/some/file",
            35
        );
        String serializedElement = mapper.writeValueAsString(element);
        System.out.println("Serialized Element: " + serializedElement);
        assertEquals(element, mapper.readValue(serializedElement, StackTraceElement.class));
    }
    
Serialize Element Print Statement:
    
    {
	"classLoaderName": "testClassloader",
	"moduleName": "testModule",
	"moduleVersion": "module-version",
	"methodName": "firstMethod",
	"fileName": "/some/file",
	"lineNumber": 35,
	"className": "com.test.DeclaringClass",
	"nativeMethod": false
    }
    
Assertion Failure Output:
    
    Expected: testClassloader/testModule@moduleversion/com.test.DeclaringClass.firstMethod(/some/file:35)
    Actual :com.test.DeclaringClass.firstMethod(/some/file:35)

**Comment by cowtowncoder** [comment]
This can not be supported before adding support for JDK9 or later (in practice JDK11 as that is the first LTS unlike JTK9) -- constructor to pass these properties was added in JDK9 so is not available before.

I think this would need something like `Java11DatatypeModule` (or just` Java11Module`).
I think I will create a new tag for this, in case I (or someone else) has time and needs this feature.

**Comment by michaelcdillon** [comment]
Okay thanks for looking into this, I really appreciate it. Any chance you have a suggestion on a quick and dirty work around?

**Comment by cowtowncoder** [comment]
@michaelcdillon Hmmh. Could perhaps either copy-paste existing `StackTraceElementDeserializer`, or just write and register custom-written one?

**Comment by michaelcdillon** [comment]
Sounds good, thanks. Also thanks for the effort you put in here!

**Comment by cowtowncoder** [comment]
@michaelcdillon no problem!

Also: creating a new module for JDK9 (or JDK11 depending), assuming there might be other types that need support, is not tons of work. Just in case you or anyone else finding this wanted to see where that could lead. Other users could find it useful and we could add it as one of FasterXML modules.

**Comment by cowtowncoder** [comment]
Fixed.
