### ISSUE TITLE
Converter Inheritance

### ISSUE THREAD

**Issue by amirtu** [FasterXML/jackson-databind#2596]
Hi guys,

I think there is a bug emerged in  #288 Converter: Bean to AnotherBean. It fires when you want to use the same converter between parent and derived classes by forcing the expected type of deserialization to the base of converter input type (i.e. the parent class), while it looks like it could perfectly be a derived type.

Here is an example:
```
@JsonDeserialize(converter = ParentEntity.MyConverter.class)
public class ParentEntity {
    String a, b;

    static class MyConverter<T extends Parent> extends StdConverter<T, T> {
        @Override
        public T convert(T entity) {
            entity.a = entity.a.toLowerCase();
            return entity;
        }
    }
}

@JsonIgnoreProperty({"b"})
public class ChildEntity extends ParentEntity {
    public ChildEntity() {
        b = "whatever";
    }
}
```
DeserializerCache::_createDeserializer(...) currently creates deserializer with return type of ParentEntity while in code it is expected to be an instance of ChildEntity. This results in java.lang.IllegalStateException: argument type mismatch exception.

[The commit introduced this behavior](https://github.com/FasterXML/jackson-databind/commit/a4575017d54b7a7d0be5711d9761d1c4eb0aea35), should the check consider hierarchy as well?

(BTW Jackson version used: 2.9.1, Spring 4.3.22)

**Comment by cowtowncoder** [comment]
I think I would need a full test case. Above does not show enough details on actual usage to know if this is supported usage or not.

**Comment by amirtu** [comment]
```
@JsonDeserialize(converter = Teammate.TeammateConverter.class)
public class Teammate {
    private String name;
    private String position;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    static class TeammateConverter<T extends Teammate> extends StdConverter<T, T> {
        private static final String[] search = new String[] {"é", "î", "è"};
        private static final String[] replace = new String[] {"e", "i", "e"};

        @Override
        public T convert(T entity) {
            entity.setName(StringUtils.replaceEach(entity.getName(), search, replace));
            return entity;
        }
    }
}

@JsonIgnoreProperties({ "position" })
public class Teamlead extends Teammate {
    public Teamlead() {
        setPosition("team leader");
    }
}

public class Team {
    private List<Teammate> teammates;
    private Teamlead teamlead;

    public List<Teammate> getTeammates() {
        return teammates;
    }

    public void setTeammates(List<Teammate> teammates) {
        this.teammates = teammates;
    }

    public Teamlead getTeamlead() {
        return teamlead;
    }

    public void setTeamlead(Teamlead teamlead) {
        this.teamlead = teamlead;
    }
}

    @Test
    public void test() throws IOException {
        String json = "" +
                "{\n" +
                "   \"teammates\": [\n" +
                "       { \"name\" : \"Alizée Jacotey\", \"position\": \"front-end\" }\n" +
                "   ],\n" +
                "   \"teamlead\": { \"name\": \"Rustin Cohle\" }\n" +
                "}";
        System.out.println(json);

        ObjectMapper mapper = new ObjectMapper();
        Team team = mapper.readValue(json, Team.class);
    }
```
Output:
```
{
   "teammates": [
       { "name" : "Alizée Jacotey", "position": "front-end" }
   ],
   "teamlead": { "name": "Rustin Cohle" }
}

com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing property 'teamlead' (expected type: [simple type, class Teamlead]; actual type: `Teammate`), problem: argument type mismatch
...
```

**Comment by amirtu** [comment]
I have accidently closed the issue, didn't actually mean to.

**Comment by amirtu** [comment]
I have accidently closed the issue, didn't actually mean to.

**Comment by cowtowncoder** [comment]
Ok. Thank you for providing the test case; I hope to look into this in near future.

One note: use of type parameters in

    static class TeammateConverter<T extends Teammate> extends StdConverter<T, T> {

serves no real purpose, as those variables are not bound to anything; this will be same as

    static class TeammateConverter extends StdConverter<Teammate, Teammate> {

since `T` is just a variable with bounds and nothing binds it to type. This is probably part of the issue.
Not sure if that is the main problem; and if it is, can that be resolved or not, but thought I'll mention it.

**Comment by cowtowncoder** [comment]
Ok. Looking into this, based on test, I think this is unfortunately usage that can not be supported.
Problem is as follows:

* Converter for type `Teammate` (and its subclasses) is of type `StdConverter<T, T>` where `T extends TeamMate` -- but T is unbound type variable, so it can only ever really be `StdConverter<Teammate, Teammate>`
* Jackson uses this converter for both `TeamMate` -- where it should work, binding first to `TeamMate`, then calling converter, then assigning property with setter -- and also, for sub-classes.
     * but for sub-class, converter still gives type `T extends TeamMate` and since it is NOT bound to subtype, it will produce `TeamMate`, then try to assign to `Teamlead`, which fails when introspection tries to call setter.

You can resolve this in couple of ways. One is to override `Converter` either for sub-class (but it must use proper type bounds), something like

    class TeamleadConverter extends TeammateConverter<Teamlead> { }

    @JsonDeserialize(converter = TeamleadConverter.class)
    class Team { ... }

or, you can override converter on property:

    @JsonDeserialize(converter = TeamleadConverter.class)
    private Teamlead teamlead;

Attempts to use generics for converter specification will not work, unfortunately, since Java annotations can only take `Class` values, not generic types.

**Comment by amirtu** [comment]
Thank you very much for detailed explanation. Looks like it is not possible to make this work without any extra code, shouldn't converter be non-inheritable? I also found one more possibility to work-around this behavior by using Curiously recurring template pattern, shown below, but in Java it is not properly achievable.

```
    BaseTeammate<T extends BaseTeammate<T>> {
        public static class Converter extends BaseConverter<T> {} // CT error
        ...
        private static class BaseConverter<T extends BaseTeammate<T>> extends StdConverter<T, T> { ... }
    }
```

**Comment by cowtowncoder** [comment]
It would be great if Jackson could distinguish inheritable and non-inheritable class annotations, and yes, this is one of annotations that probably should be non-inheritable. But unfortunately there is no good way to do that as code that does "flattening" (of class as well as method/field annotation inheritance resolution) has no knowledge of semantics of individual annotations: they are all handled exactly the same way.

Same problem can be problematic for `@JsonSerialize` and `@JsonDeserialize`; and inability to know where annotation came from (within hierarchy) is problematic for `@JsonTypeInfo` as well (during serialization at least, when it is not possible to know "true" base type, something that placement of annotation should tell).

And yes, I was considering whether to suggest that pattern as it would seem like it could actually work in some form... but I assume `static` modifier for nested class prevents use of `T` as reference to surrounding declaration. I think there should be a way to make that approach work, however...

**Comment by cowtowncoder** [comment]
Oh. Except that unfortunately use of `XxxConverter.class` in annotations requires use of concrete type: and not something parameterizable. So it is not possible only by using suitable parameters in base class: it is necessary to repeat it in sub-class. This is limitation of annotation properties and I don't see a way around that one unfortunately.

But if it is ok to use clumsier, 2-phase conversion, you could just ask Jackson to convert to `Map` or `JsonNode` and then in `convert()` method handle conversion to specific Entity type. This would require that sub-class has reference somewhere to exact target `Class`, but that could be type-bound to type variables. So something like

     class BaseConverter extends StdConverter<JsonNode, ParentEntity> {
         public ParentEntity convert(JsonNode input) {
         }
     }

... except, problem here being not having reference to something that can easily use `mapper.convertValue(node, parentSubClass.class). So maybe that's not the way to go.

**Comment by amirtu** [comment]
Noted with thanks your insights on how things are going. It was somewhat confusing when you facing such problems for the first time, when code looks legal (both in terms of type-checking and visual perception). As I now understand, Java is almost unable in metaprogramming, except reflection, so I think there is no correct way to use CRTP to specialize the generic class without any code duplication.

**Comment by amirtu** [comment]
Btw, what do you think about the following:
```
public class BaseTeammate<T extends BaseTeammate<T>> extends StdConverter<T> {
    ...
    @Override
    public T convert(T entity) {
        entity.setName(StringUtils.replaceEach(entity.getName(), search, replace));
        return entity;
    }
}

@JsonDeserialize(converter = Teammate.class)
public class Teammate extends BaseTeammate<Teammate> {
    ...
}
```

**Comment by cowtowncoder** [comment]
@amirtu I think that might work? Sub-class relationship does retain generic typing, so `T` should resolve properly within `convert` method.
