### ISSUE TITLE
com.fasterxml.jackson.core.ObjectCodec#readTree fails on a nested object with DeserializationFeature.FAIL_ON_TRAILING_TOKENS enabled

### ISSUE THREAD

**Issue by dc-up42** [FasterXML/jackson-databind#2597]
Hi.

We have a custom JSON deserializer that uses `jsonParser.codec.readTree()` inside it. It was working fine until we enabled `DeserializationFeature.FAIL_ON_TRAILING_TOKENS`. Now any token which follows the object we are trying to deserialize is erroneously considered a "trailing token".

Please see a simplified example in Kotlin:

```kotlin
package com.example.sandbox.jackson

import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.*
import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.module.kotlin.KotlinModule
import org.junit.jupiter.api.Test

data class Foobar(
        val a: Int,
        val b: InnerFoobarStr
) {
    data class InnerFoobarStr(val strRepr: String)
}

class SubtreeJsonDeser : JsonDeserializer<Foobar.InnerFoobarStr>() {
    override fun deserialize(p: JsonParser, ctxt: DeserializationContext): Foobar.InnerFoobarStr {
        val codec = p.codec as ObjectMapper
        val node = codec.readTree<JsonNode>(p)
        val json = node.toString()
        return Foobar.InnerFoobarStr(json)
    }
}

class TestModule : SimpleModule() {
    init {
        addDeserializer(Foobar.InnerFoobarStr::class.java, SubtreeJsonDeser())
    }
}

class JacksonTrailingTokensTest {
    private fun createObjectMapper(): ObjectMapper {
        return ObjectMapper().apply {
            registerModule(KotlinModule())
            registerModule(TestModule())
            enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS)
        }
    }


    @Test
    fun `deserialization does not fail`() {
        val json = """
            {
                "b": {"c": 666},
                "a": 1
            }
        """.trimIndent()

        val om = createObjectMapper()

        println(om.readValue(json, Foobar::class.java))
    }
}
```

In a sandbox where I compiled the example I used Jackson `2.10.1` .
In an actual project we use `2.9.9` - the symptoms are the same.

**Comment by cowtowncoder** [comment]
Unfortunately this is the way things work with 2.x -- call via `codec` to `readTree()` is root-level call, expecting not to find any trailing tokens and will fail.

But there is an easy fix which should avoid this problem as well as be more efficient and generally better method: use `DeserializationContext.readTree(JsonParser)` method. Method was added in Jackson 2.10; if you can not use that version, `ctxt.readValue(p, JsonNode.class)` would work similarly.

**Comment by dc-up42** [comment]
@cowtowncoder Thank you! Will try this ASAP.

**Comment by cowtowncoder** [comment]
np, good luck!

**Comment by dc-up42** [comment]
As expected, the way recommended in https://github.com/FasterXML/jackson-databind/issues/2597#issuecomment-575768336 works.
