### ISSUE TITLE
No serializer found for class java.io.FileDescriptor

### ISSUE THREAD

**Issue by xbaker** [FasterXML/jackson-databind#2598]
<groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.10.1</version>

**java : AdoptOpenJdk 11**
**Spring boot : 2.1.2.release**

No serializer found for class java.io.FileDescriptor and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: org.springframework.util.LinkedMultiValueMap["media[file]"]->java.util.LinkedList[0]->java.io.FileInputStream["fd"])

**Comment by cowtowncoder** [comment]
I don't think there is a meaningful way to serialize (much less deserialize) this type, so I think this is reasonable exception to throw if an instance serialization is attempted.
But you can work around it in couple of ways:

1. Do what exception message suggests! (disable SerializationFeature.FAIL_ON_EMPTY_BEANS...)
2. Ignore property with this value, if you can modify class declaration in question
3. Add custom serializer that outputs whatever you think makes sense (`null`, empty Object)
4. Use config override mechanism to prevent serialization of any value with this type:

     objectMapper.configOverride(FileDescriptor.class)
        .setIsIgnoredType(true);

of which (4) might be the best way.

**Comment by Eboubaker** [comment]
I had problems with ObjectMapper trying to serialize ApplicationPart (uploaded file). This is how I did it ( I intercept the `_convert` call of ObjectMapper)
```java
import com.coxautodev.graphql.tools.SchemaParserOptions;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import graphql.schema.*;
import graphql.servlet.core.ApolloScalars;
import graphql.servlet.core.DefaultObjectMapperConfigurer;
import org.apache.catalina.core.ApplicationPart;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class GraphQLConfig {
    @Bean
    public GraphQLScalarType uploadScalar() {
        return ApolloScalars.Upload;
    }

    @Bean
    public SchemaParserOptions schemaParserOptions() {
        var defaultObjectMapperConfigurer = new DefaultObjectMapperConfigurer();
        return SchemaParserOptions.newOptions()
            .objectMapperProvider(fieldDefinition -> {
                var mapper = new ObjectMapper() {
                    @Override
                    protected Object _convert(Object fromValue, JavaType toValueType) throws IllegalArgumentException {
                        if (toValueType.getRawClass().equals(ApplicationPart.class)) {
                            return fromValue;
                        }
                        if (toValueType.hasContentType()
                            && toValueType.getContentType().getRawClass().equals(ApplicationPart.class)) {
                            return fromValue;
                        }
                        return super._convert(fromValue, toValueType);
                    }
                };
                defaultObjectMapperConfigurer.configure(mapper);
                return mapper;
            })
            .build();
    }
}

```
This is what I have in the graphql Mutation
```graphql
scalar Upload
type Mutation {
    saveOrder(attachments: [Upload!]!, order: OrderInput!): Order
}
```
In the service:
```java
import com.coxautodev.graphql.tools.GraphQLMutationResolver;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
@Service
public class OrderService implements GraphQLMutationResolver {
    @Transactional
    public Order saveOrder(List<ApplicationPart> attachments, @NotNull Order order) {
        // 
    }
}
```
my build.gradle:
```gradle
dependencies {
    implementation("com.graphql-java-kickstart:graphql-spring-boot-starter:5.10.0")
}
```
