### ISSUE TITLE
PropertyNamingStrategy not working with ParameterNamesModule

### ISSUE THREAD

**Issue by VVinner38** [FasterXML/jackson-databind#2601]
Jackson version: 2.10.1

I'm using the following object mapper with 
```java
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
objectMapper.configure(MapperFeature.AUTO_DETECT_FIELDS, true);
objectMapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
objectMapper.registerModule(new ParameterNamesModule());
```

I wanted to disable `MapperFeature.ALLOW_FINAL_FIELDS_AS_MUTATORS` but it created errors in my tests.

After investigating, it seems that the constructor parameters are not using the PropertyNamingStrategy but being set by reflection and that disabling the previous feature prevents the field from being set.
I would expect the field to be set by the constructor.

Here is an example:
```java
public void testDeserializeFoo() {
        Foo foo = objectMapper.readValue("{\"simple\": 1, \"not_found\": 2, \"shouldNotBeFound\": 3}", Foo.class);
        System.out.println(foo);
}
 public static class Foo {
        private final int simple;
        private final int notFound;
        private final int shouldNotBeFound;

        public Foo(int simple, int notFound, int shouldNotBeFound) {
            System.out.println(simple);
            System.out.println(notFound);
            System.out.println(shouldNotBeFound);
            this.simple = simple;
            this.notFound = notFound;
            this.shouldNotBeFound = shouldNotBeFound;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Foo foo = (Foo) o;
            return simple == foo.simple &&
                    notFound == foo.notFound &&
                    shouldNotBeFound == foo.shouldNotBeFound;
        }

        @Override
        public int hashCode() {
            return Objects.hash(simple, notFound, shouldNotBeFound);
        }

        @Override
        public String toString() {
            return "Foo{" +
                    "simple=" + simple +
                    ", notFound=" + notFound +
                    ", shouldNotBeFound=" + shouldNotBeFound +
                    '}';
        }
    }
```

With MapperFeature.ALLOW_FINAL_FIELDS_AS_MUTATORS not set, it prints
```
1
0
3
Foo{simple=1, notFound=2, shouldNotBeFound=3}
```

With MapperFeature.ALLOW_FINAL_FIELDS_AS_MUTATORS set, it prints 
```
1
0
3
```
then it fails because notFound is missing.

What I'd expect is for it to print:
```
1
2
0
```
and then fail. Without shouldNotBeFound, it should not fail.

**Comment by cowtowncoder** [comment]
Why doesn't `Foo` constructor have `@JsonCreator` on it? If it is missing, I would suggest adding it first -- there are some issues that are specific to way 2.x introspection works (and unfortunately unfixable without full rewrite, to occur in 3.x), where "late" introspection of Creators (inference, not annotations) will lead to missing linkage.

**Comment by VVinner38** [comment]
Hello,
As you said, with the @JsonCreator it is working as expected.
It seems that you were right and that it is an introspection issue, and with the annotation it is working as expected.
Thanks!
