### ISSUE TITLE
Robust deserialization of maps

### ISSUE THREAD

**Issue by apinaut** [FasterXML/jackson-databind#262]
Hi,

    one of our customers is using PHP to connect to our backend. Every
    time he sends empty values for a map with PHP, the JSON content is
    parsed as array (since in PHP, there are only associative arrays
    whereas emtpy ones look identical to usual arrays).

    If one could modify the MapDeserializer class, method  "deserialize"
    to the following:

    [...]
             if ( t != JsonToken.START_OBJECT && t !=
    JsonToken.FIELD_NAME && t != JsonToken.END_OBJECT )
             {
                 // [JACKSON-620] (empty) String may be ok however:
                 if ( t == JsonToken.VALUE_STRING )
                 {
                     return ( Map<Object, Object> )
    this._valueInstantiator.__createFromString( jp.getText( ) );

                 }
                 // empty PHP map looks like an array
                 if ( t == JsonToken.START_ARRAY )
                 {
                     return new HashMap<Object, Object>( );
                 }

                 throw ctxt.mappingException( getMapClass( ) );
             }
    [...]

    This should solve the problem. Maybe it would be nice to make this
    configurable as a feature in the mapper.

**Comment by cowtowncoder** [comment]
Now there is #540, which allows deserializing ' [ ]' as null for POJOs as well as Maps.
Since that might cover this use case, I will close the issue.

If there is still need to instead allow construction of an empty `Map`, please re-open.
