### ISSUE TITLE
Polymorphism of field - Problems

### ISSUE THREAD

**Issue by MasterProgs** [FasterXML/jackson-databind#2622]
Hello,

I need some help to resolve a problem.

The client send to the server this JSON

```
{ 
   "call":"sendMessage",
   "data":{ 
      "type":"ShortcutBarAddRequestMessage",
      "data":{ 
         "barType":1,
         "shortcut":{ 
            "_type":"ShortcutSpell",
            "slot":4,
            "spellId":"0"
         }
      }
```
   

My service deserialize the message by the `_type `of data field (in this case is `ShortcutBarAddRequestMessage`.

The class is

```
public class ShortcutBarAddRequestMessage extends Message
{
	public short barType;
	public Shortcut shortcut;

	public ShortcutBarAddRequestMessage() { }

	public ShortcutBarAddRequestMessage(short barType, Shortcut shortcut)
	{
		this.barType = barType;
		this.shortcut = shortcut;
	}
}
```

The problem -> Shortcut is a parent class, the client precise de `_type` in the shortcut field, During deserialization Jackson try to parse, the field spellId is missing (logical because it check the 
Shortcut class due the the attributs of ShortcutBarAddRequestMessage.

 

```
public class MessageReceiver {
	
	public String call;
	public MessageCall data;
	public String id;

	class MessageCall
	{
		public String type;
		public Object data;
	}
	
	public MessageReceiver()
	{
		
	}
	
	public Message GetMessage() throws ClassNotFoundException, InstantiationException, Exception
	{
 	   Class<?> c =  Class.forName("elk.network.messages." + data.type);
 	   Message msgInstance = (Message) c.newInstance();
 	   
 	   if(data.data != null)
 	   {
	 	   ObjectMapper objectMapper = new ObjectMapper();
	 	   final String json = objectMapper.writeValueAsString(data.data);	 		
	 	   return objectMapper.readValue(json, msgInstance.getClass());
 	   }
 	   
 	   return msgInstance;
	}
}
```

So my question is, How can I precise that the shortcut field of ShortcutBarAddRequestMessage has the `_type `of the shortcut field in the JSON message. (Others Message has this problems)

Regards

**Comment by cowtowncoder** [comment]
Issue tracker is for reporting issues or requesting new features: not as support forum for usage questions. Please consider using

* https://groups.google.com/forum/#!forum/jackson-user (user mailing list)
* https://gitter.im/FasterXML/jackson-databind (online chat)
