### ISSUE TITLE
Upgrade Jackson-databind version to 2.9.10.2 is not working using pom.xml

### ISSUE THREAD

**Issue by rabiihlioui** [FasterXML/jackson-databind#2625]
Hi,
I tried to upgrade my jackson-databind version from 2.9.10.1 to 2.9.10.2 in order to mitigate the gadget vulnerabilities but i cannot download it using maven.
I changed the version in my project's pom.xml but it's not getting downloaded.
Thank you.

**Comment by cowtowncoder** [comment]
Version is available via Maven Central:

https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.9.10.2/

so you will need to figure out why your build system fails to get it.
