### ISSUE TITLE
@JsonTypeInfo visible=true serialises the field twice

### ISSUE THREAD

**Issue by drekbour** [FasterXML/jackson-databind#263]
Spun off from #250.

The below code will add a `name` field twice into the serialised JSON:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "name", visible = true)
public static abstract class Fruit {
    // @JsonIgnore
    public abstract String getName();
}
```

Adding in the `@JsonIgnore` is a workaround but I cannot imagine a circumstance where I would want that behaviour. This ticket is requesting a "visible" property be ignored by default during serialisation.

**Comment by lchavan** [comment]
I am having similar issue, not able to avoid or ignore field 'type' being serialized  twice 

I end up getting response like    { "type":"test", "@type":"test"}

I need to avoid @type completely


@JsonIgnore
@JsonTypeId
private String type;

@JsonTypeInfo(use = Id.NAME, include = As.EXTERNAL_PROPERTY, visible=true,defaultImpl=TestRO.class)
private AbstractConfigRO xmlConfig;	

@JsonIgnore
public String getType() {
		return type;
}
	
@JsonIgnore	
public void setType(String type) {
		this.type = type;
}

**Comment by cowtowncoder** [comment]
Names "type" and "@type" are different from JSON perspective. But you should be able to specify

   @JsonTypeInfo(.... property="type")

to change the default of "@type" into "type".

**Comment by aterreno** [comment]
Is there any way to do not deserialise the type information at all? 

I don't want to emit the 'type' in the json, but I need polymorphism. Any workaround?

Thanks.

**Comment by cowtowncoder** [comment]
@aterreno so how would you figure out intended type?

**Comment by aterreno** [comment]
I am trying to model a json that looks like this: 

`    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }`

(from http://jsonapi.org/ ) 

The type is in the key, not as an attribute (inside relationships), while specifying the type inside the data attribute is totally fine.
