### ISSUE TITLE
Failure to resolve generic type parameters on serialization

### ISSUE THREAD

**Issue by simonedavico** [FasterXML/jackson-databind#2632]
(note: originally reported against Kotlin module, example in Kotlin but failure in databind, transferred)

I have a `Either` definition:

```kotlin
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonSubTypes(
    JsonSubTypes.Type(Either.Left::class, name = "left"),
    JsonSubTypes.Type(Either.Right::class, name = "right")
)
sealed class Either<out A, out B> {
    class Left<A>(val value: A): Either<A, Nothing>()
    class Right<B>(val value: B): Either<Nothing, B>()
}
```

that I use in a simple data class:

```kotlin
data class Foo(
    val bar: Either<String, String>,
    val second: String
)
```

I create an instance and try to serialize:

```kotlin
return Foo(
    bar = Either.Left("aaa"),
    second = "bbbb"
)
```

but jackson throws an `IndexOutOfBoundsException`:

```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
        at java.base/java.util.Collections$EmptyList.get(Collections.java:4481)
        at com.fasterxml.jackson.databind.type.TypeFactory._resolveTypePlaceholders(TypeFactory.java:478)
        at com.fasterxml.jackson.databind.type.TypeFactory._bindingsForSubtype(TypeFactory.java:451)
        at com.fasterxml.jackson.databind.type.TypeFactory.constructSpecializedType(TypeFactory.java:423)
        at com.fasterxml.jackson.databind.cfg.MapperConfig.constructSpecializedType(MapperConfig.java:305)
        at com.fasterxml.jackson.databind.DatabindContext.constructSpecializedType(DatabindContext.java:163)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWriter.java:893)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:705)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
        ... 85 common frames omitted
```

Is it some misconfiguration on my side? I am using jackson `2.10.1`.

**Comment by cowtowncoder** [comment]
Ok so, first things first: changed code to avoid `IndexOutOfBoundsException`: will now indicate that type parameters do not match (specialization is impossible).

Now... while type parameterization is, as far as I can see, wrong, this probably should NOT fail when serializing: after all, object instance exists. Failing on deserialization would seem legit.
Unfortunately type specialization is not specific to ser/deser side (that is, `TypeResolver` does not know), so it is not yet clear if it would be possible to ignore such issues on one operation but not other.

Another possibility, altogether, could also be to consider whether substitution from `String` to `Object`, should be accepted as a special case -- perhaps only for "missing type" case which can be detected. I am not sure I like that idea, but that could perhaps cover a few legit cases and has the benefit that "String" is a type that "raw" `Object` does naturally map to (in theory, then, could map `Long` and `Boolean` too ... but `String` is much more common).

**Comment by cowtowncoder** [comment]
Was able to actually prevent this failure: changed the type specialization in such a way that validation problems are ignored on serialization side. That solves this case and in general should not break existing working cases, although it is possible there are other cases where something different is needed to actually resolve type discrepancy. But we'll cross that bridge when we get there -- no known problems exist.

**Comment by simonedavico** [comment]
@cowtowncoder thank you! I was finally able to try this and I can confirm it works like a charm! The `Either` data class I defined above gets serialised as:

```
value": {
  "@type": "left",
  "value": "${fixtureFamily}"
}
```

which is a nice starting point. Would there be a way for me to configure the annotations in such a way that it serialises to the plain `value? For example, for the above I would like to get: 

```
"value": "${fixtureFamily}"
```

**Comment by cowtowncoder** [comment]
If you do not want to include Type Id, then just do not use `@JsonTypeInfo`; there is no point in working around that if you have actual logic in (de)serializer, and use of 2 separate physical type is more of an implementation detail than type hierarchy to support.
