### ISSUE TITLE
Add descriptive exception for attempts to use `@JsonWrapped` via Creator parameter

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#265]
`@JsonUnwrapped` does not currently work with creator parameters; both because name linkage is needed (despite not being used), but also because unwrapped-handler absolutely requires existence of POJO to assign reconstructed value to -- which can not be done without Creator having access. So basic chicken-and-egg problem.

While this is theoretically (and hopefully ultimately) solvable problem, at this point (jackson 2.9 development) it is better to add clear exception to indicate the issue, instead of producing a confusing and misleading exception like currently happens.

**Comment by LukaszWiktor** [comment]
+1

**Comment by weaselmetal** [comment]
+1 ... I think it should be possible to remove any suffix/prefix that was added when unwrapping and call a JsonCreator with the remaining / cleaned field names. No?

**Comment by cowtowncoder** [comment]
@weaselmetal You are welcome to check how easy that would be to do. Unfortunately I won't have time to work on this  issue any time soon.

**Comment by cowtowncoder** [comment]
Quick note: the problem is NOT with creator + unwrapped combination not working, but rather that somehow `@JsonUnwrapped` is not merged properly. If `@JsonUnwrapped` is added to a field or any other linked accessor other than creator property, things seem to  work.
So: a work-around is to do just that if possible.

Working version:

```java
   static class JPerson {
        @JsonUnwrapped
        protected JAddress address;
         
        @JsonCreator
        public JPerson(@JsonProperty("name") String name,
           @JsonUnwrapped JAddress address) {
               // ...
        }
```

whereas this fails:

```java
   static class JPerson {
        protected JAddress address;
         
        @JsonCreator
        public JPerson(@JsonProperty("name") String name,
        @JsonUnwrapped JAddress address) {
               // ...
        }
```

I'll try to resolve the problem itself, but work-around may be useful esp. for older Jackson versions that will not get fix (only 2.7 and later open; most likely fix in 2.9 only or 2.9 and 2.8).

**Comment by cowtowncoder** [comment]
Ok. After first falsely concluding that this could work, I am realizing that the way unwrapped properties are implemented, they will NOT be supportable as constructor-backed creator properties without major rewrite.

So. What I will do for 2.9 is to add checks so that attempts to do this should fail earlier with more descriptive error message. I will also remove code that tries to handle the case since it can not work as designed: Creator expects fully resolved unwrapped values, but unwrapped-value resolved can only run after Creator has created the POJO to assign values to.

But I will create a new issue for potentially doing said major rewrite to add support, since it is theoretically doable. Just not with small/medium incremental changes.

**Comment by cowtowncoder** [comment]
For 2.19, support is actually being added -- after all these years! See #1467 for details.
