### ISSUE TITLE
Change DEFAULT_TIMEZONE from 'UTC' to 'TimeZone.getDefault()' in BaseSettings.java:28

### ISSUE THREAD

**Issue by DiamonCheng** [FasterXML/jackson-databind#2652]
Run code below.  

```
public class Main {
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date date;
    
    public Date getDate() {
        return date;
    }
    
    public Main setDate(Date date) {
        this.date = date;
        return this;
    }
    
    public static void main(String[] args) throws JsonProcessingException {
        Date d=new Date(1583955961139L);
        System.out.println(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(d));
        System.out.println(new ObjectMapper().writeValueAsString(new Main().setDate(d)));
    }
}
```

Result:
2020-03-12 03:46:01
{"date":"2020-03-11 19:46:01"}

My default timezone Asia/Shanghai

**Comment by cowtowncoder** [comment]
I am not sure I understand exact request: if you want some other timezone to be used than UTC, you will need to configure your `ObjectMapper` (or `ObjectWriter`) to use it.
Or, use `@JsonFormat.timezone` for property.

One thing that will not be changed is to use "local timezone" as the default, however: UTC is chosen intentionally to remove one common source of problems, where systems use arbitrary default timezone setting. Users can still set that, if they think that is useful, but it should not be the default.
