### ISSUE TITLE
Add new factory method for creating custom `EnumValues` to pass to `EnumDeserializer`

### ISSUE THREAD

**Issue by whut** [FasterXML/jackson-databind#2663]
The `com.fasterxml.jackson.databind.util.EnumValues` constructor is now private, which means that it is
not possible to create `EnumSerializer` instance with custom `EnumValues`. It should be at least protected, like is the case of `com.fasterxml.jackson.databind.util.EnumResolver` used by `EnumDeserializer`.

I try to implement different strategy for serialization and deserialization of enums, simply to convert java SNAKE_CASE to more common in JSON camelCase and vice-versa. It is quite easy with `EnumDeserializer`, but in case of `EnumSerializer` it is not. I would like to just create new instance of `EnumSerializer` with `EnumValues` instance build using different logic. Currently the only way (without reflection which I will use for the time being) is to cal the `EnumValues#construct*` methods, which have hard-coded enum-to-string mapping logic.

BTW. Consider adding casing strategy for enum serialization/deserialization as build-in jackson feature. For example in JSON.NET it is just a matter of passing approprate [NamingStrategy](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_NamingStrategy.htm) to [StringEnumConverter](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Converters_StringEnumConverter__ctor_1.htm) constructor.

**Comment by cowtowncoder** [comment]
If a constructor is `private`, there tends to be specific reason for that, and a factory method to call it. So I do not think changing that access method is usually the right way to go -- it just opens up a fragile, unsupported extension point; something that will likely break when databind needs to pass some more information. Not sure why constructor for deserializer is left non-private; perhaps an oversight.
Granted, use of reflection is even worse, and even more likely to break with new versions (private methods not being considered part of API and changeable on any minor version).

But adding an alternative factory method could be a slightly better choice. Perhaps one that would take `PropertyNamingStrategy` (along your suggestion).
While it is designed for property name handling, it could probably be used for `Enum`s as values as defined as... `Method`s I think? (or possibly `Field`s, would need to check).

I am open to other ideas, PRs.

**Comment by GedMarc** [comment]
I think I came across something similar, maybe just to spark some ideas - 

You don't construct enums ever but rather check class and pull the values from the class store? 
e.g. not enum.values()
```
	if (IdType.class.isEnum())
		{
			Class<?> workFromClass = IdType.class;
			for (Object enumConstant : workFromClass.getEnumConstants())
			{
				String valueSearch = enumConstant.toString();
				//find the json creator and return
			}
		}
```
if i'm wrong here I would love to learn more about this! the referencing from the class object of constants is the correct reference?

**Comment by cowtowncoder** [comment]
One quick that I can easily add, and have no problems with is to just add matching factory method in 2.11. I'd prefer keeping constructor private in this case for now, since class is already `final` ((package) protected would be needed for sub-classing).

**Comment by cowtowncoder** [comment]
Added 2 `construct` methods that will allow constructing specific instance necessary.

I think idea of supporting naming strategies in some form is good, and so although there are some open questions, will create a follow-up issue for that.
