### ISSUE TITLE
Allow configuring "get" and "set" prefixes.

### ISSUE THREAD

**Issue by feinstein** [FasterXML/jackson-databind#2674]
This is a feature request for being allowed to use getters and setters that don't use the traditional Java Bean notation, with `get` and `set` prefixes, this way a getter with just the name of the variable would be used, this is helpful for people using AutoValue, such as in here #2344.

**Comment by cowtowncoder** [comment]
Looks like there was already an issue #1325; but will close that, leave this open, for better visibility (newer issue sorted first).

**Comment by feinstein** [comment]
Can't this be a little bit automatic? For example, in the case of #2344, upon detecting there's a getter with the name of a JSON key and a Builder with a setter, Jackson could automatically detect this should be used.

**Comment by cowtowncoder** [comment]
Unfortunately builder and target class definitions are not directly linked in any way, so this information is not available.

**Comment by feinstein** [comment]
Thought this info could come from `@JsonPOJOBuilder` + the output of a `build` or `create` method. So Jackson would know that's a builder and that it builds.

**Comment by cowtowncoder** [comment]
Jackson knows details of Builder and Result classes, but they are handled separately (deserializer discovered for Builder first, as slight modification of "regular" POJOs; and then deserializer is eventually fetched for result type of build-method: that one has zero-knowledge of anything preceding it. Both are introspected separately.
So there is no real information transfer or sharing between the two, unfortunately.

**Comment by feinstein** [comment]
Got it.

**Comment by cowtowncoder** [comment]
And just to be clear: I am not saying it is a bad point, or that it wouldn't be good if the two could collaborate -- it would make sense. But due to historical reasons (the way builder-style was implemented as reusing "default one"), this is not how things work at this point.
Improvements would be welcome; it just may be tricky thing to change wrt backwards compatibility.

**Comment by feinstein** [comment]
Makes sense.

**Comment by cowtowncoder** [comment]
This will actually be possible globally, with #2800, using `DefaultAccessorNamingStrategy` configured to use different prefix.

**Comment by cowtowncoder** [comment]
Will close, assuming #2800 is sufficient -- if not sufficient, may be refiled explaining why this is not sufficient or suitable solution (and ideally suggesting alternative way to configure).

**Comment by feinstein** [comment]
Are there any samples on how to use it?

**Comment by cowtowncoder** [comment]
Mostly just tests (see `grep AccessorNamingStrategy src/test/**/*.java`):

     src/test/java/com/fasterxml/jackson/databind/introspect/AccessorNamingStrategyTest.java

although when 2.12 is released I hope to write bit more about various features.

**Comment by feinstein** [comment]
Perfect, thanks.
