### ISSUE TITLE
Request guidance on an error within the Spring Boot Framework

### ISSUE THREAD

**Issue by VahidGarousi** [FasterXML/jackson-databind#2676]
Hi I'm implementing an REST API using this framework. The language I use is Kotlin. After creating the relationships between the tables, Using a tool called Postman I send a Json to the server and related endpoint with the following structure: Category Json
Full document in stackoverflow :
https://stackoverflow.com/questions/60980694/request-guidance-on-an-error-within-the-spring-boot-framework

`{
    "title" :"Sport"
}`
After receiving it, I will encounter the following error. The error message is as follows:

`{
    "timestamp": "2020-04-01T21:28:22.631+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "JSON parse error: No Object Id found for an instance of `ir.vahidgarousi.app.farzin.modules.posts.models.Category`, to assign to property 'id'; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: No Object Id found for an instance of `ir.vahidgarousi.app.farzin.modules.posts.models.Category`, to assign to property 'id'\n at [Source: (PushbackInputStream); line: 3, column: 1] (through reference chain: ir.vahidgarousi.app.farzin.modules.posts.models.Category[\"id\"])",
    "path": "/category/"
}`
more information:

Category Entity:

`@Entity
@Table(name = "categories_tbl")
@JsonIdentityInfo(
  generator = ObjectIdGenerators.PropertyGenerator::class,
  property = "id")
data class Category(
  @Id @GeneratedValue(strategy = GenerationType.IDENTITY) var id: Long? = null,
  @ManyToMany(mappedBy = "categories")
  var posts: List<Post> = mutableListOf(),
  var title: String,
  @Column(name = "created_at")
  var createdAt: LocalDateTime = LocalDateTime.now(),
  @Column(name = "updated_at")
  var updatedAt: LocalDateTime = LocalDateTime.now()
)`
Post Entity:

```
@Entity
@Table(name = "posts_table")
@JsonIdentityInfo(
  generator = ObjectIdGenerators.PropertyGenerator::class,
  property = "id")
data class Post(
  @Id @GeneratedValue(strategy = GenerationType.IDENTITY) var id: Long? = null,
  @ManyToOne
  @JsonManagedReference
  var user: User,
  @ManyToMany
  @JoinTable(name = "post_catefories")
  var categories: List<Category> = mutableListOf(),
  var title: String,
  var body: String,
  var cover: String,
  @Column(name = "created_at")
  var createdAt: LocalDateTime = LocalDateTime.now(),
  @Column(name = "updated_at")
  var updatedAt: LocalDateTime = LocalDateTime.now()
)
```

CategoryController :

```
@RestController
@RequestMapping("/category")
class CategoryController @Autowired constructor(private val categoryService : CategoryService) {

  @RequestMapping(*["/", ""], method = [RequestMethod.GET])
  fun getCategories(): List<Category> {
    return categoryService.getAll()
  }

  @RequestMapping(*["/", ""], method = [RequestMethod.POST])
  fun addCategory(@RequestBody category: Category): Category {
    return categoryService.addCategory(category)
  }
}
```

CategoryService:

```
@Service
class CategoryService @Autowired constructor(val categoryRepository: CategoryRepository) {
  fun getAll(): List<Category> {
    return categoryRepository.findAll()
  }
  fun addCategory(category : Category) : Category {
    return  categoryRepository.save(category)
  }
}
```

Category Repository:

```
@Repository
interface CategoryRepository: JpaRepository<Category, Long> {
}
```

application.properties

```
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3308/*
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
```

**Comment by cowtowncoder** [comment]
I would need a Jackson-only reproduction of the issue: otherwise the issue may be due to REST framework, or ORM framework needed.
