### ISSUE TITLE
Explicitly fail (de)serialization of `java.time.*` types in absence of registered custom (de)serializers

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2683]
(inspired by #2626)

So, a relatively common problem by users seem to be the case of using Java 8 date/time types, without registered Java 8 date/time module. For serialization this can even produce seemingly legit JSON output as values are considered just POJOs/Beans, which is problematic as JSON representation will NOT be what module would support, nor something that can be deserialized.

While general case of knowing that something is missing wrt support is unsolvable, the specific case of `java.time` type support may be something we could perhaps detect.
My first idea is that when looking for (de)serializer, if no (de)serializer found via module registrations, trying to find one for `java.time.*` classes should give specific failure suggesting that module is needed, and NOT try to create Bean[De]Serializer.

Due to timing concerns (2.11.0.rc1 being tested, official 2.11.0 due soon) this will probably need to go in 2.12.0.

**Comment by cowtowncoder** [comment]
Implementing; appears to work, does not conflict with Java 8 date/time module when registered.

About the only open question is this: initial implementation will throw deferred exception -- that is, only when actual attempt is made to read/write values. But should it be eager failure instead, at least for deserialization? (serialization might be trickier).

**Comment by rajpra8** [comment]
If java 8 going to be minimum supported version at some point, can JavaTimeModule gets registered by default?

**Comment by cowtowncoder** [comment]
Java 8 will be default for 2.13 (and was always at least Java 8 for Jackson 3.0).

However, I am still not 100% sure about direct inclusion due to sheer size of Java 8 date/time module.
Jackson 3.0 does embed other java 8 types (optionals) and parameter name introspection; 2.13 will likely include these too.

**Comment by joschi** [comment]
@cowtowncoder It would be great if we could add this to the release notes of Jackson 2.12.0:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12

And judging by the number of linked GitHub issues/PRs, people seem to be a bit surprised by the fact that previously "working" serialization of `java.time.*` doesn't work anymore in Jackson 2.12.0. 😂
