### ISSUE TITLE
Jackson-databind new gadget.

### ISSUE THREAD

**Issue by thiscodecc** [FasterXML/jackson-databind#2687]
about Vulnerability details, please watch info@fasterxml.com, Email sent: April 10, 2020

**Comment by cowtowncoder** [comment]
I have not received anything via that email address. Could you re-send?

**Comment by thiscodecc** [comment]
I just sent an email, please watch info@fasterxml.com

**Comment by cowtowncoder** [comment]
Got it -- will create separate issue as placeholder, with standard description.

**Comment by cowtowncoder** [comment]
Created #2688.
