### ISSUE TITLE
Caching result of BeanSerializerModifier

### ISSUE THREAD

**Issue by ptahchiev** [FasterXML/jackson-databind#2699]
Here's my situation - I'd like to provide way for users to configure the JSON response from the server dynamically at runtime. So I have created a configuration in the database that holds certain fields and if the user adds a projection parameter to the url (for example http://localhost/rest/product/123?projection=small) then I load the `small` configuration from the DB and return only the product fields that are associated with the configuration. I have achieved this using a custom `BeanSerializerModifier` and this works perfectly fine.

However, it seems that once Jackson uses my `BeanSerializerModifier` the result gets cached, so even if I change the configuration in the database, and change the fields of the product associated with this projection, the result is still the same, unless I restart the server. 

Is there a way to programmatically  clean the cache of the `BeanSerializerModifier`?
Thank you

**Comment by cowtowncoder** [comment]
Design is such that you are only ever guaranteed for `BeanSerializerModifier` to be applied once (like you observed): results themselves are used to construct `BeanSerializer` (or more generally just `JsonSerializer` from last call), and those are cached for performance reasons.
It is possible that caching does not occur in some edge cases, or that cache is filled and some instances fall out, but neither of these can be guaranteed.
So typically if you would want more dynamic handling, you would create your own serializer and make changes on per-call basis. This may or may not be easy, but is the common route.

However, if performance is not of concern, you can just construct new `ObjectMapper` as (de)serializer caches are on per-mapper basis. There is `ObjectMapper.copy()` method, too, if you want to retain configuration settings.
