### ISSUE TITLE
Wring version in 2.11 release notes

### ISSUE THREAD

**Issue by ignasi35** [FasterXML/jackson-databind#2702]
(Reporting this nitpick here since FasterXML/jackson doesn't have GitHub's `issues` enabled)

[The Wiki page with the release notes for 2.11](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.11) states the version is 2.10:

```
Jackson Release 2.11

Version 2.10 was released on April 26, 2020.
----------^^
```

Cheers,

**Comment by cowtowncoder** [comment]
Thank you-- yes, confusing typo there. Fixed!
