### ISSUE TITLE
for json deserializer , how can i get the field genericSuperclass type ?

### ISSUE THREAD

**Issue by majinding** [FasterXML/jackson-databind#2711]
for example 

```java
@Getter
@Setter
public class MyExpression<T> {

    private T t;
    private String expr;

}
```
```java
@Getter
@Setter
public class MyReward implements Serializable {

    private static final long serialVersionUID = 2670751308594930008L;
    private int id;
    private String name;
    private MyExpression<Boolean> expr;

}
```

When I use Jackson for deserialization, how to get the type of T, such as Boolean ?

**Comment by cowtowncoder** [comment]
Where would you want to know it?

**Comment by majinding** [comment]
```java
@Getter
@Setter
public class MyReward1 implements Serializable {
    private MyExpression<Boolean> expr;
}
```
```java
@Getter
@Setter
public class MyReward2 implements Serializable {
    private MyExpression<Long> expr;
}
```
```java
@Getter
@Setter
public class MyReward3 implements Serializable {
    private MyExpression<String> expr;
}
```
```java
@Getter
@Setter
public class MyReward4 implements Serializable {
    private MyExpression<ObjectXxx> expr;
}
```

```java
@Slf4j
public class MyExpressionDeserializer extends JsonDeserializer<MyExpression> {

    @Override
    public MyExpression deserialize(JsonParser jp, DeserializationContext context) throws IOException {
        try {
            String expr = jp.getText().trim();
                        
            // I want to get declare MyExpression genericSuperclass 
            // example : I want to get MyReward below MyExpression<Boolean> generic type ， Boolean , Long , String , ObjectXxx ?

            MyExpression myExpression = new MyExpression();            
            myExpression.setExpr(expr);
            return myExpression;
        } catch (Exception e) {
            throw new IOException(e);
        }
    }
}
```

I need get (MyExpression<Boolean> expr ) <Boolean> type
if (T instanceof  Boolean) do...
if (T instanceof  Long ) do...

**Comment by cowtowncoder** [comment]
This is not possible in `deserialize()`; but you may be able to store and use that information when deserialized is registered. This requires you to write some more code for registration since call where fully resolved type is passed is in `Deserializers` implementation:

```
    public JsonDeserializer<?> findBeanDeserializer(JavaType type,
            DeserializationConfig config, BeanDescription beanDesc)
        throws JsonMappingException;
```

specifically `type` would contain this information, you would get first type parameter from:

```
JavaType firstTypeParameter = type.containedTypeOrUnknown(0);
```

Note that use of `SimpleModule` (or `SimpleDeserializers` it uses) will probably not work (or at least you need to override things).

**Comment by majinding** [comment]
Thanks 
About deserialize () I have tried it for a while ,  now I will give up this way

Is it possible to use annotations to achieve 

like this [https://www.cnblogs.com/rollenholt/p/5406573.html](https://www.cnblogs.com/rollenholt/p/5406573.html)
but it's Serializer , I will use it for Deserializer ? can I use this way ?

```java
@Getter
@Setter
public class MyReward1 implements Serializable {
    @Expression(boolean)
    private MyExpression<Boolean> expr;
}

@Getter
@Setter
public class MyReward2 implements Serializable {
    @Expression(Long)
    private MyExpression<Long> expr;
}
```
but how can I to use It ? config where ?

I can't find the information online, I need your help, thank you

**Comment by cowtowncoder** [comment]
You could make it work with annotations too I suppose; your serializer would need to implement `ContextualSerializer`, implement `createContextual(...)` method, and access annotation from `BeanProperty` parameter given.
`BeanProperty` has method `getAnnotation()` which would see annotation(s) added to accessor (field, getter, setter).

Similarly it works for deserializers as well, need to implement `ContextualDeserializer`. Same `BeanProperty` available there as well.

I hope this helps!

**Comment by majinding** [comment]
Thanks for your help .
according you suggestions, I have successfully obtained the type of `T` , thanks again.

```java
@Slf4j
public class MyExpressionDeserializer extends JsonDeserializer<MyExpression>
        implements ContextualDeserializer {

    private Class clz;

    @Override
    public MyExpression deserialize(JsonParser jp, DeserializationContext context) throws IOException {
        String expr = "deserialize---" + clz + " " + jp.getText().trim();
        System.out.println(expr);

        return new MyExpression<>(clz, expr);
    }

    @Override
    public JsonDeserializer<?> createContextual(DeserializationContext ctxt, BeanProperty property) {
        Class<?> rawClass = property.getType().containedTypeOrUnknown(0).getRawClass();
        System.out.println(rawClass);

        return new MyExpressionDeserializer(rawClass);
    }


    public MyExpressionDeserializer() {
    }

    public MyExpressionDeserializer(Class clz) {
        this.clz = clz;
    }
}
```

**Comment by cowtowncoder** [comment]
@majinding Excellent! I am glad you were able to resolve the problem -- this is not easy to figure out.
