### ISSUE TITLE
FasterXML performance regression when dealing with list

### ISSUE THREAD

**Issue by giovannicuccu** [FasterXML/jackson-databind#2716]
Hi, I found a performance issue when serializing/deserializing lists. The issue is fully explained [here ](https://stackoverflow.com/questions/61573944/fasterxml-performance-regression-when-dealing-with-list).
In addition to the StackOverflow info I can add the following informations:

1. The problem seems to be present even in 2.10.4 and 2.9.10
2. I ran the benchmark  with java -Xmx256m -server -Xrunhprof:cpu=samples,depth=10,verbose=n,interval=2 using java 8 (oracle jdk 8 v 251), the output is attached.
[java.hprof.txt](https://github.com/FasterXML/jackson-databind/files/4605276/java.hprof.txt)

Hope it helps in finding the problem cause.
Giovanni

**Comment by cowtowncoder** [comment]
Ok thank you for reporting this, adding all the information requested.
Since it is in 2.9.10 and 2.10.4 (as well as I assume 2.11.0) it is unlikely to be a recent regression

**Comment by cowtowncoder** [comment]
Nothing obvious jumps out of profile, although this could be due to profiling being done over the whole test (or all tests), read/write and so on. So if I have time I'll probably try to focus testing on specific section.

**Comment by giovannicuccu** [comment]
Hi, just tried with 2.13.0 and the results are the same.

**Comment by cowtowncoder** [comment]
At this point I think I'd need to see the full reproduction, not just as link to SO. So test methods from jmh project.
My main concern is that example linked to seemed to have incorrect typing, for example, reading generic `List<?>`.
It would also be necessary to know if `ObjectMapper` instance is reused etc.

**Comment by giovannicuccu** [comment]
Hi, there is a github project with all the code: https://github.com/giovannicuccu/fasterxmllistperfomance. the class with the test is FasterXMLPerformance.java and the test showing the problem is fasterXMLStandard

**Comment by cowtowncoder** [comment]
Ok. Some further notes:

First: profiler output is not very useful for a couple of reasons:

1. It includes both serialization and deserialization (should remove first one by pre-serializing content first, outside tests)
2. There is a lot of noise from helper code (`EasyRandom`) used for set up: this should be refactored out of test too

But there is also an actual bug, I think. This:

```
        List<Persona> personeDeser=jsonMapper.readValue(personeAsStr,List.class);
```

does not do what you think it does. It is actually same as:

```
        List<Object> personeDeser=jsonMapper.readValue(personeAsStr,List.class);
```

because type `List.class` does not (and cannot, as per type erasure) have parameterization for contents.
So it does very different thing from:

```
        List<Persona> personeDeser=jsonMapper.readValue(personeAsStr, new TypeReference<List<Persona>>() { });
```

Aside from that, how do you run benchmark itself? `java` snippet above (`java -Xmx256m -server -Xrunhprof:cpu=samples,depth=10,verbose=n,interval=2 `) is missing the actual main class to invoke.
I'll see if I can figure it out.

**Comment by cowtowncoder** [comment]
I am not sure how this package is to be built: basic `mvn install` / `mvn package` does not create full uber jar, but just regular classes. But there seem to be settings in `pom.xml` for assembly to package pieces, indicate Main class.
I am just not sure what the invocation is expected to be.

**Comment by giovannicuccu** [comment]
Hi, I followed your advice and I taken out the EsayRandom part from the execution phase. The performance regression is no longer here. The changes are in the branch feature/performance_regression. After all it seems an EasyRandom issue, if you agree you can close the issue. Sorry for the confusion.
P.S. when executing single benchmark I run the main from my IDE.

**Comment by cowtowncoder** [comment]
@giovannicuccu lol. Ok, better this way! Just wish I had suggested that earlier. Thank you for confirming the issue.

**Comment by stevenschlansker** [comment]
Sounds like this issue should be closed, but maybe forgot to do that.
