### ISSUE TITLE
Is it possible to apply '@JsonSetter(contentNulls = Nulls.SKIP)' by default?

### ISSUE THREAD

**Issue by remal** [FasterXML/jackson-databind#2734]
Hello,

Is it possible to apply `@JsonSetter(contentNulls = Nulls.SKIP)` for all deserialized types by default.

I'm interested not only in bean objects deserialization, but also in collections deserialization. For example `objectMapper.readValue("[1,null,2]", new TypeReference<List<Integer>>(){})`.

**Comment by cowtowncoder** [comment]
In future, please use mailing list (https://groups.google.com/forum/#!forum/jackson-user) or chat (https://gitter.im/FasterXML/jackson-databind) for questions.

So... yes and no. Yes, `ObjectMapper` can be built with such global setting

```java
     ObjectMapper mapper = JsonMapper.builder()
          .defaultSetterInfo(...)
          .build();
```

(and there is also legacy setter, `ObjectMapper.setDefaultSetterInfo()` for old style configuration).

 but no, `null`s will NOT be skipped in Collections or arrays: `null` handling only affects property values. Filtering out of Collections and arrays is quite different operation as they are positional so it would need to be implemented as a separate feature.
As things are I would probably implement custom `ArrayList` subtype of which `add` method will skip `null`s.
