### ISSUE TITLE
JsonFactory API problem

### ISSUE THREAD

**Issue by liping-java-happy** [FasterXML/jackson-databind#2738]
```
JsonGenerator jsonGenerator = JsonObjectMapper.getFactory().createGenerator(os);
```

when the parameter type of the "os" is  DataOutputStream will can not complie and report error like this "The method createGenerator(OutputStream) is ambiguous for the type JsonFactory".
because "DataOutputStream" extend "FilterOutputStream" and implements "DataOutput" ,so i'm not
 sure is this a bug.
version:jackson-databind 2.9.10.3

**Comment by cowtowncoder** [comment]
In that case you will have to use cast to decide which method to call: I suspect you would want to use

```
JsonGenerator jsonGenerator = JsonObjectMapper.getFactory().createGenerator((OutputStream) os);
```

although casting as `DataOutput` should work as well (but is probably slightly less efficient).

I don't think this is a bug as this is how Java type system works: if you have a class that implements two types, compiler does not want which method you want and you will have to tell it.
