### ISSUE TITLE
First class support for Enums in deserializing polymorphic types

### ISSUE THREAD

**Issue by lpandzic** [FasterXML/jackson-databind#2739]
Currently when serializing an enum we get first class support with out of the box use of Enum.toString.
Unfortunately this is not the case in opposite direction when using polymorphic types:

```java
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "type",
        visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = Foo.class, name = "FOO"),
})
public interface FooBar {
...
}
```

At best we can use an indirection which prevents us from using the aforementioned Enum.toString feature:

```java
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "type",
        visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = Foo.class, name = FooBarType.Constants.FOO),
})
public interface FooBar {
...
}
```
```java
@AllArgsConstructor
public enum FooBarType {

	FOO(Constants.FOO);

	@JsonValue
	@Getter
	private final String value;

	public static class Constants {
		static final String FOO = "FOO";
	}
}
```

What I propose is that new field be added to JsonSubTypes.Type that would hold enum value so we can have:

```java
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "type",
        visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = Foo.class, enumName = FooBarType.FOO),
})
public interface FooBar {
...
}
```
```java
public enum FooBarType {
	FOO;
}
```

This would significantly reduce code ceremony and would prevent lazy user from doing the wrong thing - typing less at the cost of duplicate type json value and possible bugs that come after that.

**Comment by cowtowncoder** [comment]
One quick note: if I remember correctly, one unfortunate limitation of Java annotations is that while you can use value type of specific `enum` (like `FoobarType`) for annotation properties, you can not (to my knowledge) specify anything like "any enum". 
So I am not sure there is a way to express value type for `enumName` within `JsonSubtypes.Type`.

**Comment by lpandzic** [comment]
You are correct, I should've researched the topic a little bit more before opening the issue. :)

**Comment by cowtowncoder** [comment]
No problem. I can see why the idea would be useful. And I just happened to have tried similar usage before so remembered this unfortunate limitation. :-/
