### ISSUE TITLE
Adding extra properties with MixIn

### ISSUE THREAD

**Issue by cemo** [FasterXML/jackson-databind#274]
This is a request for an enhancement for Jackson MixIn's. Currently one of the suggested usage of MixIn is using as a subclass. 

> hint: since method implementations are ignored, it often makes sense to define mix-ins as interfaces or abstract classes
> hint: if you can, it often makes sense to define mix-in class as a sub-class of target class, and use `@Override` JDK annotation to ensure method name and signature match

This is really pretty neat since It allows user abstraction of JSON without polluting actual domain classes. And also as stated in the MixIn documentation page Type Safety is a big win by `@Override`.

But currently adding a new property to JSON Output by Jackson is pretty difficult and MixIn does help in this situation. It does not support add new properties dynamically. Allowing new properties dynamically would be awesome.

Consider this case: 

``` java
public class Person {
   public String name;
   public String surname;
}
```

And in my JSON output I need to frequently need `name + surname` or `class`. 

In order to provide this I need to change my person entity to this: 

``` java
public class Person {
   public String name;
   public String surname;

   public String getNameAndSurname(){
      return name + " " + surname;
   }
}
```

This is not what I wanted because in my business side I do not want any JSON related annotations or implementation in my domain modal. Instead I would prefer this:

``` java
public class MixinPerson extends Person {

   public String getNameAndSurname(){
      return name + " " + surname;
   }
}
```

This is a simple fictional scenario but I come up against similar scenarios. 

I am ready for any kind of help. 

Thanks

**Comment by mettyoung** [comment]
Hi, what's the latest update for this issue?

**Comment by cowtowncoder** [comment]
@mettyoung This issue is closed. But I think `@JsonAppend`, added via #638, was the follow-up.
Read f.ex:

    https://www.baeldung.com/jackson-advanced-annotations#jsonappend

for explanation.
