### ISSUE TITLE
Incorrect documentation for WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS

### ISSUE THREAD

**Issue by MHajoha** [FasterXML/jackson-databind#2740]
About the feature `WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS`, the wiki page https://github.com/FasterXML/jackson-databind/wiki/Serialization-features says
> WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS (default: false)

However, the actual default is `true`. This is also correctly mentioned in the Javadoc:
```
Feature is enabled by default, to support most accurate time values possible.
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this... Hmmh. This is a mess.

**Comment by cowtowncoder** [comment]
Fixed Wiki.
