### ISSUE TITLE
Jackson-datbind vulnerabilities

### ISSUE THREAD

**Issue by Al1ex** [FasterXML/jackson-databind#2745]
Hello, I have found two blacklist bypass vulnerabilities in fasterxml Jackson datbind before version 2.9.10.4. I have reported the application for CVE number before but failed to respond. I want to ask where to feed back the vulnerability? Writing directly to issues, I feel that I am not very responsible and do not meet the criteria of safety disclosure. Please contact me if necessary, thank you!

Email:hps_ fly@163.com

**Comment by cowtowncoder** [comment]
@Al1ex Thank you -- yes, I appreciate your inquiring about right procedure. As per `SECURITY.md`:

https://github.com/FasterXML/jackson-databind/blob/master/SECURITY.md

you can either send information to `info` at fasterxml dot com OR follow through Tidelift contact (you do NOT have to be subscriber to Tidelift). Both work.
I can then follow up wrt details on getting additional blocks included for 2.9.10.5
