### ISSUE TITLE
jackson-databind 2.12.0-SNAPSHOT DeserializationContext NullPointerException

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#2749]
[info]   java.lang.NullPointerException:
[info]   at com.fasterxml.jackson.databind.DeserializationContext.<init>(DeserializationContext.java:208)
[info]   at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.<init>(DefaultDeserializationContext.java:49)
[info]   at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.<init>(DefaultDeserializationContext.java:332)
[info]   at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext$Impl.createInstance(DefaultDeserializationContext.java:354)
[info]   at com.fasterxml.jackson.databind.ObjectMapper.createDeserializationContext(ObjectMapper.java:4645)
[info]   at com.fasterxml.jackson.databind.ObjectMapper.canDeserialize(ObjectMapper.java:3311)
[info]   at com.fasterxml.jackson.module.scala.ScalaObjectMapper.canDeserialize(ScalaObjectMapper.scala:173)
[info]   at com.fasterxml.jackson.module.scala.ScalaObjectMapper.canDeserialize$(ScalaObjectMapper.scala:172)
[info]   at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapperTest$$anon$1.canDeserialize(ScalaObjectMapperTest.scala:50)
[info]   at com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapperTest.$anonfun$new$7(ScalaObjectMapperTest.scala:92)

**Comment by pjfanning** [comment]
ObjectMapper passes on the null JsonParser in this code.

```  
  public boolean canDeserialize(JavaType type)
    {
        return createDeserializationContext(null,
                getDeserializationConfig()).hasValueDeserializerFor(type, null);
    }
```

DeserializationContext.java:208 -- this line blows up because JsonParser is null.

**Comment by cowtowncoder** [comment]
Ah. Thank you for reporting: sounds like a unit test would be needed here.

**Comment by cowtowncoder** [comment]
Fixed.
