### ISSUE TITLE
CoercionConfigs (2.12): make existing coercions configurable

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2750]
Now that #2113 -- core system for configuring allowed coercions -- has been implemented, what is needed next is to change actual deserializers to make use of configuration. This mostly covers existing implicitly allowed coercions (or possibly, blocked). So far existing changes cover:

* Allowing coercion from empty String (and in case of XML, blank) into POJOs, Collections/arrays, Maps -- and possibly many other types (if they extend `StdDeserializer`, or deserializers that extend it).
* Allowing `String` coercion into primitives (mostly numbers, but also booleans/Booleans).

but most other things are not yet checked.

I created this placeholder issue to allow users to comment; I will likely create separate issues for individual deserializer changes (or some grouping of those).

**Comment by cowtowncoder** [comment]
Just to seed discussion, here are some thoughts:

1. Boolean type: allowing (or not) use of integer number values (as of now, coercion from `0` is false, non-`0` true) -- and (I have to check this), verify if floating-point numbers are blocked or not
2. JDK string-like types: verify existing `EmptyString` coercion
3. Date/time types (Joda, Java 8); at least check `EmptyString` handling. Probably same for floating-point numbers, and (in case Array type is not standard serialization), arrays.
4. Guava: verify that `Collection`, `Map` follow `EmptyString` coercion

Some existing tickets that seem relevant too:

* #1852 (case-insensitive booleans) -- not sure how this can be addressed
* #2066 (UUID from empty String) -- part of (2) above

Finally, I added `coercion-config` label to use for these issues.

**Comment by cowtowncoder** [comment]
Implemented, at least:

* All existing coercions to `boolean`/`Boolean` (from String, integer number) converted to use new mechanism (but old ones also work)
* Float-to-integer checks similarly upgraded
* Coercion from empty String to `Map` verified
* From-empty-String coercions for JDK scalar types verified

This leaves

* Java 8 date/time
* Collection types (Guava esp)
* Possible additional leniency settings for `boolean`

**Comment by cowtowncoder** [comment]
Implemented "Empty String" coercion checks for Joda and Java 8 date-time types.

Will need to add one new coercion config check wrt Enums but will file separate issue for that.

**Comment by WojciechLuczkow** [comment]
I use following walk-around for 2.12:

Create custom deserializer
```java
  @Override
  public String deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {

    List<JsonToken> forbiddenTypes =
        Arrays.asList(
            JsonToken.VALUE_NUMBER_INT,
            JsonToken.VALUE_NUMBER_FLOAT,
            JsonToken.VALUE_TRUE,
            JsonToken.VALUE_FALSE);

    if (forbiddenTypes.contains(p.getCurrentToken())) {
      String message =
          MessageFormat.format("Cannot coerce {0} to String value", p.getCurrentToken());
      throw MismatchedInputException.from(p, String.class, message);
    }
    return super.deserialize(p, ctxt);
  }
```

And use it with `objectMapper`

```java
      SimpleModule deserializerModule = new SimpleModule();
      deserializerModule.addDeserializer(
          String.class, new CoercionLessStringDeserializer());
      mapper.registerModule(deserializerModule);
```

More advanced approach would be to use `ctxt.findCoercionAction(logicalType(), handledType(), CoercionInputShape.?) ` for each possible JsonToken.
