### ISSUE TITLE
Fix wrong articles in javadoc

### ISSUE THREAD

**Issue by onacit** [FasterXML/jackson-databind#2766]
I'm not good at English yet strongly believe following two sentences use a wrong article.

`an long`?

https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/JsonNode.java#L583
https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/JsonNode.java#L597

Thanks.

**Comment by cowtowncoder** [comment]
Thank you -- you are absolutely correct that it is wrong. This is probably due to copy-paste of method comments (was "an int"). Will fix.
