### ISSUE TITLE
Exposing target type to JsonDeserializer

### ISSUE THREAD

**Issue by lpandzic** [FasterXML/jackson-databind#2768]
When writting generic JsonDeserializer it would be really helpful if there's some way to extract target type in the model.

Example:
```java
module.addDeserializer(Foo.class, new FooBarJsonDeserializer<Foo>());
```

```java
class FooBarJsonDeserializer<T> extends JsonDeserializer<T> {
    @Override
    public T deserialize(JsonParser parser, DeserializationContext context) throws IOException {
         // I'd like to get Foo.class here from some of the arguments
    }
}
```

**Comment by cowtowncoder** [comment]
Currently the expectation is that (de)serializers hold on to all information they need, including type they are to handle. There is no mechanism for passing nominal type during deserialization itself, only during construction of deserializers: during construction this information is both passed when looking up deserializer by type -- exposed through `Deserializers` provider:

```java
    public JsonDeserializer<?> findBeanDeserializer(JavaType type,
            DeserializationConfig config, BeanDescription beanDesc)
```

although not accessible if using `SimpleModule` (instead, you'd need to implement `Deserializers`, register that.
Alternatively information is also available to deserializable itself if (and only if) it implements `ContextualDeserializer`:

```java
    public JsonDeserializer<?> createContextual(DeserializationContext ctxt,
            BeanProperty property) { }
```

in which case `property.getType()` provides nominal type if (but only if) deserializer is for POJO property.
There is also alternative of `DeserializationContext.getContextualType()` which should provide same information.

I cannot think of any existing mechanism that would pass type from model during actual deserialization, although there is the "current value", accessible through `JsonParser` (via `getParsingContext()`). But that would be "parent" value, as deserializer itself is to create value being deserialized.

**Comment by lpandzic** [comment]
Ok, that seems to work for my case, thanks!

For other readers:

```java
@AllArgsConstructor // used by createContextual
@NoArgsConstructor // used when you don't know the type, e.g. in simple module creation or in `@JsonDeserialize`
class FooBarJsonDeserializer<T> extends JsonDeserializer<T> implements ContextualDeserializer {

    private final Class<T> targetType;

    @Override
    public JsonDeserializer<?> createContextual(DeserializationContext deserializationContext,
                                                BeanProperty beanProperty) {
        return new FooBarJsonDeserializer<>(deserializationContext.getContextualType().getRawClass());
    }

    @Override
    public T deserialize(JsonParser parser, DeserializationContext context) throws IOException {
         // targetType should be Foo.class here
    }
}
```

**Comment by cowtowncoder** [comment]
Thank you for documenting your usage, should come handy for others that may need to do the same.
