### ISSUE TITLE
master changes to StdValueInstantiator causing compile issues for scala module

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#2794]
findValueInstantiator seems to have been replaced - is createContextual the right replacement?

```
-  override def findValueInstantiator(config: DeserializationConfig, beanDesc: BeanDescription,
-    defaultInstantiator: ValueInstantiator): ValueInstantiator = {
+  override def createContextual(config: DeserializationConfig, beanDesc: BeanDescription): ValueInstantiator = {
```

The scala functionactually uses `defaultInstantiator: ValueInstantiator`. What would you recommend to create a defaultInstantiator where the scala code needs the  defaultInstantiator?

Generally, the scala module master branch is just barely compiling and it's going to take a lot of effort to get all the tests to pass again.

**Comment by cowtowncoder** [comment]
Yes, apologies for big changes for 3.0 made a while ago (mostly?). I think this is relatively new, however, undoing some problem I uncovered with its access from datatype module; mostly related to having to pass either [Deserialization]Config or DeserializationContext... that is a big change between 2.x and 3.x, and delineation in 2.x was haphazar.

 Let me find the replacement: I think it just moved to another place, but should be accessible.

**Comment by cowtowncoder** [comment]
@pjfanning Ah ok. I think this is wrt `ValueInstantiators`? If so, I split functionality from 1 to 2 methods; if you do need default `ValueInstantiator`, there is the new `modifyValueInstantiator()` to use -- the idea simply being that `findValueInstantiator()` is called before constructing default one (and if it returns non-null, use that); and `modifyValueInstantiator()` only if first call did not result in `ValueInstantiator`. This can be used to avoid some error conditions (where attempt to construct default instantiator) would fail, as well as minor optimization.

**Comment by cowtowncoder** [comment]
Also, one other idea I have had (and need to send email to dev list):

https://github.com/FasterXML/jackson-integration-tests

wherein I was thinking of building daily-run set of tests across components. That could more easily find these compatibility problems. Not sure if this could be easily made to work with Scala module (wrt build tool choice, dependencies), but it could help catching some of the problems more quickly.

**Comment by pjfanning** [comment]
Thanks @cowtowncoder - I have the scala module building again - I'll probably need a lot of help when it comes to getting the tests to pass but at least the build is compiling.

**Comment by cowtowncoder** [comment]
Happy to help -- 2.x->3.0 changes are sizable -- but it is good progress to at least get things to compile. Functionality itself actually has not changed all that much so getting to calls matching should be most of the work.
