### ISSUE TITLE
Illegal reflective access warnings are caused using jackson-databind 2.11.0 with JDK 11

### ISSUE THREAD

**Issue by Dmeghana1** [FasterXML/jackson-databind#2802]
WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil
 (file:modules/build-cache/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.11.0/8f5aaf3878b0647ff3a16610af53b1a5c05d9f15/jackson-databind-2.11.0.jar) to field java.util.AbstractMap$SimpleEntry.key
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by cowtowncoder** [comment]
Would need a reproduction, this is unfortunately a very general warning and one that can only addressed on case-by-case basis.

**Comment by cowtowncoder** [comment]
Can not really do anything without reproduction; closing, may be reopened with a test case.
