### ISSUE TITLE
I should ObjectMapper be set to static?

### ISSUE THREAD

**Issue by wang271724646** [FasterXML/jackson-databind#2810]
- **ObjectMapper is thread safe.**
 **but I am not sure whether to set it to static, It will reduce the efficiency of the program.
How do you use it in the project?**

**Comment by kupci** [comment]
This is more of a usage question. There is a mailing list where you might find some help: https://groups.google.com/forum/#!forum/jackson-user

However, depending on what Jackson version you use, I believe the advice from this StackOverflow post is useful:

> I would suggest an alternative: keep static ObjectMapper somewhere, but only get ObjectReader / ObjectWriter instances (via helper methods), retain references to those in other places (or dynamically call). These reader/writer objects are not only fully thread-safe wrt reconfiguration, but also very light-weight (wrt mapper instances). So keeping thousands of references does not add much memory usage.

https://stackoverflow.com/questions/3907929/should-i-declare-jacksons-objectmapper-as-a-static-field

**Comment by cowtowncoder** [comment]
+1 for all @kupci said; in addition I do not think there are reasons that would make use of shared static instance less efficient in typical use cases.
Will close this now, assuming question is resolved -- in future, please use mailing list mentioned above or chat (https://gitter.im/FasterXML/jackson-databind).
