### ISSUE TITLE
Using JsonValue and JsonFormat on one field does not work as expected

### ISSUE THREAD

**Issue by nils-christian** [FasterXML/jackson-databind#2822]
Hi,

We tried to use the both annotations `JsonValue `and `JsonFormat` on one field, but the serialization does not work as expected. Assume following code:

```
public static void main( final String[] args ) throws JsonProcessingException {
	final ObjectMapper objectMapper = new ObjectMapper( );
	objectMapper.enable( SerializationFeature.INDENT_OUTPUT );
	objectMapper.setVisibility( PropertyAccessor.ALL, Visibility.NONE );
	objectMapper.setVisibility( PropertyAccessor.FIELD, Visibility.ANY );

	System.out.println( objectMapper.writeValueAsString( new A( "Some Value", new B( BigDecimal.ONE ) ) ) );
}

private static class A {

	private final String description;
	private final B b;

	public A( final String description, final B b ) {
		this.description = description;
		this.b = b;
	}

}

private static class B {

	@JsonValue
	@JsonFormat( shape = Shape.STRING )
	private final BigDecimal value;

	public B( final BigDecimal value ) {
		this.value = value;
	}

}
```

Note that the field `value` of `B` has two annotations. The resulting string is 
```
{
  "description" : "Some Value",
  "b" : 1
}
```

We would expect the value of `B` beeing written as a string, so we would expect
```
{
  "description" : "Some Value",
  "b" : "1"
}
```

If we remove the `JsonValue `annotation, we get the correct (but nested) value
```
{
  "description" : "Some Value",
  "b" : {
    "value" : "1"
  }
}
```

Is this a bug or the correct behaviour?

Thank you and best regards

  Nils

Edit: We are using Jackson 2.11.2.

**Comment by cowtowncoder** [comment]
I think that this should work, ideally. So sounds like a real bug.
I hope to add a (failing) unit test to verify when I have time, and see how difficult this would be to fix.

Thank you for reporting this!

**Comment by cowtowncoder** [comment]
I can reproduce this, and will see if use of `@JsonFormat` can be supported with `@JsonValue` (there are potential challenges unfortunately).

In the meantime if anyone is looking for work-arounds, forcing serialization as String for all `BigDecimal`s, you'd use configuration override:

```
        MAPPER.configOverride(BigDecimal.class)
            .setFormat(JsonFormat.Value.forShape(JsonFormat.Shape.STRING));
```

**Comment by cowtowncoder** [comment]
Ah ha. `JsonValueSerializer.createContextual()` is missing handling of one branch... seems promising.

**Comment by cowtowncoder** [comment]
Good news: I fixed the problem with annotation propagation. One downside: I realized that the annotation placement to use must be bit different -- it has to be next to actual property, and not within definition next to `@JsonValue`, so:

```java
private static class A {
        // Needs to be here as this is the actual property through which access occurs
	@JsonFormat( shape = Shape.STRING )
	private final B b;

	public A( final String description, final B b ) {
		this.description = description;
		this.b = b;
	}
}

private static class B {
	@JsonValue
        // CANNOT be here, alas
	private final BigDecimal value;

	public B( final BigDecimal value ) {
		this.value = value;
	}
}
```

and with that, fix works. Supporting alternative placement would be nice but I am not sure how feasible it is -- conceptually that would be logical: annotation on `@JsonValue` property should probably be used same way as class annotation of `B` would be.
That may be worth filing as another RFE issue; but for now I'll close this particular issue as there was an actual fix either way.
