### ISSUE TITLE
Cannot deserialize instance of `java.lang.Long` out of START_OBJECT token

### ISSUE THREAD

**Issue by lvjingang-git** [FasterXML/jackson-databind#2831]
When the version is 2.11.1, the following problems occur. Long is returned through the controller, and the @ restcontroller annotation is added to the controller header. At this time, the returned is < long > XXX < / long >, and "cannot deserialize instance of" appears when other services are accepted` java.lang.Long ` out of START_ If the object token is 2.10.1, it will return XXX. At this time, other services will accept it, and this problem will not occur. The springboot version 2.3.2 spring5.2.4 is used

**Comment by cowtowncoder** [comment]
Explanation is not enough, please include a reproduction that does NOT include external frameworks (such as Spring Boot or RESTeasy or DropWizard).

**Comment by lvjingang-git** [comment]
> Explanation is not enough, please include a reproduction that does NOT include external frameworks (such as Spring Boot or RESTeasy or DropWizard).
> 
> Alternatively you may want to ask about this problem (or file an issue if there is a problem with framework implementation) on mailing list of rest framework you are using, as it might be related to framework instead of Jackson.

I replaced Jackson with fastjson and added this code



@Bean

public HttpMessageConverters customConverters() {

FastJsonHttpMessageConverter fastConverter=new FastJsonHttpMessageConverter();

FastJsonConfig fastJsonConfig=new FastJsonConfig();

fastJsonConfig.setSerializerFeatures (

SerializerFeature.PrettyFormat ,

SerializerFeature.WriteMapNullValue ,

//If the list field is null, the output is [] instead of null

SerializerFeature.WriteNullListAsEmpty ,

//If the list field is null, the output is [] instead of null

SerializerFeature.WriteNullStringAsEmpty );

fastJsonConfig.setCharset ( Charset.forName ("UTF-8"));



fastConverter.setFastJsonConfig (fastJsonConfig);

return new HttpMessageConverters(fastConverter);

}
