### ISSUE TITLE
ObjectNode Issue

### ISSUE THREAD

**Issue by ControlByDestiny** [FasterXML/jackson-databind#2833]
**Is your feature request related to a problem? Please describe.**
Can't get value by use JsonNode.get(int index) of ObjectNode.The source code is return null, why not return the child of the children's map which at the specified index ?
![image](https://user-images.githubusercontent.com/28295419/91257923-a279e280-e79d-11ea-8305-9dad1aabd8e1.png)
```java
    @Override
    public JsonNode get(int index) { return null; }
```
Flolow link is the source code of ObjectNode:
[ObjectNode](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/node/ObjectNode.java)

**Describe the solution you'd like**
return the child of the children's map at the specified index

**Comment by cowtowncoder** [comment]
No, you can not use `get(int)` method on `ObjectNode`, it is only designed for use with `ArrayNode`. This is documented in Javadoc for `JsonNode`:

```
    /**
     * Method for accessing value of the specified element of
     * an array node. For other nodes, null is always returned.
```

To access children of `ObjectNode`, either access them by name or iterate over children with foreach loop (`JsonNode` implements `Iterable<JsonNode>`).
