### ISSUE TITLE
NegativeArraySizeException when using ObjectMapper.treeToValue on a <150MB file (b64 encoded)

### ISSUE THREAD

**Issue by senn** [FasterXML/jackson-databind#2843]
**Describe the bug**
We're encountering a NegativeArraySizeException when using ObjectMapper.treeToValue on a file that is b64 encoded.
It occurs here: 
![image](https://user-images.githubusercontent.com/1144233/92222939-08eab900-eea0-11ea-984a-8a7302ea6b22.png)
The shift operation generates a negative integer (because of overflowing, I guess).

**Version information**
2.9.2

**To Reproduce**
Example Maven project: https://easyupload.io/0fyrfl (file will expire in 30days so if unavailable, please let me know)

Project contains working example with small PDF and exception with big PDF.
It simulates a JSON response from our application.
Just run the main method in this code example and the error occurs. Might take a while (loading and encoding the file).

**Additional context**
Seems related to https://github.com/FasterXML/jackson-core/issues/351 although the file is not nearly as big.

**Comment by cowtowncoder** [comment]
Thank you for reporting this! Although it is for bit old Jackson version, I suspect it probably occurs with later versions too as that piece of code probably has not really changed. Your suspicion of int overflow sounds reasonable.

I hope to look into this soon, get it fixed.

**Comment by cowtowncoder** [comment]
Hmmh. Looks like 2.10.5 does not fail the same way; 
This is the reason why it would be great to test with new versions.

**Comment by cowtowncoder** [comment]
I think fix was for #2217: looks like calculation was just wrong wrt shift.

This did give me an idea for incremental improvement for 2.12, although specific problem was resolved with 2.10.0 (and thereby fix is to upgrade).

**Comment by senn** [comment]
Thanks for the feedback.  I'll check if upgrading to 2.10 is possible.
