### ISSUE TITLE
Block one more gadget type (WebSphere)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2845]
Another gadget type(s) has been reported -- but not yet verified -- regarding class(es) of IBM WebSphere application server

See https://medium.com/@cowtowncoder/on-jackson-cves-dont-panic-here-is-what-you-need-to-know-54cd0d6e8062 for description of the general problem.

Mitre id: [to be allocated]
Reporter(s): [to be added]

Fix (if one needed) would be included in:

* 2.9.10.7
* Not considered valid CVE for Jackson 2.10.0 and later (see https://medium.com/@cowtowncoder/jackson-2-10-safe-default-typing-2d018f0ce2ba)

**Comment by gurshafriri** [comment]
👋 is there any update here? 
was this deemed not an issue?

**Comment by cowtowncoder** [comment]
@gurshafriri no time to dig deeper, trickier to reproduce (no public dependency to use); may be an issue (not ruled as invalid).

**Comment by cowtowncoder** [comment]
Have not been able to access relevant libraries (do not seem accessible via Maven Central, asking submitter for more info).
May close the issue if not reproducible using public maven dependencies.

**Comment by cowtowncoder** [comment]
No further action planned at this point, not reproducible.
