### ISSUE TITLE
Add `defaultImpl` without annotation usage

### ISSUE THREAD

**Issue by blacksteed232** [FasterXML/jackson-databind#2850]
Hi,

We have a legacy codebase that we are trying to modularize better. This involves us making subtype registration dynamic (to an object mapper), so we have been converting annotation usages to declarative ones (example below)

```java
// ------------------------------------------------ BEFORE ------------------------------------------------ 

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "_type", defaultImpl = Hardcover.class)
@JsonSubTypes({
    @JsonSubTypes.Type(value=Hardcover.class, name="hardCover"),
    @JsonSubTypes.Type(value=Paperback.class, name="paperBack")
})
public abstract class Book{
    public String _type;
}

// ------------------------------------------------ AFTER ------------------------------------------------ 

// in shared module
...
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "_type")
public abstract class Book{
    public String _type;
}

// in Hardcover plugin module
...
objectMapper.registerSubTypes(
    new NamedType(Hardcover.class, "hardCover")
);

// in Paperback plugin module
...
objectMapper.registerSubTypes(
    new NamedType(Paperback.class, "paperBack")
);
```

For the `after`, since we're trying to make this modular, let's say we have 2 plugins, and in each, we implement a method that takes `objectMapper` and registers the plugin's own subtype of `Book`.

Now we got a problem with `defaultImpl` because we have some legacy data floating around which carries no `_type` info. But now, we don't know how we could dynamically add that. I think I know there's a small problem with allowing it to be configured dynamically because each plugin can say "I'm the default". It's not safe.

Nonetheless, we want to know your opinion, and if you have a solution in mind for the `Hardcover` plugin to be considered as the default implementation in this architecture. We have an orchestrator that loads all the plugins and we could potentially place the "default setter" there and it's safe that way.

And last but not least, thank you so much for this great project @cowtowncoder!

---
EDIT

We thought the most straightforward approach is to set the value of `_type` in `Book` to `hardCover`, like below:

```java
// NOTE: I have added `visible = true` but it doesn't help
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, visible = true, property = "_type")
public abstract class Book{
    // NOTE: I have tried `@JsonProperty(defaultValue = "hardCover")` but it doesn't help either
    public String _type = "hardCover";
}
```

But then we got a `missing type id property '_type'` when the input JSON does not contain the field `_type` (the structure is of a `Hardcover` though) :(

If this approach might work and it's that we messed up the `JsonTypeInfo` or so, please let us know. But also, it would be best if you have a cleaner solution in mind: we don't really want `Book` to have any knowledge of its subtypes.

**Comment by blacksteed232** [comment]
@cowtowncoder Looks like using `addAbstractTypeMapping` would work for my case.

```java
objectMapper.registerModule(new SimpleModule().addAbstractTypeMapping(Book.class, Hardcover.class);
```
And as I have tested this will follow the rule "later one wins". So later if someone adds another plugin and attempts to mess with this, they probably could. I wonder if there's a safer way to do this (or I can implement the logic in the orchestrator I mentioned earlier to do this validation. Probably exposing `objectMapper` to the plugin is not that safe either).

**Comment by cowtowncoder** [comment]
@blacksteed232 The only other thing I could think of would be overriding method in `JacksonAnnotationIntrospector` that handles reading of `@JsonTypeInfo`, but unfortunately compared to most other overridable methods ones relevant (`findTypeResolver()`,  `findPropertyTypeResolver()`, `findPropertyContentTypeResolver()` are bit complicated and include logic beyond simple reading of annotation.

So I think your approach is probably a good way to do it. You are right in that "later one wins", i.e. further registration could theoretically change mapping. This is a potential problem with modules: there are settings that are difficult to make delegating (to allow multiple settings); and even when that was possible there is always the question of precedence.
