### ISSUE TITLE
A security Bug.

### ISSUE THREAD

**Issue by KinofRikin** [FasterXML/jackson-databind#2853]
Hello, buddy. I found a JRE dependent gadget that can be used for SSRF when deserializing.

I have sent an email to info@fasterxml.com for details of the vulnerability.

Thanks.

**Comment by cowtowncoder** [comment]
@KinofRikin Thank you! I see the email there; will create a placeholder etc. I think it does qualify for CVE, I hope to work on it soon:

https://github.com/FasterXML/jackson/wiki/Jackson-Polymorphic-Deserialization-CVE-Criteria

**Comment by cowtowncoder** [comment]
Created #2854 to track this issue.
