### ISSUE TITLE
Illegal reflective access operation (java.time.OffsetDateTime)

### ISSUE THREAD

**Issue by varjoranta** [FasterXML/jackson-databind#2856]
**Describe the bug**

I am using java.time.OffsetDateTime on my Spring Boot application, and I see this warning in my logs. I updated to latest jackson-databind, but I still see the issue.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil (file:/*REDACTED*/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.2/jackson-databind-2.11.2.jar) to field java.time.OffsetDateTime.offset
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Version information**
2.11.2

**To Reproduce**
Have Spring boot application with endpoint that exposes entities containing java.time.OffsetDateTime typed variables. Call the endpoint and see the WARNING in application log.

**Expected behavior**
Behavior is fine, i.e. the data comes out as expected, but I would not expect to see that WARNING in logs.

**Comment by cowtowncoder** [comment]
Not sure what if anything can be done here: general symptom already reported a few times (#2626 f.ex).

Problem is that exception does not really tell enough about how problems comes about; there is no stack trace and as such it is not easy to know what actually triggered the warning (is there a way to make this actual hard fail to produce stack trace?)
It would also be great to have an isolated test case without framework (to isolate call path, remove possibility of SB triggering the issue).

Further: is `jackson-datatype-jsr310` registered or not? If not, it should be. If it is registered, do `LocalDate` properties use default serializer or deserializer (is this during serialization or deserialization?), or is there annotation indicating which (de)serializer to use?

**Comment by varjoranta** [comment]
I added explicit version 2.11.2 for all the following artifacts in pom:
jackson-datatype-jsr310
jackson-core
jackson-datatype-jsr310
jackson-annotations
jackson-databind
jackson-dataformat-yaml
jackson-dataformat-cbor
jackson-datatype-jdk8
jackson-module-parameter-names

Confirmed from IntelliJ IDE Maven Project external libraries list, that all jackson related libraries were of the same latest version. The error still happens.

I don't know in which part the WARNING happens. Will see if I can figure it out.

**Comment by amCap1712** [comment]
Here is a gist which reproduces the issue (hopefully correctly) https://gist.github.com/amCap1712/96d4043b6ebe6c5a7777e1c200d61ab0 with Jackson 2.11.4 .  The error only occurs when JacksonTimeModule is not registered with the ObjectMapper. From 2.12 onwards, the error is mititgated anyways because it is necessary to register the module to handle date and time types.
