### ISSUE TITLE
Wrong casing while converting POJO to JSON

### ISSUE THREAD

**Issue by vipulbansal91** [FasterXML/jackson-databind#2859]
**Describe the bug**
While converting POJO to JSON, for variables in camel case and having their second letter in capital like, `sOme`, `aNy`,  variable name in the resultant json output is `some`, `any` instead of `sOme`, `aNy`. Note that this happens only for variables which have their second letter in capital. 

**Version information**
Which Jackson version(s) was this for?
`2.9.x`

**To Reproduce**
Use the following code to reproduce : 
```
    public static class MySampleClass {
        private String aNyVariable;

        public void setANyVariable(String variable) {
            this.aNyVariable = variable;
        }
    }


    @SneakyThrows
    public static void main(String[] args) {
        ObjectMapper mapper = new ObjectMapper();

        MySampleClass sampleObject = new MySampleClass();
        sampleObject.setANyVariable("sample");

        String output = mapper.writeValueAsString(sampleObject);

        System.out.printf(output);
    }
```

**Expected behavior**
I expect the output to be `{"aNyVariable":"sample"}` but it is `{"anyVariable":"sample"}` (Please note the difference in casing of letter 'N')

**Comment by cowtowncoder** [comment]
Try enabling `MapperFeature.USE_STD_BEAN_NAMING`: that should prevent lower-casing of multiple upper-case characters.
However: I am not sure your example is quite complete, there is probably matching get method?

If that does not work, you will need to add `@JsonProperty` annotation.

**Comment by cowtowncoder** [comment]
At this point I am not sure there is anything to change: original example seems to use Lombok so I do not know what kind of underlying class is being generated, but I suspect it is simply due to the way Lombok generates getter/setter names.
Will close: may be reopened with a reproduction that does not use Lombok (use of Lombok in general is fine, but it can not be used for test).
