### ISSUE TITLE
Question: Hide/Ignore fields conditionally

### ISSUE THREAD

**Issue by CEikermann** [FasterXML/jackson-databind#2860]
Dear Jackson community,

we are trying to enhance the Jackson serializer in one of our project. We want to hide / ignore certain fields from certain objects conditionally. Means certain fields should only be serialized to JSON when a specific condition is true. We want to restrict certain fields based on the current user access.

Our idea is to pass a auth context to Jackson, this auth context will contain information which fields the current user can see and which not.

The difficult part now comes how we can hide certain fields based on this.

What we already considered:
- JsonIgnore annotation (does not work, its static and not based on conditions)
- JsonInclude annotation (does not work, its static and not based on conditions)
- JsonView (not very practical, we would need to create one view class for each field in all objects)
- Using custom serializer as described here https://www.baeldung.com/jackson-serialize-field-custom-criteria#2-custom-serializer (Can only work to hide a complete object, not just certain fields)

Does anyone has a good approach in Jackson to exclude / hide / ignore certain fields dynamically?

**Comment by cowtowncoder** [comment]
@CEikermann we do not really provide usage information via bug tracker (not many devs necessarily read new issues), so your best bet would be to email to

https://groups.google.com/g/jackson-user

To me things you have attempted sounds about main approaches but I am sure user community has other suggestions to share beyond standard functionality.

**Comment by cowtowncoder** [comment]
Question was sent to user list; closing the issue.
