### ISSUE TITLE
Release one more 2.6 micro-patch, 2.6.7.4

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2866]
(note: follow-up to #2864)

Thanks to backport of fixes, there is probably need for one more micro-patch, esp. to help AWS Client users.
Timing not established: feel free to "vote" if you would use such a release.

**Comment by cenedhryn** [comment]
Hi, another member of the AWS Java SDK here. At least one customer has indicated that they'd like to avoid the CVE/CWEs in the patched version.

**Comment by cowtowncoder** [comment]
One last micro-patch, 2.6.7.4 of `jackson-databind` released, along with matching `jackson-bom` 2.6.7.4.
Includes all existing CVE fixes up to 2.9.10.6
