### ISSUE TITLE
Add `@JsonKey` annotation (similar to `@JsonValue`) for customizable serialization of Map keys

### ISSUE THREAD

**Issue by CidTori** [FasterXML/jackson-databind#2871]
**Describe the bug**
When serializing a map key, if the key's type uses `@JsonValue` on one of its attributes, and if that attribute's type uses `@JsonValue` on one of its own attributes, the second `@JsonValue` is ignored, and `toString()` is used instead.

**Version information**
2.10.0

**To Reproduce**
```java
    class Inner {

        @JsonValue
        String string;

        Inner(String string) {
            this.string = string;
        }

        public String toString() {
            return "Inner(String="+this.string+")";
        }

    }

    class Outer {

        @JsonValue
        Inner inner;

        Outer(Inner inner) {
            this.inner = inner;
        }

    }

    public void test() throws Exception {
        Outer outer = new Outer(new Inner("key"));
        ObjectMapper mapper = new ObjectMapper();
        System.out.println(mapper.writeValueAsString(outer)); // outputs "key", as expected
        System.out.println(mapper.writeValueAsString(Collections.singletonMap(outer,"value"))); // outputs {"Inner(String=key)":"value"}, expected {"key":"value"}
    }
```

**Comment by cowtowncoder** [comment]
Correct: `@JsonValue` only affects serialization of _values_, not (Map) keys. It is not designed to work that way, and in a way can not -- keys are written using `JsonParser.writeFieldName()`, values may use a set of other calls (`writeString()`, `writeNumber()`).

This means that as things are you will need to register separate "key serializer", either via module, or using `@JsonSerialize(keyUsing = ...)` on class.

**Comment by CidTori** [comment]
It could be best to use another annotation indeed, like `@JsonKey`, because you could also want to serialize an object differently if it's a key or a value (since, as you said, in JSON, keys must be Strings, unlike values).

I just want to add that, currently, `@JsonValue` **does** affect serialization of *keys*, since, in my example, the `@JsonValue` on `Outer.inner` is not ignored ; it's the `@JsonValue` on `Inner.string` that is ignored.

**Comment by cowtowncoder** [comment]
Good point wrt different annotation for key/value aspect, somehow missed that (I think I had that in mind in the past).

I'll have to see how `@JsonValue` is used, then; I was thinking that it might be used for `Enum`s but not other types. But perhaps I have forgotten about a feature I added at some point...
Adding a separate annotation would make sense, regardless, I think -- but obviously need to consider existing handling as users may be relying on that.
And I agree that if chaining works for values, it should work for keys as well.

**Comment by CidTori** [comment]
Yep, for example : while serializing a map key, if there is a `@JsonKey`, use it (with chaining), else if there is a `@JsonValue`, use it (with chaining too), else use `toString()` ?

**Comment by Anusien** [comment]
I've started working on this.

**Comment by Anusien** [comment]
```
    class Inner {

        @JsonKey
        @JsonValue
        String string;

        Inner(String string) {
            this.string = string;
        }

        public String toString() {
            return "Inner(String="+this.string+")";
        }
    }

    class Outer {

        @JsonValue
        Inner inner;

        Outer(Inner inner) {
            this.inner = inner;
        }
    }
```
If we only put `@JsonValue` on the `Outer` class (and not `@JsonKey`), would you expect it to trickle down and read the `@JsonKey` value on the inner class? Or would the requirement be to have `@JsonKey` on `Outer` *and* `Inner`?

**Comment by cowtowncoder** [comment]
@Anusien Interesting... this gets quite tricky, wrt overlap of annotations, precedence.

I think that it will be simpler and more reliable to keep `@JsonValue` and `@JsonKey` separate, and that would, I think, require duplication of annotation at both levels.
Conversely if handling of the two was coupled it could cover more cases with fewer annotations but would probably have weird edge cases and more complicated handling internally (to try to combine intended logic).

Does this make sense?

**Comment by cowtowncoder** [comment]
Just realized there's the original issue, #47, that gives more context.
