### ISSUE TITLE
`MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS` should work for enum as keys

### ISSUE THREAD

**Issue by XakepSDK** [FasterXML/jackson-databind#2873]
**Describe the bug**
ACCEPT_CASE_INSENSITIVE_ENUMS not working for enums as map keys

**Version information**
2.11.2

**To Reproduce**
Use enum as map key and deserialize json with different key case

**Expected behavior**
ACCEPT_CASE_INSENSITIVE_ENUMS works for map enum keys

**Comment by ILGO0413** [comment]
I would like to work on it.

**Comment by ILGO0413** [comment]
According to README.md#Basic rules for Code Contributions, I should provide a filled Contributor License Agreement. Do you have any example of CLA?

**Comment by ILGO0413** [comment]
Would you accept it if I write it by hand?

**Comment by cowtowncoder** [comment]
CLA as submitted fine (i.e. electronic variant works for us). Thank you for doing it very quickly!

**Comment by cowtowncoder** [comment]
Merged, backported in 2.12. Thank you @ILGO0413!
