### ISSUE TITLE
Serialization-deserialization chain not reproducable

### ISSUE THREAD

**Issue by raphw** [FasterXML/jackson-databind#2874]
Jackson cannot read all JSON that itself produces if a `valueOf` method is used for unmarshalling, I was rather surprised by this as two components using the same versions and setup failed to communicate. For an example, consider the following non-Jackson related bean class where one, unrelated to Jackson, defines a `valueOf` method:

    public static class Sample {

        private Value id;

        public Value getId() {
            return id;
        }

        public void setId(Value id) {
            this.id = id;
        }
    }

    public static class Value {

        private final String first, second;

        public static Value valueOf(String input) {
            return new Value(input.substring(0, 4), input.substring(4, 8));
        }

        public Value(String first, String second) {
            this.first = first;
            this.second = second;
        }

        public String getFirst() {
            return first;
        }

        public String getSecond() {
            return second;
        }

        @Override
        public String toString() {
            return first + second;
        }
    }

The following code renders an error:

        ObjectMapper mapper = new ObjectMapper();
        String input = "{\"id\":\"12345678\"}";
        Sample sample = mapper.readValue(input, Sample.class);
        String output = mapper.writeValueAsString(sample);
        Sample next = mapper.readValue(output, Sample.class);

Is this working as intended? In my understanding, using `valueOf` implicitly for deserializartion is only safe when also implicitly using `toString` for serialization.

The outputting JSON is neither equivalent to the input:

    {"id":"12345678"} // input
    {"id":{"first":"1234","second":"5678"}} // output

Also: Is there a convention for serialization similar to valueOf?

**Comment by cowtowncoder** [comment]
Use of `valueOf()` for a limited set of cases is a very old legacy feature, intended mostly to support JDK types, or third-party applications, so that's one part of this.

But more importantly, from the very beginning Jackson has kept serialization and deserialization sides somewhat uncoupled: this mostly since serialization-only use case was considered common (deserialization-only probably also exists but less often). So there has never been requirement that one should be able to do both, or that they are necessarily even symmetric.
As such there is no intent to force or infer coupling of `toString()` / `valueOf()` -- not saying this would not be logical or make sense, as I can see value; just that this is not intent.

Now... not sure what to think of this case, let me think a bit more.

**Comment by raphw** [comment]
Alright, I had the impression that *input -> output -> input* chains would always work with Jackson. I worked around the problem by registering a module for now but I'd suggest changing the default behavior for the 3.0 release. I'd very much prefer an error at the first receiver where `valueOf` should not have worked to begin with in this case. From logs everything seems normal as a third-party class was used and the reception of a value from an external system did work but failed once serialized and attempted deserialized in an internal system that used the exact same configuration.

**Comment by cowtowncoder** [comment]
@raphw I am not sure I understand the exact request here: would you prefer no auto-detection of static `valueOf()` method (as delegating creator, similar to being annotated with `@JsonCreator(mode = Mode.DELEGATING)`) -- which is something I would definitely consider for 3.0 -- or some bigger change? And if latter, maybe some of the ideas for how it'd work here.

**Comment by raphw** [comment]
I'd prefer to being able to turn this off somehow since it would make such an implicit, incompatible conversion fail where it occurs. And if there are breaking changes in 3.0, I suggest you might consider this as the default option.

**Comment by cowtowncoder** [comment]
@raphw I'll keep this in mind as suggestion, esp. in making use of `static X valueOf(...)` opt-in, instead of opt-out.

**Comment by cowtowncoder** [comment]
Not sure there is specific follow-up work: if there is, need to file separate issue(s).
