### ISSUE TITLE
Upcoming 2.12 breaks source compatibility from 2.11

### ISSUE THREAD

**Issue by RomainMuller** [FasterXML/jackson-databind#2878]
**Describe the bug**

The removal of a checked exception from the signature of `ObjectMapper#treeToValue()` introduced via #2805 is a source-breaking change, as any code attempting to `catch` that checked exception will no longer compile.

**Version information**
2.12.0-rc1

**To Reproduce**

```java
try {
  new ObjectMapper().treeToValue(tree);
} catch (JsonProcessingException e) { // <- exception com.fasterxml.jackson.core.JsonProcessingException is never thrown in body of corresponding try statement
  throw new RuntimeException(e);
}
```

**Expected behavior**
Expected code that builds fine against Jackson 2.11 to continue building with 2.12.

**Additional context**
This appears to breach [Apache Versioning](https://apr.apache.org/versioning.html) convention, which Jackson claims to enforce: https://github.com/FasterXML/jackson/wiki/Jackson-Releases#general

**Comment by cowtowncoder** [comment]
First of all, thank you for reporting this.

You are right, this would be source incompatible (although binary compatible).

I'll bring this up on dev mailing list, see how others feel about it. It's bit tricky as it is a useful in many ways, removing need for useless catch. But if there is significant existing usage that has catch blocks that would be annoying change as it would make it more difficult to retain cross-version compatibility.

**Comment by cowtowncoder** [comment]
Decided to put back the exception. Too bad as while it was declared, one will never be thrown (`IOException` if caught -- unlikely to ever thrown to begin with -- would be re-thrown as `IllegalArgumentException`). But good catch so as not to break builds with simple minor upgrade.

**Comment by RomainMuller** [comment]
No disagreement on the fact this is annoying (especially since this is a useless `catch`...).

I was prepared to accept "#wontfix" as an answer, but it kinda struck me that the magnitude of the source compatibility breakage might be larger than intended (sadly).

Well anyhow - thanks for the consideration here! And glad we're "fixing" it (while also sad for the void catch 🤷🏻‍♂️).

**Comment by cowtowncoder** [comment]
Yeah @RomainMuller I fully agree. At least 3.0 fixes it, and maybe I can finally go back to focusing on it after 2.12.0 is out :)
