### ISSUE TITLE
Upcoming 2.12 breaks ABI for aws-sdk-java

### ISSUE THREAD

**Issue by brettkail-wk** [FasterXML/jackson-databind#2880]
**Describe the bug**
[This change](https://github.com/FasterXML/jackson-databind/commit/9f97baa28c31b450b6fde22ae56e067dd50c2eb4#diff-d0e2f64295891d9fc684285fa47ca496L444) breaks [this code](https://github.com/aws/aws-sdk-java/blob/5694fc578e5069dbadb40b789091d4db9a834edc/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java#L89).

**Version information**
2.12.0-rc1

**To Reproduce**

**Expected behavior**

**Additional context**
It's problematic for consumers if a dependency library ever removes API.  Please consider reverting this API change.  Even if you coordinate with aws-sdk-java for this specific change, it likely still causes complications for integrators, and there is risk that other integrators are affected.

**Comment by cowtowncoder** [comment]
@brettkail-wk Could you elaborate on this: links to do not quite explain what your concern is. The intent here was to deprecate existing constants to address #2715 but only remove them in 3.x, to retain expected backwards-compatibility. But it sounds like part of the change did do something else, and I'd like to understand specific problem.

**Comment by cowtowncoder** [comment]
@brettkail-wk Ah. I see what you mean. Let me think about this specific part -- since there is non-trivial 2.6.x usage left, it is a valid concern. Especially given that there is specific example (as compared to potential concern).

Thank you for pointing this out.
