### ISSUE TITLE
Error in documentationof TypeFacorty::constructParametricType

### ISSUE THREAD

**Issue by axthosarouris** [FasterXML/jackson-databind#2886]
**Which part of documentation is missing, incorrect or out of date? Please describe.**
You may suggest changes, deletions, additions.

The present documentation contains the following:
```
 *<pre>
     *  JavaType inner = TypeFactory.constructParametricType(Set.class, Set.class, Integer.class);
     *  return TypeFactory.constructParametricType(ArrayList.class, List.class, inner);
     *</pre>
```
but there is no method `constructParametricType(Class<?>,Class<?>, JavaType)`. There is only the deprecated `constructParametrizedType` with this parameter list 

Suggested correction: 
```
TypeFactory.constructParametricType( List.class, inner);
```

**Comment by cowtowncoder** [comment]
Thank you for the suggestion! Will go ahead, make suggested changes.
