### ISSUE TITLE
@JsonIgnoreType not having any effect

### ISSUE THREAD

**Issue by OrangeDog** [FasterXML/jackson-databind#2893]
**Describe the bug**
A `@JsonIgnoreType` annotation applied to an interface does not exclude its getters from serialisation.

**Version information**
2.11.2

**To Reproduce**
```java
@JsonIgnoreType
public interface Parent {
    default String getFoo() { return "foo"; }
    String getBar();
}

public class Child implements Parent {
    public String getBar() { return "bar"; }
    public String getBaz() { return "baz"; }

    public static void main(String... args) {
        new ObjectMapper().writeValue(System.out, new Child());
    }
}
```
> {"baz":"baz","bar":"bar","foo":"foo"}

**Expected behavior**
Should be the same as is using this
```java
public interface Parent {
    @JsonIgnore default String getFoo() { return "foo"; }
    @JsonIgnore String getBar();
}
```
> {"baz":"baz"}

**Comment by cowtowncoder** [comment]
I think you may have misunderstood usage of `@JsonIgnoreType`: it does not mean "hide everything this type has" but rather "ignore all values of this type". It can not, however, apply to the root value itself but only to property values.

So if you had something like

```java
class Container {
   public Child child;
   public int x;
}
```
then serialization of container would like

```java
{"x":13}
```

ignoring `child` since it is of type with `@JsonIgnoreType` annotation.

I am open to improvements in Javadocs of `@JsonIgnoreType` is that caused confusion here.

**Comment by OrangeDog** [comment]
> all properties of annotated type

I thought it meant "all properties that this type has", rather than "all properties that have this type".
The latter phrasing should avoid future confusion.

**Comment by cowtowncoder** [comment]
Improved javadocs as suggesed.

**Comment by cowtowncoder** [comment]
Yes @nektro: all properties found that have this (exact) type.

**Comment by nektro** [comment]
i mean is there an annotation i can put on a class to make it as if there was `@JsonIgnore` on every single one, so that i can then manually override specific fields with `@JsonInclude`

**Comment by cowtowncoder** [comment]
@nektro You can try to see if combination works, but the intent is not for "default inclusion" (exclude unless included) but to fully exclude all instances. To be used on types one never wants to include.
