### ISSUE TITLE
Removal of PASCAL_CASE_TO_CAMEL_CASE creates compatibility problems

### ISSUE THREAD

**Issue by skohlmann** [FasterXML/jackson-databind#2897]
**Describe the bug**
The removal of `com.fasterxml.jackson.databind.PropertyNamingStrategy#PASCAL_CASE_TO_CAMEL_CASE` creates problems within AWS environments. The field is referenced by `com.amazonaws.util.EC2MetadataUtils` (transitive reference in `com.amazonaws:aws-java-sdk-core:jar:1.11.883`) and raise a _NoSuchFieldError_ if overwriting the Jackson environment of AWS `com.amazonaws:aws-java-sdk-core` (which is Jackson 2.6.7).

**Version information**
2.12.0-rc1

**To Reproduce**

Call  `com.amazonaws.services.sqs.AmazonSQSClientBuilder#defaultClient()` (of package `com.amazonaws:aws-java-sdk-sqs:jar:1.11.883`) with `com.fasterxml.jackson.core:jackson-databind:jar:2.12.0-rc1`.

**Expected behavior**
There is no _NoSuchFieldError_ in combination of com.amazonaws:aws-java-sdk-core and Jackson.

**Comment by cowtowncoder** [comment]
Hi @skohlmann! Yes, thank you for reporting this -- release candidates are meant to find out accidental changes like this.
Issue has been resolved as #2880 and will be included in `2.12.0-rc2` once we get that out.

**Comment by hohwille** [comment]
I do not know what is happening here but with AWS `s3-2.16.1.jar` in combination with `jackson-databind-2.16.0.jar` I am getting this:
```
Caused by: java.lang.NoSuchFieldError: PASCAL_CASE_TO_CAMEL_CASE
	at software.amazon.awssdk.regions.internal.util.EC2MetadataUtils.<clinit>(EC2MetadataUtils.java:95)
	at software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider.tryDetectRegion(InstanceProfileRegionProvider.java:68)
	at software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider.getRegion(InstanceProfileRegionProvider.java:52)
	at software.amazon.awssdk.regions.providers.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:51)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.regionFromDefaultProvider(AwsDefaultClientBuilder.java:202)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveRegion(AwsDefaultClientBuilder.java:184)
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:135)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:157)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:27)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:129)
```

AWS code is:
```
    private static final ObjectMapper MAPPER = new ObjectMapper();
    // ...
    private EC2MetadataUtils() {
    }

    static {
        MAPPER.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        MAPPER.setPropertyNamingStrategy(PropertyNamingStrategy.PASCAL_CASE_TO_CAMEL_CASE);
    }
```

So was it fixed at all? Or breaking change redone after fix? Any sync with AWS guys? 
This turns out as a complete blocker for S3 client usage.
Any workarounds?

**Comment by hohwille** [comment]
https://github.com/aws/aws-sdk-java/discussions/3098

**Comment by hohwille** [comment]
Workaround seems to be `jackson-databind-2.15.4.jar`. According to maven central that was released on `2024-02-15 17:35` while `2.16.0` what sounds more recent was released on `2023-11-15 22:38` and "latest" `2.16.1` on `2023-12-24 04:31`.
So I will just ignore `2.16.x` releases for now and should be able to proceed. Hope this may help others stumbling over the same problem...

**Comment by pjfanning** [comment]
@hohwille why not use aws 2.24.x or 2.23.x? The AWS code was changed - see https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java

**Comment by hohwille** [comment]
> @hohwille why not use aws 2.24.x or 2.23.x? The AWS code was changed - see https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java

@pjfanning thanks for pointing that out. Usually the first thing I do when adding a dependency is checking maven central for the latest version. Indeed the version `2.16.1` is rather old so my mistake. Great that it can be solved either with the proper version of `jackson` (2.15.4) or a newer version of AWS sdk for s3. So all solved 👍

**Comment by mattbishop** [comment]
The reason I can't update AWS SDK versions is because I am using the Camel AWS integration and cannot upgrade that at the moment.

Better for Jackson to preserve the API for minor library upgrades, as per Semantic Versioning conventions. When Jackson moves to 3.x, a major version change, then these kinds of breaking changes can be expected.

https://semver.org

**Comment by cowtowncoder** [comment]
In general, tho, we do try to keep compatibility in a way like you suggest.

But at this point, field has been removed tho and trying to add it back would be even more confusing as some intermediate versions wouldn't have it.

**Comment by danjee** [comment]
I am having the same issue with jackson v 2.17.0 and aws sdk 2.25.17 (latest as today)

**Comment by danjee** [comment]
It worked with 2.15.4 so most likely the fix wasn't merged in 2.17.0 even though is more recent than the fix.

**Comment by cowtowncoder** [comment]
@danjee at this point there isn't anything planned to be changed on Jackson side.

Not sure what "it worked" here specifically means, but it sounds like newer version of AWS client works with newer versions of Jackson so that's probably the way forward.

**Comment by danjee** [comment]
> Not sure what "it worked" here specifically means, but it sounds like newer version of AWS client works with newer versions of Jackson so that's probably the way forward.

I've tried with the latest aws sdk version2.25.17 (latest as yesterday) and jackson 2.17.0 as I've stated in the previous comment and the error popped up. Downgrading jackson lib to 2.15.2 and keeping the aws lib to 2.25.17 (latest as yesterday) it "worked" as in the error didn't appeared. 

> at this point there isn't anything planned to be changed on Jackson side.

My guess was that for 2.15.2 the fix was applied and for 2.17.0 it wasn't. 
Thanks

**Comment by cowtowncoder** [comment]
No, there was no fix in 2.15.2 -- but rather already deprecated (in 2.7) field was finally removed from 2.16. Assumption being that since it has been deprecated for so long -- with a compatible replacement since 2.7, to upgrade to -- no client would be using field any longer. Looks like this was being optimistic.

But given this, there are multiple releases without said deprecated field and it will not be reintroduced. Dependant libraries/frameworks need to use the replacement strategy.

**Comment by cowtowncoder** [comment]
btw, which AWS sdk library are we talking about? https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-core has version only to 1.12.x

**Comment by danjee** [comment]
https://mvnrepository.com/artifact/software.amazon.awssdk/s3/2.25.17 - I see that they made 2.25.18 the same day. I'll try that too. Thanks

**Comment by cowtowncoder** [comment]
@danjee Did it work out? And if so, which Jackson version does it depend on (MvnRepository does not show Jackson as direct dependency and I couldn't figure out which transitive dep would show it).

**Comment by FibinPhilipTR** [comment]
> I am having the same issue with jackson v 2.17.0 and aws sdk 2.25.17 (latest as today)

Same issue facing for me too..  jackson v 2.17.2 and aws sdk v2.25 or even with latest aws sdk 2.29

**Comment by cowtowncoder** [comment]
@sheetalj2205 Please reach out to AWS SDK community or maintainers (or... LocalStack? Whatever that is). We do not maintain those packages.

**Comment by tomkalafut** [comment]
@sheetalj2205 Did you ever have any lucky with this? We're using LocalStack, too.
