### ISSUE TITLE
Jackson does not support deserializing new Java 9 unmodifiable collections

### ISSUE THREAD

**Issue by TheSpiritXIII** [FasterXML/jackson-databind#2900]
**Describe the bug**
Java 9 introduced new unmodifiable collection APIs. For instance, List.of.

Today, Jackson has a special deserializer for Collections.unmodifiableList but not for these new classes:
https://github.com/FasterXML/jackson-databind/blob/a64e1bfd7ced17c2e19e73da1a00f3e679011fec/src/main/java/com/fasterxml/jackson/databind/deser/impl/JavaUtilCollectionsDeserializers.java#L81

**Version information**
2.11.2

**To Reproduce**
```java
@Test
public void testUnmodifiableList() throws JsonMappingException, JsonProcessingException {
	final ObjectMapper mapper = new ObjectMapper();
	mapper.activateDefaultTypingAsProperty(
		new NoCheckSubTypeValidator(),
		ObjectMapper.DefaultTyping.NON_FINAL,
		"@class"
	);

	final List<String> list = Collections.unmodifiableList(Collections.singletonList("a"));
	final String actualJson = mapper.writeValueAsString(list);
	System.out.println(actualJson);
	final List output = mapper.readValue(actualJson, List.class);
	System.out.println(output);
}

@Test
public void testJava9UmodifiableList() throws JsonMappingException, JsonProcessingException {
	final ObjectMapper mapper = new ObjectMapper();
	mapper.activateDefaultTypingAsProperty(
		new NoCheckSubTypeValidator(),
		ObjectMapper.DefaultTyping.NON_FINAL,
		"@class"
	);

	final List<String> list = List.of("a");
	final String actualJson = mapper.writeValueAsString(list);
	System.out.println(actualJson);
	final List output = mapper.readValue(actualJson, List.class);
	System.out.println(output);
}

@Test
public void testJava9ListWrapped() throws JsonMappingException, JsonProcessingException {
	final ObjectMapper mapper = new ObjectMapper();
	mapper.activateDefaultTypingAsProperty(
		new NoCheckSubTypeValidator(),
		ObjectMapper.DefaultTyping.NON_FINAL,
		"@class"
	);

	final List<String> list = Collections.unmodifiableList(List.of("a"));
	final String actualJson = mapper.writeValueAsString(list);
	System.out.println(actualJson);
	final List output = mapper.readValue(actualJson, List.class);
	System.out.println(output);
}
```
testJava9UmodifiableList fails. The other 2 pass.

**Expected behavior**
I would think the new classes are added as additional aliases as candidates for special deserialization.

Unfortunately, I think this is tricky for two reasons:
1. These are Java 9 classes and Jackson supports a lower minimum Java version. I'm not sure if there's a way to add them without breaking backwards compatibility or introducing a new Java 9 add-on library, like there exists for Java 8.
2. There are multiple classes. For List.of, there seem to be 3 different ones depending on the number of arguments:
- Empty list if 0 arguments.
- List12 if 1 or 2 arguments.
- ListN if more than 2 arguments.
Source: https://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.base/share/classes/java/util/List.java#l1031

**Comment by cowtowncoder** [comment]
Ok, had a chance to look a bit into this. I agree with notes on 2 main challenges, but there is also third immediate problem wrt tests: type for `List` is actually `final` which is what sort of breaks the test since:

1. During serialization, actual type -- which is `final` -- will result in no type information being added, BUT
2. During deserialization, requested type -- `List` -- is NON-FINAL and as such no type information is excepted

so test would fail even if special handling was added.

For now I think I can at least add failing test(s), under `src/test-jdk14/` to allow reproducing the issue, in case someone has time to look deeper into possible solutions.

**Comment by cowtowncoder** [comment]
Quick note: I think changes from #3009 may have helped (or will help), although there is still at least one failure.

**Comment by cowtowncoder** [comment]
Ok, so I fixed the main issue for 2.13.0 and when type id is included `List.of()` as well as `Map.of()` sourced containers should handle as expected.

The problem wrt test and inclusion -- that implementation types are `final`, preventing application of Default Typing -- is something that I don't quite know how to tackle at this point.

**Comment by joakime** [comment]
When will 2.13.0 be release?

**Comment by kupci** [comment]
> 
> 
> When will 2.13.0 be release?
Per below, towards end of Q2 or early Q3 ( so June/July 2021)
https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress

**Comment by Sam-Kruglov** [comment]
Hi, 2.13.0 doesn't seem to work with `Set.of()` and I don't see any tests for it, there're only for `List.of()` and `Map.of()`.
