### ISSUE TITLE
Jackson 11.2 TreeTraversingParser loses previously set `currentValue` if `nextToken()` is not null

### ISSUE THREAD

**Issue by SamOrozco** [FasterXML/jackson-databind#2904]
**Describe the bug**
The `currentValue` is not longer persisted to field parsers. This breaks deserializers that expect the `JsonParser` `currentValue` to be the `currentValue` that was previously set on the parser.  

**Version information**
Broken on version 2.11.2 working on version 2.10.4

**To Reproduce**

This is a parsing example of where the bug occurs

Class example
```java
class Job {
    private Task task;

}
@JsonDeserialize(using = Deserializer.class)
 private static class Task {

}
```

```java
	public static <T> T parseJson(String json, Class<T> clazz, Object objectToPass)
	{
		try
		{
			JsonParser parser = JsonUtils2.getJsonFactory().createParser(json);
			ObjectCodec mapper = parser.getCodec();
			JsonNode node = parser.readValueAsTree();
			JsonParser subParser = node.traverse(mapper);
			subParser.setCurrentValue(objectToPass);
			return mapper.readValue(subParser, clazz);
		}
		catch (IOException ex)
		{
			throw new JsonException("Error parsing json", ex);
		}
	}
```

Custom Deserializer
```java 
static class Deserializer extends JsonDeserializer<Task> {
    @Override
    public Task deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
        Object curVal = p.getCurrentValue();
        if (!(curVal instanceof Job))
            throw new JsonMappingException(p, "exception");
```

**Expected behavior**
I would expect the child field to get the values that is being set on the json parser. 

**Additional context**

Looks like previously in TreeTraversingParser(**2.10.4**) you would set current token and return out. 

*TreeTraversingParser.java*
```java
    @Override
    public JsonToken nextToken() throws IOException, JsonParseException
    {
        if (_nextToken != null) {
            _currToken = _nextToken;
            _nextToken = null;
            return _currToken;
        }
```

In TreeTraversingParser(**2.11.2**) you are making sure next token is not null then resetting the `_nodeCursor` which will reset the `currentValue`
```java
    @Override
    public JsonToken nextToken() throws IOException, JsonParseException
    {
        _currToken = _nodeCursor.nextToken();
        if (_currToken == null) {
            _closed = true; // if not already set
            return null;
        }
        switch (_currToken) {
        case START_OBJECT:
            _nodeCursor = _nodeCursor.startObject();
```

# Note

I just found a work around of getting the parsingContext parent then getting the current value from parent.

**Comment by cowtowncoder** [comment]
I'd have to think through this carefully, but in general current value is typically set by Jackson core and (de)serializers during processing. It seems to me that in this particular case it seems that a typical deserializer would be expected to assign current value to be value it constructs for matching `JsonToken.START_OBJECT` -- and that your work-around would be expected to find the "parent" value, which you assigned earlier.

So I suspect that the new behavior is closer to how this might be expected to work going forward. Having said that the maintenance of currentValue is quite elaborate in case where there are multiple parsers (at least in theory; TreeTraversingParser is often used for buffering and is sort of enclosed by underlying parser used for content outside)

**Comment by SamOrozco** [comment]
Closing for now because of work around.
