### ISSUE TITLE
@JsonDeserialize not working on field

### ISSUE THREAD

**Issue by Tsyklop** [FasterXML/jackson-databind#2906]
`@JsonDeserialize` not working on field.

Using Spring Boot 2 and Jackson 2.11.3.

Code:

```java
@Data
public class EventOddPOJO {

    @JsonProperty("id")
    private String id;

    @JsonDeserialize(using = EventOddPartDeserializer.class)
    private String part;

    @JsonProperty("ss")
    private String score;

    @JsonDeserialize(using = EventOddMinuteDeserializer.class)
    private String minute;

    @JsonDeserialize(using = EventOddSecondDeserializer.class)
    private String second;

    @JsonProperty("over_od")
    private String overOd;

    @JsonProperty("home_od")
    private String homeOd;

    @JsonProperty("draw_od")
    private String drawOd;

    @JsonProperty("away_od")
    private String awayOd;

    @JsonProperty("under_od")
    private String underOd;

    @JsonProperty("time_str")
    private String timeStr;

    @JsonProperty("add_time")
    private String addTime;

    @JsonProperty("handicap")
    private String handicap;

    public static class EventOddPartDeserializer extends StdDeserializer < String > {

        public EventOddPartDeserializer() {
            this(null);
        }

        public EventOddPartDeserializer(Class < ? > vc) {
            super(vc);
        }

        @Override
        public String deserialize(JsonParser p, DeserializationContext ctxt) throws IOException,
        JsonProcessingException {

            String timeStr = p.getValueAsString("timeStr");

            if (Objects.isNull(timeStr)) {
                return "-";
            }

            return timeStr.split(" - ")[0];

        }
    }

    public static class EventOddMinuteDeserializer extends StdDeserializer < String > {

        public EventOddMinuteDeserializer() {
            this(null);
        }

        public EventOddMinuteDeserializer(Class < ? > vc) {
            super(vc);
        }

        @Override
        public String deserialize(JsonParser p, DeserializationContext ctxt) throws IOException,
        JsonProcessingException {

            String timeStr = p.getValueAsString("timeStr");

            if (Objects.isNull(timeStr)) {
                return "-";
            }

            return timeStr.split(" - ")[1].split(":")[0];

        }
    }

    public static class EventOddSecondDeserializer extends StdDeserializer < String > {

        public EventOddSecondDeserializer() {
            this(null);
        }

        public EventOddSecondDeserializer(Class < ? > vc) {
            super(vc);
        }

        @Override
        public String deserialize(JsonParser p, DeserializationContext ctxt) throws IOException,
        JsonProcessingException {

            String timeStr = p.getValueAsString("timeStr");

            if (Objects.isNull(timeStr)) {
                return "-";
            }

            return timeStr.split(" - ")[1].split(":")[1];

        }
    }

}
```

Json:

    {
                        "id": "35008186",
                        "home_od": "1.952",
                        "handicap": "+3.5",
                        "away_od": "1.740",
                        "ss": "95:98",
                        "time_str": "4 - 04:08",
                        "add_time": "1603807890"
    }

**Comment by Tsyklop** [comment]
@cowtowncoder When I try to read json to Object.

If you insert `System.out.println` or place debugger point in the custom deserializers - you didnt receive any feedback in console or ide

Sample code:

```
public class BackendRestApiV1Application {

    public static void main(String[] args) throws JsonProcessingException {

        ObjectMapper objectMapper = new ObjectMapper();

        System.out.println(objectMapper.readValue("{\n" +
                "                    \"id\": \"35008186\",\n" +
                "                    \"home_od\": \"1.952\",\n" +
                "                    \"handicap\": \"+3.5\",\n" +
                "                    \"away_od\": \"1.740\",\n" +
                "                    \"ss\": \"95:98\",\n" +
                "                    \"time_str\": \"4 - 04:08\",\n" +
                "                    \"add_time\": \"1603807890\"\n" +
                "                }", EventOddPOJO.class));

    }

}
```

**Comment by cowtowncoder** [comment]
@Tsyklop So are you saying that the custom deserializers are not getting called?

**Comment by Tsyklop** [comment]
@cowtowncoder Yes. I assume that they are not called because these fields are not in json

**Comment by cowtowncoder** [comment]
Ok I will need a stand-alone unit test of some kind, with assertions.
Or if anyone else has time to look, that'd help too; I'll tag this as "good first issue".

**Comment by Anusien** [comment]
So the first thing I notice is that the JSON has a field called `time_str` but your deserializers are looking for one called `timeStr`. Even after you fix that, you can make Jackson take the `time_str` field to power one of `part`/`minute`/`second` using `@JsonAlias`. But I can't find a way to make Jackson deserialize multiple fields using the same JSON property, if that's what you're asking.

**Comment by Tsyklop** [comment]
```
String timeStr = p.getValueAsString("timeStr");
```
My mistake. Should be `"time_str"`.

I find other way. I create deserializer for all class.

Thanks.

**Comment by cowtowncoder** [comment]
@Tsyklop that probably makes sense given that you want to handle it as whole. There are some convenience methods available via `DeserializationContext` like `readTree()` (to get current contents as `JsonNode`) and `readValue()` (if you want to read contents into intermediate container, or maybe just `java.util.Map`).

Good luck!

**Comment by Anusien** [comment]
If all these member variables are trivially derived from the same field, you could deserialize a more complex object, and then derive all those valuesfrom that complex object. In this case, it would probably be `java.time.LocalDate`.

**Comment by ashishkucheria** [comment]
> ```
> String timeStr = p.getValueAsString("timeStr");
> ```
> 
> My mistake. Should be `"time_str"`.
> 
> I find other way. I create deserializer for all class.
> 
> Thanks.

How did you fix it?

**Comment by Tsyklop** [comment]
> > ```
> > String timeStr = p.getValueAsString("timeStr");
> > ```
> > 
> > 
> > My mistake. Should be `"time_str"`.
> > I find other way. I create deserializer for all class.
> > Thanks.
> 
> How did you fix it?

I create own deserializer for class

**Comment by marciodevelopment** [comment]
I´m using a spring boot version 2.3.9.RELEASE and i´m have the same problem.

**Comment by lukasdo** [comment]
I had the same issue using spring boot version 2.5.6. I resolved it by adding a no arguments constructor to the POJO class.

The primary method for deserializing objects of the BeanDeserializer.java class the is using a flag called _vanillaProcessing. 
In my case without a no arguments constructor, _vanillaProcessing was disabled and another deserializer was used.
However with a no arg constructor _vanillaProcessing was enabled and my custom JsonDeserialize was triggered.
