### ISSUE TITLE
Large integer in scientific notation converted to float (with trailing .0)

### ISSUE THREAD

**Issue by GrahamHannington** [FasterXML/jackson-databind#2908]
Large integer values in scientific notation, such as `0.8590E+10`, get converted to floating-point values, such as `8590000000.0`, with a trailing `.0`.

I consider that trailing `.0` to be a bug.

The zeros before the decimal point are required to correctly represent the magnitude of the value. However, the trailing `.0` indicates a level of precision for which there is no evidence in the original scientific notation.

With apologies: I'm not sure I'm reporting this issue against the correct project.

I'm using Logstash, a component of the Elastic Stack. I believe Logstash uses Jackson to parse JSON.

I'm here after creating the Elastic discussion forum topic "[Logstash converts integer value in scientific notation to float, causing mapping error in Elasticsearch](https://discuss.elastic.co/t/logstash-converts-integer-value-in-scientific-notation-to-float-causing-mapping-error-in-elasticsearch/253396)".

A user on that forum replied:

> logstash uses a third-party library to parse JSON. Jackson, I believe. So the bug, if it is a bug, would be in the third-party library.

**Jackson version**

Based on what I read in the Logstash 2.9 [source](https://github.com/elastic/logstash/blob/7.9/versions.yml): jackson-databind 2.9.10.4

**Comment by cowtowncoder** [comment]
Unfortunately this description is not enough to understand what specifically you think is bug. The problem is that exactly how numbers are processed depends on usage. Numbers like `0.8590E+10` are always considered floating-point by Jackson, and that is by design (to determine they do not have fractional part requires pretty heavy computation), but they can be accessed as `double` or `BigDecimal`. Latter would probably work better for your use case.
And beyond internal representation there must be some additional processing for you to see `.0` (serialization of some kind).

So.... I'd need some sort of reproduction; ideally unit tests; that just uses Jackson and produces something you consider wrong.

**Comment by GrahamHannington** [comment]
Hi @cowtowncoder ,

Thanks very much for your reply.

You wrote:

> beyond internal representation there must be some additional processing for you to see .0 (serialization of some kind).

Yes. I see the `.0` in the serialized values output by Logstash.

I pass a value such as `0.8590E+10`, in JSON Lines, into Logstash. Logstash uses Jackson to parse that JSON. Logstash outputs the "expanded", parsed value `8590000000.0`.

The presence of a decimal point in the serialized representation of a number tells you something about that number. The decimal point tells you that the number does not represent a count. It tells you that the key can have fractional, non-integer values.

The addition of a trailing `.0` to an integer value is both unnecessary and, potentially, confusing.

Person 1: "How many children do you have?"
Person 2: "Two point zero."

There is nothing in the input value `0.8590E+10` to indicate a fractional precision level. By converting that value to `8590000000.0`, with a trailing `.0`, Jackson is confecting information. That's a bug.

That is, if Jackson is actually responsible. I don't know that for sure; there, I'm taking the word of Badger, the user on the Elastic discussion forum who replied to my topic reporting this behavior in Logstash.

> I'd need some sort of reproduction; ideally unit tests; that just uses Jackson and produces something you consider wrong.

Yes, I understand your position. You're a Jackson developer, you want a Jackson-only test case. For my part, I'm a Logstash user that only just found out Logstash uses Jackson. I'll have to think about that. I think I'd prefer to engage the Logstash developers; certainly, they ought to be interested in this. I'll contact them.

**Comment by GrahamHannington** [comment]
I've decided to stop digging this hole; doesn't seem worth the effort 🙂. As @kares pointed out, there are already easy fixes for this without changes to Logstash or its dependencies. Thanks for your time, @cowtowncoder.

**Comment by cowtowncoder** [comment]
@GrahamHannington Thank you for the update & all the work you did going through it. Things get "interesting" with all the layers involved...  and it is actually interesting to know what issues exist with integration. I suspect this may came up in some form at a later point, esp. with systems trying to work around Javascript limitations of 64-bit double being used for all values (as  I understand JS runtime semantics).
