### ISSUE TITLE
Make some java platform modules optional

### ISSUE THREAD

**Issue by XakepSDK** [FasterXML/jackson-databind#2910]
**Is your feature request related to a problem? Please describe.**
Jackson module descriptor implicitly depends on these modules:
1. `requires java.desktop`
2. `requires java.logging`
3. `requires java.sql`
4. `requires java.xml`
Can they become optional?

**Describe the solution you'd like**
Make these modules optional
1. `requires static java.desktop`
2. `requires static java.logging`
3. `requires static java.sql`
4. `requires static java.xml`
This may require some code changes, since making module optional means that module may not be present at runtime.
So code should check, if relevant classes are present.

**Usage example**
jlink and jpackage will produce smaller images. `java.sql` itself brings 10MB+ of dependencies, according to this https://github.com/google/gson/pull/1707#issuecomment-696492821

**Comment by GedMarc** [comment]
Remember that the benefits of going native imaging isn't so much the size as much as it is the new filesystem JRT, the new class loader, the encapsulated module paths and your 60% on average performance enhancements depending on your personal module structure.

That said, the reason why I left most of them as mandatory was to restrict the development to as small as possible with minimal impact. Java.desktop is enormous, the beanutils class is used from there and exists in the top most level databind. Java.logging will be in everywhere, that will always be present in your artefact.

My assumption was that size of the deployable would be the smallest concern granted all the other benefits you get by going modular, also when looking at what would usually be included in a module for a program that isn't hello world, it would be really weird to write something without java.sql 

I'll highlight each use case tonight, and why I left them mandatory, but on an overall perspective, to me a deployable for an ee scale app of 89mb was acceptable. :)

**Comment by GedMarc** [comment]
P.s. I did these implementations during the dev of guicedee, if you want to see total sizes of complete jlink apps try out www.guicedee.com xD

**Comment by XakepSDK** [comment]
@GedMarc my use case is desktop, so smaller image is better for me
@cowtowncoder 
> On practical terms, I am not sure if anything can or should be done for Jackson 2.x; users really do not like when things that used to work "suddenly start to fail". It'd probably be against SemVer too.
Things will not fail if user does not use module system, since all modules are present;
and if module system is used, then things wouldn't faill too, since jackson does not require `java.sql` or other modules transitively (`requires transitive module.name`)

If jackson did `requires transitive java.sql`, then changing it to `requires static` or just `requires` would be incompatible change, since `requires transitive java.sql` exports `java.sql` to jackson users

`java.logging` (`grep -rl "java.util.logging" .`):
```                          
./jsontype/impl/SubTypeValidator.java // entry in some list of strings, contains a lot classes from spring or other frameworks
./jsontype/DefaultBaseTypeLimitingValidator.java // entry in list of strings
./ext/beans/JavaBeansAnnotations.java // comment
```

`java.desktop` (package searched `java.beans`)
```
// INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES(true)
// if user of jackson does not depend on `java.desktop`, this feature is pointless,
// since calling code can not pass `java.beans.ConstructorProperties` or `java.beans.Transient`
./MapperFeature.java

// implementation of MapperFeature
./ext/beans/JavaBeansAnnotationsImpl.java
./ext/beans/JavaBeansAnnotations.java
./introspect/JacksonAnnotationIntrospector.java 

// a lot of tests, docs and package-info.java ommited
```

`java.sql`, `DateDeserializers` static block needs little change
```
./deser/std/DateDeserializers.java
./ser/std/SqlDateSerializer.java
./ser/std/SqlTimeSerializer.java
./ser/std/StdJdkSerializers.java
```

I have not checked `javax.xml` usages, but i think situation is same as with `java.sql`
```
./ext/CoreXMLDeserializers.java
./ext/XMLGregorianCalendarSerializer.java
./ext/OptionalHandlerFactory.java
./ext/DOMDeserializer.java
```

Looks like most of the code is ready to be turned in optional.
I think it is safe to switch from `requires` to `requires static` with some minor code changes.

Since jackson does not require these modules transitively, calling code definitely can't pass classes from those modules without explicitly requiring those modules.

note: i did not heavily checked anything, i just did some grep and checked code in vim, it took like 15min except writing this comment, it took more

**Comment by GedMarc** [comment]
@XakepSDK  thought I would show you this - The base module structure for JDK 9 is this 

![image](https://user-images.githubusercontent.com/5367513/97813325-09c97c80-1c90-11eb-8712-7938796a1cb8.png)

The java.bean package resides in java.desktop, and is used widely by everything - you'll find that i used the bottom levels to provide access - 

WRT Java 15 and records, the java.bean class already caters for the property reading of these classes, switching the BeanPropertySerializer for something else is a core change, @cowtowncoder  will need to say for here (fluent syntax property reading)

To do this I believe the modules will need to be defined more strictly for Jackson, I understand the hibernate module is going away, but to do this for you (remove java.sql, not java.desktop), but the Jackson modules will most likely be required to split out to a finer grain, maybe V3?
```
./introspect/JacksonAnnotationIntrospector.java 
```

**Comment by GedMarc** [comment]
hmm maybe using lombok's & mapstruct's property reader which support fluent and chaining.. but that would add an external dependency

**Comment by GedMarc** [comment]
Oh it's transitive because it's a base JDK library and used by all consumers of Jackson :) it's to make the modular pathway smaller, and not require consumers to define them as requirements :)
It makes the modular pathway much neater! And in native imaging, reduces module-info files a lot, this is important because of this bug

This is extremely important to use transitive! There is a 64kb limit on the final generated module-info, i would not recommend remove the transitive clause

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8240567

**Comment by XakepSDK** [comment]
> This is the core jackson class - i do not believe it will be changing any time soon
It shouldn't be changed at all, this class just weakly uses `JavaBeansAnnotations`, that's why it's listed
In fact, it already weakly implements usage of class `JavaBeansAnnotations`, so if `java.beans` class is missing for some reasons, it wouldn't fail.
`JacksonAnnotationIntrospector` uses `JavaBeansAnnotations`, `JavaBeansAnnotations` weakly loads `JavaBeansAnnotationsImpl`, `JavaBeansAnnotationsImpl` implements annotation processing and directly uses java.beans classes
```
    // NOTE: To avoid mandatory Module dependency to "java.beans", support for 2
    // annotations is done dynamically.
    private static final JavaBeansAnnotations _javaBeansHelper;
    static {
        JavaBeansAnnotations x = null;
        try {
            x = JavaBeansAnnotations.instance();
        } catch (Throwable t) { }
        _javaBeansHelper = x;
    }
```

**Comment by XakepSDK** [comment]
I believe that:
1. `java.desktop`, `java.logging` both can be safely switched to static right now
2. `java.xml` needs small rework in `./ext/OptionalHandlerFactory.java`
3. `java.sql` needs very simple change in  `./deser/std/DateDeserializers.java`

**Comment by GedMarc** [comment]
lets give it a try and see -

https://github.com/FasterXML/jackson-jdk11-compat-test

**Comment by GedMarc** [comment]
there's a few updates for Jakarta compatibility now that they've settled on module names i need to do as well

**Comment by XakepSDK** [comment]
Bruh, this whole time i was checking 3.0 branch. Branch 2.12 doesn't look worse. ± same level of work required

**Comment by XakepSDK** [comment]
I will test everything tomorrow and probably prepare PR if everything goes well

**Comment by cowtowncoder** [comment]
@GedMarc Jackson 2.12 has support for Java 15 Records without using any of JDK facilities beyond Java 7.

@XakepSDK Sounds good -- it'd be great to get PR soon as I am about to push 2.12.0-rc2 out, and getting this change there would be very useful wrt testing. I am trying to avoid having to do any further rcs before actual 2.12.0 goes out.

**Comment by GedMarc** [comment]
@XakepSDK - JAXB module references java.desktop, looks like I made a note in it - can you have a look?
https://github.com/FasterXML/jackson-modules-base/blob/6b7fea8b38d8f13208297d12edc6486ebc19f787/jaxb/src/moditect/module-info.java#L8

**Comment by cowtowncoder** [comment]
I think that usage:

                        if (name == null || MARKER_FOR_DEFAULT.equals(name)) {
                            name = Introspector.decapitalize(refType.getSimpleName());
                        }

might be relatively simple to replace. And probably was earlier replaced from `jackson-databind`, although not sure if that implementation (from... `BeanUtil`, I think) is available (2.12 tries to remove static functionality in favor of pluggable implementation for property name mangling).

**Comment by XakepSDK** [comment]
I need some help, more info in PR

**Comment by ryanthon** [comment]
Sorry to bring up an old issue, but I'm not seeing the changes for this in the compiled jars of any 2.12 release, even though the source changes are in the branch. Was it reverted?

**Comment by cowtowncoder** [comment]
@ryanthon I don't think so; I don't recall any reverts. 2.12.5 was released just recently.

**Comment by ryanthon** [comment]
Maybe I'm not looking at the right thing, but doesn't the module-info of the jar need to state "requires static" for the modules described in the OP? I'm not seeing that when I inspect it in IntelliJ.

When I use jdeps to list my dependencies, I'm still seeing java.sql and java.desktop in the output.
Do these changes simply mean that I no longer need to include java.sql and java.desktop when using jlink if I don't need them? jackson-databind is the only dependency I have that uses them.

**Comment by cowtowncoder** [comment]
@ryanthon Alas, those dependencies are needed due to oddities of JDK handling.

* `java.desktop` is, I think, needed for `java.beans` package: for `@ConstructorProperties` and `@Transient` annotations
* `java.sql` for couple of datatypes `java.sql.Date` / `Time` / `Blob`

These are quite tricky; support could be dropped/modularized away from databind in 3.0, but unlikely for 2.x.
In particular, I think `@ConstructorProperties` is widely used. Java SQL types is probably less of an issue, but even there it would be a breaking change for some users.

Other than that maybe @GedMarc can help here wrt "requires static".
