### ISSUE TITLE
JsonInclude.Include.NON_EMPTY is not used to suppress empty collections by default

### ISSUE THREAD

**Issue by rkatsyuryna** [FasterXML/jackson-databind#2917]
**Describe the bug**
While moving to new version where serializationFeature.WRITE_EMPTY_JSON_ARRAYS was deprecated, but new way is described: mapper.setSerializationInclusion(NON_EMPTY);

In com.fasterxml.jackson.databind.ser.PropertyBuilder we use deprecated feature to suppress empty collection by default
`default:
            // we may still want to suppress empty collections
            if (actualType.isContainerType()
                    && !_config.isEnabled(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS)) {
                valueToSuppress = BeanPropertyWriter.MARKER_FOR_EMPTY;
            }
            break;
        }`

**Version information**
Version 2.11.3

**To Reproduce**
If you have a way to reproduce this with:
use mapper.setSerializationInclusion(NON_EMPTY) for configuring mapper and see JSON is generated for empty collection (array) with value []

1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.

**Additional context**
Version 2.11.3

**Comment by cowtowncoder** [comment]
I would need a self-contained unit test here: I am not sure why `PropertyBuilder` would be related -- it is not something users would be expected to modify or have access to. But explanation alone is not sufficient to say whether behavior is expected or if there is a bug.

**Comment by rkatsyuryna** [comment]
yes simply slightly modify your test here CollectionSerializationTest.java:
` public void testEmptyListOrArray() throws IOException
    {
        // by default, empty lists serialized normally
        EmptyListBean list = new EmptyListBean();
        EmptyArrayBean array = new EmptyArrayBean();
        MAPPER.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
        assertEquals("{\"empty\":[]}", MAPPER.writeValueAsString(list));
        assertEquals("{\"empty\":[]}", MAPPER.writeValueAsString(array));

        // note: value of setting may be cached when constructing serializer, need a new instance
        ObjectMapper m = new ObjectMapper();
        MAPPER.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
        assertEquals("{}", m.writeValueAsString(list));
        assertEquals("{}", m.writeValueAsString(array));
    }`

**Comment by rkatsyuryna** [comment]
Not a bug
