### ISSUE TITLE
It would be useful if FAIL_ON_UNKNOWN_PROPERTIES (and all the FAIL_ONs) logged bad things when set to false

### ISSUE THREAD

**Issue by Yaytay** [FasterXML/jackson-databind#2919]
**Is your feature request related to a problem? Please describe.**
Currently using FAIL_ON_UNKNOWN_PROPERTIES = false causes the serialization to succeed silently, without giving any indication to the user that things might not be quite right.
When Jackson is used for config it's really important to know when things aren't as the user expects, but also important to keep going when unknown values are encountered.

**Describe the solution you'd like**
Three options, depending on how much effort should be put into it:
1. Add an else clause after ctxt.isEnabled(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES) and log in that.
2. Add another (set of) feature(s) DeserializationFeature.LOG_ON_UNKNOWN_PROPERTIES and and else if clause.
3. Add a callback that tells the caller about the problem and lets it do whatever it wants with the information.
I'll happily do a PR for whichever you'd prefer.

**Comment by cowtowncoder** [comment]
Jackson does not log anything using loggers, on purpose. This is a fundamental choice and will not be changed.

First I would suggest having a look at existing `DeserializationProblemHandler`: if you enable `FAIL_ON_UNKNOWN_PROPERTIES` you can make that skip value of unknown property as well as keep track of such properties.

Beyond that I am open to possible handler if existing functionality is not sufficient for some reason.

**Comment by Yaytay** [comment]
That is absolutely perfect.  Thank you.

**Comment by cowtowncoder** [comment]
Ok good!
