### ISSUE TITLE
Deserialize JsonObject json as String field

### ISSUE THREAD

**Issue by wuxingye** [FasterXML/jackson-databind#2923]
The json like:

```
{
	"functionId": "10012",
	"params": {
		"settleSubjectType": 0,
		"settleSubjectId": 0,
		"supplyOrderId": null,
		"settleFeeType": 0,
		"queryBeginDate": null,
		"queryEndDate": null,
		"functionId": "10012",
		"supplierId": "6206"
	}
}
```

But the object is 
```
    private String functionId;
    private String params;
```

It throws exception when deserialize

Can i deserialize it success by using feature?

thanks

**Comment by cowtowncoder** [comment]
Please use mailing lists or chat for usage questions:

* https://groups.google.com/g/jackson-user
* https://gitter.im/FasterXML/jackson-databind

But no, there is no feature to do something like that.
