### ISSUE TITLE
Method TreeNode.at("/") returns an empty node instead of the root node

### ISSUE THREAD

**Issue by VitorVilela7** [FasterXML/jackson-databind#2934]
Version tested: 2.11.2 -- the newer versions seems to be affected as well.

I'm currently working on a project that lets the client optionally filter the output though jsonpointer, however I noticed when you wanna return the whole JSON tree using the method at("/") located on TreeNode, you end up getting an empty node instead of the whole node.

It appears the cause is located on JsonPointer.java on the protected field _nextSegment, the methods compare they with 'null' while the root node (and the matching one) sets _nextSegment as JsonPointer.EMPTY.

Of course you can workaround by adding a conditional and don't call the "at" method in case the user input is "/" but I found it valid to report anyways.

Test case:
```java
    public class User {
        private String name;
        private Integer age;

        public User() { }
        public User(String name, Integer age) { this.name = name; this.age = age; }
        public Integer getAge() { return age; }
        public void setAge(Integer age) { this.age = age; }
        public String getName() { return name; }
        public void setName(String name) { this.name = name; }
    }

    private void testRootJsonPointer()
    {
        var mapper = new ObjectMapper();
        var testUser = new User("Mario", 23);
        
        System.out.println(mapper.valueToTree(testUser).at("/name").toString()); // prints 'Mario'
        System.out.println(mapper.valueToTree(testUser).at("/age").toString()); // prints '23'
        System.out.println(mapper.valueToTree(testUser).at("/").toString()); // prints ''
        System.out.println(mapper.valueToTree(testUser).toString()); // prints '{"name":"Mario","age":23}'
    }
```

**Comment by cowtowncoder** [comment]
Oh. No, this is invalid; you assume JSON Pointer `/` would mean "this node". This is not correct -- it means "property with key '' (empy String). What you want is

    mapper.valueToTree(testUser).at("")

I wish this was more prominently explained wrt JSON Pointer as it is not intuitively obvious, and I missed it myself when skimming through code above. It is specified in spec:

https://tools.ietf.org/html/rfc6901

if you are interested, in the main example.

Existing unit tests do actually cover this case too, but I'll bit more explicit tests

**Comment by VitorVilela7** [comment]
I see, that makes sense. Thank you for the clarification!
