### ISSUE TITLE
@JsonIgnoreProperties should support nested properties

### ISSUE THREAD

**Issue by Caceresenzo** [FasterXML/jackson-databind#2940]
**Is your feature request related to a problem? Please describe.**
It seems that there is no easy way to use the @JsonIgnoreProperties for nested properties.
A similar case was #690 but it seems there is no way to do it with annotation.

**Describe the solution you'd like**
Allowing a syntax with dots to go down a level with @JsonIgnoreProperties.

**Usage example**
```java
class A {
	
	int id;
	
	double value;
	
}

class B {
	
	String name;
	
	A anObject;
	
}

class C {
	
	@JsonIgnoreProperties({ "anObject.id" })
	List<B> aList;
	
}
```

Would produce a JSON like:
```json
{
	"aList": [
		{
			"name": "...",
			"anObject": {
				"value": 42.0
			},
		},
		{
			"name": "...",
			"anObject": {
				"value": 42.0
			}
		}
	]
}
```

**Additional context**
This will especially useful for JPA entities with bi-directional mapping, where you can directly return the instance without copying to model to filter some values.

**Comment by cowtowncoder** [comment]
The way Jackson serialization and deserialization work, this is not possible unfortunately.
I will leave this open for now but do not expect this to be implemented as suggested.

**Comment by Caceresenzo** [comment]
What would be a more reasonable approach? (with only using annotation)

**Comment by cowtowncoder** [comment]
I don't know if there is one, as limitation for immediate type in graph is quite fundamental restriction. `@JsonFilter` might allow something like this, but custom serializer would perhaps be needed (it could based checks on `JsonGenerator.getOutputContext()` to see relative location).

**Comment by Caceresenzo** [comment]
`@JsonFilter` only allow you to do it programmatically.

I was looking for an anwser that yould be useful coupled with Spring MVC.

**Comment by cowtowncoder** [comment]
No plans to ever implement this  (due to delegating design, will not be possible with current Jackson architecture), closing.
