### ISSUE TITLE
Inverse access of `@JsonProperty(access=)` so it can work differently on server side and client side

### ISSUE THREAD

**Issue by qianlong** [FasterXML/jackson-databind#2951]
@JsonProperty's access mode should be inversed on server side and client side when both sides are sharing the same module class.

when using access = READ_ONLY with @JsonProperty, on the server side, that means property need to be serialized but can't be deserialized. but on the client side, the same property should be able to be deserialized but not to be serialized.

Is it good to have an out-of-box feature to do this inversion?

**Comment by cowtowncoder** [comment]
Nothing to support it out-of-the-box, but you should be able to sub-class `JacksonAnnotationIntrospector` and override relevant methods to change the logic as necessary?

**Comment by cowtowncoder** [comment]
Implemented by addition of `MapperFeature.INVERSE_READ_WRITE_ACCESS`; will be included in 2.19.0.

**Comment by cowtowncoder** [comment]
Implemented for 2.19.0.

**Comment by yihtserns** [comment]
Just wondering (I do not personally ever need this because in all my projects my JSON classes are ser-deser, ser-only, or deser-only), but maybe this proposal should also consider the scenario where the same project use both "server-side" and "client-side" JSON classes? 🤔

**Comment by cowtowncoder** [comment]
@yihtserns Probably, but is there significance to this?
