### ISSUE TITLE
Problem with `JsonTypeInfo.As.EXISTING_PROPERTY`, `@JsonValue`/`@JsonCreator` combination

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#2953]
Looks like there is a regression in handling of polymorphic type that uses `@JsonAnyGetter` as well `as `EXISTING_PROPERTY` type id inclusion.
Failing test was provided by @carterkozak via #2952. 

NOTE: instead of `@JsonAnyGetter` it looks like the issue is rather with `@JsonValue`, `TypeSerializer`/`TypeDeserializer` access.

**Comment by cowtowncoder** [comment]
I don't think this is actual bug, although original test did show a difference in handling. I think (at this point) that this is a valid fix but that unfortunately earlier handling resulted in different behavior, and something that may have worked well for specific setup of things.

**Comment by cowtowncoder** [comment]
Since there is another test failure, leaving out for now, although no immediate plans for further work.

**Comment by cowtowncoder** [comment]
One last (?) note: I see why attempt was made to separate `EXISTING_PROPERTY` -- looks like handling of `FooWrapper` differs. But fundamentally this (ability to use different definitions of type info to include within a type hierarchy) is not a concept Jackson supports: all subtypes are expected to use the same type info definitions; this is a design constraint meant to support round-trip handling (since variation could be supported for serialization but not for deserialization).

**Comment by carterkozak** [comment]
The idea is that we define "union" types which are `oneOf` types, for example a union of "string foo" and "int bar" would allow json structured as the following:

`{"type": "foo", "foo": "string value of foo"}`
`{"type": "bar", "bar": 12}`
Or an unknown variant to safely deserialize types added after the client is generated, which is mapped to the special case Unknown variant:
`{"type": "anyUnknownString", "anyUnknownString": {/*anything*/}}`

I can take a look at how the old behavior could be implemented in 2.12, it will be problematic for older generated code though.

**Comment by carterkozak** [comment]
I've updated my code generator to stop adding `JsonTypeInfo` to the `UnknownWrapper`, use `EXISTING_PROPERTY` on the base type, and generate a new method on each of the known types:

```
        @JsonProperty(value = "type", index = 0)
        private String getType() {
            return "foo";
        }
```

This produces the expected results on both 2.11 and 2.12.

**Comment by cowtowncoder** [comment]
@carterkozak glad to know you were able to figure out a setting that works in both cases, as I realize that this is quite complicated use case. I hope we are getting closer to getting things to work consistently so such changes to observed behavior are not needed. Thank you very much for reporting these issues!

**Comment by cowtowncoder** [comment]
As per above discussion I think the new behavior is expected one and what is defined as "works as expected" form 2.12 onwards. Closing.
