### ISSUE TITLE
deserialize to static List<T> field get double repeat value

### ISSUE THREAD

**Issue by medlying** [FasterXML/jackson-databind#2963]
**Testcase**: 

```java
public class Test {
    private static final ObjectMapper MAPPER = new ObjectMapper();

    static {
        MAPPER.registerModule(new JodaModule());
        MAPPER.registerModule(new JodaTimeModule());
        MAPPER.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        MAPPER.configure(DeserializationFeature.ACCEPT_EMPTY_ARRAY_AS_NULL_OBJECT, true);
        MAPPER.configure(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT, true);
        MAPPER.configure(com.fasterxml.jackson.databind.SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    }

    protected static List<String> list = new ArrayList();

    protected static String str = "str";

    public List<String> getList() {
        return list;
    }

    public String getStr() {
        return str;
    }

    public static void main(String[] args) {
        Test test = new Test();
        test.getList().add("1");
        String jsonString = MAPPER.writeValueAsString(test);
        System.out.println(jsonString);
        Test test1 = MAPPER.readValue(jsonString, Test.class)
        System.out.println(test1.getList());
        System.out.println(test1.getStr());
    }
}
```

**Result:**
{"str":"str","list":["1"]}
[1, 1]
str

I am very confused why "list" value change to double repeat value. if execute "writeValueAsString" and "readValue" multiple times, each will double for the result

**Comment by cowtowncoder** [comment]
@medlying This looks accidental:

```java
    protected static List<String> list = new ArrayList();
```

since that does not make much sense. If it is intentional, you may want to read a Java tutorial explaining how `static` members work.

**Comment by medlying** [comment]
> @medlying This looks accidental:
> 
> ```java
>     protected static List<String> list = new ArrayList();
> ```
> 
> since that does not make much sense. If it is intentional, you may want to read a Java tutorial explaining how `static` members work.

my jackson-databind version is 2.10.5, in debug  model , to execute MAPPER.readValue(jsonString, Test.class) will first go to method :com.fasterxml.jackson.databind.deser.impl.SetterlessProperty#deserializeAndSet it will do this: toModify = _getter.invoke(instance, (Object[]) null); this step will get the 'list' value because in my case contains getter method. the second go to com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer#deserialize(com.fasterxml.jackson.core.JsonParser, com.fasterxml.jackson.databind.DeserializationContext, java.util.Collection<java.lang.String>){
       ...
       String value = p.nextTextValue();
                if (value != null) {
                    result.add(value);
                    continue;
                }
}
then the list will add the text value. so the result is double.So there is no way to avoid this problem except delete getter method?

**Comment by cowtowncoder** [comment]
@medlying Did you not even BOTHER TO READ MY COMMENT?!?!?!? If you don't even bother doing that, just go away. Your example is bad and you should feel bad.
Neither did you explain WHAT DO YOU SPECIFICALLY THINK IS THE PROBLEM but made a vague statement about duplication; code is using print statements instead of test assertions.
I hate to waste time on reports like this.

**Comment by medlying** [comment]
@cowtowncoder sorry to interrupt you, I certainly read your first comment. I apologize for my poor English expression skills!!!

**Comment by cowtowncoder** [comment]
@medlying Ok sorry for getting annoyed. I understand you tried to explain the issue.

My problem is that I am not sure I understand the problem: `static` member that is updated is not something you would normally use because every instance of `Test` will now update same List, not separate one.

**Comment by medlying** [comment]
@cowtowncoder yes, you are right. I try to describe the dilemma I encountered.

1. there is a class `AbstractQuery` in a java library that i can not modify.
@Data
public abstract class AbstractQuery {

    private static long MAX_PER_PAGE = 100;

    private static long MIN_PER_PAGE = 5;

    private static Long DEFAULT_PAGE_LIMIT = 20L;

    public static final String DEFAULT_SORT_BY = "create_ts";

    public static final String DEFAULT_SORT_ORDER = "desc";

    protected static final List<String> ALL_SORT_ORDER = new ArrayList<>();

    protected static final List<String> ALL_SORT_BY = new ArrayList<>();

    static {
        ALL_SORT_ORDER.add("desc");
        ALL_SORT_ORDER.add("asc");
        ALL_SORT_BY.add(DEFAULT_SORT_BY);
    }

    @ParamName("sort_by")
    protected String sortBy;
    @ParamName("sort_order")
    protected String sortOrder;

    @ParamName("page")
    protected Long page = 1L;
    @ParamName("page_limit")
    protected Long pageLimit = 20L;

    public List<String> getALL_SORT_BY() {
        return ALL_SORT_BY;
    } 
}
2.in my project there is a class `TaskQuery`
@Data
public class TaskQuery extends AbstractQuery {

    @ParamName("task_id")
    private Long taskId;

    @ParamName("route_id")
    private Long routeId;

    @ParamName("route_name")
    private String routeName;

    @ParamName("route_type")
    private Short routeType;
}
3.in my project, there is an API will invoke `taskServiceImpl.download`  as below
```
@Service
public class TaskServiceImpl {
    private static final ObjectMapper MAPPER = new ObjectMapper();

    @Autowired
    DownloadService downloadService;

    public void download(Long taskId, Long routeId, String routeName, Short routeType) {
        TaskQuery taskQuery = new TaskQuery();
        taskQuery.setTaskId(taskId);
        taskQuery.setRouteId(routeId);
        taskQuery.setRouteName(routeName);
        taskQuery.setRouteType(routeType);
        String jsonStr = MAPPER.writeValueAsString(taskQuery);
        downloadService.doDownloadLogic(jsonStr, TaskQuery.class);
    }
}

@Service
public class DownloadService {

    @Async("asyncTaskExecutor")
    private T void doDownloadLogic(String param, Class<T> paramClass) {
        ...
        MAPPER.readValue(param, paramClass); 
        ...
    }
}
```
after call API multiple times, `AbstractQuery.ALL_SORT_ORDER` will expand exponentially as you said every instance will update same List. In fact I don’t want to change the value of the `AbstractQuery.ALL_SORT_ORDER`. 

The solution I can think of is add @JsonIgnore in method  `getALL_SORT_BY` but it exist in library i can not modify. So can you give me some suggestions? 

There may also be others super class has `static` members like `ALL_SORT_ORDER`, if i can configure  like this
MAPPER.configure(DeserializationFeature.INGORE_STATIC_ MEMBER, true) be great if so.

I don't know whether i had explained clearly，if not , i am so sorry!!!

**Comment by cowtowncoder** [comment]
Static members are NEVER used for anything: they are fully ignored. Methods, fields. Access is not via static members.

However, when you have a getter method but no matching setter AND value type is `Collection` or `Map`, then value returned by getter is modified instead.

If you want to disable this behavior, disable `MapperFeature.USE_GETTERS_AS_SETTERS` (it is enabled mostly because it is what JAXB uses as well).

**Comment by medlying** [comment]
@cowtowncoder cool!! I think this is what I want, Thanks!!
