### ISSUE TITLE
CoercionConfig of LogicalType.EmptyString for Boolean types does not respect KotlinModule default settings.

### ISSUE THREAD

**Issue by jacinpoz** [FasterXML/jackson-databind#2964]
**Describe the bug**
In jackson-databind StdDeserializer.java you can find the following Coercion related code:

```{java}
        final CoercionAction act = _checkFromStringCoercion(ctxt, text,
                LogicalType.Boolean, Boolean.TYPE);
        if (act == CoercionAction.AsNull) {
            _verifyNullForPrimitive(ctxt);
            return false;
        }
        if (act == CoercionAction.AsEmpty) {
            return false;
        }
```
The problem with automatically assuming the boolean value to be "false" is that `KotlinModule` has a setting which allows null values to be automatically translated to property default values. See below:

```{kotlin}
    val kotlinModule = KotlinModule(nullIsSameAsDefault = true)
```
So if you have a data class with default values such as this:

```{kotlin}
    enum class LogLevel {
        TRACE, DEBUG, INFO, WARN, ERROR
    }

    data class MapperTest(
        val processName: String,
        val logLevel: LogLevel = LogLevel.WARN,
        val datadump: Boolean = true,
        val expiration: Int = 0
    )
```
You would expect an empty string for the "datadump" property to be deserialized to the default value "true", but instead it is deserialized to "false" because of the coercion logic shown above.

This works well with the "logLevel" enum property property though. When I pass a null value it is deserialized as the default value, which is `LogLevel.WARN`.

The coercion settings for ENUM are set like this and work as expected:
```{kotlin}
            objectMapper.coercionConfigFor(LogicalType.Enum)
                .setCoercion(CoercionInputShape.EmptyString, CoercionAction.AsNull)
```

The coercion settings for Boolean are set like this and *don't work as expected*.
```{kotlin}
            objectMapper.coercionConfigFor(LogicalType.Boolean)
                .setCoercion(CoercionInputShape.EmptyString, CoercionAction.AsNull)
```

**Version information**
2.12.0

**To Reproduce**
You can reproduce this issue by adding the relevant jackson 2.12.0 dependencies (databind and kotlin module) and running the unit test below:

```{kotlin}
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.cfg.CoercionAction
import com.fasterxml.jackson.databind.cfg.CoercionInputShape
import com.fasterxml.jackson.databind.type.LogicalType
import com.fasterxml.jackson.module.kotlin.KotlinModule
import org.junit.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class BooleanCoercionTest{
    enum class LogLevel {
        TRACE, DEBUG, INFO, WARN, ERROR
    }

    data class MapperTest(
        val processName: String,
        val logLevel: LogLevel = LogLevel.WARN,
        val datadump: Boolean = true,
        val expiration: Int = 0
    )

    @Test
    fun testBooleanCoercion(){
        val objectMapper = ObjectMapper()
        objectMapper.registerModule(KotlinModule(nullIsSameAsDefault = true))
        objectMapper.coercionConfigFor(LogicalType.Enum)
            .setCoercion(CoercionInputShape.EmptyString, CoercionAction.AsNull)
        // Coercion to null/empty Boolean
        objectMapper.coercionConfigFor(LogicalType.Boolean)
            .setCoercion(CoercionInputShape.EmptyString, CoercionAction.AsNull)
        val value = objectMapper.readValue("""{"processName":"NAME", "logLevel":"", "datadump":""}""",MapperTest::class.java)
        assertEquals(LogLevel.WARN, value.logLevel)
        // Expected the value to be "true" but it is "false"
        assertTrue(value.datadump)
    }
}
```

**Additional context**
Not sure if this issue should be raised in the kotlin module repo as well, happy to raise it there if it makes more sense.

**Comment by cowtowncoder** [comment]
It would probably make sense to report to Kotlin module: databind module has no visibility into extensions so it is often the case that extension modules will need some work to "adopt" new features.

**Comment by jacinpoz** [comment]
Ok, I reported the issue there as well. Thank you!

**Comment by cowtowncoder** [comment]
Since there is an issue on Kotlin side, closing this one as dup.
