### ISSUE TITLE
Interface deserialization

### ISSUE THREAD

**Issue by ArtjomProzorov** [FasterXML/jackson-databind#2965]
I have an a response object that always include response object as property and different types of values hence I have Interface in a class as a field, so that it would bring correct implementation based on some unique value identifier. 

    Could not execute the callcom.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class com.opngo.nowos.nowos.api.response.DataResponse]: missing type id property 'operation' (for POJO property 'response')
     at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 180] (through reference chain: com.opngo.nowos.nowos.NowOSResponse["response"])

Here is my Interface 

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "operation")
    @JsonSubTypes({@JsonSubTypes.Type(value = AuthResponse.class, name = "account_auth")})
    public interface IResponse {
        ///
    }
```

Here is one of the response objects that implements the interface mentioned above

```java
@RequiredArgsConstructor
    public class AuthResponse implements IResponse {
    
        @JsonProperty
        private final String accountID;
        @JsonProperty
        private final String authToken;
        @JsonProperty
        private final String language;
    }
```

Here is main Response that have that interface that should bring correct response object 

 ```java
public class NowOSResponse {
    
        @JsonProperty
        private final String operation;
        @JsonProperty
        private final String version;
        @JsonProperty
        private final IResponse response;
        @JsonProperty
        private final String status;    
    }
```

It looks like it does not look into the parent and searches for operation field in the AuthResponse which is of course empty since operation field is always present in parent and that parent have response -> AuthResponse ->CreateAccResponse and so on

**Comment by cowtowncoder** [comment]
I think I would need actual code, not just type definitions, to know what is being done.
And if the use case requires an external library (Immutables or Lombok?), I would also need post-processed classes, to know what class actually looks like during runtime.

**Comment by cowtowncoder** [comment]
No reproduction, cannot do much. May be reopened with a reproduction as per previous comment.
