### ISSUE TITLE
Regression: JsonTypeInfo lost when wrapped in object with JsonValue

### ISSUE THREAD

**Issue by merlinorg** [FasterXML/jackson-databind#2967]
Regression in Jackson 2.12.0 from 2.11.3 and prior: When a polymorphic type using `@JsonTypeInfo` is serialized inside a container using `@JsonValue` on a field of type `Object` the type info is not serialized.

In prior releases the type info was serialized as expected; the serialized form was the same whether wrapped or not.

```
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.ObjectMapper;

public class JT {
    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include= JsonTypeInfo.As.PROPERTY, property = "_type")
    public static abstract class Super {}

    public static class SuperCow extends Super {}

    public static class Wrapper {
        @JsonValue
        private final Object o;

        public Wrapper(final Object o) {
            this.o = o;
        }
    }

    public static void main(String[] args) throws Exception {
        final var om = new ObjectMapper();
        System.out.println(om.writeValueAsString(new SuperCow()));
        // {"_type":"JT$SuperCow"}
        System.out.println(om.writeValueAsString(new Wrapper(new SuperCow())));
        // {}
    }
}
```

**Comment by merlinorg** [comment]
Duplicate of issue #1840 except that it worked at some points between then and now.

**Comment by cowtowncoder** [comment]
The new behavior is fix to earlier, broken behavior: `@JsonTypeInfo` should always follow declared type, both for regular properties, and for `@JsonValue`. It is unfortunate that earlier handling deviated, leading to existing usage based on observed  behavior.

So this behavior is planned to remain as it is in 2.12.0.

**Comment by merlinorg** [comment]
👍
