### ISSUE TITLE
Can `Annotation` values be serialized?

### ISSUE THREAD

**Issue by mohanr** [FasterXML/jackson-databind#2987]
Is it feasible to serialize this ?
```
    public @interface Name{
        String getInterface() default "interface";
    }
```

**Describe the solution you'd like**

{"interface":"interface"}

**Comment by cowtowncoder** [comment]
Please do not ask usage questions on issue tracker: tracker is for:

* Reporting issues (unit test to show what is not working), OR
* Suggesting/requesting new features (if so, explain desired functionality or improvement) 

You may want to rephrase description to be in form for one of these.

For usage questions better places, for future reference, are:

* https://gitter.im/FasterXML/jackson-databind
* https://groups.google.com/forum/#!forum/jackson-user

As to whether annotations can be serialized, I have not tried doing that, but there is no way to deserialize them at least.
I am guessing that serialization might fail as there are no "getter" methods; but perhaps you could annotate properties with `@JsonProperty`?
