### ISSUE TITLE
Jackson Ser/Des implementation that allows to override the names of properties and other behaviors

### ISSUE THREAD

**Issue by casmeiron** [FasterXML/jackson-databind#2988]
**Is your feature request related to a problem? Please describe.**
No, not a problem.

**Describe the solution you'd like**
Imagine we have a class that we want to serialize using Jackson but we want to change the property name during ser/des, so I think it should be possible to extends some Ser/Des class that returns for every field the correct property name. The default implementation should fetch for @JsonProperty but a custom one could do something else to figure out the proper name.
That would be very nice!

**Usage example**

```
@Target( { ElementType.ANNOTATION_TYPE, ElementType.FIELD } )
@Retention( RetentionPolicy.RUNTIME )
public @interface MyCustomField {
    String name( ) default "";
}

public class Person {
    @MyCustomField("fullName")
    private String name;
}
```

In this example, when serialization occurs, I would like to override the behavior for property 'name', fetching the custom annotation, getting the 'name' and returning as property name that Jackson should use. Even though I have the access to the source code and I could simply put @JsonProperty there there are cases that I need also a custom annotation with the same value as JsonProperty so its redundant to use both of them, I should be allowed to provide to Jackson Ser/Des the property name to use instead of using @JsonProperty annotation.

**Additional context**
Add any other context about the feature request here.

**Comment by cowtowncoder** [comment]
@casmeiron If this a question on how to use Jackson, issue tracker is not the forum to use. Instead consider

* https://gitter.im/FasterXML/jackson-databind
* https://groups.google.com/g/jackson-user

This may sometimes lead to filing an RFE, or bug report, of course, but chat/mailing lists are better for discussions on usage.

**Comment by casmeiron** [comment]
Ok because I've searched through and to me its a new feature, 'cause I couldn't find a way of doing that.
I will close the issue anyway, thanks.

**Comment by cowtowncoder** [comment]
@casmeiron true, I can see it as a request for something for covering a use case -- I am not against this (you may reopen it) but it might be good to first ask for what solutions exist, and not many people read through issues. Based on responses may be you could update specifics on this one, for suggesting specific approach to configuration -- right now you are probably right that nothing like this exists: property names are very much static and there is no support for per-call changes (nor any plans to support anything like that).
But users do have ways of achieving the same effect with 2-phase processing (for example) and maybe others sharing their solutions on mailing list or chat could help.

**Comment by casmeiron** [comment]
Got it, I will check with users first, thanks very much!
