### ISSUE TITLE
Breaking API change in `BasicClassIntrospector` (2.12.0)

### ISSUE THREAD

**Issue by fdutton** [FasterXML/jackson-databind#2990]
Jackson 2.12 introduced a breaking change for users that have a custom ClassIntrospector.

**Version information**
2.12.0

**Additional context**
The method signature for constructPropertyCollector replaced the mutatorPrefix parameter with an AccessorNamingStrategy. This causes a runtime exception when the JVM cannot find the old method on BasicClassIntrospector. Reviewing the code shows several other breaking API changes.

**Comment by cowtowncoder** [comment]
Ok thank you. The original intent was for `ClassIntrospector` to be the API, and `BasicClassIntrospector` being implementation but not extension point of its own.
But I can see why in practice developers would be more likely to extend default implementation, and in hindsight it would have made sense to handle this the usual way via deprecation and call chaining.
And in fact some of comments already suggest extensibility ("overridable methods").
