### ISSUE TITLE
Can we release 2.12.1 earlier?

### ISSUE THREAD

**Issue by felipecrs** [FasterXML/jackson-databind#2995]
Hello there, 

Since 2.12.0 introduced an unintended breaking change, we are having a few issues in some Jenkins plugins, such as https://github.com/jenkinsci/docker-plugin/issues/821.

The issue was already fixed in jackson-databind 2.12.1-SNAPSHOT, but since it was not released yet, the Jackson 2 API plugin was not also.

Is it possible to accelerate the release of the jackson-databind 2.12.1, so we can release a new version of the Jenkins plugin and therefore unblock the issues that started to happen after the upgrade?

**Comment by cowtowncoder** [comment]
It's holiday season and I was originally planning to release 2.12.1 either first thing in January, or last thing in December.
(full patch release takes 2-4 hours of my time)
Since this appears to be common enough issue, I'll see if I can get released this before New Year (there may also be other issues in-flight, solution for which affects timing).

**Comment by felipecrs** [comment]
No problem, thanks so much for the support anyway! Happy holidays!

**Comment by cowtowncoder** [comment]
Thank you -- happy holidays to you too!

**Comment by hkhkhk1987** [comment]
any update for 2.12.1 release date?

**Comment by cowtowncoder** [comment]
Waiting for a fix for an issue with Blackbird module, hoping to have a look later today; that is the only blocker.

**Comment by TobiasMeyster** [comment]
Any news here?

**Comment by mprins** [comment]
2.12.1 was released 2 days ago
https://github.com/FasterXML/jackson-databind/releases/tag/jackson-databind-2.12.1

**Comment by cowtowncoder** [comment]
Yes sorry, forgot to update this ticket. 2.12.1 is out, as per:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12.1

**Comment by felipecrs** [comment]
Now, all we need is a new version of the https://github.com/jenkinsci/jackson2-api-plugin.

**Comment by TobiasMeyster** [comment]
do u see any chance that i will not have to deploy the plugin manually to jenkins until tommorow?
