### ISSUE TITLE
Do not trim before lookup enum values

### ISSUE THREAD

**Issue by TheWeaVer** [FasterXML/jackson-databind#3012]
In 2.12, there is a [trmming operations before lookup enum values](https://github.com/FasterXML/jackson-databind/blob/2.12/src/main/java/com/fasterxml/jackson/databind/deser/std/EnumDeserializer.java#L210-L217).
```java
    protected Object _fromString(JsonParser p, DeserializationContext ctxt,
            String text)
        throws IOException
    {
        CompactStringObjectMap lookup = ctxt.isEnabled(DeserializationFeature.READ_ENUMS_USING_TO_STRING)
                ? _getToStringLookup(ctxt) : _lookupByName;
        Object result = lookup.find(text);
        if (result == null) {
            String trimmed = text.trim();
            if ((trimmed == text) || (result = lookup.find(trimmed)) == null) {
                return _deserializeAltString(p, ctxt, lookup, trimmed);
            }
        }
        return result;
    }
```
It breaks backward compatibility.

So, I suggest of removing trimming or making a new option like `DeserializationFeature.TRIM_ENUM_VALUE_WHITESPACE`

Could you take a look??

**Comment by cowtowncoder** [comment]
@TheWeaVer So what specifically is the problem here? How did backwards compatibility change? (I assume from version 2.11)

**Comment by TheWeaVer** [comment]
@cowtowncoder Not only with other jackson version, but also the backwards compatibility with clients. :)

**Comment by cowtowncoder** [comment]
@TheWeaVer What I am asking is not theoretical problems there might be but what specifically is the problem you actually have?

**Comment by TheWeaVer** [comment]
@cowtowncoder We already met this problem. We have dependent on jackson enum deserializer to validate json represented by the enum object, however, by this change, we are going to make our custom enum deserializer for hadnling it.
I don't think that making custom enum deserializer is what you expected, so I make this issue. 🙂

**Comment by cowtowncoder** [comment]
@TheWeaVer I still do not know what the actual problem is, and if there is one more comment without any actual information, I'll just close the issue.
