### ISSUE TITLE
@JsonDeserialize Incompatible types

### ISSUE THREAD

**Issue by stringang** [FasterXML/jackson-databind#3014]
I need to write a custom Serializer for one of my entities "Performance" and I have to implement it by extending `StdSerializer`:

```java
@JsonDeserialize(using = PerformanceDeserializer.class) // compile error
public class Performance {
}

public class PerformanceDeserializer extends StdDeserializer<Performance> {

  public PerformanceDeserializer(Class<Performance> vc)  {
    super(vc);
  }

  @Override
  public Performance deserialize(JsonParser jsonParser,
      DeserializationContext deserializationContext) throws IOException, JsonProcessingException {
    // some logics
    return new Performance();
  }
}
```

**Version information**
    <jackson.version>2.10.2</jackson.version>

**compile error info**：

```
Incompatible types. Found: 'java.lang.Class<PerformanceDeserializer>', required: 'java.lang.Class<? extends org.codehaus.jackson.map.JsonDeserializer<?>>'
```

**Comment by cowtowncoder** [comment]
I think you are accidentally using Jackson 1.x types somewhere -- type `org.codehaus.jackson.map.JsonDeserializer` -- and must instead use Jackson 2.x equivalent (under `com.fasterxml.jackson.databind.` package).

**Comment by stringang** [comment]
> I think you are accidentally using Jackson 1.x types somewhere -- type `org.codehaus.jackson.map.JsonDeserializer` -- and must instead use Jackson 2.x equivalent (under `com.fasterxml.jackson.databind.` package).

Thank you for your reply, the problem has been successfully solved.
