### ISSUE TITLE
Looking for compatible for the Xamarin platform

### ISSUE THREAD

**Issue by naveenachar** [FasterXML/jackson-databind#3016]
Hello,

Having lot of runtime issues when I try to integrate Android AAR(archive) into Xamarin. 
1. AAR is dependency on Jackson library - Works fine without any issues in the Android platform.
2. Integrating Android application in the form library to Xamarin, where its has lot runtime issues in Jackson-databind lilbrary.

for example below are the some errors:
CS0534	'ParserBaseInvoker' does not implement inherited abstract member 'ParserMinimalBase.NextToken()'
CS0534	'ParserBaseInvoker' does not implement inherited abstract member 'JsonParser.GetTextCharacters()'

Just wanted to know any additional addons or supporting library need in the Xamarin platform? Looking for resolving runtime errors.

Thanks in advance

**Comment by cowtowncoder** [comment]
@naveenachar I am not familiar with Xamarin platform so I do not need what might be needed. Your best bet with Jackson usage is probably to ask on Jackson user mailing list:

* https://groups.google.com/g/jackson-user

but it might make sense to ask on Xamarin-specific forum; perhaps they could help.

From errors my only guess would be that perhaps you need to use specific version of Jackson. 2 methods mentioned, however, have been part of Jackson streaming API interface for a long time so maybe it is not a version issue.

**Comment by cowtowncoder** [comment]
Question was asked on mailing list; hoping some other developer can help with the issue there.
