### ISSUE TITLE
Provide better Moxy compatibility

### ISSUE THREAD

**Issue by nkiesel** [FasterXML/jackson-databind#3023]
Hi,

our project uses Jersey and tries to switch from Moxy to Jackson (2.12.1).  Most of this works beautifully.  However, we found one scenario where Jackson produces different JSON than Moxy:
```java
    public static class TaskResponse {
        @XmlElementWrapper(name = "items")
        @XmlElement(name = "task")
        public List<String> tasks;
}
```
is serialized as `{"items": {"task": ["task1", "task2"]}}` in Moxy but as `{"items": ["task1", "task2"]}` in Jackson.  I like the Jackson version better, but we have many existing clients which expect the Moxy variant.

Is there a Mapper or SerializationFeature or another annotation which will make Jackson produce the same output as Moxy?

**Comment by cowtowncoder** [comment]
No, unfortunately for your usage Jackson will only add wrapping for specific case of XML (although with JAXBAnnotationIntrospector wrapper name will be used to rename property).
There is a highly-voted for request to add `@JsonWrapped` annotation (to complement existing `@JsonUnwrapped`) which I think would allow such wrapping, but this has not been implemented.

**Comment by nkiesel** [comment]
Thanks for the reply and all your work on Jackson!

**Comment by cowtowncoder** [comment]
Thank you! It is too bad I couldn't help with this specific issue (it is bit tricky since even custom (de)serializer route would be challenging).
