### ISSUE TITLE
Serialization of "is" getters is no longer backward compatible.

### ISSUE THREAD

**Issue by treekt** [FasterXML/jackson-databind#3024]
As of version 2.12.0 the serialization of "is" getters is no longer backward compatible.

Previously, if there was an `isState()` method returning property `isState`, serialization was successful. From now on, if there is an `isState()` method, serialization looks for property `state`, not `isState` as well.

Previously, `state` or `isState` was found during serialization.
Is it possible to fix this?

Here link to this case in stackoverflow: https://stackoverflow.com/questions/65876901/serialization-problem-with-is-getter-to-property-name-in-jackson-databind

**Comment by cowtowncoder** [comment]
@treekt Please include a full test case here: description does not make sense as there should be no change to serialization logic of Java POJOs.

**Comment by cowtowncoder** [comment]
One other thing: there is one change in 2.12 that could potentially cause issues (added to allow Kotlin module to handle "isX" vs "x" discrepancy) -- it shouldn't break or change Java "isX" property handling and no problems have been reported, but maybe there is a specific sequence of events or settings that has problems.

**Comment by cowtowncoder** [comment]
As far as I can see, 2.12 works as expected. Methods "isState()" / "getState()" / "setState()" all infer property "state". If a field is to match, its name needs to be "state". If this is not the case, then `@JsonProperty` or equivalent is needed.
