### ISSUE TITLE
ObjectNode.with and ObjectNode.withArray mutates the object

### ISSUE THREAD

**Issue by rizsotto** [FasterXML/jackson-databind#3027]
**Describe the bug**

This is a code from `ObjectNode` class...

```java
public ArrayNode withArray(String propertyName)
{
    JsonNode n = _children.get(propertyName);
    if (n != null) {
        if (n instanceof ArrayNode) {
            return (ArrayNode) n;
        }
        throw new UnsupportedOperationException("Property '" + propertyName
            + "' has value that is not of type ArrayNode (but " + n
            .getClass().getName() + ")");
    }
    ArrayNode result = arrayNode();
    _children.put(propertyName, result);
    return result;
}
```

The line `_children.put(...)` mutate the object, which I don't think is a desired side effect.

If I would call this method with multiple `propertyName` which are not exists (so, `_children.get(...)` would return `null`) this code would grow the object size because it would insert values for each previously not existing keys.

**Version information**
2.12.1

**To Reproduce**
If you have a way to reproduce this with:

```java
public void test() throws JsonProcessingException {
	ObjectMapper objectMapper = new ObjectMapper();
	String json = "{ \"color\" : \"Black\", \"type\" : \"FIAT\" }";
	JsonNode jsonNode = objectMapper.readTree(json);
	for (int it = 0; it < 10_000; it++) {
		jsonNode.withArray(Integer.toHexString(it));
	}
}
```

**Expected behavior**
I would expect the code which inspect the JSON nodes is not mutating the object.

**Additional context**

**Comment by cowtowncoder** [comment]
I am not sure where you get your expectation: both `with()` and `withArray()` are expected to either use an existing Object or Array, respectively, or if one does not exist, create and add them.

This is what Javadoc says:

```
    /**
     * Method that can be called on Object nodes, to access a property
     * that has <code>Array</code> value; or if no such property exists, to create,
     * add and return such Array node.
     * ...
     */
    public <T extends JsonNode> T withArray(String propertyName) {
```

If you do not want anything to be created, you probably want to use `path()` method instead: it will not create anything, but in absence of a node will return "missing node" instance.
Or alternatively just `get()` which would return null.
