### ISSUE TITLE
Serializing list does not include type annotations

### ISSUE THREAD

**Issue by daw3rd** [FasterXML/jackson-databind#303]
This may be related to https://github.com/FasterXML/jackson-databind/issues/292, since you mentioned it may also have been related to Collections.  However, since I can't find the 2.2.4 snapshot for download to test on it or this new problem, I thought I should post here just in case.  I can serialize/deserialize a single DataValue and it includes the _type_ property to identify the type to deserialize back into, as follows

```
{
  "_type_" : "DataValue",
  "value" : "foo"
}
```

but when I try this with a List<DataValue>, the serialization does not include _type_ for the DataValue and it does something I would not expect with the ArrayList...

```
[ "ArrayList", [ {
  "value" : "name1"
 }, {
  "value" : "name2"
} ] ]
```

The full code is below.  My apologies if this is the same as the 292.  Either way, could you provide a URL for the snapshots?  Thanks.

```
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;

public class JacksonList
{
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type_")
@JsonSubTypes({ 
     @Type(value = ArrayList.class,                 name = "ArrayList"),
     @Type(value = JacksonList.DataValue.class,     name = "DataValue")
}
)
public static class Mixins {    }

public static class DataValue {

    public Object value;

    protected DataValue() { value = null; }

    public DataValue(Object value) {    this.value = value; }

    public String toString() { return  "(value=" + value + ")"; }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((value == null) ? 0 : value.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof DataValue))
            return false;
        DataValue other = (DataValue) obj;
        if (value == null) {
            if (other.value != null)
                return false;
        } else if (!value.equals(other.value))
            return false;
        return true;
    }
}

public static void main(String[] args) throws IOException {
    ObjectMapper mapper = new ObjectMapper();

    SimpleModule module = new SimpleModule(JacksonList.class.getName());
    module.setMixInAnnotation(JacksonList.DataValue.class, Mixins.class);
    module.setMixInAnnotation(ArrayList.class, Mixins.class);
    mapper.registerModule(module);

    testWriteReadObject(mapper, new DataValue("foo"), DataValue.class);

    List<DataValue> ldv = new ArrayList<DataValue>();
    ldv.add(new DataValue("name1"));
    ldv.add(new DataValue("name2"));

    testWriteReadObject(mapper, ldv, ArrayList.class);
}

private static void testWriteReadObject(ObjectMapper mapper, Object toTest, Class<?> objectClass)
        throws JsonProcessingException, IOException, JsonParseException, JsonMappingException {
    String json = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(toTest);
    System.out.println(json);
    Object o = mapper.readValue(json, objectClass);
    if (o.equals(toTest)) 
        System.out.println("Objects are equal");
    else
        System.err.println("Objects are NOT equal");
}
```

}

**Comment by daw3rd** [comment]
Ok so for anyone else that might be reading, below is something that gives me what I want.  I had to set the mixin type for Object.class (just so I can catch all classes easily) and then I preferred to programmatically register the DataValue subtype using ObjectMapper.registerSubtypes(). 

```
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;

public class JacksonList {

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type_")
public static class Mixins {    }

public static class DataValue {

    public Object value;

    protected DataValue() { value = null; }

    public DataValue(Object value) {    this.value = value; }

    public String toString() { return  "(value=" + value + ")"; }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((value == null) ? 0 : value.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof DataValue))
            return false;
        DataValue other = (DataValue) obj;
        if (value == null) {
            if (other.value != null)
                return false;
        } else if (!value.equals(other.value))
            return false;
        return true;
    }

}

public static void main(String[] args) throws IOException {

    ObjectMapper mapper = new ObjectMapper();
    mapper.registerSubtypes(JacksonList.DataValue.class);
    SimpleModule module = new SimpleModule(JacksonList.class.getName());
    module.setMixInAnnotation(Object.class, Mixins.class);

    mapper.registerModule(module);

    testWriteReadObject(mapper, new DataValue("foo"), DataValue.class);

    ArrayList<DataValue> ldv = new ArrayList<DataValue>();
    ldv.add(new DataValue("name1"));
    ldv.add(new DataValue("name2"));

    testWriteReadObject(mapper, ldv, ArrayList.class);

}

private static void testWriteReadObject(ObjectMapper mapper, Object toTest, Class<?> objectClass)
        throws JsonProcessingException, IOException, JsonParseException, JsonMappingException {
    String json = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(toTest);
    System.out.println(json);
    Object o = mapper.readValue(json, objectClass);
    if (o.equals(toTest)) 
        System.out.println("Objects are equal");
    else
        System.err.println("Objects are NOT equal");
}
}
```

**Comment by antemo** [comment]
We encountered a bit of a strange problem in our project.

We have something like this:


private class SomeClass<T> {

		private Map<T, List<Base>> someMap = new HashMap<>();

		public Map<T, List<Base>> getSomeMap() {
			return someMap;
		}

		public void setSomeMap(final Map<T, List<Base>> someMap) {
			this.someMap = someMap;
		}

	}

	@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
	@JsonSubTypes({
		@Type(value = StringExtendedBase.class, name = "stringBase"),
		@Type(value = IntegerExtendedBase.class, name = "integerBase")
	})
	private abstract class Base {

		private String field = "firstField";

		public String getField() {
			return field;
		}

		public void setField(final String field) {
			this.field = field;
		}
	}

	private class StringExtendedBase extends Base {

		private String field2 = "secondField";

		public String getField2() {
			return field2;
		}

		public void setField2(final String field2) {
			this.field2 = field2;
		}
	}

	private class IntegerExtendedBase extends Base {

		private Integer field2 = 42;

		public Integer getField2() {
			return field2;
		}

		public void setField2(final Integer field2) {
			this.field2 = field2;
		}
	}

When we fill SomeClass and try to send it with Spring RestTemplate, we noticed strange behavior. When we set log4j level to DEBUG, everything is serialized OK (type field is set for every element), but when we set log4j level to INFO, type field is not inserted.

What is causing this behavior, and how should we avoid it?

**Comment by dzklip** [comment]
Sad, @cowtowncoder : it is definitely and obviously a bug. The JSON for a list of objects should be exactly the same as the JSON for each object, separated by ',' and surrounded by '[', ']'.  The fact that you cannot deserialize List[Object] correctly is not an excuse for serializing List[Object] incorrectly. To state the obvious, deserialization might not happen in Jackson. It might happen in an environment where List[Tablature] is not type-erased into List[Object]. In fact, every single JSON produced by our web-service is deserialized in such an environment.

**Comment by cowtowncoder** [comment]
@dzklip You seem like a really arrogant person, with very strongly held and expressed opinions, with little backing facts. You are free to fuck off and bother some other project.

**Comment by OrangeDog** [comment]
Is there an annotation that can be put on a `List` property in order to trigger type inspection, or are `Object` mixin and `List` extension still the only ways to do it?

**Comment by korda** [comment]
Since this is high in search results when looking for this problem I want to add a simple workaround for those who for some reason can't get actual type in their context (code is in Kotlin, but should be easy enough to port to Java).

Please just note that this will impact performance - this trade off may or may not be acceptable depending on use case. 

```kotlin

public fun Any.writeAsJson(): String =
	if (this is Collection<*>) {
		val jsonArray = objectMapper.createArrayNode().addAll(
			this.map { objectMapper.valueToTree(it) }
		)
		objectMapper.writeValueAsString(jsonArray)
	} else {
		objectMapper.writeValueAsString(this)
	}
```
