### ISSUE TITLE
Optional<JSONNode> get() is throwing ClassCastException : class java.util.LinkedHashMap cannot be cast to class com.fasterxml.jackson.databind.JsonNode

### ISSUE THREAD

**Issue by abhupadh** [FasterXML/jackson-databind#3031]
Hi,

We are upgrading our project to latest version of Spring boot and spring and I am facing this issue while executing few tests

springboot (2.1.6 --> 2.3.6.RELEASE)
spring (5.1.9.RELEASE --> 5.2.8.RELEASE)
jackson-databind - 2.11.3
Java 11

**Comment by cowtowncoder** [comment]
There is no information here to help you unfortunately. Please include code you are using with input used -- ideally a simplified unit test.
