### ISSUE TITLE
Since 2.12.0 error: Type com.fasterxml.jackson.databind.PropertyNamingStrategies$SnakeCaseStrategy not present

### ISSUE THREAD

**Issue by investr777** [FasterXML/jackson-databind#3039]
Hi. If I use `@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy::class)` deserialization  is successful. But if I use - `@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)` deserialization is failed with error: `Type com.fasterxml.jackson.databind.PropertyNamingStrategies$SnakeCaseStrategy not present`.
Why?

**Comment by investr777** [comment]
I solved this problem.
I use only the dependency `com.fasterxml.jackson.module:jackson-module-kotlin:2.12.1`.
But if I will add: 
```
com.fasterxml.jackson.core:jackson-core:2.12.1
com.fasterxml.jackson.core:jackson-databind:2.12.1
com.fasterxml.jackson.core:jackson-annotations:2.12.1
```
Everything works.

**Comment by cowtowncoder** [comment]
Right, `PropertyNamingStrategies` was added in Jackson 2.12, in `jackson-databind`, so you probably had an older version of `jackson-databind` in classpath for some reason. This is bit odd as `jackson-module-kotlin` 2.12.1 should depend on 2.12.1 of jackson-databind too... but perhaps you depended on some other library that specified an older version.

There is `jackson-bom` (Bill of Materials) pom:

    https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom

that can give a full set of compatible versions which you may want to use via Maven import (if using Maven); not sure how it'd be used via Gradle. That could help eliminate unexpected discepancies without requiring you to explicitly specify every Jackson component (in this case dependency on Kotlin module would bring in annotations, core and databind properly).
