### ISSUE TITLE
Rename `SerializerProvider` as `SerializationContext`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#3043]
Something that should have been done during 1.x->2.0 major version upgrade but better late than never: due to historical reasons (serialization implemented before deserialization), context object naming is inconsistent. We have:

* `DeseralizationContext` for deserialization
* `SerializerProvider` for serialization

Latter may have made sense in 0.9.4 since the primary reason was access to child serializers (and this is still an importan use case); but conceptually it is a context object, and has expanded a lot in functionality.
So let's fix this naming discrepancy in 3.0.
(yes, this will result in lots of changes across the whole codebase)

**EDIT**: Related renaming:

* `JsonFormatVisitorWithSerializerProvider` -> `JsonFormatVisitorWithSerializationContext`

**Comment by cowtowncoder** [comment]
/cc @JooHyukKim @pjfanning @k163377 I will be doing this major renaming now for 3.0/master. Apologies for short term disruption. This is part of my focusing again on making 3.0 actual reality. Will try to keep everyone informed.

This work f.ex is part of [JSTEP-6](https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-6).
I will also try to update documentation.

**Comment by cowtowncoder** [comment]
So far I have update almost all modules, including Kotlin but not Scala (but I think @pjfanning is already doing or has done that). One remaining failure is for `jackson-datatypes-collection`, some odd code generation issue). But we are mostly done I think.

**Comment by JooHyukKim** [comment]
Great work on the work itself and for focusing on 3.0 version!
