### ISSUE TITLE
Bug in polymorphic deserialization with `@JsonCreator`, `@JsonAnySetter`, `JsonTypeInfo.As.EXTERNAL_PROPERTY`

### ISSUE THREAD

**Issue by martineaus83** [FasterXML/jackson-databind#3045]
I'm using Jackson for a while in simply way. I've just tried some more difficult tricks and I found a strange behaviour. 

When I've combined JsonCreator annotation with a JsonTypeInfo.As.EXTERNAL_PROPERTY resolver, then the result is not the same than if I had not put the @JsonCreator. 

My example is simple : I want to deserialize this String :

```
{ "time":345,
  "type":"track",
  "data":{"data-internal":"toto"}
}
```

My classes are
```

	public static class MyData {
		@JsonAnySetter
		public HashMap data = new HashMap();
		@Override
		public String toString() {
			StringBuilder buf = new StringBuilder();
			buf.append("[");
			Set<Entry> entrySet = data.entrySet();
			for (Entry e : entrySet) {
				buf.append("[").append(e.getKey()).append("=").append(e.getValue()).append("]");
			}
			buf.append("]");
			return buf.toString();
		}
	}

	public static class MyJson {
		private long time;
		private String type;
		private Object data;

		public MyJson() {
		}
		public long getTime() {
			return time;
		}
		public void setTime(long time) {
			this.time = time;
		}
		public String getType() {
			return type;
		}
		public void setType(String type) {
			this.type = type;
		}
		public Object getData() {
			return data;
		}
		@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "type")
		@JsonTypeIdResolver(ChildBaseByParentTypeResolver.class)
		public void setData(Object data) {
			this.data = data;
		}
	}

	public static class MyJson2 {
		private final long time;
		private String type;
		private Object data;

		@JsonCreator
		public MyJson2(@JsonProperty("time") long t) {
			System.out.println("MyJson2<init>");
			time = t;
		}
		public long getTime() {
			return time;
		}
		public String getType() {
			return type;
		}
		public void setType(String type) {
			this.type = type;
		}
		public Object getData() {
			return data;
		}
		@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "type")
		@JsonTypeIdResolver(ChildBaseByParentTypeResolver.class)
		public void setData(Object data) {
			this.data = data;
		}
	}

```
When I launch the the two deserialization, I have the next results 

```
content = {"time":345,"type":"track","data":{"data-internal":"toto"}}
MyJson result
time=345
type=track
data=class com.navalgroup.sdms.ac.model.impl.test.TestDeserialisation$MyData ; [[data-internal=toto]]

MyJson2 result
time=345
type=null
data=null

```

When I've got the sources and I've tried to debug the unexpected MyJson2 result, I've lost myself in BeanDeserializer.deserializeUsingPropertyBasedWithExternalTypeId. The Json datas seem to be put in TokenBuffer which doesn't seem used.

I attached a fully executed Java File with my test classes.
[TestDeserialisation.zip](https://github.com/FasterXML/jackson-databind/files/5931364/TestDeserialisation.zip)

Thanks for your attention

**Comment by martineaus83** [comment]
My Jackson version, for the test, is 2.12.0

**Comment by cowtowncoder** [comment]
Not sure what the problem might be, thank you for providing the reproduction code. I hope to have a look in near future but this may take a while.

The difference between `@JsonCreator` is likely buffering: without use of creator buffering is typically not needed (since instance can be created immediately and properties can be handled in any order), whereas with creator buffering is usually needed (to hold all arguments before calling constructor, if multiple arguments; or if type id does not come first in JSON). That in itself should not cause loss of contents so this definitely looks like a bug; but I just mention this as it is likely related.

**Comment by cowtowncoder** [comment]
Found one problem, fixed, but looks like there are multiple flawed code paths.
