### ISSUE TITLE
Allow serializing enums to lowercase (`EnumFeature.WRITE_ENUMS_TO_LOWERCASE`)

### ISSUE THREAD

**Issue by knyttl** [FasterXML/jackson-databind#3053]
**Is your feature request related to a problem? Please describe.**
Java enums are usually defined as `UPPER_CASE_WITH_UNDERSCORE`. This is not a standard in endpoints, as these rather use `lower_case_with_underscore`. There is already feature for `ACCEPT_CASE_INSENSITIVE_ENUMS`, which helps with deserialization, the feature for serialization is however currently missing. Only option is using `@JsonProperty` or `toString()` serialization.

**Describe the solution you'd like**
I would like to have `SerializationFeature.WRITE_ENUM_LOWERCASED`.

**Usage example**
Any API endpoint.

**Comment by knyttl** [comment]
See proposed PR.

**Comment by cowtowncoder** [comment]
I don't think I'll accept this as a `SerializationFeature` as it is little bit too specific (I know, there are some ENUM-specific ones already but I'd rather want to get rid of them).
But there probably should be separate `EnumConfig` / `EnumFeature` set for things to configure Enum handling with.

Or, alternatively, have something like `PropertyNamingStrategy` but for Enum values.

I'll keep this issue open but the solution will need to be something other than another `SerializationFeature` (which very likely also would require matching `DeserializationFeature`).

**Comment by cowtowncoder** [comment]
@kdankert I probably will not have time to work on this any time soon unfortunately. 

2.13 will be released whenever it might be ready: versions are not scheduled based on time. But before release there will be one or more Release Candidates and announcements will typically be sent on dev mailing list (as well as via `FasterXML` Witter account.).

**Comment by kdankert** [comment]
No problem, thanks for the update.

**Comment by ZeroOne3010** [comment]
So Jackson 2.14 is out and I'm unable to use this feature, the new `SerializationFeature.WRITE_ENUMS_LOWERCASED` enum value is not there yet. Should the label be updated or am I doing something wrong?

**Comment by cowtowncoder** [comment]
@ZeroOne3010 Unfortunately this feature did not make it in due to timing constraints, all the other work. I changed the label -- it is intended to show release targeted, but is not binding (i.e. aspirational, not constraining)

**Comment by ZeroOne3010** [comment]
@cowtowncoder OK, no worries, thanks for the clarification! I can wait. :)

**Comment by cowtowncoder** [comment]
Implemented via #3776.
