### ISSUE TITLE
Improve support for reactive streams parsing

### ISSUE THREAD

**Issue by symposion** [FasterXML/jackson-databind#3058]
Spring's WebFlux client uses Reactive Streams to support a non-blocking approach to web requests. There's a default Codec  that will parse JSON objects from the stream using Jackson, but it has some important (and non-obvious) limitations. In particular, it breaks object id resolution in Jackson. This is because reactive streams uses a push rather than a pull model, and Jackson provides no good support for this. The current implementation (https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/codec/json/AbstractJackson2Decoder.java) uses ObjectReader.readValue for each new JSON object, which works, but loses all the context - including previously resolved ids. 

ObjectReader has "readValues" which returns an iterator to support this sort of streaming use case, but it doesn't work for Reactive Streams which need to be able to push data into the reader rather than pull data from it.

The most obvious solution (to me) - which I believe would serve quite a few other uses cases as well - would be to allow callers to maintain and provide externalised context information that can optionally be passed in to calls to readValue. In this way the caller could control the scope of parser state rather than it always being scoped to the method calls on ObjectReader/ObjectMapper.

Alternatively, ObjectMapper/ObjectReader could have methods specifically designed to support the push stream use case; these could return some sort of callback interface that allowed clients to push new values in (as  JsonParser built on a TokenBuffer) but maintained state across calls.

**Comment by cowtowncoder** [comment]
Quick question: does reactive streams implementation use Jackson's non-blocking/async parsing?
Or does it still use blocking I/O based parsing?

**Comment by symposion** [comment]
It uses the new non-blocking stuff. See https://github.com/spring-projects/spring-framework/blob/29fb3f27bebc6e26c1854ce13ee60087f1739189/spring-web/src/main/java/org/springframework/http/codec/json/Jackson2Tokenizer.java

The basic parsing works great; I haven't tried it at scale yet but I assume it behaves as desired for a non-blocking streaming parser. The issue is at the databind level; there needs to be a way to maintain state - in particular Object Id bindings - across the entire stream. Allowing cilents more control over the scope of such state would also help with a bunch of other use cases. I have several times wanted to be able to pre-populate a parse-specific context of id->object before parsing a block of JSON and the current design makes this extremely hard to achieve without throwing away the entire ObjectMapper and starting afresh each time.

**Comment by cowtowncoder** [comment]
I understand the issue, but the life-cycle of `DeserializationContext` is fundamentally per-read and that is something I really do not want to change by exposing it outside of the databind package.
That is a conscious decision and saves a lot of potential trouble from maintenance side; similar to how I do not want to support recycling of `JsonParser`/`JsonGenerator` instances (but both can be used for reading over sequences of input)
So the wholesale replacement of state across calls is not something I am interested in supporting at this point.

But this is not to say that Object id life-cycle has to be similarly constrained; this aspect is something that has been requested earlier and I can see why it would be useful (... even if potentially risky...) to let that binding have scope beyond individual read/write calls (via ObjectMapper/-Reader/-Writer).

I am not sure how this can be done and am open to ideas; but one obvious place to look is probably `MappingIterator` (related to `readValues()`) as that has life-cycle of its own. Similarly for writing side there is the `SequenceWriter`.

So, if this can be scoped to specific pieces of state, I think issue can probably be addressed.

**Comment by symposion** [comment]
I figured that this was a conscious design choice. If I get a chance over the next few weeks I'll try to put together a PR that allows for managing the scope of the Object id separately from the deserialization context. I'll take another look at MappingIterator for some inspiration

**Comment by cowtowncoder** [comment]
@symposion Sounds good. Encapsulating Object Id mapping handling (likely needing to add some abstraction) would be a good thing overall. The challenge, as usual, is the backwards compatibility.

**Comment by symposion** [comment]
Which branch should I target?

**Comment by cowtowncoder** [comment]
2.13: cannot go in earlier (assuming it needs to extend API), `master` is for 3.0 which will still take a while.

**Comment by cowtowncoder** [comment]
No actionable things here; closing. May be re-filed in future as necessary.
