### ISSUE TITLE
Get JsonNode from String but not only JsonString

### ISSUE THREAD

**Issue by bradhuang9999** [FasterXML/jackson-databind#3073]
I know that we can convert JsonString to JsonNode By

```
ObjectMapper mapper = new ObjectMapper();
JsonNode actualObj = mapper.readTree(jsonString);
```

But my value is not only JsonString but also String
So I want to convert it correctly to specifiy type of JsonNode.

EX:
"abc" ==> TextNode
"123" ==> NumberNode
"{\"f1\":\"abc\",\"f2\":\"def\"}" ==> ObjectNode
"[{\"d1\":\"1_1\",\"d2\":\"1_2\"},{\"d1\":\"2_1\",\"d2\":\"2_2\"}]" ==> ArrayNode

It comes from parsing request parameters of front-end.
Because I don't want to force front-end to use contentType:application/json.
So I need to cover the ordinary request parameter.

**Comment by cowtowncoder** [comment]
I am not sure I understand the question here: `readTree()` will parse JSON into specific `JsonNode` sub-class and return that. So if content describes a JSON Object value, you will get `ObjectNode` and so forth. If you are certain of type, you can specify type in declaration like:

    ObjectNode rootOb = mapper.readTree(content);

otherwise you can get `JsonNode` and use methods to introspect

    JsonNode root = mapper.readTree(content);
    if (root.isObject()) { ... }

**Comment by bradhuang9999** [comment]
I want to write a method that can transfer "any" string but not only JsonString to JsonNode

ex: a new method call stringToJsonNode
stringToJsonNode("abc") will return a TextNode
stringToJsonNode("{"f1":"abc","f2":"def"}") will return a ObjectNode
stringToJsonNode("[{"d1":"1_1","d2":"1_2"},{"d1":"2_1","d2":"2_2"}]") will return a ArrayNode

 If I use readTree directly with not JsonString, it will throw an exception.
ex: mapper.readTree("abc") will throw an exception.

**Comment by cowtowncoder** [comment]
`YAMLMapper` (or rather `jackson-dataformat-yaml`) was moved here:

https://github.com/FasterXML/jackson-dataformats-text/

But I can't help you with non-JSON content to be read with JSON parser. There are other conversion libraries that can help with that I'm sure. Good luck!
