### ISSUE TITLE
bug: Jackson converts List objects like "[133]-[sid-tocqc]-[sid-zhiliang-test1]" which is not a json string, but the content of the List is [133], which is truncated

### ISSUE THREAD

**Issue by carlyin0801** [FasterXML/jackson-databind#3074]
Jackson converts List objects like "[133]-[sid-tocqc]-[sid-zhiliang-test1]" which is not a json string, but the content of the List is [133], which is truncated

**Comment by cowtowncoder** [comment]
@carlyin0801 Setting you want to enable is `DeserializationFeature.FAIL_ON_TRAILING_TOKENS`: this will force a check that after reading one value, no more content is available. It will then catch the problem of malformed token.

**Comment by carlyin0801** [comment]
Ok，thank you
