### ISSUE TITLE
Deserialization of wrappers with delegates doesn't advance the parser

### ISSUE THREAD

**Issue by jameskleeh** [FasterXML/jackson-databind#3077]
**Describe the bug**
The JsonParser is not advanced for delegate deserialization

This logic here https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/bean/BeanDeserializerBase.java#L1322 is in question

If the property based deserialization is used, the token is advanced here https://github.com/FasterXML/jackson-databind/blob/0f725e859936e102404fb1bbc9c55fa1555695ca/src/main/java/com/fasterxml/jackson/databind/deser/bean/BeanDeserializer.java#L559

For delegate deserializers, the token is never advanced and the wrong value is used. For example:

```
    @Introspected
    static class Wrapper {
        public final List<String> inner

        @ConstructorProperties(["inner"])
        @JsonCreator
        Wrapper(List<String> inner) {
            this.inner = inner
        }
    }

    @Introspected
    static class Outer {
        public final Wrapper wrapper

        @ConstructorProperties(["wrapper"])
        @JsonCreator
        Outer(Wrapper wrapper) {
            this.wrapper = wrapper
        }
    }
```

Introspected is a Micronaut annotation that triggers the usage of a module that reads and writes the values without reflection.

`objectMapper.readValue("{\"wrapper\":{\"inner\":[]}}", Outer.class)`

Results in `outer.wrapper.inner` being set to `["wrapper"]` instead of an empty list.

**Version information**
2.11

**To Reproduce**

- `git clone https://github.com/micronaut-projects/micronaut-core`
- `git checkout issue-5078`
- `./gradlew runtime:test --tests "io.micronaut.jackson.modules.BeanIntrospectionModuleSpec.test more list wrapping scenarios"`

**Expected behavior**
The list should be an empty list and the test should pass

**Additional context**
Here is our bean introspection module source https://github.com/micronaut-projects/micronaut-core/blob/2.4.x/runtime/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java

**Comment by cowtowncoder** [comment]
Hmmh. Code being pointed to is not actually equivalent to delegate case: `nextToken()` is indeed used to traverse over properties, but at the point deserializer gets called, parser does point to the first token and it should not be advanced.

But I wonder if the problem here is related to use of `@JsonCreator`? As shown, combination of `@JsonCreator` and `@ConstructorProperties` does imply PROPERTIES-style deserialization and not delegation.
To force use of delegation, you can still do

```
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
```

but otherwise existence of explicitly named parameters implies use of PROPERTIES.

**Comment by jameskleeh** [comment]
@cowtowncoder Is there anything I can do in the module to force that path?

**Comment by cowtowncoder** [comment]
Actually, now that I look at the example, I don't think it expects delegation.

But I also cannot reproduce this with a stand-alone test like so:

```
public class Issue3077Test extends BaseMapTest
{
    static class Wrapper {
        public final List<String> inner;

        @ConstructorProperties({"inner" })
        @JsonCreator
        Wrapper(List<String> inner) {
            this.inner = inner;
        }
    }

    static class Outer {
        public final Wrapper wrapper;

        @ConstructorProperties({"wrapper"})
        @JsonCreator
        Outer(Wrapper wrapper) {
            this.wrapper = wrapper;
        }
    }

    public void testIssue3077() throws Exception
    {
        final ObjectMapper mapper = newJsonMapper();
        Outer result = mapper.readValue("{\"wrapper\":{\"inner\":[]}}", Outer.class);
        assertNotNull(result);
        assertNotNull(result.wrapper);
        assertNotNull(result.wrapper.inner);
        assertEquals(0, result.wrapper.inner.size());
        System.out.println("RESULT:\n"+mapper.writeValueAsString(result));
    }
}
```

although test from the test repo does fail.

So I would suspect something going on with maybe custom deserializers, or serializers?

**Comment by cowtowncoder** [comment]
I also noticed that the repo depends on Jackson 2.11.2 -- it'd make sense to upgrade to the latest patch, 2.11.4, just to verify there are fixed bugs that could explain this. But my changing `gradle.properties` locally did not change the behavior so I don't think that matters here.

**Comment by jameskleeh** [comment]
The test without our module doesn't fail because it goes down the properties style path of deserialization

**Comment by cowtowncoder** [comment]
@jameskleeh From your example, I don't see why your code should not do the same though? Why should it switch to using delegation?

If you do want to force delegation, however, add the `mode = JsonCreator.Mode.DELEGATING` to `@JsonCreator`. 
But that would then except a different input: a simple JSON Array if both constructors are to use delegation.

**Comment by jameskleeh** [comment]
@cowtowncoder Because the line I linked above returns a deserializer https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/bean/BeanDeserializerBase.java#L1322

I don't control whether or not that deserializer gets created. It seems like if we declare we support creating from a delegate it happens automatically because of the methods we have overridden. https://github.com/micronaut-projects/micronaut-core/blob/issue-5078/runtime/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java#L407

**Comment by jameskleeh** [comment]
Just to clarify, I'm not saying this is a problem with Jackson. I just don't know how to move forward on this issue. Extending Jackson to allow for its usage without reflection is not a simple task and it seems like maybe we are missing something somewhere or doing something incorrectly. I am just at a loss to determine what that is

**Comment by cowtowncoder** [comment]
Yes, understood. I was about to suggest the same -- code you linked to is rather advanced by looks of it. And it does sound like there may well be something that is not advancing parser, and/or another deserializer that is not checking some constraints/invariants (leading it to accept tokens it should not, or assuming token of unacceptable type).

As usual I guess it'd be good to isolate the issue more. And while I don't expect Jackson version to matter a ton here, trying this against 2.12.2 (recently released) might be a good idea to see if there are differences.

**Comment by jameskleeh** [comment]
@cowtowncoder I'd really like to get this resolved quickly so I will create an example app that has the minimum amount of code to reproduce the issue using 2.12.2. I'll update this issue here later today

**Comment by cowtowncoder** [comment]
@jameskleeh Sounds good!

**Comment by jameskleeh** [comment]
@cowtowncoder Here you go https://github.com/jameskleeh/test-jackson-issue

You just need to run the main class and you can see the output. The method implementations are hard coded in the class to represent what would be returned in our case.

**Comment by cowtowncoder** [comment]
I am sorry, I do not follow what the implementation is trying to do. It is somehow mixing delegating- and properties-based creators (something that is not meant to be used, is not supported), ending up in odd state.

That it does not work is unfortunate; what I do not know how exactly it was meant to work, or why; or was even the idea.

I wish I could help here but you probably need to find whoever implement this code originally and maybe try to extract intent of what was being done.

**Comment by jameskleeh** [comment]
@cowtowncoder I got this figured out. The crux of it was `canCreateUsingArrayDelegate`. I don't understand the magic that is used to determine that, but simply delegating to the original implementation for that method seems to have resolved the issue, as well as returning false for `createUsingDelegate`.

**Comment by cowtowncoder** [comment]
@jameskleeh Ok I am very glad you were able to figure it out.

And yes, some things I can point out is that the expectation/constraint is that

* Delegating-case has precedence over properties-based one (so if you indicate delegate available, that is to be used)
* Array-delegate (relatively new addition, 2.9 maybe?) has precedence over general-purpose
* Calls between "canXXX" and matching accessors for using it are paired up
* No interaction planned across instantiation mechanisms (so mixing of delegate/properties-based not expected or supported)

I am guessing that array-delegate addition may have caused handling problems here.
