### ISSUE TITLE
`SORT_PROPERTIES_ALPHABETICALLY` is case-sensitive: capital letters sorted before lower-case

### ISSUE THREAD

**Issue by flyinghawker** [FasterXML/jackson-databind#3086]
Background: For signature verification, I need all fields sorted in absolute order from server to client.

Here is the basic code

```
    ObjectMapper mapper = new ObjectMapper();  
    mapper.enable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY);
    mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
    mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
    mapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss SSS"));
    String bodyString = mapper.writeValueAsString(data);
```

Inside my custom class, there is one boolean field called topped,  but it seems not placed in right place after sorting.
For example:

> {"chatPair":{"createdAt":"2021-03-23 16:53:43 825","id":19,"pairUser":{"createdAt":"2021-03-23 16:53:43 875","fromUserId":4,"id":"6059ac979aad5b48e05dfaa2","muted":false,"pairId":19,"relationType0":"Unknown","relationType1":"Unknown","screened":false,**"toUserId":5,"topped":false**,"updatedAt":"2021-03-23 16:53:43 875"},"updatedAt":"2021-03-23 16:53:43 709"}}

field **topped** is supposed to sit before field **toUserId**.
Field topped was declared as "boolean topped = false;" in my class, and no @JsonPropertyOrder set.

**Version information**
2.10.2

**Comment by cowtowncoder** [comment]
Although this is reported against an old version (2.10.2), and without providing actual class, I suspect I know the answer here. According to default Java lexicographic sorting, capital letters are sorted before lower-case letters (mentioned f.ex here https://www.baeldung.com/java-sort-string-alphabetically).

It would be possible to implement case-insensitive sorting, but at minimum documentation should state that "alphabetic" only works for same-case letters at this point.

**Comment by flyinghawker** [comment]
> Although this is reported against an old version (2.10.2), and without providing actual class, I suspect I know the answer here. According to default Java lexicographic sorting, capital letters are sorted before lower-case letters (mentioned f.ex here https://www.baeldung.com/java-sort-string-alphabetically).
> 
> It would be possible to implement case-insensitive sorting, but at minimum documentation should state that "alphabetic" only works for same-case letters at this point.

Thanks for your reply with detailed explanation and the idea is valuable.
But the issue seems still existing.
Here is part of the class:

```
@Data
@Document(collection = COLLECTION_CHAT_PAIR)
public class ChatPair  implements Serializable {
    private static final long serialVersionUID = 6982562610831496227L; 

    @Transient
    PairUser pairUser;  
    ...
}

@Data
@Document(collection = COLLECTION_PAIR_USER)
public class PairUser implements Serializable {
    private static final long serialVersionUID = -3417562536227199157L;
   ...
    Integer toUserId; 
    boolean topped = false; 
    ...
}
```
Based on your idea, I add config as such
```
 ObjectMapper mapper = new ObjectMapper();
            mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);//key按字典顺序排序
            mapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true);
            mapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true);
            mapper.configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES, true);
            mapper.enable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY);
            mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
            mapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss SSS"));
            String bodyString = mapper.writeValueAsString(data);
```
still  get sorted json with ... **"toUserId":5,"topped":false**...

**Comment by cowtowncoder** [comment]
Sorry, no, did not mean that there was any setting that would change this. Case-insensitive handling applies to mapping of external names to internal property names, but is not used for sorting currently.

**Comment by flyinghawker** [comment]
> Sorry, no, did not mean that there was any setting that would change this. Case-insensitive handling applies to mapping of external names to internal property names, but is not used for sorting currently.

Well,  that is another type of answer. I may need to change my naming policy to match Jackson style.  LOL
Thanks!

**Comment by flyinghawker** [comment]
> Sorry, no, did not mean that there was any setting that would change this. Case-insensitive handling applies to mapping of external names to internal property names, but is not used for sorting currently.

As gson in android and JSONEncoder in iOS  don't have such sorting rules, this specific rule may bring conflict between back and frond end. Hope certain solution could solve this difference.

**Comment by cowtowncoder** [comment]
Actually I think I'll re-open this since it does seem like something that would be good to improve for Jackson 3.0 (if not earlier). I am not saying that case-sensitive ordering is optimal, just that it is how things currently work -- so it should at very least be documented.
It is also not something that was consciously chosen but rather what JDK `String` default ordering does. Implementing case-insensitive ordering requires more work, and then the challenge is simply that doing this is a behavioral change, and some use cases (or at very least tests) probably assume that the current way is the way it will always work... and changing to case-insensitive could break other use cases.

So: thank you for bringing this issue to our attention. As I said I think it'd be good to improve upon, just needs to be thought out carefully wrt backwards compatibility.

**Comment by FelixVaughan01** [comment]
Hello, I'm trying to fix this issue, but am unsure where to add the needed modification as I'm a first time contributor. Would this be put in ObjectMapper.html?

**Comment by cowtowncoder** [comment]
@FelixVaughan01 Yes, I think that if a new on/off feature is needed -- which I think is true since there will be behavioral change -- it should be added as `MapperFeature`. This because although this mostly/only affects Serialization side of things, it is not something that can likely be changed on per-call basis (since sorting order is calculated when creating serializers, which are then cached; and not dynamically as-needed).
