### ISSUE TITLE
Classloader leak: DEFAULT_ANNOTATION_INTROSPECTOR holds annotation reference

### ISSUE THREAD

**Issue by BenICE** [FasterXML/jackson-databind#3093]
**Describe the bug**
After undeploying our application on a JBoss, we will face that the classloader cannot be garbage collected as a reference stays behind.
![grafik](https://user-images.githubusercontent.com/5716833/112753054-62e6d380-8fd6-11eb-961d-51e465c03444.png)

The static field DEFAULT_ANNOTATION_INTROSPECTOR keeps the JacksonAnnotationIntrospector alive which in turns holds a map which holds a Schema Annotation from a DTO. 
This leads to a classloader leak.

**Version information**
At least 2.11.4 & 2.12.2

**To Reproduce**
Tried it the last 2 days to make a mini project where it happens as well. Right now I can just reproduce it with our real application.
A simple spring boot app with DTOs annotated with io.swagger.core.v3.swagger-annotations does not do the trick.

Hope some of you can give me a hint where / why everything goes amiss.

**Expected behavior**
The classloader can be gced as no strong reference stays behind.

**Additional context**
Currently I solve it by registering a PreDestroy hook in a component that sets an empty LRUMap into _annotationsInside. Pretty much what was suggested here: https://issues.redhat.com/browse/WFLY-7037
This works...

**Comment by cowtowncoder** [comment]
Thank  you for reporting this. Yes, I think I can follow this... it may be challenging to reproduce but the mechanism looks clear enough. Probably it will be necessary to replace static singleton with a newly created instance: that is the right thing to do anyway, given that the annotation classes are very likely to come from different packages (as opposed to referencing Jackson's own annotations).

**Comment by BenICE** [comment]
(Un)fortunately this is no longer an issue and I was chasing a bug in 2.9.
JBoss is implicitly injecting an old Jackson library and is not using the explicitly bundled version (no clue why any software should use implicitly declared stuff over explicitly...but the JBoss team will have their reason).

I configured the JBoss to not inject any Jackson related stuff in our WAR, which solves the issue. So version 2.11.4 does not have the issue anymore.

Sorry for bothering you,

**Comment by cowtowncoder** [comment]
@BenICE Ok no problem.

**Comment by ciis0** [comment]
I think I am currently running into the issue.

![image](https://user-images.githubusercontent.com/16290850/215194874-2a8e6283-4f97-41ee-adb0-c4a8b49445aa.png)

![image](https://user-images.githubusercontent.com/16290850/215194593-11286558-eeb3-4e5d-84f9-6273a73a959b.png)

Maybe I'll be able to provide a minimal reproducible example.

**Comment by cowtowncoder** [comment]
@ciis0 If so, please file a new issue (which can refer to this one as background), including version information.
