### ISSUE TITLE
Support for retrieving incomplete string/bytes from an InputStream when EOF is reached

### ISSUE THREAD

**Issue by the-codinator** [FasterXML/jackson-databind#3098]
I have an InputStream which may have some additional characters at the end (incomplete json object string) which I want to retrieve after reading a bunch of json values.

To elaborate:
I have an InputStream for reading a large file, but due to throttling reasons, the InputStream sends and EOF after a pre-defined number of bytes are transferred. In other words, I have a large file, which lets me open InputStreams for reading 100MB or data at a time. When the 100MB limit is reached, the stream ends, and you need to create a new InputStream for the next "block" / "page".

Due to this model, the stream may end with a json object split across 2 blocks. I need to be able to handle this while reading.

I was referring to #1304 which helped me solve how to read values from an input stream.

Here's a small piece of code as an example

```java
        var json = "  {\"a\":{\"b\":[{\"c\":1}\n]}}   { \"a\" : 1}\n{ \"b\" : 1} {} {\"x";
        var input = new ByteArrayInputStream(json.getBytes());
        var reader = Util.getObjectMapper().readerFor(Object.class);
        var iterator = reader.readValues(input);
        Iterable<Object> iterable = () -> iterator;
        try {
            for (var x : iterable) {
                print(x);
            }
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
        print("Left: " + new String(input.readAllBytes()));
```

Here's the output of the above:

```
{a={b=[{c=1}]}}
{a=1}
{b=1}
{}
java.lang.RuntimeException: Unexpected end-of-input in field name
 at [Source: (ByteArrayInputStream); line: 3, column: 18]
	at com.fasterxml.jackson.databind.MappingIterator._handleIOException(MappingIterator.java:417)
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:203)
	at Scratch.main(scratch.java:24)
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in field name
 at [Source: (ByteArrayInputStream); line: 3, column: 18]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:662)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseEscapedName(UTF8StreamJsonParser.java:2020)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.slowParseName(UTF8StreamJsonParser.java:1925)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1709)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:766)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:707)
	at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:280)
	at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:199)
	... 1 more
Left: 
```

As can be seen, the entire stream has been consumed. Is there any buffer that Jackson stores this in to be able to retrieve from ?

I'm trying to retrieve the unresolved part of the InputStream and prefix it to the next one (using something like SequenceInputStream).

Any way I can do this ?

**Comment by cowtowncoder** [comment]
There is `JsonParser.releaseBuffered()` (two variants) that gives access to content read but not consumed by parser.
You may need to also wrap `InputStream` to prevent closing it (or use configuration to prevent closing it).

**Comment by the-codinator** [comment]
@cowtowncoder I tried what you mentioned, but it doesn't seem to do what it was supposed to...

Here's an updated code snippet:

```java
        var json = " { \"a\" : 1}  \n  {\"x"; // Continues with "\": 123 }"
        var input = new ByteArrayInputStream(json.getBytes());
        var reader = new ObjectMapper().readerFor(Object.class).without(Feature.AUTO_CLOSE_SOURCE);
        var iterator = reader.readValues(input);
        try {
            while (iterator.hasNextValue()) {
                try {
                    print(iterator.nextValue());
                } catch (JsonEOFException e) {
                    print("EOF: " + (input.read() == -1));
                    // Stream ended with incomplete json
                    ByteArrayOutputStream output = new ByteArrayOutputStream();
                    print("Parser: " + (iterator.getParser() == e.getProcessor()));
                    // iterator.getParser().releaseBuffered(output);
                    print("Bytes: " + e.getProcessor().releaseBuffered(output));
                    print("Buffer: " + output.toString());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace(System.out);
        } finally {
            print("Left: " + new String(input.readAllBytes()));
            input.close();
        }
```

with output:

```
{a=1}
EOF: true
Parser: true
Bytes: 0
Buffer: 
Left:
```

I would've expected it to be `Buffer: {"x` instead.

On inspection, I see both `_inputEnd` and `_inputPtr` inside `UTF8StreamJsonParser.releaseBuffered()` having the same value (19 in this case), and hence it returns 0 bytes.

Am I missing something ?

PS: I'm using v2.12.2 on Java 11.0.10

**Comment by cowtowncoder** [comment]
@the-codinator This sounds like a possible bug; your usage looks correct and output odd. I'll add this to things I hope to investigate soon.

**Comment by the-codinator** [comment]
@cowtowncoder I see. Could you confirm the right underlying buffer and pointer in the UTF8StreamJsonParser that should be holding the right values?

I'll try working on a PR by cross-referencing the functionality with other Parser implementations.

**Comment by cowtowncoder** [comment]
@the-codinator yes `_inputPtr` and `_inputEnd` would indicate range of content.

However. Now that I look at test again, there's a reference to EOF exception -- if that occurs, there would not be any content in buffers, by definition. At that point parser has read and consumed all content.
Once input has become `JsonToken`s, it is not buffered in input buffers.

So I think I misunderstood the issue here. To solve this problem, you might need to actually buffer token content. That can definitely be done with `TokenBuffer`, for example, but that adds overhead and complexity (you would try to read a balanced sequence of input into buffer first, then "read" from buffer; or if there is end of input, read and combine).

**Comment by the-codinator** [comment]
@cowtowncoder I get what you're trying to say, and I'm trying a few things to make this work.
Could you help me with some docs around using TokenBuffer? I understand what its supposed to do, but I was unable to find any useful usage examples for reference...

Here's a few ideas I'm trying:

- Buffer the `JsonToken`s somehow using `TokenBuffer` and recreate (a semantically equivalent representation of) the incomplete json part from the `InputStream`. -OR- Is there a way I can get the tokens currently parsed from the InputStream by the Parser ? This will require working with the Parser directly, rather than high level APIs of `ObjectReader`
- Is there a way I can get (from each read) the number of bytes that were consumed in producing the `value` from `iterator.nextValue()` ? If I have this, I can Buffer the InputStream and use (InputStream's) mark/reset or something similar to get back the tail bytes representing the incomplete json
- Is there a way I can disable buffering of bytes inside of the Parser ? This way I would know that after each read (`iterator.nextValue()`), the `InputStream` would've progressed only as much as is necessary to extract a complete json value (stops at the `END_OBJECT` token). Again, I can then solve the problem with a `BufferedInputStream` and mark/reset.
- Is there a way I can know how many bytes are currently buffered in the Parser (it won't be elegant, but I can probably hack this via reflection). And again use mark/reset

PS: Any kind of buffering I try to do will fall into the loophole of having to manage its size to be able to hold required number of bytes, but that's something I can try to deal with separately - using a dynamic length buffer, or using a large fixed size buffer greater than the length of any json object. If I'm working with `JsonToken`s, then `TokenBuffer` would be an optimized buffer I can use.

I see `TokenBuffer.copyCurrentStructure(JsonParser)`, but that just copies only unused tokens, whereas the Parser I have has already consumed the tokens)

Any tips for the above would be greatly helpful...

Also, what do u think about adding this use-case as a feature in Jackson Streaming APIs (may be some time in the future) ?

**Comment by cowtowncoder** [comment]
I am sorry but I am not sure you can actually achieve what you want, if I understand the problem correctly.
At least not via blocking API. I'll elaborate on alternative after explaining the problem.

Assuming that the input can be split at ANY position, this may split a token, like:

```
{ "name":"va
lue", "another
":"value" }
```

`JsonParser` will try to read a token, consume input, and then fail; there is no way to retrieve this, nor will there be a token (one cannot be created since information simply does not exist in stream).

Trying to keep track of such consumed content would be difficult, inefficient, and serving niche use cases.
But even if it would be doable in example above, it is not generally doable: Jackson uses fixed-length buffers for input and if token is split across buffer boundary, that makes it impractical to even attempt keeping it all available (consider a long text segment with length exceeding input buffer).

There may be a way to actually achieve this using non-blocking ("async") parsing. It is briefly explained on:

https://cowtowncoder.medium.com/jackson-2-9-features-b2a19029e9ff

but the idea is that if you can feed content as `byte[]` blocks, you can check whether one more token can be decoded; if so, you access it via `JsonParser` regular way. If not, you need to feed more content.

Still, this would let you get tokens and still need buffering.

`TokenBuffer` implements `JsonGenerator` so you can use `JsonGenerator.copyCurrentToken()`. And later on, create `JsonParser` from `TokenBuffer` as well.

It all gets very complicated and it is questionable if that is in the end doable or worth the hassle.
I don't think it is reasonable to expect that streams can be randomly split and that system needs to be able seamlessly recover.

**Comment by the-codinator** [comment]
@cowtowncoder I was trying out the non-blocking version to feed bytes, but it gets very complex, especially since you need to parse the tokens to value yourself (since `asyncParser.readValueAs()` is not supported), or Buffer the tokens and check for balanced json and then read its value (making it inefficient).

I've been tinkering on this a bit more now, and I thought of the following:
- Create an `ObjectReader` or `JsonParser` and correspondingly a `MappingIterator` for the input
  - `mapper.readerFor(Object.class).readValues(inputStream)`
  - `mapper.createParser(inputStream).readValuesAs(Object.class)`
- before every `iterator.nextValue()` store the current bye offset of the stream `iterator.getCurrentLocation().getByteOffset()` (can get current location from `JsonParser` too). This would give me the total number of bytes consumed from the Stream (so far) to produce **valid** values.
- Use this in conjunction with something like a `CountingInputStream` from [apache commons-io](https://github.com/apache/commons-io/blob/master/src/main/java/org/apache/commons/io/input/CountingInputStream.java) or [google guava](https://www.google.com/search?client=firefox-b-d&q=nonblockingjsonparser) to get the total number of bytes read (wrap the original `inputStream` with this). With this, I now have the number of "unprocessed" bytes (`N`).
- Now I can handle the incomplete json bytes in the following ways:
  - on `JsonEOFException`, indicate to the system that the next `InputStream` to be created, should start `N` bytes earlier. This offloads the complexity to the InputStream creation logic which needs to support this requirement.
  - assuming you know the max json size, create a `Queue` like `OutputStream` to store the bytes (maybe something like a circular byte array) and use `TeeInputStream` from [apache commons-io](https://github.com/apache/commons-io/blob/master/src/main/java/org/apache/commons/io/input/TeeInputStream.java) to store a copy of every read byte. The last `N` bytes will be what you want when you hit the `JsonEOFException`.

Does the above sound OK to you? I'm mainly looking for confirmation on `getCurrentLocation().getByteOffset()` being the total number of bytes consumed to produce `JsonToken`s for an `InputStream`, and that `iterator.nextValue()` guarantees that only as many bytes as consumed as required to create a valid Json element - no additional unused chars are consumed, i.e. un-consumed bytes are left in internal buffer for future consumption, with location pointing to first un-consumed byte.

**Comment by cowtowncoder** [comment]
I think that sounds like a possible way to try to do it. Biggest caveat is that while Jackson's parsers do try to keep offsets in sync, there only has to be one path where things go wrong to throw the offset off.
So it'd probably be good to test this well, with system that plays feeds with various edge conditions to verify it at least appears to work.

I would not count on consumption of content but just location offsets calculated after successfully decoded value, and use that then to keep track of input stream (and replay as necessary).

**Comment by the-codinator** [comment]
Thanks, your concern is very true. Any path that circumvents the counting operations (even unintentionally) will instantly cause failures in the entire logic. This approach is highly dependent on the reliability of said counts.

I will thoroughly test this with our actual use-case to make sure it works. Simultaneously, I'll continue checking for possibly more reliable alternatives.

**Comment by cowtowncoder** [comment]
While there is on-going work, I think this specific issue turned out to be bit of misunderstanding between what can be retrieved (non-consumed content) and what would be expected (all content for which token has not been produced, including possible partial token content consumed and indicated in exception message).
