### ISSUE TITLE
Enum desarialization fails in Jackson-databind 2.11.4 (with Spring Boot)

### ISSUE THREAD

**Issue by KamilWitkowski7** [FasterXML/jackson-databind#3100]
ObjectMapper config:
```
public abstract class ObjectToJsonConverter<T> implements AttributeConverter<T, String> {

    private final ObjectWriter objectWriter;
    private final ObjectReader objectReader;

    public ObjectToJsonConverter () {
        ObjectMapper objectMapper = new JacksonConfiguration().objectMapper();
        objectWriter = objectMapper.writer();
        objectReader = objectMapper.readerFor(getTClass());
        objectMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
        objectMapper.configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL, true);
    }

    @Override
    public String convertToDatabaseColumn(T attribute) {
        try {
            return attribute != null ? objectWriter.writeValueAsString(attribute) : null;
        } catch (JsonProcessingException e) {
            handleJsonProcessingException(e);
        }
        return null;
    }

    @Override
    public T convertToEntityAttribute(String dbData) {
        try {
            return isNotBlank(dbData) ? objectReader.readValue(dbData) : null;
        } catch (IOException e) {
            handleIOException(e);
        }
        return null;
    }



    protected void handleJsonProcessingException(JsonProcessingException e){
        log.error("Error occurred while serializing JSON for object of class: " + getTClass(), e);
        throw new ObjectToJsonConvertingException(getTClass(), e);
    }

    protected void handleIOException(IOException e){
        log.error("Error occurred while deserializing JSON for object of class: " + getTClass(), e);
        throw new ObjectToJsonConvertingException(getTClass(), e);
    }

    public abstract Class getTClass();
}
```

In class `ObjectMapper.java` from `jackson-databind-2.11.4.jar`

```
    public <T> T readValue(String content, JavaType valueType)
        throws JsonProcessingException, JsonMappingException
    {
        _assertNotNull("content", content);
        try { // since 2.10 remove "impossible" IOException as per [databind#1675]
            return (T) _readMapAndClose(_jsonFactory.createParser(content), valueType);
        } catch (JsonProcessingException e) {
            throw e;
        } catch (IOException e) { // shouldn't really happen but being declared need to
            throw JsonMappingException.fromUnexpectedIOE(e);
        }
    } 
```

When content is: 
`{"a":"2(...)","operationResult":"OK","s":1,"decodeStatusMessage":"OK","errorMessage":"No errors","logErrorMarker":"No log errors marker"}`
    
valueType is:    
[simple type, class java.lang.Enum]
class (...).OperationResult

```
public enum OperationResult {
    @JsonProperty("OK")
    OK("OK"),
    @JsonProperty("ERROR")
    ERROR("ERROR");

    private String value;

    OperationResult(String value) {
        this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static OperationResult fromValue(String text) {
        for (OperationResult b : OperationResult.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        return null;
    }
}
```
    
I get an exception:

> error: c throw: Could not read JSON: Cannot deserialize instance of `pl.(...).OperationResult` out of START_OBJECT token
>  at [Source: (String)"{"a":"2(...)","operationResult":"OK","status":1,"decodeStatusMessage":"OK","errorMessage":"No errors","logErrorMarker":"No log errors marker"}"; line: 1, column: 1]; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `pl.(...).OperationResult` out of START_OBJECT token
>  at [Source: (String)"{"a":"2(...)","operationResult":"OK","status":1,"decodeStatusMessage":"OK","errorMessage":"No errors","logErrorMarker":"No log errors marker"}"; line: 1, column: 1]

c is method.
The issue occured after upgrading SpringBoot 1.5.x to 2.3.9 and jackson databind upgraded due that to version 2.11.4 from version 2.8.11.2.

On version 2.8.11.2, before changing SpringBoot etc. i checked that method `readValue` was not called using the same test.

StackTrace from version 2.11.4 and this error:

> at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:237)
> 	at org.springframework.cloud.stream.converter.ApplicationJsonMessageMarshallingConverter.convertFromInternal(ApplicationJsonMessageMarshallingConverter.java:110)
> 	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:182)
> 	at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:70)
> 	at org.springframework.cloud.stream.config.SmartPayloadArgumentResolver.resolveArgument(SmartPayloadArgumentResolver.java:115)
> 	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117)
> 	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:148)
> 	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116)
> 	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
> 	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:134)
> 	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:62)
> 	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
> 	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
> 	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
> 	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
> 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
> 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)

**Comment by KamilWitkowski7** [comment]
The weird behavior occurred only after upgrading SpringBoot in a specific area.

Someone make weird mistake in code like that:

    @StreamListener(A_OUTPUT)
    public void a(String a) {
        eventSender.sendAtLeastOnceAfterCommit(A_OUTPUT, a); 
}


Commenting line:
@StreamListener(A_OUTPUT)

fixed the issue.

**Comment by cowtowncoder** [comment]
I am not sure there is anything Jackson can do here: if there is a remaining problem (it sounds like possibly not, but wasn't 100% sure), a Jackson-only reproduction would be needed. May be reopened with such reproduction, if necessary.
