### ISSUE TITLE
Bringing Java 6 support back

### ISSUE THREAD

**Issue by smola** [FasterXML/jackson-databind#3104]
**Is your feature request related to a problem? Please describe.**

I use an in-house jackson-databind fork with JDK 6 support. The required changes are relatively non-invasive, but it'd be great if these fit upstream.

**Describe the solution you'd like**

Example of JDK 6 porting for jackson-databind 2.12.2:
https://github.com/smola/jackson-databind/commit/979a747cb56f6a3c8b76fae0f9a73f8c3d814ae0

Is this something you would consider as a contribution to jackson-databind 2.x?

**Comment by cowtowncoder** [comment]
Thank you for the offer, but at this point I am not interested in adding back workarounds for Java 6 use case: Java 7 has been the baseline for databind since Jackson 2.8.

Jackson 2.13 will increase baseline to Java 8.

**Comment by smola** [comment]
@cowtowncoder Thanks. I can't blame anyone for not supporting Java 6 in 2021 :joy: 

We'll maintain this fork for the foreseeable future.

**Comment by cowtowncoder** [comment]
@smola Right, I do try to be cautious about baseline increases, but also once the change is made it becomes harder and harder to justify going back. Thank you for the offer tho. And if you happen to notice regressions in `jackson-core` let me know: it is planned to remain Java 6 for 2.x.
