### ISSUE TITLE
Deserialization: How to skipp null values for a Map<String,Object> in jackson 2.9

### ISSUE THREAD

**Issue by JayChandler** [FasterXML/jackson-databind#3107]
Hello

It seems **JsonInclude.Include.NON_NULL** only works for serialization to prevent writing null values. I did not find a way to get the same behaviour when deserializing a map. 

There is a boolean flag __skipNullValues_ in **ContainerDeserializerBase** but for a map it always seems to be false?

How can i do that?

**Comment by cowtowncoder** [comment]
Check out `@JsonSetter` with `contentNulls property, added in 2.9:

https://cowtowncoder.medium.com/jackson-2-9-features-b2a19029e9ff

and this example:

```
public class Config {
   @JsonSetter(nulls=Nulls.SKIP) // don't override if null
   public Coordinates coordinates = new Coordinates(1, 2);
   @JsonSetter(nulls=Nulls.AS_EMPTY) // null will clear to empty list
   public List<String> names = Collections.emptyList();
   @JsonSetter(nulls=Nulls.AS_EMPTY,
       contentNulls=Nulls.FAIL)
   public Map<String, Extra> attributes;
}
```

**Comment by JayChandler** [comment]
Okay but how about doing it without annotations? Is there any setting on the ObjectMappper ?

**Comment by cowtowncoder** [comment]
@JayChandler please read the blog post I linked to.
