### ISSUE TITLE
Support Type Id mappings where two ids map to same `Class`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#312]
Currently default type id handlers do require mapping between ids and types (Classes) to be bijective; that is, neither side can have duplicates. This makes sense if both serialization and deserialization is required; if there are multiple choices, mapping would be ambiguous.

But for cases where Jackson is only used for deserializing, it may be useful to map more than one type id to a single class. It would be good if default type id serializer could support such usage; it is acceptable (and desirable) to throw an exception if such mapping was being used for serialization.

**Comment by cowtowncoder** [comment]
@umbreak I don't think you are reading what I have written above. As I have repeatedly pointed out, mapping is not bijective which is WHY CURRENT IMPLEMENTATION WILL THROW AN EXCEPTION. And that further, with changes, IT WOULD START WORKING FOR DESERIALIZATION.

**Comment by cowtowncoder** [comment]
Implemented for 2.6.0.

**Comment by cowtowncoder** [comment]
@gimlet2 If there are follow up problems, could you please file a follow-up issue? It may reference this issue as background. I don't usually re-open old issues if fix in question has been published, as doing so complicates figuring out which version fix(es) go in.

**Comment by JoergHeinicke5005** [comment]
@gimlet2 Has this follow-up issue ever been created?

We are running exactly into the issue that registerSubtypes(..) doesn't work for use with mapping multiple types to the same class while it worked with annotating the super class. The latter we don't want to do anymore as it is a generic class not supposed to know about subtypes (also see #2104).
