### ISSUE TITLE
No-argument construction method deserialization

### ISSUE THREAD

**Issue by qq443672581** [FasterXML/jackson-databind#3121]
entity:

```
public class E{
    private String a;
    private int b;

    public E(String a, int b) {
        this.a = a;
        this.b = b;
    }
    
    ... set get
}
```

![image](https://user-images.githubusercontent.com/12726982/114987187-7398b400-9ec7-11eb-9189-cc460f2c0420.png)

do deserialize ，error message：
(no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

I want to deserialize an entity, but there is no parameterless construction method for this entity, because there are a large number of such entities in our business, so I can’t process it in batches, and can only modify the serialization tool。

I found the ReflectionFactory class, which can initialize a class that does not have a constructor, but I don’t know where Jackson initializes the entity. So, does anyone know how to deal with it? Thank you

**Comment by cowtowncoder** [comment]
Have you tried using `@JsonCreator` annotation to use the constructors you do have?

**Comment by qq443672581** [comment]
> Have you tried using `@JsonCreator` annotation to use the constructors you do have?

Thank you, but I don't want to change the history code because they're huge. I want to deal with them in a crosscutting way

**Comment by cowtowncoder** [comment]
Currently your options are:

1. Use `@JsonCreator` on class
2. Use `@JsonCreator` via mix-in annotations (f.ex https://springframework.guru/jackson-mix-in-annotation/)
3. In case of one `public` constructor, using `jackson-module-parameter-names`... it should be automatically used -- you need to do nothing
4. Custom deserializer

There is no mechanism that tries to instantiate POJOs by-passing constructors.

**Comment by qq443672581** [comment]
> Currently your options are:
> 
> 1. Use `@JsonCreator` on class
> 2. Use `@JsonCreator` via mix-in annotations (f.ex https://springframework.guru/jackson-mix-in-annotation/)
> 3. In case of one `public` constructor, using `jackson-module-parameter-names`... it should be automatically used -- you need to do nothing
> 4. Custom deserializer
> 
> There is no mechanism that tries to instantiate POJOs by-passing constructors.

thank you~

**Comment by qq443672581** [comment]
wow，I was surprised to find that it could be done
![image](https://user-images.githubusercontent.com/12726982/115535361-41be8d80-a2cb-11eb-8c41-cf71e02e617b.png)

ahaha☺

**Comment by cowtowncoder** [comment]
Ah. Good find for how to plug this in @qq443672581 !

It seems possible that a very simple module could be created, one that adds such handler: since handlers may be chained, this could work well with other modules too.

Depending on where `ReflectionFactory` comes from this could even become a jackson-databind core feature (enabled/disabled via `MapperFeature`) -- but only if that class can be easily embedded. I did see a reference to "sun.reflect.ReflectionFactory" which (if that's the one used) would require module as it is not part of official JDK specs; but adding modules is not a big deal in general.
