### ISSUE TITLE
Deep merge for `JsonNode` using `ObjectReader.readTree()`

### ISSUE THREAD

**Issue by sirianni** [FasterXML/jackson-databind#3122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Ability to deep merge two `JsonNode` objects, and/or to deserialize a stream by updating an existing `JsonNode` rather than creating a new one.

**Usage example**
```java
    var mapper = new ObjectMapper();
    var node1 = mapper.readTree("{\"root\":{\"a\":\"aaa\",\"foo\":\"hello\"}}");
    var node2 = mapper.readerForUpdating(node1)
        .readTree("{\"root\":{\"b\":\"bbb\",\"foo\":\"goodbye\"}}");
```

**Additional context**
https://github.com/FasterXML/jackson-databind/issues/584 implies that this capability exists, but it does not appear to be functioning propery for `JsonNode`.  There also doesn't seem to be a way to specify shallow or deep merge using the tree API `readerForUpdating()`

**Comment by cowtowncoder** [comment]
It should just work, with Jackson 2.12 at least. There is no (and there is unlikely ever to be a way) to select deep/shallow merge as this depends on POJOs in question (or more accurately, deserializers).

If `JsonNode` merge does not work, it'd be good to explain what exactly you see, and how that differs from the expectation. Ideally a unit test.

**Comment by sirianni** [comment]
Thanks @cowtowncoder for the quick reply!  I've created a repo https://github.com/sirianni/jsonMerge with a [failing unit test](https://github.com/sirianni/jsonMerge/blob/master/src/test/java/jsonmerge/JsonMergeTest.java).

**Comment by sirianni** [comment]
> select deep/shallow merge as this depends on POJOs in question (or more accurately, deserializers).

What are the semantics for `JsonNode`?

**Comment by cowtowncoder** [comment]
Since `JsonNode` is mutable, it should allow deep merge; `JsonDeserializer` associated with a type should indicate this via `Boolean supportsUpdate()` (true, false or null (not known)).
Technically only `ObjectNode` and `ArrayNode` are updateable since leaf scalar types are immutable.

But actual implementation relies on `deserialize()` override which takes existing instance; if that is implemented as mutable operation, merges are possible.

**Comment by cowtowncoder** [comment]
Ah. Quick fix is to use `readValue()`, not `readTree()` -- there is no benefit from trying to use `readTree()` here.

But I am not sure why the difference should matter and will see if that can be fixed. Thanks!

**Comment by cowtowncoder** [comment]
Fixed by simply delegating calls to `readValue()` in case "valueToUpdate" is defined; seems that this should work (and does handle tests I added). Added in 2.13 just to minimize any possibility of breakage for 2.12.x;  I would recommend just using `readValue()` directly here in general.

**Comment by sirianni** [comment]
Thanks Tatu!!

**Comment by ollijm** [comment]
@sirianni Would you happen to have a working code example of this deep merge?

**Comment by ollijm** [comment]
Ah I had a silly mistake, got it now:
```
        ObjectMapper mapper = new ObjectMapper();
        JsonNode node1 = mapper.readValue("{\"root\":{\"a\":\"aaa\",\"foo\":\"hello\"}}", JsonNode.class);
        JsonNode node2 = mapper.readerForUpdating(node1)
                .readValue("{\"root\":{\"b\":\"bbb\",\"foo\":\"goodbye\"}}");
```
