### ISSUE TITLE
Serializing `java.lang.Thread` fails on JDK 11 and above (should suppress serialization of `ClassLoader`)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#3130]
Looks like serialization of `Thread` (for exp, `Thread.currentThread()`) fails with StackOverflow on JDK11, due to addition of a new property. Looks like this might be via `ClassLoader`, which probably should not really be serialized anyway.
Passed on JDK 8.

**Comment by cowtowncoder** [comment]
Since this does change output, will not try to resolve in 2.12, will target 2.13.

Work-around for anyone hit by this would be to add `ClassLoader` type into "ignored types" list, like so:

```
    mapper.configOverride(ClassLoader.class).setIsIgnoredType(true);
```

which I think should work. If not, mix-in with `@JsonIgnoredType` against `ClassLoader` definitely should work.

**Comment by LishengVoltDB** [comment]
Strating at which release of jackson-databind, this error has been fixed?
