### ISSUE TITLE
`ObjectMapper.setDateFormat` not applied to `java.time` classes

### ISSUE THREAD

**Issue by ionel-sirbu-crunch** [FasterXML/jackson-databind#3132]
**Describe the bug**
I have a use case where I have to marshall an object that's very generic. Basically, imagine a proxy that knows nothing about the data it passes around, they're just flat structures, so I'm using a plain `Map<String,?>` to model that. The problem is when that structure contains `java.time` classes, e.g. `LocalDateTime`, I expect them to be formatted in a certain way & that doesn't seem to happen.

**Version information**
2.11.4
Replicated with 2.12.3 as well.

**To Reproduce**
```java
        ObjectMapper objectMapper = new ObjectMapper().findAndRegisterModules();
        objectMapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ"));

        LocalDateTime localDateTime = LocalDateTime.of(2020, 3, 10, 9, 0);
        System.out.println(objectMapper.writeValueAsString(localDateTime));
        // yields "2020-03-10T09:00:00"
        
        ZonedDateTime zonedDateTime = ZonedDateTime.of(localDateTime, ZoneOffset.UTC);
        System.out.println(objectMapper.writeValueAsString(zonedDateTime));
        // yields "2020-03-10T09:00:00Z"

        Date utilDate = Date.from(zonedDateTime.toInstant());
        System.out.println(objectMapper.writeValueAsString(utilDate));
        // yields "2020-03-10T09:00:00.000+0000" - this is the expected value
```

**Expected behavior**
The format set via `setDateFormat()` to be applied to `java.time` classes in the same manner that it does for `java.util` ones. Unless there's another way to achieve that, that I'm not aware of?

**Comment by cowtowncoder** [comment]
Unfortunately format String application in Java 8 date/time is different from "old JDK" types; `DateFormat` cannot be used at all.

There is a way to specify format for Java 8 types, however: either using `@JsonFormat(pattern = ".....")` on fields, or its equivalent via "config overrides", like:

```
mapper.configOverride(LocalDate.class).setFormat(JsonFormat.Value.forPattern("dd-MMM-yyyy"));
```

**Comment by ionel-sirbu-crunch** [comment]
Thanks for looking into this!

The `@JsonFormat` is out of discussion for obvious reasons, but the other suggested approach works just fine, i.e.
```java
objectMapper.configOverride(ZonedDateTime.class).setFormat(JsonFormat.Value.forPattern("yyyy-MM-dd'T'HH:mm:ss.SSSZ"));
```

**Comment by cowtowncoder** [comment]
Thank you for adding the update!

Ah right, since you are serializing arbitrary objects and it's not accessed via typed field.

Glad that config overrides work as expected: it also should work for `java.util.*` types although that is something I should verify (that there are unit tests to ensure).
