### ISSUE TITLE
Deserialization of collection does not support single element lists (without array token)

### ISSUE THREAD

**Issue by nocxsville** [FasterXML/jackson-databind#3135]
**Describe the bug**
An exception is thrown when trying to deserialize a list of elements that contains a single element only and does not have an array start and end token.

The follwoing exception is thrown;
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<tst.Test$MyElement>` from Object value (token `JsonToken.START_OBJECT`)

**Cause:** The method "com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(JsonParser, DeserializationContext, Collection<Object>)" expects an array start token:

```
// Ok: must point to START_ARRAY (or equivalent)
  if (!p.isExpectedStartArrayToken()) {
      return handleNonArray(p, ctxt, result);
  }
```

However, in JSON this is optional for single elements.

**Version information**
jackson-core 2.11.4 (managed by spring boot 2.4.2)
same behavior in version 2.12.3

**To Reproduce**

In this example the sub list "global" has only one element. The array start and end token is missing (as it is optional in case of a single element).

```
  public static void main(String[] args) throws Exception {
      String value = "..."; // {"elements":{"name":[{"value":null}],"email":[{"value":null}],"global":{"value":"sun"}}}"
      ObjectMapper mapper = new ObjectMapper();
      mapper.readValue(value, MyObject.class);
    } 
    static class MyElement {
      private String value;
  
      public String getValue() {
        return value;
      }
  
      public void setValue(String value) {
        this.value = value;
      }
    }
  
    static class MyObject {
      private Map<String, List<MyElement>> elements;
  
      public Map<String, List<MyElement>> getElements() {
        return elements;
      }
  
      public void setElements(Map<String, List<MyElement>> elements) {
        this.elements = elements;
      }
    }
```

**Expected behavior**
The "CollectionDeserializer" should handle lists with single elements even without array start/end token.

**Additional context**
nothing to add here

**Comment by cowtowncoder** [comment]
Basic databinding from JSON expects -- as it should, in my opinion -- that for `Collection`/array types, there is JSON Array.
Assuming that any other type might be just missing array for some reason will allow all types of mismatches and hides issues.
This is different from, say, XML, which does not have distinction between Arrays and Objects and thereby must use some other tricks.

But if you do want to enable logic of "array-or-single-value" you can enable that with Jackson by either:

* Globally enable `DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY`
* Add annotation `@JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)` on specific property

**Comment by nocxsville** [comment]
Thanks a lot, this solved my issue!
Sometimes you have to deal with such stuff. I get the JSON by an external library (PrimeNG data table). So, it is not in my hand.
