### ISSUE TITLE
Nested generic type information lost when using builder deserialization

### ISSUE THREAD

**Issue by etki** [FasterXML/jackson-databind#3136]
**Describe the bug**
While using builder (in my case, Lombok-generated one) and at least TypeReference, nested generic type information got lost.
`TypeReference<SomeType>` works fine, but `TypeReference<SomeGenericType<NestedType>>` does not - Jackson uses behaves as if `Object` would be used instead of `NestedType`.

**Version information**
2.11.2

**To Reproduce**

```java
public class Main {
    private static final String SOURCE = """
            {
              "value": {
                "value": 12
              }
            }
            """;

    public static void main(String[] args) throws Exception {
        ObjectMapper mapper = new ObjectMapper();

        BuiltContainer<BuiltContainer<Integer>> built = mapper.readValue(SOURCE, new TypeReference<>() {});
        System.out.println(built);
        Object value = built.getClass().getDeclaredField("value").get(built);
        System.out.println(value.getClass());

        RegularContainer<RegularContainer<Integer>> deserialized = mapper.readValue(SOURCE, new TypeReference<>() {
        });
        System.out.println(deserialized);
    }

    @lombok.Data
    @lombok.Builder(builderClassName = "Blueprint", setterPrefix = "with")
    @JsonDeserialize(builder = BuiltContainer.Blueprint.class)
    private static class BuiltContainer<T> {
        private final T value;
    }

    @lombok.Data
    private static class RegularContainer<T> {
        private T value;
    }
}
```

Output:

```
Main.BuiltContainer(value={value=12})
class java.util.LinkedHashMap
Main.RegularContainer(value=Main.RegularContainer(value=12))
```

As you can see, for built container LinkedHashMap was provided as value, while regular approach works as expected. Type erasure conceals this up to unwrapping (`.getValue()`) call.

**Comment by cowtowncoder** [comment]
One quick note: this will not work and cannot be used:

```
        RegularContainer<RegularContainer<Integer>> deserialized = mapper.readValue(SOURCE, new TypeReference<>() {
        });
```

specifically, you cannot leave out type parameter from `TypeReference`, nor use type variable: type must be fully spelled out. So it should read:

```
        RegularContainer<RegularContainer<Integer>> deserialized = mapper.readValue(SOURCE, new TypeReference<RegularContainer<RegularContainer<Integer>>>() {
        });
```

as that is the whole point: you must work around Java Type Erasure.

I don't know if that omission was accidental in code snippet (i.e. you use it in real code); if it was left out on purpose, it cannot be.

**Comment by etki** [comment]
@cowtowncoder I don't have infra at hand to prove it, but i believe that diamond operator correctly infers type here. It's the same as omitting it in `Map<String, String> map = new HashMap<>();`

**Comment by cowtowncoder** [comment]
@etki I am not sure that is how it goes since type inference in most cases tends to be syntactic sugar (that is, affects only compilation-time storing nothing for run time). But since I haven't actually tried this out I am not curious and will replicate with a simple test.

**Comment by cowtowncoder** [comment]
Ah actually never mind, no. That code does not even compile on Java 8, but it could not possibly pass type parameters even if it did.

As the first step I would try adding type parameters in there. If there is still a problem, I would need a version after Lombok has done its magic, to show the issue.

**Comment by cowtowncoder** [comment]
Cannot reproduce at this point; may be reopened with reproduction that does not use Lombok (that is, shows classes after Lombok processing).
