### ISSUE TITLE
Inherit JsonInclude attribute

### ISSUE THREAD

**Issue by chrylis** [FasterXML/jackson-databind#3138]
As of Jackson 2.12.0, an `@JsonInclude` attribute applied to a superclass is disregarded when a subclass is used. Specifically, I have some JSON:API business that includes this snippet:

```
abstract class JsonApiResource<A> {
  @JsonInclude(NON_NULL)
  abstract A getAttributes();
}
```

However, the directive is not inherited, and so classes implementing this still have their null members serialized.

**Comment by cowtowncoder** [comment]
It should be supported: I would need a unit test to show your exact usage to confirm.

**Comment by cowtowncoder** [comment]
No reproduction; will close but may be reopened with repro (unit test ideally).
