### ISSUE TITLE
Serialization of polymorphic objects with custom resolver

### ISSUE THREAD

**Issue by sblasco** [FasterXML/jackson-databind#314]
To serialize/deserialize polymorphic objects that at compilation time are not known.

I try to create my own type resolver with custom type info as a wrapper object. For the ID use the value of the JsonRootName annotation.

There is an abstract class and some inherited containing different values.
The idFromValue() method from TypeIdResolver (CustomResolver class) receives sometimes an object of inherited class an other times an object the class of @JsonValue annotation.

It worked with version 2.1.3 for any @JsonValue annotation class but any other later version doesn't work the same way.

See http://jackson-users.ning.com/forum/topics/serialization-of-polymorphic-objects-with-custom-resolver where there is an example.

**Comment by cowtowncoder** [comment]
At this point not quite sure what to do with this one -- I think it's better to close this one, open new one with better idea of how handling would be expected to work. Behavior of 2.1 was more of accidental (although in way that was useful I am guessing), not as designed.
