### ISSUE TITLE
@JsonUnwrapped: missing property value when property is also mapped in outer structure

### ISSUE THREAD

**Issue by MortenEriksen** [FasterXML/jackson-databind#3149]
**Describe the bug**

When both the unwrapped structure and the owner structure maps a property, the value of the property in the unwrapped structure seemingly remains uninitialized.

Is this expected behaviour, or a bug?

**Version information**

2.12.3

**To Reproduce**

```
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.databind.ObjectMapper;

public class BugReproducer {
  public static void main(String[] argsArray) throws Throwable {
    String input = "{\"in_outer\": 42, \"not_in_outer\": 42}";
    OuterStructure outer = (new ObjectMapper()).readValue(input, OuterStructure.class);
    System.out.println(String.format("in outer: %d, not in outer: %d",
                                     outer.unwrapped.inOuter,
                                     outer.unwrapped.notInOuter));
  }


  public static class OuterStructure {
    @JsonProperty(value = "in_outer")
    int inOuter;

    @JsonUnwrapped
    UnwrappedPart unwrapped;
  }

  public static class UnwrappedPart {
    int inOuter;
    int notInOuter;
        
    @JsonCreator
    public UnwrappedPart(@JsonProperty("in_outer") int inOuter,
                         @JsonProperty("not_in_outer") int notInOuter) {
      this.inOuter = inOuter;
      this.notInOuter = notInOuter;
    }
  }
}
```

**Additional context**

The above code to reproduce doesn't really show a use case where it is convenient to have a property in both an outer class and its unwrapped class, but that happens e.g. when there's inheritance so that the OuterClass has a superclass where we want to expose the inOuter property directly.

**Comment by cowtowncoder** [comment]
If outer value has property, it should not be delegated to `@JsonUnwrapped` objects.

As of Jackson 2.x, delegation for unwrapped properties is a mess and I am always wondering if adding this feature in general was just a bad idea.
But if I ever find time to get 3.0 ready, rewrite of handling would be quite high on todo list.

**Comment by MortenEriksen** [comment]
Thank you for your response. I'll assume it won't be added for any 2.x then. (Not really a problem, it wasn't a big deal to code around this, though it ended up a little less elegant than using `@JsonUnwrapped`.)
