### ISSUE TITLE
How to serialize static variables?

### ISSUE THREAD

**Issue by MikeTheGreat** [FasterXML/jackson-databind#3150]
I'm very sorry for posting this as an issue - I'm having a really hard time finding something and am hoping y'all can help.

I'd like to serialize a class that has some public static variables in it.  The ObjectMapper doesn't seem to notice them by default.  Is there a way to have the ObjectMapper also serialize static variables as well?

(For my particular case I'm looking at a class that contains only public static variables, so I don't have to worry about re-serializing the same static variables every time ObjectMapper finds another instance, since there aren't any instances, just the public static variables)

Any advice and/or pointers for where else to look for help would be greatly appreciated!

**Comment by MikeTheGreat** [comment]
I think I've got a way around this, so I'm going to close it

**Comment by cowtowncoder** [comment]
The usual way would be to add a "getter" method: it is not possible to annotate `static` members as they are completely filtered out by processing wrt property handling.

**Comment by Taylorjtt** [comment]
> I think I've got a way around this, so I'm going to close it

What was your workaround?

**Comment by MikeTheGreat** [comment]
I'm very sorry, but it's been like 2 years since I opened this.  I don't remember even a little :(
