### ISSUE TITLE
serializeWithType not being called for collections within customer serializers

### ISSUE THREAD

**Issue by rohanprabhu-jm** [FasterXML/jackson-databind#3157]
**Describe the bug**

I am using a custom serializer to sort of "taint" a particular serializing process, similar to the use-case over here - How to access default jackson serialization in a custom serializer

What I essentially need is to create a custom serializer, that has access to the otherwise serializer that would have been used (think of it as a serializer with a decorator pattern). But to get the actual default serializer that would have been used, I need to use a BeanSerialzierModifier. So I've got this setup and all of it actually works great, except when I need to serialize type information for objects inside a collection.

I've setup a very basic repro from my actual code:

```
fun main() {
    class TaintingSerializer(
        private val defaultSerializer: JsonSerializer<Any>
    ) : JsonSerializer<Any>() {
        override fun serialize(p0: Any, p1: JsonGenerator, p2: SerializerProvider) {
            // Taint the serialization process here
            p2.setAttribute("taint_value", true)
            defaultSerializer.serialize(p0, p1, p2)
        }

        override fun serializeWithType(
            value: Any,
            gen: JsonGenerator,
            serializers: SerializerProvider,
            typeSer: TypeSerializer
        ) {
            defaultSerializer.serializeWithType(value, gen, serializers, typeSer)
        }
    }

    val objectMapper = ObjectMapper()
    @Suppress("UNCHECKED_CAST")
    val module = object : SimpleModule() {
        override fun setupModule(context: SetupContext) {
            context.addBeanSerializerModifier(object : BeanSerializerModifier() {
                override fun modifySerializer(
                    config: SerializationConfig,
                    beanDesc: BeanDescription,
                    serializer: JsonSerializer<*>
                ): JsonSerializer<*> {
                    return TaintingSerializer(serializer as JsonSerializer<Any>)
                }
            })
        }
    }

    objectMapper.registerModule(module)
    println(objectMapper.writeValueAsString(Dog("bruno", "loud")))
    println(objectMapper.writeValueAsString(
        Container(
            listOf(Dog("bruno", "loud"), Cat("felix", "purr")))
        )
    )
}
```

The two objects you see above being serialized are defined with the type annotations as follows:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "animalType")
@JsonSubTypes(
    JsonSubTypes.Type(value = Dog::class, name = "dog"),
    JsonSubTypes.Type(value = Cat::class, name = "cat")
)
abstract class Animal {
    abstract val name: String
}

@JsonTypeName("cat")
data class Cat(
    override val name: String,
    val meowType: String
) : Animal()

@JsonTypeName("dog")
data class Dog(
    override val name: String,
    val barkType: String
) : Animal()
```

Take a closer look at the last two lines in the `main` function:

```
println(objectMapper.writeValueAsString(Dog("bruno", "loud")))
println(objectMapper.writeValueAsString(
    Container(
        listOf(Dog("bruno", "loud"), Cat("felix", "purr")))
    )
)
```

The above outputs:

```
{"animalType":"dog","name":"bruno","barkType":"loud"}
{"animals":[{"name":"bruno","barkType":"loud"},{"name":"felix","meowType":"purr"}]}
```

If you notice, in the second line, the two objects being printed have no animalType or the type-id descriptor. If I comment the following line (which is basically I use objectmapper as-is):

```
object.registerModle(module)
```
Then the correct output shows up, with animalType in the objects in the collection as well:

```
{"animalType":"dog","name":"bruno","barkType":"loud"}
{"animals":[{"animalType":"dog","name":"bruno","barkType":"loud"},{"animalType":"cat","name":"felix","meowType":"purr"}]}
```

To further test my hyopthesis, I then put in a println statement to differentiate between serialize() function calls and serializeWithType function calls, and what I've realised is that the serializeWithType is simply not being called for any object within the collection - but for the top-level object it is.

**Version information**
2.12.3

**To Reproduce**
If you have a way to reproduce this with:

1. Code mentioned above, can be run as-is without any dependencies except `jackson-core` and `jackson-databind`

**Expected behavior**
If I'm always using the exact same serializer underneath, then the correct type serialization must be called whenever working on a serializer. While I'm suspecting that this is due to the serializer being called without the context of the field name it is being called in (which would give it the parent-level type information), but I'm not sure why this would happen - and where exactly this detachment is occurring.

**Comment by cowtowncoder** [comment]
Without looking any deeper, I have couple of suggestions that might help:

1. Extend one of base serializer types like `StdSerializer` and not directly `JsonSerializer`
2. It is almost always necessary to implement both `ContextualSerializer` and `ResolvableSerializer`: delegate to serializer being delegated to/wrapped. If this is not done, most configuration will be ignored

Of these, (2) can cause various issues so I would tackle that first: in both cases you will just need to see if underlying serializer implements matching interfaces, and if so, call it on them.
In case of `resolve()` nothing is returned (instance itself is modified: this is only used to handle cyclic dependencies); for `createContextual()` returned instance may be different and you may need to construct a new instance of `TaintingSerializer`.

**Comment by rohanprabhu-jm** [comment]
@cowtowncoder Yup, adding in a resolvable and contextual totally works, so thank you so much for this. Can I get some more information on why (or how) this is the case? Specifically the statement "If this is not done, most configuration will be ignored". I don't need literal documentation, if anyone could point me to a code file on GitHub as well where the relevant piece starts, that will do it as well.

And to re-iterate, thank you so much for replying to this GH issue!

**Comment by cowtowncoder** [comment]
@rohanprabhu-jm The best way to see what kind of configuration is done would probably to search for implementations of `createContextual()` (for `ContextualSerializer`) and `resolve()` (for `ResolvableSerializer`) (in 2.13 branch).

In general, `resolve()` is only/mostly used for POJOs (`BeanSerializer` or `BeanSerializerBase`) to handle issue of cyclic dependencies (2 types refer to each other).
`createContextual()` however is used for things like applying annotations on properties, and any configuration that might be overridden on per-property basis. This information is not available at the time serializer instances are constructed since the only thing passed at that time is type being handled.
