### ISSUE TITLE
Java 8 date/time type `java.time.LocalDateTime` not supported by default

### ISSUE THREAD

**Issue by esfomeado** [FasterXML/jackson-databind#3164]
**Describe the bug**
I have upgrade Jackson from 2.11.4 to 2.12.3 and not I get this exception:

> Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling

Now I have to explicitly register the JavaTimeModule(). Is there any behavior change?

Thanks

**Version information**
2.12.3

**To Reproduce**
https://github.com/esfomeado/jackson-test

Java 8

**Expected behavior**
Should work the same way has the previous version.

**Additional context**
Spring Boot 2.5

**Comment by cowtowncoder** [comment]
This is intentional, see #2683: Java 8 date/time values should NOT be serialized as POJOs by default because that representation has caused lots of issues -- it cannot be read back.

**Comment by cowtowncoder** [comment]
@esfomeado Ah, yes. Did the code sample use `convertValue()`? One thing #3091 could use is actual reproduction of the issue (wrt convertValue() or use with `JsonNode`)... to verify that fix works.

**Comment by Tuegor** [comment]
Hey, nice chit-chat between you two, but how to fix this one after all? I've added the dependency to POM as was required, but still it's not working!

**Comment by GedMarc** [comment]
ObjectMapper.registerModule.....

**Comment by Tuegor** [comment]
Thanks, found this one already.

**Comment by gautamkumargojoko** [comment]
> ObjectMapper.registerModule.....

I dont understand why but it is not working for me!!

**Comment by AndyCodez** [comment]
> 



> > ObjectMapper.registerModule.....
> 
> I dont understand why but it is not working for me!!

@gautamkumargojoko were you able to solve this?

**Comment by gautamkumargojoko** [comment]
> > 
> 
> > > ObjectMapper.registerModule.....
> > 
> > 
> > I dont understand why but it is not working for me!!
> 
> @gautamkumargojoko were you able to solve this?

**after adding this to Config file**
```
 @Bean
  public MappingJackson2HttpMessageConverter mappingJackson2HttpMessageConverter() {
    Jackson2ObjectMapperBuilder builder =
        new Jackson2ObjectMapperBuilder()
            .featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .serializers(
                new LocalDateTimeSerializer(DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssZ")))
            .serializationInclusion(JsonInclude.Include.NON_NULL);
    return new MappingJackson2HttpMessageConverter(builder.build());
  }
```
  
  **and added these annotations :**
```
  @JsonSerialize(using = LocalDateTimeSerializer.class)
  @JsonDeserialize(using = LocalDateTimeDeserializer.class)
  @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", shape = JsonFormat.Shape.STRING)
  private LocalDateTime createdAt;
```
  then it worked for me

**Comment by cowtowncoder** [comment]
It should NOT be necessary -- and I would recommend against -- add `@JsonSerialize` / `@JsonDeserialize` settings.
Instead the `DateTimeModule` should be registered, to avoid having to do that.

**Comment by gautamkumargojoko** [comment]
> It should NOT be necessary -- and I would recommend against -- add `@JsonSerialize` / `@JsonDeserialize` settings. Instead the `DateTimeModule` should be registered, to avoid having to do that.

I had tried but unfortunately it did not work for me !! @cowtowncoder

**Comment by zhaishudong** [comment]
上面有任何后续吗？我也是升级到了2.13版本，并主动注册了：
@Configuration
public class JacksonConfig {
﻿
@Bean
public ObjectMapper objectMapper() {
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(new JavaTimeModule());
return objectMapper;
}
}
但是一样不起作用，同时抛出了异常：
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.HashMap["cacheTime"])
﻿

**Comment by zhaishudong** [comment]
Is there any follow-up above? I also upgraded to version 2.13 and proactively registered:
@Configuration
Public class JacksonConfig{
@Bean
Public objectMapper objectMapper(){
Object Mapper object Mapper=new Object Mapper();
ObjectMapper. registerModule (new JavaTimeModule());
Return objectMapper;
}
}
But it still doesn't work and throws an exception:
Com. fasterxml. jackson. databind. exc. InvalidDefinitionException: Java 8 date/time type ` Java. time LocalDateTime ` not supported by default: add Module "com. fasterXML. jackson. datatype: jackson datatype jsr310" to enable handling (through reference chain: java. util. HashMap ["cacheTime"])

**Comment by JooHyukKim** [comment]
It should work with Java8 module registered. Try checking ur Spring configuration settings.

**Comment by cowtowncoder** [comment]
@zhaishudong This sounds like a Spring configuration problem: Jackson cannot really do anything there. You may want to ask on Spring support forums.
