### ISSUE TITLE
How to convert one class to another using JsonProperty

### ISSUE THREAD

**Issue by arturmkr** [FasterXML/jackson-databind#3170]
Having following class:
```
@Data
@Accessors(fluent = true)
public class AccountRequest {

  @JsonProperty("accountId")
  private String accountId;
}
```

and following:
```
@Data
@Accessors(fluent = true)
public class AccountResponse {

  @JsonProperty("accountId")
  private String accountId;

  @JsonProperty("createdDate")
  private String createdDate;

  @JsonProperty("status")
  private String status;
}
```

I would like to convert instance of class AccountResponse to class AccountRequest.
There are similar @JsonProperty values.
What is the best way to do this?

I found only one solution, but I am not sure that converting class to json all the time is a good option:
```
    AccountResponse accountResponse;
    ObjectMapper mapper = new ObjectMapper();
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    String json = mapper.writeValueAsString(accountResponse);
    AccountRequest accountRequest =  mapper.readValue(json, AccountRequest.class);
```

**Comment by yawkat** [comment]
There's a dedicated convertValue method on ObjectMapper that you can use.

**Comment by cowtowncoder** [comment]
I would recommend using jackson-user list:

https://groups.google.com/g/jackson-user

or Gitter chat:

https://gitter.im/FasterXML/jackson-databind 

for usage questions.

Issue trackers are not a support forum but channels to report problems and requesting new features.
There are also many more devs who can help on above-mentioned list/chat, compared to a small number of core devs who follow issue tracker updates.
