### ISSUE TITLE
Serialization - Class extends HashMap

### ISSUE THREAD

**Issue by samuelfac** [FasterXML/jackson-databind#3173]
I'm using **jackson-databind version 2.12.3** with java8

Create myObject:
```java
  MyObject myObject = new MyObject();
  myObject.setField1("value1");
  myObject.setField2("value2");

  Link link = new Link();
  link.setField(new HrefType().href("/link"));
  link.put("test",new HrefType().href("/test"));

  myObject.setLinks(link);
```
on serialize myObject should return like this:
```json
{
  "field1":"value1",
  "field2":"value2",
  "links":{
    "field":{
      "href":"/link"
    },
    "test":{
      "href":"/test"
    }
  }
}
```
But with the default ObjectMapper the "myObject.link.field" is ignored and the returned json is:
```json
{
  "field1":"value1",
  "field2":"value2",
  "links":{
    "test":{
      "href":"/test"
    }
  }
}
```
My classes are these:

```java
public class Link extends HashMap<String, HrefType>  {
  private HrefType field = null; //ERROR: this field is ignored on serializer
  ...
}

public class HrefType  {
  private String href = null;
  ...
}

public class MyObject  {
  private String field1 = null;
  private String field2 = null;
  private Link links = null;
  ...
}
```

I think it's a bug which ignores the fields of the class that extends a hashmap

**Comment by cowtowncoder** [comment]
This is by design: by default all `Map`s are serialized as `Map`s; no additional properties are assumed or used.

But if you want to serialize them as POJOs, you can configure it with

    @JsonFormat(shape=JsonFormat.Shape.OBJECT)

either on custom class, or on property. This will then only serialize whatever properties are found: if you want contents to be serialized too, you need to use `@JsonAnyGetter` annotation on a field or getter.

**Comment by samuelfac** [comment]
With @JsonFormat(shape=JsonFormat.Shape.OBJECT) only the declared fields are converted, the HashMap items are ignored.

With @JsonAnyGetter it made no difference, it only returned the HashMap items

**Comment by cowtowncoder** [comment]
You can combine `Shape.OBJECT` to get regular properties and then use `@JsonAnyGetter` to provide entries.
Latter may get tricky wrt recursiveness, if your Map subtype has `@JsonFormat` annotation -- but I think that if declared type is `Map<String, Object>` it might not be a problem.

At any rate, this works as designed: all Map types are by default expected to be used as Maps; they are not POJOs (similarly for `Collection`s).

**Comment by samuelfac** [comment]
I will try. Tks a lot.

**Comment by yanxiyue** [comment]
@samuelfac how did you solve it in the end?
