### ISSUE TITLE
Can I serialize subclasses based on an external key with jackson?

### ISSUE THREAD

**Issue by xenoterracide** [FasterXML/jackson-databind#3189]
https://stackoverflow.com/q/68105631/206466

is it possible to deserialize subclasses with Jackson using a type that external? e.g. the type defining the subclass would come from the copy name somehow (using js/json5 syntax here for brevity). This would require some kind of `Pair` class, but it appears there's support in external modules for `vavr`/`commons-lang3`. I can see that the left side of the pair could be a lowercase enum.  I can't seem to find a simple way to do this mapping via annotations, the only thing I've been able to find is having a `type` property, or having the exact classname (which is a bad abstraction imo)

```json5
[
 copy: {
   source: "foo",
   destination: "bar"
 },
 search_replace: {
   search: "foo",
   replace: "bar",
   destination: "bar"
 }
]
```

**Comment by cowtowncoder** [comment]
Please use mailing list:

https://groups.google.com/g/jackson-user

or Gitter chat;

https://gitter.im/FasterXML/jackson-databind

for usage questions.
