### ISSUE TITLE
@JsonUnwrapped doesn't work on EnumMap

### ISSUE THREAD

**Issue by Pr0methean** [FasterXML/jackson-databind#3215]
When I annotate an EnumMap with `@JsonUnwrapped`, it's still serialized as a nested object rather than as multiple properties of the parent object. I recently ran into a case where this broke backward-compatibility (I was using the EnumMap to replace multiple fields of the value type). The only workaround seems to be to extend EnumMap rather than delegating to it, but this requires exposing put and putAll.

**Comment by cowtowncoder** [comment]
Correct: `@JsonUnwrapped` only works for POJOs, and not for `Map`s as per #171. Closing this as duplidate.

As a work-around (until #171 is implemented), you might be able to use `@JsonAnyGetter`.
