### ISSUE TITLE
Avoid escaping quotes

### ISSUE THREAD

**Issue by sebhani** [FasterXML/jackson-databind#3218]
**Is your feature request related to a problem? Please describe.**
When I parse the following Json string using `readValue(String content, JavaType valueType)` method with valueType set to Map.class: 
![image](https://user-images.githubusercontent.com/39838955/126091589-3aeb00c4-37ee-425a-9626-ffbd6140547a.png)

It returns **"value":"De Maisonneuve 26" Starbucks 510 - Ø8" - WO7633"** (No backslashes before the double quotes). This creates a data corruption in my DB and throws parsing errors when trying to read such values later.

**Describe the solution you'd like**
I'd like to know if there's a way to achieve avoiding escaping double quotes. If not, I would love to have a suggestion on how to implement this (cause I am planning on implementing it).

**Comment by yawkat** [comment]
Not 100% sure what you mean – neither of your samples includes any backslashes?

That said, it is intentional that strings are unescaped during parsing. If this is causing issues downstream in your database, you should fix it there.

**Comment by cowtowncoder** [comment]
Agreed with @yawkat. But if you think there is a real problem, we would need a unit test reproduction -- keeping in mind that to write valid JSON, you can not just concatenate Strings without handling escaping/quoting (something that Jackson will handle automatically when you use it via `writeValue()`, for example).

**Comment by sebhani** [comment]
@yawkat @cowtowncoder Thanks for responding! I updated my original description... Hope it clarifies the problem that I am facing.

**Comment by cowtowncoder** [comment]
@sebhani If I understand your question correctly, this is the way Jackson is expected to work: as per JSON specification, backslashes are used for escaping and in this case value to get should not include them. That's how JSON works.

When writing out JSON, however, this means that whatever is writing JSON will need to similarly escape a small set of characters by prepending them with backslashes: this includes doublequotes included within String values.

If you need that escaping for something else without using Jackson, you will need to do it separately.
