### ISSUE TITLE
Numeric value for a boolean value is accepted.

### ISSUE THREAD

**Issue by johnreilly100** [FasterXML/jackson-databind#3219]
**Describe the bug**
A numeric value for a boolean value is accepted. Any numeric value besides 0 ends up in the boolean value getting set to true. 0 will set it to false.
Using the openapi-generator to generate the code where there is a boolean property in the request body.
Note this is for requests where the value is not in quotes. If the value is in quotes only true or false is accepted.

**Version information**
jackson-databind 2.11.2
openapi-generator 4.2.3

**To Reproduce**
Body of rest request.
`{
 "booleanProperty": 9
}`

Outcome
<html><body>

Value | Boolean value set to
-- | --
0 | false
1 | true
9 | true
-1 | true

</body>
</html>

**Expected behavior**
Only 0 or 1 should be accepted as valid options besides true or false. A config option should be available so that only true or false are valid options.

**Comment by GedMarc** [comment]
So gotta be honest, I don't actually consider this incorrect - 
There actually isn't any specification in JSON for numeric to boolean, so anything goes really - https://json-schema.org/understanding-json-schema/reference/boolean.html

Boolean conversions have quite the funny convention, as a textual based primitive representation they are actually quite unique in Java->Json->Java conversions

Not only this but Localization and etc come into play as well, Yes/No, Ja/Nee, 1.0, 1, 0.0, 0, -0, +0, +1, etc - The number of combinations for conversion actually become insane.

I agree with the decision to leave it to the consumer to specify the actual requirements for serialization and deserialization to JSON based on this, there is no actual one-fits-all in this scenario.

Going a bit deeper, into https://byjus.com/maths/boolean-algebra/ any value higher than 1 equates to true. Therefore the implementation is correct from a mathematical and scientific stand point as well

You can alter your states like the following, 

```
public class StringToBoolean
		extends JsonDeserializer<Boolean>
{
	public static boolean nullable = true;

	@Override
	public Boolean deserialize(JsonParser p, DeserializationContext ctxt) throws IOException
	{
		return convert(p.getValueAsString());
	}

	public Boolean convert(String value)
	{
		if (Strings.isNullOrEmpty(value))
		{
			return null;
		}
		value = value.trim().toLowerCase();
		switch (value)
		{
			case "1":
			case "1.0":
			case "y":
			case "yes":
			case "true":
				return true;
			case "0":
			case "0.0":
			case "no":
			case "n":
			case "false":
				return false;
		}
		if(nullable)
			return null;
		else return false;
	}
}
```

There is also a funny on higher JDK's, 14 and up to be specific - where primitive and boxed equate the same

Type<Boolean> and Type<boolean> are equal, so there isn't really any way to specify different deserializers or serializers for each of these type separately ;) 
But that again, is up to debate on whether it should be, maybe to allow nulls but that's it

**Comment by cowtowncoder** [comment]
As per @GedMarc, this is a feature, not bug. A few coercions are accepted: originally this particular one was due to languages like C and Perl not having native boolean types.

But it is possible to prevent this acceptance using CoercionConfig, explained ff.ex here:

https://cowtowncoder.medium.com/jackson-2-12-most-wanted-4-5-cbc91c00bcd2

and the example case:

    mapper.coercionConfigFor(LogicalType.Boolean)
       .setCoercion(CoercionInputShape.Integer, CoercionAction.Fail);

which specifically makes this coercion fail.

Existing default can not really be changed for Jackson 2.x for backwards compatibility.

**Comment by johnreilly100** [comment]
@cowtowncoder Thanks that config option, that was what I was looking for.
@GedMarc take your point about the history of why things are the way they are but I still think that -1 should not equate to a boolean value getting set to true.

**Comment by GedMarc** [comment]
@johnreilly100  godo stuff man glad it's sorted out - 

(-1) is true in boolean cause of JavaScript, COBOL, BASIC, and any other linear language ;) 

By programming rules - quote - "All values are truthy unless they are defined as falsy (i.e., except for false, 0, "", null, undefined, and NaN)."

I know what you say sounds right, but, sadly it isn't :)

**Comment by kupci** [comment]
> I know what you say sounds right, and to a normal human it would make sense - but, not in our world :)

And you haven't even talked about JavaScript, that's where things get downright crazy :)
