### ISSUE TITLE
Global coercions rules

### ISSUE THREAD

**Issue by joca-bt** [FasterXML/jackson-databind#3222]
Jackson 2.12 introduced coercion rules (https://cowtowncoder.medium.com/jackson-2-12-most-wanted-4-5-cbc91c00bcd2/). Although this is a step in the right direction for people that want strict JSON typing, it is too granular and requires quite a lot of setup for something that should be simpler to achieve (in my opinion).

As far as I understood, when defining coercions, we always need to specify the source type, the provided type, and the coercion rule. For example, if I want strict booleans I need to provide several coercion rules: fail integer to boolean, fail string to boolean, etc. If I want strict JSON I need to do these for all types, which is quite the setup.

Is there an option to set coercion rules globaly for a type (e.g. never coerce booleans, never coerce \<type\>) or for all types as a whole? There's a `coercionConfigDefaults` but it seems to work the other way around.

**Comment by cowtowncoder** [comment]
CoercionConfig defaults are indeed meant to cover the default setting:

```
mapper.coercionConfigDefaults()
    .setCoercion(CoercionInputShape.Boolean, CoercionAction.Fail);
````

although I am sure it is still not as minimal as some potential "VERY STRICT MODE".
But it does not require target type, only source JSON (etc) shape. So I think it should work for your case (although see (1) below).

There are a few other issues relevant here:

1. Not all deserializers have been modified to look for coercion config: more work is needed to cover all existing implicit coercions
2. Default handling is along loose lines, but existence of various one-off features makes reasoning quite difficult -- especially as there is no way to currently distinguish between enabled/disabled/initial-default (that is, whether setting is explicit enable or explicit disable; or just whatever was the initial state)

**Comment by joca-bt** [comment]
I found some situations in which the coercions are not functioning as expected. Shall I create a new ticket or put the examples here?

**Comment by joca-bt** [comment]
Thanks, that works.
