### ISSUE TITLE
How come @JsonProperty does not allow for dot notation selectors?

### ISSUE THREAD

**Issue by kiriakos** [FasterXML/jackson-databind#3236]
I seem to be falling for this every time I do a Jackson web project. At some point I'll write:

```
class Foo {
    @NotNull
    @JsonProperty("foo.bar")
    private String bar;
}
```

and get reminded that dot notation does not work as a value to `@JsonProperty`. So I started googling and could not find any info as to why Jackson forces one to go the custom deserialization route so early when in many cases I would expect supporting dot notation selectors for json properties could go a long way. I'm aware that technically `"foo.bar"` is a valid JSON attribute name but it still seems like an omission to have no way of indicating that one wants to query into the object instead of expecting a dot in the property name.

Selecting data like this seems to also convey some info about what the user expects and especially what the user seems to not care much about (the rest of the object hierarchy). Following, in the serialization case I think it could be reasonable enough to assume that users will be fine with this just serializing back to something skinny.

```
{
  "foo": {
    "bar": "baz"
  }
}
```

Maybe this is just a documentation issue but I really am looking to understand this.

**Comment by cowtowncoder** [comment]
JSON specification does not add any specific interpretation to "dotted" names -- there is no expectation that they would convey any structural information. `@JsonProperty` will match the name but has no structural transformations.

From technical perspective Jackson operates in streaming/incremental fashion which makes it difficult to add structural transformations such as inferring multiple levels from convention such as dotted names.
There is some limited support for this, using `@JsonUnwrapped` but it wouldn't work here (it does sort of opposite).

There are no plans to make `@JsonProperty` do anything like this; although I think there is another issue for adding support for `@JsonWrapped` (see #512) which might do what you want.

**Comment by cowtowncoder** [comment]
I will close this; if there is desire to add support, please file a new issue explaining expected usage. New issue may refer this issue for background info.

**Comment by d3bt3ch** [comment]
@kiriakos You can achieve this by writing a custom deserializer.

An example could be

```
public final class KeySetDeserializer extends StdDeserializer<List<String>> {

    @Serial
    private static final long serialVersionUID = 1L;

    public KeySetDeserializer() {
        super(List.class);
    }

    @Override
    public List<String> deserialize(@NonNull JsonParser parser, @NonNull DeserializationContext context) throws IOException {
        Data data = parser.readValueAs(Data.class);
        return data.getKeys();
    }

    @lombok.Data
    private static final class Data {

        @JsonProperty("keys")
        private List<String> keys;
    }
}
```

The json structure is ...

```
{
    .......
    "data": {
        "keys": [
            "hmac",
            "rsa-1",
            "rsa-2",
            "test"
        ]
    },
    .......
}
```

We wanted our `POJO` to have a `keys` at top level and not under `Data`.

```
public final class KeySet {

    @JsonProperty("data")
    @JsonDeserialize(using = KeySetDeserializer.class)
    private List<String> keys;
}
```

Hope this solves your problem.
