### ISSUE TITLE
ObjectMapper : java.math.BigDecimal cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by aniketvsawant** [FasterXML/jackson-databind#3237]
Hi Team,

I am trying to convert POJO to string but having issues while using object mapper.  Please suggest.
FYI: BigDecimal field in the POJO having a negative value.

Thanks.

**Comment by yawkat** [comment]
Please give more context, e.g. a test case and full stack trace

**Comment by aniketvsawant** [comment]
Please ignore this issue. Internal configuration issue hence closing this issue.
