### ISSUE TITLE
Upper snake case property naming strategy

### ISSUE THREAD

**Issue by kennethjor** [FasterXML/jackson-databind#3238]
**Describe the solution you'd like**
A property naming strategy that does UPPER_SNAKE_CASE.

**Usage example**
The parameter `userId` is serialized as `{"USER_ID":<value>}`

I wasn't able to find this in the source, so apologies if I've just missed it.

**Comment by cowtowncoder** [comment]
Sounds like a potentially useful feature, if anyone wants to tackle this!
It could go in 2.14.0 (2.13.0 is feature frozen at this point).

**Comment by TanveshT** [comment]
Hello @cowtowncoder as it's mentioned as a `good first issue`, what can be a good entry point for the code base to understand and add this feature? I was looking to work on this issue

**Comment by cowtowncoder** [comment]
@TanveshT I think existing implementations for other standard in class `PropertyNamingStrategies` (as of Jackson 2.12) would be a good starting place.

**Comment by TanveshT** [comment]
Hey thanks @cowtowncoder, I make a shot at this issue and try to raise a PR.

**Comment by TanveshT** [comment]
@cowtowncoder PR has been raised for the issue, you can review it and if any changes are there I can commit them. Thank you

**Comment by cowtowncoder** [comment]
Thank you!

**Comment by cowtowncoder** [comment]
Excellent work @TanveshT! Thank you for contributing this -- I merged it in 2.13, will update release notes and so on, and it'll be in 2.13.0 once that gets out.

**Comment by Dagte** [comment]
I may be totally mistaken about this, but wouldn't this implementation that was named UpperSnakeCaseStrategy would be more accurately named ScreamingSnakeCaseStrategy?

I would expect UpperSnakeCaseStrategy to make userId to be serialised as {"User_Id":<value>}

**Comment by cowtowncoder** [comment]
@Dagte perhaps, but having been added a while ago this will be the name it shall be known as :)
