### ISSUE TITLE
Unbounded range

### ISSUE THREAD

**Issue by pawelxyz** [FasterXML/jackson-databind#3254]
After upgrade to version 2.12.x, my builds fail in Eclipse with this message:
"Invalid JDK version in profile 'java14+': Unbounded range: [14, for project com.fasterxml.jackson.core:jackson-databind com.fasterxml.jackson.core:jackson-databind:jar:2.12.3".
The problem goes away if I add close the range by adding the ")" character in file .m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.pom:
```
  <activation>
    <jdk>[14,)</jdk>
  </activation> 
```
I'm proposing to make this change permanently in the pom file.

**Comment by cowtowncoder** [comment]
Looks like this had been done for 2.13 already. Changed in 2.12 as well. Thanks!
