### ISSUE TITLE
Not setting ParsePosition causes Java to error on valid Dates 

### ISSUE THREAD

**Issue by texnewmex** [FasterXML/jackson-databind#3260]
**Describe the bug**
Java spec defines for the `Date parse(String source, ParsePosition pos)` method on `DateFormat` for it's `pos` parameter

> [...] on output, the position at which parsing terminated, or the start position if the parse failed.
https://docs.oracle.com/javase/7/docs/api/java/text/DateFormat.html#parse(java.lang.String,%20java.text.ParsePosition)

Jackson's `StdDateFormat` implementation overrides this method, but does nothing with the `pos` argument, so much as to literally call it `bogus`
https://github.com/FasterXML/jackson-databind/blob/5dc76cff304d64922faad92dd250d86b78b17569/src/main/java/com/fasterxml/jackson/databind/util/StdDateFormat.java#L562 

So Jackson returns a properly parsed Date, then Java throws an exception because it thinks Jackson errored:
https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/text/DateFormat.java#L355-L356
```java
ParsePosition pos = new ParsePosition(0);
Date result = parse(source, pos);
if (pos.index == 0)
    throw new ParseException("Unparseable date: \"" + source + "\"" ,
        pos.errorIndex);
```

**Expected behavior**
Set the parse position to a non-zero value so that Java does not error with valid dates.

**Comment by cowtowncoder** [comment]
@texnewmex Ok thank you for clarifying -- I will see what warnings to add. I do not want there to be a false expectation of this class being usable externally. There are couple of other classes that have sometimes been repurposed for external use and that tends to lead to issues.

**Comment by cowtowncoder** [comment]
Looking at code, I think it would make sense to actually even fail for `ParsePosition` that defines offset other than 0.
But I will not quite yet change that before 2.13.0 as there is no time to verify safety of doing that.
Further, I think that position may have been originally sort of supported when handling was delegated to `SimpleDateFormat` (somewhere before 2017, pre-2.9 or so?); it was probably passed on.

At this point there are references to offset location when constructing exceptions; this should be changed ideally to indicate problem location.

Will close this for now wrt documentation.
