### ISSUE TITLE
Json annotations are not working on generics

### ISSUE THREAD

**Issue by amiragl** [FasterXML/jackson-databind#3269]
**Describe the bug**
I'm using @JsonView and @JsonIgnore on simple classes (without generics) and it works fine.

But I have another case : inheritance using generics. I put the @JsonView/@JsonIgnore in the right get methods, but the filter is not working I always get all attributes in Json Body response..

**Version information**
Version : 2.10.5

`

**Comment by cowtowncoder** [comment]
I would really need a reproduction here: annotations should work on generic types just fine.
Reproduction would need to only use Jackson (not frameworks like Spring Boot, or Lombok (in case of Lombok, post-processed classes are fine, just not Lombok runtime)).

**Comment by cowtowncoder** [comment]
Not reproducible without a test case, closing. May be reopened with a reproduction on a recent version of Jackson (2.12.5 ideally).
