### ISSUE TITLE
Combination of @JsonIdentityInfo and @JsonValue does not work

### ISSUE THREAD

**Issue by m31collision** [FasterXML/jackson-databind#3286]
Suppose we have a simple class like this:
```java
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator)
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS)
@TupleConstructor
class C {
    int value
}
```
Arbitrary object will be serialized to:
```json
{
  "@class" : "C",
  "@id" : 1,
  "value" : 1
}
```
Note that both fields `@id` and `@class` are present.
But if you add `@JsonValue` method to class `C` like this:
```java
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator)
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS)
@TupleConstructor
class C {
    int value

    @JsonValue
    Map<String, String> custom() {
        Map.of("test", "" + value)
    }
}
```
JSON output will miss an `@id` field, although `@class` is still present:
```json
{
  "@class" : "C",
  "test" : "1"
}
```
Is this a bug or documented behaviour?

Tested versions: 2.12.4, 2.12.5, 2.13.0-rc2

**Comment by yawkat** [comment]
Why use `@JsonValue` here instead of `@JsonAnyGetter`?

**Comment by m31collision** [comment]
AFAIK `@JsonValue` is a full replacement of properties of current serializing bean, while `@JsonAnyGetter` is an additional properties to properties of serializing bean.

I tried with `@JsonAnyGetter` and it worked (both `@class` and `@id` added to json), but it *adds* properties but not replaces which is not always desired result.
I also tried to use `@JsonAnyGetter` with `@JsonIncludeProperties("non-existing property")` which would emulate `@JsonValue` but it also omits `@id` field.

**Comment by cowtowncoder** [comment]
Yes, @m31collision is correct: use of `@JsonValue` fully replaces serialization and this is likely why combination does not work. Whether it could and should work is a separate question; it certainly would be somewhat complicated regarding interaction of things, but I don't want to declare it impossible or something that should not be done.

At the moment, however, there isn't any simple or quick way to make that combination work so I would suggest working around the problem. Use of `@JsonAnyGetter` / `@JsonAnySetter` should work with `@JsonIdentityInfo`.

**Comment by yawkat** [comment]
You could also put a `@JsonAutoDetect` configuration on the class if you want to avoid implicit properties being serialized.

**Comment by cowtowncoder** [comment]
I don't think it is possible to really support combination of `@JsonIdentityInfo` and `@JsonValue`. Will marks as will-not-fix, close.
