### ISSUE TITLE
Add support for customized serializer output, when Map/List/Collection.size()==0

### ISSUE THREAD

**Issue by KonradMachotka** [FasterXML/jackson-databind#331]
Currently Jackson produces {},[],[] when non-null but empty Map/List/Collection is serialized.

With NullSerializer it is possible to replace {},[] output, but onlly when value is null.

I am asking for adding customization in situation, when Map/List/Collection field in Bean is not nulled, but it has no elements (it is empty).

For example in the current source of Jackson MapSerializer code I can see, the {} will be always written for non-null Map, even when there are no elements inside that Map. 
@Override
public void serialize(Map<?,?> value, JsonGenerator jgen, SerializerProvider provider)
throws IOException, JsonGenerationException
{
  jgen.writeStartObject(); // will write curly bracket {
  ..
  gen.writeEndObject(); // will write curly bracket }
}

I would like to see customization for writing custom-output (for example "null") in above situation for Map/List/Collection instead of non-customizable output: {} [] [] which we currently see with non-null but empty fields of type Map/List/Collection.

**Comment by cowtowncoder** [comment]
Note too that `@JsonInclude(Include.NON_EMPTY)` allows removal of output for such cases.

For now I will close this, as I am not quite sure how to support specific customizability; and since there is (I think) another feature request for specific case of serializing empty lists as `null`s.
