### ISSUE TITLE
Add serializer-cache size limit to avoid Metaspace issues from caching Serializers

### ISSUE THREAD

**Issue by mcolemanNOW** [FasterXML/jackson-databind#3311]
I know this is a topic that has been discussed before (#489 & #1905), but it has been a few years so I wanted to open the discussion again.

I see that there are changes coming in 3.0 to limit the size of the serializer cache to 4000 (#1994). Are there any other plans to allow tuning this size, adding a 'super flush', or letting the consumer provide the cache implementation (ex. with weak references)?

Our app servers have a lot of `DelegatingClassLoaders` sticking around due to reflection methods being stored in the `SerializerCache`(like `_accessorMethod` in `BeanPropertyWriter`) and it would be great if we had more control over the caching strategy so metaspace doesn't grow unbounded.

**Comment by cowtowncoder** [comment]
@pjfanning @ben-manes I think I'll try to do this (basically backport of #1994)
