### ISSUE TITLE
Unexcepted json format when use "SNAKE_CASE"

### ISSUE THREAD

**Issue by mark4z** [FasterXML/jackson-databind#3318]
**Describe the bug**

when use ObjectMapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE) ,the filed like 'sth2' will be format to 'sth2', not 'sth_2', it's normal?

**Version information**
Which Jackson version(s) was this for?

2.12.1

**To Reproduce**
If you have a way to reproduce this with:

1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.

**Additional context**

**Comment by yawkat** [comment]
Yes this is expected behavior. The exact behavior is documented here: https://fasterxml.github.io/jackson-databind/javadoc/2.8/com/fasterxml/jackson/databind/PropertyNamingStrategy.SnakeCaseStrategy.html
