### ISSUE TITLE
Activating a research fault localization bot on your project?

### ISSUE THREAD

**Issue by dginelli** [FasterXML/jackson-databind#3321]
Hi! 

We are software engineering researchers and are currently looking for active open-source projects where we could test a new cool software bot: flacocobot!

When a new pull request is open, if it has test failures/errors, flacocobot analyzes the failure and posts a diagnosis as comments to the pull request, highlighting the most suspicious lines that likely need to be analyzed to fix the bug.

flacocobot works as follows:

- When a new PR is open, if the test suite fails, flacocobot starts its analysis.
- The top k suspicious (potentially buggy) lines of code are then highlighted as comments to the PR.

We would love to have your feedback in order to understand what you like or you do not like, what we can improve, and if you find it useful!

If you are interested in trying it, we will run flacocobot on your project for a period of two weeks and then give you a 1-minute questionnaire to collect your feedback.

What do you think? Can we activate flacocobot for [jackson-databind](https://github.com/FasterXML/jackson-databind)?

Thanks,

Davide (@dginelli), André (@andre15silva), Matias (@martinezmatias), Benjamin (@danglotb), Martin (@monperrus)

You can find out more in our tools repos:
- https://github.com/SpoonLabs/flacoco
- https://github.com/eclipse/repairnator

**Comment by cowtowncoder** [comment]
I think it is FUCKING OBNOXIOUS to start filing issues automatically across Github.

Fuck this shit.

If you want to raise awereness go through mailing list and other proper channels.

**Comment by dginelli** [comment]
Hello @cowtowncoder,

First of all, I didn’t create automatically the issue. I read the issue templates that you provide because I wanted to see if you had some policies about opening issues for topics not directly related to the source code/feature/documentation etc. I did this precisely to avoid this type of situations because we do not want to bother the developers.

Having said that, in the “Issues” section of the project, there are these templates:

- Bug report;
- Documentation request;
- Feature request;
- Something else;
- Report a security vulnerability.

Since our request is neither a bug report nor a documentation request/feature request/security vulnerability, I chose the “Something else” template. Since the template is empty, I thought I could write our question directly in an issue. I was not aware about other channels or mailing lists that you provide.

Now, I tried to click on “Open a blank issue” and I read the information about the other channels. I think you could put that information also in the “Something else” template. In this way, you can avoid receiving this kind of requests.

Sorry for bothering you, it was not our intention.

**Comment by GedMarc** [comment]
@dginelli Wow thanks though, bot it may not be copy paste it certainly is if not - 

https://github.com/primefaces/primefaces/issues/8066

You need to shop elsewhere, I agree with @cowtowncoder  - this is intrusive advertising, not only to mention that we pretty much know of all the faults and reasons why, and why it was left there as well.. you can definitely write too clean code :)

Please stop, I don't want to click that report for service abuse on intrusive product advertising
