### ISSUE TITLE
Get parent json string inside DeserializationProblemHandler

### ISSUE THREAD

**Issue by steve-todorov** [FasterXML/jackson-databind#3324]
Hey there,

I posted [this question on SO](https://stackoverflow.com/questions/69931167/get-parent-json-string-inside-deserializationproblemhandler-jackson). 

In short, I'm working with a remote API which can change and I have no control over it. This is why I would like to do some logging when unknown properties appear in the received JSON so I can take action when necessary. 

To do this, I have written myself a small jackson module which has a `DeserializationProblemHandler` implementation which logs those "unknown properties". This works just fine, but I want to make my life easier and add more context to the logged message like the JSON root string which was being parsed so I know what actually broke the deserialization, instead of a vague "oh well" warning.

So having the following JSON example:

```json
{ "myUnknownProperty": "value123", "myIgnoredProperty": true, "myKnownProperty": true }
```

A log should look something similar to this:

```
WARN: Found unexpected property while parsing json: /myUnknownProperty (type: com.foo.PartiallyIgnoredPOJO); JSON { "myUnknownProperty": "value123", "myIgnoredProperty": true, "myKnownProperty": true }
```
<details>
    <summary>Example Code</summary>

    import com.fasterxml.jackson.annotation.JsonCreator;
    import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
    import com.fasterxml.jackson.annotation.JsonProperty;
    import com.fasterxml.jackson.core.JsonParser;
    import com.fasterxml.jackson.core.JsonProcessingException;
    import com.fasterxml.jackson.core.Version;
    import com.fasterxml.jackson.databind.DeserializationContext;
    import com.fasterxml.jackson.databind.DeserializationFeature;
    import com.fasterxml.jackson.databind.JsonDeserializer;
    import com.fasterxml.jackson.databind.Module;
    import com.fasterxml.jackson.databind.ObjectMapper;
    import com.fasterxml.jackson.databind.deser.DeserializationProblemHandler;
    import org.junit.jupiter.api.Test;
    import org.slf4j.Logger;
    import org.slf4j.LoggerFactory;

    import javax.annotation.Nullable;
    import java.io.IOException;

    import static org.mockito.Mockito.mock;
    import static org.mockito.Mockito.verify;

    public class ExampleTest
    {

        // Test
        @Test
        public void mockTest() throws JsonProcessingException
        {
            Logger logger = mock(Logger.class);
            try
            {
                new ObjectMapper().disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                                  .registerModule(new UnknownPropertyModule(logger))
                                  .readValue(partiallyIgnoredSONSample, PartiallyIgnoredPOJO.class);
            }
            finally
            {
                verify(logger).warn(UnknownPropertyModule.MESSAGE,
                                    "/myUnknownProperty",
                                    PartiallyIgnoredPOJO.class,
                                    partiallyIgnoredSONSample);
            }
        }

        // Implementations
        private static class UnknownPropertyDeserializationProblemHandler extends DeserializationProblemHandler
        {

            private final Logger logger;
            private final String format;

            UnknownPropertyDeserializationProblemHandler(final Logger logger, final String format)
            {
                this.logger = logger;
                this.format = format;
            }

            @Override
            public boolean handleUnknownProperty(final DeserializationContext context,
                                                 final JsonParser parser,
                                                 final JsonDeserializer<?> deserializer,
                                                 final Object beanOrClass,
                                                 final String propertyName) throws IOException
            {
                final Class<?> type = beanOrClass.getClass();
                String jsonPath = parser.getParsingContext().pathAsPointer().toString();
                String json = "__How_to_get_the_entire_JSON_from_the_root___";
                logger.warn(format, jsonPath, type, json);
                return false;
            }

        }

        private static class UnknownPropertyModule extends Module
        {
            public static final String MESSAGE = "Found unexpected property while parsing json: {} (type: {}); JSON: {}";
            private final Logger logger;

            public UnknownPropertyModule(@Nullable final Logger logger)
            {
                this.logger = logger != null ? logger : LoggerFactory.getLogger(getClass().getName());
            }

            @Override
            public String getModuleName()
            {
                return getClass().getSimpleName();
            }

            @Override
            public Version version()
            {
                return Version.unknownVersion();
            }

            @Override
            public void setupModule(Module.SetupContext context)
            {
                context.addDeserializationProblemHandler(new UnknownPropertyDeserializationProblemHandler(logger, MESSAGE));
            }
        }

        // Example json & mapping.
        private static final String partiallyIgnoredSONSample = "{ \"myUnknownProperty\": \"value123\", \"myIgnoredProperty\": true, \"myKnownProperty\": true }";

        @JsonIgnoreProperties("myIgnoredProperty")
        private static class PartiallyIgnoredPOJO
        {

            private final boolean myKnownProperty;

            @JsonCreator
            public PartiallyIgnoredPOJO(@JsonProperty("myKnownProperty") boolean myKnownProperty)
            {
                this.myKnownProperty = myKnownProperty;
            }

            public boolean getMyKnownProperty()
            {
                return myKnownProperty;
            }

        }

    }

</details>

<details>
   <summary>Dependencies</summary>

    <dependencies>
        
        <dependency>
            
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>
        

        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
        </dependency>
        

        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        

        
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty-core</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty-http</artifactId>
        </dependency>
        

        
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit-pioneer</groupId>
            <artifactId>junit-pioneer</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <scope>test</scope>
        </dependency>
        

    </dependencies>

</details>

**Comment by yawkat** [comment]
`JsonParser.getCurrentLocation` may be what you want

**Comment by steve-todorov** [comment]
Thanks for your reply @yawkat!

Unfortunately I don't really see how calling `parser.getCurrentLocation()` helps? 
![image](https://user-images.githubusercontent.com/2303663/141795239-843cd2da-7817-4de4-9916-bea0fbb50fe3.png)

Would you please post an example using the above self-contained code?

**Comment by yawkat** [comment]
`JsonLocation` should include source info if it's available. But you're right, in your case, it isn't. Apparently unknown property handling stores all the data in a TokenBuffer, which does not have backing source data that can be displayed.

**Comment by cowtowncoder** [comment]
On Mon, Nov 15, 2021 at 12:44 AM Jonas Konrad ***@***.***>
wrote:

> JsonParser.getCurrentLocation may be what you want
>

Close: I think `JsonParser.getParsingContext()` is what could help here --
it exposes a bit of information about ancestor path (property names, array
indexes).

-+ Tatu +-

**Comment by cowtowncoder** [comment]
On Mon, Nov 15, 2021 at 9:41 AM Tatu Saloranta ***@***.***> wrote:

> On Mon, Nov 15, 2021 at 12:44 AM Jonas Konrad ***@***.***>
> wrote:
>
>> JsonParser.getCurrentLocation may be what you want
>>
>
> Close: I think `JsonParser.getParsingContext()` is what could help here --
> it exposes a bit of information about ancestor path (property names, array
> indexes).
>

Uh sorry, no, I should have read the whole question here.

If the question is whether the whole input is available, the answer is
simple "No".
Jackson parser is fully streaming and only reading chunks it needs
(buffered).
To retain original content you will need to keep a copy: one possibility
would be to use a chaining (or "T") `Reader`
or `InputStream` -- some frameworks may already buffering the whole
content, too.

One possibility for injecting buffering Reader/InputStream is to register
`InputDecorator` for `JsonFactory`: that allows
code to create a wrapped instance.

I hope this helps,

-+ Tatu +-

**Comment by steve-todorov** [comment]
Thanks to both of you for your replies!

Yes, the question was if I can get the full `input`. I am not familiar with the Jackson code base yet so I will have to dig into your suggestions @cowtowncoder and see where it leads in due time. In some cases I see the `UnrecognizedPropertyException` contains the full JSON string which I assume it gets via `p.getCurrentLocation().toString()` somewhere in the `BeanDeserializer`? :)

**Comment by cowtowncoder** [comment]
Yes, if input given is the full document (such as passing `String` or `byte[]`), and small enough, then it is indeed included.
That information would be included in `JsonLocation`, accessible using `JsonLocation.contentReference()` (added in 2.13 -- formerly there is less useful `getSourceRef()`).
So if your input source happens to be `String[]` or `byte[]` or `char[]` you can probably access it.

**Comment by yawkat** [comment]
I think in this specific case it is still missing if you use a `String` content source, for the reason I gave above: What is actually passed into `handleUnknownProperty` is a `TokenBuffer`, not the original parser

**Comment by cowtowncoder** [comment]
True, @yawkat, good point. It may be rather difficult to access it at all, in such case -- would need to attach full input with `ThreadLocal` or (depending) as `ContextAttribute` for `DeserializationContext`.

**Comment by cowtowncoder** [comment]
Closing as there is (nor likely will be) a way to get full original content -- Jackson, in general, does not keep track of it.
But conversely there are ways to access the original input source which IN SOME CASES does allow access (when passed as `String` or `byte[]`).
