### ISSUE TITLE
Shouldn't Long and Int Nodes be equivalent?

### ISSUE THREAD

**Issue by tommack** [FasterXML/jackson-databind#333]
If I build an ObjectNode with small "Long" or "long" values, I cannot round trip the the node into an equivalent node.

```java
    @Test
    public void test_long_obj() throws IOException {
        ObjectMapper om = new ObjectMapper();
        ObjectNode node = om.createObjectNode();
        // this node tree will contain a LongNode
        node.put("long", Long.valueOf(1234));
        String string = om.writeValueAsString(node);
        // this newTree will contain an IntNode
        JsonNode newTree = om.readTree(string);
        // this will be false because IntNode never equals LongNode
        assertEquals(node, newTree);
    }

    // this test also fails

    @Test
    public void test_long_primitive() throws IOException {
        ObjectMapper om = new ObjectMapper();
        ObjectNode node = om.createObjectNode();
        node.put("long", 1234L);
        String string = om.writeValueAsString(node);
        JsonNode newTree = om.readTree(string);
        assertEquals(node, newTree);
    }
    
    // these two tests pass
    
    @Test
    public void test_int_obj() throws IOException {
        ObjectMapper om = new ObjectMapper();
        ObjectNode node = om.createObjectNode();
        node.put("int", Integer.valueOf(1234));
        String string = om.writeValueAsString(node);
        JsonNode newTree = om.readTree(string);
        assertEquals(node, newTree);
    }
    
    @Test
    public void test_int_primitive() throws IOException {
        ObjectMapper om = new ObjectMapper();
        ObjectNode node = om.createObjectNode();
        node.put("int", 1234);
        String string = om.writeValueAsString(node);
        JsonNode newTree = om.readTree(string);
        assertEquals(node, newTree);
    }

```

Shouldn't the same logic that is used when deserializing the String be used when creating the tree? If I pass in a long value that will fit in an int, why not create an IntNode? Is there a way for me to access this logic when I'm creating a tree? Is there a way to force a tree into a canonical representation that can be compared against another tree? Is there a method besides "equals" that compares two trees as JSON entities and not Maps and Lists of Java Objects?

**Comment by cowtowncoder** [comment]
One more note: #790 addresses the equality question as well, allowing bit simpler external/custom equality comparison.

**Comment by cowtowncoder** [comment]
Actually, no. I have to contradict myself and claim that it does not make sense to add such logic into `JsonNodeFactory`. For 2.6.0, I will add a switch that will allow such coercion, but leave it disabled by default. Otherwise we can not support features like #504 which will need more control over exact kind of `NumberNode` being constructed.

**Comment by cowtowncoder** [comment]
Come to think of it, I won't add a configuration method. It is easy enough to sub-class factory, add functionality that way; and adding more state into base implementation seems like a wrong idea due to extensive sharing of the default node factory.
