### ISSUE TITLE
JDK15: broken default serialization for CharSequence subtypes

### ISSUE THREAD

**Issue by seregamorph** [FasterXML/jackson-databind#3331]
**Describe the bug**
The default CharSequence-subclasses serialization is broken since JDK 15.

**Version information**
2.12.x
2.13.x

**To Reproduce**
Serialize class like this:
```
    public static final class AppId implements CharSequence {

        private final long value;

        public AppId(long value) throws IllegalArgumentException {
            this.value = value;
        }

        public static AppId valueOf(String value) throws IllegalArgumentException {
            if (value == null) {
                throw new IllegalArgumentException("value is null");
            }
            return new AppId(Long.parseLong(value));
        }

        @Override
        public int length() {
            return toString().length();
        }

        @Override
        public char charAt(int index) {
            return toString().charAt(index);
        }

        @Override
        public CharSequence subSequence(int start, int end) {
            return toString().subSequence(start, end);
        }

        // pay attention: no @JsonValue here
        @Override
        public String toString() {
            return Long.toString(value);
        }
    }
```
Create a default `ObjectMapper` and then serialize the value, say `AppId.valueOf("3074457345618296002")`
In JDK 8 it is serialized by default (as expected):
```
"3074457345618296002"
```
In JDK 17 it is serialized wrong:
```
{"empty":false}
```

**Expected behavior**

**Additional context**
There is a default serialization for classes defined as subclasses of `java.lang.CharSequence`. This logic is defined in `BasicSerializerFactory.findSerializerByAddonType(SerializationConfig, JavaType, BeanDescription, boolean)`:
```
if (CharSequence.class.isAssignableFrom(rawType)) {
    return ToStringSerializer.instance;
}
```
It is working pretty well and reliable till JDK 15. This JDK version introduces new method in `java.lang.CharSequence`:
```
...
     *
     * @since 15
     */
    default boolean isEmpty() {
        return this.length() == 0;
    }
```
As the result this branch in `BeanSerializerFactory`:
```
AnnotatedMember anyGetter = beanDesc.findAnyGetter();
if (anyGetter != null) {
```
becomes visited in JDK 17 (there is a property "empty") and default `ToStringSerializer` is not applied anymore (object is serialized as bean).

**Comment by cowtowncoder** [comment]
Dup of #3305 ?

**Comment by seregamorph** [comment]
yes
