### ISSUE TITLE
Custom handling of unknown/ignored properties outside of a deserializer

### ISSUE THREAD

**Issue by oliveryasuna** [FasterXML/jackson-databind#3335]
In a custom deserializer, one can simply look at the tree (`JsonNode`) to determine if the tree contains unexpected properties. It would be nice if developers could implement custom handling, rather than something like `@JsonAnyGetter` and `@JsonAnySetter`. Right now, I cannot find a solution other than in a deserializer.

**Comment by cowtowncoder** [comment]
Have you looked into `DeserializationProblemHandler`? It was originally designed to allow handling of unknown properties and might work for you.
Note, too, that `@JsonAnySetter` when added to a method would also allow customized handling (although needs to be a method in value class, cannot be external0.

**Comment by oliveryasuna** [comment]
@cowtowncoder Thank you so much. I was not aware of `DeserializationProblemHandler`.
