### ISSUE TITLE
`Set.of()` (Java 9) cannot be deserialized with polymorphic handling

### ISSUE THREAD

**Issue by Sam-Kruglov** [FasterXML/jackson-databind#3344]
Hi, 2.13.0 doesn't seem to work with `Set.of()` and I don't see any tests for it, there're only for `List.of()` and `Map.of()`.

_Originally posted by @Sam-Kruglov in https://github.com/FasterXML/jackson-databind/issues/2900#issuecomment-988333797_

```java
public static void main(String[] args) throws Exception {
    ObjectMapper mapper = JsonMapper.builder()
            .findAndAddModules()
            .activateDefaultTyping(LaissezFaireSubTypeValidator.instance, EVERYTHING, JsonTypeInfo.As.PROPERTY)
            .build();
    Set<?> set = Set.of("a", "b", "c");
    String actualJson = mapper.writeValueAsString(set);
    Set<?> output = mapper.readValue(actualJson, Set.class);
}
```
Output: 
```java
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.util.ImmutableCollections$SetN` (no Creators, like default constructor, exist): no default no-arguments constructor found
```

Same example with `List.of()` works and is already here:
https://github.com/FasterXML/jackson-databind/blob/f584290e6fe03f4a0505cfae4a0fb2c8cebc1cc6/src/test-jdk14/java/com/fasterxml/jackson/databind/failing/Java9ListsTest.java#L50-L53

**Comment by cowtowncoder** [comment]
Since tests are under `failing`, likely those won't work on later JDKs either. But definitely worth adding a test for `Set` as well.

**Comment by Sam-Kruglov** [comment]
I can confirm that I was running this example on JDK 11 on 2.13.0 and List.of() works fine
