### ISSUE TITLE
JsonNodeDeserializer ignores custom Deserializer Configuration

### ISSUE THREAD

**Issue by VagrantBlackbird** [FasterXML/jackson-databind#3347]
**Describe the bug**
When using an **ObjectMapper** with custom configuration (for example to deserialize empty strings as null values), using the _#readTree(String content)_ method will not consider custom deserialization configurations. This is caused by the fact that internally, **JsonNodeDeserializer** is used when calling that method, which has its own serialization implementation. 
This is inconsistent with methods like _#readValue(String content, Class<T> valueType)_ which do take custom deserialization configuration into account.

Since the documentation of ObjectMapper suggests the two approaches (i.e. serialized to a Java Object and serializing to the tree representation) are equivalent and that custom deserializers can be added to change the behavior, I'd expect deserialization to create JSON tree representations to also be configurable in this manner.

**Version information**
2.13.0

**To Reproduce**
```java
import static org.junit.jupiter.api.Assertions.assertAll;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.io.IOException;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.deser.std.StringDeserializer;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.node.JsonNodeType;

public class JsonNodeDeserializerTest {
	
	private final ObjectMapper mapper;
	private final String filledInText = "{\"text\":\"hello\"}";
	private final String emptyText = "{\"text\":\"\"}";
	private final String nullText = "{\"text\":null}";
	
	private JsonNodeDeserializerTest() {
		mapper = new ObjectMapper();
		
		SimpleModule module = new SimpleModule();
		module.addDeserializer(String.class, new EmptyStringDeserializer());
		mapper.registerModule(module);
	}
	
	@Test
	@DisplayName("Deserialize filled in text")
	void parseFilledInText() throws JsonProcessingException {
		TextDto textDto = mapper.readValue(filledInText, TextDto.class);
		assertEquals("hello", textDto.getText());
		
		JsonNode jsonNode = mapper.readTree(filledInText);
		JsonNode textNode = jsonNode.get("text");
		
		assertAll(
			() -> assertEquals(JsonNodeType.STRING, textNode.getNodeType()),
			() -> assertEquals("hello", textNode.textValue())
		);
	}
	
	@Test
	@DisplayName("Deserialize empty text")
	void parseEmptyText() throws JsonProcessingException {
		TextDto textDto = mapper.readValue(emptyText, TextDto.class);
		assertNull(textDto.getText());
		
		JsonNode jsonNode = mapper.readTree(emptyText);
		JsonNode textNode = jsonNode.get("text");
		assertAll(
			() -> assertEquals(JsonNodeType.NULL, textNode.getNodeType()), //Fails, this is a STRING node
			() -> assertNull(textNode.textValue()) //Fails, returns empty string
		);
	}
	
	@Test
	@DisplayName("Deserialize null text")
	void parseNullText() throws JsonProcessingException {
		TextDto textDto = mapper.readValue(nullText, TextDto.class);
		assertNull(textDto.getText());
		
		JsonNode jsonNode = mapper.readTree(nullText);
		JsonNode textNode = jsonNode.get("text");
		assertAll(
			() -> assertEquals(JsonNodeType.NULL, textNode.getNodeType()),
			() -> assertNull(textNode.textValue())
		);
	}
	
	//From https://github.com/FasterXML/jackson-databind/issues/768
	private static class EmptyStringDeserializer extends JsonDeserializer<String> {
		
		@Override
		public String deserialize(JsonParser parser, DeserializationContext context) throws IOException, JsonProcessingException {
			if (parser.getCurrentToken() == JsonToken.VALUE_STRING && "".equals(parser.getText())) {
				return null;
			}
			
			return StringDeserializer.instance.deserialize(parser, context);
		}
	}
	
	private static class TextDto {
		private String text;
		
		public String getText() {
			return text;
		}
	}
}
```

**Expected behavior**
Custom deserialization configuration affects the JSON tree representation created by the different _readTree()_ methods **or** documentation clarifies that this group of methods can not be customized in this manner.

**Comment by cowtowncoder** [comment]
This sounds like a misunderstanding of things: when reading a tree (`JsonNode`, or more generically, `TreeNode`), other types are not considered and this is by design. Any String-valued properties are read as `TextNode`s, not as `String`s.
Put another way, tree nodes (`JsonNode`) are not POJOs and do not have typed properties in the same sense.
This means that you cannot (re)configure handling the same way you would for POJO values.

You can override deserializer for `JsonNode` itself and customize deserialization; however, there are no convenient ways to customize deserialization of `JsonNode` scalar values. So it is also not possible currently to override deserializer for `TextNode`.

**Comment by VagrantBlackbird** [comment]
Hey, thanks for the response. I understand the reasoning, but for me that's something that wasn't too clear from the documentation, so that's a bit where the confusion arose. I'm also not sure whether that can be easily improved, by the way, so I'll just await any extensions of the functionality that seem to be locking positive, thanks!

**Comment by dobijan** [comment]
For those struggling to attach custom logic to tree deserialization I can offer a solution that is probably feasible in most scenarios. 

Personally I wanted to process strings before they'd be embedded into the structure, be that structure a POJO or a `JsonNode`. At first I also thought that a custom `String` deserializer would be sufficient but alas.

My alternative for trees was to customize the `JsonNodeFactory` used by the `ObjectMapper`.

First implement your factory either by extension or composition. The example is just that, an example:
```java
public class MyTextCapitalizingJsonNodeFactory extends JsonNodeFactory {

    public MyTextCapitalizingJsonNodeFactory(boolean exactBigDecimals) {
        super(exactBigDecimals);
    }

    @Override
    public TextNode textNode(String text) {
        return super.textNode(text.toUpperCase());
    }
}
```

You can override other node creation methods too.

Then, configure your objectMapper:
```java
public static ObjectMapper objectMapper() {
    return JsonMapper.builder()
            // ... other configuration ...
            .nodeFactory(new MyTextCapitalizingJsonNodeFactory(true /* or false */))
            .build();
}
```

Test:

```java
public class CapitalizingStringDeserializationTest {

    @Test
    @SneakyThrows
    public void shouldCapitalizeWhenDeserializingIntoTree() {
        // Arrange
        ObjectMapper om = objectMapper();
        String payload = "{\"foo\":\"bar\"}";

        // Act
        JsonNode tree = om.readTree(payload);
        String result = om.writeValueAsString(tree);

        // Assert
        assertThat(result).isEqualTo("{\"foo\":\"BAR\"}");
    }
}
```

**Comment by cowtowncoder** [comment]
Thank you for sharing @dobijan !
