### ISSUE TITLE
Give Ability to Replace existing Key with New Key and KEEP SAME ORDER as existing key

### ISSUE THREAD

**Issue by bmistry13** [FasterXML/jackson-databind#3348]
**Is your feature request related to a problem? Please describe.**

I know JSON Is key is order less according to speciation but we are using JSON for diff and order is very important when doing diff. Hence, the put and remove method is messing order in LinkedhashMap used as a data structure to store Objects.  I know LinkedHashMap does not provide replace method to replace keys but it is very very useful to provide this functionality.

For example, 

Problem:

```{ 
"1" : "v1",
"2" : "v1",
"3" : "v1",
}
```

Now, If I wanted to KEEP the key order and replace ‘key and value’ at the position of  "2" but keep the position. 

((ObjectNode)JsonNode root).remove("2","v5");
((ObjectNode)JsonNode root).put("22","v6");
I will end up with:

```
{ 
"1" : "v1",
"3" : "v1",
"22" : "v6"
}
```

But I would like to keep the order of the old key:

```
{ 
"1" : "v1",
"22" : "v6"
"3" : "v1",
}
```

The behavior I would like to have to replace the key at position "2" with a new key "22".

**Describe the solution you'd like**
The behavior I would like to have to replace key at position "2" with new key "22".

Can Object Node class have the following method which preciously does replace and keep the position:
```
replaceAtPosition(String originKey, String newKey, JsonNode value)
{
	replaceAtPosition(_children, originKey, newKey, value);

}
```
```
/**
   * Replaces the {@param originKey} and it's value with the new {@param key} and {@param value} for
   * the {@param map}. <b>CAUTION: This only works on {@link LinkedHashMap}!</b>
   *
   * @param map a {@link LinkedHashMap} to replace the key and value on
   * @param originKey the KEY which will be replaced
   * @param key the new KEY used
   * @param value the new VALUE used
   * @param <K> type of the KEYs for the {@link Map}
   * @param <V> type of the VALUEs for the {@link Map}
   */private static <K, V> void replaceAtPosition(Map<K, V> map, K originKey, K key, V value) {
    assert (map != null);
    assert !map.containsKey(key);
    Map<K, V> newMap = new LinkedHashMap<>(map.size());
    for (Map.Entry<K, V> entry : map.entrySet()) {
      if (entry.getKey().equals(originKey)) {
        newMap.put(key,value);
      }else{
        newMap.put(entry.getKey(),entry.getValue());
      }
    }
    map.clear();
    map.putAll(newMap);
  }
```

**Usage example**
If you have a clear idea of how to use the proposed new/modified feature, please show an example.
ObjectNode.replaceAtPosition(String originKey, String newKey, JsonNode value)
**Additional context**
Add any other context about the feature request here.

If you have a better way to do this rename of key and keep the same position then let me know.

**Comment by yawkat** [comment]
fwiw it is technically possible to update a LHM entry value through the `Map.Entry#setValue` method. It is not necessary to rebuild the full map

**Comment by bmistry13** [comment]
Hi @cowtowncoder and @yawkat,

Thanks for answering the question.  I wanted to do this generically in our code how do I tell mapper to use ObjectNode Type of MyObjectNode type.  How do I inject MyObjectNode which would subtype of ObjectNode?  

We use following code:
JsonNode root = mapper.readTree('json string').

Do you have something that I can set my own factory? Something like this:
mapper.setJSONFACTORY ( new MYJsonNodeFactory)

I am sorry I am new to the Jacksonian data binding.  So asking for a reference.

Thanks in advance for help!

Thanks,

Bhavesh

**Comment by bmistry13** [comment]
Thank you all for your help!

**Comment by cowtowncoder** [comment]
@bmistry13 Great! Glad you were able to figure it out -- this is not something that is well documented or in wide use. But it is intended to be possible and I am happy it can be made to work the way you wanted.
