### ISSUE TITLE
JsonTypeInfo is ignored when serializing a list of annotated object

### ISSUE THREAD

**Issue by rabolfazl** [FasterXML/jackson-databind#336]
It seems that JsonTypeInfo is somehow ignored when serializing a list of annotated object. The following is some piece of code describing the situation.

```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "clazz")
public class ProjectElement extends BaseObject {
    private Long id = 10L;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
}

public abstract class AbstractTask extends ProjectElement {
}

public class Task extends AbstractTask {
}
```

The following two pieces of code produce the results shown:

```
Task aTask = new Task();
objectMapper.writeValueAsString(aTask)
```

Outputs: {"id":10, "clazz":"Task"}

```
Task aTask = new Task();
List aList = new ArrayList();
aList.add(aTask);
objectMapper.writeValueAsString(aList);
```

Outputs: [{"id":10}]

"clazz" is not produced in the second code. why?

**Comment by goldenrat** [comment]
Don't you think this will work ? 

```
public abstract class AbstractTask {
     @JsonProperty("clazz")
     public String getClassName() {
         return this.getClass().getName();
     }
}
```

This will force the even with generics you will always have `clazz` in your key

**Comment by cowtowncoder** [comment]
@goldenrat That will simply add type-erased `Class`, which does not contain generic type information.

**Comment by jgribonvald** [comment]
I think I'm having the same problem, but how to solve it ? 
here are the details of my problem : http://stackoverflow.com/questions/37663404/jackson-xml-problems-on-serializing

**Comment by cowtowncoder** [comment]
@jgribonvald Please either discuss this on user mailing list, or create a new issue (if it's for XML, for `jackson-dataformat-xml`; if you can confirm it also affects JSON, here on `jackson-databind`).
Comments on closed issued should be limited to exactly same problem, and often similar symptoms may be produced by different underlying root causes. In addition even if issues are related release notes are easiest to follow when history of issue does not get complicated with resolution for one version but some followup work later on.

Thanks!
