### ISSUE TITLE
Define deserializer for class and inheritance

### ISSUE THREAD

**Issue by cunhazera** [FasterXML/jackson-databind#3370]
I have many classes that extend from `CustomPageImpl`, and I created this deserializer:

``` java
public class PageModule extends SimpleModule {
    private static final long serialVersionUID = 1L;

    public PageModule() {
        addDeserializer(CustomPageImpl.class, new PageDeserializer());
    }
}
```

I have many classes like this:
``` java
public class Example extends CustomPageImpl<ExampleDTO> {
    private static final long serialVersionUID = -1;

    public Example() {
    }
}
```

It's working if I do it:
``` java
Page<CustomPageImpl> res = new ObjectMapper().registerModule(new PageModule()).readValue(json, new TypeReference<CustomPageImpl>() {
        });
```

But doesn't work if I do it:
``` java
Page<Example> res = new ObjectMapper().registerModule(new PageModule()).readValue(json, new TypeReference<Example>() {
        });
```

How can I add a deserializer that works on both parent and child class?

**Comment by cowtowncoder** [comment]
This will not work with `SimpleModule` as deserializer lookup checks for exact type, and not for any of possible parent/child relationships.

You will need to implement `Module`, register custom `Deserializers` (and not `SimpleDeserializers`) implementation, and that will get a callback to get `JsonDeserializer` (method `findBeanDeserializer()`).
That's where you can use whatever logic to see if you have custom deserializer for given `JavaType`.
