### ISSUE TITLE
Deserialization not working with valueOf  if constructor is annotated with @java .beans.ConstructorProperties

### ISSUE THREAD

**Issue by Fischblick** [FasterXML/jackson-databind#3374]
**Describe the bug**
Deserialization not working if the constructor is annotated with `@java .beans.ConstructorProperties` and has a static factory method `valueOf`. The annotation `ConstructorProperties` is generated with lombok. If you remove the annotation then the deserialization is working with `valueOf` but it is not possible to deserialize other object if they do not have a noArgsConstructor therefor we need that annotation.

**Version information**
The attached test is working with version 2.11.4.
It is **NOT** working with version >= 2.12.1

**To Reproduce**
Run the attached test with version eg 2.13.1. Example project is attached.

**Expected behavior**
It is possible to deserialize with static `valueOf` method.
[jackson-example.zip](https://github.com/FasterXML/jackson-databind/files/7882825/jackson-example.zip)

**Comment by cowtowncoder** [comment]
Possibly not a bug but `@ConstructorProperties` implies use of "Properties"-style Creator method, whereas `valueOf()` usually requires "Delegating"-style. Difference being that in former incoming value must be JSON Object with matching named properties, whereas delegating can take any value.

Also: if both `valueOf()` and constructor were annotated, only one of these would be used. I do not remember how tie-breaking works (delegating vs properties-based).

But basically if you want `valueOf()` factory method to be used, you will need to get rid of `@ConstructorProperties` annotation.
Fortunately there is 

    MapperFeature.INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES

which you can disable to prevent its use. This might solve your case?

**Comment by Fischblick** [comment]
Thank you for the very quick response and the hint to `MapperFeature.INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES`. If I understand it correct than this MapperFeature will not solve our issue.

**All** our DTOs have an  AllArgsConstructor with the annotation `@java.beans.ConstructorProperties` from lombok and they have  **no** NoArgsConstructor at all. ConstructorProperties works like a json creator. That's fine for "usual" Objects. It is possible to deserialize this kind of objects.

Some DTOs have besides the AllArgsConstructor with the annotation `ConstructorProperties` a `static valueOf` method. These kind of objects are WrapperObjects. Older versions of jackson eg 2.11.4 prefer the `static valueOf` method for deserialization, newer versions throw an `MismatchedInputException` for WrapperObjects if they try to derserialize it.

If we now disable the `ConstructorProperties` feature with `INFER_CREATOR_FROM_CONSTRUCTOR_PROPERTIES`, than we cannot deserialize all "usual" objects. We can only deserialize WrapperObjects. This means that we have to work on all our "usual" DTOs to get diserialization working with new jackson versions. We have to add a NoArgsConstructor. Sometimes it is not possible because it is not our DTO object, it is a foreign dependency. This is some work for our objects and error prone if we forget one.

If we enable the `ConstructorProperties` feature than our "usual" objects are working but we cannot deserialize our WrapperObjects. Same issue as above. We have to change them and have to annotate it with `@JsonCreator` if it is not a foreign dependency.

The attached demo project includes one "usual" object and one WrapperObject and a test. You can see that the test is green and deserialization is working with 2.11.4 without adaption of a "usual" or a WrapperObject. The test is red for newer versions.

Thank you for any further suggestions and hints.

**Comment by cowtowncoder** [comment]
Ok, one quick note: `static valueOf()` with NO annotation should only ever be discovered for certain types, and have lower precedence than something that is annotated (with `@ConstructorProperties` or `@JsonCreator`).
But `valueOf(value)` really should never have `@ConstructorProperties` as that cannot infer "delegating" mode. So it seems odd such annotation did exist.

Assuming those do exist, however, one thing you could do to "hide" it would to override method `findCreatorAnnotation()` of `JacksonAnnotationIntrospector` and change behavior there -- determining if you have the old case (and if so returning `null`) or otherwise calling `super.findCreatorAnnotation()`.

**Comment by Fischblick** [comment]
Thanks for the advice.
It looks like we have to change the code.

I think it is not specified that `@JsonCreator` on a `valueOf(value)` method has a higher priority than `@ConstructorProperties` on a constructor. It is working with new version 2.13.1 but maybe not in the future. What do you think?

Example:

`public class WrapperType {
    private final String value;

    @ConstructorProperties({"value"}) // generated with lombok for all DTOs
    public WrapperType(String value) {
        this.value = value;
    }


    // annotation needed for new versions old versions took always the valueOf method
    @JsonCreator
    public static WrapperType valueOf(String value) {
        return new WrapperType(value);
    }
}`

**Comment by cowtowncoder** [comment]
Right, precedence of these cases is difficult to deduce or specify at this point in time.

There are no plans to change the precedence, for what that is worth, and I think there are existing unit tests that do cover this implicit precedence between (static) factory methods and constructors.

If someone has time to figure out existing rule(s) and suggest improvements to Javadocs (of `@JsonCreator`, I think), I'd be happy to make those changes (merge PR against `jackson-annotations`).

**Comment by Fischblick** [comment]
Thanks for the support.
