### ISSUE TITLE
How to gracefully handle a string instead of json-string

### ISSUE THREAD

**Issue by sodaRyCN** [FasterXML/jackson-databind#3376]
When using objectmapper to convert string to String.class, it is possible that the string is just a string and not a jsonstring.
More abstractly, how to know that the string is serialized before converting

**Comment by cowtowncoder** [comment]
This is not a user question forum: please use mailing list:

https://groups.google.com/g/jackson-user

or chat

https://gitter.im/FasterXML/jackson-databind
