### ISSUE TITLE
How to implement handleMissingInstantiator？

### ISSUE THREAD

**Issue by asasas234** [FasterXML/jackson-databind#3378]
I want to deserialize some classes that don't have a default constructor and are part of a framework that I can't modify, such as org.springframework.http.ResponseEntity. searching I learned that I can inherit from the DeserializationProblemHandler class and implement handleMissingInstantiator to solve this problem, but I'm not sure how to implement this method, is there a concrete example please?

**Comment by cowtowncoder** [comment]
This is not a user question forum: please use mailing list:

https://groups.google.com/g/jackson-user

or chat

https://gitter.im/FasterXML/jackson-databind
