### ISSUE TITLE
 How to make work TypeResolverBuilder with registerSubtypes

### ISSUE THREAD

**Issue by xdrsynapse** [FasterXML/jackson-databind#3379]
Hello,

I can't use annotations because it's a external library so I neeed to register subTypes for an interface and set custom type handler.

I searched and tried multiple guides but without sucess

This is the code that I tried but without sucess, typeResolver is working but Jackson not matching the registered subTypes with the type.

```
TypeResolverBuilder<?> typeResolver = new ObjectMapper.DefaultTypeResolverBuilder(ObjectMapper.DefaultTyping.NON_FINAL, BasicPolymorphicTypeValidator.builder()
                .allowIfBaseType(BeOutMessage.class)
                .build());
        typeResolver.init(JsonTypeInfo.Id.NAME, null);
        typeResolver.inclusion(JsonTypeInfo.As.PROPERTY);
        typeResolver.typeProperty("action");

        mapper.registerSubtypes(
                new NamedType(InitRequestBeMessage.class, ActionType.INIT_REQUEST.name()),
                new NamedType(PlayRequestBeMessage.class, ActionType.PLAY_REQUEST.name())
        );
        mapper.setDefaultTyping(typeResolver);
```
        
I get this error: 

```
typecom.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'INIT_REQUEST' as a subtype of `classpath.BeOutMessage`: known type ids = []
```

The most easiest solution that I found is use JsonDeserializer:

```
public class BeOutMessageDeserializer extends JsonDeserializer<BeOutMessage> {

    @Override
    public BeOutMessage deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
        JsonNode jsonNode = p.getCodec().readTree(p);
        Class<? extends BeOutMessage> entityClass = BeOutMessageType.valueOf(jsonNode.get("action").asText()).entityClass();
        return ((ObjectMapper)p.getCodec()).readValue(jsonNode.toString(), entityClass);
    }
}
   
```

But I don't like it and I don't think that is efficient enough like the JsonSubTypes.
How would be the proper way to do it at runtime?

Thank you!

**Comment by yawkat** [comment]
I don't think `setDefaultTyping` is meant to be used this way.

What you can do is simply declare a mixin for the base class:

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "action")
abstract class BeOutMessageMixin {}
```

And register it in the `ObjectMapper`:

```java
mapper.addMixIn(BeOutMessage.class, BeOutMessageMixin.class);
```

**Comment by xdrsynapse** [comment]
Thanks for your answer!

mixin looks like a workaround no? Would that be more faster than custom deserializer?

**Comment by yawkat** [comment]
I think a mixin would have no amortized overhead over a static declaration, it doesn't matter for perf after initial introspection is done.

Your custom deserializer may be faster in some cases than subtype handling in general, but it will also be slower in others and have certain correctness problems, because you load the entire object into a jsonnode first.

**Comment by xdrsynapse** [comment]
After some performance tests agaisnt mixin I got this results:

```
mixin:
Total execution time: 438ms
Total execution time: 217ms
Total execution time: 122ms
Total execution time: 183ms

customDeserializer:
Total execution time: 748ms
Total execution time: 370ms
Total execution time: 269ms
Total execution time: 336ms
```

And it improves a little bit when using with mapper.readerFor. Ergo we will use mixin and I hope that other devs can get usefull this issue for info.

Thanks @yawkat, I think we can close the issue if there is nothing else to add

**Comment by cowtowncoder** [comment]
One note after the fact: if you use "Default Typing", registration of subtypes has no effect -- Default Typing specifically forces use of class names (and potentially opens up security holes). Subtype registration is (only) used when Type Ids are used instead -- a safer approach, but one that does require mapping.

It sounds like mix-ins could work here, but use of `TypeResolverBuilder` would not make any sense to me.
