### ISSUE TITLE
What should I configure to not to deserialize property by using annotation `@javax.persistence.Transient`?

### ISSUE THREAD

**Issue by samho2008** [FasterXML/jackson-databind#3383]
What should I configure to not to deserialize property by using annotation `@Transient`?
It's a common way to use `@JsonIgnore`, but it's a huge work to add it in the whole project, and all the property I don't want to be deserialize has been annotated with `@Transient`, so can I configure not to serialize and deserizalize by using `@Transient` instead of `@JsonIgnore`? Thank you very much for you help.

btw: the version of jackson I am using is 2.5.1.

**Comment by cowtowncoder** [comment]
I think support for using `@Transient` (which was added in JDK 7) was added in Jackson 2.7. Version 2.5.1 is positively ancient so I'd recommend upgrade anyway.

So try a newer version, that should work.

**Comment by samho2008** [comment]
I updated to 2.13.1 just now, but it still doesn't work. I use the `javax.persistence.Transient` (which is provided by hibernate 4) instead of `java.beans.Transient`, is there any solution?

**Comment by samho2008** [comment]
I updated to 2.13.1 just now, but it still doesn't work. I use the `javax.persistence.Transient` (which is provided by hibernate 4) instead of `java.beans.Transient`, is there any solution?

**Comment by cowtowncoder** [comment]
@samho2008 Oh that is different; it is not currently supported. You will need to probably create custom `AnnotationIntrospector`: may sub-class `JacksonAnnotationIntrospector`.

**Comment by samho2008** [comment]
Thanks. That sounds good. Is there any example or doc to instruct me how to configure with the `setAnnotationIntrospector` method and `JacksonAnnotationIntrospector`?

**Comment by samho2008** [comment]
Is there any possibility to support `@javax.persistence.Transient` in the later version? I found this problem also be issued in the past. If possible, that will make jackson more convenient. Since jackson have support `@java.beans.Transient`, it would be not difficult to be compatible with `@javax.persistence.Transient` I guess.

**Comment by cowtowncoder** [comment]
Not in core `jackson-databind`, likely, since it would require adding a new depencency. Via new module, yes, if someone wants to take time. Especially if there are other potentially useful `javax.persistence` annotations.

I personally won't have time to work on this but would be happy to help if someone else wanted to try implementation.

Implementing `AnnotationIntrospector` handling is actually quite simple: if sub-classing `JacksonAnnotationIntrospector`, method to override would be `_isIgnoreable(Annotated)`. This is where Beans `Transient` is handled.

**Comment by samho2008** [comment]
Thank you for your patient explanation :). It works under your instruction. You know, there are still many projects using `hibernate` and it has its own annotation `javax.persistence.transient`. In this case, I personally think it's still meaningful to support it. I am glad to help. If permitted, I can submit my modification by `PR`.

**Comment by cowtowncoder** [comment]
@samho2008 Oh!!!! Are you using `jackson-datatype-hibernate` module? 

https://github.com/FasterXML/jackson-datatype-hibernate

Maybe they already provide this? I forgot to check this.

**Comment by samho2008** [comment]
That sounds goods. I will try. Thank you~
