### ISSUE TITLE
Allow use of `JsonNode` field for `@JsonAnySetter`

### ISSUE THREAD

**Issue by sixcorners** [FasterXML/jackson-databind#3394]
**Is your feature request related to a problem? Please describe.**
When working with unmapped nodes I want to work with JsonNode instead of Map.

**Describe the solution you'd like**
I want JsonAnySetter to support a field of the type JsonNode or maybe ObjectNode.

**Usage example**
class Test {
@JsonAnySetter
JsonNode extraData;
}
mapper.readValue("{\"test\": 3}", Test.class).extraData.path("test").intValue() == 3

**Additional context**
I'm a big fan of JsonNode.

**Comment by cowtowncoder** [comment]
Will be in 2.14.0.
