### ISSUE TITLE
Parser don't throw exception when specific JSON is not valid

### ISSUE THREAD

**Issue by honzap** [FasterXML/jackson-databind#3400]
**Describe the bug**
When trying to parse invalid JSON, the parser doesn't throw ParseException but parse the JSON. 
JSON:
```
{}something
```
Simple test:
```java
public class JsonParseTest {

    @Test
    void testParsingJson()  {
        ObjectMapper objectMapper = new ObjectMapper();

        assertThrows(JsonParseException.class, () -> objectMapper.readTree("{}something"));
    }
}
```

**Version information**
2.13.1

**To Reproduce**
Just run the parsing (`readTree` or `readValue`) with incorrect JSON input as shown.

**Expected behavior**
Parser throws JsonParseException

**Additional context**

Attached simple test project:
[jackson-parse-error.zip](https://github.com/FasterXML/jackson-databind/files/8096891/jackson-parse-error.zip)

**Comment by yawkat** [comment]
If you want this to fail, you need to enable `DeserializationFeature.FAIL_ON_TRAILING_TOKENS`

**Comment by yawkat** [comment]
According to the javadoc, it's disabled for compatibility reasons

**Comment by yawkat** [comment]
imo it is better to fail by default here. If you're parsing line-delimited json, you'll notice immediately if you forget to turn off `FAIL_ON_TRAILING_TOKENS`. However in the other direction, if it was off by default and you forget to turn it on, you probably would never notice (few people test for failures), which could also open up the door to parsing differential vulnerabilities in an application.

**Comment by cowtowncoder** [comment]
@yawkat Fair enough. Originally I had aversion to unnecessary traversal beyond needed tokens. But that's probably not much of an argument. Could you please file a separate feature request (issue) for changing `FAIL_ON_TRAILING_TOKENS` default value for Jackson 3.0? That way I can close this issue.

**Comment by cowtowncoder** [comment]
Closing as I do not consider it a bug & there is the follow-up issue of possibly changing the default behavior.
