### ISSUE TITLE
Could not find artifact com.fasterxml.jackson.module:jackson-module-kotlin:jar:2.13.2 in nexus

### ISSUE THREAD

**Issue by leonchen83** [FasterXML/jackson-databind#3410]
**Describe the bug**

```
Could not find artifact com.fasterxml.jackson.module:jackson-module-kotlin:pom:2.13.2 in nexus
```

**Version information**
Which Jackson version(s) was this for?

2.13.2

**To Reproduce**
If you have a way to reproduce this with:

1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here

parent pom
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <artifactId>jackson-bom</artifactId>
                <groupId>com.fasterxml.jackson</groupId>
                <version>2.13.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

child pom
```
        <dependency>
            <artifactId>jackson-core</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
        </dependency>
        <dependency>
            <artifactId>jackson-databind</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
        </dependency>
        <dependency>
            <artifactId>jackson-annotations</artifactId>
            <groupId>com.fasterxml.jackson.core</groupId>
        </dependency>
        <dependency>
            <artifactId>jackson-module-kotlin</artifactId>
            <groupId>com.fasterxml.jackson.module</groupId>
        </dependency>
```

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.

no exception

**Additional context**

seems like `com.fasterxml.jackson.module` does not upload to maven central yet

[2.13.1](https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-kotlin/2.13.1/)
[2.13.2](https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-kotlin/2.13.2/)

**Comment by cowtowncoder** [comment]
See https://github.com/FasterXML/jackson-module-kotlin/issues/550

Note: this is wrong Repo for the issue, closing -- but see the filed issue. Need someone to have a look; unfortunately this problem was not caught before starting the release process.
