### ISSUE TITLE
Odd Boolean serialization when is-get and get method are both present

### ISSUE THREAD

**Issue by SimoneGiusso** [FasterXML/jackson-databind#3415]
I have noticed that when trying to serialize a Boolean field, when both the _is_ method and _get_ method are present, Jackson will use the _get_ method for serialization. Let's take this example, and imagine to have an endpoint that returns the Person object by name:

```java
public class Person {

    private String name; // Tatu

    private Boolean employed; // null

    public String getName() {
        return name;
    }

    // Jackson will use this method for serialization over isEmployed. The person endpoint for Tatu
    // will return
    //
    // {
    //    "name": "Tatu",
    //    "employed": null
    // }
    public Boolean getEmployed() {
        return employed;
    }

    // Jackson will use this method for serialization if getEmployed is commented and will return
    //
    // {
    //    "name": "Tatu",
    //    "employed": false
    // }
    public boolean isEmployed() {
        return Boolean.TRUE.equals(employed);
    }

}
```

When Jackson try to serialize the Person object it will use `getEmployed()` method to serialize the `employed` field. Of course if the `getEmployed()` method is removed, it will use the `isEmployed()`. I would be nice to have at least this behaviour documented.

I have a demo project, a trivial application using spring boot starter to simulate this behaviour at this [link](https://github.com/SimoneGiusso/Jackson-Boolean-Serialization-Test).

**Comment by cowtowncoder** [comment]
Does seem like an odd edge case and should be addressed: in particular, seems like `isEmployed()` should be preferred over `getEmployed()` when "is-getters" are auto-detected.

**Comment by SimoneGiusso** [comment]
I don't have a strong opinion about if `isEmployed()` should be preferred over `getEmployed()` or viceversa. 

Could make sense use the `get` method to serialize in use cases where:

- I want `isEmployed()` as short-cut for `Boolean.TRUE.equals(employed);` and use it in the code (it could have even the corresponding `isNotEmployed()`.
- I want serialize a `Boolean` so I want to see all the three possible value after serialization: true, false and null for the employed field.

In my opinion a simple addition in the javadoc documentation (if possible) that explains the current behaviour would be fine.

**Comment by GedMarc** [comment]
I came across this, but I don't consider it a bug - it also resolves properly on jdk 14 with primitive generic types on the deserializer, 

Boolean is nullable and uses get, boolean is not nullable and uses isXXX

Specifying the correct type for the use case resolves this properly, 

Anything not true is false is the rule for boolean, which is correct,
Anything not true for Boolean is false, unless missing which makes it null, also correct

To make anything not false or true null, you need a custom deserializer, which is also correcr

**Comment by SimoneGiusso** [comment]
> it is more specific and hence should be selected, with no configurability -- override, if any, would be with either explicit `@JsonProperty` and/or `@JsonIgnore` annotations, or Visibility Detection changes.

Sure, this makes sense, because currently if we put the `@JsonIgnore` on the is-getter method the get method will be ignored during serialization. Same if the `@JsonIgnore` is on the get method, in this case the is-getter method will be ignored as well. In other terms currently if you put the `@JsonIgnore` annotation on one of the two methods the field employed will be not serialized.

> I also suspect that the current behavior is a side-effect of something missing in processing; and might even be non-deterministic if it is based on -- for example -- order in which Methods are returned by Reflection.

If the behaviour is not deterministic than this is dangerous, so we should address it in every case. 

> My only concern, as usual, is the backwards compatibility.

Can we maybe throw a compilation error if we detect both is-getter and get as possible methods to serialize a Boolean type? This should be thought as a conflict maybe.  This could force the developer to specify the method to use for serialization but in this case we lose the possibility to automatic pick is-getter as serialization method.

**Comment by cowtowncoder** [comment]
There is conflict detection, which is why I am surprised that logic here is not ONE of:

1. Just use "is-getter" as per expected logic, OR
2. Throw exception since there are two conflicting choices.

as to non-deterministic; those are difficult to detect so I am just speculating. I haven't had time to look into this due to that pesky CVE that has everyone running around, myself included.

But I hope to get to this eventually.

**Comment by cowtowncoder** [comment]
Ok, looked into this only briefly and realized that the precedence is defined as per a comment in `POJOPRopertyBuilder` method `getGetter()` when selecting amongst possibly multiple candidates: 

```
            /* 30-May-2014, tatu: Three levels of precedence:
             * 
             * 1. Regular getters ("getX")
             * 2. Is-getters ("isX")
             * 3. Implicit, possible getters ("x")
             */
```

and there is also a reference to issue #238 which apparently decides it too.
One problem with the implementation, however, is that it seems to hard code "get" and "is" prefixes even tho other parts of code allow custom prefixes.

But it looks like "regular" getters do have precedence over "is-getters" at this point, and this is to be considered the expected behavior.

**Comment by SimoneGiusso** [comment]
Thanks to have checked this. In fact this is what I discovered with my simple example, at least we know that this behaviour has been documented and is deterministic.

**Comment by cowtowncoder** [comment]
@SimoneGiusso right. It was good to verify this, given that I had forgotten what I had earlier implemented :-)
