### ISSUE TITLE
Jackson.databind  -Vulnerable in version 2.11.4 & No such Method error in 2.13.2 (latest version) 

### ISSUE THREAD

**Issue by MohanRamu** [FasterXML/jackson-databind#3429]
shade(group: 'com.fasterxml.jackson.core', name: 'jackson-core')

Jackson Data bind jar in gradle project fails to execute test cases when i use latest version-2.13.2 due to No such method error in com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet;
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet;

When i use 2.11.4 it is working as expected, but it is highly vulnerable in sonarqube report.

**Comment by yawkat** [comment]
The error sounds like you're still using an outdated version (pre 2.12) of jackson-core. You will need to update that to 2.13.2.

2.11 is unsupported and will not receive a backport: https://twitter.com/fasterxml/status/1507198466732175378

**Comment by MohanRamu** [comment]
> The error sounds like you're still using an outdated version (pre 2.12) of jackson-core. You will need to update that to 2.13.2.
> 
> 2.11 is unsupported and will not receive a backport: https://twitter.com/fasterxml/status/1507198466732175378

With the version 2.13.2, i got No such method error in com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet;
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.getReadCapabilities()Lcom/fasterxml/jackson/core/util/JacksonFeatureSet;

**Comment by yawkat** [comment]
You need 2.13.2.1 of jackson-databind, and 2.13.2 of jackson-core. You do not have the latter.

**Comment by MohanRamu** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/10909157/160113068-b679188d-7241-4ed6-8cbf-aa853e1c6aaa.png">

jackson-databind 2.13.2 is the latest, i could not find 2.13.2.1

**Comment by yawkat** [comment]
It's not visible on mvnrepository yet, but it is available on maven central.

**Comment by MohanRamu** [comment]
Could not download jackson-databind 2.13.2.1
 Required by:
         project :ae-features > com.fasterxml.jackson.core:jackson-databind:2.13.2.1
   > Could not find com.fasterxml.jackson:jackson-bom:2.13.2.1.
     Searched in the following locations:
       - file:/C:/Users/mohramu/.m2/repository/com/fasterxml/jackson/jackson-bom/2.13.2.1/jackson-bom-2.13.2.1.pom
       - https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/2.13.2.1/jackson-bom-2.13.2.1.pom
       - https://nexusrepo.***.com/repository/***-unite-product/com/fasterxml/jackson/jackson-bom/2.13.2.1/jackson-bom-2.13.2.1.jar

**Comment by yawkat** [comment]
That error is tracked under #3428. Please see the comments there for a workaround.

**Comment by cowtowncoder** [comment]
@MohanRamu as per notes, there is no `jackson-bom` version `2.13.2.1`, closing.
