### ISSUE TITLE
Is this the intended behavior?

### ISSUE THREAD

**Issue by sangyongchoi** [FasterXML/jackson-databind#3430]
```kotlin
data class Coordinate(
     val x: Double,
     val y: Double,
) {
    fun getGeoHash(): String {
        return "123213"
    }
}
```

```kotlin
val objectMapper = ObjectMapper()
val coordinate = Coordinate(1.5, 1.5)
val result = objectMapper.writeValueAsString(coordinate)

println(result)
```

Is this the intended behavior?
current : { "latitude":1.5,"longitude":1.5,"geoHash":"123123" }
my expectations :  { "latitude":1.5,"longitude":1.5 }

If the getter exists, will it be serialized even if the field doesn't exist?
thank you

**Comment by pjfanning** [comment]
use `@JsonIgnore` if you don't want to serialise the geohash

**Comment by cowtowncoder** [comment]
Also, specific to non-pure-Java: Kotlin? If so, needs to move to `jackson-module-kotlin`.

But @pjfanning is correct: if there is "getX()" then "x" existence is implied and one has to explicitly exclude it; for example by adding `@JsonIgnore`.

**Comment by sangyongchoi** [comment]
@pjfanning @cowtowncoder thank you 😄
