### ISSUE TITLE
jackson-databind before 2.13.0 allows a java stackoverflow exception

### ISSUE THREAD

**Issue by bhaskarrepuri** [FasterXML/jackson-databind#3442]
**Describe the bug**
Getting  Vulnerable failure in Jenkins build with jackson-databind

**Version information**
2.13.0

**To Reproduce**
Used jackson-databind with 2.13.0 in gradle in spring boot application.

**Expected behavior**
Local Gradle build there are no issues. In Jenkins builds we are always getting the Vulnerable failure. 

**Additional context**
As i know issue already reported and fixed : https://github.com/advisories/GHSA-57j2-w4cx-62h2, We suspect issue not fixed.

**Comment by yawkat** [comment]
This is tracked under #2816. Please upgrade to 2.13.2.1. This is also described in the GHSA you linked!

**Comment by SaiKrishnaKosna** [comment]
When a Jar file is created using `mvn clean install` the Jar file is created with Jackson-databind dependency version as 2.13.2 and not 2.13.2.2 which was mentioned in the pom.xml, Where ever this Jar file is being used it shows the same security issue.

pom.xml
`    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>2.12.6.1</version>
    </dependency>`

![image](https://user-images.githubusercontent.com/62735196/162419775-c440d027-478b-4b9f-b671-491a94d1544e.png)

**Comment by yawkat** [comment]
@SaiKrishnaKosna This is not a jackson issue, this is a problem in your build. It's impossible to say more with the information you've given.
