### ISSUE TITLE
Integration of jackson-databind into OSS-Fuzz

### ISSUE THREAD

**Issue by onionpsy** [FasterXML/jackson-databind#3454]
Hi all,

I have prepared the initial integration https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/b00498f091f17361abc9dbee13fa1b5802912fa6 of jackson-databind into [google oss-fuzz](https://github.com/google/oss-fuzz). This will enable continuous fuzzing of this project, which will be conducted by Google. Bugs that will be found by fuzzing will be reported to you. After the initial integration of this project into oss-fuzz, I will continue to add additional fuzz tests to improve the code coverage over time.

The integration requires a primary contact, someone to deal with the bug reports submitted by oss-fuzz. The email address needs to belong to an established project committer and be associated with a Google account as per [here](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/). When a bug is found, you will receive an email that will provide you with access to ClusterFuzz, crash reports, and fuzzer statistics. More than 1 person can be included. Please let me know who I should include, if anyone.

[Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) is used for fuzzing Java applications. Jazzer is a coverage-guided, in-process fuzzer for the JVM platform developed by Code Intelligence. It is based on libFuzzer and brings many of its instrumentation-powered mutation features to the JVM. Jazzer has already found several bugs in JVM applications: [Jazzer Findings](https://github.com/CodeIntelligenceTesting/jazzer#findings)

Please let me know if you have any questions regarding fuzzing or the oss-fuzz integration.

**Comment by yawkat** [comment]
@onionpsy there are already oss-fuzz integrations for other jackson modules, you can probably just copy the primary contact off that.

`mapper.readValue(data.consumeRemainingAsString(), Object.class);` is going to be quite limited though (i assume it's made to catch #2816). Not sure how to improve this though, it'd basically need special setup for every deserializer that needs to be tested.

**Comment by cowtowncoder** [comment]
Yup, what @yawkat said -- there's one existing Fuzz project for `jackson-core`, `jackson-databind` as well as for XML, cbor and Smile formats.

@yawkat Fuzzers that exist predate #2816 and mostly seem to focus on sort of low-level decoding aspects -- so generation of all kinds of (usually) invalid json (etc) matters most.
But I agree that to actually properly test `jackson-databind`, it'd be more interesting to try out different Java object models as this is where the real stuff is.
For low-level JSON decoding, `jackson-core` covers 90% of need I think.

**Comment by onionpsy** [comment]
Hey all,

Thank you for your insights. I have modified the integration to exclude the instrumentation of `jackson-core` as it is already integrated and I have also extended the code coverage by adding several different java & custom classes. You can see the changes there https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/0ad72a15bf456a7d13186294c033b57f0087c9d7

Don't hesitate to contact me again if you would like to see some changes in the fuzz target or if there are parts of the library you would like to fuzz in priority.

**Comment by cowtowncoder** [comment]
Thank you @onionpsy! One quick question: which Jackson version(s) would this originally target? As you probably know, `master` branch is for future Jackson 3.0, and the actively developed branch currently is 2.14, but will change over time. Eventually (... still no firm plans, alas), focus will move to `master` but for time being it'd make sense to target 2.14.

**Comment by onionpsy** [comment]
@cowtowncoder You're right, I changed it to use the `2.14` branch. 
I will keep an eye on the project and change the branch accordingly for the next releases.

**Comment by cowtowncoder** [comment]
Thanks!
