### ISSUE TITLE
standardise on NumberInput where possible

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#3459]
**Is your feature request related to a problem? Please describe.**
https://github.com/FasterXML/jackson-databind/pull/3458 shows the suggested change

**Describe the solution you'd like**
A clear and concise description of what you want to happen

**Usage example**
If you have a clear idea of how to use proposed new/modified feature, please show an example.

**Additional context**
Add any other context about the feature request here.

**Comment by cowtowncoder** [comment]
Good idea; merged for 2.14.
