### ISSUE TITLE
Provide documentation on how to sign the CLA

### ISSUE THREAD

**Issue by jsattler** [FasterXML/jackson-databind#3462]
The README.md mentions that contributors need to fill a Contributor License Agreement (CLA), but there is no reference or guidance on how to do that.

It would help to either provide guidance within this section or provide a reference on how to fill the CLA.

**Comment by cowtowncoder** [comment]
Sounds like a good improvement, yes.

Do you think a link to 

https://github.com/FasterXML/jackson/blob/master/CONTRIBUTING.md

would work?

Also: while I can do this (and will as necessary), PRs are always welcome, including those for READMEs.

**Comment by jsattler** [comment]
Yes, I think that works. Thanks for the improvement!
