### ISSUE TITLE
Type info is not passed for fields of Object type

### ISSUE THREAD

**Issue by zarebski-m** [FasterXML/jackson-databind#3479]
**Describe the bug**
When the property type is `Object` and its value is set to an instance with `@JsonTypeInfo`, the type information is not serialized to JSON.

**Version information**
Checked on Jackson 2.13.2.

**To Reproduce**
Issue reproduces in Java as well, but added Kotlin code for brevity:

```kotlin
import com.fasterxml.jackson.annotation.JsonTypeInfo
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper

data class Root(val id: Long, val data: Any?)

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
sealed class Base
data class Foo(val id: Long) : Base()
data class Bar(val id: Long) : Base()

val mapper = jacksonObjectMapper()

fun main() {
    val root = Root(1, Bar(1))
    println(mapper.writeValueAsString(root)) // {"id":1,"data":{"id":1}}
}
```

**Expected behavior**
The 'type' field should be present in the serialized JSON.

**Additional context**
I understand that deserialization of such class makes a `Map<String, Object>` value anyway, but IMO the `type` field should still be present in the JSON itself.

**Comment by cowtowncoder** [comment]
No, this is working as expected unless I misread something.

Type information to include is always based on _declared_ type, not runtime type.
So if declared type if `java.lang.Object` (any), it checks for `@JsonTypeInfo` for type `java.lang.Object`, finding none and then not enabling polymorphic type handling.

You can make it work, however, by adding `@JsonTypeInfo` on property (field / method) declaration for `data` (I think Kotlin has a way to indicate that).
