### ISSUE TITLE
#convertValue doesn't play well with #writeRawValue in JsonSerializer

### ISSUE THREAD

**Issue by wingsofovnia** [FasterXML/jackson-databind#3480]
**Describe the bug**
I have a custom `JsonSerializer` that produces custom built (valid) json and pastes it via  `writeRawValue`:
```java
class MyTypeSerializer extends JsonSerializer<MyType> {

  @Override
  public void serialize(MyType msg, JsonGenerator generator, SerializerProvider provider) throws IOException {
    generator.writeRawValue(serializeToJson(msg));
  }

  private String serializeToJson(MyType msg) { /** custom logic here **/ }
}
```

This works fine for regular serialization, e.g. with `writeValueAsString`, but when I attempt to do `mapper.convertValue(msg, Map.class)` it fails:
```
Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` from Embedded Object (token `JsonToken.VALUE_EMBEDDED_OBJECT`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
```

The problem is that `TokenBuffer#writeRawValue` appends my generated JSON as `JsonToken.VALUE_EMBEDDED_OBJECT`, which is not supported by `MapDeserializer`.

**Expected behavior**
`mapper.convertValue(msg, Map.class)` produces the same result as `mapper.readValue(mapper.writeValueAsString(msg), Map.class)`

**Version information**
2.13.2.2

**Comment by cowtowncoder** [comment]
Unfortunately I do not think Raw Values can be supported in general with `convertValue()`, without actually doing full serialization, so this is not something that will be done.
