### ISSUE TITLE
JsonView Bug

### ISSUE THREAD

**Issue by Hoysion** [FasterXML/jackson-databind#3483]
```java
public class ConflictUser {
    @JsonProperty("username")
    private String userName;

    private String username;

    @JsonProperty("TALL")
    private String tall;


    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @JsonView(User.UserSimpleView.class)
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getTall() {
        return tall;
    }

    public void setTall(String tall) {
        this.tall = tall;
    }
}
```

when getUsername() method annotated the @JsonView,serialize the conflictUser  but no confllict exception be thrown,such like this:Conflicting setter definitions for property \"username"

```java
ConflictUser conflictUser = new ConflictUser();
conflictUser.setTall("192");
conflictUser.setUserName("Big userName");
conflictUser.setUsername("small username");
objectMapper.writeValueAsString(conflictUser);
```

**Comment by cowtowncoder** [comment]
There is no conflict because methods (and property names) differ by case: `userName` vs `username`. Property names are case sensitive.
So I am not sure what the failure here would be.

**Comment by Hoysion** [comment]
> There is no conflict because methods (and property names) differ by case: `userName` vs `username`. Property names are case sensitive. So I am not sure what the failure here would be.

See the     
   @JsonProperty("username")
    private String userName;
the "userName" will serialize the "username",when remove  the JsonView(User.UserSimpleView.class) annotation,the excption will be thrown, the message is such like this:
ConflictUser#getUsername(0 params) vs ConflictUser#getUserName(0 params)
but with the JsonView annotation,it is correct

**Comment by Hoysion** [comment]
See the
   @JsonProperty("username")
    private String userName;
the "userName" will serialize the "username",when remove  the JsonView(User.UserSimpleView.class) annotation,the excption will be thrown, the message is such like this:
ConflictUser#getUsername(0 params) vs ConflictUser#getUserName(0 params)
but with the JsonView annotation,it is correct




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tatu ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 凌晨4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FasterXML/jackson-databind] JsonView Bug (Issue #3483)





 
There is no conflict because methods (and property names) differ by case: userName vs username. Property names are case sensitive.
 So I am not sure what the failure here would be.

**Comment by cowtowncoder** [comment]
Ok. It sounds then that there might be a problem.

But I want to be 100% sure I understand which case passes and which does not. So it would be good to include just the case where a conflict IS reported (exception IS thrown).
Ideal reproduction would be a unit test that shows the problem. It does not show the case that works, can just mention what needs to be added (or removed).

**Comment by Hoysion** [comment]
```java
package hoysing.test;


import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;


public class ConflictUser {
&nbsp; &nbsp; @JsonProperty("username")
&nbsp; &nbsp; private String userName;


&nbsp; &nbsp; private String username;


&nbsp; &nbsp; @JsonProperty("TALL")
&nbsp; &nbsp; private String tall;




&nbsp; &nbsp; public String getUserName() {
&nbsp; &nbsp; &nbsp; &nbsp; return userName;
&nbsp; &nbsp; }


&nbsp; &nbsp; public void setUserName(String userName) {
&nbsp; &nbsp; &nbsp; &nbsp; this.userName = userName;
&nbsp; &nbsp; }


&nbsp; &nbsp; public String getUsername() {
&nbsp; &nbsp; &nbsp; &nbsp; return username;
&nbsp; &nbsp; }


&nbsp; &nbsp; public void setUsername(String username) {
&nbsp; &nbsp; &nbsp; &nbsp; this.username = username;
&nbsp; &nbsp; }


&nbsp; &nbsp; public String getTall() {
&nbsp; &nbsp; &nbsp; &nbsp; return tall;
&nbsp; &nbsp; }


&nbsp; &nbsp; public void setTall(String tall) {
&nbsp; &nbsp; &nbsp; &nbsp; this.tall = tall;
&nbsp; &nbsp; }


&nbsp; &nbsp; interface SimpleView {
&nbsp; &nbsp; }


&nbsp; &nbsp; @Test
&nbsp; &nbsp; void testGroup() {
&nbsp; &nbsp; &nbsp; &nbsp; ConflictUser conflictUser = new ConflictUser();
&nbsp; &nbsp; &nbsp; &nbsp; conflictUser.setTall("192");
&nbsp; &nbsp; &nbsp; &nbsp; conflictUser.setUserName("Big userName");
&nbsp; &nbsp; &nbsp; &nbsp; conflictUser.setUsername("small username");


&nbsp; &nbsp; &nbsp; &nbsp; ObjectMapper objectMapper = new ObjectMapper();
&nbsp; &nbsp; &nbsp; &nbsp; Assertions.assertThrows(JsonMappingException.class, () -&gt; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; objectMapper.writeValueAsString(conflictUser);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "Conflicting getter definitions for property \"username\":" +
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; " hoysing.test.ConflictUser#getUsername() vs hoysing.test.ConflictUser#getUserName()");


&nbsp; &nbsp; &nbsp; &nbsp; CorrectUser correctUser = new CorrectUser();
&nbsp; &nbsp; &nbsp; &nbsp; correctUser.setTall("192");
&nbsp; &nbsp; &nbsp; &nbsp; correctUser.setUserName("Big userName");
&nbsp; &nbsp; &nbsp; &nbsp; correctUser.setUsername("small username");
&nbsp; &nbsp; &nbsp; &nbsp; Assertions.assertDoesNotThrow(()-&gt;{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; objectMapper.writeValueAsString(correctUser);
&nbsp; &nbsp; &nbsp; &nbsp; });
&nbsp; &nbsp; }


&nbsp; &nbsp; static class CorrectUser {
&nbsp; &nbsp; &nbsp; &nbsp; @JsonProperty("username")
&nbsp; &nbsp; &nbsp; &nbsp; private String userName;


&nbsp; &nbsp; &nbsp; &nbsp; private String username;


&nbsp; &nbsp; &nbsp; &nbsp; @JsonProperty("TALL")
&nbsp; &nbsp; &nbsp; &nbsp; private String tall;




&nbsp; &nbsp; &nbsp; &nbsp; @JsonView(SimpleView.class)
&nbsp; &nbsp; &nbsp; &nbsp; public String getUserName() {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return userName;
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; public void setUserName(String userName) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; this.userName = userName;
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; public String getUsername() {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return username;
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; public void setUsername(String username) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; this.username = username;
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; public String getTall() {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return tall;
&nbsp; &nbsp; &nbsp; &nbsp; }


&nbsp; &nbsp; &nbsp; &nbsp; public void setTall(String tall) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; this.tall = tall;
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }
}
```
notice the error message contains the package name!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FasterXML/jackson-databind"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 凌晨5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FasterXML/jackson-databind] JsonView Bug (Issue #3483)





 
Ok. It sounds then that there might be a problem.
 
But I want to be 100% sure I understand which case passes and which does not. So it would be good to include just the case where a conflict IS reported (exception IS thrown).
 Ideal reproduction would be a unit test that shows the problem. It does not show the case that works, can just mention what needs to be added (or removed).

**Comment by cowtowncoder** [comment]
Ok, this actually works as specified, for better or worse. The problem is due to a combination of things:

1. Field `userName` is originally linked to `getUserName()` (and `setUserName()`) by same name
2. But field `userName` is renamed as `username` property -- this will pull in `getUsername()`
3. If there is no annotation to indicate which of getter methods is to be used there is a conflict

Use of `@JsonView` annotation resolves this by indicating the preferred getter.

Unfortunately I think that in this case some annotations are required; or possibly removal of one annotation -- I am not sure annotation on field `userName` makes sense here, since there are getters and setters so field itself is never accessed anyway.
But if annotation is used there needs to be something to indicate preferred get method to use.

**Comment by Hoysion** [comment]
Confused that why the `@JsonView` will affect the serialized result without writeWithView method

**Comment by cowtowncoder** [comment]
@Hoysion that is because it is recognized as a "Jackson annotation", which in turn indicates that accessor (field/method) is to be considered visible, something to (potentially) use for reading or writing.
And that is because otherwise users might have add multiple annotations (like extra `@JsonProperty`) otherwise.
