### ISSUE TITLE
CWE-597

### ISSUE THREAD

**Issue by zhudaxi** [FasterXML/jackson-databind#3487]
[CWE-597](http://cwe.mitre.org/data/definitions/597.html) is found for [code](https://github.com/FasterXML/jackson-databind/blob/2.14/src/main/java/com/fasterxml/jackson/databind/deser/std/EnumDeserializer.java#L229)
Should use `.equals()` method rather than `==` in string compare.

**Comment by cowtowncoder** [comment]
This is total nonsense -- did you look into that piece of code? There is very specific reason why it OBVIOUSLY uses identity comparison. To see if `trim()` returned String as-is, or modified.

Please, PLEASE verify which warnings various tools give before filing an issue. I don't want to waste time on bogus reports like this one.

**Comment by zhudaxi** [comment]
@cowtowncoder Apologize for submitting this issue without looking into the code carefully. And really appreciate your feedback. Sure we will verify the issue before filing it next time. Thanks!
