### ISSUE TITLE
Stop rethrowing exception objects

### ISSUE THREAD

**Issue by ruckc** [FasterXML/jackson-databind#3492]
**Describe the bug**
Multiple locations within ObjectMapper and ClassUtil rethrows an existing exception.  This permanently hides the exception's existing stacktrace, replacing it with the new thrower's stacktrace.

**Version information**
2.13

**Expected behavior**
Ideally, any exceptions coming from jackson should have full, intact stacktraces.  Ideally, ObjectMapper should wrap caught exceptions with a new exception and throw that.  I'd submit a PR that does this, but none of the exception types support a simple Throwable constructor.

**Additional context**

**Comment by yawkat** [comment]
Your premise is wrong. Rethrowing does not modify the stack trace.

**Comment by ruckc** [comment]
It does, it squashes it and replaces it with the caller's stacktrace.  Right now i'm in a state where i'm getting a `JsonProcessingException(`Current context not Object but root`)` when I call `ObjectMapper.writeValueAsString`.  When I print the stack trace, I am only seeing upto the throw, nothing below the `_writeValueAndClose()` where the exception has to be coming from.

**Comment by ruckc** [comment]
My test case is giving me this... from writeValueAsString.

com.fasterxml.jackson.core.JsonGenerationException: Current context not Object but root
	at com.example.SomeTest.serialize(ExpressionsTest.java:92)
	at com.example.SomeTest.someTest(ExpressionsTest.java:83)
	
my serialize method:

```java
    private String serialize(SomeObject o) throws JsonProcessingException {
        log.debug("Serializing " + o);
        return mapper.writeValueAsString(o);
    }
```

**Comment by yawkat** [comment]
Then something else is touching your stack trace, it has nothing to do with jackson or rethrowing. Rethrowing an exception does not change its stack trace

**Comment by ruckc** [comment]
Argh, maven-surefire-plugin changed defaults... it now trims stacktraces... that is stupid.  Sorry for wasting your time.

**Comment by cowtowncoder** [comment]
Ahhh! Thank you for sharing the root cause. This makes more sense.
