### ISSUE TITLE
Cannot chain object node properties with nested object node

### ISSUE THREAD

**Issue by JoshMcCullough** [FasterXML/jackson-databind#3496]
https://github.com/FasterXML/jackson-databind/blob/3be614716f4736867379345c6febbc0c3898050f/src/main/java/com/fasterxml/jackson/databind/node/ObjectNode.java#L544

Why does this return `JsonNode` and not `ObjectNode`? This makes chaining not possible:

```java
new ObjectNode(nodeFactory)
    .set("bio", new ObjectNode(nodeFactory)
        .put("name", "Tim")
        .put("email", "tim@example.com"))
    .put("role", "manager");  // Cannot resolve method 'set' in 'JsonNode'
```

This results in the error:

> Cannot resolve method 'set' in 'JsonNode'

**Comment by yawkat** [comment]
duplicate of #2537 and fixed on branch 3.x, see the discussion there.

Please also note that .put does *not* return the original node here, so it does not do what you want

**Comment by JoshMcCullough** [comment]
Closing as dupe.
