### ISSUE TITLE
@JsonCreate does not work with nested array object.

### ISSUE THREAD

**Issue by hadson172** [FasterXML/jackson-databind#3499]
**Describe the bug**
I have the following data objects:
```
data class CreateAdRequest(
    val title: String,
    val images: List<AdImage> = emptyList()
)

data class AdImage(
    val type: String,
    val image: ByteArray
) {
    companion object {
        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
        @JvmStatic
        fun newAdImage(image: String): AdImage {
            return AdImageParser.parse(image)
        }
    }
}
```
And parsing code:

```
        val result = ObjectMapper().registerModule(KotlinModule.Builder().build())
            .readValue("""
                {"title": "c",
                "images": [
                    "someImage"
                ]}""".trimIndent(), CreateAdRequest::class.java)

```

> 2022-05-29 12:36:45.660  WARN 15284 --- [nio-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `x.g
.z.z.ads.request.AdImage`, problem: Not found type; nested exception is com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `x.g
.z.z.ads.request.AdImage`, problem: Not found type<EOL> at [Source: (PushbackInputStream); line: 4, column: 9] (through reference chain: x.g
.z.z.ads.request.CreateAdRequest["images"]->java.util.ArrayList[0])]      

**Version information**
2.13.1 (same problem at 2.13.3 as well)

**Expected behavior**
There should not be error when parsing

**Comment by yawkat** [comment]
Can you give a reproducible test case for this? I tried it in java, and it worked fine. Maybe it's an issue with the kotlin module.

**Comment by hadson172** [comment]
@yawkat Hi,  thanks for the answer. It seems that I fixed this problem by replacing
`        @JsonCreator`

with
`        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)`

On nested data structure (example is valid/working). It was quiet hard to find any information about this in web. Sorry for inconvenience. It seems that this may be closed
