### ISSUE TITLE
Sorting declared methods for serialization

### ISSUE THREAD

**Issue by peteruhnak** [FasterXML/jackson-databind#3504]
**Is your feature request related to a problem? Please describe.**
Jackson uses `java.util.Class#getDeclaredMethods` to find methods to turn into properties
https://github.com/FasterXML/jackson-databind/blob/2.14/src/main/java/com/fasterxml/jackson/databind/util/ClassUtil.java#L1235

Unfortunately, `getDeclaredMethods()` does not guarantee source order, or any other order.
This means that if a serialized file (such as swagger definition, which uses jackson internally) is kept in version control, each time a different result is produced.

Whilst we can already declare explicit order via an annotation, it is inevitably both more work and error-prone (easy to forget, or make a typo).

**Describe the solution you'd like**
Can we explicitly sort the methods by name?

```java
    public static Method[] getClassMethods(Class<?> cls)
    {
        try {
            Method[] methods = cls.getDeclaredMethods();
            Arrays.sort(methods, Comparator.comparing(Method::getName));
            return methods;
        } // ...
    }
```

**Usage example**
Consistent serialization ordering, such as for files kept in version control, or when diffing different serializations (e.g. for debugging).

**Additional context**
There is a possibility that the sorting will change some previous nonguaranteed stability.

My observation was that `getDeclaredMethods()` is mostly stable for classes without inheritance,
but mostly unstable for classes with inheritance. However the JavaDoc explicitly states that the order is not guaranteed.

This wouldn't impact serialization that already has explicit ordering, as that happens after this sorting.

**Comment by yawkat** [comment]
Do you have an example where it breaks? IME, it is the declaration order, though I can see inheritance causing issues (eg bridge methods). I think changing the order by default would break a lot of people that rely on it being declaration order.

btw, check out `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` which allows you to get the behavior you want, and also mentions the current behavior: "order is unspecified (based on what JDK gives us, which may be declaration order, but is not guaranteed)."

**Comment by cowtowncoder** [comment]
Agree with @yawkat and even more I'd say hard no here, for Jackson 2.x. I am not sure I see the benefit here over `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY`. I get that the order in which members are reported is not guaranteed, but I also know that based on observed behavior some users are counting on observed stability for non-inheritance case.

For Jackson 3.x I think we are planning on defaulting to `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` being true (or maybe even removing and hard-coding), I think.

**Comment by peteruhnak** [comment]
If this is something you are already planning for Jackson 3.x then I'm happy with that as that solves this long-term.

For the current one, I'll looking into `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` or do some post-processing on our end.

Thanks!
