### ISSUE TITLE
Fallback Default Value for Enum Type Field 

### ISSUE THREAD

**Issue by ko-ing** [FasterXML/jackson-databind#3529]
**Is your feature request related to a problem? Please describe.**
jackson-databind: 2.11.4

Hi, I was trying to deserialize json to Kotlin data class object which includes enum type field.
But since the value of the corresponding json field is not one of the enum values, it throws `InvalidFormatException`
```
data class A(
   val type: EnumType
   ...
) : Serializable
```

However, I don't need values other than the ones that are already of the enum values. So I want to set the field of the object as the default value if the value from the json does not match with any of the enum values. 
I think there's no way this can be done as far as I have searched.

**Describe the solution you'd like**
Annotation that sets default value as fallback on a field of a serialzable object 

**Usage example**
```
data class A(
   @DeserializeEnumDefault(EnumType.TypeA)
   val type: EnumType
   ...
) : Serializable
```

**Comment by cowtowncoder** [comment]
Have you tried `@JsonEnumDefaultValue` on Enum entry you want to use as default? I think that might do what you want.

**Comment by cowtowncoder** [comment]
Note: you say you are using version `2.11.2` -- that is quite old, so I would strongly recommend trying `2.13.3` instead, or at least `2.12.7`.

Second thing is that it'd be good to try to isolate code out of Spring Boot to see if it works: often the issue is that the `ObjectMapper` is not getting configured like you expect (or rather, configured instance not used by SB).

Good lcuk!

**Comment by ko-ing** [comment]
Thanks for your gentle answer!

It turned out that it was my mistake to only implement the object mapper on the encoder of webclient.
I managed to add this configuration and works fine for me!
```
                clientDefaultCodecsConfigurer.defaultCodecs().jackson2JsonDecoder(Jackson2JsonDecoder(objectMapper(), MediaType.APPLICATION_JSON))

```

I'll close this issue
Have a good day!

**Comment by cowtowncoder** [comment]
@ko-ing I am very glad it worked out once you found the problem. Thank you for confirming!
