### ISSUE TITLE
Java field `qName` serialized/deserialized in lowercase

### ISSUE THREAD

**Issue by jgomer2001** [FasterXML/jackson-databind#3541]
**Describe the bug**
If a Java bean has a field named `qName` or `QName`, jackson mapper does not recognize it properly. Seems  it wants it to be `qname`. See steps to reproduce.

**Version information**
com.fasterxml.jackson.core:jackson-databind:jar:2.13.2.1

**To Reproduce**

Suppose this class exists:

```java
package io;

public class Flow {
    
    private String qName;
    public String getQName() {
        return qName;
    }
    public void setQName(String qName) {
        this.qName = qName;
    }
```

This code:

```java
ObjectMapper mapper = new ObjectMapper();
Flow f = mapper.readValue("{\"qName\": \"oh yep.\"}", Flow.class);
```

throws error: `An exception occured while executing the Java class. Unrecognized field "qName" (class io.Flow), not marked as ignorable (1 known properties: "qname"])`. Note there is no `qName` in known properties, but `qname` … (lowercased).

Likewise

```java
Flow f = new Flow();
f.setQName("flow");
System.out.println(mapper.writeValueAsString(f));
```

outputs `{"qname": "flow"}`

**Expected behavior**
Default ObjectMapper instance should recognize `qName` upon deserialization, and use `qName` for serialization.

**Comment by cowtowncoder** [comment]
No. Behavior is as expected: from getter/setter, name `qName` can not be deduced.

If you want `qName`, please add

```
@JsonProperty("qName")
```

to either getter or setter (can ignore the field) and the "external" property name (one used in JSON) will be as you want it.
