### ISSUE TITLE
Object instance from number String can typecast Integer, not Long... Why?

### ISSUE THREAD

**Issue by doljae** [FasterXML/jackson-databind#3544]
```java
  public static void main(String[] args) throws JsonProcessingException {
      final String temp = "10";
      final ObjectMapper objectMapper = new ObjectMapper();
      final Object o = objectMapper.readValue(temp, Object.class);
      System.out.println(o instanceof Long); // false
      System.out.println(o instanceof Integer); // true
  }
```

I deserialized an integer string via `ObjectMapper` to `Object` type.
Deserialized instances can be typecast to `Integer` but not to `Long`.
If you have a cause for this or a reference document explaining it, please share.

**Comment by yawkat** [comment]
I mean, it has to be returned as *some* type, it can't be Long and Integer at the same time. Unless you configure [USE_LONG_FOR_INTS](https://fasterxml.github.io/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/DeserializationFeature.html#USE_LONG_FOR_INTS), it will use Integer for small numbers.

**Comment by doljae** [comment]
@yawkat , Thanks for your reply.
I have another question...

```java
public static void main(String[] args) throws JsonProcessingException {
    final String temp = "10";
    final ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.configure(DeserializationFeature.USE_LONG_FOR_INTS, true);

    final Object o = objectMapper.readValue(temp, Object.class);
    System.out.println(o instanceof Long); // true
    System.out.println(o instanceof Integer); // false
}
```
Enabling `USE_LONG_FOR_INTS` as per your comment gives the expected result.

Then I wonder why the result of enabling `USE_LONG_FOR_INTS` is not reflected in this setting. 
```java
public static void main(String[] args) throws JsonProcessingException {
    final String temp = "10";
    final ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.configure(DeserializationFeature.USE_LONG_FOR_INTS, true);

    objectMapper.activateDefaultTyping(objectMapper.getPolymorphicTypeValidator(),
                                       DefaultTyping.NON_FINAL,
                                       As.PROPERTY);

    final Object o = objectMapper.readValue(temp, Object.class);
    System.out.println(o instanceof Long); // false
    System.out.println(o instanceof Integer); // true
}

Actually, my understanding of `DefaultTyping` is not very good, so it seems that I am not finding the cause. 
Can you explain in detail?...

**Comment by doljae** [comment]
@yawkat
Plus, Is there a way with activating DefaultTyping & USE_LONG_FOR_INTS both?
Actually, this setting is default in my project, so I need to use both...

**Comment by cowtowncoder** [comment]
@doljae That does not really make tons of sense because `DefaultTyping` is for enabling polymorphic type handling -- in which JSON contains actual explicit class name to indicate intended type -- and `USE_LONG_FOR_INTS` suggest coercion in "untyped" cases.

So with DefaultTyping type is forced strictly.

But make sure you do understand why you would be using Default Typing -- people tend to overuse it; and it can be an actual security risk if accepting external content.
Even if you do need polymorphic handling it is possible to use `@JsonTypeInfo` annotation either on abstract base classes (to use for that type and subtypes), or on properties (to use for values of that property).

**Comment by doljae** [comment]
@cowtowncoder ,

Thanks for the kind explanation. It seems to make some sense now.

What I learned for sure is that `it is very difficult to set a common ObjectMapper that can be applied to all value types`. As I am trying to do everything with one `ObjectMapper`, it seems that I am using it unnaturally. 😓 

Giving the `DefaultTyping` setting and applying this setting to the project common `ObjectMapper` should be modified.

Thanks for the reply. The wiki documentation from `jackson-docs` was also very helpful 🙂

**Comment by cowtowncoder** [comment]
No further action planned, closing.
