### ISSUE TITLE
validation not working as expected

### ISSUE THREAD

**Issue by timnick-snow** [FasterXML/jackson-databind#3548]
see https://stackoverflow.com/questions/28632365/jacksons-json-2-5-0-validation-not-working-as-expected

It behaves the same in version 2.13

So, how to verify that an input (such as a string) is a valid JSON

**Comment by yawkat** [comment]
You can enable `FAIL_ON_TRAILING_TOKENS` to check that the full input is valid

**Comment by timnick-snow** [comment]
> You can enable `FAIL_ON_TRAILING_TOKENS` to check that the full input is valid

it is helpful
