### ISSUE TITLE
`@JacksonInject` value overridden by `null` from JSON input

### ISSUE THREAD

**Issue by shootercheng** [FasterXML/jackson-databind#3555]
**Is your feature request related to a problem? Please describe.**

When the value of JSON string field is null, the default injected value will be overwritten

**Describe the solution you'd like**

When the value of JSON string field is null, the default injected value should be used

**Usage example**
If you have a clear idea of how to use proposed new/modified feature, please show an example.

jackson version
```xml
<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.13.2.1</version>
        </dependency>
```
test code
```java
    static class TestBen {
        private String name;

        @JacksonInject(value = "INTEGER_ZERO")
        private Integer age;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Integer getAge() {
            return age;
        }

        public void setAge(Integer age) {
            this.age = age;
        }
    }

    private ObjectMapper createObjectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        InjectableValues.Std injectableValues = new InjectableValues.Std();
        injectableValues.addValue("INTEGER_ZERO", 0);
        mapper.setInjectableValues(injectableValues);
        return mapper;
    }


    @Test
    public void testInjectOk() throws JsonProcessingException {
        ObjectMapper mapper = createObjectMapper();
        String jsonValue = "{\"name\":\"123\"}";
        TestBen testBen = mapper.readValue(jsonValue, TestBen.class);
        Assertions.assertEquals(0, testBen.getAge());
    }

    @Test
    public void testInjectNull() throws JsonProcessingException {
        ObjectMapper mapper = createObjectMapper();
        String jsonValue = "{\"name\":\"123\", \"age\":null}";
        TestBen testBen = mapper.readValue(jsonValue, TestBen.class);
       //        Assertions.assertEquals(0, testBen.getAge());
        Assertions.assertEquals(null, testBen.getAge());
    }
```

**Additional context**
Add any other context about the feature request here.

**Comment by ajamesa** [comment]
nulls skip
```
JsonSetter.Value customSetter = JsonSetter.Value.forValueNulls(Nulls.SKIP);
objectMapper.setDefaultSetterInfo(customSetter);
```

**Comment by cowtowncoder** [comment]
@shootercheng It seems to me that the behavior is as expected: if input has a value -- and `null` is a value -- that should override whatever otherwise injected value is. I hope  @ajamesa 's solution works (it can also be applied on property using `@JsonSetter` ).

Also note that if you never want input to be used, there is:

```
@JacksonInject(useInput = OptBoolean.FALSE)
```

which means that only injected value is ever used. But no special rules for cases where sometimes input is to be used, other times now.

**Comment by cowtowncoder** [comment]
Note: if there is a desire to add some new functionality to allow different behavior, may file a new issue.
The current behavior is, however, the way things should be so no change will be made to skip `null`s by default or such.

**Comment by shootercheng** [comment]
Thanks



---Original---
From: "Tatu ***@***.***&gt;
Date: Thu, Aug 4, 2022 01:51 AM
To: ***@***.***&gt;;
Cc: "James ***@***.******@***.***&gt;;
Subject: Re: [FasterXML/jackson-databind] How @JacksonInject supports null？ (Issue #3555)




 
@shootercheng It seems to me that the behavior is as expected: if input has a value -- and null is a value -- that should override whatever otherwise injected value is. I hope  @ajamesa 's solution works (it can also be applied on property using @JsonSetter ).
 
Also note that if you never want input to be used, there is:
 @JacksonInject(useInput = OptBoolean.FALSE)  
which means that only injected value is ever used. But no special rules for cases where sometimes input is to be used, other times now.
