### ISSUE TITLE
Feature request: Annotation based mixin configuration

### ISSUE THREAD

**Issue by b0c1** [FasterXML/jackson-databind#3557]
Hi!
Usually, I working on a multi-module project where the ObjectMapper initialization is in the parent project.
This will help to create Mixin in the child project. I created a small example:

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
public @interface Mixin {
    Class<?> value();
}
//================================

public class AnnotationMixinResolver implements ClassIntrospector.MixInResolver {
    private Map<Class<?>, Class<?>> cachedMixinList = new HashMap<>();

    @Override
    public Class<?> findMixInClassFor(Class<?> cls) {
        if (cachedMixinList.containsKey(cls)) {
            return cachedMixinList.get(cls);
        }
        if (cls.isAnnotationPresent(Mixin.class)) {
            Class<?> foundMixin = cls.getAnnotation(Mixin.class).value();
            cachedMixinList.put(cls, foundMixin);
            return foundMixin;
        }
        return null;
    }

    @Override
    public ClassIntrospector.MixInResolver copy() {
        return new AnnotationMixinResolver();
    }
}
```
I register the `AnnotationMixinResolver` class in the ObjectMapper with `.setMixInResolver(new AnnotationMixinResolver())`

**Comment by cowtowncoder** [comment]
Only now realized that this was filed against wrong repo (jackson-core, which is for streaming), needs to be here at `jackson-databind`.

**Comment by cowtowncoder** [comment]
Hmmh. After re-reading the feature request, I am not sure I understand the idea: mix-ins are typically used when the target cannot be modified at all. So adding an annotation to associate a mix-in seems odd -- and maybe use of `@JacksonAnnotationsInside` (for annotation bundles) would make more sense.

Alternatively use of custom mix-in resolvers is fine, and can be done by users.

So I don't think I see a feature to add to core databind at this point, closing.
