### ISSUE TITLE
tools.jackson.databind.deser.jackson.BaseNodeDeserializer - would it be possible to make it public?

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#3567]
**Is your feature request related to a problem? Please describe.**

I've copied over some new code in jackson-module-scala 2.14 branch to the master branch. It won't compile in the master branch.

**Describe the solution you'd like**
The error message from the Scala build indicates that it is unhappy about tools.jackson.databind.deser.jackson.BaseNodeDeserializer being package private.

```
[error] Test suite tools.jackson.module.scala.deser.BitSetDeserializerTest failed with java.lang.IllegalAccessError: failed to access class tools.jackson.databind.deser.jackson.BaseNodeDeserializer from class tools.jackson.module.scala.deser.ImmutableBitSetDeserializer$ (tools.jackson.databind.deser.jackson.BaseNodeDeserializer and tools.jackson.module.scala.deser.ImmutableBitSetDeserializer$ are in unnamed module of loader sbt.internal.LayeredClassLoader @7cbcfccd).
```

https://github.com/FasterXML/jackson-module-scala/pull/592 has the failing CI build

**Comment by cowtowncoder** [comment]
Yes, that'd be ok. It'd be nice to avoid non-Jackson-component developers from extending it, but as long as Javadocs indicate that it's not meant for "external extension" I'd be ok.
But for Scala module (for example) it probably makes sense to be able to do that.

**Comment by cowtowncoder** [comment]
Changed in master (3.0).
