### ISSUE TITLE
.setDateFormat() not working

### ISSUE THREAD

**Issue by mikadev** [FasterXML/jackson-databind#3575]
Hello i now there is already some discussions about but it is simply not working

```  
ObjectMapper mapper = new ObjectMapper()
                .registerModule(new Jdk8Module())
                .registerModule(new JavaTimeModule());
        mapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd hh:mm:ss"));
        try {
            System.err.println(mapper.writeValueAsString(LocalDateTime.now()));
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
// output => "2022-08-18T10:58:18.5847198" 
```

**Comment by yawkat** [comment]
the objectmapper-level date format does not (cannot) apply to java.time types, those don't go through SimpleDateFormat. you can use `@JsonFormat` however.

**Comment by mikadev** [comment]
for those who are interested here working solution
https://www.programcreek.com/java-api-examples/?api=com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer
