### ISSUE TITLE
Modifying the method will create many empty objects, resulting in oom.

### ISSUE THREAD

**Issue by mjs8002** [FasterXML/jackson-databind#3599]
**Describe the bug**

**Version information**
Which Jackson version(s) was this for?
2.13.2.1
**To Reproduce**
If you have a way to reproduce this with:
 public void testReadValue() throws ServiceException {
        // Given

        ObjectMapper MAPPER = ObjectMapperUtil.getMapper()
            .configure(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS, true)
            .configure(DeserializationFeature.ACCEPT_FLOAT_AS_INT, false);
        try {
            Object decodedObj1 = MAPPER.readValue("{\"bgpPeer\":[{\"vrfId\":3}]}", Test2.class);
            Object decodedObj = MAPPER.readValue(
                "{\"bgpPeer\":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]}",
                Test2.class);
            System.out.println(decodedObj);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY, getterVisibility = JsonAutoDetect.Visibility.NONE,
        setterVisibility = JsonAutoDetect.Visibility.NONE)
    @NoArgsConstructor
    @AllArgsConstructor
    @EqualsAndHashCode
    @ToString
    public static class Test2{

        @JsonProperty("bgpPeer")
        private List<Test1> bgpPeer = new ArrayList();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY, getterVisibility = JsonAutoDetect.Visibility.NONE,
        setterVisibility = JsonAutoDetect.Visibility.NONE)
    public static class Test1{
        @JsonProperty("vrfId")
        private Integer vrfId = null;
    }
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.
MAPPER.readValue("{\"bgpPeer\":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}..........]}",Test2.class);
Modifying the method will create many empty objects, resulting in oom.
**Additional context**

**Comment by cowtowncoder** [comment]
First things first: reproduction cannot use Lombok, so I'd need version that has expanded code that Lombok generates. Tests cannot rely on Lombok framework.

**Comment by mjs8002** [comment]
> public void testReadValue() throws ServiceException { // Given
> 
> ```
>     ObjectMapper MAPPER = ObjectMapperUtil.getMapper()
>         .configure(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS, true)
>         .configure(DeserializationFeature.ACCEPT_FLOAT_AS_INT, false);
>     try {
>         Object decodedObj1 = MAPPER.readValue("{\"bgpPeer\":[{\"vrfId\":3}]}", Test2.class);
>         Object decodedObj = MAPPER.readValue(
>             "{\"bgpPeer\":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]}",
>             Test2.class);
>         System.out.println(decodedObj);
>     } catch (Exception e) {
>         throw new RuntimeException(e);
>     }
> }
> 
> @JsonIgnoreProperties(ignoreUnknown = true)
> @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY, getterVisibility = JsonAutoDetect.Visibility.NONE,
>     setterVisibility = JsonAutoDetect.Visibility.NONE)
> @NoArgsConstructor
> @AllArgsConstructor
> @EqualsAndHashCode
> @ToString
> public static class Test2{
> 
>     @JsonProperty("bgpPeer")
>     private List<Test1> bgpPeer = new ArrayList();
> }
> 
> @JsonIgnoreProperties(ignoreUnknown = true)
> @JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY, getterVisibility = JsonAutoDetect.Visibility.NONE,
>     setterVisibility = JsonAutoDetect.Visibility.NONE)
> public static class Test1{
>     @JsonProperty("vrfId")
>     private Integer vrfId = null;
> }
> ```

public void testReadValue() throws ServiceException {
// Given

    ObjectMapper MAPPER = ObjectMapperUtil.getMapper()
        .configure(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS, true)
        .configure(DeserializationFeature.ACCEPT_FLOAT_AS_INT, false);
    try {
        Object decodedObj1 = MAPPER.readValue("{\"bgpPeer\":[{\"vrfId\":3}]}", Test2.class);
        Object decodedObj = MAPPER.readValue(
            "{\"bgpPeer\":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]}",
            Test2.class);
        System.out.println(decodedObj);
    } catch (Exception e) {
        throw new RuntimeException(e);
    }
}

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY, getterVisibility = JsonAutoDetect.Visibility.NONE,
    setterVisibility = JsonAutoDetect.Visibility.NONE)
public static class Test2{

    @JsonProperty("bgpPeer")
    private List<Test1> bgpPeer = new ArrayList();
}

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY, getterVisibility = JsonAutoDetect.Visibility.NONE,
    setterVisibility = JsonAutoDetect.Visibility.NONE)
public static class Test1{
    @JsonProperty("vrfId")
    private Integer vrfId = null;
}

The same problem still exists when you do not use Lombok.

**Comment by cowtowncoder** [comment]
@mjs8002 Yes the idea is just to have a reproduction without Lombok -- not that it would be Lombok's fault.

**Comment by cowtowncoder** [comment]
@mjs8002 I cannot reproduce this: now OutOfMemoryException thrown.

**Comment by mjs8002** [comment]
> @mjs8002 I cannot reproduce this: now OutOfMemoryException thrown.

MAPPER.readValue("{"bgpPeer":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}..........]}",Test2.class);
We can copy {} infinitely to construct the first parameter. The packet size of about 2 m will cause jackson to deserialize 660,000 objects, occupying 200 m memory and causing oom.

**Comment by mjs8002** [comment]
> > @mjs8002 I cannot reproduce this: now OutOfMemoryException thrown.
> 
> MAPPER.readValue("{"bgpPeer":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}..........]}",Test2.class); We can copy {} infinitely to construct the first parameter. The packet size of about 2 m will cause jackson to deserialize 660,000 objects, occupying 200 m memory and causing oom.

Instead of constructing an object, we expect Jackson to automatically skip {} when deserializing.

**Comment by cowtowncoder** [comment]
"we expect Jackson to automatically skip {} when deserializing."

That's not how Jackson works and I think most users would find such behavior very odd, silently dropping legit data.

But next time please do not claim "Throws OOM" if your test case does not show that.
Of course if you read big enough document you exhaust memory.

As to skipping Empty Objects, that could be a feature request. If so, please file a separate issue for that; description here is confusing.
