### ISSUE TITLE
JeffreyVictorino

### ISSUE THREAD

**Issue by JeffreyVictorino** [FasterXML/jackson-databind#3600]
**Describe the bug**

**Version information**
Which Jackson version(s) was this for?

**To Reproduce**
If you have a way to reproduce this with:

1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.

**Additional context**

**Comment by cowtowncoder** [comment]
Accidentally filed? Will close.
