### ISSUE TITLE
Jackson filtering out fields nested  without annotations

### ISSUE THREAD

**Issue by xuwenping123** [FasterXML/jackson-databind#3602]
Hi, I have a question about the exclusion of serialization of class specified attributes.

```
    @Setter
    @Getter
    class User {
        private String name;
        private Integer age;     // exclude, I want to avoid serialization
        private List<Child> childs;
    }

    @Setter
    @Getter
    class Child {
        private Integer age;
        private Integer gender; // exclude, I want to avoid serialization
    }

    public void testFilterAge(Class<?> clazz, Set<String> excludeColumns) {
        ObjectMapper objectMapper = new ObjectMapper();
        // ....
        // how to do
    }
```
I have an object User, which contains another object Child, in
In the testFilterAge method, I want to avoid serialization by specifying class and Columns,

What should I do without adding annotations (JsonFilter etc.)
Thanks！

**Comment by xuwenping123** [comment]
```
`   @Setter
    @Getter
    class User {
        private String name;
        private Integer age;     // exclude, I want to avoid serialization
        private List<Child> childs;
    }

    @Setter
    @Getter
    class Child {
        private Integer age;
        private Integer gender; // exclude, I want to avoid serialization
    }

    public void testFilterAge(Class<?> clazz, Set<String> excludeColumns) {
        ObjectMapper objectMapper = new ObjectMapper();
        // ....
        // how to do
    }`
```

**Comment by cowtowncoder** [comment]
This is not a usage question forum; please use:

* mailing list: https://groups.google.com/g/jackson-user OR
* gitter chat: https://gitter.im/FasterXML/jackson-databind

There are also many articles, blog posts about use of `@JsonView`, `@JsonFilter`, f.ex:

* http://www.cowtowncoder.com/blog/archives/2011/02/entry_443.html
* http://www.cowtowncoder.com/blog/archives/2011/09/entry_461.html
