### ISSUE TITLE
ObjectMapper Logging for READ_UNKNOWN_ENUM_VALUES_AS_NULL

### ISSUE THREAD

**Issue by T-Developer1** [FasterXML/jackson-databind#3606]
**Is your feature request related to a problem? Please describe.**

I have an ObjectMapper which Maps an Enum Value.
If the Enum Value is not in my Enum List it should set the Enum as unknown.
So i set the Flag 

`.enable( DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL );
`

This works fine so far.

A clear and concise description of what the problem is.

I would like to have a logging when the unknown value is mapped to null.
For example if my value is "red" and my enum is [blue,green] i would like to know, that there was an error, and red is not in my color enum.

**Describe the solution you'd like**

A logging message which contains informations like
value "red" could not be parsed to enum [blue,green] , value is set to null. 

**Usage example**

```
   public static class TestClass
   {
      public enum TestEnum
      {
         blue,green
      }

      public TestEnum testEnum;
   }
```

```
      var objectMapper = new ObjectMapper()
         .enable( DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL );

      String json = "{ \"testEnum\" : \"red\"  }";
      TestClass testClass = objectMapper.readValue( json, TestClass.class );
```
If i use it like this, it mappes the unknown Value to null. But i would like to have an logging of what happened.

**Comment by cowtowncoder** [comment]
Jackson does not do logging for anything since I believe that libraries usually should not do so (at least kinds of Jackson).
If logging was already done I might consider this but as things are I don't see this as feasible.
