### ISSUE TITLE
Cannot ignore null value in JSONArray

### ISSUE THREAD

**Issue by codesmith47** [FasterXML/jackson-databind#3612]
**Describe the bug**
```java
ObjectMapper mapper = new ObjectMapper()
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
 Item[] items = mapper.readValue(json, Item[].class);
 for (Item item : items) {
     System.out.println(item);
 }
```

```java
import com.fasterxml.jackson.annotation.*;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Item {
    private int id, count;

    public Item() {}

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    .....
```
I have this code and I this JSON (https://paste.gg/p/anonymous/b4babcabec414e048c8bd7b185da2fa8) and I have already figured out how to only get the id and count, but now I cannot figure out how to tell Jackson to ignore the null fields in the JSON array when deserializing.

**Version information**
Which Jackson version(s) was this for?
2.13.4v

**To Reproduce**
If you have a way to reproduce this with:

1. create a JSON Array with multiple entries of objects
2. set a few to null
3. try to read the JSON into an array of an Object with the Ignore Unknown Annotation
4. 
**Expected behavior**
Remove/Ignore null values in root JSON array when deserializing.

**Additional context**

**Comment by cowtowncoder** [comment]
There is no way to automatically trim `null` values from Arrays; null-skipping is only done for properties of POJOs (if configured), never for Collection/array elements:

* `@JsonInclude` only affects serialization (writing of Java values as JSON)
* `@JsonIgnoreProperties` only relates to ignoring properties with unmatched name during deserialization (same for DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)

I will close this as none of the settings should do anything on Collection/array `null` elements.

You may file another issue for requesting some mechanism for such exclusion (skipping) of null values; currently such does not exist.
