### ISSUE TITLE
Add DeserializationFeature to ignore unknown properties 

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#3640]
**Is your feature request related to a problem? Please describe.**

I'm not suggesting this for Jackson 2.14.

Unexpected fields in JSON will lead to Jackson deserialization failing (by default). You can disable DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES. This is not recommended if you can receive JSON from untrusted sources.

If you disable FAIL_ON_UNKNOWN_PROPERTIES then Jackson will parse the unexpected fields and this can be expensive.

https://github.com/FasterXML/jackson-databind/blob/2.14/src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializer.java#L513

You can add an annotation to your Java class: `@JsonIgnoreProperties(ignoreUnknown = true)` to avoid some of the overhead.

**Describe the solution you'd like**

It would be nice to have a DeserializationFeature (eg IGNORE_UNKNOWN_PROPERTIES) to allow users to avoid having to add an annotation. 

**Additional context**

Relates to https://github.com/FasterXML/jackson-module-scala/issues/609

**Comment by cowtowncoder** [comment]
@pjfanning I am not quite sure how this could be implemented different from `DeserializationFeature.IGNORE_UNKNOWN_PROPERTIES`, or how would it differ from user perspective?
I guess I'd prefer focusing on figuring out how to handle existing ignoral in a better way.

For above we need to be able to test that skipping does avoid certain expensive calls -- and I think that'd be one of:

* Avoid construction of `BigInteger` / `BigDecimal` for numbers that are ultimately not needed/bound (with possible some exceptions like "any-setter" or `@JsonUnwrapped` where this cannot be achived currently)
* Possibly avoid allocating (big) `String` similarly.

Ignoral/skipping could probably be tested by using `JsonParserDelegate` and override accessors to ensure that certain calls are avoided -- either by throwing exception, or, perhaps returning sub-class of `BigInteger`/`BigDecimal` that can be detected in test (or fails if accessed).

In addition there's probably the part of focusing more on decoding limits at streaming parser level; similar to super deep nesting fundamentally streaming parser/generator is in better position to add fundamental (but configurable) limits.

**Comment by cowtowncoder** [comment]
Based on discussions, as well as default change via #3721 (for Jackson 3.0), plus changes to `jackson-core` to ensure lazy parsing of `BigDecimal`, I think this is no longer needed.
If there are cases where skipping of ignored properties is sub-optimal, let's instead tackle those cases individually.
