### ISSUE TITLE
@JsonUnwrapped does not work on Map.Entry

### ISSUE THREAD

**Issue by ThatSneakyRaccoon** [FasterXML/jackson-databind#3642]
When serializing the following class using the default `ObjectMapper`
```
class Foo {
     @JsonUnwrapped
     Map.Entry<String, String> entry;
    
     Foo() {
         this.entry = Map.entry( "hello", "world" );
     }
}
```
The output is
```
{
  "entry" : {
    "hello" : "world"
  }
}
```
I would expect it to be
```
{
  "hello" : "world"
}
```
Tested on version **2.13.1**

**Comment by cowtowncoder** [comment]
Correct, `@JsonUnwrapped` only works for POJOs and `Map.Entry` is not POJO.

I am not 100% sure if support could be added -- there is potential ambiguity if, say, multiple `Map.Entry` valued properties were found; ditto for "any setter" -- but I'll leave this open as an RFE.
I'll also see if there's an earlier issue for this.

**Comment by cowtowncoder** [comment]
`@JsonUnwrapped` only works on POJOs, by design, so same is true for using it on `java.util.Map`s too. Will close as "will-not-implement".

However, could consider allowing `@JsonAnyGetter` to work on `Map.Entry` instead -- if that makes sense, feel free to create new issue.
