### ISSUE TITLE
Add option to reconfigure `InternalNodeMapper`

### ISSUE THREAD

**Issue by Yury-Fridlyand** [FasterXML/jackson-databind#3644]
**Is your feature request related to a problem? Please describe.**
`JsonNode::toPrettyString` uses very default settings and there is no option to override anything, for example, printer settings.
`toPrettyString` call goes to https://github.com/FasterXML/jackson-databind/blob/0569cca8f2c775e01b39457223e40ec9614ee43a/src/main/java/com/fasterxml/jackson/databind/node/InternalNodeMapper.java#L40-L46 which uses non-configurable `ObjectWriter` https://github.com/FasterXML/jackson-databind/blob/0569cca8f2c775e01b39457223e40ec9614ee43a/src/main/java/com/fasterxml/jackson/databind/node/InternalNodeMapper.java#L25-L26

**Describe the solution you'd like**
It is good to have an option to configure these writers or make them read global settings.

**Usage example**
```java
    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.setDefaultPrettyPrinter(new DefaultPrettyPrinter()
            .withObjectIndenter(new DefaultIndenter().withLinefeed("\n")));

    return objectMapper
        .readTree(myObject)
        .toPrettyString();
```

**Additional context**
Version: 2.13.4

**Comment by cowtowncoder** [comment]
@Yury-Fridlyand If you want configurable pretty-printing, please use properly configured `ObjectMapper`: `JsonNode` instances do not and can not (should not) have mapper-level configurability.

`JsonNode.toPrettyString()` is only meant for casual usage and will not be made configurable.
