### ISSUE TITLE
(3.x) Chaining does not work after `ObjectNode.set()`

### ISSUE THREAD

**Issue by tehnodev** [FasterXML/jackson-databind#3653]
I try build this json
```
{
    "id": 1,
    "msg": {
        "hello": "world"
    },
    "name": "test"
}
```
with this code
```
var test = JsonNodeFactory.instance.objectNode()
    .put("id", 1)
    .set("msg", JsonNodeFactory.instance.objectNode()
        .put("hello", "world")
    )
    .put("name", "test");
```
and get error for last put("name", "test")
```
The method put(String, String) is undefined for the type JsonNode
```
Looks like set() do not return `this` from previous objectNode like first put("id", 1). Documentation says
```
Returns: This node after adding/replacing property value (to allow chaining)
```
Is this a bug?

**Version information**
2.13

**To Reproduce**
```
var test = JsonNodeFactory.instance.objectNode()
    .put("id", 1)
    .set("msg", JsonNodeFactory.instance.objectNode()
        .put("hello", "world")
    )
    .put("name", "test");
```

**Expected behavior**
Should be able to continue fluently build json object the same as after put() method

**Comment by cowtowncoder** [comment]
This is an unfortunate flaw in design, but unfortunate cannot be changed for 2.x since that is major backwards incompatibility to change (binary incompatibility as Method Signature changes :-( ).

But for 3.0 should allow chaining; I forget if this has already been changed. Will mark as 3.0 change.

**Comment by cowtowncoder** [comment]
Verified: 3.0 has return type properly as `ObjectNode` so that'll work.
