### ISSUE TITLE
java.lang.NoClassDefFoundError: com.fasterxml.jackson.databind.ser.impl.ReadOnlyClassToSerializerMap$$ExternalSyntheticLambda0

### ISSUE THREAD

**Issue by zero0cool0** [FasterXML/jackson-databind#3657]
**Describe the bug**

The following snippet 

```
        ObjectMapper mapper = new ObjectMapper();
        ArrayList<Integer> list = new ArrayList<>();
        list.add(1);
        try {
            String s = mapper.writeValueAsString(list);
        } catch (JsonProcessingException e) {
            Timber.e(e);
        }
```
crashes with 

`java.lang.NoClassDefFoundError: com.fasterxml.jackson.databind.ser.impl.ReadOnlyClassToSerializerMap$$ExternalSyntheticLambda0`

The same snippet is working under 2.13.3 but is now failing with 2.14.0

**Version information**
2.14.0,  gradle compileSdkVersion 33, minSdkVersion 22
Error only happens on Android API 23 or lower

**Additional Information**
The single gradle line relating to this is

`implementation "com.fasterxml.jackson.core:jackson-databind:$jackson_version"`

where `jackson_version` is set to 2.14.0

Gradle dependency tree is as follows:
```
+--- com.fasterxml.jackson.core:jackson-databind:2.14.0
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.14.0
|    |    \--- com.fasterxml.jackson:jackson-bom:2.14.0
|    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.14.0 (c)
|    |         +--- com.fasterxml.jackson.core:jackson-core:2.14.0 (c)
|    |         \--- com.fasterxml.jackson.core:jackson-databind:2.14.0 (c)
|    +--- com.fasterxml.jackson.core:jackson-core:2.14.0
|    |    \--- com.fasterxml.jackson:jackson-bom:2.14.0 (*)
|    \--- com.fasterxml.jackson:jackson-bom:2.14.0 (*)
```

**Comment by zero0cool0** [comment]
Closing this again, but leaving it here if anyone else has the same issue.

Cleaning the project in Android Studio wasn't enough, I had to invalidate the caches to get rid of the crash.

**Comment by cowtowncoder** [comment]
While I do not know exactly how this specific error comes about, Jackson 2.14 will require Android SDK 26, due to #3658.
Perhaps that is the root cause.

I updated 2.14 release notes to mention this baseline increase:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14

If earlier Android SDK support is needed, 2.13.x needs to be used; that branch remains open.

**Comment by zero0cool0** [comment]
Thank you. Reverting back to 2.13
