### ISSUE TITLE
NoSuchMethodError on JsonSubTypes.failOnRepeatedNames()

### ISSUE THREAD

**Issue by mayank-aggarwal28** [FasterXML/jackson-databind#3672]
**Describe the bug**
I am trying to upgrade jackson-databind from 2.13.4.2 to 2.14.0 and I am getting test failures with the below error:
java.lang.NoSuchMethodError: 'boolean com.fasterxml.jackson.annotation.JsonSubTypes.failOnRepeatedNames()

**Version information**
2.14.0

**To Reproduce**
Upgrading from 2.13.4.2 to 2.14.0

**Expected behavior**
Seamless upgrade or some property which enables old behaviour

**Comment by pjfanning** [comment]
2.14.0 is a significant upgrade. If you don't have time to spend on changing your code, then you should stick with jackson-databind 2.13.4.2.

**Comment by pjfanning** [comment]
`boolean com.fasterxml.jackson.annotation.JsonSubTypes.failOnRepeatedNames()` was added in jackson-annotations v2.14.0

You probably have an older version of jackson-annotations jar on your classpath.

**Comment by mayank-aggarwal28** [comment]
@pjfanning Upgrading jackson-annotations to 2.14.0 too solved my problem. Thank you.

**Comment by cowtowncoder** [comment]
Yes: one and only change to `jackson-annotations` in 2.14.0 is addition of this property: it is checked by `jackson-databind`. So databind 2.14 requires annotations 2.14.
