### ISSUE TITLE
apply streamReadConstraints when parsing numbers

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#3686]
jackson-databind often uses jackson-core JsonParser methods to get parsed numbers - and those methods apply the streamReadConstraints.

In some case cases, jackson-databind gets the text from the JsonParser instead and uses NumberInput to parse the numbers. In these cases, streamReadConstraints are not applied.

Examples appear in this method:
https://github.com/FasterXML/jackson-databind/blob/dc40f290d8e591eda3e5989709a04a891b16cb53/src/main/java/com/fasterxml/jackson/databind/deser/std/NumberDeserializers.java#L790

The question is how best to get access to the streamReadConstraints in this deserialize method. It has access to a JsonParser instance and the DeserializationContext. Would it be ok add a public method to ParserMinimalBase to replace the protected _streamReadConstraints method?

**Comment by cowtowncoder** [comment]
@pjfanning Yes, +1 for replacing `_streamReadConstaints()` with public `streamReadConstraints()` (move away from "getXxx()" is part of 3.0, but we can start adding this in new methods for 2.x as well).

**Comment by pjfanning** [comment]
this is merged
