### ISSUE TITLE
Add FieldReference in Jackson ValueNode to improve various json processing (e.g masking)

### ISSUE THREAD

**Issue by niralepatel** [FasterXML/jackson-databind#3696]
Issue type : Enhancement

Use case :-
	We are trying to mask the node(s) value(s) that matches a single JsonPath or list of JsonPaths. Please note, this json can be very large and we want to achieve this in the most efficient way without degrading the performce.
	
	{"root":
		{"obj": {
			"key1": "secret", 
			"key2": "pwd2"}
		}
	}

For above json, if JSONPath expression is given as "$.root.obj.key1 and I want to mask "secret" and if I have a referce of ObjectNode and field name(key1) for this ValueNode, then I can set maskedValue using getObject().set(fieldName,value) method.

		ValueNode vn= ....
		FieldReference fr = vn.getFieldRef();
		if (fr != null) {
			fr.getObject().set(fr.getFieldName(), maskNode);
		}
		
		

If we do not have the reference then, to mask perticular value, we have to traverse the entire json recursively and find out the reference and then set it which can increase the time complexity.

**Solution:-**
	Setting the FieldReference (fieldName and ObjectNode)in ValueNode will help to perform any action on that perticular ValueNode without traversing the entire json.

**Comment by cowtowncoder** [comment]
I don't know what `FieldReference`; I assume it comes from some other package.
I don't think we would want to extend Jackson model to add value types of other libraries.
So this will not be something we'd consider.

But you can sub-class `ObjectNode` (and other `JsonNode` implementation types) on your own if you want, expose their construction using custom `JsonNodeFactory`

**Comment by niralepatel** [comment]
Thanks @cowtowncoder 
FieldReference is not the third party class, this is a new class which I have added.
Please refer this MR: https://github.com/FasterXML/jackson-databind/pull/3705

We are using the same way in our project and it is working as expected. It would be great and helpful for others if we add the same in standard jackson-databind library.

**Comment by cowtowncoder** [comment]
@niralepatel Ah ok, thank you for explanation.

Now... I am not arguing it might not be useful for some, but it sounds like it'd add non-trivial overhead for processing and memory usage.

But most importantly: if this is sort of back-reference from values within `ObjectNode` back to it, creating cyclic dependency. We also have shareable `ValueNode`s (for booleans, null, missing node) that would have to unshared now.

So unless misunderstood something this is unfortunately something that would break existing `JsonNode` model; and that is something I am not considering.

**Comment by niralepatel** [comment]
@cowtowncoder Thanks!!

I didn't understand how it will create the cyclic dependency ?

If not this Field reference the can you please provide any alternative by which we can get the reference to ObjectNode for that ValueNode?

One way would be to traverse entire json, compare and get it, but for big and complex json this would be non efficient. Any alternative?

**Comment by cowtowncoder** [comment]
Cyclic reference: `ObjectNode` has child nodes (pointer/ref parent -> child). And now child `ValueNode`s would have a reference back to parent `ObjectNode`.

As to how to find parent; correct, either you'd need to traverse from root, keep track. Or include parent reference like you suggested.

One thing you could consider -- which is quite a bit of work, alas -- is to create custom sub-types or implementations of `ObjectNode` and other types: these can be registered by configuring `ObjectMapper` with `JsonNodeFactory` you create for constructing your own types. You would either sub-class existing types, or implement them from scratch: sub-classing should be doable for `ObjectNode` and `ArrayNode` (most complex ones).
These sub-types would then have your `FieldReference`s and so on. They could also implement interfaces you specify; there would need to be some casting for access, but core Jackson should work with these node types just fine, similar to standard ones.

The intent was always to support custom implementations, although it is difficult to support parallel type hierarchies that way. But this is why there is `TreeNode` super-interface that `JsonNode` implements.
