### ISSUE TITLE
JsonNode.equals is not actually comparing JSON nodes (?)

### ISSUE THREAD

**Issue by black-snow** [FasterXML/jackson-databind#3698]
Updated description; original post below hline:

JSON only has one number type but `JsonNode.equals` seems to treat different numeric (Java) data types as being different.

There's a comparator that deals with differen Java number types in the comments below - shouldn't this be built into Jackson as there's only one number type in JSON?

-----

**Describe the bug**
Contrary to [other](https://www.baeldung.com/jackson-compare-two-json-objects) [statements](https://stackoverflow.com/a/6527118/890537) the order of keys _does_ seem to matter:

Is this intended behaviour? It isn't really clear from [the docs](https://github.com/FasterXML/jackson-databind/blob/2.15/src/main/java/com/fasterxml/jackson/databind/JsonNode.java#L1464):

```java
    /**
     * Equality for node objects is defined as full (deep) value
     * equality. This means that it is possible to compare complete
     * JSON trees for equality by comparing equality of root nodes.
     *<p>
     * Note: marked as abstract to ensure all implementation
     * classes define it properly and not rely on definition
     * from {@link java.lang.Object}.
     */
    @Override
    public abstract boolean equals(Object o);
```

I didn't expect this behaviour.

**Version information**
2.14.1

**To Reproduce**
```java
    // junit 4 test
    @Test
    public void testOrderMatters() throws JsonProcessingException {
        final ObjectMapper om = new ObjectMapper();
        final JsonNode a = om.readTree("{\"a\":1, \"b\":2}");
        final JsonNode b = om.readTree("{\"b\":1, \"a\":2}");
        assertEquals(a, b);
    }
```

**Expected behavior**
Two Trees (`JsonNode` root nodes) are equal irrespective of in what order the children appeared in the JSON representation.

**Additional Context**
**Bonus:** I thought I might be able to hack my way around this using `@JsonPropertyOrder(alphabetic = true)` and ordering my expected JSON accordingly but no:

> expected: com.fasterxml.jackson.databind.node.ObjectNode<{"estimatedValue":123,"id":"1337","text":"text body","title":"titel"}> but was: com.fasterxml.jackson.databind.node.ObjectNode<{"estimatedValue":123,"id":"1337","text":"text body","title":"titel"}>
java.lang.AssertionError: expected: com.fasterxml.jackson.databind.node.ObjectNode<{"estimatedValue":123,"id":"1337","text":"text body","title":"titel"}> but was: com.fasterxml.jackson.databind.node.ObjectNode<{"estimatedValue":123,"id":"1337","text":"text body","title":"titel"}>
	at org.junit.Assert.fail(Assert.java:89)

What the heck? The test turns green when I

```java
        final JsonNode json = om.convertValue(event, JsonNode.class);
        final JsonNode expectedJson = om.readTree(new File("src/test/resources/some.json"));
        assertEquals(expectedJson.textValue(), json.textValue());
```

**Comment by yawkat** [comment]
your test is wrong, you swapped the values as well

**Comment by black-snow** [comment]
@yawkat true, thanks for spotting that. That's weird - why does my original test fail then? ...

It shoudln't matter how I create the `JsonNode`, should it?  
This is how I create the two:

```java
final Event event = factory.create(some, stuff);
// final JsonNode json = om.valueToTree(event); // tried both, doesn't matter
final JsonNode json = om.convertValue(event, JsonNode.class);

final JsonNode expectedJson = om.readTree(new File("src/test/resources/some.json")); // {"estimatedValue": ...
assertEquals(expectedJson, json);
```

Where `Event` is just a POJO (well, actually an interface but the implementing class is):
```java
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SomeEventTheFactoryCreates implements Event {

    @JsonIgnore
    private static final String VERSION = "v1";

    @JsonProperty("id")
    private String id;

    public String getId() {
        return id;
    }
    // ...
```

**Comment by cowtowncoder** [comment]
@black-snow It is possible that numeric value types could be handled differently in some regards: `long` property could become `LongNode` when directly converting --  but if its value is small enough, say, `1` then it would be read as `IntNode` from JSON.

But as to the original question: no, the order does not (nor should) matter for comparison of `ObjectNode`s. Non-equality in your case is related to something else.

Also note that `JsonNode` has functionality to use for external Comparator which can be used to customize comparison to (f.ex) try to unify Number nodes using whatever logic you want.
That may be necessary to use in some cases: but the benefit is that logic only needs to consider `ValueNode`s (i.e. not Object or ArrayNodes) which is usually somewhat smaller task to tackle.

**Comment by black-snow** [comment]
Actually, the abov fails when one gets read as FloatNode and the other as DoubleNode - improved version:

```java
    private static class JsonComparator implements Comparator<JsonNode> {

        @Override
        public int compare(final JsonNode o1, final JsonNode o2) {
            if (o1.isNumber() && o2.isNumber()) {
                if (o1.numberValue().equals(o2.numberValue()))
                    return 0;

                final long l1 = o1.asLong();
                final long l2 = o2.asLong();
                if (l1 < l2) return -1;
                else if (l1 > l2) return 1;

                final BigDecimal bd1 = new BigDecimal(o1.asText());
                final BigDecimal bd2 = new BigDecimal(o1.asText());
                return bd1.compareTo(bd2);
            }
            else if (o1.isBoolean() && o2.isBoolean()) {
                return Boolean.compare(o1.asBoolean(), o2.asBoolean());
            }

            return o1.asText().compareTo(o2.asText());
        }
    }
```

**Comment by cowtowncoder** [comment]
@black-snow Whether JSON "only knows Numbers" is up to debate: textual representations differ b/w ints and FPs. To me they are not the same.

But as practical matter trying to canonicalize `Number`s gets rather complicated and inefficient, messy, really really fast. We tried at some point and will not be making the same mistake again.

Users can relatively easily figure out something that works for their needs, but library/framework is much more difficult to balance: in practice, there'd need to be ever-expanding set of comparison strategies to cover all use cases.

**Comment by black-snow** [comment]
Aight, thanks - gonna closes this.

**Comment by cowtowncoder** [comment]
Quick note: it is possible to implement `java.util.Comparator<JsonNode>` and call `JsonNode.equals(Comparator<> comp, JsonNode otherNode)` to implement logic that does consider different kinds of `NumberNode`s equal.

Even if basic `JsonNode.equals(JsonNode otherNode)` does not have such logic.
