### ISSUE TITLE
CWE-400: Uncontrolled Resource Consumption ('Resource Exhaustion')

### ISSUE THREAD

**Issue by Cw404** [FasterXML/jackson-databind#3700]
Hello everybody, please help me.

question: I close my staging repositories in nexus repository manager, discover ' CWE-400: Uncontrolled Resource Consumption ('Resource Exhaustion') ' !

use version: jackson-core@2.14.1

sonatype report: [see report](https://sbom.lift.sonatype.com/report/T1-a0368c8f29fdaa555824-8be322a6faf936-1671045971-8b847a36d0304c959a3763deaf9f1736)

ps: I see fixed in V2.15, from [pull #827](https://github.com/FasterXML/jackson-core/pull/827)、[pull #846](https://github.com/FasterXML/jackson-core/pull/846), so I would like to ask when this release will be released.

**Comment by cowtowncoder** [comment]
Note: https://github.com/FasterXML/jackson-core/pull/827 is what resolves issue mentioned and I updated its description to say so. Databind does not handle low-level decoding details so it does not directly affect this module (although it has dependency to `jackson-core`).
