### ISSUE TITLE
Invalid naming strategy for field iName in serializer 

### ISSUE THREAD

**Issue by sergeykashin** [FasterXML/jackson-databind#3710]
**Describe the bug**
I have a POJO with private field iName and getter setters true lombok, 
anyway i have getIName method

in POJOPropertiesCollector you have 2 methods
1._addFields(props) it correctly add iName to props
2. _addMethods(props); it incorrectly add second Name - "iname" to props, 
later i have exception in deserializer "com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "iname" "

**Version information**
2.3.13

**To Reproduce**
try to serialize class with same name

**Expected behavior**
i have correctly only one name "iName"

**Additional context**
bug is in DefaultAccessorNamingStrategy
        for (; i < end; ++i) {
            c = basename.charAt(i);
            d = Character.toLowerCase(c);
            if (c == d) {
                sb.append(basename, i, end);
                break;
            }
            sb.append(d);
        }

line             d = Character.toLowerCase(c);

see vars on screenshoot for iName field and getIName method
https://photos.app.goo.gl/NkZXANkt5UV5R9cW6

**Comment by pjfanning** [comment]
With it being holiday season, it might take a while to look at this. I'd recommend that you try setting some Jackson annotations on your class to ignore the problem method. There are plenty of annotations that you could try. https://www.baeldung.com/jackson-annotations is a good intro.

**Comment by cowtowncoder** [comment]
This sounds like a Lombok problem to  be honest: logic it uses differs from that of Jackson -- in Jackson name introspection starts with getters/setters and does not assume anything about fields (field names are used as-is).
Names like `iName` are known problematic since transformation to/from matching getter/name is essentially lossy.

What would be needed here is NOT speculation on low-level name-mangling -- which probably works exactly as intended -- but a reproduction (unit test). And that MUST NOT include Lombok, but rather classes after Lombok processing.

It is very likely that what you need to use annotations for some field name cases; `iName` would be one such case.

**Comment by jpnovais** [comment]
Hi, any plans on this? 

I am also experiencing the same issue with **Kotlin**, although it works fine in Java.
As workaround for now I use `@get:JsonProperty("aValue")`

## Reproducible Example

```kotlin
@Test
  fun testJacksonSerialization() {
    data class SomeObject(
      @get:JsonProperty("aValue") val aField: String = "aValue",
      val bField: String = "bValue",
      val okField: String = "okValue",
    )

    val json = jacksonObjectMapper()
      .writeValueAsString(SomeObject())
      .also { println(it) }
    assertThatJson(json).isEqualTo(
      """
      {
          "aField": "aValue",
          "bField": "bValue",
          "okField": "okValue"
      }
    """.trimIndent()
    )
  }
  ```
  
  Failure
  ```
  Different keys found in node "", missing: "aField","bField", extra: "aValue","bfield", expected: <{"aField":"aValue","bField":"bValue","okField":"okValue"}> but was: <{"aValue":"aValue","bfield":"bValue","okField":"okValue"}>
  ```
  
  
####  dependencies
```
dependencies {
  api "com.fasterxml.jackson.core:jackson-annotations:2.18.0"
  api "com.fasterxml.jackson.core:jackson-databind:2.18.0"
  api "com.fasterxml.jackson.module:jackson-module-kotlin:2.18.0"
  api "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.0"

  testImplementation "net.javacrumbs.json-unit:json-unit-assertj:3.4.1"
}
```
