### ISSUE TITLE
Inconsistent behaviour of JsonInclude.Include.NON_DEFAULT for HashMap and POJO

### ISSUE THREAD

**Issue by doom369** [FasterXML/jackson-databind#3712]
Hello. When I try to serialize a map in POJO, Jackson removes the default value entries from the map. However, when the same map is serialized without POJO, default entries are not removed.

Here is the reproducer:

```
    public static void main(String[] args) throws Exception {
        ObjectMapper objectMapper = new ObjectMapper()
                .setSerializationInclusion(JsonInclude.Include.NON_DEFAULT)
                .setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.NONE)
                .setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        Map<Integer, Integer> map = Map.of(0, 1, 1, 2, 2, 0);
        System.out.println(objectMapper.writeValueAsString(map));
        System.out.println(objectMapper.writeValueAsString(new TestClass(map)));
    }

    public class TestClass {

        private final Map<Integer, Integer> map;

        public TestClass(Map<Integer, Integer> map) {
            this.map = map;
        }
    }

```

Output:

```
{"2":0,"1":2,"0":1}
{"map":{"1":2,"0":1}}
```

Is that expected? Jackson version 2.14.1.

My understanding is that output in both cases should be the same `{"2":0,"1":2,"0":1}`.

**Comment by pjfanning** [comment]
This is what appears to cause the problem.

`.setSerializationInclusion(JsonInclude.Include.NON_DEFAULT)`

I'm not an expert on all these Jackson customisations - but it might be possible for you to get by for the next while by removing this.

**Comment by doom369** [comment]
@pjfanning it's added on purpose. I don't want to serialize non defaulf values. However, when I enabled this feature some of my internal tests failed and I found this inconsistency. According to the documentation, map values should be not affected with `JsonInclude.Include.NON_DEFAULT`.

**Comment by cowtowncoder** [comment]
It sounds like a flaw to me.
Thank you for providing a test case; I don't know when I have time to look into it but it should help.

**Comment by cowtowncoder** [comment]
@doom369 On Map values, inclusion criteria is used for `Map` entries; some Javadocs may have older definition as support was added over time (i.e. initially filtering was not performed).

**Comment by cowtowncoder** [comment]
Quick note: looks like filtering is at least applied to root `Map`s, and `NON_NULL`, `NON_EMPTY` work to remove `null` values. Will next try to see why `NON_DEFAULT` does not filter out `0`s.

**Comment by cowtowncoder** [comment]
Ahhhhh. So the Good Old Java Type Erasure is what happened here -- type definition of root level `Map` is only known as `Map<?,?>` (roughly same as `Map<Object, Object>`). Because of this, filter constructed is based on just `java.lang.Object` and there is no "default" value in that case.

So there are 3 commonly used ways to work around the problem.

1. Use a wrapper POJO to avoid issue altogether: this is why `Map` field of `TestClass` worked -- Fields and Methods retain full type information
2. Use a helper non-generic class, like `class IntIntMap extends HashMap<Integer, Integer> { }` -- it will retain type information and can be serialized at root just fine
3. Force `ObjectWriter` to use specified generic type (specify type so erasure won't matter):

```
     Map<Integer, Integer> map = ...;
    String json = mapper.writerFor(new TypeReference<Map<Integer, Integer>>() { })
         .writeValueAsString(map);
```

Unfortunately one of above is needed: Jackson needs type information for filtering of default and empty values.

**Comment by doom369** [comment]
@cowtowncoder ok, thanks. And my understanding is that there is no way to say to Jackson "don't apply `NON_DEFAULT` for maps" (except an annotation in every pojo)?

**Comment by cowtowncoder** [comment]
@doom369 I don't quite follow: do you mean that if you set Global Default inclusion setting, it will apply to all types? If so, yes.

But! Note that you can separately define inclusion for "main" values and "content" values -- latter applies to Map entries, array/Collection elements. Method is `ObjectMapper.setDefaultPropertyInclusion()` which takes value class that has TWO settings for inclusions. Second one is one that applies to Map values and you probably want that different from the first value (which applies to `Map` itself, as well as POJOs, arrays, Collections etc).

**Comment by doom369** [comment]
@cowtowncoder thanks. Seems like what I need.
