### ISSUE TITLE
Maps are lost in the process of deserialization if the Value is null

### ISSUE THREAD

**Issue by svrdoljak** [FasterXML/jackson-databind#3728]
### Description

Here is a demo application which show the example where the map is completely lost in the process of deserialization in case the KEY of a map is set but the VALUE of a map is NULL. The HTTP client log level is set to TRACE and you can see the request body before and after it hits the controller. The controller logs the payload out and the "secondKey" is completely gone. I don't know if this is meant to be so or I am doing something wrong.

If you need more information, please let me know.

Just start the test and see the output. There are also comments which explain what is expected and what is the actual result.

### Example Application

https://github.com/svrdoljak/mn-jackson

### Version

2.14.1

**Comment by cowtowncoder** [comment]
Thank you for reporting the issue. Unfortunately I do not use "run this application and see textual output" type of tests for various reasons:

1. Often framework configures settings and/or add handlers, changing behavior from default Jackson
2. Without assertions that tests have it is often not clear what is assumed to be the problem 
3. Actual reproduction (unit test) cannot have new external dependencies so it is rarely easy to extract test

So I would need a stand-alone reproduction that:

1. Only depends on Jackson-databind and its dependencies
2. Has some form of assertion of what is expected to happen

**Comment by yawkat** [comment]
this is purely a micronaut issue, nothing with jackson

**Comment by svrdoljak** [comment]
Closing the issue. This was a Framework issue.
