### ISSUE TITLE
Add ability to serialize and deserialize java.nio.file.Path

### ISSUE THREAD

**Issue by shs96c** [FasterXML/jackson-databind#373]
Since Path is an Iterable, this currently chokes on OS X (not tested on Windows). A simple transformation to and from String is easy:

Serialize: path.toString();

Deserialize: Paths.get(stringPath);

**Comment by trejkaz** [comment]
Just FYI, `Paths#get(String)` isn't actually the inverse of `Path#toString()`.

Found this ticket totally at random while searching to see whether anyone has a real solution to it. I was thinking that maybe using URIs is safer.
