### ISSUE TITLE
Add support in `TokenBuffer` for lazily decoded (big) numbers

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#3730]
(note: for background see #3721) 

There are a few issues with `TokenBuffer` regarding number coercions, mostly due to eager buffering sometimes needed, which forces decision on use of type (`double` vs `BigDecimal` in particular) before knowing target type.
There are also concerns about overhead in some cases, preventing efficient skipping of big number values in cases where buffering is needed: for example, when `@JsonCreator` use requires preservation of content that would ultimately be skipped.

An idea that came to mind is that since `TokenBuffer` stores all buffered content using 2 elements -- `JsonToken` for type, and opaque `Object` (depending on type) -- it would be possible to augment handling to use hypothetical `BufferedNumber` (or `LazyNumber`) type, which could:

1. Store more information on actual `NumberType` (to preserve distinction between finer grain `JsonParser` exposes)
2. Allow deferred decoding esp. for "big" numbers (`BigInteger`, all floating-point types)

This would require support from `jackson-core` for:

* New type itself (`BufferedNumber`) as well as implementation(s) if not concrete
* New accessor(s) from `JsonParser` -- either specific "always get buffered" or hybrid (buffered if not decoded; `Number` if decoded)

There are probably other subtleties too but this is the general idea. If anyone plans to work on this, another issue needs to be created on `jackson-core` side.

**Comment by pjfanning** [comment]
@cowtowncoder I added lazy nums in https://github.com/FasterXML/jackson-databind/pull/3727

In the test case that shows the unnecessary parseBigInteger call now doesn't end up parsing the big int - the LazyBigInteger is stored but the number is never parsed.

Unfortunately, no existing test leads to lazy nums being actually parsed - so I can't yet guarantee that the lazy code actually works all the way through.

**Comment by cowtowncoder** [comment]
Another potential mechanism to use: https://github.com/FasterXML/jackson-core/issues/902 (assuming I get to implement it).

**Comment by cowtowncoder** [comment]
Ok, instead I went with:

https://github.com/FasterXML/jackson-core/issues/902

with adds `JsonParser.getNumberValueDeferred()`. I hope to work on this soon, but @pjfanning if you have time and interest don't let me block your progress.

One thing I need to figure out has to do with testing, how to verify expected handling improvements both wrt skipping of unused contents (need mocking, maybe?) and wrt retaining of exact representation through buffering.

**Comment by pjfanning** [comment]
@cowtowncoder https://github.com/FasterXML/jackson-databind/pull/3761 is open

**Comment by cowtowncoder** [comment]
Merged #3761 so this is now implemented.
