### ISSUE TITLE
Deserialize with multiple levels of polymorphic type hierachy

### ISSUE THREAD

**Issue by joseph2002** [FasterXML/jackson-databind#374]
It seems that this use case is not supported:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value=B1.class, name="b1"),
    @JsonSubTypes.Type(value=B2.class, name="b2")
})
public abstract class A {
    ...
}

public class B1 extends A {
    ...
}

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "subtype")
@JsonSubTypes({
    @JsonSubTypes.Type(value=C1.class, name="c1"),
    @JsonSubTypes.Type(value=C2.class, name="c2")
})
public abstract class B2 extends A {
    ...
}

public class C1 extends B2 {
    ...
}

public class C2 extends B2 {
    ...
}
```

What I want is to resolve this one: { "type": "b1"; ... } to class B1, and { "type": "b2"; "subtype": "c1"; ... } to class C1 and { "type": "b2"; "subtype": "c2"; ... } to class C2. (B1 has no "subtype" property, while C1 and C2 have the same "type" property and different "subtype" property)
Any suggestions?

**Comment by jamarillo** [comment]
I have a similar problem, i have 3 class, abstract class generic (), class class1 extends generic() and class11 extends class1() :

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")

@JsonSubTypes({@JsonSubTypes.Type(value=CardActivityTable.class, name="5") })
@Document(collection = Card.COLLECTION_NAME)

public abstract class Card extends AuditableEntity {
}

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "typeActivity")

@JsonSubTypes({ @JsonSubTypes.Type(value = CardActivity.class, name = 3) })
@Document(collection = Card.COLLECTION_NAME)

public class CardActivityTable extends Card {
}


 @Document(collection = Card.COLLECTION_NAME)

public class CardActivity extends CardActivityTable {
   public String optionC;
}

I'm trying to insert the json:

{
"type":"5",
"typeActivity": "3",
"optionC": "test"
}

but i show the error :

"Could not read document: Unrecognized field \"optionC\"

**Comment by cowtowncoder** [comment]
@jamarillo possibly -- and as you noticed, support for multi-level resolution does not exist nor is planned. So chaining of definitions will not work.

**Comment by hrishikesh-kumar** [comment]
@cowtowncoder  
This post is around 4 years old, now is there any update on this? Because I fell it's a basic use-case.  Do we have any workaround. I'm designing my classes on composite design pattern and facing this issue. 


```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "componentType", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = ElementGroup.class, name = "ELEMENT_GROUP"),
        @JsonSubTypes.Type(value = Element.class, name = "ELEMENT")})
public abstract class Component {
    private String id;
    private String displayName;
    private DisplayOrientation displayOrientation;
    private Map<String, String> properties;
    private ComponentType componentType;
}
```

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "provider" , visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = AMElementGroup.class, name = "AM")}
)
public abstract class ElementGroup extends Component {
    private ElementProvider provider;
    private List<Component> children;
}
```

```
public class AMElementGroup extends ElementGroup {
    private TimeFilterConfig timeFilterConfig;
    private List<Aggregate> allowedAggregates;
}
```


I tried custom JsonDeserialize but didn't work. 

Waiting for response.

**Comment by cowtowncoder** [comment]
@hrishikesh-kumar It is not supported and there are no plans to support it. Do not design your system assuming this will be implemented.

And I have no idea what " tried custom JsonDeserialize but didn't work." means -- custom deserializers can support LITERALLY anything.
