### ISSUE TITLE
schemaType of `LongSerializer` is wrong

### ISSUE THREAD

**Issue by luozhenyu** [FasterXML/jackson-databind#3742]
**Describe the bug**
The `schemaType` of `LongSerializer` and `ShortSerializer` should be `integer` instead of `number`.
https://github.com/FasterXML/jackson-databind/blob/2.15/src/main/java/com/fasterxml/jackson/databind/ser/std/NumberSerializers.java#L188-L190

**Version information**
2.x

**To Reproduce**
```java
ObjectMapper mapper = new ObjectMapper();
JsonSchema jsonSchema = mapper.generateJsonSchema(Long.class);
System.out.println(mapper.writeValueAsString(jsonSchema));
// stdout: {"type":"number"}
```

**Expected behavior**
1. Do you think we should fix it up? change the `schemaType` of `LongSerializer` and `ShortSerializer` from number to integer.
2. I notice the interface `SchemaAware` is removed in 3.x , but the latest release is still 2.x . New developers may still override methods of SchemaAware. I think `interface SchemaAware`  should be marked with `@Deprecated`.

**Comment by cowtowncoder** [comment]
@luozhenyu Yes, I think you are right, these should be changed to give more specific type. This can go in 2.15.

As to `SchemaAware`... it might make sense to mark it deprecated; the main problem is that this will lead to lots of warnings for serializer implementation in databind package.
But other 2 types in that package are indeed deprecated so maybe it should be.
Could you please file a separate issue suggesting adding deprecation?
And I'll go ahead change schema type under this issue.
