### ISSUE TITLE
Javadoc page is down

### ISSUE THREAD

**Issue by joca-bt** [FasterXML/jackson-databind#3765]
The Javadoc page appears to be down. https://fasterxml.github.io/jackson-databind/javadoc/2.14/

**Comment by pjfanning** [comment]
related to #3440

**Comment by joca-bt** [comment]
Removing old versions from the current URL will potentially break a lot of pipelines.

**Comment by cowtowncoder** [comment]
@joca-bt Sorry about that -- I did not realize there was actual automated usage.
