### ISSUE TITLE
Deserialization of list of map is not working if json has no data

### ISSUE THREAD

**Issue by NitinSapre** [FasterXML/jackson-databind#3779]
I have a class which is something like this(cant share all the code)  -

```
@Data
@JsonAutoDetect
@JsonIgnoreProperties(ignoreUnknown = true)
public class RequestData implements Serializable {
    private List<Map<String, Object>> selected;
}
```

when the incoming Json has this property as empty, jackson fails to deserialize the object.
For example:
`selected=[{type=xyz}]` works fine 
but
`selected=[]` or `selected=[{}]` or `selected=null` does not work. It says bad request.

I think an empty list of empty map should be initialized even if data is not present in incoming request.

I am using Jackson version - 2.10.4

**Comment by NitinSapre** [comment]
you are right. This is not a bug.
I found the problem and will deal with it in our code.
Thanks 👍 
And apologies for raising an incorrect issue

**Comment by cowtowncoder** [comment]
Ok just glad you figured it out -- thank you for quick follow up @NitinSapre!
