### ISSUE TITLE
Custom deserializers are ignored by the class-level deserializer

### ISSUE THREAD

**Issue by bxvpm** [FasterXML/jackson-databind#3781]
If we have a class annotated with a custom `JsonDeserialize` other deserializers added at runtime are ignored, see the below example, even though `CustomDogDeserializer `is added, jackson is still using the Dog.Builder.class deserializer.

    public class Main {

    public static void main(String[] args) throws IOException {
    ObjectMapper objectMapper = new ObjectMapper();

    SimpleModule simpleModule = new SimpleModule();
    simpleModule.addDeserializer(Dog.class, new CustomDogDeserializer(PriceList.getInstance()));
    objectMapper.registerModule(simpleModule);

    objectMapper.readValue(Path.of("/files/s1.yml").toFile(), DogOwner.class);
    // com.fasterxml.jackson.databind.exc.MismatchedInputException:
    // Cannot construct instance of `Main.Dog$Builder`
    // (although at least one Creator exists): no String-argument construct
    }

    public static class CustomDogDeserializer extends JsonDeserializer<Dog> {
      final PriceList priceList;

      public CustomDogDeserializer(PriceList priceList) {
        this.priceList = priceList;
      }

      @Override
      public Dog deserialize(JsonParser p, DeserializationContext ctxt) throws IOException, JsonProcessingException {
        String valueAsString = p.getValueAsString();
        String[] split = valueAsString.split("-");
        return Dog.builder().setName(split[0]).setPrice(priceList.getNext()).build();
      }
    }

    @AutoValue
    @JsonDeserialize(builder = DogOwner.Builder.class)
    public abstract static class DogOwner {

      public static DogOwner.Builder builder() {
        return new AutoValue_DogOwner.Builder();
      }

      @JsonProperty("name")
      public abstract String getName();

      @JsonProperty("dog")
      public abstract Dog getDog();

      @AutoValue.Builder
      public abstract class Builder {

        @JsonCreator
        public static DogOwner.Builder builder() {
          return DogOwner.builder();
        }

        @JsonProperty("owner")
        public abstract Builder setOwner(String name);

        @JsonProperty("dog")
        public abstract Builder setDog(Dog dog);

        public abstract DogOwner build();
      }
    }

    @AutoValue
    @JsonDeserialize(builder = Dog.Builder.class)
    public abstract static class Dog {

      public static Dog.Builder builder() {
        return new AutoValue_Dog.Builder();
      }

      @JsonProperty("name")
      public abstract String getName();

      @JsonProperty("price")
      public abstract int getPrice();

      @AutoValue.Builder
      public abstract class Builder {

        @JsonCreator
        public static Dog.Builder builder() {
          return Dog.builder();
        }

        @JsonProperty("name")
        public abstract Builder setName(String name);

        @JsonProperty("price")
        public abstract Builder setPrice(int price);

        public abstract Dog build();
      }
    }

**Comment by yawkat** [comment]
so your issue is that the annotation takes precedence?

**Comment by bxvpm** [comment]
> so your issue is that the annotation takes precedence?

yes

**Comment by cowtowncoder** [comment]
Annotation will always have preference over default (de)serializers: this is pretty fundamental design decision. I do not think this will ever be changed; generally if class should not have deserialized tightly coupled with it, annotations should not be used.
I'll also note that these annotations are produced by a framework, which perhaps has ways to prevent this addition.

But aside from use of mix-in annotation (with `@JsonDeserialize(using = Void.class)` to "remove" annotation), it is also possible to block it by overriding `AnnotationIntrospector` (usually by sub-classing `JacksonAnnotationIntrospecotr`) method `findDeserializer(Annotated a)` -- this is what is used to find the annotation. You could block cases where `a` is `AnnotatedClass` of specific type(s).

**Comment by cowtowncoder** [comment]
As per my comment, this works as designed and behavior itself will not be changed.

I am open to suggestions on how to handle the problem case, however; just not on suggested change (mostly on technical/practical grounds -- not necessarily philosophically).

So if anyone has good ideas of how to allow better overriding of annotations in a way -- something like -- just as an example -- having distinction between "default" serializers (lowest priority) vs "override" serializers (with highest priority) I would be open to suggestions.
If so, please file a new issue, linking to this one as background.

Closing this issue as wont-fix.
