### ISSUE TITLE
Add the capabilities to create a JsonMapper.builder from a JsonMapper

### ISSUE THREAD

**Issue by nithril** [FasterXML/jackson-databind#3782]
**Is your feature request related to a problem? Please describe.**

I did not find an easy way to copy a `JsonMapper` from another `JsonMapper` by using `JsonMapper.Builder`. 

The convenient way is to use `ObjectMapper#copy` but the `enable(MapperFeature)` / `disable(MapperFeature)` methods are deprecated.

**Describe the solution you'd like**

The capacity to create builder from a mapper: `JsonMapper.builder(mapper)`

**Comment by yawkat** [comment]
you can use JsonMapper.rebuild

**Comment by cowtowncoder** [comment]
Yes. While 3.0 (`master`) adds true, completely functioning rebuild(), `JsonMapper.rebuild()` is available to allow use of `Builder` over copy of an `ObjectMapper` (well, must be `JsonMapper`).
