### ISSUE TITLE
Improve Javadoc of `SimpleModule` to indicate "last one wins" for (de)serializer registrations

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#3787]
(offshoot of #3089) 

Looks like Javadocs do not mention the basic implementation aspect that if a (de)serializer is added to be registered for a given `Class`, possible earlier addition will be replaced. This should be mentioned about everything that can be added, most notably serializers/deserializers.

**Comment by JooHyukKim** [comment]
May I try to write the the descprtion in javadoc for all `addDeserializer` and `addSerializer` methods?
And  one test case for each method?

**Comment by JooHyukKim** [comment]
Lemme know how you think~

**Comment by cowtowncoder** [comment]
@JooHyukKim Excellent, will review!
