### ISSUE TITLE
Add a warning message when encountering unknown properties in JSON

### ISSUE THREAD

**Issue by danielnsilva** [FasterXML/jackson-databind#3794]
**Is your feature request related to a problem? Please describe.**
It's common to have errors in the names of properties in JSON objects, which can cause issues when deserializing them into Java objects using Jackson. Currently, if a JSON object contains a property that doesn't exist in the corresponding Java object, Jackson silently ignores it. This can make it difficult to diagnose issues that arise due to typos or other mistakes in the property names.

**Describe the solution you'd like**
I would like to propose adding a warning message when Jackson encounters a property in a JSON object that doesn't exist in the corresponding Java object. This would make it easier to identify and resolve issues caused by typos or other errors in property names.

**Usage example**
Suppose we have the following JSON object:

```json
{
  "firstName": "John",
  "lastName": "Doe",
  "age": 30,
  "email": "johndoe@example.com"
}
```

And suppose we have a Java class with the following fields:

```java
public class Person {
  private String firstName;
  private String lastName;
  private int age;
}
```

Currently, if we try to deserialize the JSON object into a Person object using Jackson, the email property will be silently ignored. With the proposed warning message, we would see a message like "Unknown property 'email' in JSON for type 'Person'" in the logs, which would help us identify and correct the mistake.

**Additional context**
I believe that adding this warning message would be a useful addition to Jackson, as it would help developers catch errors in their code more quickly and easily.

**Comment by pjfanning** [comment]
Do you have a test case that proves this assertion?

DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES is enabled bt default. You get an exception if the JSON has unexpected properties. You have to explicitly disable this feature, if you want to allow unknown properties.

**Comment by danielnsilva** [comment]
You are correct about that. I made a mistake, because the scenario I described was when the `FAIL_ON_UNKNOWN_PROPERTIES` is false, which is sometimes desired, especially in cases where the ability to add fields without a direct relationship to the Java object is an advantage.

In such cases, errors caused by typos in property names, for example, might be harder to identify without the warning feature. It is true that with `FAIL_ON_UNKNOWN_PROPERTIES` enabled, the need for the warning feature may not be as significant, but when this feature is disabled, as I described, it can be quite helpful.

**Comment by pjfanning** [comment]
I strongly recommend not disabling FAIL_ON_UNKNOWN_PROPERTIES if you are at all unsure about the origin of the JSON you are parsing. Malicious actors can add unexpected fields that have values like that can cause issues (unexpected exceptions, excessive memory use, etc.).

If the JSON is wrong, why not fail? Isn't that normally the correct thing to do? If you log it, couldn't the logs be lost in reams of other log messages?

Jackson does not log anything - except in 2 small adjunct modules - according to https://cowtowncoder.medium.com/jackson-is-not-affected-by-log4j-logback-cves-fdebf152057f

**Comment by danielnsilva** [comment]
Thank you for this input. I understand and agree with your concerns about disabling `FAIL_ON_UNKNOWN_PROPERTIES`, especially when parsing JSON from untrusted sources.

However, there are scenarios where failing the entire deserialization process when adding unknown properties to the JSON is not the desired behavior.

In those cases, logging a warning message can help to identify potential issues caused by typos or errors in property names. Of course, the logs can be lost in a sea of other messages, but with proper log management and analysis, it is possible to filter and prioritize these warnings.

Regarding the logging behavior of Jackson, thank you for sharing the information. I wasn't aware on that.

Overall, I still think that the problem of identifying unknown properties during deserialization is important, and I appreciate your feedback. In this case, considering your advice, maybe would be better use a custom Deserializer to ensure proper logging.

**Comment by cowtowncoder** [comment]
@danielnsilva You may want to check out use of `DeserializationProblemHandler` which allows you to handle case of unknown property. Example usage could be found from:

     src/test/java/com/fasterxml/jackson/databind/deser/filter/TestUnknownPropertyDeserialization.java

It allows you to "resolve" various problems without terminating databinding process -- for example to collect all issues.

Another technique that could work is defining a method annotated with `@JsonAnySetter` (that takes `String` and `Object` arguments) -- or `Map<String, Object>` field similarly annotated -- this allows you to also collect unknown entries. This is bit more intrusive but might be useful.

I definitely would not want developers to have to write custom deserializers for tasks like finding unknown properties.

**Comment by danielnsilva** [comment]
Thank you, @cowtowncoder. I was actually considering creating a custom deserializer and modifying the `handleUnknownProperty` method. However, I now realize that this is not an ideal solution.

After reviewing the example in `TestUnknownPropertyDeserialization`, using the `DeserializationProblemHandler` seems like the perfect approach. I will take a closer look on it and give it a try.

Thank you again for your suggestion and for pointing me in the right direction.

**Comment by cowtowncoder** [comment]
Good luck @danielnsilva !
