### ISSUE TITLE
serialize a list object return space string result

### ISSUE THREAD

**Issue by happyjt528** [FasterXML/jackson-databind#3800]
hi, when i use jackson to serialize an object , but it does not work well.   

**all my maven dependencies:** 
`
	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>
			<version>2.14.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.14.2</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.14.2</version>
		</dependency>
	</dependencies>`

**this is my java objects :** 

`

public class Po {
	
	private String id;
	private List<Sub> subs;

       // getting and setting ....
}

public class Sub {
	
	private String key;
	
	private String remark;
	
	public Sub(){}

	public Sub(String key, String remark) {
		super();
		this.key = key;
		this.remark = remark;
	}

	@Override
	public String toString() {
		return "Sub [key=" + key + ", remark=" + remark + "]";
	}
   // getting and setting ....
}

`

**then test class:**
`

public class TestJson {
	
	public static void main(String[] args) {
		
		Po po = new Po();
		po.setId("0001");
		
		po.setSubs(IntStream.range(0, 150)
				.mapToObj(i -> new Sub(i+"", "xxxxxxx"))
				.collect(Collectors.toList()));
		
		System.out.println(po.getSubs().size());
		System.out.println(po.getSubs().stream().findAny().get().toString());
		
		ObjectMapper mapper = new ObjectMapper();
		try {
			System.out.println(mapper.writeValueAsString(po));
		} catch (JsonProcessingException e) {
			e.printStackTrace();
		}
		
	}
	
}

`

In the test class, i will get a space string result.   If  i reduce the size of List<Sub>,  serialization is perfect. 

Perhaps i have this mistaken result with a  wrong usage，please let me know, Tks .

**Comment by cowtowncoder** [comment]
This is an issue tracker, not usage support forum. Please use a mailing list or chat:

* https://groups.google.com/g/jackson-user
* https://app.gitter.im/#/room/#FasterXML_jackson-databind:gitter.im
