### ISSUE TITLE
Use FAIL_ON_UNKNOWN_PROPERTIES for specific packages

### ISSUE THREAD

**Issue by gituserjava** [FasterXML/jackson-databind#3820]
Is there a way we can use `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` (via Spring spring.jackson.deserialization.fail-on-unknown-properties) globally but only to specific pojos in certain packages?

**Comment by pjfanning** [comment]
How about working around the fact that is a setting for the Object Mapper instance by creating 2 Object Mappers? Check the class you want to map to using instanceof and use the Object Mapper that is configured for that class.

**Comment by gituserjava** [comment]
@pjfanning , not sure I understood your suggestion but in my case I cannot change code because the ObjectWrapper code is currently within a JAR file which I am not allowed to change currently.

**Comment by cowtowncoder** [comment]
Jackson does not use Java packages as scoping for any annotations or configuration, out of the box. So you'd have to implement that on your own -- it would be doable by custom `AnnotationIntrospector`; you can look at `JacksonAnnotationIntrospection` on how it checks for `@JsonIgnoreProperties` annotation (which method is called), and implement your custom logic that way.

The problem with Java packages is that it would be very difficult to combine Package logic with class inheritance logic -- Jackson follows class inheritance.

**Comment by cowtowncoder** [comment]
The other usual way to modify settings for 3rd party types (aside from tweaking `AnnotationIntrospector`) is to use Mix-In annotations: you can register sort of overrides targeting any other classes, to virtually add annotations. This works well if you have a small number of things to override; either just couple types in general or if there is a commonly used base type (Jackson annotations are inheritance-aware) -- if so, you use a mix-in to target that basetype and all sub-classes get to use it too.

Just outlining things that do exist, and that may work for your case.

**Comment by gituserjava** [comment]
@cowtowncoder be, looks like mixin option also does not work for us because BOTH the pojos and the ObjectWrapper that is using the pojos are within the third party JAR. 

Imagine this JAR is calling a REST API and is building the pojos based on Rest API response within the JAR. Now the Rest API is enhanced to return new data points/fields which are not available in the POJOs and this is breaking with `UnrecognizedPropertyException` on new fields. Using `spring.jackson.deserialization.fail-on-unknown-properties=false` in `application.properties` will fix the issue but it is applying to all the other Pojos (local to application) and we just want to avoid that. That is the reason me asking the original question - can we apply such settings on a specific package. Please advise.

**Comment by cowtowncoder** [comment]
@gituserjava Please read my earlier answers in detail: I answered your question.
