### ISSUE TITLE
Throw exception for set `@JsonProperty(access = READ_ONLY)` fields during Record deserialization

### ISSUE THREAD

**Issue by safdevke** [FasterXML/jackson-databind#3822]
Hi, is there anyway to throw an exception if fields annotated with `@JsonProperty(access = READ_ONLY)` are set during deserialization? After extensive googling, I haven't found a solution.

I currently have this class:
```java
public record ExampleDTO (
    @JsonProperty(access = READ_ONLY)
    String name,
    @JsonProperty(access = READ_WRITE)
    String email ) {}
```
I have this request:
```json
{
    "name": "Dolores Elte",
    "email": "email@jkjk.com"
}
```
I get this response:
```json
{
    "name": null,
    "email": "email@jkjk.com"
}
```
`name` is never set as expected but is there any way to throw an exception instead (and possibly return a bad request status to the user)?

**Comment by mukham12** [comment]
Hello,

You can try configuring the ObjectMapper by adding the line **.configure(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES, true)** to your code. This will help to throw an **IgnoredPropertyException** when an ignored property is encountered during deserialization. You can then catch this exception and implement the logic required to return a 400 status code. This can help you to ensure that ignored properties are handled properly, and your API provides appropriate responses to users.

I hope this helps!

Please note that this approach may not meet your specific needs, but I answered it to the extent I understood the question. 

What do you think @cowtowncoder? Thanks!

**Comment by mukham12** [comment]
My pleasure @safdevke. Thanks.

**Comment by cowtowncoder** [comment]
Hmmh. Original case sounds like a bug, actually; for `READ_ONLY`, explicit `null` should throw an exception. `null`s are values like anything else.

As to handling: another useful thing to know about is `DeserializationProblemHandler` which allows sort of ignoring a few kinds of failure conditions, including that of unrecognized property.

I'll re-open this issue to hopefully have a look on original issue tho, if I can reproduce it (not all details of usage are included).

**Comment by cowtowncoder** [comment]
Ohhh. This about `Record` types, missed that part.

**Comment by cowtowncoder** [comment]
Actually, will close for now.

**Comment by mukham12** [comment]
Hi.

If this is causing issues, I'd be happy to take a look with some guidance. I'm still getting familiar with the code, but I'd be happy to investigate further if you can tell me why you think there might be a bug and what the expected result should be. Thanks!

Also, the OP said that it solved their problem. So maybe no need to do any work. Either way let me know if I can help!

**Comment by cowtowncoder** [comment]
@mukham12 I think behavior between Record and POJO should be same, in general. So one possibility would be to see how POJO works (I think it would indeed throw an exception); then see what happens with Record and proceed from there.
There may be problem with Annotation unification for Records still, although 2.15 branch has improved things a lot.

**Comment by cowtowncoder** [comment]
First of all: this could be useful for other users so thank you for sharing.

Unfortunately usage via 3rd party frameworks is usually not super helpful from Jackson maintainer side since they have their own configuration settings, mechanisms and overrides -- and we cannot include additional dependencies to our unit tests either.

For example: default behavior with Plain Jackson IS to throw exception; Spring Boot does indeed change default configuration here.
