### ISSUE TITLE
"setSerializationInclusion(JsonInclude.Include.NON_NULL)" has no effect

### ISSUE THREAD

**Issue by qingshan1993** [FasterXML/jackson-databind#3823]
**Describe the bug**
"setSerializationInclusion(JsonInclude.Include.NON_NULL)" has no effect

**Version information**
jackson:2.13.5
jdk: zulu-1.8

**To Reproduce**
When i setSerializationInclusion(JsonInclude.Include.NON_NULL), it has no effect
In the following example, I expect s4 = {"age":"18"}.
Did I miss something?  Thanks!

```
public class JacksonIssueTest {

    public static void main(String[] args) throws JsonProcessingException {
        CommonObject commonObject = new CommonObject();
        commonObject.setAge("18");
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
        //default
        objectMapper.setSerializationInclusion(null);
        String s2 = objectMapper.writeValueAsString(commonObject);
        System.out.println("s2: " + s2);
        //s2 = {"name":null,"age":"18"}
        Assertions.assertTrue(s2.contains("name"));

        //ignore null field
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        String s4 = objectMapper.writeValueAsString(commonObject);
        System.out.println("s4: " + s4);
        // s4 = {"name":null,"age":"18"}
        Assertions.assertTrue(!s4.contains("name"));

    }

    public static class CommonObject {
        private String name;
        private String age;

        public void setName(String name) {
            this.name = name;
        }

        public void setAge(String age) {
            this.age = age;
        }
    }
}
```

**Comment by pjfanning** [comment]
https://stackoverflow.com/questions/37406817/jackson-objectmapper-setserializationinclusion-not-working answers says you set the ObjectMapper config once and not change it. What happens if the `objectMapper.setSerializationInclusion(null)` bit?

**Comment by cowtowncoder** [comment]
Right, as @pjfanning suggested, the test is invalid: you CANNOT reconfigure `ObjectMapper` after it has been used (readValue(), writeValue()) -- initial settings may not take effect (or, if you are unlucky, might take effect; this is not specified).
In your case configuration is used to construct actual `JsonSerializer` instances with settings in effect at that point; these serializers are cached and reused for the life of `ObjectMapper`.

If you need to use different global settings you need to create two differently configure `ObjectMapper`s.
The basic rule of configuration is that ALL configuration set through `ObjectMapper` MUST be set before first use and SHOULD NOT be changed after that.

But conversely anything configurable using `ObjectReader` or `ObjectWriter` (you create these from `ObjectMapper`) can be changed between calls (new instances of readers, writers are constructed and this is thread-safe).

I hope this helps.

**Comment by qingshan1993** [comment]
> Right, as @pjfanning suggested, the test is invalid: you CANNOT reconfigure `ObjectMapper` after it has been used (readValue(), writeValue()) -- initial settings may not take effect (or, if you are unlucky, might take effect; this is not specified). In your case configuration is used to construct actual `JsonSerializer` instances with settings in effect at that point; these serializers are cached and reused for the life of `ObjectMapper`.
> 
> If you need to use different global settings you need to create two differently configure `ObjectMapper`s. The basic rule of configuration is that ALL configuration set through `ObjectMapper` MUST be set before first use and SHOULD NOT be changed after that.
> 
> But conversely anything configurable using `ObjectReader` or `ObjectWriter` (you create these from `ObjectMapper`) can be changed between calls (new instances of readers, writers are constructed and this is thread-safe).
> 
> I hope this helps.

Thank you for your answer.
