### ISSUE TITLE
`Optional<Boolean>` is not recognized as boolean field

### ISSUE THREAD

**Issue by thnaeff** [FasterXML/jackson-databind#3836]
A method like this

```
  public Optional<Boolean> isUsed() {
    return Optional.ofNullable(used);
  }
```

does not seem to get automatically recognized by Jackson as a field to include for serialization, meaning that it does not appear in the serialized JSON at all.

Changing it to this works since it is now a standard boolean return type
```
  public Boolean isUsed() {
    return used;
  }
```

What also works is annotating it. However, this then produces a field `isUsed` (it does not strip the `is` as it generally happens for boolean properties). Annotating a `Optional<String> get...` method with `@JsonProperty` works as expected with stripping the `get`.
```
  @JsonProperty
  public Optional<Boolean> isUsed() {
    return Optional.ofNullable(used);
  }
```

So to get the "standard" boolean field behavior it needs
```
  @JsonProperty("used")
  public Optional<Boolean> isUsed() {
    return Optional.ofNullable(used);
  }
```

Any `get` methods are recognized by default, so I would think this is an issue specific to boolean properties.

I should note that this has been run with `jackson-datatype-jdk8`/`-annotations`/`-core` v2.13.3 as well as v2.15.0-rc1, both with same behavior

**Comment by cowtowncoder** [comment]
Ok so the location for the fix is method `findNameForIsGetter()` in `DefaultAccessorNamingStrategy`:

```
        if (_isGetterPrefix != null) {
            final Class<?> rt = am.getRawType();
            if (_isGettersNonBoolean || rt == Boolean.class || rt == Boolean.TYPE) {
                if (name.startsWith(_isGetterPrefix)) {
                    return _stdBeanNaming
                            ? stdManglePropertyName(name, 2)
                            : legacyManglePropertyName(name, 2);
                }
            }
        }
```

where we need to change things a bit. But it seems pretty much doable.

**Comment by cowtowncoder** [comment]
Fixed, tested with `AtomicBoolean` and `AtomicReference<Boolean>` -- should work for `Optional<Boolean>` too.

Actually will verify in `master`.
