### ISSUE TITLE
Customer JsonDeserializer throw a StackOverFlowException

### ISSUE THREAD

**Issue by littlestar2125** [FasterXML/jackson-databind#3839]
hello,i creat a customer JsonDeserializer to check json data,i want to judge if json data has "chargeNum" property,i want creat subClass,then i want create this class,just like this:

```
@JsonDeserialize(using = CostListAndBindAmountVO.CostListAndBindAmountVODeserializer.class)
public class CostListAndBindAmountVO extends CostListVO {
    private BigDecimal bindAmount;

    public static class CostListAndBindAmountVODeserializer extends JsonDeserializer<CostListAndBindAmountVO> {
        @Override
        public CostListAndBindAmountVO deserialize(JsonParser parser, DeserializationContext context) throws IOException {
            ObjectCodec codec = parser.getCodec();
            JsonNode node = codec.readTree(parser);
            if (node.has("chargeNum")) {
                return JSON.parseObject(node.toString(), CostChargeDetailVO.class);
//                return node.traverse(codec).readValueAs(CostChargeDetailVO.class);
            } else {
//                return node.traverse(codec).readValueAs(CostListAndBindAmountVO.class);
                return JSON.parseObject(node.toString(), CostListAndBindAmountVO.class);
            }
        }
    }
}
```
now,i can't use jackson's method to deserialize CostListAndBindAmountVO class,because it always call the deserialize method,then throw StackOverFlowException,how can i use jackson's method to do this?

**Comment by cowtowncoder** [comment]
@littlestar2125 You would need to register a `BeanDeserializerModifier`, which gives you access to the "standard" deserializer and then you can construct your own and pass it a reference to standard deserializer to use (delegate). It exposes 3 methods (I think), of which modifyDeserializer()` is what you want. You just need to make sure it is being called for type (class) for which you want to change deserializer to use.

**Comment by littlestar2125** [comment]
> 
@cowtowncoder Can I get an example?I did not find an introduction about BeanDeserializerModifier

**Comment by littlestar2125** [comment]
> @littlestar2125 Have a look at unit tests, there should be something. Otherwise googling for `BeanDeserializerModifier jackson` is probably your best bet.
> 
> Seems there's one potential hit: https://stackoverflow.com/questions/48390287/how-to-use-jackson-beandeserializermodifier
Thanks for your help,but i thought this case can't help me.because i want deserialize this class use jackson method,and then  it always called the deserialize method and throw stackoverflow exception,i jsut want to find json data contains "chargeNum" property then deserialize to CostListAndBindAmountVO's sub class which names is CostChargeDetailVO,else i want deserialize to CostListAndBindAmountVO,i thought if i use BeanDeserializerModifier can't help me,i try to use it,but i still need to check if contains "chargeNum" then deserialize to CostChargeDetailVO,so BeanDeserializerModifier  can't help me.

**Comment by cowtowncoder** [comment]
@littlestar2125 Ok. Best of luck to you then. `BeanDeserializerModifier` is the mechanism to use if you need to rely on "default" deserializer Jackson would construct.
