### ISSUE TITLE
Inheritance info lost for generic list or generic type with generic list

### ISSUE THREAD

**Issue by SetoKaiba** [FasterXML/jackson-databind#3841]
**Describe the bug**
I try to deserialize a list. And I found the inheritance info lost.

**Version information**
2.14.2

**To Reproduce**
```java
                    ObjectMapper objectMapper = new ObjectMapper();
                    try {
                        System.out.println("baba:" + objectMapper.writeValueAsString(items));
                        for (Item item : items) {
                            System.out.println("caca:" + objectMapper.writeValueAsString(item));
                        }
                        ItemList itemList = new ItemList(items);
                        System.out.println("dada:" + objectMapper.writeValueAsString(itemList));
                        LiveListResponse<Item> liveListResponse = new LiveListResponse<>(items);
                        System.out.println("eaea:" + objectMapper.writeValueAsString(liveListResponse));
                    } catch (Exception e) {
                        e.printStackTrace();
                        throw new RuntimeException(e);
                    }
```
```java
public class ItemList extends LiveListResponse<Item> {
}
```
```java
public class LiveListResponse<T> {
    public List<T> list;
}
```
Inheritance info lost for generic list or generic type with generic list
```
baba:[{"id":30664403225411584,"guid":"6629c272-bae3-0404-3962-8917038a75bf","name":"初音头发","part":"Hair","idString":"30664403225411584"}]
caca:{"$type":"ClothingItem, Assembly-CSharp","id":30664403225411584,"guid":"6629c272-bae3-0404-3962-8917038a75bf","name":"初音头发","part":"Hair","idString":"30664403225411584"}
dada:{"list":[{"$type":"ClothingItem, Assembly-CSharp","id":30664403225411584,"guid":"6629c272-bae3-0404-3962-8917038a75bf","name":"初音头发","part":"Hair","idString":"30664403225411584"}]}
eaea:{"list":[{"id":30664403225411584,"guid":"6629c272-bae3-0404-3962-8917038a75bf","name":"初音头发","part":"Hair","idString":"30664403225411584"}]}
```
1. List&lt;Item&gt; not working
2. Item working
3. ItemList extends LiveListResponse&lt;Item&gt; working.
4. LiveListResponse&lt;Item&gt; not working.

**Expected behavior**
All the deserialization should have inheritance info.

**Comment by SetoKaiba** [comment]
It's a common usage with List<xxx> with Resteasy Reactive. It would be crazy for wrap all the restful endpoint of list. This is common. It's simple to just return the list. But the list serialization doesn't serialize the inheritance info.
```
    @Path("/item/list/{page}")
    @GET
    @WithSession
    public Uni<List<Item>> itemList(int page) {
        return Item.<Item>findAll().page(page, 10).list().invoke(items -> {
            ObjectMapper objectMapper = new ObjectMapper();
            try {
                System.out.println("gagagaga:" + objectMapper.writeValueAsString(items));
                for (Item item : items) {
                    System.out.println("zazazaza:" + objectMapper.writeValueAsString(item));
                }
                ItemList itemList = new ItemList();
                itemList.list = items;
                System.out.println("fafafafa:" + objectMapper.writeValueAsString(itemList));
            } catch (Exception e) {
                e.printStackTrace();
                throw new RuntimeException(e);
            }
        });
    }
```

**Comment by cowtowncoder** [comment]
First of all, example is missing definition of `Item` -- unless it has `@JsonTypeInfo` (or Default Typing is included), no type information is (or should) be included. So could you please included `Item` class definition.

In addition, note that Resteasy Reactive handling differs because Jackson cannot introspect endpoints: it is Resteasy that passes necessary type information: if it simply passes value of `List<Item>`, Java Type Erasure will prevent access to declared type. This would explain lack of polymorphism.

So as things are this may or may not work as expected: inclusion of `List` will help figure out this.

**Comment by SetoKaiba** [comment]
I added `@JsonTypeInfo` already. As you can see the other two way output the $type propety.
The problem is that it seems the generic in Java is compiled time, not runtime. It doesn't has such type info for an List<T> instance alone. So wrap is the only method. Right?

**Comment by cowtowncoder** [comment]
@SetoKaiba I asked you to please include `List` definition.

But as to the only mechanism, there are 3 ways (I think you included 2); wrapper POJO is one.

1. Wrapper
2. Sub-classing of `List<X>` as `class XList extends List<X>`
3. Explicitly passing type to construct `ObjectWriter` with known type:

     ObjectWriter w = mapper.writerFor(new TypeReference<List<X>>() { });
     w.writeValueAsString(list);

**Comment by SetoKaiba** [comment]
OK. I see. Thank you. Wrapper is the choice for my code.
