### ISSUE TITLE
StdDateFormat.clone is not a proper clone

### ISSUE THREAD

**Issue by mebigfatguy** [FasterXML/jackson-databind#3861]
**Describe the bug**
We derive from com.fasterxml.jackson.databind.util.StdDateFormat and implement clone in our derived method using super.clone(), but this causes  ClassCastExceptions because StdDateFormat implements clone using new (incorrectly), rather  than super.clone().

**Version information**
2.14.2

**To Reproduce**
public class MyFormat extends StdDateFormat() {
      public MyFormat  clone() {
            try {
                  return (MyFormat) super.clone();
            } catch (CloneNotSupportedException e) {
                  throw new Error("Won't happen");
            }
      }
}

1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.

**Additional context**

**Comment by cowtowncoder** [comment]
`StdDateFormat` is NOT user extensible, not designed for such use case. Please do not try doing that. I can add Javadocs to make sure but this really is an internal class meant for internal usage only.
