### ISSUE TITLE
apply bigdecimal scale check before converting to big int

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-databind#3863]
* see https://github.com/FasterXML/jackson-core/issues/968
* there are 5 toBigInteger calls in jackson-databind code and it will be hard to access StreamReadConstraints (unless StreamReadConstraints,defaults() is used)
* it should be safe to ignore code that takes doubles/floats and applies BigDecimal.valueOf(value).toBigInteger because the max scale of a double is 308.

**Comment by cowtowncoder** [comment]
Fixed via PR merged.
