### ISSUE TITLE
Auto module name in manifest

### ISSUE THREAD

**Issue by debjitk** [FasterXML/jackson-databind#3865]
Please add `MANIFEST.MF` with `Auto-Module-Name`. It would be nice for projects/libraries importing `jackson` as a dependency, building with the new `JAVA 9` modules feature.

**Comment by pjfanning** [comment]
let's discuss in https://github.com/FasterXML/jackson-core/issues/982 - don't create lots of issues - 1 is enough to discuss why you think we do not properly support Java 9+ modules
