### ISSUE TITLE
2.15.0 does not seem to honor PropertyAccessor.IS_GETTER visibility anymore

### ISSUE THREAD

**Issue by fleiber** [FasterXML/jackson-databind#3904]
Here is a small main reproducing the behaviour change:
```kt
import com.fasterxml.jackson.annotation.JsonAutoDetect
import com.fasterxml.jackson.annotation.PropertyAccessor
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.kotlin.KotlinModule


fun main() {
    val mapper = ObjectMapper().apply {
        registerModule(KotlinModule.Builder().build())
        setVisibility(PropertyAccessor.IS_GETTER, JsonAutoDetect.Visibility.NONE)
    }

    class Foo(val bar: Int) {
        val isZero get() = bar == 0
    }

    println(mapper.writeValueAsString(Foo(1)))
    // with Jackson 2.14.2, prints: {"bar":1}
    // with Jackson 2.15.0, prints: {"bar":1,"isZero":false}
}

```
We serialize these classes with `setVisibility(PropertyAccessor.IS_GETTER, Visibility.NONE)` to ignore the isXXX methods, and please note that we cannot use `@JsonIgnore` ("This annotation is not applicable to target 'member property without backing field or delegate'").
Starting with Jackson 2.15.0, the `isZero` property is serialized, then the deserialization fails.
The way we use the visibility feature looks fine to me, this property was correctly ignored at serialization with version 2.14.2, so I would say the 2.15 change does look like a regression.

**Comment by pjfanning** [comment]
Could you move this to the jackson kotlin module? Noone in core jackson team uses Kotlin.

**Comment by fleiber** [comment]
> Could you move this to the jackson kotlin module? Noone in core jackson team uses Kotlin.

As you wish, but I can also edit it to write the same code in Java :)

**Comment by pjfanning** [comment]
try a Java example but as long as this remains a Kotlin example, it will probably require us to pass this off to the Kotlin module team to look at

**Comment by fleiber** [comment]
> try a Java example but as long as this remains a Kotlin example, it will probably require us to pass this off to the Kotlin module team to look at

I could not reproduce in Java, and with the cleaner example shown in the updated description, the issue disappears when removing the KotlinModule... Let me close this issue and open a new one in the Kotlin module repo.

Sorry for the inconvenience,

**Comment by cowtowncoder** [comment]
@fleiber Thank you for checking this. I think this is related to the nasty incompatibility between Kotlin's handling of "isXxx" properties wrt Java Beans handling. I think Kotlin will retain "is" part for logical property name (as per Kotlin spec, perfectly fine), but that does not necessarily play nicely with databind as the rules are different.
But I hope this can be resolved; I don't know what change (and intentional or unintentional) caused behavior to change between versions.
