### ISSUE TITLE
2.15.0 : serialization regression for property with name isComplete

### ISSUE THREAD

**Issue by drapej** [FasterXML/jackson-databind#3934]
**Describe the bug**
Since the v 2.15.0, if a property is declare with the following class, the JSON produce is different. We have something like 
`{isComplete:true}` instead of previously `{complete:true}`

This problem is I think due to this modification : https://github.com/FasterXML/jackson-databind/issues/3682
What we need to do to have the previous JSON ? (rename the property ?)

**Version information**
2.15.0

**To Reproduce**
```kotlin
data class MyClass(
    val objects: Iterable<MyObject> = emptyList()

) { 
  val isComplete
        get() = (objects.filter{it.ok()}.count()) 
}
```

**Comment by pjfanning** [comment]
jackson-databind is a Java library. I think you are running into a documented change in jackson-module-kotlin. 

https://github.com/FasterXML/jackson-module-kotlin/blob/2.16/release-notes/VERSION-2.x#L25-L27

**Comment by drapej** [comment]
> jackson-databind is a Java library. I think you are running into a documented change in jackson-module-kotlin.
> 
> https://github.com/FasterXML/jackson-module-kotlin/blob/2.16/release-notes/VERSION-2.x#L25-L27

Ah sorry of course, i didn't check this lib... thanks for the info
