### ISSUE TITLE
Extend DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT to cover scalar type Objects

### ISSUE THREAD

**Issue by GI-2023** [FasterXML/jackson-databind#3941]
**Describe the bug**
As stated in issue #1588 (further discussions in #1095 and #1106), there is currently no way to prevent mapping of an empty string ("") to Java "numbers" (java.lang.*: e.g. java.lang.Short, java.lang.Integer, java.lang.Long, java.lang.Double), - this always gets converted to null.

In other words, there is no difference between specifying (null) and ("") and there is no way to distinguish between the two.

Disabling MapperFeature.ALLOW_COERCION_OF_SCALARS is of no use, as it prevents valid numbers specified in a string to be processed (e.g. "\"6\"").

**Version information**
2.15.0

**To Reproduce**
import org.springframework.http.converter.json.Jackson2ObjectMapperFactoryBean;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.MapperFeature;

public class Test {

	public static void main(String[] args) throws JsonMappingException, JsonProcessingException {
		Test.acceptEmptyStringAsNullObject();
		Test.allowCoersionOfScalars();
	}
	
	private static final void acceptEmptyStringAsNullObject() throws JsonMappingException, JsonProcessingException  {
        Jackson2ObjectMapperFactoryBean objectMapperFactory = new Jackson2ObjectMapperFactoryBean();
        objectMapperFactory.setFeaturesToDisable(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT);
        try {
            objectMapperFactory.afterPropertiesSet();
        } catch (Exception e) {
            throw new IllegalStateException("afterPropertiesSet() failed", e);
        }
        
		Integer i = objectMapperFactory.getObject().readValue("\"\"", Integer.class);
		System.out.println(i);			
	}

	private static final void allowCoersionOfScalars() throws JsonMappingException, JsonProcessingException  {
        Jackson2ObjectMapperFactoryBean objectMapperFactory = new Jackson2ObjectMapperFactoryBean();
        objectMapperFactory.setFeaturesToDisable(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT, MapperFeature.ALLOW_COERCION_OF_SCALARS);
        try {
            objectMapperFactory.afterPropertiesSet();
        } catch (Exception e) {
            throw new IllegalStateException("afterPropertiesSet() failed", e);
        }
        
		Integer i = objectMapperFactory.getObject().readValue("\"6\"", Integer.class);
		System.out.println(i);			
	}
}

**Current behavior**
1. "null" printed out to stdout
2. Exception thrown in Test.allowCoersionOfScalars: Cannot coerce String value ("6") to `java.lang.Integer` value (but might if coercion using `CoercionConfig` was enabled)

**Expected behavior**
1. Exception thrown in Test.acceptEmptyStringAsNullObject();

**Comment by cowtowncoder** [comment]
Actually there should be specific ways to prevent this with "Coercion Config" system, which is to fully replace coarse `DeserializationFeature`s such as `ACCEPT_EMPTY_STRING_AS_NULL_OBJECT`.

See, f.ex #3013 and later #3613.

**Comment by GI-2023** [comment]
Thanks @cowtowncoder, but I am not 100% sure how do I apply this without writing my own deserializer (something I am trying to avoid).

In a nutshell, I'd like any conversion from String to "numbers" to be successful if the string is a valid number (that also includes "marginal" cases, where float to integers is also permitted, i.e. "6.5" to integer returns "6"), **except** if it is an empty string (""), in which case an exception should be thrown and not convert this to a null.

It goes without saying that null values that are specified explicitly (e.g. "numberProperty: null") should also be accepted.

**Comment by GI-2023** [comment]
`ObjectMapper mapper = objectMapperFactory.getObject();
mapper.coercionConfigFor(LogicalType.Float).setCoercion(CoercionInputShape.EmptyString, CoercionAction.Fail);
mapper.coercionConfigFor(LogicalType.Integer).setCoercion(CoercionInputShape.EmptyString, CoercionAction.Fail);
`

The above pretty much did it, so no need to do anything special and it worked out of the box to `perfection!

**Comment by GI-2023** [comment]
Yes please - the coersion config (something I wasn't aware of existed) works to perfection, so, yes, no need to do anything. Thank you for your support on this.

**Comment by GI-2023** [comment]
Ah, sure. apologies. Closing...
