### ISSUE TITLE
Provide OOB ability to output JSON array elements on the separate lines

### ISSUE THREAD

**Issue by IvanPizhenko** [FasterXML/jackson-databind#3957]
**Is your feature request related to a problem? Please describe.**
We'd like to have arrays in the resulting JSON formatted so that each array element is on the separate line.
For example, now we get following result:
```
{
    "someArray": ["A", "B", "C"]
}
```
But we'd like to have the following:
```
{
    "someArray": [
        "A",
        "B",
        "C"
    ]
}
```

**Describe the solution you'd like**
Provide appropriate array indenter class OOB.

**Usage example**
Something like this:
```java
var prettyPrinter = new DefaultPrettyPrinter();
prettyPrinter.indentArraysWith(new EachElementOnTheSeparateLineArrayIndenter());
```

**Additional context**
no additional context.

**Comment by pjfanning** [comment]
* this is pluggable - ie you can write your own PrettyPrinter implementation
* still possibly a useful enhancement for jackson-databind
* but this is OSS and if you really want a feature, submitting a PR is the best way to get it

**Comment by IvanPizhenko** [comment]
Looks like following does the job:
```java
var prettyPrinter = new DefaultPrettyPrinter();
prettyPrinter.indentArraysWith(DefaultIndenter.SYSTEM_LINEFEED_INSTANCE);
```
