### ISSUE TITLE
Extra content after end of an array is ignored

### ISSUE THREAD

**Issue by marekkrk** [FasterXML/jackson-databind#3977]
**Describe the bug**
Extra content after a square bracket that ends an array is ignored. Example:
`[]abc`

**Version information**
2.15.2

**To Reproduce**
Run the following code:

import com.fasterxml.jackson.databind.ObjectMapper;

public class ParseArray {

    public static void main(String[] args) throws Exception {
        var mapper = new ObjectMapper();
        var obj = mapper.readValue("[]abc", Object.class);
        System.out.println(obj);
    }
}

**Expected behavior**
A parse exception is thrown.

**Additional context**
No exception, an empty list is printed to standard out.

**Comment by marekkrk** [comment]
This also applies to curly brackets. Example:
`{}y`

**Comment by JooHyukKim** [comment]
@marekkrk thank you for reporting! 🙏🏼 I think either this should not be allowed, or at least have configuration to enable/disable. 

One question though. does your stated `Expected behahior` come from previous Jackson version, or out of convention? For example like this wasn't the case in Jackson 2.14.0.

**Comment by yawkat** [comment]
this is intended, you can enable FAIL_ON_TRAILING_TOKENS if you want

**Comment by marekkrk** [comment]
> this is intended, you can enable FAIL_ON_TRAILING_TOKENS if you want

Thanks, this solves the problem. But why is this not enabled by default?

**Comment by yawkat** [comment]
see #3406 and the linked discussion
