### ISSUE TITLE
No content in repository (2.15.2)

### ISSUE THREAD

**Issue by mimenz** [FasterXML/jackson-databind#3985]
Hi there,

I can download the jar files for v2.15.2 in the Maven repo for jackson-core and jackson-annotation.
But there is no content when browsing the url https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.2
Can you help?

BTW: thanks for the great lib!

Bye, Michael

**Comment by yawkat** [comment]
the jar and pom works fine: https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.2/jackson-databind-2.15.2.jar

the directory listings not working seems like just a sonatype issue.

**Comment by mimenz** [comment]
Your're right, thanks!
Haven't tried that...

**Comment by cowtowncoder** [comment]
Yes, I observed this same issue with Sonatype during release process. No idea if it is accidental or intentional -- and it's something that made release tracking more difficult too. So I hope it is something accidental Sonatype will resolve.
