### ISSUE TITLE
Apply improved handling of `Enum` to all part

### ISSUE THREAD

**Issue by JooHyukKim** [FasterXML/jackson-databind#3990]
## Motivation 

Since #3832 introduced handling of `Enum` values as `Annotated` which allowed more dynamic handling of `Enum` types. But as of writing, such improvement is not retrofitted to all parts within our project.

This issue will serve as parent issue to keep futre improvements in one place.

### Introspection/Annotations/mixins
- (very first) #3832
- #4025

### Deserialization (EnumResolver)
- #4032
- #4033 
- #4034
- #4000

### Serialization (EnumValues)
- #4039
- #4040
- #3991

**Comment by cowtowncoder** [comment]
It does sound like we are done -- there may still be some minor bugs, missing handling, but it sounds like known issues have been resolved.
