### ISSUE TITLE
JsonPointer lookups for different nodes return the same node instances if they have the same values

### ISSUE THREAD

**Issue by costas80** [FasterXML/jackson-databind#4003]
**Describe the bug**

Calling `JsonNode.at()` with pointer expressions that should result in different nodes, return the same node instances if they have the same values. From my experimentation this does not happen with object nodes, only with primitive nodes such as  `IntNode`.

**Version information**

2.15.0

**To Reproduce**

The issue can be fully reproduced with the following unit test:

```java
  @Test
  void testAtJsonPointer() throws JsonProcessingException {
      String json = "{ \"foo\": [" +
              "{ \"prop1\": 1, \"prop2\": 2 },"+
              "{ \"prop1\": 1, \"prop2\": 2 }"+
      "]}";
      JsonNode root = new ObjectMapper().readTree(json);
      JsonNode node1 = root.at("/foo/0/prop2");
      JsonNode node2 = root.at("/foo/1/prop2");
      // Two different nodes should be returned, however the following assertion fails (the same IntNode instances are returned)..
      assertNotSame(node1, node2);
  }
```

The two JSON pointer expressions should return different `IntNode` instances however they both return the same instance. While debugging I noticed that at the point when the JSON string is parsed, the `IntNode` instances for the same values are the same exact instances. I would expect that these should be separate instances that have the same value (i.e. are equal but not identical).

**Additional context**

This issue came up as part of our custom software to validate JSON. When validation completes all reported issues include the JSON pointer of the offending node which we use to determine line numbers to highlight. In scenarios such as the one I describe above however, this breaks for nodes with the same primitive values as the different JSON pointers always result in the same node instances.

**Comment by pjfanning** [comment]
I, for one, see nothing wrong with the existing behaviour. IntNodes only wrap ints. They have no field linking to a parent node.

It is more performant to not keep creating new instances of IntNode in the case where you have 2 integers in the JSON input with the same value.

Many users might rely on the existing behaviour.

So, for me, since there is the existing behaviour is a legitimate solution - I don't see any benefit in changing it - and there are risks to changing the behaviour.

**Comment by yawkat** [comment]
theres no guarantee it has to produce different nodes

**Comment by costas80** [comment]
Fair enough @pjfanning and @yawkat. Would it be too much to hope for a configuration option when creating the `ObjectMapper` to ensure that each encountered JSON node is mapped to a distinct node instance? The default behaviour would remain the current approach but it would allow edge cases such as the one I describe.

**Comment by pjfanning** [comment]
Wouldn't be a priority for me. jackson-databind is already complicated enough. You're welcome to fork jackson-databind and hack it to suit your needs.

**Comment by yawkat** [comment]
you can already provide your own JsonNodeFactory if you wish, it seems too niche for a config option

and imo it's a weird thing to want to do in the first place, maybe try implementing it a different way

**Comment by costas80** [comment]
Ok thanks for the feedback. I'll check to see where I can get with a custom `JsonNodeFactory` and close this issue.
