### ISSUE TITLE
Change in behavior of parameter analysis for Enum.valueOf in Jackson 3.0.

### ISSUE THREAD

**Issue by k163377** [FasterXML/jackson-databind#4019]
As the subject states, this is in Jackson 3.0.

In `Jackson 3.0` I noticed that `AnnotationIntrospector.hasRequiredMarker` is being called for the parameter `Enum.valueOf`.
This was not called in `Jackson 2.0`.

I have not been able to check the detailed behavior, but since `Enum.valueOf` is a function that cannot be overridden, there seems to be no point in doing all the parsing processing, not just for `hasRequiredMarker`.
Therefore, shouldn't this be skipped?

---

This change causes the following tests to fail, for example
https://github.com/FasterXML/jackson-module-kotlin/blob/master/src/test/kotlin/tools/jackson/module/kotlin/test/github/TestCasesFromSlack.kt

relates to https://github.com/FasterXML/jackson-module-kotlin/issues/555

**Comment by cowtowncoder** [comment]
I am not sure I follow this one -- why/how is this causing problems? What is getting `Enum.valueOf()` as parameter?
Which part of processing?

Maybe a PR for changing behavior would make sense here -- it is is possible the change could be due to incomplete/incorrect merge from 2.x.

**Comment by k163377** [comment]
> why/how is this causing problems?

In 2.x, `AnnotationIntrospector.hasRequiredMarker` is not called for `Enum.valueOf()` parameter.
On the other hand, it seems to be called in 3.0.

The current `kotlin-module` does not assume parsing of functions that do not require instance parameter on `kotlin-reflect`, so [this code](https://github.com/FasterXML/jackson-module-kotlin/blob/01082da3a31fe0c627752eef7e6642e97d714470/src/main/kotlin/tools/jackson/module/kotlin/KotlinAnnotationIntrospector.kt#L188) causes an error.

**Comment by cowtowncoder** [comment]
@k163377 Oh. The one parameter of static `Enum.valueOf(String)` method.

I don't think that would have been an intentional change for just that method, but rather a side effect of something else. But if so, it probably was changed years ago.

**Comment by cowtowncoder** [comment]
I am not sure how to proceed here. @k163377 would it be possible to convert the Kotlin test to Java-only reproduction?
I need to understand why this (likely) unnecessary call causes actual problems, as opposed to just being overhead.
Like I said, I do not remember any conscious change so it is likely a side effect of some change.

**Comment by k163377** [comment]
> would it be possible to convert the Kotlin test to Java-only reproduction?

The `IndexOutOfBoundsException` in `kotlin-module` is caused by `kotlin-module` specific processing.
Therefore, it cannot be reproduced only in `Java`.

**Comment by cowtowncoder** [comment]
@k163377 Ok but why does Kotlin module not do proper bounds checks? Is this an issue with Kotlin runtime?
I don't think there should be an exception throwing for calling `hasRequiredMarker()` on any legal accessor (method, field etc)?

I guess, however, that calling it on a static accessor does not make sense if that is the case.

So, just to make sure I understand: the original statement is:

```
In Jackson 3.0 I noticed that AnnotationIntrospector.hasRequiredMarker is being called for the parameter Enum.valueOf.
```

I think this means `static` method `valueOf(...)` on `Enum.class`. If so, you are right, that is not useful.
Since Java-only reproduction is not easy to do (or won't reproduce quite the same way), could you instead just add stack trace through `jackson-databind` so it's bit easier for me to see, and hopefully prevent call.

**Comment by k163377** [comment]
I did some research.

First, I confirmed that the problem of the `Enum.valueOf` parameter being parsed cannot be reproduced by a simple test.
I created the following test based on [TestCasesFromSlack1](https://github.com/FasterXML/jackson-module-kotlin/blob/bd3b2c9e75430ab77c2cb1de77ea5473d9773ce4/src/test/kotlin/tools/jackson/module/kotlin/test/github/TestCasesFromSlack.kt#L34-L35), but this test does not seem to reproduce the problem.

```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.junit.Test;

public class Temp {
    enum RSVP {
        going("rsvp.going"), maybe("rsvp.maybe"), interested("rsvp.interested");

        private final String nameKey;

        RSVP(String nameKey) {
            this.nameKey = nameKey;
        }

        public String getNameKey() {
            return nameKey;
        }
    }

    static class Dto {
        private RSVP rsvp;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        Dto(
                @JsonProperty("rsvp") RSVP rsvp
        ) {
            this.rsvp = rsvp;
        }

        @JsonProperty("rsvp")
        public RSVP getRsvp() {
            return rsvp;
        }

        public void setRsvp(RSVP rsvp) {
            this.rsvp = rsvp;
        }
    }

    @Test
    public void test() {
        ObjectMapper mapper = new ObjectMapper();

        Dto dto = mapper.readValue("{\"rsvp\":\"going\"}", Dto.class);
        System.out.println(dto);
    }
}
```

I will continue to research why this makes such a difference.

---

As for the `kotlin-module` implementation, it is the result of optimization.
As of `2.x`, the boundary checks were not needed, so my priority was to minimize the load.
Of course this part could be modified, but I didn't think it was necessary to change `kotlin-module` if it could be fixed by `databind`.

**Comment by k163377** [comment]
I found what seems to be the cause.

The `findCreatorAnnotation` should return `null` if it is not a creator, but `master` is returning `DEFAULT` (still overriding `hasCreatorAnnotation` in `2.x`).
https://github.com/FasterXML/jackson-module-kotlin/blob/bd3b2c9e75430ab77c2cb1de77ea5473d9773ce4/src/main/kotlin/tools/jackson/module/kotlin/KotlinNamesAnnotationIntrospector.kt#L123

Very sorry, this is clearly a deficiency in the `kotlin-module` and this issue was a mistake.

**Comment by cowtowncoder** [comment]
Ahhhhhh. So `hasCreatorAnnotation()` not `hasRequiredMarker()`! Now this make much more sense. Thank you for digging in this @k163377 .
