### ISSUE TITLE
Question: select subtype when serializing in case multiple names are present for the same type

### ISSUE THREAD

**Issue by amseager** [FasterXML/jackson-databind#4064]
### Describe your Issue

Suppose I have smth like this (took it from [this issue](https://github.com/FasterXML/jackson-databind/issues/312#issuecomment-30356388)):
```
@JsonTypeInfo(  
    use = JsonTypeInfo.Id.NAME,  
    include = JsonTypeInfo.As.PROPERTY,  
    property = "animalType",
    visible = true)  
@JsonSubTypes({  
    @Type(value = Mammal.class, name = "ZEBRA"),  
    @Type(value = Mammal.class, name = "SHEEP"),  
    @Type(value = Bird.class, name = "PARROT"),
        @Type(value = Bird.class, name = "OWL")})
public class Animal{
```
Suppose that it also wrapped in some other object:
```
public class AnimalWrapper {
    public Animal animal;
}
```
Now you want to convert it to e.g. HashMap<String, Object>:
```
Map<String, Object> result = objectMapper.convertValue(animalWrapperObject, new TypeReference<>() {
            });
```
As I understood, in case of "Mammal" object, the very first name ("ZEBRA") will be selected as a key (string).

The question is about configuring jackson somehow to be able to select other values ("SHEEP" etc.). Maybe some settings are already exist for it?

**Comment by cowtowncoder** [comment]
Currently this should fail on attempt to serialize, due to ambiguity, I think.
If not that should be the first name.
And no, there is no way to change the behavior, whichever it is.

One thing that might work is to use explicit `@JsonTypeName` on `Mammal`: since it only takes one value, that should be the primary name to use.

**Comment by amseager** [comment]
@cowtowncoder thank you for the response.
In my case, this is a generated class, I can't change it, that's why I was thinking about some workarounds with jackson. Will try to do smth else with it then.
I'm closing this issue.
