### ISSUE TITLE
How to configure a custom serializer for the value of a specified key in a Map?

### ISSUE THREAD

**Issue by labulalala** [FasterXML/jackson-databind#4068]
### Describe your Issue

I have a Map<String,Object> = new HashMap(). I want to configure a serializer for the value corresponding to the key named "specialKey" (or other keys). At first I tried to override the parent class (MapSerializer.class) serialization method to implement this. However, I realized it would lose a lot of logic from the original source code. Is there a better approach to accomplish this?

**Comment by pjfanning** [comment]
This is a bug tracker - not a support site. I would suggest reading https://www.baeldung.com/jackson-map. There is also Stackoverflow. Open Source projects put some onus on users to use the internet to do some of their own research.

**Comment by cowtowncoder** [comment]
Also, Jackson user mailing list:

https://groups.google.com/g/jackson-user

is a good place to ask questions.
