### ISSUE TITLE
generateJsonSchema method performing differently in moving from jackson databind version 2.8 to 2.9

### ISSUE THREAD

**Issue by RaviGupta8080** [FasterXML/jackson-databind#4069]

**Comment by pjfanning** [comment]
Reformatted - but this is not actionable. We would need NewClientRequest class definition to reproduce this.

It would help a lot if @RaviGupta8080 could also provide the schemas generated using both versions of Jackson (2.8 and 2.9) so people don't need to do that busy work themselves.

Also note that Jackson is planning to abandon JSON Schema support because of lack of interest in the feature.

**Comment by RaviGupta8080** [comment]
> Reformatted - but this is not actionable. We would need NewClientRequest class definition to reproduce this.
> 
> It would help a lot if @RaviGupta8080 could also provide the schemas generated using both versions of Jackson (2.8 and 2.9) so people don't need to do that busy work themselves.
> 
> Also note that Jackson is planning to abandon JSON Schema support because of lack of interest in the feature.





schema generated for 2.8 :

{
    "type": "object",
    "properties": {
        "retryAttempts": {
            "type": "integer"
        },
        "setupModerationGuidelines": {
            "type": "boolean"
        },
        "setupUserManagement": {
            "type": "boolean"
        },
        "updateSalesforceAccountSyndication": {
            "type": "boolean"
        },
        "updateSalesforceServiceContracts": {
            "type": "boolean"
        },
        "packageType": {
            "type": "string"
        },
        "salesforceData": {
            "type": "object",
            "properties": {
                "contractLineItems": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "productId": {
                                "type": "string"
                            },
                            "bvSiteId": {
                                "type": "string"
                            },
                            "recordType": {
                                "type": "string"
                            },
                            "id": {
                                "type": "string"
                            },
                            "attributes": {
                                "type": "string"
                            }
                        }
                    }
                },
                "contactId": {
                    "type": "string"
                },
                "opportunityId": {
                    "type": "string"
                },
                "singleSignOn": {
                    "type": "string"
                },
                "clientEmail": {
                    "type": "string"
                }
            }
        },
        "clientId": {
            "type": "string"
        },
        "sharedKey": {
            "type": "string"
        },
        "password": {
            "type": "string"
        },
        "firstName": {
            "type": "string"
        },
        "lastName": {
            "type": "string"
        },
        "created": {
            "type": "string"
        },
        "prrBundleName": {
            "type": "string"
        },
        "prrTemplateToUse": {
            "type": "string"
        },
        "prrPasswordSha1Hash": {
            "type": "array",
            "items": {
                "type": "byte"
            }
        },
        "prrAppList": {
            "type": "string"
        },
        "cloudFrontTemplateUrl": {
            "type": "string"
        },
        "cloudFrontStackId": {
            "type": "string"
        },
        "lastUpdated": {
            "type": "string"
        },
        "prrClientTrunkDirectoryUrl": {
            "type": "string"
        },
        "lastClientCommittedRevision": {
            "type": "string"
        },
        "cloudFrontDeploymentName": {
            "type": "string"
        },
        "cloudFrontDeploymentDomain": {
            "type": "string"
        },
        "status": {
            "type": "string",
            "enum": [
                "NEW",
                "CREATED",
                "PROCESSING",
                "COMPLETED",
                "CANCELING",
                "CANCELED",
                "RETRYING",
                "ERROR",
                "MANUAL"
            ]
        },
        "provisioningType": {
            "type": "string",
            "enum": [
                "NEW_CONVERSATIONS",
                "UPGRADE_CONNECTIONS_ONLY",
                "UPGRADE_CUR_ONLY",
                "POWER_REVIEWS_CLIENT",
                "EXTENDED_NETWORK_CLIENT",
                "NEW_PRR",
                "NEW_PRR_RELATED",
                "CURALATE_ONLY",
                "ALPINE_CLIENT",
                "NEW_CONVERSATIONS_RELATED",
                "UPGRADE_BRAND_ANSWER"
            ]
        },
        "clientDisplayName": {
            "type": "string"
        },
        "clientName": {
            "type": "string"
        },
        "locales": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "displayCode": {
            "type": "string"
        },
        "relatedClient": {
            "type": "string"
        },
        "cluster": {
            "type": "string"
        },
        "customerServiceURL": {
            "type": "string"
        },
        "stepName": {
            "type": "string",
            "enum": [
                "CLUSTER_CHECK",
                "PRR_VALIDATE",
                "CLIENT_RECORD",
                "CLIENT_INSTALL_STAGING",
                "CLIENT_INSTALL_PRODUCTION",
                "PRR_CREATE_SVN_FOLDERS",
                "PRR_BUILD_TRUNK_FOLDERS",
                "PRR_UPDATE_PARENT_BUNDLE",
                "PRR_CLEAN_UP_SVN",
                "PRR_CREATE_CLIENT_CLOUD_FRONT_STACK",
                "PRR_STAND_UP_CLIENT_CLOUD_FRONT_STACK",
                "PRR_VERIFY_CLIENT_CLOUD_FRONT_STACK_UP",
                "PRR_CLOUD_FRONT_TO_AKAMAI_DNS",
                "PRR_ADD_CLIENT_TO_AKAMAI_DNS",
                "PRR_ADD_CLIENT_TO_AKAMAI_PROPERTY",
                "WORKBENCH_CLIENT_UPDATE_STG",
                "WORKBENCH_CLIENT_UPDATE_PROD",
                "SWAT_STAGING_KEY_GENERATION_STEP",
                "STAGING_KEY_GENERATION_STEP",
                "SWAT_PROD_KEY_GENERATION_STEP",
                "PROD_KEY_GENERATION_STEP",
                "CONVAPI_PROVISIONING_STEP",
                "CONVAPI_VERIFICATION_STEP",
                "DIMSUM_SETUP",
                "PRR_DIMSUM_SETUP",
                "EXTENDED_NETWORK_SETUP",
                "SERVICE_LEVEL_TEMPLATE_STEP",
                "CUSTOMER_SERVICE_URL_STEP",
                "EMAIL_TEMPLATE_INMAIL_STEP",
                "PRODUCT_SAMPLING_STEP",
                "AGREEMENTS_STEP",
                "RR_DATA_GENERATION_STEP",
                "AA_DATA_GENERATION_STEP",
                "PROVISION_PRODUCTION_FTP",
                "PROVISION_STAGING_FTP",
                "SALESFORCE_BV_SITE",
                "UPDATE_WORKBENCH",
                "SALESFORCE_SYNDICATION_UPDATE",
                "SALESFORCE_SERVICE_CONTRACT_UPDATE",
                "MODERATION_GUIDELINES_SETUP",
                "USER_MANAGEMENT_STEP",
                "PRR_JIRA_STEP",
                "DATA_TEAM_MANUAL_STEP"
            ]
        },
        "jiraTicket": {
            "type": "string"
        },
        "errors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "featureFlags": {
            "type": "object"
        },
        "companyName": {
            "type": "string"
        },
        "streetAddress": {
            "type": "string"
        },
        "postalZipCode": {
            "type": "string"
        },
        "country": {
            "type": "string"
        },
        "emailSenderFromName": {
            "type": "string"
        },
        "emailServiceProvider": {
            "type": "string",
            "enum": [
                "AMAZON_SES",
                "EXACT_TARGET"
            ]
        },
        "billingID": {
            "type": "string"
        },
        "salesforceID": {
            "type": "string"
        },
        "clientVertical": {
            "type": "string"
        },
        "maxSpotlights": {
            "type": "string"
        },
        "domains": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "domainAddress": {
                        "type": "string"
                    },
                    "allowSubdomain": {
                        "type": "boolean",
                        "required": true
                    },
                    "firstPartyCookieEnabled": {
                        "type": "boolean",
                        "required": true
                    },
                    "thirdPartyCookieEnabled": {
                        "type": "boolean",
                        "required": true
                    }
                }
            }
        },
        "prrDomain": {
            "type": "string"
        },
        "prrSFTPUsername": {
            "type": "string"
        },
        "prrSFTPPassword": {
            "type": "string"
        },
        "prrBvApiHostName": {
            "type": "string"
        },
        "prrEncodingKey": {
            "type": "string"
        },
        "prrFeatures": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "requester": {
            "type": "string"
        },
        "city": {
            "type": "string"
        },
        "emailSenderFromAddress": {
            "type": "string"
        },
        "implementationTemplate": {
            "type": "string"
        },
        "prrDisplayCodeFeatures": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "state": {
            "type": "string"
        },
        "regionID": {
            "type": "string"
        },
        "prrLocale": {
            "type": "string"
        },
        "id": {
            "type": "string"
        }
    }
}






Schema generated for 2.9 : 

{
    "type": "object",
    "properties": {
        "retryAttempts": {
            "type": "integer"
        },
        "setupModerationGuidelines": {
            "type": "boolean"
        },
        "setupUserManagement": {
            "type": "boolean"
        },
        "updateSalesforceAccountSyndication": {
            "type": "boolean"
        },
        "updateSalesforceServiceContracts": {
            "type": "boolean"
        },
        "packageType": {
            "type": "string"
        },
        "salesforceData": {
            "type": "object",
            "properties": {
                "contractLineItems": {
                    "type": "array"
                },
                "contactId": {
                    "type": "string"
                },
                "opportunityId": {
                    "type": "string"
                },
                "singleSignOn": {
                    "type": "string"
                },
                "clientEmail": {
                    "type": "string"
                }
            }
        },
        "prrClientTrunkDirectoryUrl": {
            "type": "string"
        },
        "lastClientCommittedRevision": {
            "type": "string"
        },
        "cloudFrontDeploymentName": {
            "type": "string"
        },
        "cloudFrontDeploymentDomain": {
            "type": "string"
        },
        "clientId": {
            "type": "string"
        },
        "sharedKey": {
            "type": "string"
        },
        "password": {
            "type": "string"
        },
        "firstName": {
            "type": "string"
        },
        "lastName": {
            "type": "string"
        },
        "created": {
            "type": "string"
        },
        "prrBundleName": {
            "type": "string"
        },
        "prrTemplateToUse": {
            "type": "string"
        },
        "prrPasswordSha1Hash": {
            "type": "array",
            "items": {
                "type": "byte"
            }
        },
        "prrAppList": {
            "type": "string"
        },
        "cloudFrontTemplateUrl": {
            "type": "string"
        },
        "cloudFrontStackId": {
            "type": "string"
        },
        "lastUpdated": {
            "type": "string"
        },
        "emailSenderFromAddress": {
            "type": "string"
        },
        "prrDisplayCodeFeatures": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "implementationTemplate": {
            "type": "string"
        },
        "prrEncodingKey": {
            "type": "string"
        },
        "prrFeatures": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "provisioningType": {
            "type": "string",
            "enum": [
                "NEW_CONVERSATIONS",
                "UPGRADE_CONNECTIONS_ONLY",
                "UPGRADE_CUR_ONLY",
                "POWER_REVIEWS_CLIENT",
                "EXTENDED_NETWORK_CLIENT",
                "NEW_PRR",
                "NEW_PRR_RELATED",
                "CURALATE_ONLY",
                "ALPINE_CLIENT",
                "NEW_CONVERSATIONS_RELATED",
                "UPGRADE_BRAND_ANSWER"
            ]
        },
        "clientDisplayName": {
            "type": "string"
        },
        "clientName": {
            "type": "string"
        },
        "locales": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "displayCode": {
            "type": "string"
        },
        "relatedClient": {
            "type": "string"
        },
        "cluster": {
            "type": "string"
        },
        "customerServiceURL": {
            "type": "string"
        },
        "stepName": {
            "type": "string",
            "enum": [
                "CLUSTER_CHECK",
                "PRR_VALIDATE",
                "CLIENT_RECORD",
                "CLIENT_INSTALL_STAGING",
                "CLIENT_INSTALL_PRODUCTION",
                "PRR_CREATE_SVN_FOLDERS",
                "PRR_BUILD_TRUNK_FOLDERS",
                "PRR_UPDATE_PARENT_BUNDLE",
                "PRR_CLEAN_UP_SVN",
                "PRR_CREATE_CLIENT_CLOUD_FRONT_STACK",
                "PRR_STAND_UP_CLIENT_CLOUD_FRONT_STACK",
                "PRR_VERIFY_CLIENT_CLOUD_FRONT_STACK_UP",
                "PRR_CLOUD_FRONT_TO_AKAMAI_DNS",
                "PRR_ADD_CLIENT_TO_AKAMAI_DNS",
                "PRR_ADD_CLIENT_TO_AKAMAI_PROPERTY",
                "WORKBENCH_CLIENT_UPDATE_STG",
                "WORKBENCH_CLIENT_UPDATE_PROD",
                "SWAT_STAGING_KEY_GENERATION_STEP",
                "STAGING_KEY_GENERATION_STEP",
                "SWAT_PROD_KEY_GENERATION_STEP",
                "PROD_KEY_GENERATION_STEP",
                "CONVAPI_PROVISIONING_STEP",
                "CONVAPI_VERIFICATION_STEP",
                "DIMSUM_SETUP",
                "PRR_DIMSUM_SETUP",
                "EXTENDED_NETWORK_SETUP",
                "SERVICE_LEVEL_TEMPLATE_STEP",
                "CUSTOMER_SERVICE_URL_STEP",
                "EMAIL_TEMPLATE_INMAIL_STEP",
                "PRODUCT_SAMPLING_STEP",
                "AGREEMENTS_STEP",
                "RR_DATA_GENERATION_STEP",
                "AA_DATA_GENERATION_STEP",
                "PROVISION_PRODUCTION_FTP",
                "PROVISION_STAGING_FTP",
                "SALESFORCE_BV_SITE",
                "UPDATE_WORKBENCH",
                "SALESFORCE_SYNDICATION_UPDATE",
                "SALESFORCE_SERVICE_CONTRACT_UPDATE",
                "MODERATION_GUIDELINES_SETUP",
                "USER_MANAGEMENT_STEP",
                "PRR_JIRA_STEP",
                "DATA_TEAM_MANUAL_STEP"
            ]
        },
        "jiraTicket": {
            "type": "string"
        },
        "errors": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "featureFlags": {
            "type": "object"
        },
        "companyName": {
            "type": "string"
        },
        "streetAddress": {
            "type": "string"
        },
        "postalZipCode": {
            "type": "string"
        },
        "country": {
            "type": "string"
        },
        "emailSenderFromName": {
            "type": "string"
        },
        "emailServiceProvider": {
            "type": "string",
            "enum": [
                "AMAZON_SES",
                "EXACT_TARGET"
            ]
        },
        "billingID": {
            "type": "string"
        },
        "salesforceID": {
            "type": "string"
        },
        "clientVertical": {
            "type": "string"
        },
        "maxSpotlights": {
            "type": "string"
        },
        "domains": {
            "type": "array"
        },
        "prrDomain": {
            "type": "string"
        },
        "prrSFTPUsername": {
            "type": "string"
        },
        "prrSFTPPassword": {
            "type": "string"
        },
        "prrBvApiHostName": {
            "type": "string"
        },
        "requester": {
            "type": "string"
        },
        "status": {
            "type": "string",
            "enum": [
                "NEW",
                "CREATED",
                "PROCESSING",
                "COMPLETED",
                "CANCELING",
                "CANCELED",
                "RETRYING",
                "ERROR",
                "MANUAL"
            ]
        },
        "city": {
            "type": "string"
        },
        "state": {
            "type": "string"
        },
        "prrLocale": {
            "type": "string"
        },
        "regionID": {
            "type": "string"
        },
        "id": {
            "type": "string"
        }
    }
}
