### ISSUE TITLE
The use of BasicSerializerFactory.usesStaticTyping in the BeanSerializerFactory looks wrong

### ISSUE THREAD

**Issue by k163377** [FasterXML/jackson-databind#4077]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

`BasicSerializerFactory.usesStaticTyping` returns `false` if the `TypeSerializer` parameter is `null`.

https://github.com/FasterXML/jackson-databind/blob/7d112ec1d74fd50c2ea5a71345e0dedf6e8704a9/src/main/java/com/fasterxml/jackson/databind/ser/BasicSerializerFactory.java#L1312-L1318

On the other hand, `BeanSerializerFactory`, the only module that uses this method, inputs `null` for this argument in all places where it is used.
https://github.com/FasterXML/jackson-databind/blob/7d112ec1d74fd50c2ea5a71345e0dedf6e8704a9/src/main/java/com/fasterxml/jackson/databind/ser/BeanSerializerFactory.java#L202
https://github.com/FasterXML/jackson-databind/blob/7d112ec1d74fd50c2ea5a71345e0dedf6e8704a9/src/main/java/com/fasterxml/jackson/databind/ser/BeanSerializerFactory.java#L615

### Version Information

At least 2.16 branche

### Expected behavior

I don't know what this code was intended to do, but it appears to be skipping some decision by mistake.
Also, if it is an unnecessary decision, I think the call should be removed.

**Comment by cowtowncoder** [comment]
One clarification: it returns `false` if `typeSer` is NOT null. So this is unnecessary check (never matches), but does not skip any processing.

I think the original intent was as comment suggests: avoid assuming static typing for polymorphic types.
But no call path comes in with `TypeSerializer` as non-null at this point -- perhaps at some earlier point something did... but no longer.

I'll have to think about this, but probably want to eliminate unnecessary parameter, check.
