### ISSUE TITLE
2.15.0 breaking behavior change X509Certificate serialization work with 2.13.5 but failing with 2.15.0-rc1

### ISSUE THREAD

**Issue by softwesy** [FasterXML/jackson-databind#4084]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

After upgrading to latest version of jackson i.e. 2.15.0-rc1, serialization of X509Certificate is failing with error whereas same is working with 2.13.5

Getting following error:

Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class sun.security.util.ObjectIdentifier and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: CertChainValidation["chain"]->java.util.ArrayList[0]->CertificateChain["certificate"]->sun.security.x509.X509CertImpl["publicKey"]->sun.security.rsa.RSAPublicKeyImpl["algorithmId"]->sun.security.x509.AlgorithmId["oid"])

We are getting following error from our internal application:
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class java.util.Vector$1 and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.softwareag.tn.cloud.common.model.profile.CertChainValidation["chain"]>java.util.ArrayList[0]>com.softwareag.tn.cloud.common.model.profile.CertificateChain["certificate"]->sun.security.x509.X509CertImpl["elements"])

I know we can fix by disabling the SerializationFeature.FAIL_ON_EMPTY_BEANS but we want to retain the old behavior. Any pointer on retaining the old behavior will be appreciated. 

### Version Information

2.15.0-rc1

### Reproduction

<-- Any of the following
1. I have attached the repo IntelliJ Idea project,
2. To run the Main class change the libs added from libs_working to libs_failing in classpath(Library)
 -->
```java
// Your code here
``` 
[JacksonTest.zip](https://github.com/FasterXML/jackson-databind/files/12379030/JacksonTest.zip)

**Comment by cowtowncoder** [comment]
Uhh? Why would you be using a RELEASE CANDIDATE version?

Try to reproduce this with 2.15.2 first.

**Comment by softwesy** [comment]
this issue is related to https://github.com/FasterXML/jackson-databind/issues/3948, hence closing now
