### ISSUE TITLE
Support multiples views at the same time

### ISSUE THREAD

**Issue by joca-bt** [FasterXML/jackson-databind#4094]
Our DTOs might have disjoint views and we need to serialize with several at the same time.

```
class Dto {
   @JsonView(View1.class)
   String aField;
   @JsonView(View2.class) // extends View1
   String anotherField;
   @JsonView(View3.class) // disjoint (doesn't extend 1 or 2)
   String yetAnotherField;
}
```

For example, we might need to serialize with View1 and View3 at the same time.

Would it be possible to allow ObjectMapper/(De)SerializationConfig to support multiple views?

**Comment by yawkat** [comment]
couldnt you create a new View4 interface that extends both View1 and View3?

**Comment by joca-bt** [comment]
That would work for this _limited_ example if I would set the view on the ObjectMapper to View4 (even though View4 is never declared in any field).

For example, consider you have multiple API versions and you want to return fields depending on the API version. You have 4 views.
- V1 -> only return this field for API version 1
- V2 -> only return this field for API version 2
- V1Plus -> return this field for API version 1 and all posterior versions
- V2Plus -> return this field for API version 2 and all posterior versions

```
class Dto {
   @JsonView(V1)
   String v1;
   @JsonView(V2)
   String v2;
   @JsonView(V1Plus)
   String v1plus;
   @JsonView(V2Plus)
   String v2plus;
}
```

When serializing for API version 1 I should get `v1` and `v1plus`. When serializing for API version 2 I should get `v2`, `v1plus`, and `v2plus`.

**Comment by joca-bt** [comment]
I was able to implement this the way you suggested.

Feel free to close the ticket if you don't feel the request makes sense.

**Comment by cowtowncoder** [comment]
Due to sheer complexity of trying to support multiple views at same time, I think I'll just close this as I do not think that will be supported, ever.
