### ISSUE TITLE
After Jackson databind 2.15.2 upgrade we are facing issues

### ISSUE THREAD

**Issue by vindhyahegde31** [FasterXML/jackson-databind#4125]
### Describe your Issue

Recently we upgraded jackson-datanind from 2.14.2 to 2.15.2 and it Started breaking our Jenkins build which is related to Android.
In the console we are getting error message like,
```
FAILURE: Build failed with an exception.
11:50:32  
11:50:32  * What went wrong:
11:50:32  Execution failed for task ':app:mergeDebugJavaResource'.
11:50:32  > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
11:50:32     > Failed to transform expression-evaluator-client.jar to match attributes {artifactType=android-java-res, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
11:50:32        > Execution failed for JetifyTransform:
```
Currently we are stuck at this not able to figure out this issue
buildToolsVersion "29.0.2"
kotlin_version='1.6.10'

Can please anyone suggest and help us with resolving this issue

Thanks in advance,

**Comment by yawkat** [comment]
this is not enough to go on

**Comment by vindhyahegde31** [comment]
@yawkat  Thanks for the response. I have copied the block of log where the execution is starting. 
Is this helpful? 
 
 ============================= Running Android Test Gradle Command =============================
  [Pipeline] sh
  + docker exec -u appian android-build bash -c 'cd expression-evaluator/expression-evaluator-client/android-test;                           ./gradlew firebaseBuild'
  Starting a Gradle Daemon (subsequent builds will be faster)
  > Task :app:preBuild UP-TO-DATE
  > Task :app:preDebugBuild UP-TO-DATE
  > Task :app:compileDebugAidl NO-SOURCE
  > Task :app:compileDebugRenderscript NO-SOURCE
  > Task :app:generateDebugBuildConfig
  > Task :app:javaPreCompileDebug
  > Task :app:checkDebugAarMetadata
  > Task :app:generateDebugResValues
  > Task :app:generateDebugResources
  > Task :app:createDebugCompatibleScreenManifests
  > Task :app:extractDeepLinksDebug
  > Task :app:mergeDebugResources
  > Task :app:processDebugMainManifest
  > Task :app:processDebugManifest
  > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
  > Task :app:mergeDebugShaders
  > Task :app:compileDebugShaders NO-SOURCE
  > Task :app:generateDebugAssets UP-TO-DATE
  > Task :app:mergeDebugAssets
  > Task :app:processDebugJavaRes NO-SOURCE
  > Task :app:compressDebugAssets
  > Task :app:mergeDebugJavaResource FAILED
  > Task :app:processDebugManifestForPackage
  
  FAILURE: Build failed with an exception.
  
  * What went wrong:
  Execution failed for task ':app:mergeDebugJavaResource'.
  > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
     > Failed to transform expression-evaluator-client.jar to match attributes {artifactType=android-java-res, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
        > Execution failed for JetifyTransform: /home/appian/appian-libraries/expression-evaluator/expression-evaluator-client/android-test/app/libs/expression-evaluator-client.jar.
           > Failed to transform '/home/appian/appian-libraries/expression-evaluator/expression-evaluator-client/android-test/app/libs/expression-evaluator-client.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 61. (Run with --stacktrace for more details.)
             Suggestions:
              - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
              - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).
  
  * Try:
  > Run with --stacktrace option to get the stack trace.
  > Run with --info or --debug option to get more log output.
  > Run with --scan to get full insights.

**Comment by yihtserns** [comment]
Honestly, that looks like an issue one asks the company's senior devs for help with... 😬

**Comment by pjfanning** [comment]
@vindhyahegde31 The unpaid volunteers at Jackson are not here to provide debugging servives for your Gradle build issues.

What has your Java version issue got to do with Jackson?

> Failed to transform '/home/appian/appian-libraries/expression-evaluator/expression-evaluator-client/android-test/app/libs/expression-evaluator-client.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 61. (Run with --stacktrace for more details.)
