### ISSUE TITLE
Add test to verify that deserialization of sub type doesn't wrongly use BigDecimal

### ISSUE THREAD

**Issue by richturner** [FasterXML/jackson-databind#4138]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

New issue created from comment in #3251 (which seems related).

Deserializing JSON with floating point numbers will incorrectly use `BigDecimal` instead of `Double` when using sub types (even though `DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS` is `false`).

This bug is fixed in `2.15.2` but is present in the mentioned version (`2.14.3`) but a test should be added to prevent future regression if this fix was not deliberate.

I can also confirm the value of `@JsonTypeInfo#include` does not affect this behaviour.

### Version Information

2.14.3

### Subtype class definition
```
@JsonTypeInfo(property = "type", use = JsonTypeInfo.Id.NAME)
@JsonSubTypes({
    @JsonSubTypes.Type(ValueTest.ValueTest1.class)
})
public class ValueTest {

    @JsonTypeName("valueTest1")
    public static class ValueTest1 extends ValueTest {
        Object[] allowedValues;

        @JsonCreator
        protected ValueTest1() {
        }

        public ValueTest1(Object... allowedValues) {
            this.allowedValues = allowedValues;
        }

        public Object[] getAllowedValues() {
            return allowedValues;
        }
    }
}
```

### JSON string to deserialize
```
JSON.readValue("{\"allowedValues\": [ 1.5, 2.5 ], \"type\": \"valueTest1\"}", ValueTest.class)
```

### Result
Hydrated `ValueTest` instance will have `BigDecimal` objects in the `allowedValues` property.

### Expected behavior

Hydrated `ValueTest` instance should contain `Double` objects unless `DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS` is `true`

**Comment by cowtowncoder** [comment]
Added test based on suggestion; passes for 2.16.0-SNAPSHOT and should guard against regression now.
