### ISSUE TITLE
Change to use `_method#hashCode` directly in `AnnotatedMethod#hashCode`.

### ISSUE THREAD

**Issue by k163377** [FasterXML/jackson-databind#4150]
### Describe your Issue

I found that `AnnotatedMethod#hashCode` returns the hash code of `_method#getName`.
https://github.com/FasterXML/jackson-databind/blob/36ecf8f38dbe3250a4a4f93a70340405c89cf838/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedMethod.java#L248-L251

It seems to increase the probability of collisions, for example using `HashMap` with `AnnotatedMethod` as the key.
How about using `_method#hashCode` instead?
This one seems to have a lower collision rate since it includes the `Class` name information.

```java
    public int hashCode() {
        return getDeclaringClass().getName().hashCode() ^ getName().hashCode();
    }
```

**Comment by k163377** [comment]
I did a little more research and it appears that `AnnotatedField` and `AnnotatedConstructor` have the same implementation.
However, since `Constructor#name` contains the class name, this problem does not seem to occur.

https://github.com/FasterXML/jackson-databind/blob/36ecf8f38dbe3250a4a4f93a70340405c89cf838/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedField.java#L130-L133
https://github.com/FasterXML/jackson-databind/blob/36ecf8f38dbe3250a4a4f93a70340405c89cf838/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedConstructor.java#L178-L181

**Comment by cowtowncoder** [comment]
I am not sure there's a major problem here, however, considering that `Method.equals()` compares `_method`, perhaps `hashCode()` should the same. Same applies to `AnnotatedField` and `AnnotatedConstructor`.

So I'd be happy to merge a PR.
