### ISSUE TITLE
Document Jackson coding style

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#4156]
### Describe your Issue

(note: follow-up to #4151 comment)

We need to document current expectation of Jackson-wide default coding style; probably as a page in wiki of https://github.com/FasterXML/jackson project. This can then be linked to from other repos such as this one.

Things that come to mind are:

1. Indentation: spaces, no tabs, 4 spaces per level
2. Import statement wildcard: can use wildcards, should use wildcards at 5 imports from same package, but may use for lower number (esp. for `java.util`, `java.io`, main Jackson packages like `com.fasterxml.jackson.databind`)
3. Import statement ordering: start with platform (JDK) imports, then Jackson "base" types (annotations, core, databind) -- from "lowest" to highest level
4. Field naming; leading underscore for non-public member fields.
5. Method naming (regular Java style for public methods; use leading underscore for internal methods used by class itself; may use for methods for use by sub-classes but not for methods to call from outside class otherwise)

so nothing super advanced, documenting basically existing practices.

**Comment by yawkat** [comment]
imo there should also be an intellij code style xml somewhere. i assume that's the ide most people use. jetbrains even puts the code style into each repo, but that may be too much for jackson, so having it in a central location would be enough.

Example: https://github.com/JetBrains/intellij-community/blob/master/.idea/codeStyles/Project.xml

**Comment by JooHyukKim** [comment]
> imo there should also be an intellij code style xml somewhere

👍🏼 Would be quite helpful, but we may need to consider Eclipse users. I recall @cowtowncoder uses Eclipse also? I think what Tatu uses matters, since he makes most changes. 

Luckily, there seems to be some type of adaptor for [Eclipse-to-IntelliJ code format style plugin ](https://plugins.jetbrains.com/plugin/6546-adapter-for-eclipse-code-formatter) for Intellij.

**Comment by JooHyukKim** [comment]
> Willing to draft a starting point if needed.

Before adding the actual coding style page, I first tried organizing **the whole Wiki** in **my fork of FasterXML/Jackson**. May I ask for a review, @yawkat @cowtowncoder? If agreed, let's apply these changes upstream.

Then the **Jackson coding style** may be added to the new [Contribution section](https://github.com/JooHyukKim/jackson/wiki/Contribution).

**Comment by cowtowncoder** [comment]
Code styles could be useful in addition, to the degree they can help enforce constraints. Some aspects (like naming) probably need to be simply documented; especially in cases where there are suggestions, not strong guidelines.

**Comment by JooHyukKim** [comment]
> Before adding the actual coding style page, I first tried organizing the whole Wiki in [my fork of FasterXML/Jackson](https://github.com/JooHyukKim/jackson/wiki). May I ask for a review, @yawkat @cowtowncoder? If agreed, let's apply these changes upstream.

Have you made an approval using "👍🏼" here, @cowtowncoder? Just wondering :))

**Comment by cowtowncoder** [comment]
> > Before adding the actual coding style page, I first tried organizing the whole Wiki in [my fork of FasterXML/Jackson](https://github.com/JooHyukKim/jackson/wiki). May I ask for a review, @yawkat @cowtowncoder? If agreed, let's apply these changes upstream.
> 
> Have you made an approval using "👍🏼" here, @cowtowncoder? Just wondering :))

Sorry, was meant as general "thanks!" note. Will have a look now...

**Comment by cowtowncoder** [comment]
@JooHyukKim new Wiki main page seems to be missing many of entries from existing one -- like entries from under "Reference Manual"? I am fine with these being re-organized under different pages to keep entry page clean but I hope they are still available?

**Comment by JooHyukKim** [comment]
> new Wiki main page seems to be missing many of entries from existing one -- like entries from under "Reference Manual"?

I've double-checked and can't find what's missing, 🤔. If you're referring to [this link](https://github.com/JooHyukKim/jackson-docs), it's at the bottom of the main Wiki page.

Regardless, this Wiki re-organization is growing beyond anticipated. Let's halt for now (or move to other issue). I started it aiming for a smooth merge, followed by working on the coding style.

**Comment by cowtowncoder** [comment]
@JooHyukKim Ok sorry, I must have been looking at wrong page or something.

**Comment by JooHyukKim** [comment]
Filed https://github.com/FasterXML/jackson/pull/201 that we can start off somewhere 👍🏼 Let me know what ya'll think

**Comment by cowtowncoder** [comment]
Thank you @JooHyukKim !

**Comment by cowtowncoder** [comment]
Resolved via

https://github.com/FasterXML/jackson/pull/201
