### ISSUE TITLE
TypeWrappedSerializer fails to serialise root objects

### ISSUE THREAD

**Issue by kevinwright** [FasterXML/jackson-databind#4158]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When serialising a root-level object that has custom type info, serialisation fails with
```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
```

### Version Information

2.15.3

### Reproduction

Create an interface (and associated subclasses) annotated with:

```
@JsonTypeInfo(
    use = Id.CUSTOM,
    include = As.EXISTING_PROPERTY,
    property = "recordType",
    visible = true
)
@JsonTypeIdResolver(MyResolver.class)
public interface MyObject {
    MyEnum recordType
    ...
}
```

Where `recordType` is an enum with a distinct value for each possible subclass, and MyResolver specifies the name -> class mappings.

Then attempt to serialise with `ObjectMapper:writeValueAsString`

`myMapper.writeValueAsString(objectInstance)` will fail with `com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value`.  

`mapper.writeValueAsString(Map.of("content", objectInstance))` will succeed.

Unlike `DefaultSerializerProvider`, `TypeWrappedSerializer` does not appear to be correctly calling `gen.writeStartObject()`

### Expected behavior

The object serialises without error.

**Comment by ritikverma2000** [comment]
Hi @kevinwright I would like to work on this issue can guide me with the project setup once.

**Comment by cowtowncoder** [comment]
Cannot reproduce without FULL reproduction -- for example, what does `MyResolver` exactly do? Details matter a lot.

So, a stand-alone reproduction (ideally unit test) would be needed. I don't doubt there could be an issue here but verbal description is unfortunately often not enough to replicate the problem.

**Comment by JooHyukKim** [comment]
FYI, you may refer to the comment https://github.com/FasterXML/jackson-databind/issues/3569#issuecomment-1758062252 PLUS what `MyResolver` does as mentioned above.

**Comment by kevinwright** [comment]
Reproduction in a dedicated project here: https://github.com/kevinwright/jackson-4158

**Comment by kevinwright** [comment]
The problem comes from serialisation, not deserialisation. 

I can read the JSON just fine, it's only in writing it that jackson crashes

**Comment by cowtowncoder** [comment]
@kevinwright I was just commenting on suggestion, I may have misunderstood it. But I did understand that the current symptom ("crash"... exception that is) is due to Type Id writer being called in wrong context, i.e. serialization orchestration flaw.

**Comment by kevinwright** [comment]
The problem is that serialisation to JSON, in the context of `@JsonTypeInfo` and `@JsonTypeIdResolver` fails to correctly call `writeStartObject()`

**Comment by kevinwright** [comment]
I have a workaround that I can use via `@JsonSerialize(using = RawValueSerializer.class)`

```
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.BeanDescription;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializationConfig;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.exc.InvalidDefinitionException;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import com.fasterxml.jackson.databind.ser.BeanSerializer;
import com.fasterxml.jackson.databind.ser.BeanSerializerFactory;
import com.fasterxml.jackson.databind.ser.SerializerFactory;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.fasterxml.jackson.databind.util.ClassUtil;
import java.io.IOException;
import java.lang.reflect.Method;
import java.lang.reflect.Field;
import java.util.concurrent.atomic.AtomicReference;

public class RawValueSerializer<T> extends StdSerializer<T> {
  public RawValueSerializer() {
    this(null);
  }

  public RawValueSerializer(Class<T> t) {
    super(t);
  }

  AtomicReference<JsonSerializer<Object>> rawSerializerRef = new AtomicReference<>(null);

  protected JsonSerializer<Object> mkRawSerializer(SerializerProvider provider, Class<?> rawType)
      throws JsonMappingException
  {
    SerializationConfig config = provider.getConfig();
    JavaType fullType = config.constructType(rawType);
    BeanDescription beanDesc = config.introspect(fullType);
    try {
      Field f = SerializerProvider.class.getDeclaredField("_serializerFactory");
      f.setAccessible(true);
      SerializerFactory fac = (BeanSerializerFactory) f.get(provider);

      Method m = BeanSerializerFactory.class.getDeclaredMethod(
          "_createSerializer2",
          SerializerProvider.class,
          JavaType.class,
          BeanDescription.class,
          boolean.class
      );
      m.setAccessible(true);
      Object serObj = m.invoke(fac, provider, fullType, beanDesc, true);
      BeanSerializer ser = (BeanSerializer) serObj;
      ser.resolve(provider);
      return ser;
    } catch (Exception e) {
      throw InvalidDefinitionException.from(provider.getGenerator(), ClassUtil.exceptionMessage(e), fullType);
    }
  }

  @Override
  public void serialize(
      T value,
      JsonGenerator gen,
      SerializerProvider provider
  ) throws IOException {
    rawSerializerRef.compareAndSet(
        null,
        mkRawSerializer(provider, value.getClass())
    );
    rawSerializerRef.get().serialize(value, gen, provider);
  }

  @Override
  public void serializeWithType(
      T value,
      JsonGenerator gen,
      SerializerProvider provider,
      TypeSerializer typeSer
  ) throws IOException {
    serialize(value, gen, provider);
  }
}
```
But with reflection and having to fight the caching mechanism every step of the way it's far from pretty

**Comment by cowtowncoder** [comment]
Ok. So, while technically there is a reproduction is has one issue wrt inclusion: it uses Lombok.
Lombok is unfortunately a blocker both for inclusion as a test (I do not accept Lombok dependency for anything in Jackson, partly since it is intrusive and requires configuration of IDE to work) and for investigation.
I'd basically need a resolved version of classes (result of Lombok's source/bytecode processing).
Otherwise reproduction looks reasonable wrt size.

**Comment by cowtowncoder** [comment]
On reproduction: I think `DiscriminatorResolver` looks wrong wrt lack of implementation of `idFromValue` and `idFromValueAndType` methods -- these would be needed for obtaining Type Id to use for serialization.

**Comment by JooHyukKim** [comment]
Phew, took a while to write a reproduction and solution #4198.
There was no bug, but missing pieces in reproduction that are....

1. `idFromValueAndType()` should be implemented, as per @cowtowncoder 
2. Understand the nature of `JsonTypeInfo.As.EXISTING_PROPERTY`. Explained further in detail below.

> Inclusion mechanism similar to PROPERTY with respect to deserialization; but one that is produced by a "regular" accessible property during serialization. This means that TypeSerializer will do nothing, and expects a property with defined name to be output using some other mechanism (like default POJO property serialization, or custom serializer).

According to the [documentation (JavaDoc)](https://github.com/FasterXML/jackson-annotations/blob/4fabac8c9d06a6fb09544ad2ee86e882914d03b5/src/main/java/com/fasterxml/jackson/annotation/JsonTypeInfo.java#L237), with `JsonTypeInfo.As.EXISTING_PROPERTY` configured, nothing happens during serialization. It assumes that the container bean already has a property with name "discriminator". So what you should do is either pass `Discriminator.STRING` or `INT` to the builder, or set default value of `Discriminator` in builder.

**Comment by cowtowncoder** [comment]
Thank you @JooHyukKim for doing the detective work here. Your explanation sounds correct.
And yes, I should have picked up on `EXISTING_PROPERTY`: `TypeSerializer` should indeed only write start/end-markers, but no property. Although in this case standard `TypeSerializer` was used, not customized one so not 100% sure what went wrong (combination of information from `@JsonTypeInfo`?)

**Comment by JooHyukKim** [comment]
> Although in this case standard TypeSerializer was used, not customized one so not 100% sure what went wrong (combination of information from @JsonTypeInfo?)

Good question, it may have to do with getter method and type property name both being present. 

Do you think it is worth investigating, @cowtowncoder? If so, I will try to s ee what the problem is exactly. Maybe there is something we can improve on. 

After writing this, I think we have something to improve on especially the error message
