### ISSUE TITLE
Deprecate `DefaultTyping.EVERYTHING` in `2.x` and remove in `3.0`

### ISSUE THREAD

**Issue by JooHyukKim** [FasterXML/jackson-databind#4160]
### Is your feature request related to a problem? Please describe.

As per JavaDoc of `ObjectMapper.DefaultTyping.EVERYTHING` itself, users are better off without it, even though was initally created off a feature request. So I propose that we remove it progressively.

### Describe the solution you'd like

1. Deprecate in `2.x`, then
2. remove in `3.0`

**Comment by timnick-snow** [comment]
When is 3.0 planned to be released ?

**Comment by JooHyukKim** [comment]
> When is 3.0 planned to be released ?

Please ask over at https://github.com/FasterXML/jackson/discussions, unless the question is related to the issue in which case we need more detail. 👍🏼

**Comment by cowtowncoder** [comment]
@timnick-snow It being a major new version, sometime after 2.17 gets ready I would hope. It has been going on along side for years now, unfortunately. No firm date/plan -- my hope is to rewrite property introspection logic in 2.x and then move on to focus on 3.0.
