### ISSUE TITLE
Default branch change impedes forking and submitting requests.

### ISSUE THREAD

**Issue by garretwilson** [FasterXML/jackson-databind#4167]
### Describe your Issue

I just cloned the repository in order to start submitting pull requests, e.g. #4165. The build is breaking with `ObjectMapperTest.testCopyWith()`. I was going to file a bug for that, but then I noticed what got forked was the `2.16` branch. I looked more closely, and apparently this is set to the default branch, not `master`.

I understand cutting branches for releases. I don't know why that branch was set to the default, though. Now I'm not sure if I should be filing bugs against the `2.16` branch or ignoring them. I'll go check to see if `master` builds, but first I'll have to go research to find out how to get that branch into my fork, or redo the fork.

Was it inadvertent that the default branch got changed from `master`, and is there a reason for it? The only purpose I could think of is that you have some automatic build process verifying and building that branch, but if that process requires changes the default branch, it would seem less than idea. In any case changing the default branch impedes someone jumping in and doing work on the repository.

**Comment by garretwilson** [comment]
OK, part of that was my fault for not reading the readme closely. It says:

> `master` branch is for developing the next major Jackson version -- 3.0 …
> `2.16` is the branch for "next" minor version to release (as of July 2023)

So it seems that `2.16` really should be the default branch, because normal development is being done on a version branch, while `master` is used for the next big change some time in the future.

Fair enough—it's just a name, anyway. But if v3.0 is really a long ways off, then it might be less unexpected to have normal development done on `master` and relegate v3.0 development to a branch until it's ready to release from the oven.

I'll close this ticket as invalid, and then go file a bug for the `2.16` branch.

**Comment by JooHyukKim** [comment]
You are right that there is reason, though I cannot explain in case I convey wrong message 😅.

Anyway, the `master` branch is reserved for the in-development `Jackson 3.0` version. The default branch represents the latest stable `2.x` version, which is `2.16` currently.

Also, there is link to contribution guide in `README.md` saying...

> See [CONTRIBUTING](https://github.com/FasterXML/jackson/blob/master/CONTRIBUTING.md) for details on things like:

... this, which kind of serves as project introduction --I think this would apply to all projects (not only Jackson). Though putting in work would be welcome, I personally think that trying to understand the context of project first would ease the workload on already existing ones, like explaining the

**Comment by garretwilson** [comment]
> See [CONTRIBUTING](https://github.com/FasterXML/jackson/blob/master/CONTRIBUTING.md) for details …

Thanks for pointing that at. I'll go read it. Now I see there are agreements to sign and such. 😒

**Comment by JooHyukKim** [comment]
> Now I see there are agreements to sign and such. 😒

There is, but quite simple :)  --unless complexity is not the concern here 😅

**Comment by JooHyukKim** [comment]
You can work on the PR first then just before merging will be asked. But I recall agreements are NOT all contributions require CLAs.

**Comment by garretwilson** [comment]
> There is, but quite simple :) --unless complexity is not the concern here

It was just that my plan was to set aside time to wake up and quickly knock off some tickets for contributing to Jackson and ClassMate. The "quickly" part of the plan is now out the window. 😅 No worries—once it's done it will be out of the way.

**Comment by garretwilson** [comment]
So the [latest release](https://central.sonatype.com/artifact/com.fasterxml.jackson.core/jackson-databind/versions) is `2.16.0-rc1`. Should I then file improvements such as #4165 against the `2.16` branch?

As I noted earlier, the `2.16` branch is broken. So I'll have to file and/or fix a big on it before even working on other tickets. (I don't like to submit tickets when the build is breaking.)

**Comment by cowtowncoder** [comment]
It's all good in the end I hope.

Yes, `master` is for 3.0 for what are now historical reasons; I had hoped we'd have switched a while ago.
But yes, `2.16` (and in near future `2.17`) is what would be mainline for other projects.

CLA is needed in general, but not necessary for documentation/wiki/test changes -- it's mandatory for changes to code that is released (non-test code).
(in theory we wouldn't really need CLA for trivial changes either, but it is simpler to just get one for all production code changes)
