### ISSUE TITLE
Exception when deserialization of `private` record with default constructor

### ISSUE THREAD

**Issue by janpachol** [FasterXML/jackson-databind#4175]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When deserializing a record, jackson fails with
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of ... (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```
It looks like jackson does not see default constructor.

### Version Information

2.16.0-rc1

### Reproduction

```java
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class TestObjectTest {

    @Test
    public void shouldDeserialize() throws JsonProcessingException {
        TestObject testObject = new ObjectMapper().readValue("{\"text\":\"anything\"}", TestObject.class);
        Assertions.assertEquals("anything", testObject.text());
    }

    private record TestObject(String text) {}
}
```

When I add compact constructor with `@JsonCreator` to TestObject, it works correctly:

```java
    private record TestObject(String text) {
        @JsonCreator
        private TestObject {
        }
    }
```

### Additional context

- It works correctly in version 2.15.3
- tested on java 21
- May be related to https://github.com/FasterXML/jackson-databind/issues/4119

**Comment by pjfanning** [comment]
@janpachol we have tests with records like this. I think that this is most likely down to the record being `private` as opposed to the fact that jackson can't handle `public record TestObject(String text) {}`.

**Comment by pjfanning** [comment]
I created https://github.com/FasterXML/jackson-databind/pull/4176 as a reproducible test case.

**Comment by janpachol** [comment]
Oh, you're correct, but it looks problem is not in private record, but in private constructor (when record is private, it looks that compilation creates also private constructor):

This doesn't work:
```java
    public record TestObject(String text) {
        private TestObject {
        }
    }
```
This works:
```java
    private record TestObject(String text) {
        public TestObject {
        }
    }
```

**Comment by cowtowncoder** [comment]
Yes, it makes sense the issue is `private` constructor via Record being `private` (in the original case).
Given it is regression from 2.15, would be great to fix.

**Comment by JooHyukKim** [comment]
Created a PR for #4178. The issue seems to link back to the fix for #3906 via https://github.com/FasterXML/jackson-databind/commit/75d0c46a4a773d1852ae2305cba9231d465940fc where sort of force setting of record constructor visibility.

**Comment by cowtowncoder** [comment]
Cool. While I have am bit concerned about change causing some other regression, there isn't much that can be done without reproduction of such problem.

**Comment by JooHyukKim** [comment]
> Cool. While I have am bit concerned about change causing some other regression, there isn't much that can be done without reproduction of such problem.

Wrt regression, we may already have some tests against regression via https://github.com/FasterXML/jackson-databind/commit/228bc0ef4a59dd47422603a59812768153ddd1c8
