### ISSUE TITLE
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_ENUMS = true Spring Boot Issue

### ISSUE THREAD

**Issue by joelwilson005** [FasterXML/jackson-databind#4187]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_ENUMS = true, enum fields are being serialized and deserialized as objects and not strings. 

### Version Information

Maven: com.fasterxml.jackson.core:jackson-databind:2.15.3 (jackson-databind-2.15.3.jar)

### Reproduction

<-- Any of the following
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here
 -->
```java
// Your code here
``` 

### Expected behavior

Enums should  be serialized and deserialized as strings when that field is set to true.

**Comment by pjfanning** [comment]
We generally only accept Jackson only issues. This issue appears to involve Spring Boot. You should ideally raise an issue with Spring Boot first.

**Comment by mukham12** [comment]
@joelwilson005,

Please consider creating a PR with a failing test case to help us identify the issue. Alternatively, a minimal reproducible example would also be useful.

**Comment by cowtowncoder** [comment]
Definitely needs a Jackson-depedency-only reproduction to be able to help. Hopefully one is added, otherwise will close in near future, given there is a reasonable chance this could be just related to configurability of Spring.

**Comment by mukham12** [comment]
I played with this but could not replicate it. Considering the OP has been inactive for a while, I believe it's appropriate to conclude that this can be closed. We could reopen if necessary, with a reproduction test case using Jackson only.

**Comment by cowtowncoder** [comment]
Thank you @mukham12. Closing; can be re-opened if issue becomes reproducible.
