### ISSUE TITLE
Duplicate serialization with variables that start with a single letter 

### ISSUE THREAD

**Issue by southeo** [FasterXML/jackson-databind#4197]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When serializing a field that starts with a single letter (e.g. "xVal") which is annotated by the @JsonProperty("fieldName") annotation, the field is serialized twice when a standard getter is provided. 
It seems Jackson is expecting a getter with the first character in lowercase (e.g. getxVal), which is not in-line with standard getters, e.g. from lombok, which would have the first character of the  getXVal(). 

### Version Information

2.15.2

### Reproduction

Further demonstration in [github repo](https://github.com/southeo/jackson_issue)

Given the following POJO: 

```java
public class UppercaseGetter {
    @JsonProperty("ac:xFrac")
    private Double xVal;

    public Double getXVal(){
        return xVal;
    }
}
``` 

the operation `mapper.valueToTree(new UppercaseGetter(0.1)` will produce the following JsonNode, where the field "xval" is serialzed twice. 

```json

{
  "xval" : 0.1,
  "ac:xFrac" : 0.1
}

``` 

However, a Pojo with a lowercase getter will produce a correct serialization:

```java
public class LowercaseGetter {

    @JsonProperty("ac:xFrac")
    private Double xVal;

    public Double getxVal(){
        return xVal;
    }
}
```

```json

{
  "ac:xFrac" : 0.1
}

``` 

### Additional context

Uppercase getters are more aligned with Java conventions and with what Lombok produces.

**Comment by JooHyukKim** [comment]
Difficult call. The naming convention is already quite settled down. Plus Jackson mostly follows naming convention. Could you provide link/url to the mentioned Java convention? 

Meanwhile, I found some discussion you may refer to?

- https://stackoverflow.com/questions/30205006/why-does-jackson-2-not-recognize-the-first-capital-letter-if-the-leading-camel-c
- https://futuretask.blogspot.com/2005/01/java-tip-6-dont-capitalize-first-two.html

**Comment by southeo** [comment]
Looks like my issue is elsewhere then, good point :+1:
