### ISSUE TITLE
Issue with Avro generated classes: camelCase and snake_case combo in one class causes UnrecognizedPropertyException

### ISSUE THREAD

**Issue by fcpunk** [FasterXML/jackson-databind#4203]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

By the look of it starting from v2.12 something changed in ObjectMapper implementation and the code below stopped working:
```
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Sample {
	private String snake_case;
	private String camelCase;

	public String getSnakeCase() {
		return snake_case;
	}

	public void setSnakeCase(String snake_case) {
		this.snake_case = snake_case;
	}	
	
	public String getCamelCase() {
		return camelCase;
	}
	
	public void setCamelCase(String camelCase) {
		this.camelCase = camelCase;
	}
	
	@org.junit.jupiter.api.Test
	public void test() throws JsonProcessingException {
		ObjectMapper objectMapper = new ObjectMapper();
		objectMapper.readValue("{\"snake_case\": \"sample data 1\",\"camelCase\":\"sample data 2\"}", Test.class);
	}
	
}
```

MixIn and annotations are not an option for generated classes. This is just a simple example, in my case class has hundreds of fields and is generated from an Avro schema. I have no control over generation of the getters/setters which confuses Jackson.

Implementing a custom PropertyNamingStrategy doesn't work here because getters/setters don't match field names.

### Version Information

2.12+
2.15.3

### Reproduction

```
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Sample {
	private String snake_case;
	private String camelCase;

	public String getSnakeCase() {
		return snake_case;
	}

	public void setSnakeCase(String snake_case) {
		this.snake_case = snake_case;
	}	
	
	public String getCamelCase() {
		return camelCase;
	}
	
	public void setCamelCase(String camelCase) {
		this.camelCase = camelCase;
	}
	
	@org.junit.jupiter.api.Test
	public void test() throws JsonProcessingException {
		ObjectMapper objectMapper = new ObjectMapper();
		objectMapper.readValue("{\"snake_case\": \"sample data 1\",\"camelCase\":\"sample data 2\"}", Test.class);
	}
	
}
```

### Expected behavior

This code sample should work with default ObjectMapper settings.

**Comment by yawkat** [comment]
Not sure what we can do about this. Sounds more like the generator should be fixed, e.g. by emitting explicit property name annotations.

**Comment by fcpunk** [comment]
Unfortunately it can't. There's no such option in avro-maven-plugin. 

If it won't be fixed, could you suggest a workaround?

**Comment by fcpunk** [comment]
It turns out the latest avro-maven-plugin switched default access type for fields from public to private. Changing it back to public did the trick. It's not a Jackson bug, my bad.

**Comment by cowtowncoder** [comment]
@fcpunk Thank you for quick follow up and updating this issue. Better safe than sorry.
