### ISSUE TITLE
Make `BeanDeserializerModifier`/`BeanSerializerModifier` implement `java.io.Serializable`

### ISSUE THREAD

**Issue by k163377** [FasterXML/jackson-databind#4209]
### Is your feature request related to a problem? Please describe.

The `BeanDeserializerModifier` does not currently implement `Serializable`.
https://github.com/FasterXML/jackson-databind/blob/5be890cc11c3e763d4044f15471fbad3cc7f4501/src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializerModifier.java#L48

On the other hand, this class is used as a field in `SimpleModule` which implements `Serializable`.
This means that if a simple implementation of `BeanDeserializerModifier` is used in a `SimpleModule`, the `JDK` serialization may cause unintended errors.
https://github.com/FasterXML/jackson-databind/blob/5be890cc11c3e763d4044f15471fbad3cc7f4501/src/main/java/com/fasterxml/jackson/databind/module/SimpleModule.java#L94

### Describe the solution you'd like

Either have `BeanDeserializerModifier` implement `Serializable` or provide a base class like `SimpleBeanDeserializerModifier` that implements `Serializable` as well as other supporting classes.

**Comment by cowtowncoder** [comment]
Hmmh. Interesting. Yes, at least for Jackson 2.x this would make sense. Same wrt `BeanSerializerModifier`.

**Comment by mukham12** [comment]
@cowtowncoder,

To ensure clarity, is the solution as straightforward as incorporating `implements Serializable` into the `BeanSerializerModifier` class? If that's the case, I could submit a PR.
