### ISSUE TITLE
Custom deserializer via @JsonDeserialize should be invoked before NULL-checking

### ISSUE THREAD

**Issue by MartinHaeusler** [FasterXML/jackson-databind#4225]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-module-kotlin/issues) and found nothing similar.

### Describe the bug

When specifying a custom deserializer via `@JsonDeserialize`, the deserializer should be invoked **before** the value is checked for `null`. It is entirely possible that the custom deserializer produces a non-`null` object out of a JSON `null` value. Currently this doesn't seem to be possible.

### To Reproduce

```kotlin
class MyClass(
    @JsonDeserialize(using = CustomListDeserializer::class)
    val myList: List<String>
)

// the following is a minimal implementation to demonstrate the point;
// for the sake of argument, assume that the deserializer contains further complex custom logic.
class CustomListDeserializer : JsonDeserializer<List<String>>() {

    override fun deserialize(p: JsonParser, ctxt: DeserializationContext): List<Any> {

        val jsonToken = p.currentToken

        return when (jsonToken) {
            JsonToken.VALUE_NULL -> {
                emptyList()
            }
            JsonToken.VALUE_STRING -> {
                listOf(p.valueAsString)
            }
            else -> {
                throw JsonParseException(p, "Failed to parse value!")
            }
        }
    }

}
```

... and try to deserialize the following JSON:

```json
{
    "myList": null
}
```

This will result in a `MissingKotlinParameterException`, claiming that: `value failed for JSON property myList due to missing (therefore NULL) value for creator parameter myList which is a non-nullable type`

### Expected behavior

I would expect that the JSON is deserialized by invoking the `CustomListDeserializer` on the JSON `null` value, producing an empty list. This empty list should then be handed to the primary constructor of `MyClass`.

### Versions

Kotlin: 1.9.20
Jackson-module-kotlin:  2.15.3
Jackson-databind: 2.15.3

**Comment by cowtowncoder** [comment]
(note: moved from `jackson-module-kotlin`, hence Kotlin reproduction)

So, no this is not quite correct: in Jackson deserializers are NOT asked to deserialize from `null` (`JsonToken.VALUE_NULL`) -- original intent being to avoid every deserializer from having to do null-handling. Whether this is a good or bad decision at this point is another question but it is fairly fundamental limitation.

Deserializers are, however, asked to produce `null value` (later addition to try to support ability for deserializers to influence handling of `null`s) by calling this method:

```
   public T getNullValue(DeserializationContext ctxt) throws JsonMappingException;
```

so it should be possible to implement this method and produce appropriate null replacement by custom deserializer. One downside is that no contextual information is passed regarding parsing state (`JsonParser` not passed). It is also possible that this method is only called once and not every time `null` is encountered (I don't remember if caching is done or not).

But it should be sufficient for this use case. I would expect Kotlin module to call this method as well.

**Comment by cowtowncoder** [comment]
As per my comment, `JsonDeserializer`s' deserialization methods are not called for `null` tokens; there are separate accessors (`getNullValue()` and `getNullAccessPattern()`). Closing.
