### ISSUE TITLE
Class com.fasterxml.jackson.annotation.SimpleObjectIdResolver has no default (no arg) constructor

### ISSUE THREAD

**Issue by architp1112** [FasterXML/jackson-databind#4269]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

I'm getting error in deserialize JSON content from given JSON content String.
It's working with Build apk but not working in signed apk.
Current code had been working in AGP 4.0.2 but after updating it to 8.2.0,it is not working and throwing an error.

I'm using below dependencies:

implementation 'com.fasterxml.jackson.core:jackson-core:2.12.5'
implementation 'com.fasterxml.jackson.core:jackson-annotations:2.12.5'
implementation 'com.fasterxml.jackson.core:jackson-databind:2.12.5'

### Version Information

Current Version: 2.12.5

### Reproduction

Code: 

String mapdata = readMapFile(); //this function returns string of json file.
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.enable(DeserializationFeature.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT);
objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
MapGraph mapGraph = objectMapper.readValue(mapdata, MapGraph.class);

### Expected behavior

Should be work with signed apk

**Comment by pjfanning** [comment]
Could you do this on stackoverflow? The AGP/APK questions have no relation to Jackson.

**Comment by architp1112** [comment]
> Could you do this on stackoverflow? The AGP/APK questions have no relation to Jackson.

No. I haven't

**Comment by pjfanning** [comment]
> > Could you do this on stackoverflow? The AGP/APK questions have no relation to Jackson.
> 
> No. I haven't. I think bug is related to Proguard-rules for this library. Need to add rules for that.

Please read https://github.com/FasterXML/jackson-databind/issues/1504

Closing.

**Comment by cowtowncoder** [comment]
Also: usage questions probably better asked on mailing lists:

https://groups.google.com/g/jackson-user

although I guess one could have an issue asking for having and documenting standard ProGuard definitions for project. Would require user contribution, probably, but not unreasonable thing to ask for.
Although this specific ask may be bit too specific?

**Comment by architp1112** [comment]
> > > Could you do this on stackoverflow? The AGP/APK questions have no relation to Jackson.
> > 
> > 
> > No. I haven't. I think bug is related to Proguard-rules for this library. Need to add rules for that.
> 
> Please read #1504
> 
> Closing.



> > > Could you do this on stackoverflow? The AGP/APK questions have no relation to Jackson.
> > 
> > 
> > No. I haven't. I think bug is related to Proguard-rules for this library. Need to add rules for that.
> 
> Please read #1504
> 
> Closing.

not found anything relevant and also tried to add rules as mentioned in comments; None of working,
