### ISSUE TITLE
On deserialization using `Creator` with vargs style argument (`String...`)

### ISSUE THREAD

**Issue by k163377** [FasterXML/jackson-databind#4270]
### Describe your Issue

Executing the following code will cause a `NullPointerException` at `Arrays.asList(args)`.

```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.List;

public class VarargTest {
    static class Dto {
        private final List<String> args;

        @JsonCreator
        Dto(@JsonProperty(value = "args") String... args) {
            this.args = Arrays.asList(args);
        }
    }

    @Test
    void test() throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();
        Dto dto = mapper.readValue("{}", Dto.class);
    }
}
```

Personally, I found it counter-intuitive that `null` would be entered for `VarArgs` when the input was `undefined`.
I feel that an empty array should be passed to `vararg` when it is called from `Java` with no arguments.

Is this behavior a basic policy of `Jackson`?
If it is for consistency of interconversion, I can understand this behavior.

As far as my search, I could only find the following
https://github.com/FasterXML/jackson-databind/pull/1434

**Comment by cowtowncoder** [comment]
There is no special handling for varargs case; I am not sure what it looks like at bytecode level -- probably nominal type of `String[]`? But since some value is required for this constructor, and nothing is passed, `null` is the default choice.

So I think this makes sense wrt "why/how is this working this way".

I am also not sure if this should be changed: I'm tempted to say it works the way it should.

**Comment by k163377** [comment]
I have no strong opinion on the use of `null`, at least in `databind`.

On the other hand, in `Kotlin`, it is not possible to set `null` for a `vararg` argument (this is the background of my question).
I was going to modify the `kotlin-module` to use an empty array if the input to the `vararg` argument is `missing`.
I wanted to know if this fix should be done for `databind` or not.

Thank you for your answer, this issue is closed.

**Comment by cowtowncoder** [comment]
@k163377 Ok.
