### ISSUE TITLE
JsonPointer for annotation JsonProperty

### ISSUE THREAD

**Issue by long76** [FasterXML/jackson-databind#4285]
### Is your feature request related to a problem? Please describe.

i need parse multilevel json like
```json
{
   "user": {
      "name": {
          "first": "Test"
      }
   }
   "adress": {
      "street": {
          "name": "Street name"
      }
   }
}
```
now for use it in databind i need create a lot of classes or use `readTree` with method `at` every time

### Describe the solution you'd like

use annotation `@JsonProperty`, like `@JsonProperty(value = "/user/name/first", isJsonPointer = true)`, then we can use it in databind without useless classes without many getters

### Usage example

```java
public class User {
    @JsonProperty(value = "/user/name/first", isJsonPointer = true)
    private String firstName;

    public String getFirstName() {
        return firstName;
    }
}
```
```json
{
    "user": {
        "name": {
            "first": "Test"
        }
    }
}
```
```java
ObjectMapper objectMapper = new ObjectMapper();
User user = objectMapper.readValue(jsonString, User.class);
System.out.println(user.getFirstName());
```

**Comment by cowtowncoder** [comment]
Not possible to support, from technical perspective.

Will close as "won't implement".
