### ISSUE TITLE
Generate A.toB() methods with new @MappingMethod annotation

### ISSUE THREAD

**Issue by 0248991** [FasterXML/jackson-databind#4288]
### Is your feature request related to a problem? Please describe.

I want to simplify work with `objectMapper` in a way that allows me to map object A to object B with a simple overridable `A.toB() `method, and not have to call it explicitly.

### Describe the solution you'd like

Instead of:
```
A a = new A();
B b = mapper.convertValue(a, B.class);
```

do this:

```
@MappingMethod(B.class)
class A {

  //function will be generated during compilation
  public B toB() {
    return mapper.convertValue(this, B.class);
  }

}
```

The benefit is also that the function toB() could be overridden for explicit mapping, e.g. like so:
```
@MappingMethod(B.class)
class A {

  @Override
  public B toB() {
    B b = new B();
    b.setExplicitField("explicit value");
    return ObjectMapper.mapFrom(this, b); //note: I know that function mapFrom probably doesn't exist, it's just a placeholder
    //note: mapFrom would need to be either a static call, or there should be an instance of a mapper available somehow
  }

}
```

### Usage example

Mapping from A to B would be simplified to:
`B b = a.toB();`

### Additional context

I think this would be a nice feature to get rid of stuff like MapStruct or similar, which require defining extra interfaces. 
Also, it would make explicit mapping (own implementation) easier, noticeable and compile-safe. So e..g. instead of:
 
```
interface MapStruct {
  
  @Mapping(target = "explicitField", expression="java(bad syntax)") // doesn't have IDE support like navigation, static analysis,...
  B mapFrom(A a);
}
```

do this:

  ```
@Override
  public B toB() {
    B b = new B();
    b.setExplicitField("explicit value"); //is casual code, has full IDE support
   return ObjectMapper.mapFrom(this, b);
  }
```

**Comment by cowtowncoder** [comment]
Jackson databind does not do any code generation, so this is not something we can add.

There are 2 modules -- Afterburner and Blackbird -- that do:

https://github.com/FasterXML/jackson-modules-base

which could theoretically add this. But more likely, such functionality should be provided by some new, not yet existing module. Especially if the idea is to do this at compile time, which is not something Afterburner/Blackbird do.

Will leave open for some discussion but likely close in near future.

**Comment by 0248991** [comment]
Okay :)
I meant to do it the same way as other annotations work, e.g. `@ToString` - don't they generate code during compilation?

And about "overriding" a method - I think this could be done the same way it's done with e.g. `@Getter` methods - create a method with the same signature to stop Jackson from generating it.

I definitely didn't mean "code generation" as a separate step.

**Comment by cowtowncoder** [comment]
Not sure which `@ToString` annotation you are thinking of (Jackson does not provide one) -- maybe it's Lombok?
So other frameworks like Lombok and Immutables do perform such processing. But Jackson is strictly only using runtime access and use of annotations, and does not participate in compilation/build cycle in any way.

**Comment by 0248991** [comment]
Ah, right, I got it wrong, it's the Lombok stuff, sorry.
I guess you can close this ticket, then.

**Comment by JooHyukKim** [comment]
@0248991 Can you close the ticket? You are the author after all. Tnx!
