### ISSUE TITLE
I also encountered the same problem, but it is much larger than 250M, as shown in the figure, with 5.7G. How should I limit the modification

### ISSUE THREAD

**Issue by WDXDenys** [FasterXML/jackson-databind#4289]
I also encountered the same problem, but it is much larger than 250M, as shown in the figure, with 5.7G. How should I limit the modification
![image](https://github.com/FasterXML/jackson-databind/assets/154816419/f5fe397c-ec77-4c89-a52a-16564dd074ac)

_Originally posted by @WDXDenys in https://github.com/FasterXML/jackson-databind/discussions/4287#discussioncomment-7947296_

**Comment by cowtowncoder** [comment]
Looks like this got accidentally created from a comment. Closing.
