### ISSUE TITLE
Any text after json definition is ignored

### ISSUE THREAD

**Issue by iMashtak** [FasterXML/jackson-databind#4290]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

The following code:

```java
var json = new ObjectMapper();
var result = json.readTree("""{}some secret text""");
System.out.println(json.writeValueAsString(result));
```

do not fails and prints `{}` as a result

### Version Information

2.15.3

### Reproduction

Described in previous section

### Expected behavior

I expect parser to fail if I send not valid json to it.

### Additional context

That causes incorrect behavoiur in projects like [json-schema-validator](https://github.com/networknt/json-schema-validator) - invalid json passes validation :(

**Comment by cowtowncoder** [comment]
Not a bug: only content that is needed to bind a value is decoded. This is the default behavior.

But if you do want to additional validate all content being sent, please enable

    DeserializationFeature.FAIL_ON_TRAILING_TOKENS

and content will be scanned and exception thrown.
