### ISSUE TITLE
README.md link gets redirected back to top

### ISSUE THREAD

**Issue by Farmbuyer** [FasterXML/jackson-databind#4292]
### Documentation Improvement

Under the section "Annotations: changing property names" is a line

> There are other mechanisms to use for systematic naming changes: see [Custom Naming Convention](https://github.com/FasterXML/jackson-databind/wiki/JacksonCustomNamingConvention) for details.

When clicked, the JacksonCustomNamingConvention link just gets redirected back to the wiki index page.

**Comment by cowtowncoder** [comment]
Looks like link points to non-existing wiki page; removed as I could not find a match either here, or within `jackson-docs` repo. Also changed the following "mix-in" link, for which Wiki page does exist.
