### ISSUE TITLE
KotlinModule is not registered in findAndAddModules in 3.0

### ISSUE THREAD

**Issue by k163377** [FasterXML/jackson-databind#4295]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

In branch 2.17, I added the following test.
This test confirms that `new ObjectMapper().findAndRegisterModules()` registers `KotlinModule`.
https://github.com/FasterXML/jackson-module-kotlin/pull/744/files#diff-e321202d356c7c7d5868457f76b2d378bfa922d95322cc609c74fa38e2768159

On the other hand, when I modified this test as follows and tried to merge it into master, the test failed.

```kotlin
    @Test
    fun findAndRegisterModulesTest() {
        val mapper = JsonMapper.builder().findAndAddModules().build()
        assertTrue(mapper.registeredModules.any { it is KotlinModule })
    }
```

Here, JavaTime modules were registered in both 2.17 and 3.0 (so far only these two modules are registered when running `findAndRegisterModules` in 2.17).

### Version Information

3.0(master)

### Expected behavior

As in 2.x, a `KotlinModule` should be added.

**Comment by cowtowncoder** [comment]
There is nothing special in `jackson-databind` for any of the modules, so I think this is due to SPI metadata.
And looking at Kotlin module's `src/main/resources/META-INF/services`, I think I see the issue: name for resource is

    com.fasterxml.jackson.databind.JacksonModule

and contains:

    com.fasterxml.jackson.module.kotlin.KotlinModule

These need to be changed to

    tools.jackson.databind.JacksonModule

and 

    tools.jackson.module.kotlin.KotlinModule

I can do a PR.

**Comment by cowtowncoder** [comment]
@k163377 PR here: https://github.com/FasterXML/jackson-module-kotlin/pull/749

**Comment by k163377** [comment]
Thank you, I have confirmed that it has been corrected.
I should have looked into the ServiceLoader a bit more, sorry.

**Comment by cowtowncoder** [comment]
> Thank you, I have confirmed that it has been corrected. I should have looked into the ServiceLoader a bit more, sorry.

No that's fine: I made the changes for 3.0 compatibility and I should have caught it. But it's good now: all's well that ends well etc.
