### ISSUE TITLE
Support for random json property order

### ISSUE THREAD

**Issue by jhaber** [FasterXML/jackson-databind#4298]
### Is your feature request related to a problem? Please describe.

As part of Jackson upgrades, it's not uncommon for the order in which properties get written to change. We always find some number of unit tests start to fail because they were comparing raw json strings, rather than json nodes. 

### Describe the solution you'd like

Go has random iteration order on maps to avoid this problem at a language level. I'm curious if something like that would be useful for Jackson, basically something like `@JsonPropertyOrder(random = true)`. This way people can't write tests which rely on property ordering.

Theoretically we could also solve our problem using `@JsonPropertyOrder(alphabetical = true)`, since that would result in a stable order. However, this would further encourage people to compare raw strings and rely on property order (which we're trying to avoid)

**Comment by cowtowncoder** [comment]
Quick note: all processing of annotations like `@JsonProperty` happens when constructing Serializers/Deserializers, which are then cached (per `ObjectMapper`). So in case of regular ordering, order chosen is fixed as part of `JsonSerializer` (in case of writing output).

As such, implementing random ordering would produce random but stable ordering for given mapper; but not something where every call to `ObjectMapper.write()` (etc) would produce different ordering.
This may or may not be desired behavior.
 
If "random every time" handling was desired, one would need to make `BeanSerializer` itself handle randomization.

But I guess I should have started by asking bit more explanation on intended use case -- would this be for use in testing? And what would be the desired properties wrt "how random" (vs stable) for such "sorting".

**Comment by jhaber** [comment]
> But I guess I should have started by asking bit more explanation on intended use case -- would this be for use in testing? And what would be the desired properties wrt "how random" (vs stable) for such "sorting".

I would say the primary use-case is for making unit tests more robust. Because the property ordering seems to be relatively stable for a given Jackson version, within a large codebase we inevitably end up with unit tests that come to rely on the ordering. This dependency is sometimes explicit, for example by asserting `writeValueAsString` matches a String literal such as `{"a": 1, "b": 2}` (which then breaks if a newer version of Jackson returns `{"b": 2, "a": 1}`.  And sometimes it's more indirect/subtle, for example by hashing something that happens to include Jackson-generated json, which causes hash mismatches if the property order changes.

All of this code that depends on property ordering then becomes a huge impediment to upgrading Jackson, because each test failure must be individually investigated to determine whether something is actually broken, or whether the test was just relying on property ordering.

But if the property order was random, then you wouldn't end up in this situation because people wouldn't be able to write these brittle tests in the first place.

And while I think testing is the primary use-case, technically production code can also come to depend on property order, just like any other observable behavior (especially with public APIs where do you don't control the client code)

> As such, implementing random ordering would produce random but stable ordering for given mapper; but not something where every call to ObjectMapper.write() (etc) would produce different ordering.
This may or may not be desired behavior.

I'm imagining that random for a given JVM would be sufficient (and random for a mapper is even stronger than that). That way each unit test run would produce a different ordering, which handles the testing use-case. And each container in production would also produce a different ordering, which mostly handles any concerns with production code

**Comment by yawkat** [comment]
this is also a feature the new immutable collections in the jdk have (Set.of etc). they have a JVM-level "salt" that changes the iteration order of sets so that people don't rely on the implementation-defined order.

**Comment by JooHyukKim** [comment]
For both users' and Jackson development perspective, we might also want to consider if we want test-purpose configuration take place in production code. Idk if it's worth it, considering how invasive it would be (I only suppose).

Have you considered/looked-for shuffling libraries? I imagine something like....

```java
SomeBean bean = initializeSomeBean();

// random ordered serialization part
String JSON = objectMapper.writeValueAsString(bean);
String shuffledJSON = shuffler.shuffle(JSON);

// do actual testing
...
```

**Comment by yihtserns** [comment]
> Have you considered/looked-for shuffling libraries?

From the way OP writes, I think it's less about him writing the tests, and more about "encouraging/nudging" his other coworkers in the company he's working in.

I think they're likely also a Java shop, because if they were to use Groovy/Spock to write tests writing a String to assert is much more hassle than:
```
String json = ...
new JsonSlurper().parseText(json) == [a: 1, b: 2, c:3]
```

**Comment by jhaber** [comment]
> For both users' and Jackson development perspective, we might also want to consider if we want test-purpose configuration take place in production code.

I would consider this a valuable feature for production as well. For example, third parties that are consuming JSON from our APIs may come to rely on property order if it is consistent.

> > Have you considered/looked-for shuffling libraries?
> 
> From the way OP writes, I think it's less about him writing the tests, and more about "encouraging/nudging/~forcing~" his other coworkers in the company he's working in.

Yes, we have 1,500+ engineers and people _mostly_ write robust tests, but with so many people writing code there's always going to be stuff sneaking in (we also use error-prone, but the ways in which code can depend on property order are too numerous and subtle to reliably prevent with static analysis). 

If something like `@JsonPropertyOrder(random = true)` existed, we could apply that globally to solve the problem

**Comment by pjfanning** [comment]
I agree with @yihtserns. Jackson is complicated enough already. This seems like something a code reviewer should look for. There is nothing more annoying than a test that passes sometimes and fails other times. Random order tests will still pass some times. There are so many other enhancements that we could be looking at.

**Comment by jhaber** [comment]
> This seems like something a code reviewer should look for.

Maybe in a perfect world, but empirically it seems that no amount of vigilance can reliably prevent these sorts of issues in large codebases with thousands of engineers (which is part of the value proposition of tools like error-prone).  

> There is nothing more annoying than a test that passes sometimes and fails other times. Random order tests will still pass some times. 

The likelihood of the test passing decreases exponentially as the number of properties increases. For example, if your object graph has 10 properties total (not very big), the chance of it passing with random property order is roughly one in a thousand.

> There are so many other enhancements that we could be looking at.

Fair enough, but I did think it was worth the time to try to explain the pain point clearly as I imagine most large orgs that use Jackson widely experience similar problems when trying to upgrade.

**Comment by jhaber** [comment]
It looks like you can actually simulate this feature using existing Jackson extension points. It won't randomize map keys and probably has other gaps, but it seems to mostly work and is probably good enough for what I had in mind:

```java
import com.fasterxml.jackson.core.Version;
import com.fasterxml.jackson.databind.BeanDescription;
import com.fasterxml.jackson.databind.Module;
import com.fasterxml.jackson.databind.SerializationConfig;
import com.fasterxml.jackson.databind.ser.BeanPropertyWriter;
import com.fasterxml.jackson.databind.ser.BeanSerializerModifier;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

public class RandomPropertyOrderModule extends Module {

  @Override
  public String getModuleName() {
    return getClass().getSimpleName();
  }

  @Override
  public Version version() {
    return Version.unknownVersion();
  }

  @Override
  public void setupModule(SetupContext context) {
    context.addBeanSerializerModifier(new RandomPropertyOrderBeanSerializerModifier());
  }

  private static class RandomPropertyOrderBeanSerializerModifier
    extends BeanSerializerModifier {

    @Override
    public List<BeanPropertyWriter> orderProperties(
      SerializationConfig config,
      BeanDescription beanDesc,
      List<BeanPropertyWriter> beanProperties
    ) {
      if (shouldSortAlphabetically(config, beanDesc)) {
        return beanProperties;
      } else {
        beanProperties = new ArrayList<>(beanProperties);
        Collections.shuffle(beanProperties);

        return beanProperties;
      }
    }
  }

  private static boolean shouldSortAlphabetically(
    SerializationConfig config,
    BeanDescription beanDesc
  ) {
    Optional<Boolean> sortAlphabetically = Optional.ofNullable(
      config
        .getAnnotationIntrospector()
        .findSerializationSortAlphabetically(beanDesc.getClassInfo())
    );

    return sortAlphabetically.orElseGet(config::shouldSortPropertiesAlphabetically);
  }
}
```

**Comment by cowtowncoder** [comment]
@jhaber That looks like a nice approach!

I was about to suggest overriding `AnnotationIntrospector.findSerializationPropertyOrder()` but then realized that it requires specifying names of properties and does not get passed introspected property names.
Whereas `BeanSerializerModifier.orderProperties()` is specifically given all the necessary information.

**Comment by pjfanning** [comment]
To me, it seems like someone could write a JsonShuffler library in the language of their choice. An API like `String shuffleJson(String)`. Other input and output types could be supported.

This lib doesn't have to be Jackson based.

**Comment by cowtowncoder** [comment]
@pjfanning I assume such things already exist with various testing frameworks. FWTW it sounds like the thing here is related to (unit) testing against Jackson-based system so there is probably issues relating to practical minimally invasive changes to tease out fragile tests, and for those more specific tooling is probably helpful.

It is also worth noting that `JsonNode` comparison is order-insensitive wrt JSON Objects; this works well enough for many use cases (although with usual caveats wrt number type comparisons).

**Comment by jhaber** [comment]
> To me, it seems like someone could write a JsonShuffler library in the language of their choice. An API like String shuffleJson(String). Other input and output types could be supported.
>
> This lib doesn't have to be Jackson based.

Most of the time people compare json structure (via `JsonNode`) rather than json strings, so no shuffling is needed. But we still run into rare cases where property order changes break something. Sometimes the dependency on property order is very subtle, and you need to dig down multiple layers before you even realize it's the root cause of a test failure (ie, the test might not even reference Jackson or json directly)

Given enough engineers, a large enough codebase, and a stable property order, I would posit that things _will_ come to depend on that property order. We can argue about how many engineers and how large of a codebase before that effect emerges, but given large enough values it feels like the conclusion is inevitable.
