### ISSUE TITLE
Add option to resolve type from multiple existing properties (`@JsonTypeInfo(use=DEDUCTION)`)

### ISSUE THREAD

**Issue by bytesandwich** [FasterXML/jackson-databind#43]
Rather than forcing the creation of an additional typeId property, or class info, determine the type by its natural properties. Possible As.EXISTING_PROPERTIES, and register a TypeResolver that returns the JavaType by inspecting the object. 

Given a type hierarchy, naturally subtypes have additional fields and their type can likely be determined simply by inspecting the fields.

**Comment by cowtowncoder** [comment]
See #1100 for pssible additional ideas.
