### ISSUE TITLE
StdValueInstantiator unwraps exceptions, losing context

### ISSUE THREAD

**Issue by milesk-amzn** [FasterXML/jackson-databind#432]
When using ObjectMapper to create objects, if the constructor throws an exception, it is "unwrapped" such that the JsonMappingException's direct cause is the *innermost* exception. This potentially loses important context that had been added to the exception chain by the constructor, such as which property the exception applied to.

https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/deser/std/StdValueInstantiator.java#L440

I'm not entirely clear on why StdValueInstantiator is looking for an existing JsonMappingException in the exception chain rather than just unconditionally wrapping the outermost exception directly.

**Comment by cowtowncoder** [comment]
One note on original question: the reason for looking for an existing `JsonMappingException` is to reuse applicable exception instead of adding yet another layer of wrapping; as well as to preserve location information container therein (granted it would be wrapped). I have come to dislike massive onion-like layers of exception wrapping.

But I can see how unwrapping itself can be problematic. The main thing to figure out would be just whether unwrapping should be controlled globally (unwrap / dont-unwrap), or for specific case of creators.
For now, I assume that global setting would be fine for simplicity.

**Comment by cowtowncoder** [comment]
Have not had time to look further into this, but one possible work-around would be to make `ValidationException` extend `JsonMappingException`. If so, it would not be wrapped or discarded.

However: for 2.7 I think I will also change the logic of unwrapper slightly: only unwrap one level, and only if it is one of JDK's wrapper exceptions, like `ExceptionInInitializerError`, but NOT to unwrap "custom" exceptions. I think this makes sense as it will retain exact exception your code throws.

**Comment by cowtowncoder** [comment]
Ok I think handling is much improved now and should handle wrapping better. Basically, it only unwraps immediate "throw from static init block / constructor" error/exception, if one exists, and then either passes as is (if already `JsonMappingException`), or wraps as `JsonMappingException` with cause, copying `message`. I think this makes sense, and specifically preserves custom exception thrown, if any.

**Comment by alveomaster** [comment]
Please i still stuck against this issue 
In a spring data rest project i use a custom RuntimeException to be called in a custom Deserializer

```
public class LocalDateDeserializer extends StdDeserializer<LocalDate> {
 ...
    @Override
    public LocalDate deserialize(JsonParser jsonparser, DeserializationContext context) throws IOException, JsonProcessingException {
        String date = jsonparser.getText();
        String name = jsonparser.getCurrentName();
        try {
            return LocalDate.parse(date, DateTimeFormatter.ISO_LOCAL_DATE);
        } catch (DateTimeParseException e) {
            throw new ApiJacksonException("error on: " + name);
        }
    }
}
```
My User.class

```
@Data
@NoArgsConstructor
public class User extends Auditing implements Serializable {
    private static final long serialVersionUID = 1L;
 ...
    @DateTimeFormat(iso = ISO.DATE)
    @JsonFormat(pattern = "yyyy-MM-dd")
    @JsonDeserialize(using = LocalDateDeserializer.class)
    @JsonSerialize(using = LocalDateSerializer.class)
    private LocalDate birthdate;
}
```
When i send a POST request with a wrong date format the @ControllerAdvice catch the custom RuntimeException

But when i send a PATCH request with a wrong date format it seams that the RuntimeException is wrapped by the JsonMappingException and can't be catched by the @ControllerAdvice in the properties file i have set

`spring.jackson.deserialization.wrap-exceptions = false`

_How to unwrap Custom RuntimeException from Jackson Mapping Exception
Have i missed some thing!_
