### ISSUE TITLE
Dynamically configure defaultInclusion on ObjectWriter

### ISSUE THREAD

**Issue by kylejmcintyre** [FasterXML/jackson-databind#4372]
### Is your feature request related to a problem? Please describe.

I want to toggle the default inclusion (e.g. NON_NULL vs. ALWAYS) dynamically (on a per-serialization basis) while still using a single mapper. Static annotations don't work for this case and Filters seems like major overkill considering the framework has a default inclusion concept already.

### Describe the solution you'd like

A fluent/builder method on ObjectWriter that allows me to change the default property inclusion on a per serialization basis. Or, perhaps more generally, a builder method on ObjectWriter that lets me specify the full Serialization Config.

### Usage example

`mapper.writer().withDefaultPropertyInclusion(JsonInclude.Include.NON_NULL).writeValueAsString(...)`

or

`mapper.writer().withSerializationConfig(mapper.getSerializationConfig().withDefaultPropertyInclusion(JsonInclude.Include.NON_NULL))`

### Additional context

Is there something about the default inclusion that makes it not work as something you can configure on the fly, or would these simple method variants make this a possibility? Or perhaps there's a way to do it but I've spent a few hours and couldn't figure out a way short of reflection and/or forking. Thanks for your consideration.

**Comment by JooHyukKim** [comment]
Would such feature affect performance, checking per serialization?

How about going other way around by implementing a custom deserializer to hold two instances of ObjectWriter?
- One with `NON_NULL`, and
- The other with `ALWAYS`

**Comment by cowtowncoder** [comment]
No, this is not possible and cannot be supported: this because inclusion criteria will directly affect construction of value serializers that get cached.
This is specifically why this is not (and will not be) configurable on per `ObjectWriter` basis.

If you want different configuration, you will need to have multiple `ObjectMapper`s (possibly using `ObjectMapper.copy()` to get a new copy with otherwise same settings.
