### ISSUE TITLE
`TextNode.equals()` throws `NullPointerException` when `TextNode` constructed with `null`

### ISSUE THREAD

**Issue by Javed6234** [FasterXML/jackson-databind#4378]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

new TextNode(null) == new TextNode(null) returns false.
When debugging this issue, it actually causes an NPE in TextNode's `equals` method.

### Version Information

Version: 2.13.5
Java 11
Spring Boot: 2.5.15

### Reproduction

```
TextNode nodeOne = new TextNode(null);
TextNode nodeTwo = new TextNode(null);
nodeOne.equals(nodeTwo);
```

### Expected behavior

I would expect this to return true as both values are equal

**Comment by pjfanning** [comment]
Does this happen if you use the equals method? That is the more correct way to check for value equality

**Comment by Javed6234** [comment]
@pjfanning Yeah, sorry, should have used equals as an example under Reproduction, I have updated it now
`((TextNode) o).textValue().equals(this._value)` causes the NPE

**Comment by pjfanning** [comment]
@Javed6234 see https://github.com/FasterXML/jackson-databind/pull/4379

**Comment by Javed6234** [comment]
@pjfanning Lovely, thank you!

**Comment by pjfanning** [comment]
@Javed6234 Looking at the code in TextNode and equivalent classes like DecimalNode, it is clear that they were never intended to support nulls. The constructors on these classes are public but not really intended to be used by non-Jackson code. They are public to faciliatate modular Jackson code.

Why do you need to use `new TextNode(null)`?

@cowtowncoder in Jackson 3, we should probably throw an exception if some calls the TextNode/DecimalNode/BigIntegerNode constructors with null inputs. I would argue that it too late in Jackson 2 to make these constructors strict about null inputs. I have created #4379 and #4380 to work around immediate issues with equals and hashCode but users who somehow get null data into instances of these classes will likely get NullPointerExceptions elsewhere (eg DecimalMode doubleValue() method is not null safe and can't be made null safe).

**Comment by cowtowncoder** [comment]
Ok, so, no, this is NOT a supported use case. We should, I think, fail with exception on `new TextNode(null)`.
Same goes for other Object-valued `JsonNode`s like you suggested.

But there is of course the pesky question of backwards compatibility, so I agree that it might be too late for 2.x.

I do agree that no NPE should be thrown for `equals()` and `hashCode()`.
And probably `equals()` should return `true` for those cases (even if that has minor backwards-compatibility implications).

Thank you @Javed6234 for reporting this problem.

**Comment by cowtowncoder** [comment]
For 2.x, then, `null` will be allowed and supported. For 3.0 we'll change that.

Thank you once again for reporting this @Javed6234 !
