### ISSUE TITLE
Prevent construction of `null`-valued `JsonNode`s (like `TextNode`)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#4381]
### Describe your Issue

(note: follow-up to #4378 which is for 2.x)

We should not allow constructing `JsonNode`s around `null`, except for explicit `NullNode`: attempts to do so should throw a `JacksonException` (`DatabindException` subtype).
This should be checked for:

* `TextNode`
* `BigIntegerNode`
* `DecimalNode`
* `BinaryNode`

There may also be cases where we decide `null` is appropriate content.
One such type is `POJONode`.

**Comment by cowtowncoder** [comment]
cc @pjfanning .

**Comment by pjfanning** [comment]
I would include BinaryNode here too.

**Comment by cowtowncoder** [comment]
@pjfanning Ok I have no strong opinion so sure, why not.
