### ISSUE TITLE
MavenGate (CVE)

### ISSUE THREAD

**Issue by amareshdlphx** [FasterXML/jackson-databind#4386]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

XFrog triggers an alert on packages: 
- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider
- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base
- com.fasterxml.jackson.core:jackson-databind
- com.fasterxml.jackson.core:jackson-core
- com.fasterxml.jackson.core:jackson-annotations

Looks like groupId can be claimed claimed by malicious user.

### Version Information

2.15.3

### Reproduction

<-- Any of the following
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here
 -->
```java
// Your code here
```

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson/discussions/206 is open
