### ISSUE TITLE
Additional parameter for @JsonAppend.Prop

### ISSUE THREAD

**Issue by feg545** [FasterXML/jackson-databind#4395]
### Is your feature request related to a problem? Please describe.

we have a pojo like this:
```json
{
  "code":"C100",
  "owner": "adle",
  "assignee": "bob"
}
```
now we want display nick name for adle and bob, and display friendly message for error code. like this:

```json
{
 "code": "C100",
  "owner": "adle",
  "assignee": "bob"
  "message": "here is some i18n message",
  "ownerName": "Adle PM",
  "assigneeName": "Bob Dev"
}
```

our java code like this:
```java
@JsonAppend(
        props = {
        @JsonAppend.Prop(value = AccountToNameSerializer.class, name = "ownerName"),
        @JsonAppend.Prop(value = AccountToNameSerializer.class, name = "assigneeName"),
        @JsonAppend.Prop(value = CodeToMessageSerializer.class, name = "message")}
)
public class Message {
    private String code;
    private String owner;
    private String assignee;
}
```
for `AccountToNameSerializer.class`, there is no way to tell it use `owner` and `assignee` as source attribute;
for `CodeToMessageSerializer.class`, there is no way to tell it use `code` as source attribute; 

### Describe the solution you'd like

add an additional property `reference` in `@JsonAppend.Prop`, for example:

```java
@JsonAppend.Prop(value = AccountToNameSerializer.class, name = "ownerName", reference="owner"),
@JsonAppend.Prop(value = AccountToNameSerializer.class, name = "assigneeName", reference="assignee"),
@JsonAppend.Prop(value = CodeToMessageSerializer.class, name = "message", reference="code")
```

### Additional context

Spring MVC 4.1.6.RELEASE
Jackson 2.9.9

**Comment by yawkat** [comment]
you could do something like this:

```java
@JsonAppend(
        props = {
        @JsonAppend.Prop(value = OwnerName.class, name = "ownerName"),
        @JsonAppend.Prop(value = AssigneeName.class, name = "assigneeName"),
        @JsonAppend.Prop(value = Message.class, name = "message")}
)
public class Message {
    private String code;
    private String owner;
    private String assignee;

    static class OwnerName extends AccountToNameSerializer { OwnerName() { super("owner"); } }
    static class AssigneeName extends AccountToNameSerializer { OwnerName() { super("assignee"); } }
    static class Message extends CodeToMessageSerializer { OwnerName() { super("code"); } }
}
```

imo the feature you're suggesting is too specific. maybe the "proper" approach would be to be able to pass any constructor arguments to the writer. but this same feature would also make sense outside JsonAppend.props, e.g. with JsonDeserialize.using, so it may be part of a wider effort.

I think the subclass approach i show above is a more powerful generic way to achieve this.

Another thing to consider is whether your approach is sensible at all. It seems like your serializers actually fetch data for the writing from external sources? That seems a bit much to do at the serialization level, and may actually interfere with web framework operation (though probably not spring). Consider making a DTO with these properties instead.

**Comment by cowtowncoder** [comment]
Yeah I don't think this is something I'd want to add -- virtual properties are not meant for renaming of actual properties, and there is no logic intended to allow automatically pass values from logical properties to serializers in context of annotation configuration.
Further, regular value serializers are explicitly only called to serialize values, not property names (except for `BeanSerializer` that does handle writing of property names) so that might be limiting here as well.

I would suggested looking into ideas @yawkat mentioned above to solve your problem.

**Comment by feg545** [comment]
Thanks for fast reply. 
> maybe the "proper" approach would be to be able to pass any constructor arguments to the writer. but this same feature would also make sense outside JsonAppend.props, e.g. with JsonDeserialize.using, so it may be part of a wider effort.

Don't care about my use case, and Yes! I just want pass some custom properties from annotation to my serializer instance.
here is example code:

```java
public class Message {
    @JsonSerialize(using = MySerializer.class, properties="xxx")
    private String owner;
}
```
```java
public class MySerializer extends ToStringSerializer {
    private String properties;

    //expose a setter method to receive properties in annotation
    public void setProperties(String properties){
        this.properties = properties;
    }

    @Override
    public void serialize(Object value, JsonGenerator gen, SerializerProvider provider) throws IOException {
        //use properties
    }
}
```
Due to the limitation of the java annotation domain, we can not create new object in annotation. But jackson can create the serializer first, and then set the additional properties. the properties is simple string, developer could use it save any config.

**Comment by cowtowncoder** [comment]
The mechanism Jackson offers for accessing information from context, in particular annotations, is via `ContextulSerializer`: implementing that will allow serializer to access this information (through passed-in `BeanProperty`).

**Comment by feg545** [comment]
thanks @cowtowncoder , the `ContextualSerializer` is the perfect solution that I need.
