### ISSUE TITLE
Support for @JsonView in property detection.

### ISSUE THREAD

**Issue by UnquietCode** [FasterXML/jackson-databind#440]
When I annotate properties with `@JsonView` my expectation is that property detection would respect the different views. Consider the following example:

```java
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.ObjectMapper;

public class TestIt {

	public static void main(String[] args) throws Exception {
		Person person = new Person();
		person.setFirstName("Donald");
		person.setLastName("Knuth");

		ObjectMapper mapper = new ObjectMapper();
		String s = mapper.writerWithView(View1.class).writeValueAsString(person);
		System.out.println(s);
	}

	public interface View1 { }
	public interface View2 { }

	public static class Person {

		private String firstName;
		private String lastName;

		@JsonProperty("name")
		@JsonView(View1.class)
		public String getFirstName() {
			return firstName;
		}

		@JsonProperty("name")
		@JsonView(View2.class)
		public String getFullName() {
			return firstName + " " + lastName;
		}

		public void setFirstName(String firstName) {
			this.firstName = firstName;
		}

		public void setLastName(String lastName) {
			this.lastName = lastName;
		}
	}
}
```

When running this I get a "java.lang.IllegalArgumentException: Conflicting getter definitions for property 'name'" error. Is it possible to support the views here, such that two properties with the same name but different views (which are unrelated by their type hierarchy) can coexist?

**Comment by sddakoty** [comment]
Has this been solved to support multiple samename `@JsonProperty` if used with different `       @JsonView`?

**Comment by cowtowncoder** [comment]
@sddakoty  No: this does not and will not work. Properties can not vary between views: views may only be used to subset from a set of properties. So issue is closed as "wont-implement".

**Comment by sddakoty** [comment]
I see, thanks for your instant feedback.

Is there any mechanism that can serialize different fields used in different views with the same property name?

**Comment by cowtowncoder** [comment]
@sddakoty not sure I understand the question.

**Comment by sddakoty** [comment]
```
        @JsonProperty("name")
        @JsonView(View1.class)
        public String getFirstName() {
            return firstName;
        }

        @JsonProperty("name")
        @JsonView(View2.class)
        public String getFullName() {
            return firstName + " " + lastName;
        }
```

I want to achieve the same as: having two different properties that should - depending on the view - be serialized with the same "name".
If I cannot use @JsonView here, maybe jackson offers a different approach I could use to make it work?

**Comment by cowtowncoder** [comment]
@sddakoty At this point it would really have to be a custom serializer, I think. Views are applied dynamically, but properties set built statically. You could perhaps add "virtual property", but that gets tricky. So I can not think of any existing declarative way that would work -- even "any getter" would not work without extra handling for view.

**Comment by pas-marcus** [comment]
@sddakoty Does this address what you are looking for? I haven't tested but came across it while researching this topic.

https://stackoverflow.com/a/41206991/2407209

**Comment by mipo256** [comment]
Time goes by, and we still do not really have any solution for this problem @cowtowncoder
