### ISSUE TITLE
Deserialization of unknown value for enums does not yield default enum value

### ISSUE THREAD

**Issue by dominik-henning** [FasterXML/jackson-databind#4403]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

i have a class containing a field of an enum type. The data is fetched from an api that can add further possible enum values at any point. I want to guard my implementation by using the JsonEnumDefaultValue.

During the deserialization of an unknown value, instead of the annotated default, a different instance of this enum is returned.

### Version Information

2.16

### Reproduction

https://github.com/dominik-henning/jackson-databind-enum-deserialization-reproducer

i created a projected containing a test class which shows my usecase and setup.

### Expected behavior

When an value is encountered which does not match to a annotated JsonProperty, i would expect that the JsonEnumDefaultValue is returned.

### Additional context

The real world example is different, but the project boils the problem down to the bare minimum.

**Comment by cowtowncoder** [comment]
Ok, yes, I can reproduce: thank you for providing the sample project.

The root cause: this happens because `"001"` is treated as index `1`, before considering it "unknown" value.

I'll have to see what we can do here.

**Comment by cowtowncoder** [comment]
@dominik-henning In the meantime you may want to enable

    DeserializationFeature.FAIL_ON_NUMBERS_FOR_ENUMS

to prevent use of index (number) values for `Enum` deserialization.
That will make things work as expected here.

**Comment by dominik-henning** [comment]
Thank you @cowtowncoder for the hint. I enabled the feature and now it works like a charm.

**Comment by cowtowncoder** [comment]
Good! I hope I can find other minor improvements but at least you can use configuration to avoid the problem.

**Comment by cowtowncoder** [comment]
Ok, was able to add a minor improvement: will NOT consider Strings with leading `0` as legitimate number: so `"001"` will no longer be coerced into number.

Not quite as good as preventing (automatic) use of "Stringified" numbers, but thinking it helps. Will be in 2.17.0.

**Comment by dominik-henning** [comment]
Thanks @cowtowncoder , appreciate it !
