### ISSUE TITLE
Deprecate `JsonNode.asText(String)`

### ISSUE THREAD

**Issue by apeteri** [FasterXML/jackson-databind#4416]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

It looks like the fallback value in `JsonNode#asText(String)` never gets a chance to appear as the 0-arg `asText()` should never return `null`, according to its Javadoc:

https://github.com/FasterXML/jackson-databind/blob/dca0c27463a3ab3a4c8f2f105f3c3109ae97f564/src/main/java/tools/jackson/databind/JsonNode.java#L604-L623

This seems to be the case in all implementations of `asText()` I can see, and has been corroborated in other issues such as #25.

The only exception is if someone calls `TextNode(String)` directly with `null` as the input. `TextNode#valueOf(String)` already converts these cases into `null` references, so the "almost" in the title is quite strong.

### Version Information

2.16.1

### Expected behavior

Either replace the `null` check with an emptyness check (but then "legitimate empty" strings will also use the default value), or deprecate the method? Not quite sure!

**Comment by cowtowncoder** [comment]
Ok explanation makes sense: I'd vote for deprecation. We can do that for 2.17 -- would be happy to get a PR (with Javadoc explaining reasoning).

**Comment by cowtowncoder** [comment]
Interestingly enough, this method behaves bit different than advertised: "defaultValue" will be returned for all `MissingNode`s and `NullNode`s EVEN THOUGH THEIR `asText()` does NOT return `null`... uh.

All the more reason to deprecate it, tho, remove from 3.0.

**Comment by cowtowncoder** [comment]
@apeteri no problem; not a big deal. Thank you for pointing this out.

**Comment by cowtowncoder** [comment]
Looks like this should be reverted, based on feedback and better understanding on logic & updated description.

**Comment by cowtowncoder** [comment]
Reverted for 2.17.1 via #4471 .
