### ISSUE TITLE
Allow specifying getMissingValue() in JsonDeserializer

### ISSUE THREAD

**Issue by gtrog** [FasterXML/jackson-databind#443]
I ran into an issue with some inconsistent behavior when using Guava's Optional<> and GuavaModule to enable deserialization of Optional<>:

If your bean consists of setters and getters:

```java
public class MyRequest {
    @JsonProperty("value")
    private Optional<String> value;

    public Optional<String> getValue() {
        return value;
    }

    public void setValue(Optional<String> value) {
        this.value = value;
    }
}
```

Then the behavior is as follows:
If your json does not specify "value" explicitly, value never gets set and getValue() returns null, allowing you to determine "value" was missing
If your json explicitly specifies "value": null, the setter is called with Optional.absent(), allowing you to determine that "value" was null rather than missing.

Next, if you instead specify your bean using a constructor:

```java
public class MyRequest {
    private final Optional<String> value;

    public MyRequest(@JsonProperty("value") Optional<String> value) {
        this.value = value;
    }

    public Optional<String> getValue() {
        return value;
    }
}
```

Then the behavior is as follows:
If your json does not specify "value" explicitly, Optional.absent() is passed in, because it must be passed in as part of the constructor.  Optional.absent() comes from the fact that the custom deserializer in GuavaModule returns Optional.absent() when calling getNullValue(), although in this case, it's not really a null value that's being deserialized, but instead a missing value.  In order to keep the behavior consistent, two things would be needed:

1.) a getMissingValue() method, which by default could return getNullValue()

2.) explicitly calling setters for missing values with getMissingValue(), in order to ensure that we don't have to make assumptions about what value an unset field will be versus setting it via constructor.

**Comment by cowtowncoder** [comment]
While addition of default values may be a desireable feature, I think we need a clearer RFE.

For what it is worth, Jackson 2.6 will use defaulting for Creators (constructors); and all `Optional`s will have properly set default via `JsonDeserializer.getNullValue(...)`.
If further support for default values for other properties is needed, let's file a new issue that specifically asks for that.
