### ISSUE TITLE
Cannot use @JsonSerialize.using to register custom serializer for a class/interface  

### ISSUE THREAD

**Issue by HristoP96** [FasterXML/jackson-databind#4451]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Annotating a class/interface with @JsonSerialize(using = `MyCustomSerializer.class`) results with a compile error:

`Annotation @JsonSerialize specifies attribute 'using'. Currently supported attributes include: [as]...`

### Version Information

2.16.2

### Reproduction

Create a simple custom serializer and register it over a class/interface by using the  JsonSerialize.using property:

```java
@JsonSerialize(using = MyModelSerializer.class)
public interface MyModel {
    String getName();
}
``` 

### Expected behavior

No compile time errors for something that is not considered as Deprecated.

**Comment by CezaryBD** [comment]
Hello, I was just searching for a similar problem and bumped into this thread! I need this fix as well!

**Comment by HristoP96** [comment]
Using micronaut  latest version at the moment (4.3.5) where only the `JsonSerialize.as` property is [supported](https://micronaut-projects.github.io/micronaut-serialization/latest/guide/#jacksonAnnotations)
