### ISSUE TITLE
Allow JSON Integer to deserialize into a single-arg constructor of parameter type `double`

### ISSUE THREAD

**Issue by davidmoten** [FasterXML/jackson-databind#4453]
### Is your feature request related to a problem? Please describe.

This test fails with a `MismatchedInputException`:

```java
    @Test
    public void testJsonValueIntToDouble() throws JsonMappingException, JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();
        Stuff a = mapper.readValue("5", Stuff.class);
        assertEquals(5, a.value);
    }
    
    public static final class Stuff {
        public final double value;

        public Stuff(double value) {
            this.value = value;
        }
    }
```
If the value being deserialized was `5.0` then it works. `5` does not work.  I'm not interested in workarounds like adding extra constructors of type `int` or `long`, this should just work.

Normally there would be a `@JsonValue` annotation on the field for serialization but that's not relevant for this issue so I've left it out.

I'm finding this hideous to solve in terms of overriding Jackson's default behaviour. Ideally Jackson would do it for me as default behaviour (or configured).

I'd like to override the default `ValueInstantiator` used by an `ObjectMapper` but that does not seem possible. Is it?

Can we change Jackson's default behaviour to support this use case? Or support a new `DeserializationFeature` for this?

### Describe the solution you'd like

see above

### Usage example

see above

**Comment by JooHyukKim** [comment]
Hello, @davidmoten, would this solution help your case?

```java
    @Test
    public void testJsonValueIntToDouble() throws JsonMappingException, JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(cusstomModule());
        Stuff a = mapper.readValue("5", Stuff.class);
        assertEquals(5.0, a.value, 0.0);
    }

    private Module cusstomModule() {
        return new SimpleModule()
                .addValueInstantiator(Stuff.class, new ValueInstantiator() {
                    @Override
                    public Object createFromInt(DeserializationContext ctxt, int value) throws IOException {
                        return new Stuff(Double.valueOf(value));
                    }
                });
    }

    public static final class Stuff {
        public final double value;
        public Stuff(double value) {
            this.value = value;
        }
    }
```

**Comment by davidmoten** [comment]
Thanks @JooHyukKim, I'm aware of that sort of fix but I'm after something more general. _In effect_ I'd like to add use of `_fromDoubleCreator` and even  `_fromFloatCreator` to this method.

https://github.com/FasterXML/jackson-databind/blob/199d3ac25081ba9064e70abe3198210314bab944/src/main/java/com/fasterxml/jackson/databind/deser/std/StdValueInstantiator.java#L353-L388

**Comment by cowtowncoder** [comment]
Sounds reasonable... although in case of `long` its value range exceeds both `float` and `double`.

So possibly would need a new `DeserializationFeature` to enable. And/or checking `CoercionConfig`.

PR welcome!

**Comment by davidmoten** [comment]
> Sounds reasonable... although in case of `long` its value range exceeds both `float` and `double`.

Not loss of range but can lose precision, yep.

> 
> So possibly would need a new `DeserializationFeature` to enable. And/or checking `CoercionConfig`.
> 
> PR welcome!

Thanks, yep I'll sort out a PR.

**Comment by davidmoten** [comment]
@cowtowncoder, when I use a JsonProperty there is no deserialization problem. On a consistency basis shouldn't we just fix StdValueInstantiator?

For example, this test passes:
```java
    @Test
    public void testJsonValueIntToDoubleMulti() throws JsonMappingException, JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();
        Stuff2 a = mapper.readValue("{\"value\":5}", Stuff2.class);
        assertEquals(5, a.value);
    }
    
    public static final class Stuff2 {
        public final double value;

        public Stuff2(@JsonProperty("value") double value) {
            this.value = value;
        }
    }
```

**Comment by JooHyukKim** [comment]
> For example, this test passes:

Strange, wonder if it is intended behavior 🤔

**Comment by cowtowncoder** [comment]
@davidmoten good point, was thinking about that after writing what I did.
You are right, it would still be consistent with that behavior... so no need to add configurability.
PR should be against 2.18.

**Comment by davidmoten** [comment]
I've had a brief look. I'd modify `StdValueInstantiator.createFromInt` and `StdValueInstantiator.createFromLong` to deserialize to a `double` value (and add tests of course).

I've noticed that JsonProperty annotated values will deserialize to a `float` but floats aren't mentioned in `StdValueInstantiator` at all. I'm happy to include float support in the same PR. Would you prefer that in a different PR?

**Comment by JooHyukKim** [comment]
It seems like we almost had it done via https://github.com/davidmoten/jackson-databind/commit/23a635d2ab36b91eb89dafc406671e26fd6e7034. LMK if you need any help with anything, @davidmoten!😆

**Comment by davidmoten** [comment]
Hi, yep I'll get on to that this week. Extended Easter hols have prevented me.

**Comment by davidmoten** [comment]
PR up for review #4474

**Comment by davidmoten** [comment]
Thanks for review and merge. I did some tests and noticed that @JsonProperty will happily deserialize integer JSON values to float, short and byte. For consistency we should do the same with single-arg constructors too. Would you like me to prepare a PR?

**Comment by cowtowncoder** [comment]
Let's add ones to `float` first... I have to think about `short` and `byte` (if they are to be added, can go together).

**Comment by davidmoten** [comment]
> Let's add ones to `float` first... I have to think about `short` and `byte` (if they are to be added, can go together).

Cool, makes sense. When I get the float change approved right then can apply the same pattern to other types. I'll do some more testing on existing JsonProperty deser behaviour too, see what happens when range exceeded (throws  or not).

**Comment by davidmoten** [comment]
Re these two issues:

* loss of precision
* overflow/underflow

I think the first issue is something that a user should wear if they choose a float for a high precision JSON decimal value for instance. The second case varies a bit in effect across byte/short/int/long and float/double but is where throwing might be reasonable. Anyway, I'll first document the JsonProperty deser behaviour for these, see where we end up.

**Comment by cowtowncoder** [comment]
@davidmoten Agreed.
