### ISSUE TITLE
FAIL_ON_NULL_FOR_PRIMITIVES should throw an exception on missing properties

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#446]
I am deserializing a constructor that takes multiple `@JsonProperty`s.

1. Due to a typo in a property name, one of the constructor arguments (an `int`) has no mapped value.
2. Jackson maps the missing value to `0`, instead of throwing an exception.
3. This is in spite of the fact that `DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES` is set.

**Comment by cowtowncoder** [comment]
As of Jackson 2.6, defining property as required will actually work for creator properties.
So I think this is semantically correct way to specify requirement.
