### ISSUE TITLE
Not able to run UAT for com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4

### ISSUE THREAD

**Issue by shivsrivastava** [FasterXML/jackson-databind#4466]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

I am trying to run UAT enabled for com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4 . I am using jdk 8 . 11, 17 with Maven .
I am executing mvn test command to run UT cases. But getting failed. Please let me know which is the correct version to be used.

### Version Information

com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4

### Reproduction

com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4

### Expected behavior

Pass

### Additional context

NA

**Comment by JooHyukKim** [comment]
Issues tab is used for bug reports and other project maintenance related tasks. Could you please transfer this to Discussions instead?

**Comment by cowtowncoder** [comment]
And 2.13.4 is an old version. And the module mentioned is one for different repo.
And there is nothing concrete....

@shivsrivastava What exactly are you trying to do here?

**Comment by shivsrivastava** [comment]
I have taken github code com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4 . That is required in my project , Now I want to build it with unit test cases passed. But build is successful but unit test is getting failed. 
I tried with jdk 8,11,17.

**Comment by shivsrivastava** [comment]
> I have taken github code com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4 . That is required in my project , Now I want to build it with unit test cases passed. But build is successful but unit test is getting failed.
> I tried with jdk 8,11,17.

I have taken github code com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4 . That is required in my project , Now I want to build it with unit test cases passed. But build is successful but unit test is getting failed.
I tried with jdk 8,11,17.

**Comment by shivsrivastava** [comment]
> And 2.13.4 is an old version. And the module mentioned is one for different repo. And there is nothing concrete....
> 
> @shivsrivastava What exactly are you trying to do here?

I have taken github code com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4 . That is required in my project , Now I want to build it with unit test cases passed. But build is successful but unit test is getting failed.
I tried with jdk 8,11,17.

**Comment by cowtowncoder** [comment]
@shivsrivastava Best of luck figuring this out: I do not have time or interest to trouble-shoot build issues with old versions as you do not even bother including relevant failure information.

**Comment by pjfanning** [comment]
This sort of GitHub beggars belief. If you has something stolen, you would go to the police and they would expect basic details like what was stolen, where and when it happened. How anyone can think they can report an issue about failing tests without naming the tests and providing stacktraces etc. - what OS they are using - etc. - makes the eyes roll.
