### ISSUE TITLE
ObjectMapper.registerSubtypes does not work as expected with subtypes

### ISSUE THREAD

**Issue by dirk-olmes** [FasterXML/jackson-databind#4479]
### Describe your Issue

I have a couple of Jackson-Annotated classes that are generated from an OpenAPI spec. I use the same set of classes on the sending and on the receiving side of my microservice infrastructure. On the receiving side I want to replace one of the classes with a subclass that has additional business methods implemented.

I can use SimpleModule.registerSubtypes() to instantiate the subclass just fine when I'm deserializing the object itself. Unfortunately, I have to deal with a reference to the class that I want to replace:

```
class Wrapper {
	Ref ref;
}

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = TypeA.class, name = "typeA"),
  @JsonSubTypes.Type(value = TypeB.class, name = "typeB"),
})
interface Ref {
}

class TypeA implements Ref {
}

class TypeB implements Ref {
}

class TypeBext extends TypeB {
	void additionalMethod() {}
}
```

What I'm trying to accomplish is that upon deserializing a "typeB" I'd like to instantiate a subclass of TypeB (TypeBext). Given that all the Jackson annotated classes are generated I'd like to stay away from adding extra annotations and just configure the deserializing ObjectMapper instead.
This works fine when I register the subclass with the module and deserialize the toplevel JSON:
```
	SimpleModule module = new SimpleModule();
	module.registerSubtypes(new NamedType(TypeBext.class, "typeB"));
	
	ObjectMapper mapper = new ObjectMapper();
	mapper.registerModule(module);
	
	String json = "{ \"type\": \"typeB" }";
	TypeB b = mapper.readValue(json, TypeB.class);
	// b is an instance of TypeBext
```

However, the scenario fails when I'm trying to deserialize the outer wrapper type:
```
	json = "{ \"ref\": { \"type\": \"typeB" } }";
	Wrapper w = mapper.readValue(json, Wrapper.class);
	// w.ref is an instance of TypeB instead of TypeBext as requested by the module
```

I would have expected that `registerSubtypes` works the same way regardless of deserializing a toplevel object or a reference.
I've been debugging around quite a bit now but I don't see the forest for the trees by now.

Is what I'm trying to do even possible with Jackson? If so, how?

**Comment by JooHyukKim** [comment]
If and only if top level deserialization works and wrapper doesn't, it sounds like be bug.

I tried reproduction, but none of the provided reproduction works at all. Please refer bottom for the full reproduction that simply fails with...

    com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "type" (class com.fasterxml.jackson.failing.RegisterSubType4479Test$TypeBext), not marked as ignorable (0 known properties: ])

... this error message 🤔. Some questions are...

- Does your configuration actually work?
- Or which Jackson version are you using? 
- Maybe provided mapper configuration does not match what is actually running?

```java
public class RegisterSubType4479Test {

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
    @JsonSubTypes({
            @JsonSubTypes.Type(value = TypeA.class, name = "typeA"),
            @JsonSubTypes.Type(value = TypeB.class, name = "typeB"),
    })
    static interface Ref { }
    static class TypeA implements Ref { }
    static class TypeB implements Ref { }

    static class TypeBext extends TypeB {
        void additionalMethod() {}
    }

    @Test
    public void topLevelDeserializationTest() throws Exception {
        SimpleModule module = new SimpleModule();
        module.registerSubtypes(new NamedType(TypeBext.class, "typeB"));
        ObjectMapper mapper = JsonMapper.builder().build()
                .registerModule(module);

        Ref b = mapper.readValue("{ \"type\": \"typeB\"}", Ref.class);

        // b is an instance of TypeBext
        Assertions.assertInstanceOf(TypeBext.class, b);
    }
}
```

**Comment by cowtowncoder** [comment]
Agreed: description sounds like a bug, but a reproduction that works is needed.

**Comment by dirk-olmes** [comment]
Sorry for the false alarm, everything works as expected. By examining your reproducer I was forced to have a look again at my (more complicated) test and spotted a few bugs that made the test fail. Now that I'm using the correct subclasses everything works on my end.

**Comment by cowtowncoder** [comment]
Great! Thank you for the follow-up @dirk-olmes .
