### ISSUE TITLE
Re-Enable default values for text nodes

### ISSUE THREAD

**Issue by henning-meinhardt** [FasterXML/jackson-databind#4496]
### Is your feature request related to a problem? Please describe.

Starting with Jackson databind 2.17 the method `JsonNode.asText(String defaultValue)` was deprecated without giving an advice how to fill the missing functionality. In #463 you added the possibility to return a default value when querying a missing text node like so:
```
JsonNode someNode = ..... // for example an empty node {}
String value = someNode.path ("property").asText ("defaultValue");
```
When property `property` was not present, value was set to `defaultValue`. According to the deprecation comment this method should not be used any longer. But there is no advice how to implement the use case "go with a default value when the property in question is not defined" in an adequately short manner. At least I could not find any useful replacement around the JsonNode class. Is there something I missed?

### Describe the solution you'd like

I would like you to rethink the deprecation or provide an easy replacement (in one statement) for getting a text property value or a fallback when missing.

I also just commented on #463 giving the workarounds I came up so far, both much too complicated compared to the existing method. There I also tried to explain why the given reason for deprecation doesn't seem valid to me.

**Comment by JooHyukKim** [comment]
Similar to #4471

**Comment by henning-meinhardt** [comment]
@JooHyukKim exactly, thanks for pointing that out, didn't find that ticket

**Comment by JooHyukKim** [comment]
> I would like you to rethink the deprecation or provide an easy replacement

Kinda valid point.

Also, as per JavaDoc..

```java
     * NOTE: deprecated since 2.17 because {@link #asText()} very rarely returns
     * {@code null} for any node types -- in fact, neither {@link MissingNode}
     * nor {@code NullNode} return {@code null} from {@link #asText()}.
```
... it was deprecated for the code path being dead cold, but un-deprecation requests tell otherwise. 🤔

**Comment by cowtowncoder** [comment]
@henning-meinhardt Did you not actually try to search for an existing issue? The very previous open one, #4471 covers this. So let's discuss there; closing this as duplicate.
