### ISSUE TITLE
RecyclerPool Memory leak in 2.17.0

### ISSUE THREAD

**Issue by jkuhn1** [FasterXML/jackson-databind#4500]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

I discovered a memory leak while performing performance test in a multi threaded environment. This seems to be due to the switch to the `LockFreePool` introduced in 2.17.0.

I'm not sure whether this is a bug or misusage also it clearly looks like a bug considering that the behaviour is degraded compared to 2.16.2 but please advice what would be a proper usage.

### Version Information

2.17.0

### Reproduction

In order to reproduce the leak, I created a simple program that starts 16 threads that all serialize a simple object multiple times using a common ObjectMapper instance which is thread safe as per documentation.

```java
package com.example.jackson.leak;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class Main {
	
	private static final ExecutorService EXECUTOR = Executors.newFixedThreadPool(16);
	
	private static final ObjectMapper MAPPER = new ObjectMapper();
	
	public static void main(String[] args) throws Exception {
		List<Worker> tasks = new ArrayList<Worker>();
		for(int i=0;i<16;i++) {
			tasks.add(new Worker());
		}
		
		EXECUTOR.invokeAll(tasks);
		
		System.in.read();
	}
	
	public static class Message {
		
		private final String message;

		public Message(String message) {
			this.message = message;
		}

		public String getMessage() {
			return message;
		}
	}
	
	public static class Worker implements Callable<Void> {

		public Void call() {
			System.out.println("Start " + Thread.currentThread().getName());
			try {
				for(int i=0;i<150000;i++) {
					MAPPER.writeValueAsBytes(new Message("Hello world"));
				}
			}
			catch(JsonProcessingException e) {
				e.printStackTrace();
			}
			System.out.println("End " + Thread.currentThread().getName());
			return null;
		}
	}
}
``` 

Using JConsole to monitor the heap I could see that the memory is stuck around 800MB (after GC):

![image](https://github.com/FasterXML/jackson-databind/assets/4090888/cb4c7421-5318-4f78-a4d6-2277e8dd3382)

The heap dump speaks for itself:

![image](https://github.com/FasterXML/jackson-databind/assets/4090888/b1f58c7b-072e-4729-94b8-a3d91a88bd1c)

![image](https://github.com/FasterXML/jackson-databind/assets/4090888/032b936c-aa96-48b3-94c3-ec151affd0ff)

### Expected behavior

I expect the tasks to complete and the heap consumption to get back to normal. The same application run with 2.16.2 terminates with a heap around 9MB after GC.

### Additional context

I run the app with OpenJDK 21.0.2

**Comment by pjfanning** [comment]
This is a known issue. I only have my phone at the moment but if you search around, you'll see that this pool is not working well. Stick with Jackson 2.16 or override the recycler pool to use the thread local one. 2.17.1 goes back to that pool as the default.

**Comment by jkuhn1** [comment]
Thanks!

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson-module-scala/issues/672

**Comment by cowtowncoder** [comment]
Sort of dup of https://github.com/FasterXML/jackson-core/issues/1260 as well -- by now issue that we are fully aware of, and 2.17.1 having patch (to revert situation to 2.16.x) stage. But still trying to figure out some of details to know path for 2.18+ and 3.0.
(others may feel differently but I think there are still gaps in understanding).

**Comment by cowtowncoder** [comment]
@jkuhn1 One interesting note: this is specifically about serialization -- I wrote a similar tool to reproduce, but combined reads and writes. But I am beginning to feel that this might be more about just serialization (writer) side. Would it be easy enough for you to see if fast (small) reads only would trigger this issue? (I'll modify my own test once I return home, travelling now).

**Comment by pjfanning** [comment]
https://jmh.morethan.io/?sources=https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/gh-pages/jdk-17-t16.json,https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/gh-pages-jackson-recycler/jdk-17-t16.json

Shows that reading and writing are affected.

**Comment by cowtowncoder** [comment]
Ok, I was specifically curious on whether "extreme memory retention" would occur for both -- vs. in general more overhead. It would make most sense for both to be heavily affected, and possibly trigger the same imbalancing problem.

**Comment by cowtowncoder** [comment]
Default `RecyclerPool` implementation changed in 2.17.1 (via https://github.com/FasterXML/jackson-core/issues//1256) -- will default to ThreadLocal-backed pool for 2.17 and 2.18 at least, possibly all of 2.x.
But specifically, will not use "LockFreePool" that was shown to have occasional degenerate behavior.
