### ISSUE TITLE
Incompatible Constructor Parameter Type in `EnumDeserializer`

### ISSUE THREAD

**Issue by Hunter-Lam** [FasterXML/jackson-databind#4581]
### Code Link
https://github.com/FasterXML/jackson-databind/blob/9af381db56ad241f6fe14b3ae6ddcad26d8e3c11/src/main/java/com/fasterxml/jackson/databind/deser/std/EnumDeserializer.java#L110

### Description
Type of `caseInsensitive` should be `Boolean` instead of `boolean`. Otherwise, when using contructors without `caseInsensitive`, e.g. `EnumDeserializer(com.fasterxml.jackson.databind.util.EnumResolver)`, will cause `NullPointerException`.

### Version Information
since 2.15.0

### Exception Related to 2.15.4 Version
```shell
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "caseInsensitive" is null
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.<init>(EnumDeserializer.java:82)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.<init>(EnumDeserializer.java:131)
...
```

**Comment by cowtowncoder** [comment]
Ok I see what you mean; there is a sub-optimal mix of primitive and wrapper: ideally it'd actually be `boolean` (primitive), I think.

Regardless I cannot simply change type as signature change is compatibility breaking, but I can easily add handling of `null`s where applicable.

I will merge fix in 2.15 but it is unlikely there will be new 2.15 releases; so fix will be released first either in 2.16(.3) or 2.17(.2).
