### ISSUE TITLE
Allow deserialisation of unwrapped and nested objects for the same property

### ISSUE THREAD

**Issue by mathiasarens** [FasterXML/jackson-databind#4623]
### Is your feature request related to a problem? Please describe.

An application (MS CRM: OData vs. FetchXML queries) returns nested objects as nested or unwrapped objects depending on query parameters. 
This is an nested property example:
````json
{
  "name":"John",
  "address":{
    "street":"Main Street",
    "city":"New York"
  }
}
````
This is an example with an unwrapped inner object:
````json
{
  "name":"John",
  "address.street":"Main Street",
  "address.city":"New York"
}
````
These are my two Java classes I would like to use to map both json examples:

````java
public class Person {
    private String name;
    private Address address;

    public void setName(String name) {
        this.name = name;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public String getName() {
        return name;
    }

    public Address getAddress() {
        return address;
    }
}

public class Address {
    private String street;
    private String city;

    public void setStreet(String street) {
        this.street = street;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return street;
    }

    public String getCity() {
        return city;
    }
}
````

### Describe the solution you'd like

I would like to use the same Java entities in both cases. Unfortunately this is not possible. Nested objects are supported by default. If I add an \@JsonUnwrapped(prefix="address.") to the address property of the person class it only supports the unwrapped json but I cannot deserialize the json with an nested object.

### Usage example

This is a simple test I would like to have both tests pass:

````java
class DeserializeNestedAndUnwrappedAddressTest {

    @Test
    void deserializeNestedAddress() throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();
        String json = "{\"name\":\"John\",\"address\":{\"street\":\"Main Street\",\"city\":\"New York\"}}";
        Person person = objectMapper.readValue(json, Person.class);
        assertEquals("John", person.getName());
        assertEquals("Main Street", person.getAddress().getStreet());
        assertEquals("New York", person.getAddress().getCity());
    }

    @Test
    void deserializeUnwrappedAddress() throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();
        String json = "{\"name\":\"John\",\"address.street\":\"Main Street\",\"address.city\":\"New York\"}";
        Person person = objectMapper.readValue(json, Person.class);
        assertEquals("John", person.getName());
        assertEquals("Main Street", person.getAddress().getStreet());
        assertEquals("New York", person.getAddress().getCity());
    }
````
I can make one of the tests work by either adding or removing the \@JsonUnwrapped(prefix="address.") annotation at the Person.address attribute. But I would favor a solution in which both test cases work without modifying the code.

````java
public class Person {
    private String name;
    // comment @JsonUnwrapped to make the deserializeNestedAddress test pass
    @JsonUnwrapped(prefix="address.")
    private Address address;

````
Why does the \@JsonUnwrapped annotation stop the nested deserialization doing its job? Alernatively, is there an alternative solution available?

**Comment by mathiasarens** [comment]
Here is a zip file with a maven project with the tests and the java entities:
[example.zip](https://github.com/user-attachments/files/16280959/example.zip)

**Comment by mathiasarens** [comment]
Okay, I think my feature request is not valid. If you tag an attribute with \@JsonUnwrapped(prefix="address.") then it will only load unwrapped properties into the property. One of the objects is empty because only one of the types were given.

If you would start to allow what I would like to see, you would get into trouble and need to define a hierarchy in the annotation processing. Because you can also have jsons like this:

````json
{
  "name":"John",
  "address":{
    "street":"Main Street",
    "city":"New York"
  }
  "address.street": "Main Street2",
  "address.city": "New York2"
}
````
Then you would not know which property to take.
So I will close this feature request.

**Comment by cowtowncoder** [comment]
I agree with your analysis, @mathiasarens .
