### ISSUE TITLE
`@JsonIgnore` on Record property ignored for deserialization, if there is getter override

### ISSUE THREAD

**Issue by yihtserns** [FasterXML/jackson-databind#4626]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

`@JsonIgnore` on a Record component is ignored when the corresponding accessor method is overridden.

### Version Information

Since `2.15.0`.

### Reproduction

```java
record RecordWithJsonIgnore(int id, @JsonIgnore String name) {
    @Override
    public String name() {
        return name;
    }
}

RecordWithJsonIgnore deser = new ObjectMapper().readValue("{\"id\":123,\"name\":\"Bob\"}", RecordWithJsonIgnore.class);

// failed with:
// org.opentest4j.AssertionFailedError: 
// Expected :RecordWithJsonIgnore[id=123, name=null]
// Actual   :RecordWithJsonIgnore[id=123, name=Bob]
assertEquals(new RecordWithJsonIgnore(123, null), deser);
```

### Additional context

There are typically 3 places to get an annotation info from:
<table>
<thead>
<tr>
  <th>Where</th>
  <th>For this scenario</th>
</tr>
</thead>
<tbody>
<tr>
<td>Constructor parameter</td>
<td>Can't have <code>@JsonIgnore</code> info because <code>@JsonIgnore</code>'s <code>@Target</code> does not include <code>ElementType.PARAMETER</code> <strong>UPDATE</strong>: Forgot to mention that the hardcoded <code>prop.addCtor(..., false)</code> in <code>POJOPropertiesCollector</code> also needs to be changed for this to work.</td>
</tr>
<tr>
<td>Accessor method</td>
<td>When overridden, <code>@JsonIgnore</code> will not be "inherited" from original method</td>
</tr>
<tr>
<td>Field</td>
<td>#3737 removed field info for deserialization, so it can't contribute the <code>@JsonIgnore</code> info</td>
</tr>
</tbody>
</table>

**Comment by cowtowncoder** [comment]
Sidenote: created https://github.com/FasterXML/jackson-annotations/issues/258 to allow `@JsonIgnore` on constructor parameters (regardless of what happens here)
