### ISSUE TITLE
Enable default values for text nodes

### ISSUE THREAD

**Issue by ccleve** [FasterXML/jackson-databind#463]
When a JsonNode contains an integer or boolean, there's a nice option to specify a default value:

int myInt = myNode.asInt(defaultValue);

This doesn't exist for text nodes. It would be nice to have this:

String myString = myNode.asText("a default value here");

**Comment by henning-meinhardt** [comment]
Hi, bitt late to the party but anyway: after upgrading to the latest Jackson databind release I noticed a deprecation warning when using `.asText (defaultValue)` but don't really understand the explanation given in the java doc:

```
    /**
     * Method similar to {@link #asText()}, except that it will return
     * <code>defaultValue</code> in cases where null value would be returned;
     * either for missing nodes (trying to access missing property, or element
     * at invalid item for array) or explicit nulls.
     *<p>
     * NOTE: deprecated since 2.17 because {@link #asText()} very rarely returns
     * {@code null} for any node types -- in fact, neither {@link MissingNode}
     * nor {@code NullNode} return {@code null} from {@link #asText()}.
     *
     * @since 2.4
     *
     * @deprecated Since 2.17, to be removed from 3.0
     */
    @Deprecated // @since 2.17
    public String asText(String defaultValue) {
```
It says that almost no node type did ever return `null` so the `== null` comparison was meaningless most of the time. That might be right but doesn't legitimate the deprecation. `MissingNode` subclass overwrites `asText (defaultValue)` as follows:
```
@Override public String asText(String defaultValue) { return defaultValue; }
```
So the `== null` check is actually not involved and a MissingNode always returned the specified default value.
So I could use something like this to default a missing node to a meaningful default value:
```
JsonNode node = ... {} // an empty node {} for example
String value = node.path ("property").asText ("default value");
```
That returned "default value" for an empty JsonNode.
Now that its deprecated I would have to write more complicated code (or there is a shorter replacement that is unfortunately not mentioned in the deprecation comment):
```
JsonNode node = ... {} // an empty node {} for example
String value = node.path ("property").getText ();
if (value == null)
    value = "defaultValue";
```
or
```
JsonNode node = ... {} // an empty node {} for example
JSonNode propertyNode = node.path ("property");
String value = propertyNode.isMissingNode () ? "defaultValue" : propertyNode.getText();
```

I have two questions:
1. Is there a simpler workaround for the now missing defaultValue feature?
2. Why did you deprecate `asText(defaultValue)` but left `asInt(defaultValue)`, `asLong(defaultValue)` and so on?

**Comment by cowtowncoder** [comment]
Follow-up discussion on #4471.
