### ISSUE TITLE
setSerializationInclusion(JsonInclude.Include.NON_EMPTY doesn't filter empty values from collections

### ISSUE THREAD

**Issue by Gems** [FasterXML/jackson-databind#4640]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Empty Map values in collections don't get filtered out.

### Version Information

2.17.2

### Reproduction

Here is code for the corresponding unit test:
```java
    final var objectMapper = new ObjectMapper()
        .setSerializationInclusion(JsonInclude.Include.NON_EMPTY);

    final var payload = Map.of(
        "key", "value",
        "empty", Map.of(),
        "list", List.of(
            Map.of("key", "value"),
            Map.of(),
            Map.of(),
            Map.of("key", "value")));

    final var json = objectMapper.writeValueAsString(payload);
    final var deserialized = (Map<?,?>) objectMapper.readValue(json, Map.class);

    final var expected = Map.of(
        "key", "value",
        "list", List.of(
            Map.of("key", "value"),
            Map.of("key", "value")));

    assertThat(deserialized)
        .isEqualTo(expected);
``` 

### Expected behavior

It's expected that the test would pass.

**Comment by yawkat** [comment]
I believe JsonInclude only applies to beans and maps.

**Comment by cowtowncoder** [comment]
Kind of: It does apply to `Collection`s wrt "simple" empty case, but it does not filter elements. So only ones with `Collection.isEmpty()` are filtered out, but not ones where there are elements that would be considered empty.

**Comment by Gems** [comment]
Yeah, I noticed it. But I don't think that it's expected behavior that comes to ones mind when then learn about the "non_empty" option.

I pathed the `SerializerFactory` to make it to produce a `CollectionSerializer` implented the same way the `MapSerializer` is implemented. Works well. 

I believe it could be a more straightforward behavior having empty collection/array items filtered out in case of the "non_empty" option is provided.

**Comment by cowtowncoder** [comment]
Changing this behavior would be major backwards-compatibility problem tho.
And conceptually skipping is only for properties (of POJOs, Maps), not for elements (of Collections, arrays).

So while I understand why it's confusing, I don't think this is something I want to change.

**Comment by Gems** [comment]
No problem. I have my workaround implemented and it solves the problem we have.

Feel free to close the issue. 

I'd usggest though leaving it open for comments, so I can share a relevant solution should anyone else stumble upon the same issue.

Cheers,
Ed

**Comment by cowtowncoder** [comment]
Will leave open for bit, close in future -- closed issued should be googlable still.
