### ISSUE TITLE
Remove use of global static `TypeFactory` singleton from 3.0

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#4659]
### Describe your Issue

(note: offshoot of https://github.com/FasterXML/jackson-core/issues/1321)

Unlike all other caches, cache for the default instance of `TypeFactory` is not bound to one specific `ObjectMapper` and can therefore lead to unintended Class retention.
This should not happen: each `ObjectMapper` should have its own `TypeFactory` instead of global singleton.

Change is probably not possible for 2.x but should be doable for 3.0.

**Comment by cowtowncoder** [comment]
Did refactor 2.x code to reduce usage of `TypeFactory.defaultInstance()` but the actual removal has to go in 3.0.

**Comment by dylan-tao** [comment]
> ### Describe your Issue
> (note: offshoot of [FasterXML/jackson-core#1321](https://github.com/FasterXML/jackson-core/issues/1321))
> 
> Unlike all other caches, cache for the default instance of `TypeFactory` is not bound to one specific `ObjectMapper` and can therefore lead to unintended Class retention. This should not happen: each `ObjectMapper` should have its own `TypeFactory` instead of global singleton.
> 
> Change is probably not possible for 2.x but should be doable for 3.0.

Great！
