### ISSUE TITLE
Jackson ignores Type information when raw return type is BigDecimal or BigInteger

### ISSUE THREAD

**Issue by brianv0** [FasterXML/jackson-databind#466]
Hi,

I'm unable to get Jackson to specified type information in JSON, both when registered via the ```@JsonTypeName``` annotation on a class I'm interested in serializing, and with the ```@JsonSubTypes``` annotation on a method in a composite class which contains the class I'm interested in serializing. This fails in a few different versions of Jackson for me. I'm not sure if I'm missing some sort of configuration somewhere or what, so I've included a gist reproducing the issue:

https://gist.github.com/brianv0/0dc42b7bd45b7a7b384e

In summary, what I get when serializing a BigDecimal, a java.lang.Integer, and a java.lang.String, where all classes have been annotated as subtypes of types decimal, integer, and string:
```
{"$type":"MetadataView","metadata":
   [{"key":"hello_decimal","value":1234.4321,"$type":"BigDecimal"},
   {"key":"hello_integer","value":1234,"$type":"integer"},
   {"key":"hello_string","value":"world","$type":"string"}]
}
```

What I'd like:
```
{"$type":"MetadataView","metadata":
   [{"key":"hello_decimal","value":1234.4321,"$type":"decimal"},
   {"key":"hello_integer","value":1234,"$type":"integer"},
   {"key":"hello_string","value":"world","$type":"string"}]
}
```

**Comment by cowtowncoder** [comment]
Somewhat surprisingly, this is now fixed: suspecting this is due to #1385 fix.
