### ISSUE TITLE
ObjectMapper convertValue does not check if the value is already of target type

### ISSUE THREAD

**Issue by lorenzbaier** [FasterXML/jackson-databind#4661]
Why does `objectMapper.convertValue`  not check if the object already has the desired target type and then return the object immediatly.

https://github.com/FasterXML/jackson-databind/blob/5e0dedaea766bf1fd94ffac449c6b1cfea7dfd46/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L4602

When converting a class which has a recursive getter of some form, I expect to get the object back immediatly if it has the correct type to begin with.
```java
@Test
  void testConvertRecursive() {
    var convertedTp = new ObjectMapper().convertValue(new Recursive(), Recursive.class);
    assertNotNull(convertedTp);
  }

  public record Recursive(String name) {
    Recursive() {
      this("test");
    }

    public Recursive getSelf() {
      return new Recursive();
    }
  }
```
Instead I get: `Infinite recursion (StackOverflowError) (through reference chain:....`

**Comment by cowtowncoder** [comment]
Have a look at method definition (https://github.com/FasterXML/jackson-databind/blob/5e0dedaea766bf1fd94ffac449c6b1cfea7dfd46/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L4541); there's some notes on why short-cut is not taken -- this used to be the behavior, but it is problematic for true conversion case where behavior between "proper" conversion (serialize-then-deserialize) and "fake" one (omit doing anything if type is already expected).

Issue for change in 2.10 was this:

https://github.com/FasterXML/jackson-databind/issues/2220

**Comment by yawkat** [comment]
Instead of `mapper.convertValue(x, T.class)`, callers can just do `if (!(x instanceof T)) mapper.convertValue(x, T.class)`.

**Comment by lorenzbaier** [comment]
sure the "first" level is not a problem, but what if the object is deeper down in the hierarchy?

**Comment by lorenzbaier** [comment]
Okay thanks for the info, I will look into a more specific solution that fits my use case.
