### ISSUE TITLE
Add `UpperCamelCase` naming strategy to `EnumNamingStrategies`

### ISSUE THREAD

**Issue by lbenedetto** [FasterXML/jackson-databind#4663]
### Is your feature request related to a problem? Please describe.

Some APIs I deal with use UpperCamelCase naming strategy for Enums. I can provide my own custom implementation of EnumNamingStrategy, but this is annoying.

### Describe the solution you'd like

It would be nice if EnumNamingStrategy provided an UpperCamelCase strategy in addition to the lowerCamelCase strategy it currently provides. 

This aligns more closely with PropertyNamingStrategy, which provides many common naming strategies, including UpperCamelCase and lowerCamelCase

### Usage example

`@EnumNaming(EnumNamingStrategies.UpperCamelCaseStrategy.class)`

### Additional context

I have provided an implementation pull request here
https://github.com/FasterXML/jackson-databind/pull/4660

**Comment by cowtowncoder** [comment]
Was hoping for a new PR, as this is a good addition. But will probably not be able to get it merged in 2.18.0 due to imminent 2.18.0-rc1 release. May go in 2.19 branch when that opens.

**Comment by lbenedetto** [comment]
I'll open a new PR when I find some time.

**Comment by cowtowncoder** [comment]
Sounds good, no rush.

Depending on timing, can still do it against 2.18 -- whatever is the latest open 2.x branch at the time.

**Comment by cowtowncoder** [comment]
While technically earlier, will close as dup in favor of #4676 to keep release notes simple.
