### ISSUE TITLE
Change `EnumNamingStrategy.convertEnumToExternalName()` to take `MapperConfig` argument

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#4664]
### Describe your Issue

For some reason there is an oversight in `EnumNamingStrategy` such that configuration is not passed to it. We should fix that for 3.0 (cannot change due to compatibility requirements in 2.x).

**Comment by yihtserns** [comment]
I wonder if it wasn't a method parameter because any custom implementation can get it here if they need it:
```
class SomeCustomAnnotationIntrospector extends NopAnnotationIntrospector {

   public Object findEnumNamingStrategy(MapperConfig<?> config, 
                                                                    AnnotatedClass ac) {

      return new CustomEnumNamingStrategy(config);
   }
}
```
🤔
