### ISSUE TITLE
Allow setting global enum naming strategy similar to property naming strategy

### ISSUE THREAD

**Issue by hajdamak** [FasterXML/jackson-databind#4674]
### Is your feature request related to a problem? Please describe.

- Currently you have to annotate all enums with `EnumNaming` in order to change default enum naming strategy which is cumbersome and verbose.

### Describe the solution you'd like

It should be possible to set default enum naming strategy directly on `ObjectMapper`.

### Usage example

`ojbectMapper.setEnumNamingStrategy(EnumNamingStrategies.CAMEL_CASE)`

**Comment by cowtowncoder** [comment]
Sounds reasonable. PR would be most welcome.
