### ISSUE TITLE
Support other enum naming strategies than camelCase

### ISSUE THREAD

**Issue by hajdamak** [FasterXML/jackson-databind#4676]
### Is your feature request related to a problem? Please describe.

Currently `EnumNamingStrategies` contains only camelCase strategy. Some API guidelines require other strategies like `snake_case` or `UPPER_SNAKE_CASE`.

### Describe the solution you'd like

`EnumNamingStrategies` should support other strategies like for example `snake_case` or `UPPER_SNAKE_CASE`.

**Comment by cowtowncoder** [comment]
Would be provided by #4660 which works but needs some refactoring wrt code reuse.

**Comment by cowtowncoder** [comment]
Fixed via #4728 will be in 2.19.0.
