### ISSUE TITLE
Support for generic factory method for TypeReference.

### ISSUE THREAD

**Issue by andirady** [FasterXML/jackson-databind#4677]
### Is your feature request related to a problem? Please describe.

Currently, to instantiate a `TypeReference` you'd have to create an anonymous sub-class, e.g.:
```java
TypeReference<?> ref = new TypeReference<Map<String, Object>>() {};
```
The `{}` is annoying because without special formatting, the IDE might format the code as follows:
```java
TypeReference<?> ref = new TypeReference<Map<String, Object>>() {
}; // IDE puts the closing braces in a new line.
```

### Describe the solution you'd like

Provide a generic static factory method called `of` to construct the `TypeReference`, which is similar to modern java factory methods for collection classes, e.g. `List.of()`, `Map.of()`.

### Usage example

```java
Map<String, Object> personAsMap = objectMapper.convertValue(person, TypeReference.<Map<String, Object>>of());
// which also can be shorten as
Map<String, Object> personAsMap = objectMapper.convertValue(person, TypeReference.of());
```

**Comment by yawkat** [comment]
It's not possible due to type erasure.

**Comment by andirady** [comment]
> It's not possible due to type erasure.

I have a working implementation for the samples above, but I'm not sure about the type erasure. Can you provide a use case?

**Comment by yawkat** [comment]
The case you test would also work simply with List.class, you don't need TypeReference. It's the more complicated types that fail

**Comment by andirady** [comment]
> The case you test would also work simply with List.class, you don't need TypeReference. It's the more complicated types that fail

It works, but it will give `Unchecked` warning. Some teams may require the code to have no warning.

**Comment by yawkat** [comment]
Look. There's a good reason why there's an unchecked warning if you use `.class`: The conversion is unchecked. The List may contain types that don't match the type parameter, so you may get weird class cast exceptions.

Now try it with your proposal:

```java
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.List;

public class X {
    public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();
        Integer i = mapper.readValue("[\"foo\"]", new TypeReference<List<Integer>>() {}).get(0);
        //Integer i = mapper.readValue("[\"foo\"]", X.<List<Integer>>of()).get(0);
        System.out.println(i);
    }

    public static <T> TypeReference<T> of() {
        return new TypeReference<T>() {};
    }
}
```

With the original TypeReference approach, you will see a `com.fasterxml.jackson.databind.exc.InvalidFormatException`, which is the correct behavior. With your proposal, there is a `java.lang.ClassCastException` instead. This is because your proposal has a hidden unchecked assignment. There may not be a compiler warning, but it's still there.

This is the technical reason why TypeReference requires an anonymous class. It is a fundamental limitation of Java. There is no workaround like you propose.

**Comment by andirady** [comment]
> Look. There's a good reason why there's an unchecked warning if you use `.class`: The conversion is unchecked. The List may contain types that don't match the type parameter, so you may get weird class cast exceptions.
> 
> Now try it with your proposal:
> 
> ```java
> import com.fasterxml.jackson.core.JsonProcessingException;
> import com.fasterxml.jackson.core.type.TypeReference;
> import com.fasterxml.jackson.databind.ObjectMapper;
> 
> import java.util.List;
> 
> public class X {
>     public static void main(String[] args) throws JsonProcessingException {
>         ObjectMapper mapper = new ObjectMapper();
>         Integer i = mapper.readValue("[\"foo\"]", new TypeReference<List<Integer>>() {}).get(0);
>         //Integer i = mapper.readValue("[\"foo\"]", X.<List<Integer>>of()).get(0);
>         System.out.println(i);
>     }
> 
>     public static <T> TypeReference<T> of() {
>         return new TypeReference<T>() {};
>     }
> }
> ```
> 
> With the original TypeReference approach, you will see a `com.fasterxml.jackson.databind.exc.InvalidFormatException`, which is the correct behavior. With your proposal, there is a `java.lang.ClassCastException` instead. This is because your proposal has a hidden unchecked assignment. There may not be a compiler warning, but it's still there.
> 
> This is the technical reason why TypeReference requires an anonymous class. It is a fundamental limitation of Java. There is no workaround like you propose.

Okay, I get it already. Thanks for the explanation. It's not possible with any sort of factory methods.
