### ISSUE TITLE
Deserializer fails with the function readerWithView()

### ISSUE THREAD

**Issue by cooperlyt** [FasterXML/jackson-databind#4748]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Use function  readerWithView()  Deserializer a Object  fails
I created a [test project](https://github.com/cooperlyt/jackson-bug-test/blob/master/java-test/src/test/java/json/JsonTest.java) 
```java
@ExtendWith({SpringExtension.class})
@SpringBootTest(classes = Main.class)
public class JsonTest {

  @Autowired
  private  ObjectMapper objectMapper;

  static class SimpleStockFreezeStatusMessage {

    private Long businessId;
    private Boolean success;
    private String tenantId;

   // getter and setter  ...
  }

  @Test
  public void testSpringJsonMessage() throws IOException {
    var json = "{\"businessId\":1336504106360835,\"tenantId\":\"first\",\"success\":false}";
    var value = objectMapper.readValue(json, SimpleStockFreezeStatusMessage.class);

    System.out.println("message ser by readValue : " + value.tenantId);

    // success
    assertEquals(value.tenantId, "first");

    Class<?> view = SimpleStockFreezeStatusMessage.class;
    JavaType javaType = objectMapper.constructType(new  TypeReference<SimpleStockFreezeStatusMessage>() {});

    //this is Spring message Usage
    var value2 = (SimpleStockFreezeStatusMessage)objectMapper.readerWithView(view).forType(javaType).readValue(json);

    System.out.println("message ser by readerWithView: " + value2.tenantId);

    // tenantId is null
    assertEquals(value2.tenantId, "first");
  }
}

```

value2 all property is Null

### Version Information

 2.17.2 and 2.18.0

### Reproduction

Download my test project run test or follow my code

**Comment by JooHyukKim** [comment]
How exactly does it fail? Like ...

- Does it throw exception? If so, could you share stack trace also? Or
- Is the result unexpected? Then again how exactly does result show? How different from expected behavior?

**Comment by cooperlyt** [comment]
> How exactly does it fail? Like ...
> 
> * Does it throw exception? If so, could you share stack trace also? Or
> * Is the result unexpected? Then again how exactly does result show? How different from expected behavior?
value2 all property is Null

**Comment by cooperlyt** [comment]
I made some changes to my test and found that if I run it with the default configuration, there is no error. However, if I use the ObjectMapper from the Spring context, it fails. I’m struggling to review the Spring Boot JacksonAutoConfiguration to figure out which settings are causing the serialization to fail.

```java

  public void testSpringJsonMessage(ObjectMapper objectMapper) throws IOException {
    var json = "{\"businessId\":1336504106360835,\"tenantId\":\"first\",\"success\":false}";
    var value = objectMapper.readValue(json, SimpleStockFreezeStatusMessage.class);

    System.out.println("message ser by readValue : " + value.tenantId);

    assertEquals(value.tenantId, "first");

    Class<?> view = SimpleStockFreezeStatusMessage.class;
    JavaType javaType = objectMapper.constructType(new  TypeReference<SimpleStockFreezeStatusMessage>() {});

    //this is Spring message Usage
    var value2 = (SimpleStockFreezeStatusMessage)objectMapper.readerWithView(view).forType(javaType).readValue(json);

    System.out.println("message ser by readerWithView: " + value2.tenantId);

    assertEquals(value2.tenantId, "first");
  }

  @Test
  //success
  public void testByDefaultMapper() throws IOException {
    testSpringJsonMessage(new ObjectMapper());
  }

  @Test
  // fail
  public void testBySpringMapper() throws IOException {
    testSpringJsonMessage(objectMapper);
  }

```

**Comment by JooHyukKim** [comment]
> I made some changes to my test and found that if I run it with the default configuration, there is no error. However, if I use the ObjectMapper from the Spring context, it fails

I should've probably asked that first.
Now you need to consult Spring community, probably there is API/configuration endpoint or sorts to customize Jackson config.

**Comment by cooperlyt** [comment]
I printed the settings of the ObjectMapper in the Spring context and reconfigured an ObjectMapper() according to those results, but the error still did not occur. Did I miss any other settings?
```java
    System.out.println("Registered modules: " + objectMapper.getRegisteredModuleIds());
    System.out.println("Deserialization features: ");
    for (DeserializationFeature feature : DeserializationFeature.values()) {
      boolean isEnabled = objectMapper.getDeserializationConfig().isEnabled(feature);
      System.out.println(feature + ": " + isEnabled);
    }

    System.out.println("Serialization features: ");
    for (SerializationFeature feature : SerializationFeature.values()) {
      boolean isEnabled = objectMapper.getSerializationConfig().isEnabled(feature);
      System.out.println(feature + ": " + isEnabled);
    }
```

```java
  @Test
  public void testMockSpringMapper() throws IOException {
    var ob = new ObjectMapper();
    ob.registerModule(new Jdk8Module());
    ob.registerModule(new ParameterNamesModule());
    ob.registerModule(new JSR310Module());
    ob.registerModule(new JsonMixinModule());
    ob.registerModule(new JsonComponentModule());

    ob = ob.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    ob = ob.configure(WRITE_DATES_AS_TIMESTAMPS, false);
    ob = ob.configure(WRITE_DURATIONS_AS_TIMESTAMPS, false);
    testSpringJsonMessage(ob);
  }
```

**Comment by JooHyukKim** [comment]
How about compare all configurations and see difference one by one and figure out?

**Comment by cooperlyt** [comment]
I found the configuration. After adding ob = ob.configure(MapperFeature.DEFAULT_VIEW_INCLUSION, false);, the test fails.

**Comment by JooHyukKim** [comment]
Wrong configuration I suppose? You did not configure any "view" on target POJO.

Just use `.readValue(JSON, Xxxx.class)` then you will be fine.

**Comment by cooperlyt** [comment]
But I configured the 'view', which is the usage method in Spring Messaging, because its target view and class are dynamically retrieved.
```java
    Class<?> view = SimpleStockFreezeStatusMessage.class;
    JavaType javaType = objectMapper.constructType(new  TypeReference<SimpleStockFreezeStatusMessage>() {});

    //this is Spring message Usage
    var value2 = (SimpleStockFreezeStatusMessage)objectMapper.readerWithView(view).forType(javaType).readValue(json);
```

**Comment by JooHyukKim** [comment]
See documentation of `MapperFeature.DEFAULT_VIEW_INCLUSION`, it explains why mapper is behaving such.

<img width="691" alt="image" src="https://github.com/user-attachments/assets/7d04f38f-7c0f-4a13-8ffc-3906a7aba8ce">

**Comment by cowtowncoder** [comment]
readerWithView(view) does not configure any view, it just creates a reader for a class's view.

This is not really true: `readerWithView()` will create `ObjectReader` with view to use.
Or maybe I misread the comment.

I added "need-test-case" since although issue contains almost complete implementation, `ObjectMapper` configuration is not included. But following discussion seems to have settings, so maybe just edit the original description to be stand-alone test, @cooperlyt ?

I see a link but it'd really be nicer to have code inline here, if possible. Not a complete project, nothing just unit test class (or just test method). Those are easier to read through and add to existing test suite.

**Comment by cooperlyt** [comment]
There is [Complete project](https://github.com/cooperlyt/jackson-bug-test)
Just run ```./gradlew :java-test:test``` for java or ``` ./gradlew :kotlin-test:test ``` for Kotlin

**Comment by cowtowncoder** [comment]
I was not questioning existing of the complete project (I did see the link). But was hoping for inlined snippet of the relevant test part without everything else, to reduce need to d/l project & allow cut-n pasting into Jackson test suite.

**Comment by cooperlyt** [comment]
I excluding Spring , only Jackson now

**Comment by JooHyukKim** [comment]
Okay I just went ahead to file PR #4750 to streamline debugging process.
So `readerWithView()` is supposed to create a view even when `DEFAULT_VIEW_INCLUSION` is disabled?

**Comment by cowtowncoder** [comment]
@JooHyukKim `DEFAULT_VIEW_INCLUSION` does this:

```
Feature that determines whether properties that have no view annotations are included in JSON serialization views 
```

so it affects handling of POJO properties wrt View definition: it has no effect on setting of the `View` in use.

`readerWithView()` will construct `ObjectReader` with specified `View` active (or none with `null`).

I'll have a look at PR to see if I can see what is going on.

**Comment by cowtowncoder** [comment]
Looking at the test there is certainly some misunderstanding somewhere: test should not pass and the way I see things work exactly like they should.

Basically:  like @JooHyukKim said: 

> `@JsonView` is where you wanna start. For references, look up some references around Jackson's "View" in Baeldung. Or you can search test cases in `jackson-databind` that uses.

So @cooperlyt make sure you understand Jackson's concept of views:

1. Classes MUST specify `@JsonView` on properties to indicate inclusion of properties when view processing is enabled (which ones to include for which view, basically)
2. View processing is enabled by setting the view to use (a `Class`), f.ex by `readerWithView()` -- by default no View processing occurs
3. Handling of non-annotated Properties depends on `DEFAULT_VIEW_INCLUSION` -- if `false` such properties are excluded; if `true`, included.

Test makes no sense because there are no `@JsonView` annotations on any of properties.
Without those, why is view-processing enabled at all?
Or if you want to include non-annotated properties, why disable `DEFAULT_VIEW_INCLUSION`? (should be enabled).

**Comment by cowtowncoder** [comment]
Will leave open for now but it seems this is due to misunderstanding of how Views work, not a bug.

**Comment by cooperlyt** [comment]
> Will leave open for now but it seems this is due to misunderstanding of how Views work, not a bug.

You're right, I misunderstood readerWithView(). This is indeed not a bug

**Comment by cowtowncoder** [comment]
Ok thank you for a very quick follow-up @cooperlyt.

**Comment by cowtowncoder** [comment]
@cooperlyt I don't think so. Unfortunately it is not possible to fully inspect all possible value types before serialization to see if they might have `@JsonView` annotations -- and it is perfectly fine to omit them.
This was a case of incorrect usage, setting a View to use, without configuring POJOs to work, but I don't think we can catch conditions where this makes no sense. 

What could be done, however, is to improve Javadocs of `DEFAULT_VIEW_INCLUSION`, perhaps -- so users like you would not change its setting without understanding consequences (or possibly misunderstanding its meaning).

What might help is to understand why you thought you should be setting/changing this `MapperFeature.DEFAULT_VIEW_INCLUSION` -- what was your reasoning?

**Comment by cooperlyt** [comment]
It seems I should take a closer look at Jackson's implementation in order to make reasonable suggestions. 

DEFAULT_VIEW_INCLUSION = false is the default value in Spring, and here is the reasoning behind it:  [here](https://github.com/spring-projects/spring-framework/issues/16793)

**Comment by cowtowncoder** [comment]
Interesting. Thank you for adding link to that page!

So, I guess my other question then is why use `readerWithView()`, if you do not (it seems?) want to use View functionality (no `@JsonView`s)?
Without that there would also be no problem.

**Comment by cooperlyt** [comment]
It's not that I'm using readerWithView(), but rather that the Spring Messaging Converter uses this method by default to convert JSON objects: [here](https://github.com/spring-projects/spring-framework/blob/c261ca3102414053677c40cf17f4b70b28b4b170/spring-messaging/src/main/java/org/springframework/messaging/converter/MappingJackson2MessageConverter.java#L241)

**Comment by cooperlyt** [comment]
I don't know why Spring Messaging assumes there's a View defined; I haven't made any settings, which is also why I misunderstood the concept of "View."

**Comment by cowtowncoder** [comment]
Ok if Spring Messaging has a default View of some kind AND them defaults to `DEFAULT_VIEW_INCLUSION = false`, that does indeed sound... dangerous and confusing.
It does not seem like a good idea.

I can understand how this lead to the problem here. Thank you for helping me understand the problem, context.

**Comment by cooperlyt** [comment]
I took another look at the Spring code, and it indeed returns a Class as the View when it can't find @JsonView. Perhaps the Spring team also misunderstood the concept of View. 
 I enjoyed our discussion and appreciate you helping me gain a deeper understanding of Jackson.

**Comment by cowtowncoder** [comment]
That is interesting. Too bad, too; especially since code seems to be handling "no view" case just fine. Oh well.
