### ISSUE TITLE
@JsonInclude(value = JsonInclude.Include.CUSTOM,valueFilter = SomeFilter.class) does not work for fields of record

### ISSUE THREAD

**Issue by swpalmer-cl** [FasterXML/jackson-databind#4754]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

The `valueFilter` is not used at all when applied to a field of a `record`.
An object of the filter class is not even constructed.

### Version Information

2.17.0

### Reproduction

```java
public record MyRecord(
    @JsonInclude(
        value = JsonInclude.Include.CUSTOM,
        valueFilter = AttributeTypeSerializationFilter.class)
    String attributeType,
    String attributeValue) {

  // Never return null for the attributeType, instead return the default
  public MyRecord {
    if (attributeType == null) attributeType = "String";
  }

  static class AttributeTypeSerializationFilter {

    public AttributeTypeSerializationFilter() {
      System.out.println("AttributeTypeFilter.init");
    }

    @Override
    // return true to exclude
    public boolean equals(Object obj) {
      System.err.println("AttributeTypeFilter: " + obj);
      return obj == null || "String".equals(obj);
    }
  }
}
``` 

### Expected behavior

`@JsonInclude(value=JsonInclude.Include.CUSTOM, ... )` should work on `record` fields as it does for `class` fields.

### Additional context

The idea is to reduce the JSON payload by excluding default values, but those values are non-null.

**Comment by JooHyukKim** [comment]
Did it work in previous versions? If so, could you share with us which?

**Comment by yihtserns** [comment]
More importantly, where's the steps to reproduce the issue?

**Comment by cowtowncoder** [comment]
Also: 2.17.0 is neither latest patch (2.17.2) (nor latest in general (2.18.0)).
So should:

1. Verify it occurs on 2.17.2 (slight possibility of fix)
2. Ideally verify against 2.18.0 (reasonable chance might be fixed)

so we won't waste time looking into something that might already be fixed.

**Comment by yihtserns** [comment]
BTW I'm asking for steps to reproduce the issue because I **cannot** reproduce it with a `2.17.0` + Record + custom filter + `ObjectMapper.writeValueAsString(...)`, so I highly suspect that the report is missing some context.

**Comment by swpalmer-cl** [comment]
I will try to create a more complete example from my code, but just for reference. I took the record class I had, and re-wrote it as a class and only then did the filter get called.  The ObjectMapper was configured exactly the same in both cases.

**Comment by yihtserns** [comment]
All passed:
```java
public class JsonIncludeCustomTest {

    private ObjectMapper objectMapper = new ObjectMapper();

    @Test
    public void testBean() throws Exception {
        MyBean beanNone = new MyBean();
        beanNone.setName("N/A");
        beanNone.setAddress("N/A");

        MyBean beanDoe = new MyBean();
        beanDoe.setName("Doe");
        beanDoe.setAddress("Doe");

        assertEquals("{\"address\":\"N/A\"}", objectMapper.writeValueAsString(beanNone));
        assertEquals("{\"name\":\"Doe\",\"address\":\"Doe\"}", objectMapper.writeValueAsString(beanDoe));
    }

    @Test
    public void testRecord() throws Exception {
        MyRecord recordNone = new MyRecord("N/A", "N/A");
        MyRecord recordDoe = new MyRecord("Doe", "Doe");

        assertEquals("{\"address\":\"N/A\"}", objectMapper.writeValueAsString(recordNone));
        assertEquals("{\"name\":\"Doe\",\"address\":\"Doe\"}", objectMapper.writeValueAsString(recordDoe));
    }

    public static class MyBean {

        @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NameFilter.class)
        private String name;
        private String address;

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getAddress() {
            return address;
        }

        public void setAddress(String address) {
            this.address = address;
        }
    }

    record MyRecord(
            @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NameFilter.class) String name,
            String address) {
    }

    public static class NameFilter {

        @Override
        public boolean equals(Object obj) {
            return "N/A".equals(obj);
        }
    }
}
```

**Comment by swpalmer-cl** [comment]
I think I found the issue...
Change the `record` to:
```java
    record MyRecord(
            @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NameFilter.class) String name,
            String address) {
        @Override
        public String name() {
            if (name == null) return "N/A";
            return name;
        }
    }
```

**Comment by yihtserns** [comment]
Right, I missed the accessor method override, relying too much on the issue title (which should maybe be updated to "_@JsonInclude(value = JsonInclude.Include.CUSTOM,valueFilter = SomeFilter.class) does not work for Record field when the accessor is overridden)_")

The cause is the same as #4626, and has been fixed in `2.18.0`.

**Comment by cowtowncoder** [comment]
@swpalmer-cl Did you try this with other versions like I requested? There is little value in working on non-latest patch (2.17.0) and there is strong indicates this might be fixed in 2.18.0 -- and if so, would be documented as such (fix unlikely to be backportable due to major rewrite in 2.18).

**Comment by swpalmer-cl** [comment]
@cowtowncoder I did not, I apologise. It is indeed fixed in 2.18.0

**Comment by yihtserns** [comment]
I forgot to mention an alternative/workaround if you can't/won't upgrade - move the annotation to the overridden accessor method:
```java
record MyRecord(String name, String address) {

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NameFilter.class) 
    @Override
    public String name() {
        if (name == null) return "N/A";
        return name;
    }
}
```

**Comment by cowtowncoder** [comment]
Thank you @swpalmer-cl!
