### ISSUE TITLE
Allow "Serialize as POJO" using `@JsonFormat(shape=Shape.OBJECT)` class annotation

### ISSUE THREAD

**Issue by hesamwls** [FasterXML/jackson-databind#476]
I read here http://www.cowtowncoder.com/blog/archives/2013/10/entry_482.html that `@JsonFormat(shape=Shape.OBJECT)` must work for both collection and map types but my tests shows it doesn't work for a class that implements Map Interface.
some digging in code approved my initial guess as there's no checking for `JsonFormat` in `BasicSerializerFactory.buildMapSerializer` unlike `buildCollectionSerializer` method.
now I am not sure that blog is official or not, but is there any technical reason to not implement this feature for Map or it's just forgotten?!

**Comment by tj-recess** [comment]
+1
Any ETA on this?

**Comment by cowtowncoder** [comment]
I don't think anyone is working on this at this point.
It could be added in 2.7 if a patch is contributed.

Now, similar to my comment on an issue related to `Map.Entry`, what is needed here is the ability to also indicate "Serialize as expected, not as POJO". Use of `Shape.ANY` could work on short term, although for 2.7 could consider adding option of `Shape.NATURAL`, to indicate that default behavior (something consider most natural) should be used, whatever that is. It would be overloaded semantically, but would work ok here.

**Comment by cowtowncoder** [comment]
FWIW, #865 is the related issue.

**Comment by cowtowncoder** [comment]
This is implementable at this point, considering there's `JsonFormat.Shape.NATURAL` to indicate "serialize Map as JSON Object, but not as POJO", and we can interpret `Shape.OBJECT` to then mean "serialize as POJO".

The reverse side of accepting such POJO may be tricky to implement, but then again should be doable.

**Comment by cowtowncoder** [comment]
Ok: easy part is implemented so that class annotation like so:

```java
@JsonFormat(shape=JsonFormat.Shape.OBJECT)
@JsonIgnoreProperties({ "size" })
public class MyStrings {
   public int getCount() { 
      return size();
   }
   public Collection<String> getValues() {
      return values();
   }
}
````

would produce serialization like:

```json
{ "count" : 3,
   "value" : [ "a", "b", "c" ]
}
```

Note that that this handling only support class-annotations (including mix-ins); per-property overrides are not supported as that is surprisingly difficult to support at this point. If support for property overrides is needed a new issue needs to be filed (also affected: `Map.Entry` which has similar limitation).
