### ISSUE TITLE
Make NumberSerTest run green on non-English locale

### ISSUE THREAD

**Issue by winfriedgerlach** [FasterXML/jackson-databind#4763]
### Is your feature request related to a problem? Please describe.

We experienced problems when running the Jackson build on a German Windows system: `NumberSerTest` failed, because the serialized value was "2,0" (with comma) instead of the expected "2.0".

### Describe the solution you'd like

We suggest to replace both occurences of `new DecimalFormat("0.0")` in the test with `new DecimalFormat("0.0", new DecimalFormatSymbols(Locale.ENGLISH))`. That did the trick for us.

**Comment by pjfanning** [comment]
#4764 merged
