### ISSUE TITLE
Deserializing with annotation-less single-arg constructor POJOs in 2.18 switched from delegating to properties json creator.

### ISSUE THREAD

**Issue by softqwewasd** [FasterXML/jackson-databind#4779]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

The POJO and record introspection changes made in 2.18.0 introduced a change in behavior when deserializing json to an object of a POJO with "annotation-less" single-argument constructor. It seems like it switched from a delegating json creator to a properties json creator.

Works as expected when excluding the parameters-names module.

I've marked this as a bug since I was unable to determine whether this is expected behavior in 2.18. 

### Version Information

2.18.0

### Reproduction

```java
public class B {
    private final String value;

    public B(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

}
```
```java
public record AWrapper(String a, B b) { }
```
```java
@Test
void DoSomething() throws JsonProcessingException {
    String json = """
    {"a":"Hello","b":"World"}
    """;

    ObjectMapper objectMapper = JsonMapper.builder()
	.addModules(new JavaTimeModule(), new Jdk8Module(), new ParameterNamesModule())
	.build();

    objectMapper.readerFor(AWrapper.class).readValue(json);
}
```
Fails in 2.18.0 with the following exception:
```shell
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.example.B` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('World')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 18] (through reference chain: com.example.AWrapper["b"])
```

Succeeds without any issues in 2.17.2

### Expected behavior

Should not fail(?)

**Comment by softqwewasd** [comment]
> Could you try 2.18.1? There were some fairly big changes in that release to fix some issues with 2.18.0.
Thanks for the quick reply! Fails with the same exception.

**Comment by cowtowncoder** [comment]
As far as I can see, the new behavior is somewhat more correct one: this looks very much like `value` is a property to pass via Constructor and we have a POJO. Hence re-written POJO introspection logic consider
Why 2.17.x and before did not use this logic I do not know -- this specific case was likely not covered by unit tests. I suspect constructor was detected via legacy handling for 1-arg constructors with one of "well-known" types (String, long, int, double I think).

1-argument cases are inherently ambiguous so heuristics used can give the answer different from expectations. In this case you do need to either:

1. Add `@JsonCreator(mode = Mode.DELEGATING)`
2. Configure mapper with `ConstructorDetector` (https://www.baeldung.com/java-jackson-constructordetector-deserialization talks about it; or test `src/test/java/com/fasterxml/jackson/databind/deser/creators/ConstructorDetectorTest.java`) to prefer Delegating Creators

While it is unfortunate there is behavior change, in this case I think we'll keep the slightly changed behavior of 2.18.0/1: it seems more correct wrt intent of heuristics.
That is, it is considered a bug fix, not breakage.

**Comment by softqwewasd** [comment]
I completely agree regarding the behavior in the new one being more correct. Thanks for the answer!
