### ISSUE TITLE
jackson-databind 2.15.0+ causes serialization/deserialization issue

### ISSUE THREAD

**Issue by Mariamalmesfer** [FasterXML/jackson-databind#4782]

**Comment by pjfanning** [comment]
@Mariamalmesfer Jackson is a JSON tool. It does not have logic to do 'joins'.

**Comment by yihtserns** [comment]
Is this generated by "AI"? 🤣

**Comment by Mariamalmesfer** [comment]
After reviewing the related issues, I found relevant discussions here:

https://github.com/FasterXML/jackson-databind/issues/4105
https://github.com/FasterXML/jackson-databind/issues/3968

**Comment by pjfanning** [comment]
@Mariamalmesfer please provide a full reproduction of your issue that contains only Jackson code.

We are volunteers and I, for one, don't appreciate your cryptic and sparsely described 'issue'.
