### ISSUE TITLE
`EnumFeature.WRITE_ENUMS_TO_LOWERCASE` overrides `@JsonProperty` values

### ISSUE THREAD

**Issue by martel** [FasterXML/jackson-databind#4788]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

When using `EnumFeature.WRITE_ENUMS_TO_LOWERCASE`, the `@JsonProperty` values of enum fields are ignored.

### Version Information

2.18.1

### Reproduction

```java
class ObjectMapperTest {

  public enum Sauce {
    @JsonProperty("Ketchup")
    KETCHUP,
  }

  ObjectMapper objectMapper = new ObjectMapper()
      .configure(EnumFeature.WRITE_ENUMS_TO_LOWERCASE, true);

  @Test
  void shouldUseJsonProperty() throws JsonProcessingException {
    assertEquals("\"Ketchup\"", objectMapper.writeValueAsString(Sauce.KETCHUP));
  }
}
```

Results in:

```
org.opentest4j.AssertionFailedError: 
Expected :"Ketchup"
Actual   :"ketchup"
```

### Expected behavior

Should return `@JsonProperty` defined value.

**Comment by cowtowncoder** [comment]
Thank you for reporting this @martel -- definitely sounds like a bug. Big thanks for reproduction.

**Comment by cowtowncoder** [comment]
@JooHyukKim I think you implemented this feature; may want to see if this might be something simple to fix? Or if not, at least add "tofix" reproduction to help.

**Comment by JooHyukKim** [comment]
Okay, lemme look into this right away 👌🏼👌🏼

**Comment by JooHyukKim** [comment]
Filed #4789 , thanks!

**Comment by cowtowncoder** [comment]
Excellent work, @JooHyukKim !

**Comment by cowtowncoder** [comment]
Thank you for your the report @martel; happy we could get it fixed quickly!
