### ISSUE TITLE
JsonAnySetter handling changed recently?

### ISSUE THREAD

**Issue by alesj** [FasterXML/jackson-databind#4795]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

This used to work for me (in 2.17.2):

```
    record AnyTester(Map<String, Object> p) {
        AnyTester {
            if (p == null) {
                p = new LinkedHashMap<>();
            }
        }

        @JsonAnySetter
        public void setAnyUnknownProperty(String key, Object value) {
            p.put(key, value);
        }
    }

    @Test
    public void testAnyTester() throws Exception {
        AnyTester at = OBJECT_MAPPER.readValue("{\"foo\":\"bar\"}", AnyTester.class);
        Assertions.assertEquals("bar", at.p().get("foo"));
    }
```

Now there is no `foo=bar` entry in the `p` map.

### Version Information

2.18.1

### Reproduction

Just run the test above.

### Expected behavior

`p` should have `foo=bar` entry.

**Comment by JooHyukKim** [comment]
Might be related to #4639 could you try 2.18.2 (latest)?

**Comment by alesj** [comment]
@JooHyukKim where can I find 2.18.2 ?
(https://central.sonatype.com/search?q=jackson-databind)

**Comment by alesj** [comment]
> @JooHyukKim where can I find 2.18.2 ? (https://central.sonatype.com/search?q=jackson-databind)

Ah, OK ... I guess I should just build the current repo (which points to 2.19.0-SNAPSHOT ... which confused me)

**Comment by alesj** [comment]
@JooHyukKim yup, that seems to fix it, tnx!
(the test is now passing ...)

Closing the issue now, as fixed by the #4639

**Comment by JooHyukKim** [comment]
Phew! Awesome. Thank you for reporting @alesj !

**Comment by cowtowncoder** [comment]
Marking as duplicate of #4639. Thank you for verifying @alesj .
