### ISSUE TITLE
Using toString() on Serialization Fail.

### ISSUE THREAD

**Issue by lucky8987** [FasterXML/jackson-databind#4800]
### Is your feature request related to a problem? Please describe.

I encountered a problem, for example, when serializing: org.springframework.http.HttpMethod, it currently throws an exception because it does not provide a get method for the property, but provides toString().

### Describe the solution you'd like

I hope to serialize objects that do not provide property methods, without throwing exceptions, but by calling the toString method to complete the processing. I was wondering if it's possible to add the FAIL_USING_TO_STRING attribute in: com. fasterxml. jakson. databind. serializationFeature to solve this problem?

**Comment by pjfanning** [comment]
Jackson is highly configurable. You could register a custom serializer. The advantage if using existing features and existing configurability - you don't have to wait to for code changes and a new release.

We can't just keep adding extra features just because users don't want to try the existing features.

**Comment by JooHyukKim** [comment]
> I hope to serialize objects that do not provide property methods, without throwing exceptions, but by calling the toString method to complete the processing.

Similarly, there is `SerializationFeature.WRITE_ENUMS_USING_TO_STRING` for enums, but it "eagerly" serializes **Enums** using `toString()` not like here being asked for

    try normal serialization first then before failing, try toString

I think that's huge difference and seems way more complex.

So yeah, since we know for which object (`HttpMethod`) we want to achieve the behavior, custom serializer would be a great option.

**Comment by lucky8987** [comment]
> > I hope to serialize objects that do not provide property methods, without throwing exceptions, but by calling the toString method to complete the processing.
> 
> Similarly, there is `SerializationFeature.WRITE_ENUMS_USING_TO_STRING` for enums, but it "eagerly" serializes **Enums** using `toString()` not like here being asked for
> 
> ```
> try normal serialization first then before failing, try toString
> ```
> 
> I think that's huge difference and seems way more complex.
> 
> So yeah, since we know for which object (`HttpMethod`) we want to achieve the behavior, custom serializer would be a great option.

Thank you for your suggestion. Indeed, custom serialization can effectively solve this problem.

**Comment by lucky8987** [comment]
> Jackson is highly configurable. You could register a custom serializer. The advantage of using existing features and existing configurability - you don't have to wait for code changes and a new release.
> 
> We can't just keep adding extra features just because users don't want to try the existing features.

OK，I will follow your suggestion and solve this problem through custom serialization.

**Comment by cowtowncoder** [comment]
In this case, why not use Mix-in Annotations to annotate `toString()` method with `@JsonValue`? That would serialize using return value of `toString()` method.

Having to use custom serializer should really be the last resort, fwtw.

**Comment by yihtserns** [comment]
LOL someone [changed HttpMethod from Enum to Class](https://github.com/spring-projects/spring-framework/issues/27697).

**Comment by yihtserns** [comment]
> In this case, why not use Mix-in Annotations to annotate `toString()` method with `@JsonValue`?

Had the same thought, was going to suggest:
```java
public abstract class EnumLikeMixin {

    @JsonValue
    public abstract String name();
}

...
objectMapper.addMixIn(HttpMethod.class, EnumLikeMixin.class)
```
---
Also, maybe https://github.com/spring-projects/spring-framework/issues/33870 can & should do that internally, seeing how they've already done similar thing before: https://github.com/spring-projects/spring-framework/blob/37b110a181baa2249c75d028dfea3de58a17a2f0/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L767

**Comment by cowtowncoder** [comment]
@yihtserns Good suggestion! `name()` is probably better method to annotated indeed.

**Comment by lucky8987** [comment]
> > In this case, why not use Mix-in Annotations to annotate `toString()` method with `@JsonValue`?
> 
> Had the same thought, was going to suggest:
> 
> ```java
> public abstract class EnumLikeMixin {
> 
>     @JsonValue
>     public abstract String name();
> }
> 
> ...
> objectMapper.addMixIn(HttpMethod.class, EnumLikeMixin.class)
> ```
> 
> Also, maybe [spring-projects/spring-framework#33870](https://github.com/spring-projects/spring-framework/issues/33870) can & should do that internally, seeing how they've already done similar thing before: https://github.com/spring-projects/spring-framework/blob/37b110a181baa2249c75d028dfea3de58a17a2f0/spring-web/src/main/java/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.java#L767 (assuming your usage _is_ via Spring's `HttpMessageConverter` mecha).

Wow, your plan looks very elegant and can solve this type of problem.👍
