### ISSUE TITLE
LeakyAbstraction: NumericNodes which represent the same Json value are not considered equal 

### ISSUE THREAD

**Issue by ludgerb** [FasterXML/jackson-databind#4803]
- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Hi everyone.

when converting a java object to a JsonNode tree, depending on the underlying implementation chosen, the resulting Json trees are not considered equal, even though they represent the same Json value and serialize to the same Json string representation.

I.e. an IntNode representing 12345 is not equal to a LongNode, ShortNode, BigIntegerNode or DecimalNode representing the same value.

If I deserialize these nodes and compare the resulting Json string, they are considered equal.

This is a case of [leaky abstraction](https://en.wikipedia.org/wiki/Leaky_abstraction).

Use case is:

When testing a class producing Json output, I want to compare the produced Json to a reference json to check correctness of the implementation.

### Version Information

2.17.1

### Reproduction

```java
  @Test
  void jsonNumberSerialisationTest() throws JsonProcessingException {

    var value = 12345;
    var valueString = String.valueOf(value);

    var objectMapper = new ObjectMapper();

    var referenceNode = objectMapper.readTree(valueString);

    var intNode = IntNode.valueOf(value);
    var bigIntegerNode = BigIntegerNode.valueOf(BigInteger.valueOf(value));
    var longNode = LongNode.valueOf(Long.valueOf(value));
    var decimalNode = DecimalNode.valueOf(BigDecimal.valueOf(value));
    var shortNode = ShortNode.valueOf((short)value);

    // serialized Json is identical, representing the same Json
    assertEquals(valueString, objectMapper.writeValueAsString(referenceNode));
    assertEquals(valueString, objectMapper.writeValueAsString(intNode));
    assertEquals(valueString, objectMapper.writeValueAsString(bigIntegerNode));
    assertEquals(valueString, objectMapper.writeValueAsString(longNode));
    assertEquals(valueString, objectMapper.writeValueAsString(decimalNode));
    assertEquals(valueString, objectMapper.writeValueAsString(shortNode));

    // JsonNodes are not equal, depending on implementation used
    assertEquals(referenceNode, intNode); // passes - both are the same node type
    assertEquals(referenceNode, bigIntegerNode); // fails
    assertEquals(referenceNode, longNode); // fails
    assertEquals(referenceNode, decimalNode); // fails
    assertEquals(referenceNode, shortNode); // fails
  }
``` 

### Expected behavior

According to my expectation JsonNode trees representing the same Json String are also considered equal and do not differ in equality based on internal (implementation) details.

I do understand that for float and double this might not always hold since there -depending on precision- they may yield differing results.

Current workaround in JunitTests before comparing json result trees with the respective expected reference json:
- deserialize objects first to a Json String representation and then converting this back to a JsonNode tree, to align the JsonNode trees and ensure truly equal-check safe JsonNode trees.

Though this workaround adds considerable computational overhead for the (imho unnecessary) additional deserialisation step required.

**Comment by cowtowncoder** [comment]
For context we have previous issues:

* #3698 
* #1758 
* #1561 
* #333
* #80

as well as issue for which alternate `equals()` method was added:

* #790 

So this is definitely something users find challenging. But as I said, I think the path forward would be with providing "Number canonicalizing" `Comparator`.
It could even be configurable in some aspects. F.ex

* Does it unify Integral (int, long, BigInteger) and Fractional (double, float, BigDecimal) or not?
* What about trailing zeroes? (that is; Lexical equality (trailing zeroes matter) or Logical/Content equality (trailing zeroes would not matter)

Having said that, to get progress, a PR would probably be needed.

**Comment by JooHyukKim** [comment]
Yeah, the suggested equals method would do 👍🏼

```java
    public boolean equals(Comparator<JsonNode> comparator, JsonNode other) {
```

Otherwise, you're welcome to read through mentioned issues by @cowtowncoder above and help come up with solution -- that hopefully satisfies every(or most) user's need. Saying this because you mentioned leaky abstraction and I think we can also say that JSON number specification itself is leaky. Converting from fine grained expression to rough is easy, but not the way around.

**Comment by yawkat** [comment]
I think a `Comparator.comparing(objectMapper::writeValueAsString)` would be what most people expect for value comparison.

**Comment by cowtowncoder** [comment]
@yawkat That would be delightfully simple implementation indeed. So then it'd be just the question of plugging it in API. As I said I do not think it'd be good for `JsonNode.equals(Object)`, but any other way to plug is fair game.
