### ISSUE TITLE
can not bind `is_active` to isActive when setting PropertyNamingStrategies.SNAKE_CASE

### ISSUE THREAD

**Issue by afattahi54** [FasterXML/jackson-databind#4806]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

I have set the `PropertyNamingStrategies.SNAKE_CASE` 

So the mapper is something like:

````java
ObjectMapper mapper= 
	JsonMapper.builder()
	.enable( MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS )
	.enable( MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES )				
	.build()
	.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
	.registerModule(new JavaTimeModule()); 
````

The jsons is as:

````json
  {
    "user_id": 1,
    "first_name": "Alice",
    "last_name": "Smith",
    "email": "alice.smith@example.com",
    "date_of_birth": "1985-05-15",
    "is_active": true,
 ....

````

````java
public class User {

	private int userId;
	private String firstName;
	private String  lastName;
        private String email;
        private boolean isActive;
       .....

	public boolean isActive() {
		return isActive;
	}
	public void setActive(boolean isActive) {
		this.isActive = isActive;
	}
....
````

All the properties are mapped correctly to java object expet `is_active` 

Of course this solves:

```java
    @JsonProperty("is_active")
    private boolean isActive;

```

Is it an ok behavior. 

As we have lots of `boolean` types. Is it any way I can handle it better 

### Version Information

2.18.1

### Reproduction

<-- Any of the following
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here
 -->
```java
// Your code here
```

**Comment by JooHyukKim** [comment]
Oh there seems to be misunderstanding here @afattahi54. 

The `isActive` property gets treated as `is-getter` here so by default the `is` prefix is handled such. Just like you don't de/serialize `getFirstName()` and `setFirstName()` as JSON field name
```text
"get_first_name" : value....
```
If you want to deserialize `is_active` without `@JsonProperty` you need declare getter/setter as below

```java
        public boolean getIsActive() {
            return isActive;
        }

        public void setIsActive(boolean isActive) {
            this.isActive = isActive;
        }
```

**Comment by JooHyukKim** [comment]
Could u close the issue if there is no other issue, @afattahi54 ?
