### ISSUE TITLE
Change JDK baseline for Jackson 3.0 from Java 8 to Java 17

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#4820]
### Describe your Issue

As per title, Jackson 3.0 need not (and should not) keep JDK baseline as Java 8.
We should pick a support LTS version to use as the new base.

We have a choice to make; currently likeliest choices are:

* Java 17 (for maximal support for existing user base)
* Java 21 latest and greatest

We can decide on this via separate discussion; this issue is for tracking actual change.

**EDIT**: Discussion here: https://github.com/FasterXML/jackson-future-ideas/discussions/73

**Comment by pjfanning** [comment]
My opinion is that libs ideally support the max number of Java versions. [Multi-Release jar](https://openjdk.org/jeps/238) support is there to help us optimise support for different Java versions.

**Comment by JooHyukKim** [comment]
Found dup issue #3946

**Comment by JooHyukKim** [comment]
Which JDK version do you have in mind, with multi-release jar strategy @pjfanning?

**Comment by cowtowncoder** [comment]
I would prefer not having to use MR for anything, personally. But if we must for something I guess we can try figuring it out.

But even if we do, we need to set up minimum baseline and I think Java 8 should be left for Jackson 2.x. So the question remains.
But let's have discussion/vote on 

https://github.com/FasterXML/jackson-future-ideas/discussions/73

**Comment by cowtowncoder** [comment]
Quick suggestion: unless anyone objects, I could work on increasing baseline first to JDK 17 (wrt CI). And then if (but only if) decision is made to go to JDK 21 make further changes. This allows finding possible issues wrt change of baseline and tackling most of complexity, regardless of the ultimate decision on exact baseline JDK to use.

**Comment by cowtowncoder** [comment]
Note on work for intermediate Java 17:

* JAX-RS provider: https://github.com/FasterXML/jackson-jaxrs-providers/pull/202

**Comment by maxandersen** [comment]
Go for 17 please otherwise Quarkus, spring and lots of others will be stuck on older Jackson and we'll be all stuck maintaining old code. 

Unless you know of some specific feature in java 21 that Jackson just can't function without and not support from Java 17 then please go for 17.

**Comment by JooHyukKim** [comment]
Your vote + opinion on https://github.com/FasterXML/jackson-future-ideas/discussions/73 would be great @maxandersen !

**Comment by JooHyukKim** [comment]
### Data types

- jackson-datatypes-collections: https://github.com/FasterXML/jackson-datatypes-collections/pull/169
- jackson-datatypes-misc: ...WIP
- jackson-datatype-joda: ...WIP

**Comment by cowtowncoder** [comment]
Completed.

**Comment by cowtowncoder** [comment]
Note: discussion https://github.com/FasterXML/jackson-future-ideas/discussions/73 is now closed and JDK 17 was chosen as the baseline (over JDK 21). So changes under this issue are sufficient as-is.
