### ISSUE TITLE
Deserialization of Class with multiple constructors and usage of ParameterNamesModule

### ISSUE THREAD

**Issue by djohs** [FasterXML/jackson-databind#4834]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Hey there,

We recently upgraded to Jackson 2.18.1, and we're now encountering an issue when we try to deserialize a class with multiple constructors. We're using the `ParameterNamesModule` so that we don't need to add the `@JsonCreator` annotation.

    @Getter
    @RequiredArgsConstructor
    public static class Param {
        private final String foo;
        private final String bar;
    }

    @Getter
    public static class A {
        private final String foo;
        private final String bar;

        public A(String foo, String bar) {
            this.foo = foo;
            this.bar = bar;
        }

        public A(Param param) {
            this.foo = param.getFoo();
            this.bar = param.getBar();
        }
    }

    @Test
    void deserializationTest() throws JsonProcessingException {

        ObjectMapper objectMapper = JsonMapper.builder().addModule(new ParameterNamesModule()).build();
        A desA = objectMapper.readValue("""
                {
                  "foo": "foo",
                  "bar": "bar"
                }""", A.class);

        assertThat(desA.getFoo()).isEqualTo("foo");
        assertThat(desA.getBar()).isEqualTo("bar");
    }

We're aware that the documentation for the `ParameterNamesModule` states that the module only works if there is only one constructor. However, the example worked for us with version 2.17.3. We would like to clarify whether this behavior is intended?

### Version Information

2.18.1, 2.18.2

### Reproduction

see code sample in description

### Expected behavior

deserialization works

**Comment by cowtowncoder** [comment]
Correct: if there are multiple visible (`public`) Constructors, one should not be selected without explicit annotation. This is for regular classes; for `Record`s the canonical constructor would be chosen.

I don't know why 2.17 would have selected one of Constructors -- that was not intentional.

The only question I have is whether exception given indicates the issue? Behavior itself seems as-intended.

**Comment by JooHyukKim** [comment]
So what @cowtowncoder seems to suggest is informative error message should be provided?

**Comment by cowtowncoder** [comment]
Potentially: since no exception was provided I was just guessing it might not be informative enough. But yes, behavior itself is as currently specified.
Although... if we wanted to, we could consider using "most-parameters-taking-visible" Constructor of alternatives (assuming one has more than all others), as a new feature. If so a new feature request issue should be filed (with link to here).

**Comment by JooHyukKim** [comment]
We are quite close to closing with `work-as-intended`.
@djohs any thoughts? or could you share what issue u are facing? When you said...

> and we're now encountering an issue when we try to deserialize a class with multiple constructors.

**Comment by djohs** [comment]
Thank you for the quick response, and sorry for not providing the exception message earlier. The exception message is:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.test.JacksonTest$A` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 2, column: 3]
```

I personally think it is informative enough. As I mentioned, we were just surprised that it worked before because a big part of our codebase relies on that behavior. We just wanted to check with you before fixing something that may not be intended. 

> Although... if we wanted to, we could consider using "most-parameters-taking-visible" Constructor of alternatives (assuming one has more than all others), as a new feature. If so a new feature request issue should be filed (with link to here).

At least for us, such a feature would be very convenient. However, regarding this issue, it's fine for me to close it.

**Comment by cowtowncoder** [comment]
@djohs Thank you. We will keep the idea in mind: it (ability to select specifica one from multiple but different constructors based on simple criteria) is more achievable than trying to dynamically select, say, best match (which has been requested too, but to me gets much too complicated pretty fast).
