### ISSUE TITLE
Allow composite annotations 

### ISSUE THREAD

**Issue by davideanderson** [FasterXML/jackson-databind#485]
Even though @JsonIgnore allows ElementType.ANNOTATION_TYPE as a target, if I try to make a composite annotation, it doesn't work. 

For example, I create:

```
@Target({ METHOD, FIELD, ANNOTATION_TYPE })
@Retention(RUNTIME)
@Transient
@JsonIgnore
public @interface ServerRuntimeOnly {

}
```

In order to join @Transient and @JsonIgnore into a single annotation.
Then I create the class 

```
public class SomeEntity {
  @ServerRuntimeOnly
  String cache;
  ...
}
```

It works with @JsonIgnore on the cache, but not @ServerRuntimeOnly.
(disclaimer: my situation is much more complex than the provided example, but it still doesn't work with the composite when it does work for @JsonIgnore, so I am assuming it doesn't work for this simple case either)

**Comment by wallind** [comment]
> The trick is to use `@JacksonAnnotationsInside` meta-annotation; this will indicate that all the other annotations of "bundle" are to be included. So just add this to `@ServerRuntimeOnly` and it will work as expected.

@cowtowncoder your comment here just saved another devs day 10 years later in 2024. God bless you 🙇

**Comment by cowtowncoder** [comment]
@wallind Excellent! Thank you for sharing this story :)
