### ISSUE TITLE
Polymorphism with JsonTypeInfo doesn't use field/property type as default type

### ISSUE THREAD

**Issue by voidmain** [FasterXML/jackson-databind#495]
We are using the JsonTypeInfo and JsonSubType annotations to identify the types during serialization and deserialization. These work when great for serialization and work well during deserialization if the field/property uses the base type. However, we have a place that specifies a field as a sub-type. Jackson doesn't reflect on that field to figure out the sub-type to use. Instead, we had to override the TYPE level JsonTypeInfo on the field and specify the defaultImpl annotation parameter. 

Here's some code.

The JSON classes:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
    @Type(value = ContentApprovalNotification.class, name = "contentApproval"),
    @Type(value = ContentDeleteNotification.class, name = "contentDelete"),
    @Type(value = ContentEditNotification.class, name = "contentEdit"),
    @Type(value = ContentUserActionNotification.class, name = "userAction")
})
public abstract class BaseNotification {
}

public class ContentUserActionNotification extends BaseNotification {
  public String value;
  ...
}
```

The field that specifies a sub-type:

```
  public static class Request {
    public boolean rebroadcast = true;
    public ContentUserActionNotification userAction;
}
```

This causes an exception if the incoming JSON to deserialize looks like this:

```
{
  "rebroadcast": true,
  "userAction": {
    "value": "foo"
  }
}
```

The exception is something along the lines of "unexpected FIELD_NAME: missing property 'type' that is to contain type id".

We fixed this by adding the JsonTypeInfo annotation to the field like this:

```
  public static class Request {
    public boolean rebroadcast = true;

    @JsonTypeInfo(use = Id.NAME, include = As.PROPERTY, property = "type", defaultImpl = ContentUserActionNotification.class)
    public ContentUserActionNotification userAction;
}
```

However, this appears to be completely redundant. Our thought is that Jackson should notice that the field is a known JsonSubType according to the classes and then not require a 'type' property.

**Comment by tbartley** [comment]
We came across this recently (2.9.x) and solved it with a `DeserializationProblemHandler`:

```
public class SubtypeDeserializationProblemHandler extends DeserializationProblemHandler
{
    @Override
    public JavaType handleMissingTypeId(DeserializationContext ctxt, JavaType baseType, TypeIdResolver idResolver, String failureMsg)
    {
        JavaType type = null;
        if (baseType != null) {
            Class<?> subTypeClass = baseType.getRawClass();
            type = ctxt.constructSpecializedType(baseType.getSuperClass(), subTypeClass);
        }
        return type;
    }
}
```

Any further thoughts on why this handling shouldn't be incorporated by default rather than requiring either of these kinds of approaches (problem handler or extra JsonTypeInfo)?

**Comment by cowtowncoder** [comment]
I suspect this might be more like "working as designed", but there are also more recent requests for improving some aspects along the same lines, so I think I will close this one, and leave out one of newer ones wrt accepting "no type id" case if concrete type is requested.
