### ISSUE TITLE
Add new JsonInclude.Include feature to exclude maps after exclusion removes all elements.

### ISSUE THREAD

**Issue by cherlo** [FasterXML/jackson-databind#497]
Current exclusion features NON_NULL and NON_EMPTY help greatly in removing unwanted text in the json payloads, but maps still get serialized if they originally contained an element even when that child element is removed because it is null or empty.  For example, when making a json tree from this json:

```json
{ "foo" : {"bar" : null } }
```

then serializing with NON_EMPTY produces this:

```json
{"foo" : {} }
```

but ideally, I want the payload to be:

```json
{}
```

Seems trivial in this case, but when dealing with a realistic payload like:

```json
{"familyCount":{},"zipCode":{},"areaCode":["555"],"streetAddress":{},"profileInfo":{},"marketInfo":{},"longitude":{},"latitude":{}}
```

I would rather have to deal with just this:

```json
{"areaCode":["512"]}
```

These payloads are transported to mobile devices, logged and written to databases, so having them compact and readable is highly desirable.  I ended up having to write a "JSON cleaner" that recursively prunes empty nodes to get a compact and readable payload.  

It would be great if the ObjectMapper had a built-in serialization feature like NON_EMPTY that does this.

**Comment by cowtowncoder** [comment]
Missing piece was to add handling in `MapSerializer`, so that now following property:

```java
 class POJO
{
        @JsonInclude(content=JsonInclude.Include.NON_EMPTY,
                value=JsonInclude.Include.NON_EMPTY)
        public Map<String,String> values;   
```

would produce

    {}

for content where `values` only had "empty" values, such as `null`s and empty Strings (""), or `List`s with no elements.

**Comment by cherlo** [comment]
Thank you.  Greatly appreciated.

**Comment by SakrAmira** [comment]
This doesn't solve the nested POJO problem.

**Comment by kellerassel007** [comment]
I have the same issue
