### ISSUE TITLE
Deprecate com.fasterxml.jackson.databind.jsonschema

### ISSUE THREAD

**Issue by jackphel** [FasterXML/jackson-databind#50]
Deprecate com.fasterxml.jackson.databind.jsonschema along with: 
the generateJsonSchema method in objectmapper and defaultserializerprovider,
methods which create nodes in stdserializer,
and potentially deprecate  getSchema in a lot of serializers

**Comment by cowtowncoder** [comment]
Class itself has been deprecated since 2.2, so closing. Removal of old functionality would be nice, but probably better to wait until 3.x, or at least few more minor releases.
