### ISSUE TITLE
InvalidFormatException reports a wrong location

### ISSUE THREAD

**Issue by jgottero** [FasterXML/jackson-databind#502]
When trying to bind the following json: ```{"min":10,"max":"xxx"}```

to this java class:
```
class Range {
Double min;
Double max;
}
```

jackson throws an InvalidFormatException exception:
```Can not construct instance of java.lang.Double from String value 'xxx': not a valid Double value at [Source: {"min":10,"max":"xxx"}; line: 1, column: 10]```

Column 10 stops at: ```{"min":10```, whearas we expect column 22: ```{"min":10,"max":"xxx"```

**Proposed fix:**

Looking at the static ```from``` method from class InvalidFormatException:
```
        return new InvalidFormatException(msg, jp.getTokenLocation(),
                value, targetType);
```
I think it should be:
```
        return new InvalidFormatException(msg, jp.getCurrentLocation(),
                value, targetType);
```

**Comment by cowtowncoder** [comment]
For sake of completeness, I think the underlying issue is this:

https://github.com/FasterXML/jackson-core/issues/37

so will close this (for now?) as duplicate.
