### ISSUE TITLE
Collection deserialization does not invoke property initializer

### ISSUE THREAD

**Issue by kdkeck** [FasterXML/jackson-databind#509]
I have a class in which I want one of the properties to hold a SortedSet in reverse order.  I naively thought the following code would accomplish this:

```Java
public class Foo {
  @Id private ObjectId id;
  @JsonProperty private final SortedSet<String> reverseSortedSet =
      new TreeSet<>(Collections.reverseOrder());
}
```

But it does not.  Instead, upon deserialization, `foo.getReverseSortedSet().comparator()` returns null.

Would making this work as one would expect be too much to ask?

**Comment by cowtowncoder** [comment]
Actually #1399 allows this to work: just need to annotate property with:

```java
@JsonSetter((merge=OptBoolean.TRUE)
```

and this will make existing property-value be checked first.
Setting may also be used as global default (for all properties unless overridden), and via per-type "config overrides"; see #1399 for details.
