### ISSUE TITLE
error: package com.fasterxml.jackson.core does not exist?

### ISSUE THREAD

**Issue by GitHubMrWhy** [FasterXML/jackson-databind#514]
I try to run this code and import from jackson-databind but it show error like that.
did I import wrong?

> CreateMapping.java:1: error: package com.fasterxml.jackson.core does not exist
> import com.fasterxml.jackson.core.JsonProcessingException;
>                                  ^
> CreateMapping.java:2: error: package com.fasterxml.jackson.databind does not exist
> import com.fasterxml.jackson.databind.JsonNode;
>                                      ^
> CreateMapping.java:3: error: package com.fasterxml.jackson.databind does not exist
> import com.fasterxml.jackson.databind.ObjectMapper;
>                                      ^
> CreateMapping.java:17: error: cannot find symbol
>     private static final ObjectMapper mapper = new ObjectMapper();

```
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.*;
import java.lang.Exception;
import java.lang.String;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

public class CreateMapping {

    static final String REST_URL = "";
    private static final String API_KEY = "";
    private static final ObjectMapper mapper = new ObjectMapper();

    public static void main(String[] args) throws Exception {
        Mapping mapping = new Mapping();
        mapping.setCreator("");
        mapping.setRelation("");
        mapping.setSource("MY_USER");
        mapping.setSource_name("");
        mapping.setComment("");

        // Create terms
        List<Term> terms = new ArrayList<Term>();
        Term ncitMelanoma = new Term();
        ncitMelanoma.setOntology("");
        List<String> ncitTermIds = new ArrayList<String>();
        ncitTermIds.add("");
        ncitMelanoma.setTerm();
        terms.add();
        Term snomedMelanoma = new Term();
        snomedMelanoma.setOntology("");
        List<String> snomedTermIds = new ArrayList<String>();
        snomedTermIds.add("");
        snomedMelanoma.setTerm();
        terms.add();
        mapping.setTerms();

        // Convert mapping to JSON
        String prettyJSON = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(mapping);
        String bodyJSON = mapper.writeValueAsString(mapping);
        System.out.println("Mapping as JSON:");
        System.out.println(prettyJSON);
        System.out.println("\n\n");

        // POST to web service
        postJSON(REST_URL + "/mappings", bodyJSON);

        // Success
        System.out.println("Added mapping successfully");
    }
}
```

**Comment by mandoLuna** [comment]
I am having a similiar issue, can someone help me? "error: package com.fasterxml.jackson.databind does not exist
    [javac] import com.fasterxml.jackson.databind.*"

![image](https://cloud.githubusercontent.com/assets/22896603/19453686/e737cf0a-947b-11e6-9faf-5ac8c79f2f28.png)

**Comment by cowtowncoder** [comment]
Probably something to do with imports or your IDE. I will be muting this issue because these are not problems due to `jackson-core` itself but usage questions, and may be discussed on `jackson-user` mailing list, instead of issue tracker.
