### ISSUE TITLE
Mixin annotations lost when using a mixin class hierarchy with non-mixin interfaces (variant of #515)

### ISSUE THREAD

**Issue by stevebread** [FasterXML/jackson-databind#529]
I've found a previously working scenario related to a MixIn annotation hierarchy has broken in 2.4.2 and it may be caused by #515. 515 fixes the case where the `parents` list has a MixIn class before an interface. If the interface appears before the MixIn, then MixIn annotations are no longer applied, this used to work in 2.4.0.

Using the same example as in #515, assume that the `parents` list for `Person` has `[PersonMixIn, Contact, ContactMixIn]`. `Contact.getCity()` is processed by `mixIns.add(_constructMethod(m))` and `ContactMixIn.getCity()` is processed by `_addMixUnders(m, am)`.

Then `AnnotatedClass.resolveMemberMethods()` processes `Contact`. The `parents` list for `Contact` has `ContactMixIn` and `ContactMixIn.getCity()` is once again processed by `_addMixUnders(m, am)`.
After processing the MixIn, the call to `_addMixOvers()` in `_addMemberMethods()` would apply the annotations to `Contact.getCity()`. This method is still called in 2.4.2 but the MixIn annotations from ContactMixIn are not applied.

**Comment by cowtowncoder** [comment]
Can not reproduce at this point; may be reopened with explicit test case.
