### ISSUE TITLE
Another issue with polymorphic serialization with identity info

### ISSUE THREAD

**Issue by buzden** [FasterXML/jackson-databind#530]
Note that this issue is not the same with the issue #154 (but probably related).

Consider we have some class `Obj` with some identity info intended to be inherited

``` java
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class)
public class Obj {}
```

and its inheritant

``` java
public class Child extends Obj {
    public final String value;

    public Child(final String value) {
        this.value = value;
    }
}
```

Consider also we have some container which stores, for instance, two polymorphic `Obj` values:

``` java
public class Container2 {
    public final Obj obj1;
    public final Obj obj2;

    @JsonCreator
    public Container2(
            @JsonProperty("obj1")
            @JsonTypeInfo(property = "obj1_type", use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.EXTERNAL_PROPERTY)
            final Obj obj1,
            @JsonProperty("obj2")
            @JsonTypeInfo(property = "obj2_type", use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.EXTERNAL_PROPERTY)
            final Obj obj2) {
        this.obj1 = obj1;
        this.obj2 = obj2;
    }
}
```

Mind that polymorphic values are stored with _external property_ type info, this is important.

Serializing the object constructed as `new Container2(new Child("1"), new Child("1"))`, we have the result `{obj1={@id=1, value=1}, obj1_type=Child, obj2={@id=2, value=1}, obj2_type=Child}` as expected.

But as soon as we are going to run into the identity info usage, for example if the serialized object is constructed like

``` java
final Obj same = new Child("1");
final Container2 objectToSerialize = new Container2(same, same);
```

we will get an unexpected lack of type info for the second value:
`{obj1={@id=1, value=1}, obj1_type=Child, obj2=1}`.

I expected the result of serialization to be `{obj1={@id=1, value=1}, obj1_type=Child, obj2=1, obj2_type=Child}` and let me explain why.

I can't know whether given `obj2=1` is an id of generic object of type `Obj` because some children of this type could define their own `@JsonIdentityInfo` which have more priority than parent definition. So, it's easy to create such a situation when you have a polymorphic value with identifier (because this value already have been there before) and you have at least two children of your `Obj` with such identifier, so you can't choose anything. I'll write this example in code on demand.

Consluding, this means that _external property_ type info **have to be written** even if object is not written itself but only its identifier is written. Otherwise, serialized value does not contain enough to work with. Actually, this issue can touch _wrapper array_ and _wrapper object_ type info representations too (if this does not contradict to the JSON language definition, which whould be strange, I think).

**Comment by cowtowncoder** [comment]
I don't think there is anything here that I can work on, closing.
