### ISSUE TITLE
ObjectMapper fails to bind fields on deserialization when @JsonUnwrapped is used

### ISSUE THREAD

**Issue by jeacott** [FasterXML/jackson-databind#533]
I'm seeing this. Jackson 2.4.2

I have a simple class, structure as below:

```java
public class Parent {
@JsonUnwrapped
Child c1;
}

public class Child {
String field1;
String field2;
...
}
```

this deserializes fine without the @JsonUnwrapped, and the structure is correct,
but when I try with @JsonUnwrapped
all the fields of my the child class exist in the parent as expected, but all their values are all null.

**Comment by jf08300368** [comment]
bingo! @herau's solution works

**Comment by jf08300368** [comment]
+1

**Comment by cowtowncoder** [comment]
Issue is missing JSON to reproduce the problem so it is impossible to say whether problem is with Jackson, or code submitter is using. @herau's comments may point out the root cause; if not, may be reopened with reproducible test case.

**Comment by jeacott** [comment]
Theres a class that would generate the json in the original message

**Comment by cowtowncoder** [comment]
@jescott Class along may or may not be enough. As I said, reproducible test case would be needed, given that @herau pointed out likely cause: non-public fields are NOT serialized by default.

**Comment by jf08300368** [comment]
My Jackson version is 2.6.2. Give two classes, Parent contains nested Child object:
```
public class Parent {
    @JsonUnwrapped
    Child c1;
}

public class Child {
    String field1;
    String field2;
}
```
My goal is unwrapping Child class during serialization, namely change original (serialize without `@JsonUnwrapped`) JSON output from JSON1:
```
{
  "c1" : {
    "field1" : "1",
    "field2" : "2"
  }
}
```
to JSON2:
```
{
  "field1" : "1",
  "field2" : "2"
}
```
and keep the deserialization process untouched, namely read JSON1, I can still get the correct Parent bean. 

`@JsonUnwrapped` works fine in serialization, but does not meet my requirement in deserialization. If I deserialize with JSON1, result is a Parent bean with nested Child `c1`, but all fields in `c1` are null. The only workaround is deserializing JSON2.

**Comment by cowtowncoder** [comment]
@jf08300368 In your case, annotation to use would be `@JsonValue`. In future, let's not tack on other related questions into existing issues if they are not for same problem.
