### ISSUE TITLE
Allow `@JsonAnySetter` to flow through Creators

### ISSUE THREAD

**Issue by bimargulies** [FasterXML/jackson-databind#562]
I could speed up some code if I could write:

```
@JsonCreator
public MyClass(@JsonProperty("a") String a, @JsonAnySetter Map<String, Object> leftovers) {}
```

**Comment by whiskeysierra** [comment]
:+1: Is this something that you already considered putting in?

**Comment by cowtowncoder** [comment]
I thought there was already an issue for this one? (JsonAnySetter not working with creator).

**Comment by cowtowncoder** [comment]
Considered, yes, had time to try to tackle, no. Would definitely be nice thing to support.

**Comment by huhlig** [comment]
Any likelihood this will land in 3.x?

**Comment by davidmoten** [comment]
I'd also like to see this feature. As a workaround for the immutability enthusiasts, here's an example of using JsonAnySetter in an immutable class (swap out the Map/HashMap for an immutable equivalent as you like). The trick is that the JsonAnySetter method can be made private.

```java
@JsonAutoDetect(fieldVisibility = Visibility.ANY, creatorVisibility = Visibility.ANY, setterVisibility = Visibility.ANY)
public static final class WithMap {

    @JsonProperty("name")
    private String name;

    @JsonAnyGetter
    private Map<String, String> map;

    @JsonCreator
    public WithMap(@JsonProperty("name") String name) {
        this.name = name;
        this.map = new HashMap<>();
    }
    
    public WithMap(String name, Map<String, String> map) {
        this.name = name;
        this.map = map;
    }
    
    @JsonAnySetter
    private void put(String key, String value) {
        map.put(key, value);
    }
    
    public String name() {
        return name;
    }

    public Map<String, String> map() {
        return Collections.unmodifiableMap(map);
    }
}
```

**Comment by cowtowncoder** [comment]
@JooHyukKim I think we could use a "failing" test case for this, as pre-cursor to #3439.

**Comment by cowtowncoder** [comment]
Added a failing test, as a minor help for anyone considering to try to implement.

Also, made `@JsonAnySetter` applicable to (constructor) parameters in `jackson-annotations` 2.17 (was not previously).

**Comment by JooHyukKim** [comment]
> Also, made `@JsonAnySetter` applicable to (constructor) parameters in `jackson-annotations` 2.17 (was not previously).

This is great. Thank you for taking care of things in advance.

**Comment by cowtowncoder** [comment]
Np. Needed that already for reproduction :)

**Comment by cowtowncoder** [comment]
Quick note: really hoping to get this resolved for 2.18 -- and I think there's a good chance this can happen.

**Comment by cowtowncoder** [comment]
Thanks to PR by @JooHyukKim this is now FINALLY implemented, merged for inclusion in 2.18.0!!!

**Comment by Nick-Minutello** [comment]
Excellent. When is 2.18.0 expected to be released ?

**Comment by JooHyukKim** [comment]
@Nick-Minutello This week. Please refer to https://groups.google.com/u/2/g/jackson-dev/c/6JaMbhEFwtY
