### ISSUE TITLE
Serialization of Transient fields with public getters not happening

### ISSUE THREAD

**Issue by rohitbansal03** [FasterXML/jackson-databind#573]
In reference to: https://github.com/FasterXML/jackson-databind/issues/296

Recently I upgraded fasterxml version from 2.0.0 to 2.3.3 and with this, facing a major impacting change throughout the application. The @Transient fields with public getters were serialized before, but now none of these is being serialized.

With above change, I would have to create explicitly @JsonProperty over getters of each and every transient field to be able to serialize as before. Looking for a better approach or some flag in SerializationFeature to be able to do this.

Any help appreciated!

**Comment by ssunzulily** [comment]
The choice for Jackson to even care about hibernate's annotation is beyond me. Are these guys high or something?

**Comment by cowtowncoder** [comment]
@ssunzulily perhaps it could be taken as a compliment that Jackson would be aware of various annotations of other frameworks :)

**Comment by ssunzulily** [comment]
@cowtowncoder This kind of tightly couple yet weakly documented things with questionable value? No.

**Comment by cowtowncoder** [comment]
@ssunzulily Um, I am not sure I get your meaning here. No, jackson-databind does not read such annotations. Optional jackson-datatype-hibernate module does. Latter makes sense. Someone perhaps thought former does; not so.

**Comment by ssunzulily** [comment]
@cowtowncoder I apologize if that is the case. I was using dropwizard. I guess that included the optional module
