### ISSUE TITLE
Pass one more argument to `JsonSerializer.isEmpty()`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#588]
Currently `JsonSerializer.isEmpty()` only takes a single argument, value to check.
But since some of configuration settings affect determination of emptiness (specifically, `SerializationConfig.getSerializationInclusion()`), it would make sense to pass `SerializationConfig`.
But it may be that some other per-call information will also be needed, so let's instead pass `SerializerProvider`, which gives full access to all available configuration.

Existing method needs to be deprecated, but supported for at least until 2.6 (and probably later); existing serializers should be upgrade in 2.5 to work with both methods.

**Comment by kellerassel007** [comment]
Unfortunately still not solved issue #497 "Add new JsonInclude.Include feature to exclude maps after exclusion removes all elements. "

**Comment by cowtowncoder** [comment]
@kellerassel007 Both issues are closed at this point: if there is a case that does not work with later versions (esp. 2.9.6), please file a new issue with reproduction. It may refer to this and/or 457 for context, but otherwise explain what is not working.
