### ISSUE TITLE
@JsonValue on enum not used when enum value is a Map key

### ISSUE THREAD

**Issue by chrylis** [FasterXML/jackson-databind#594]
I have a Java enum that uses an `@JsonValue` to provide a short key for serializing the values. This works perfectly with my current `Set<MyEnum>`. However, I'm needing to store more information than just presence or absence, and I'm converting that to a `Map<MyEnum,Metadata>`.

Jackson uses the enum's full value name instead of the `@JsonValue` field as the key.

    public enum MyEnum {
        VALUE_WITH_A_REALLY_LONG_NAME_HERE("longVal");

        @JsonValue
        public String getKey() { return this.key; }
    }

    public class MyStuff {
        String id;
        Map<MyEnum,Metadata> metadata = new EnumMap(MyEnum.class);
    }

Expected output:

    {"id": "foobar", "metadata": {"longVal": /* object */} }

Actual output:

    {"id": "foobar", "metadata": {"VALUE_WITH_A_REALLY_LONG_NAME_HERE": /* object */} }

**Comment by cowtowncoder** [comment]
Oh. Looks like unit test was written wrong, and this does NOT actually work as of 2.6.2.

I hope to fix this for good for 2.6.3 for what that is worth.
