### ISSUE TITLE
Add a mechanism for using `@JsonCreator.mode` for resolving possible ambiguity between delegating- and property-based creators

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#614]
Now that https://github.com/FasterXML/jackson-annotations/issues/47 has been implemented, there's need for matching access via `AnnotationIntrospector`.

**Comment by wenxzhen** [comment]
Any example for reference? I have tried to set the JsonCreator with Jackson 2.8.6, but never make it.

Please help
Thanks,

**Comment by cowtowncoder** [comment]
@wenxzhen depends on what kind of problem you are to solve. Unit tests have lots of `@JsonCreator` examples, although many for quite specific use cases.

I should probably write a blog post detailing differences at some point.
