### ISSUE TITLE
Deserialization of @JsonUnwrapped creates objects with null attribute

### ISSUE THREAD

**Issue by jaeggir** [FasterXML/jackson-databind#615]
I have the following code (jackson 2.4.3):
```
public class Parent {
   @JsonUnwrapped
   Child c1;
}

public class Child {
   String field1;
}
```

Serialization works fine, Child.field1 is inlined in Parent as expected. However when I deserialize it again, field1 is null. Adding a constructor annotated with @JsonCreator did not work as well. Interestingly, the ObjectMapper does create two Child objects, one with and one without field1 set - unfortunately the second one is used (UnwrappedPropertyHandler seems the be responsible for that).

**Comment by jaeggir** [comment]
Thanks for looking into it! We have refactored that part of our application in the meantime. I tried to reproduce it in a minimal project but everything works as expected (as in your test case). So most likely the bug was not in jackson but in our application -> issue closed.

**Comment by cowtowncoder** [comment]
Thanks! For now I assume this is the case -- issue can always reopened if more info is found suggesting Jackson handling has issues.
