### ISSUE TITLE
Setting external class loader (useful for OSGI environment)

### ISSUE THREAD

**Issue by zdanek** [FasterXML/jackson-databind#624]
Currently there is only simple way to access classloader
```
Thread.currentThread().getContextClassLoader()
```
In OSGI env this simply does not work :(

Same as
https://jira.codehaus.org/browse/JACKSON-350

**Comment by cowtowncoder** [comment]
As per patch #854, it is now possible to construct `TypeFactory` that uses specified override `ClassLoader` for `findClass()` calls, and we made sure core Jackson pieces do resolution through `TypeFactory` and not old `ClassUtil` static method.

**Comment by zdanek** [comment]
Nice!

**Comment by larsp** [comment]
:+1:
