### ISSUE TITLE
Add a mechanism for writing sequences of values via `ObjectWriter.writeValues()`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#655]
It has been possible to read value sequences with `ObjectReader.readValues()` for a while; this is especially useful for formats like `CSV` that are basically sequences of more or less uniform values.
But there is no similar mechanism for writing, so developers have to construct `JsonGenerator` directly first, then use `ObjectMapper` (or `ObjectWriter`) on that. This is cumbersome.

It would make sense to add a new sequence writer abstraction, accessible via `ObjectWriter`; method could be named `ObjectWriter.writeValues()`.

**Comment by l15k4** [comment]
Hey,  is it possible to choose separator? It uses `space` separator by default, I would need EOL separator.

I tried `writer.withRootValueSeparator("\n")` but that's not it.

**Comment by l15k4** [comment]
Got it, it was the `MinimalPrettyPrinter`
