### ISSUE TITLE
@JsonPropertyOrder causes deserialization failure (unresolved forward reference)

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#658]
Jackson 2.4.4 is able to successfully deserialize forward references, but it fails to do so if @JsonPropertyOrder requires serializing "parent" references after "child".

Testcase: https://gist.github.com/cowwoc/e31e96e093a2981f90bf

Inserting "parent" before "child" in @JsonPropertyOrder, or removing "child" fixes the problem.

**Comment by cowtowncoder** [comment]
At this point I am not sure if the original problem still exists (a few bugs have been fixed that could have triggerd this). If it is, a reproduction with 2.8.0 would be needed. For now, I'll close as there's nothing for me work on here.
