### ISSUE TITLE
Expanding capabilities of @JsonRootName

### ISSUE THREAD

**Issue by RutledgePaulV** [FasterXML/jackson-databind#662]
### Disclaimer

I'm not sure where to put something like this, so if it should be elsewhere let me know. 
### Proposal

I would like to propose expansion of the `@JsonRootName` annotation's usage to allow specifying more than a single level of nesting. In order to avoid creating a custom syntax and remain valid among json keys, I propose the following interface:

`public String[] value() default "";`

Which would be used like:

```
@JsonRootName( value = {"root", "results", "resultA"} )
public class ResultA{
    ....
}
```

With the idea that it would allow the deserialization of:

```
{
    "root": {
       "results": {
            "resultA": {
                 ...
             }
        }
    }
}
```
### Naive Implementation

The approach I've implemented for my own purposes to extract the relevant piece before reading as a particular class (I'm not suggesting this be the implementation, just giving an example):

```
 private String extractRelevant(String[] pathSegments, String serialized) throws IOException {
        JsonNode node = objectMapper.readTree(serialized);
        for (String segment : pathSegments) {
            if (StringUtils.isNotBlank(segment)) {
                node = node.get(segment);
            } else {
                return node.toString();
            }
        }
        return node.toString();
    }
```
### Why?

I recently started consuming an API that provides some meta-data around each of the responses that it provides. This information may be useful for them and some more advanced API's, but in reality I'm only interested in consuming the inner contents. I got around this by definining a custom annotation and custom deserializer (that unfortunately couldn't extend JsonDeserializer, until this is released: https://github.com/FasterXML/jackson-databind/issues/165).

There's a strong possibility that there already exists a preferred way to handle this situation and I'm just not aware of it. If that's the case, feel free to direct me to some documentation and close this ticket.

I think this particular approach has the added bonus of being entirely backwards compatible and (I think) pretty simple to implement once these questions are answered:
### Questions
- What's the behavior if the annotation specifies a path that doesn't exist? 
- Can the annotation define an element in the array? What would that look like? 
  ex: `@JsonRootName( value = {"root", "results[0]"} )`, what happens if the element doesn't exist in the   array?
### Suggestions

The question crossed my mind as to whether this should be extended to field annotations and the like. Common sense quickly said "NO", this should only be used for classes for this kind of usecase, not arbitrary deserialization mappings since that just invites problems.
#### Concern:

it may be considered a deviation from the generally agreed upon best-practice that a model in your application should be the same as the data model being consumed.
#### Response:

JSON is often used to represent nested object relationships, this just encourages consumption in that manner while decreasing the amount of overhead involved with narrowing a verbose response to the relevant information.
#### Concern:

`@JsonRootName` might be a confusing name since using this method, you could technically point to something that isn't really a "root node" of the response, instead it is the "root node" upon which the object should be deserialized.
#### Response:

Uh, I agree it might be unclear. The reason I suggested extending this interface is because the single-element use case would be no different than the existing behavior. I think it is probably best to add it here.

**Comment by ttimot24** [comment]
Is this one implemented in Jackson?

**Comment by cowtowncoder** [comment]
No plans to implement any time soon, closing.
