### ISSUE TITLE
The method _parseInteger of StdDeserializer

### ISSUE THREAD

**Issue by wenzis** [FasterXML/jackson-databind#664]
The method _parseInteger of StdDeserializer auto handle JsonToken.VALUE_NUMBER_FLOAT to JsonToken.VALUE_NUMBER_INT,could you support enum to prohibit this feature?
_parseShort、_parseIntPrimitive and so on.

**Comment by cowtowncoder** [comment]
Added `DeserializationFeature.ACCEPT_FLOAT_AS_INT`, disabling of which prevents coercion from JSON (etc) floating-point numbers into int/long/BigInteger.

**Comment by Skarafaz** [comment]
Just noticed this crazy behaviour... no words! Having DeserializationFeature.ACCEPT_FLOAT_AS_INT = true as default is simply insane. Truncating a float means loosing information, so it MUST NOT be the default.

**Comment by cowtowncoder** [comment]
@Skarafaz you have right to voice your opinion. And I am free to disregard it.
If you want it changed, GO FUCKING CHANGE IT on your set up.
