### ISSUE TITLE
ObjectMapper()#convertValue() doesn't respect the field name's case of pojo

### ISSUE THREAD

**Issue by AlexLuya** [FasterXML/jackson-databind#668]
Hello,
     For a special reason,I need that the all fields's name of POJO to  be started with upper case.It seems that ObjectMapper()#convertValue() doesn't make exact conversion,the all keys of result map will  start with lower case.I think it shouldn't do any assumption but make exact conversion.

**Comment by cowtowncoder** [comment]
I'd need a test case to demonstrate the problem to know if I agree with this, i.e. whether you are observing a bug or feature.

**Comment by djxhero** [comment]
same problem

**Comment by cowtowncoder** [comment]
@djxhero If you have remaining problems, please file an issue with reproduction of the problem. As you can see from comment 3 years ago, what is missing is actual piece of code to show what exactly is happening.
