### ISSUE TITLE
Spring CGLIB proxies not handled as intended

### ISSUE THREAD

**Issue by zolyfarkas** [FasterXML/jackson-databind#674]
in BeanUtil.isCglibGetCallbacks 

the callbacks is not detected because spring repackages cglib: org.springframework.cglib....

changing:

            if (pname.startsWith("net.sf.cglib")
                // also, as per [JACKSON-177]
                || pname.startsWith("org.hibernate.repackage.cglib")) {
                return true;
            }

to: 

            if (pname.contains("cglib") // also, as per [JACKSON-177]
                    ) {
                return true;
            }

would work,  with the disadvantage or other cglib name usages....

**Comment by cowtowncoder** [comment]
I think I'd rather be strict here, so adding another variant is fine.
However, what'd really be neat would be to have a unit test to verify these cases.
Also perhaps Spring module would be good, if there are other commonly encountered other issues.

But for now, I think I'll just add one more case. This is deep enough in code that removing a check that shouldn't be applied is difficult, so cost of false positive is non-trivial.
