### ISSUE TITLE
Typo in method name.

### ISSUE THREAD

**Issue by aleksandy** [FasterXML/jackson-databind#678]
[hasDefuaultValue()](jackson-databind/src/main/java/com/fasterxml/jackson/databind/PropertyMetadata.java)

**Comment by cowtowncoder** [comment]
Which class?

**Comment by floating-cat** [comment]
This class:
`src/main/java/com/fasterxml/jackson/databind/PropertyMetadata.java `

https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/PropertyMetadata.java#L147

**Comment by cowtowncoder** [comment]
Ok. Rats.

Well, since it is an API change, unfortunately need to go in 2.6.0, deprecating old, adding new method.

Thank you for reporting this.
