### ISSUE TITLE
Stream not closed in databind.ObjectReader

### ISSUE THREAD

**Issue by dkwakkel** [FasterXML/jackson-databind#683]
It seems the stream created with _inputStream is not closed, see databind.ObjectReader:

```java
   @SuppressWarnings("unchecked")
    public <T> T readValue(File src)
        throws IOException, JsonProcessingException
    {
        if (_dataFormatReaders != null) {
            return (T) _detectBindAndClose(_dataFormatReaders.findFormat(_inputStream(src)), true);
        }
        return (T) _bindAndClose(_parserFactory.createParser(src), _valueToUpdate);
    }

    public <T> MappingIterator<T> readValues(File src)
        throws IOException, JsonProcessingException
    {
        if (_dataFormatReaders != null) {
            return _detectBindAndReadValues(
                    _dataFormatReaders.findFormat(_inputStream(src)), false);
        }
        return _bindAndReadValues(_parserFactory.createParser(src), _valueToUpdate);
    }
```

**Comment by cowtowncoder** [comment]
Did you bump into a bug where it seems like file handles are leaking, or is this just based on looking at the code? Methods ending with `close` typically indicate that stream would be closed, as long as core package knows it is "managed" (i.e. created by Jackson itself).

**Comment by dkwakkel** [comment]
Thanks I did not notice _bindAndCloseBy. I found the problem by looking at the code. But even if _bindAndClose closes the stream, it still can go wrong if any exception is thrown between the closing and creation of the input stream. I would expect try-with-resource or a finally block is used.

**Comment by cowtowncoder** [comment]
Try-with-resource is Java8 only, so that's not an option. But if you had peeked inside those methods, you would have found try-catch blocks.

**Comment by dkwakkel** [comment]
If _dataFormatReaders.findFormat throws an exception your stream will not be closed.  The try-finally scope must cover all logic which is using the stream. So normally code is written as:
InputStream in = new ...;
try {
  doThingsWithStream(in);
} finally {
  in.close();
}

**Comment by cowtowncoder** [comment]
Yes, I am somewhat familiar with this Java pattern, after writing Java for past 18 years.

**Comment by dkwakkel** [comment]
Congratulation! We have the same java birthday :-) Happy coding!
