### ISSUE TITLE
FAIL_ON_NUMBERS_FOR_ENUMS does not fail when integer value is quoted

### ISSUE THREAD

**Issue by kllp** [FasterXML/jackson-databind#684]
I'm using Jackson 2.4 and would like to use the FAIL_ON_NUMBERS_FOR_ENUMS deserialization feature.

This seems to be working when the json value is type int without quotes.  However, when the json value is a quoted integer, it does not throw an exception, and converts the value based on enum ordinal

**Comment by cowtowncoder** [comment]
Ah. Yes, sounds like a bug there.

**Comment by cowtowncoder** [comment]
Fixed for 2.5.1

**Comment by kllp** [comment]
Thank you!
