### ISSUE TITLE
Json deserializing in new version after upgrade

### ISSUE THREAD

**Issue by AlexandrSokolov** [FasterXML/jackson-databind#686]
For some reason I cannot edit code correctly, In preview mode you don't see some code.
I've created issue here: http://stackoverflow.com/questions/28109528/rest-jackson-jsondeserialize-stackoverflowerror-after-upgrade

You can see all description in good format there.

In the previous version of jackson the following code worked fine:

```java
import org.codehaus.jackson.map.JsonDeserializer;

import org.codehaus.jackson.JsonParser;

import org.codehaus.jackson.map.DeserializationContext;

@JsonDeserialize(using = RoleDeserializer.class)
public interface RoleDto {}

public class RoleDeserializer extends SomeSharedDeserializer<RoleDto> {}


public class SomeSharedDeserializer<T> extends JsonDeserializer<T> {
    @Override
    public T deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException
    {
        return jp.readValueAs(getImplementation());
    }

    public Class<? extends T> getImplementation(){ ... returns some generated implementation of RoleDto }
}
```

After we migrated to the last jackson version we got an exception:

```java
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of RoleDto, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
```

Ok, as in jackson new packages are used, we upgraded them to:

```java
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer;
```

The deserializer is visible now, however, we get StackOverFlow exception. Object mapper reads value (line 3023):

```java
    DeserializationContext ctxt = createDeserializationContext(jp, cfg);
    JsonDeserializer<Object> deser = _findRootDeserializer(ctxt, valueType);
    // ok, let's get the value
    if (cfg.useRootWrapping()) {
        result = _unwrapAndDeserialize(jp, ctxt, cfg, valueType, deser);
    } else {
        result = deser.deserialize(jp, ctxt);
    }
```

We go to the line:

    result = deser.deserialize(jp, ctxt);

It causes to infinite loop.

One of the way which is recommended is to implement our own SomeSharedDeserializer as:

```java
    ObjectCodec oc = jp.getCodec();
    JsonNode node = oc.readTree(jp);
    //here manually create new object and return it
```

But our classes are generated. As another solution I tried to use 

```java
ObjectMapper mapper = new ObjectMapper();
mapper.readValue(jp, getImplementation());
```

But got the same result - StackOverflow exception.

How can we fix it? Can we use some deserializer, to pass it JsonParser instance, generated class that implements base interface and without StackOverflow?

PS: sorry for formating of the issue, I could not fix it.

**Comment by cowtowncoder** [comment]
If the goal is to map an abstract type (class or interface) to a concrete implementation, there is no need to add custom deserializers. Instead, you can instantiate `SimpleModule`, use `addAbstractTypeMapping` to add mappings, and register module (mapper.registerModule(mySimpleModule));

**Comment by AlexandrSokolov** [comment]
@cowtowncoder:
Your answer is too general. Could you give me a more detailed example?
I've added a new SimpleModule with new - interface to concreate implementations - mapping.
I've registered in in ObjectMapper. 
What's next? How it helps? How to deserailze? I've checked the code in the TestSimpleModule class, but could not find the usage of addAbstractTypeMapping method.

Why don't you add a way to deserialize without breaking old mechanisms? Add a parameter, or method in order to run, for example,(JsonParser) jp.readValueAs(getType()); without getting StackOverflowError. Or via JsonMapper object.

All examples you offer now to deserialize is - manually take data of JsonParser nodes and use them to construct object. But it is extra work wich could be avoided in the previous version.

**Comment by cowtowncoder** [comment]
You deserialize it like you deserialize anything else, either via `ObjectMapper` (`readValue()`) or using `JsonParser` (`readValueAs()`).Modules are simple mechanisms for adding new handlers in modular fashion, without trying to sub-class existing components; and to allow building extension libraries (sets of serializers/deserializers for 3rd party datatypes).
What registration essentially does is to translate given base/abstract type into concrete type, look for deserializer. 

As to why this worked with 1.x I don't know. If you could write a self-contained unit test, I can run it and see. From description I do not see anything obviously wrong there. I can not think of an intentional change between 1.x and 2.x that would result in a new failure mode here.

**Comment by AlexandrSokolov** [comment]
@cowtowncoder, here is a unit test, that can help you to reproduce the problem, the testStackOverflowError method will fail with the java.lang.StackOverflowError:
<code>
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Created by alexandr on 27.01.15.
 */
public class JsonDeserializerTest
{
    static abstract class RestDtoDeserializer<T> extends JsonDeserializer<T>
    {
        @Override
        public T deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException
        {
            return jp.readValueAs(getImplementation());
        }

        public abstract Class<? extends T> getImplementation();
    }

    static class ExampleRestDtoDeserializer extends RestDtoDeserializer<AbstractType>{

        @Override
        public Class<? extends AbstractType> getImplementation()
        {
            return ExampleConcreateType.class;
        }
    }

    @JsonDeserialize(using = ExampleRestDtoDeserializer.class)
    static interface AbstractType
    {
        String getName();
        void setName(String name);
    }

    static class ExampleConcreateType implements AbstractType
    {

        private String name;

        @Override
        public String getName()
        {
            return name;
        }

        @Override
        public void setName(final String name)
        {
            this.name = name;
        }
    }

    @Test
    public void testStackOverflowError() throws Exception
    {
        ObjectMapper mapper = new ObjectMapper();
        AbstractType result = mapper.readValue("{\"name\":\"testName\"}", AbstractType.class);
        assertNotNull(result);
    }
}
</code>

**Comment by AlexandrSokolov** [comment]
@cowtowncoder , the reason of the problem:
In the previous versions the class, responsible for the deserializer creation was StdDeserializerProvider, line 397:
<code>
protected JsonDeserializer<Object> _createDeserializer(DeserializationConfig config, 
            JavaType type, BeanProperty property)
        throws JsonMappingException
    {
        if (type.isEnumType()) {
            return (JsonDeserializer<Object>) _factory.createEnumDeserializer(config, this, type, property);
        }
        if (type.isContainerType()) {
            if (type.isArrayType()) {
                return (JsonDeserializer<Object>)_factory.createArrayDeserializer(config, this,
                        (ArrayType) type, property);
            }
            if (type.isMapLikeType()) {
                MapLikeType mlt = (MapLikeType) type;
                if (mlt.isTrueMapType()) {
                    return (JsonDeserializer<Object>)_factory.createMapDeserializer(config, this,
                            (MapType) mlt, property);
                }
                return (JsonDeserializer<Object>)_factory.createMapLikeDeserializer(config, this,
                        mlt, property);
            }
            if (type.isCollectionLikeType()) {
                CollectionLikeType clt = (CollectionLikeType) type;
                if (clt.isTrueCollectionType()) {
                    return (JsonDeserializer<Object>)_factory.createCollectionDeserializer(config, this,
                            (CollectionType) clt, property);
                }
                return (JsonDeserializer<Object>)_factory.createCollectionLikeDeserializer(config, this,
                        clt, property);
            }
        }

        // 02-Mar-2009, tatu: Let's consider JsonNode to be a type of its own
        if (JsonNode.class.isAssignableFrom(type.getRawClass())) {
            return (JsonDeserializer<Object>)_factory.createTreeDeserializer(config, this, type, property);
        }
        return (JsonDeserializer<Object>)_factory.createBeanDeserializer(config, this, type, property);
    }
</code>

When we pass concreate implementation as the "type" parameter, it creates defaults BeanDeserializer instance.

In new version the com.fasterxml.jackson.databind.deser.DeserializerCache.java class is in charge of the deserializer creation. The main difference, is here, see method :
com.fasterxml.jackson.databind.deser.DeserializerCache.java, line 317
<code>
protected JsonDeserializer<Object> _createDeserializer(DeserializationContext ctxt,
            DeserializerFactory factory, JavaType type)
....
        JsonDeserializer<Object> deser = findDeserializerFromAnnotation(ctxt,
                beanDesc.getClassInfo());
        if (deser != null) {
            return deser;
        }
...
</code>

For concreate implementation as the "type" parameter, it searchs and finds the JsonDeserialize annotation, applied to the base abstract class, and uses this deserializer for subtype. 
As a result we come into an infinite loop.

**Comment by AlexandrSokolov** [comment]
@cowtowncoder , sorry for editing, I cannot do anything with it. It works partly. Not convenient at all:(

**Comment by cowtowncoder** [comment]
@AlexandrSokolov No problem wrt editing -- not much we can do. I can clean it up. Thank you for providing the test case.

**Comment by cowtowncoder** [comment]
Ah. Yes, annotation visibility causes the issue, and there really isn't much that can be done for that, because annotation inheritance is a feature. There is no annotation-specific handling to choose what to inherit or how to merge; base class annotations are used unless specifically overridden.
So I don't think usage exactly as-is can be supported; the change from 1.x to 2.x may well be due to fix to handling to support other cases, that is, 1.x should have hit similar problem if annotation and deserializer resolution worked as designed.
So I suspect code unfortunately worked due to a flaw handling so to speak.

But as to work-arounds... First, it is possible to mask that annotation by adding `@JsonDeserialize` on sub-class. This should prevent usage of deserializer recursively.
Second, if you prefer annotation usage over adding abstract mapping (which I mentioned earlier, and which should work), you could change to instead do:

```java
@JsonDeserialize(as = ExampleConcreteType.class)
    static interface AbstractType
    {
    }
```

which defines mapping, without forcing use of specific custom deserializer.

**Comment by AlexandrSokolov** [comment]
@cowtowncoder 
You know, I think, there is a better option. To break recurrection, I want to create the BeanDeserializer instance and delegate it the process. But, it's not quite clear how to create it correctly. Here is a unit test:
<code>
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.BeanDescription;
import com.fasterxml.jackson.databind.DeserializationConfig;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.BeanDeserializerFactory;
import com.fasterxml.jackson.databind.type.SimpleType;

/**
 * Created by alexandr on 27.01.15.
 */
public class JsonDeserializerTest
{
    static abstract class RestDtoDeserializer<T> extends JsonDeserializer<T>
    {
        @Override
        public T deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException
        {
            DeserializationConfig config = ctxt.getConfig();

            SimpleType simpleType = SimpleType.construct(getImplementation());
            BeanDescription beanDesc = config.introspect(simpleType);
            JsonDeserializer deserializer = BeanDeserializerFactory.instance.buildBeanDeserializer(ctxt, simpleType, beanDesc);

            return (T) deserializer.deserialize(jp, ctxt);
        }

        public abstract Class<? extends T> getImplementation();
    }

    static class ExampleRestDtoDeserializer extends RestDtoDeserializer<AbstractType>{

        @Override
        public Class<? extends AbstractType> getImplementation()
        {
            return ExampleConcreateType.class;
        }
    }

    @JsonDeserialize(using = ExampleRestDtoDeserializer.class)
    static interface AbstractType
    {
        String getName();
        void setName(String name);
    }

    static class ExampleConcreateType implements AbstractType
    {

        private String name;

        @Override
        public String getName()
        {
            return name;
        }

        @Override
        public void setName(final String name)
        {
            this.name = name;
        }
    }

    @Test
    public void testStackOverflowError() throws Exception
    {
        ObjectMapper mapper = new ObjectMapper();
        AbstractType result = mapper.readValue("{\"name\":\"testName\"}", AbstractType.class);
        assertNotNull(result);
    }
}
</code>

Now I got exception:
<code>
com.fasterxml.jackson.databind.JsonMappingException: No _valueDeserializer assigned
 at [Source: {"name":"testName"}; line: 1, column: 2] (through reference chain: com.brandmaker.mms.service.portal.test.rest.ExampleConcreateType["name"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:757)
	at com.fasterxml.jackson.databind.deser.impl.FailingDeserializer.deserialize(FailingDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:242)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
	at com.brandmaker.mms.service.portal.test.rest.JsonDeserializerTest$RestDtoDeserializer.deserialize(JsonDeserializerTest.java:35)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2146)
	at com.brandmaker.mms.service.portal.test.rest.JsonDeserializerTest.testStackOverflowError(JsonDeserializerTest.java:79)
</code>

The real problem is inside the BeanDeserializer, its instance: _beanProperties has for each property (instance of SettableBeanProperty) the FailingDeserializer as _valueDeserializer instance. But for example for integer, it should be: NumberDeserializers$IntegerDeserializer, for string: StringDeserializer, they are typical. 
How can I fix it? How correctly can I create the BeanDeserializer isntance? I beleive it's the last issue that should be resolved and we'll find the workaround of the original problem.

**Comment by cowtowncoder** [comment]
No, I do not think you should ever try to construct a `BeanDeserializer` directly. If you want to modify an instance, that is possible however, and the mechanism to do so is `BeanDeserializerModifier`, instance(s) of which can be registered via `Module`. This allows you to add/replace/modify/reorder properties; and even replace the resulting deserializer instance. One possibility for you is to do latter, and take the original deserializer, retain a reference to it and delegate.

**Comment by AlexandrSokolov** [comment]
I cannot agree with you. Even via BeanDeserializerModifier I need a possibility to create for a Java POJO a standard Jackson deserializer. And the BeanDeserializer plays this role in the previous and the current Jackson versions. Here is the solution how it can be resolved in cusom deserializer:
<code>
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.BeanDescription;
import com.fasterxml.jackson.databind.DeserializationConfig;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.cfg.DeserializerFactoryConfig;
import com.fasterxml.jackson.databind.deser.BeanDeserializerFactory;
import com.fasterxml.jackson.databind.deser.ResolvableDeserializer;
import com.fasterxml.jackson.databind.type.SimpleType;
...
    public abstract class RestDtoDeserializer<T> extends JsonDeserializer<T>
    {
        @Override
        public T deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException
        {
            DeserializationConfig config = ctxt.getConfig();
            SimpleType simpleType = SimpleType.construct(getImplementationClass());
            BeanDescription beanDesc = config.introspect(simpleType);
            BeanDeserializerFactory instance = new BeanDeserializerFactory(new DeserializerFactoryConfig());
            JsonDeserializer deserializer = instance.buildBeanDeserializer(ctxt, simpleType, beanDesc);
            ((ResolvableDeserializer)deserializer).resolve(ctxt);
            return (T) deserializer.deserialize(jp, ctxt);
        }

        public abstract Class<? extends T> getImplementationClass();
</code>

**Comment by cowtowncoder** [comment]
My position here is simple: I do not think users should ever explicitly create a `BeanDeserializer`. Doing so is not and will not be supported. The class is an implementation detail. There are many other supported mechanisms for changing behavior of deserialization; this is not one.

You may choose to sub-class or directly create instances, nevertheless, and I am not going to make that impossible or harder. But it is part of internal API for core components and may be broken if needs of internal components change.

**Comment by AlexandrSokolov** [comment]
@cowtowncoder 
I don't like either how I created and used the concreate BeanDeserializer instance.
Anyway, to solve my problem I need a way to use the standard deserializer.
In my case it's the only possible solution.

If you add a support of this feature by the API it would be great! In order to deserize a bean without using ObjectMapper or JsonParser which cause to infinite loop in my case.

A client should now know anything about concrete implementations, but a client knows that the standard API does not work any more and the funcitonality that resolves the problem exists at the same time, but is hidden.
