### ISSUE TITLE
Feature request: Provide a means for an ObjectMapper to discover mixin annotation classes on demand

### ISSUE THREAD

**Issue by ljnelson** [FasterXML/jackson-databind#688]
In a large, maturing application, it is burdensome to have to store in some central location a list of all the possible mixin classes and their target classes (and then to keep that list up to date).

Adding mixin classes on demand can be thread-unsafe or "too late" in certain circumstances.

Instead, consider a callback-based mechanism or something similar, where a mixin class provider can be queried for the appropriate mixin `Class` to use for a given target `Class` that is about to be serialized.  That way, Jackson can be in full control as to when this happens, while the mixin class provider can be in full control over how such a mixin class is located and loaded.

http://fasterxml.github.io/jackson-databind/javadoc/2.4/com/fasterxml/jackson/databind/introspect/ClassIntrospector.MixInResolver.html might be a good starting point.

**Comment by cowtowncoder** [comment]
As per commit message, finally found time to implement. By default it is possible to specify both direct mappings (lower precedence) and separate custom resolver (higher precedence).

**Comment by ljnelson** [comment]
Beautiful; thanks!

**Comment by cemo** [comment]
@cowtowncoder Is this means that I can extend a class and add easily properties on the fly with mixin? It seems that I just need to set a custom `MixInResolver`? Right? I am dying for this feature :)

**Comment by cowtowncoder** [comment]
@cemo Yes exactly, that is the idea here. Just implement `MixInResolver`.

How well it works depends on the use case I imagine, for now assumption is that there is actual class to take annotations from -- would be great to make that more dynamic, but one step at a time.

**Comment by cemo** [comment]
It would be awesome to have a feature to include MixIn properties which are not present on actual class. For example documentation of [mixin] has an example:

```
abstract class MixIn {
  MixIn(@JsonProperty("width") int w, @JsonProperty("height") int h) { }

  @JsonProperty("width") abstract int getW(); // rename property
  @JsonProperty("height") abstract int getH(); // rename property
  @JsonIgnore int getSize(); // we don't need it!
  
}
```

a new property such as `area` can easily be added to it. :) Should I open a new ticket? 

This feature will be really very nice addition. Even a mixin class can extend actual class and add new properties on the fly. Extending provides not only IDE simplifications for refactoring but also easy to new properties. 



[mixin]: http://wiki.fasterxml.com/JacksonMixInAnnotations

**Comment by cowtowncoder** [comment]
I am not sure I follow how mix-ins could add new properties -- all they can do is to add annotations to existing members of actual classes. No code from mix-ins is added or invoked; that would require bytecode manipulation. Mix-in classes are never used in any other way; being class definitions and not instances, they have no state. So what would values of such virtual properties be?

Jackson 2.5 did add possibility of virtual properties, on the other hand, with `@JsonAppend` (and underlying functionality that allows injection of virtual properties via other routes). Those may be added via mix-ins.
