### ISSUE TITLE
ObjectMapper.copy() does not copy AnnotationIntrospector

### ISSUE THREAD

**Issue by lev-kuznetsov** [FasterXML/jackson-databind#692]
ObjectMapper created via copy() call does not respect introspector set on the original. Here's an example  with JaxbAnnotationIntrospector
```java
@XmlRootElement
@XmlAccessorType (XmlAccessType.NONE)
public static class Foo {
  private @XmlElement int bar = 5;
}

public void copyWithIntrospector () throws Exception {
  ObjectMapper original = new ObjectMapper ();
  original.setAnnotationIntrospector (new JaxbAnnotationIntrospector (original.getTypeFactory ());
  Foo foo = new Foo ();
  System.out.println (mapper.writeValueAsString (foo));
  System.out.println (mapper.copy ().writeValueAsString (foo)); // fails
}
```

**Comment by cowtowncoder** [comment]
And this is with 2.5.0? There were some earlier fixes, so I just want to know which version is affected.

**Comment by lev-kuznetsov** [comment]
It looks like it's fixed in 2.5, didn't work as of 2.3.

**Comment by lev-kuznetsov** [comment]
Actually, I'm sorry, it's still there at 2.5

**Comment by cowtowncoder** [comment]
Ok thank you for verifying.

**Comment by cowtowncoder** [comment]
Actually I can not reproduce the problem with 2.5, so I need a unit test here. I check directly that the new object mapper uses same `AnnotationIntrospector`, via `SerializationConfig` and `DeserializationConfig`.

**Comment by lev-kuznetsov** [comment]
I'm sorry, you are right, there must be something else wrong with my setup.
