### ISSUE TITLE
ObjectMapper.readValue(String,Class) for MongoDB ObjectID throws JsonMappingException

### ISSUE THREAD

**Issue by ahmadux** [FasterXML/jackson-databind#695]
I am new at this so please bear with me.

I am trying to de-serialize a JSON string back to Java Object. It throws a JsonMappingException for the ID field. My ID's are auto-generated by MongoDB. HEre is what the string looks like before de-serialization:

 <i>{ "_id" : { "$oid" : "54d1df91c56df9457c8c6798"} , "_name" : "FORM DIV MODEL" .....and so on.</i>

And here is the excepiton:

<b>com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token</b>

The ID in the POJO is of type string and not ObjectId. I tried changing it to ObjectId but then other areas start to break. What am I doing wrong?

**Comment by cowtowncoder** [comment]
You should use mailing list or support forums for questions like this; issue tracker is for reporting problems and requesting new features.

As to your problem, it appears that a POJO property that expects `java.lang.String` is being given a JSON Object; and in general databinder has no idea how that should work.

I am guessing, however, that you are missing a custom deserializer that would handle a native mongo datatype. It would know what to do with such a serialization. Or, conversely, native serializer that would know how to serialize id objects as Strings, and not as JSON Objects.
But I haven't used mongodb or drivers so I don't know much details. Members of user or dev mailing lists would probably have a better idea.

**Comment by ahmadux** [comment]
Date: Wed, 4 Feb 2015 10:06:12 -0800
