### ISSUE TITLE
Copy constructor does not preserve `_injectableValues`

### ISSUE THREAD

**Issue by drcrallen** [FasterXML/jackson-databind#696]
Currently the [copy constructor](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L408) makes no effort to copy injectable values. I'm not quite sure what the proper behavior of this would be, whether the ObjectMapper copy should retain a copy of the values at the time of the copy, or if the copy and original should just point to the same instance of the injectable values. Or if it just needs to be noted in the [injectables documentation](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L1521) that the injectables are not attempted to be preserved across copies.

**Comment by drcrallen** [comment]
It is worth noting that currently there is no way to recover `_injectableValues` without resorting to reflection or independently retaining the original value passed to `setInjectableValues`. If someone has a workaround I'd appreciate it.

**Comment by cowtowncoder** [comment]
Right. I had to think for a bit, to figure out whether this is a bug or feature.
I think it is a bug, and that settings should be copied. And as (or, more) importantly, ensure same happens with `ObjectReader`, which is the preferred way of interacting with configuration these days.

As to whether these should accessible or not... so far I haven't thought they need to be made visible, hence no accessor added. I can add one; they are not state secret either. :)

**Comment by cowtowncoder** [comment]
Fixed; 2.5.1 will copy injectables as expected, and 2.6 has additional accessors.

Thank you again for reporting this!
