### ISSUE TITLE
No findEnumSerializer in Serializers.Base() like in Deserializers.Base()

### ISSUE THREAD

**Issue by dn2k-dev** [FasterXML/jackson-databind#702]
Hi,

We use Custom EnumResolver and Custom desrializer that we define for each Enum class in Deserializers.Base().findEnumDeserializer ()
But similar function doesnt exist for Serializers.Base()

**Comment by cowtowncoder** [comment]
No, because it does not exist in `Serializers`. `Serializers` is bit less refined than `Deserializers`, so 3 types (beans, trees, enums) are all handled via base `findSerializer()` method, so override that one.
