### ISSUE TITLE
Different name in Serialize operation and Deserialize operation 

### ISSUE THREAD

**Issue by haddouti-khalid** [FasterXML/jackson-databind#710]
Hello !

In my class Example, i have the property value. I want convert my instance to this JSON : {"NewValue" : 5} and create my instance using this json {"value" : 5}.

How can i do this , because the annotation @JsonProperty is applicable in Getter and Setter.

Thanks

**Comment by cowtowncoder** [comment]
You ask this on mailing list or StackOverflow. Github issues is not meant for usage questions but for bug reporting and feature reqeuest.
