### ISSUE TITLE
TypeFactory.constructParametrizedType(..) Javadoc is incorrect

### ISSUE THREAD

**Issue by Bercon** [FasterXML/jackson-databind#711]
TypeFactory.constructParametrizedType(..) Javadoc refers to non-existing methods and is obviously copy-pasted from somewhere else since it doesn't explain how to use the method.

**Comment by Bercon** [comment]
Excellent work! *thumbs up*

**Comment by cowtowncoder** [comment]
Thank you for reporting this -- I know documentation is a weak spot, and specific suggestions are useful. This way pieces that get read most should at least be in adequate condition.
Let us know of other bad areas when you come across them. And of course pull requests are welcome too, if you have good suggestions.
