### ISSUE TITLE
`jackson-databind-2.4.4` depends on `jackson-annotations-2.4.0`.

### ISSUE THREAD

**Issue by izeye** [FasterXML/jackson-databind#714]
Although `jackson-annotations-2.4.4` exists,

is there any reason why `jackson-databind-2.4.4` depends on `jackson-annotations-2.4.0`?

I have no problem with it but it looks weird.

**Comment by cowtowncoder** [comment]
That is intentional. While annotation jar does nominally have patch version, there are absolutely no differences between ones. Personally, I would only release 2.4, but some users prefer to use identical version numbers, which is why 2.4.4 exists as a compromise.
Hope this helps.

**Comment by izeye** [comment]
@cowtowncoder Got it. Thanks for the explanation :-)

**Comment by cemo** [comment]
@cowtowncoder This is asked more than once. Using identical numbers in Jackson sounds better and more intuitive to me. What do you think?

**Comment by cowtowncoder** [comment]
@cemo If there is a way to automate this via Maven release plug-in, I don't care deeply enough either way. Right now changing annotations version is a manual task, and I don't think I was able to use `${project.version}' for dependency.
