### ISSUE TITLE
Generating String similar to JSON without quotes. 

### ISSUE THREAD

**Issue by cemo** [FasterXML/jackson-databind#715]
How can I configure Jackson to generate text similar to JSON without quotes? I will use this as a String for aesthetic purposes and set inside another `Map<String, String>`. What is the easiest way to create?

**Comment by cowtowncoder** [comment]
I think I need bit more information on what you mean by "similar to JSON without quotes".

If you mean 'raw' output ("just include this String verbatim with no modifications in output"), that would be via streaming API's `writeRaw()` and/or `writeRawValue()` (former adds no decorations whatsoever; latter adds necessary separators like commas).
And at databind level it can be done with `@JsonRawValue` annotation.

**Comment by cemo** [comment]
```
      ObjectMapper objectMapper = new ObjectMapper();
      HashMap<String, Object> map = new HashMap<String, Object>();
      map.put("a", 1);
      map.put("b", "hello");
      System.out.println(objectMapper.writeValueAsString(map));
```

This is generating:

```
{"a":1,"b":"hello"}
```

I want this: 

```
{a:1,b:hello}
```

**Comment by cowtowncoder** [comment]
Ok. It is possible to force use of unquoted property names with `JsonGenerator.Feature.QUOTE_FIELD_NAMES` (defaults to `true`, disable).
There is no setting for doing that to values: if you really want that, writing a custom unquoted-String serializer would be easy; it'd just use `writeRawValue()` instead of `writeString()`.

**Comment by Abhishek-P** [comment]
In stringSerializer with a WriterBasedJsonGenerator writeString() adds quotation marks  " at each end of the string. Since we already know the walue being passed is a string, do we need to add an extra pair of quotation marks ??
