### ISSUE TITLE
DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY should be enabled by default

### ISSUE THREAD

**Issue by murphyj** [FasterXML/jackson-databind#720]
It specifies the following in the documents:

``` 
ACCEPT_SINGLE_VALUE_AS_ARRAY

public static final DeserializationFeature ACCEPT_SINGLE_VALUE_AS_ARRAY

    Feature that determines whether it is acceptable to coerce non-array (in JSON) values to work with Java collection (arrays, java.util.Collection) types. If enabled, collection deserializers will try to handle non-array values as if they had "implicit" surrounding JSON array. This feature is meant to be used for compatibility/interoperability reasons, to work with packages (such as XML-to-JSON converters) that leave out JSON array in cases where there is just a single element in array.

    Feature is disabled by default. 
```

That seems fine and I understand what's going wrong except that you don't have to enable this functionality in the SerializationFeature. It seems like there's conflicting behaviour here with the DeserializationFeature where you can map `[ {} ]` correctly into a `List<T>` without doing in serialization but with deserialization you have to enable it.

Any reasons for this or is this a bug?

To clarify I'm using jackson 2.4.1

**Comment by cowtowncoder** [comment]
There is `SerializationFeature.WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED`, which typically is used with this feature. But without enabling it (disabled by default). no unwrapping should be done.

But I guess I don't quite understand the question here... I don't see a conflicting feature. In normal uses, neither is enabled, and Java arrays and `List`s get bound to and from JSON Arrays.
It is only necessary to enable features to support non-standard cases where "clever" output is omitting JSON array around single element. However, enabling the feature is permissive, allowing use of single-element as well. Perhaps this is what you referring to? If so, that is a feature to allow working with such variant content, but without requiring that.

**Comment by murphyj** [comment]
I'm going to have a discussion with the team who owns the system we're consuming the data from. I guess to clarify and understand whether this is actually an issue we need to understand how and why they're not outputting json arrays by default.

I'll get back to you if this is actually an issue or not.

**Comment by cowtowncoder** [comment]
@murphyj  Sounds good thanks!
