### ISSUE TITLE
ObjectWriter.writeValueAsString() should not throw JsonProcessingException

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#723]
http://jira.codehaus.org/browse/JACKSON-758?focusedCommentId=304834&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-304834 provided a good explanation of why it is impossible for the underlying StringWriter to throw IOException.

I agree with the author, you should catch the exception and throw `AssertionError` if it ever occurs. Technically speaking this will never occur and it is annoying to have to catch this exception in a 1000 different pieces of code.

**Comment by cowtowncoder** [comment]
It can still well throw a `JsonGenerationException`, so I do not quite see the importance of additional work here.

**Comment by cowwoc** [comment]
@cowtowncoder I assume that `JsonGenerationException` can only be thrown in the case of programming error (e.g. the class being serialized contains Jackson-specific annotations with conflicting/invalid information). Is that correct?

**Comment by cowtowncoder** [comment]
That, or `JsonSerializer` using invalid output sequences; or if there are no properties found for type, or many other problems. Actually `JsonGenerationException` would only come about streaming-level problems, and `JsonMappingException` for databind. So more generally `JsonProcessingException` is sub-type of things that may still occur.

**Comment by cowwoc** [comment]
Okay, so the point I was trying to make is that all the causes of this exception are unrecoverable. I believe this still holds true for all the cases you mentioned above, does it not?

And if the exception is unrecoverable, I would argue that it should be an unchecked exception. I fully understand why `JsonGenerationException` and `JsonMappingException` deserve to be checked exceptions when used by other parts of the codebase, but for this specific method I think we need an unchecked exception equivalent/wrapper.

**Comment by cowtowncoder** [comment]
I'll make this easy here: I don't like making special cases for particular write methods.
So signature shall stay as is, and callers are free to add convenience methods, or sub-class `ObjectMapper` as they see fit.

**Comment by raul1991** [comment]
I am using @Sneakythrows for it. It does put things under the carpet though 😀
