### ISSUE TITLE
Invalid JSON doesn't error when parsing

### ISSUE THREAD

**Issue by IBeaumont21** [FasterXML/jackson-databind#726]
The parser seems to stop once it has reached the closing ] or } that matches the opening [ or {.  Any characters after are ignored.  If characters appear after, shouldn't an exception be thrown as the content isn't valid JSON.
For instance, this is successful, when I would expect it to fail...
        ObjectMapper mapper = new ObjectMapper();
        JsonNode node = mapper.readTree( "[1][");

**Comment by cowtowncoder** [comment]
Yes. This is by design. If you want to catch such problems, you need to construct `JsonParser`, advance it manually. Existence of multiple root-level values is not considered a validity problem, but in your case, end-of-stream without matching ']' would be caught.
