### ISSUE TITLE
Pass `DeserializationContext' argument for `JsonDeserializer` methods "getNullValue()" and "getEmptyValue()"

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-databind#741]
Currently "getNullValue()" and "getEmptyValue()" methods do not take arguments. This works for simple cases, but does not allow any configurability via `DeserializationFeature`, or other standard deserialization functionality. But it should be possible to access that.

The way to implement this would be to add new overloaded variants, mark existing ones deprecated, and add bridge method calls for 2.6; as well as retrofit modules to use new variants.
Older versions may be removed at a later version, ideally at earlier 2.8.

**Comment by cowtowncoder** [comment]
Implemented: need to work through one unfortunate code path where context is not available, may need to refactor to support propertly.

**Comment by smaudet** [comment]
I took a hack at this, however I got confused amid the garden of various Factories, Modules, Providers, Delegators, and ClassUtils, and Abstract implementations with no direct implementation other than in tests...

Is there a road map to Jackson somewhere that I'm missing?

Or a 'right direction' to travel to get this sort of thing working?

I solved my original problem, incidentally, with a JsonSerialize annotation and a private class on a DTO, but feeling like I nearly got it right doing it the other way, I'm curious how I could/should have been going about using the fruits of this change...

**Comment by cowtowncoder** [comment]
@smaudet I am not quite sure what you are referring to here -- I assume it has to do with some other issue, and not this particular one (which is only about giving more access to code that checks for "emptiness" of a value)?

**Comment by smaudet** [comment]
https://github.com/FasterXML/jackson-databind/issues/347

I was referred on that thread (by yourself) to this one...perhaps I misunderstood something?

**Comment by cowtowncoder** [comment]
@smaudet Ok, it'd make most sense to add comment to that issue as your comment is directly relevant to it.

**Comment by mykobob** [comment]
Even though I added the needed parameters, the deserializer doesn't call the `getNullValue()` or `getEmptyValue()` Is there any reason why? I'm running jackson-databind-2.6.0
