### ISSUE TITLE
mapper.enable(JsonFeature...) from README.MD does not work

### ISSUE THREAD

**Issue by bcoughlan** [FasterXML/jackson-databind#750]
I'm new to Jackson so I didn't make a PR in case I'm wrong about this:

```
mapper.enable(JsonParser.Feature.ALLOW_COMMENTS);
```

This example from the readme doesn't compile in 2.4.4.

This however does:

```
mapper.configure(JsonParser.Feature.ALLOW_COMMENTS, true);
```

**Comment by cowtowncoder** [comment]
Right, the method was only added in 2.5. But maybe I should change the README just to be bit more backwards-compatible.

Thank you for pointing this out.

**Comment by bcoughlan** [comment]
Thanks, my confusion arose because `<jackson.version>` in the readme still points to 2.4.4.

**Comment by cowtowncoder** [comment]
Ah yes. But in general it is good to be bit more conservative with code samples. Good point either way!
