### ISSUE TITLE
@JsonProperty is ignored when used together with @JsonIgnore

### ISSUE THREAD

**Issue by prudnikov** [FasterXML/jackson-databind#751]
I have the following code:

```java
public class NoteDTO {
    @JsonProperty("created_at")
    protected Date createdAt;
}

public class NoteUpdateDTO extend NoteDTO {
    @JsonIgnore
    @JsonProperty("created_at")
    protected Date createdAt;
}
```
Jackson has a different settings and exception for unknown and ignored properties. In this case I want to catch `IgnoredPropertyException` and tell user that this property is read-only. Instead it throws `UnrecognizedPropertyException` when I try to parsee `{"created_at":"...."}`.

**Comment by cowtowncoder** [comment]
Right, currently this won't work, and even from documentation perspective is bit difficult to explain how precedences should work.
There is another issue to support read-only properties.

In theory, use of `@JsonGetter` and `@JsonSetter` might work. But I can't say for sure if it would help when combined with `@JsonIgnore`.

**Comment by cowtowncoder** [comment]
FWIW, the way to implement this functionality right now is to add setter and getter methods, and make setter throw the exception you want.

For Jackson 2.6.0, you can also use:

    @JsonIgnoreProperties(value={ "created_at" }, allowGetters=true)

which will ignore property wrt setters (deserialization), but expose it via getters (serialization).
