### ISSUE TITLE
Deserialize to `java.util.Map` while ignoring empty strings

### ISSUE THREAD

**Issue by tuscland** [FasterXML/jackson-databind#752]
Hello,

When deserializing a string to a `java.util.Map`, I am trying to ignore properties whose value is an empty string. Replacing empty strings with a `null` object is fine too.

I am having difficulties on finding a solution as every example I found were about POJO mapping. Could please someone explain how to do that? Thanks!

Best,
Cam

**Comment by cowtowncoder** [comment]
This is an excellent question for mailing lists.

With Jackson 2.5, it should be possible to annotate Map-valued property like so:

```java
@JsonInclude(content=Include.NON_EMPTY)
public Map<String,String> properties;
```

**Comment by tuscland** [comment]
Thanks!
I managed to solve my problem with a custom deserializer, Jackson 2.3.2 was required.

**Comment by iiliev2** [comment]
> This is an excellent question for mailing lists.
> 
> With Jackson 2.5, it should be possible to annotate Map-valued property like so:
> 
> ```java
> @JsonInclude(content=Include.NON_EMPTY)
> public Map<String,String> properties;
> ```

This is for serializing, how do we do this when deserializing?
