### ISSUE TITLE
Disabling SerializationFeature.FAIL_ON_EMPTY_BEANS does not affect canSerialize

### ISSUE THREAD

**Issue by nickwongdev** [FasterXML/jackson-databind#756]
Spring's REST Template calls this method on MappingJackson2HttpMessageConverter:

```java
public boolean canWrite(Class<?> clazz, MediaType mediaType) {
    return (this.objectMapper.canSerialize(clazz) && canWrite(mediaType));
}
```

However, this fails even though I have set: 

```java
converter.getObjectMapper().disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
```

And, in fact, it will serialize the payload just fine, even though it reports that it cannot:

```java
System.out.println(converter.getObjectMapper().canSerialize(EmptyModel.class));
System.out.println(converter.getObjectMapper().writeValueAsString(em));
System.out.println(converter.getObjectMapper().canSerialize(EmptyModel.class));
```

```
false
{}
false
```

Also, related to bug #703 , with version 2.5.1, the result is:

```
false
{}
true
```

I haven't had time to trace down what is enabling the actual serialization to go through on writeValueAsString, but I can try to comment later on this.

**Comment by cowtowncoder** [comment]
Thank you for reporting this: it does sound like a bug indeed.

**Comment by cowtowncoder** [comment]
Fix turned out to be bit more involved than I thought, so it will only go in 2.6.0, to minimize risk of regression in a patch release.

**Comment by nickwongdev** [comment]
Thanks! :dancers:
