### ISSUE TITLE
Dynamic modification of constructor argument annotations broke in 2.5.x

### ISSUE THREAD

**Issue by toadzky** [FasterXML/jackson-databind#758]
I have a custom annotation introspector that dynamically added `@JsonProperty` annotations to constructors based on `@ConstructorProperties`. When I tried updating to 2.5.2, I found it's completely broken. I spent a couple of hours digging through the code and here's what I found.

So the place where it all goes wrong is in the [BasicDeserializerFactory](https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.5.2/src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java#L423). The map of `BeanPropertyDefinition`s doesn't have anything in it. Which means by the time it gets [here](https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.5.2/src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java#L445) or [here](https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.5.2/src/main/java/com/fasterxml/jackson/databind/deser/BasicDeserializerFactory.java#L492), there are no named properties.

I tracked it back through the collection of properties in [POJOPropertiesCollector](https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.5.2/src/main/java/com/fasterxml/jackson/databind/introspect/POJOPropertiesCollector.java#L245), then into [AnnotatedClass.resolveCreators](https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.5.2/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedClass.java#L331). In [AnnotatedClass._constructConstructor](https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.5.2/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedClass.java#L768), no annotations are found, which means when we get to [_collectRelevantAnnotations](https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.5.2/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedClass.java#L888), of course, that nothing gets added.

I need it to use my annotation introspector to find annotations, or I need the `BasicDeserializerFactory` respect the values returned by it. Any suggestions?

**Comment by cowtowncoder** [comment]
Unfortunately implementation for collecting creator properties has been unstable for longest time, and there have been a few rewrites to support things like implicit names. So although all unit tests obvious pass, it is quite possible there are gaps.

A unit test would help. Version information (version upgraded from) might be useful as well.

**Comment by toadzky** [comment]
We are using 2.3.2. I managed to get it working with the implicit names. That method didn't exist in 2.3.x, so we weren't overriding it. Here's what I did to make it work:

````java
@Override
public String findImplicitPropertyName(AnnotatedMember member)
{
  if (member instanceof AnnotatedParameter)
  {
    if (((AnnotatedParameter) member).getOwner().hasAnnotation(ConstructorProperties.class))
    {
      return ((AnnotatedParameter) member).getOwner().getAnnotation(ConstructorProperties.class)
            .value()[((AnnotatedParameter) member).getIndex()];
    }
  }
  return super.findImplicitPropertyName(member);
}
````

**Comment by cowtowncoder** [comment]
@toadzky Ok good, and apologies for breakage. Glad that you were able to resolve the problem with later versions.

Handling of implicit names was necessary due to development of JDK8, Paranamer, and languages like Scala which can provide names for ctor/method parameters; something that did not exist when `AnnotationIntrospector` was first added.

In your case it is also possible that explicit names would work, but there have also been some changes for those calls. The main difference is really whether you would want names to be overridable by `NamingStrategy` or not (implicit names do get modified as per strategy; explicit ones not).
