### ISSUE TITLE
JacksonJaxbJsonProvider setTimeZone not working

### ISSUE THREAD

**Issue by hieuhcmus** [FasterXML/jackson-databind#760]
It seems to be that the function setTimeZone of JacksonJaxbJsonProvider does not work correctly.
I want to set the timezone to default timezone instead of GMT, but it didn't work
```
@Provider
@Produces(MediaType.APPLICATION_JSON)
class JacksonConfig extends JacksonJaxbJsonProvider {
	public JacksonConfig() {
		ObjectMapper mapper = new ObjectMapper();
		mapper.setSerializationInclusion(Include.NON_NULL);
		mapper.setTimeZone(TimeZone.getDefault());
		super.setMapper(mapper);
	}
}
```

When I change it to general way using ContextResolver, it worked

```
@Provider
@Produces(MediaType.APPLICATION_JSON)
public class JacksonConfig implements ContextResolver<ObjectMapper> {
	private ObjectMapper mapper;
	public JacksonConfig() {
		mapper = new ObjectMapper();
		mapper.setSerializationInclusion(Include.NON_NULL);
		mapper.setTimeZone(TimeZone.getDefault());
	}
	@Override
	public ObjectMapper getContext(Class<?> type) {
		return mapper;
	}
}
```

**Comment by cowtowncoder** [comment]
Since this seems related to JAX-RS provider, I think issue belongs at:

https://github.com/FasterXML/jackson-jaxrs-providers/issues

if you could re-create it there (I don't think github has a way of transferring issues, unfortunately).

**Comment by hieuhcmus** [comment]
Thanks, I will recreate this issue there

**Comment by cowtowncoder** [comment]
Recreated as: https://github.com/FasterXML/jackson-jaxrs-providers/issues/62
