### ISSUE TITLE
NPE in LRUMap.java (with Scala module)

### ISSUE THREAD

**Issue by selvin** [FasterXML/jackson-databind#767]
At jackson-databind-2.4.4-sources.jar
com/fasterxml/jackson/databind/util/LRUMap.java

public V get(Object key) {  return _map.get(key); }

Error: cascading.pipe.OperatorException: [TimeSeqPathedSource(/l...][com.twitter.scalding.RichPipe.eachTo(RichPipe.scala:478)] operator Each failed executing operation at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:107) at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39) at cascading.flow.stream.BufferEveryWindow$1.collect(BufferEveryWindow.java:68) at cascading.tuple.TupleEntryCollector.safeCollect(TupleEntryCollector.java:145) at cascading.tuple.TupleEntryCollector.add(TupleEntryCollector.java:133) at com.twitter.scalding.TypedBufferOp.operate(Operations.scala:503) at cascading.flow.stream.BufferEveryWindow.receive(BufferEveryWindow.java:125) at cascading.flow.stream.BufferEveryWindow.receive(BufferEveryWindow.java:41) at cascading.flow.hadoop.stream.HadoopGroupGate.run(HadoopGroupGate.java:93) at cascading.flow.hadoop.FlowReducer.reduce(FlowReducer.java:136) at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:444) at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:392) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:179) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:415) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1565) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:174) Caused by: **java.lang.NullPointerException at com.fasterxml.jackson.databind.util.LRUMap.get(LRUMap.java:47)** at com.fasterxml.jackson.databind.type.TypeFactory._fromClass(TypeFactory.java:707) at com.fasterxml.jackson.databind.type.TypeFactory._constructType(TypeFactory.java:387) at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:358) at com.fasterxml.jackson.databind.cfg.MapperConfig.constructType(MapperConfig.java:268) at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:473) at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:630) at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:106) at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2881) at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2338) at com.twitter.ibis.scalding.job.audit.AuditJob$$anonfun$jobWithGroupBy$1.apply(AuditJob.scala:158) at com.twitter.ibis.scalding.job.audit.AuditJob$$anonfun$jobWithGroupBy$1.apply(AuditJob.scala:152) at com.twitter.scalding.typed.TypedPipe$$anonfun$groupBy$1.apply(TypedPipe.scala:362) at com.twitter.scalding.typed.TypedPipe$$anonfun$groupBy$1.apply(TypedPipe.scala:362) at scala.collection.Iterator$$anon$11.next(Iterator.scala:328) at scala.collection.Iterator$$anon$11.next(Iterator.scala:328) at scala.collection.Iterator$class.foreach(Iterator.scala:727) at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:47) at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99) ... 16 more Container killed by the ApplicationMaster. Container killed on request. Exit code is 143 Container exited with a non-zero exit code 143

**Comment by cowtowncoder** [comment]
This looks mysterious, as underlying `_map` should never be null. At first I suspected that perhaps serializability was the problem, but with tests that should not be the case.

Update to the next patch version (2.4.5) may be a good idea, although code has not changed in this code path. 2.5.2 is another option, but I don't see significant differences there either.

Does this occur often, or just rarely?

**Comment by selvin** [comment]
That's what I thought. I couldn't find a way that _map was null.

This happens not immediately but eventually everytime with the data I have - even as the data changes on a 7-day sliding window. That said the amount of data I am processing on hadoop is only about a terrabyte (unzipped)

For further reference, the operation I am performing is

    objectMapper.writeValueAsString(someScalaImmutableMap)

**Comment by selvin** [comment]
I didn't see any differences between this version upto the latest releases, but I'll give it a shot

**Comment by cowtowncoder** [comment]
Ok. This is perplexing. Sounds as if some initialization was being performed concurrently. But I can not see any obviously wrong or unsafe codepath.

Are you using scala-specific `ObjectMapper`? I know that Scala module has its own `TypeFactory`, or at least an add-on to support handling of Scala Collections, Maps, so I wonder if this could be related.

**Comment by selvin** [comment]
val objectMapper = {
      val mapper = new ObjectMapper()
      mapper.registerModule(DefaultScalaModule)
      mapper
    }

    // and then
    objectMapper.writeValueAsString(someScalaImmutableMap)

**Comment by cowtowncoder** [comment]
@christophercurrie May or may not be related, but just an FYI.

**Comment by cowtowncoder** [comment]
No reproduction so unfortunately can not do much. If this is still observed with a more recent version (2.7 or later), may be reopened.

**Comment by liaoyt** [comment]
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.databind.util.LRUMap.get(LRUMap.java:73)
	at com.fasterxml.jackson.databind.type.TypeFactory._fromClass(TypeFactory.java:1442)
	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1375)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:734)
	at com.fasterxml.jackson.databind.cfg.MapperConfig.constructType(MapperConfig.java:312)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:517)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:798)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1514)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1215)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1085)

we meet this problem with verison 2.12.3

**Comment by JooHyukKim** [comment]
@liaoyt 

2.12 version is way too outdated to take action. Please try with 2.20 at least.

Also, reproduction needed.
