### ISSUE TITLE
Cannot instantiate JSON Object using Object Mapper.

### ISSUE THREAD

**Issue by uclesn** [FasterXML/jackson-databind#770]
Hello, I've been trying to map a JSON object to a POJO class using the object mapper but I keep getting a mapping exception. Ive tried serveral different objects and used different ways to create them but no luck. I even tried to use the sample code from the 3 minute tutorial and still no go. I am using Java 8 with Tomcat 7.0.39 and using jackson databind. 2.4.4 and jackson core 2.4.4. Below is my stack trace and code.

![image](https://cloud.githubusercontent.com/assets/9577246/7307138/905e19ea-e9d8-11e4-9ca7-cc70545e2bcb.png)

Here is my code.

```jsp
<%@page language  = "java" pageEncoding="UTF-8" contentType="text/html;charset=UTF-8"%>
<%@page import="com.fasterxml.jackson.databind.ObjectMapper"%>
<%@page import="com.fasterxml.jackson.core.JsonGenerationException"%>
<%@page import="com.fasterxml.jackson.databind.JsonMappingException"%>
<%@page import="com.fasterxml.jackson.annotation.*"%>
<%@page import="java.io.File"%>
<%@page import="java.util.List"%>
<%@page import="java.util.Map"%>

<%
    ObjectMapper mapper = new ObjectMapper();
    try {
		// read from file, convert it to user class
		 MyValue name = mapper.readValue("{\"name\":\"Bob\", \"age\":\"13\"}", MyValue.class);
		// display to console
		java.lang.System.out.println(name);
        } catch (Exception e) {
            e.printStackTrace();
        }
%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>
<%!
public class MyValue 
{
    public String name;
    public String age;
}
%>
```

**Comment by uclesn** [comment]
BTW it works fine with a List or Map but not objects I create.

**Comment by cowtowncoder** [comment]
My first guess is that perhaps JSP manages to create a non-static inner class here?
Is it possible to add `static` in that definition, to check?

The problem with non-static inner classes is that they require passing of invisible `this` pointer as the first argument of a (single-argument) constructor. And in this case, pointer to pass would have to refer to servlet created for JSP page, so it is not really available.

**Comment by uclesn** [comment]
I made it static and it works now! Thank you very much.

**Comment by cowtowncoder** [comment]
Ok good. This does make sense thinking of how jsp gets converted into Servlet source code, but is quite opaque from user perspective.
