### ISSUE TITLE
@JsonView is not consistent with Lists?

### ISSUE THREAD

**Issue by Deamon87** [FasterXML/jackson-databind#773]
So in one of projects I use Spring MVC + Jackson. I annotate my controller method with JsonView annotation. The code looks something like this:

```java
interface BWithAlistView {
}

@Entity
public class A {
 ....
}

@Entity
public class B {
  ...
    @JsonView(BWithAlistView.class)
    @OneToMany    
    private List<A> alist;
    public List<A> getAlist() {
        return alist;
    }
    public void setAlist(List<A> alist) {
        this.alist = alist;
    }
}

@Controller
public class Controller {

    @JsonView(BWithAlistView.class)
    @ResponseBody
    public List<B> getAlist(){
       //returns arraylist of objects B
    }
}
```
With this configuration the "alist" field from class "B" never gets serialized. It was never even included into final json. 
But when I changed the code to this
```java
public class B {
  ...
    private List<A> alist;
    @JsonView(BWithAlistView.class)
    public List<A> getAlist() {
        return alist;
    }
    public void setAlist(List<A> alist) {
        this.alist = alist;
    }
}
```
suddenly it worked as intended.

I will make the minimal project with maven to demonstrate this behavior if required.

**Comment by cowtowncoder** [comment]
Just make sure it is stand-alone and does not use Spring MVC. Handling of `@JsonView` for resource methods is not controlled by databind. It is most likely passed via `ObjectWriter`.

**Comment by cowtowncoder** [comment]
Sounds like integration issue wrt Spring MVC, but this is either controlled by Spring.
Closing; may be re-opened it can be demonstrated using only Jackson components.
