### ISSUE TITLE
Exception serialization and deserialization

### ISSUE THREAD

**Issue by ittaiz** [FasterXML/jackson-databind#780]
Hi,
Thanks to the popularity JSON is enjoying the last few years some server components communicate between themselves using JSON on the wire (be it REST or some textual RPC).
These components often can benefit from having exceptions serialized and deserialized as polymorphic types.
This means that if server A sends a FooApiException server B would prefer knowing this type and not just handling it as a Throwable/Exception.
Additionally some services would like the cause to be handled the same way while others might prefer it to be excluded since it is not part of the API and hence the class doesn't reside on server B's classpath.
My questions are WDYT about this use-case and if I'd like to contribute this tiny jackson module to FasterXML would you be interested?
Thanks in advance

**Comment by cowtowncoder** [comment]
I think ability to support polymorphic deserialization of `Exception`s (and matching serialization as necessary too) would be valuable addition. Something along these lines has been asked before, there may even be an open issue related to this.

It could start as a module, and if things work out well, could perhaps even be added as a feature of basic databind module.

For example, it could be as simple as having `SerializationFeature` and `DeserializationFeature` to make things work as if `@JsonTypeInfo` was enabled for `Exception`.

Come to think of this, one thing I wonder is this: is this not something that "default typing" can address? I am just thinking out aloud, I have not tried using that approach myself.

**Comment by ittaiz** [comment]
Hi,
Thanks for your reply.
I needed to read up on default typing so took me a bit longer.
As far as I undrestand it default typing might work but I'm not sure it's
fine grained enough.
I'm guessing you're talking about adding another value to the enum for
exceptions right?
That can work but what does Jackson do if there is type information of a
class which isn't on the client classpath? Does it error or fallback to
Exception/Throwable?

‏בתאריך יום שני, 4 במאי 2015, Tatu Saloranta <notifications@github.com> כתב:

**Comment by cowtowncoder** [comment]
No problem. Note that default typing allows specifying of piece of code to determine exactly where it should be applied. So it may be exactly as fine-grained as necessary, although only rely on type, and not per-property annotations.
There are other problems with that as general solution, specifically that it is a global setting, and can not be easily combined with other similar defaulting. But it could work for specific user / use-case, on short term.

As to unmappable class: right now that would lead to a failure; except that `@JsonTypeInfo` does also have `defaultImpl`. So it may be (I'd have to check) that if class is not found, that type is used as a fallback. And this would actually work relatively well for `Exception` case.
