### ISSUE TITLE
How can we handle forward references (UnresolvedForwardReference)

### ISSUE THREAD

**Issue by itonics-tbeauvais** [FasterXML/jackson-databind#784]
I love Jackson!  Such a great library!  Keep up the great work.

I am wondering if there is a way to easily had forward references.  I understand the possible performance issues, but it seems a bit stick for my taste.  Is there a way to make this work?

````
[
   {
     "id":"foo",
     "parent": "bar"
   }, 
   {
     "id":"bar"
   }
]
`````

This seems like you would want to stick in a place order or a "proxy" and fill it in once you reach instance "bar" instance...

**Comment by cowtowncoder** [comment]
Thanks!

Forward references actually should already work with `@JsonIdentityInfo`; support was added in 2.4 (I think), earlier versions did not support these.

**Comment by itonics-tbeauvais** [comment]
Thanks for the response!

Do you have some documentation that shows this use case?  Every search I have is bring up that "it doesn't work" rather than a guide..

**Comment by itonics-tbeauvais** [comment]
Also, I am looking to create a string of file imports with a cache.. to resolve these forward references.. what is the best way to implement this referencing over documents.. 

I've tried to use IntecableValues.. but I don't think this is the right path..

**Comment by cowtowncoder** [comment]
To support object identity/reference resolution, you need to add `@JsonIdentityInfo` annotation either on type(s) for which Object Ids are to be used, or for properties with values for which they should be used (if type itself does not have annotation).
Usage is quite similar to `@JsonTypeInfo` which is needed for polymorphic types (or properties).

Here are links to some hits I found wrt usage:

* http://stackoverflow.com/questions/24890447/how-to-use-jacksons-jsonidentityinfo-for-deserialization-of-directed-graphs has bit of info
* http://www.insaneprogramming.be/blog/2013/07/13/circular-dependencies-with-jackson/
* http://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion

There is nothing special wrt forward-references; Jackson does indeed need to keep track of unresolved references, and try to tie them back afterwards, reporting error if no id was found at the end of deserialization process.

**Comment by itonics-tbeauvais** [comment]
Great!  Thanks.

So, how can I custom implement the look up of these references?  The ID is a URI and I have an external cache that will make the external references upon deserialization.  Is this possible?

**Comment by cowtowncoder** [comment]
That may be tricky, but not impossible theoretically. :-)

External resolution was not a use case to explicitly support, but I wouldn't be surprised if it was possible to make it work. I have not implemented such resolution myself.
Handling during deserialization goes via 

http://fasterxml.github.io/jackson-annotations/javadoc/2.5/com/fasterxml/jackson/annotation/ObjectIdResolver.html

which is specified with @JsonIdentityInfo.resolver

Looking at ObjectIdResolver definition, one problem is that no context is being passed, so passing in something to resolve from may be challenging; for that, either static singleton reference, or `ThreadLocal` may be needed.
