### ISSUE TITLE
Fails to serialize/deserialize objects with custom deserializer when using default typing

### ISSUE THREAD

**Issue by jedvardsson** [FasterXML/jackson-databind#786]
Jackson fails to serialize/deserialize objects when using default typing even though a custom serializer/deserializer is provided. I stumbled upon this when using JSR310Module together with default typing. I'm unsure if this is a databind problem or a problem with the JSR310Module.

Code to reproduce:

```java
        ObjectMapper mapper = new ObjectMapper();
        mapper.registerModule(new JSR310Module());
        mapper.enableDefaultTyping();

        ZoneId id = ZoneId.of("America/Chicago");

        String value = this.mapper.writeValueAsString(id);
        ZoneId id2 = this.mapper.readValue(value, ZoneId.class);

        assertEquals("The value is not correct.", id, id2);
```
Gives the following error:
```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (VALUE_STRING), expected START_ARRAY: need JSON Array to contain As.WRAPPER_ARRAY type information for class java.time.ZoneId
 at [Source: "America/Chicago"; line: 1, column: 1]
```

**Comment by cowtowncoder** [comment]
Ok. This is probably due to handling by JSR310Module (deserializer needs to interact with type handling), so I'll re-create the issue over there.

**Comment by cowtowncoder** [comment]
Re-created as https://github.com/FasterXML/jackson-datatype-jsr310/issues/24, closing this issue (I haven't found a way to simply move issues between repos -- if anyone knows where that is, please let me know :) ).
