### ISSUE TITLE
Root wrapping in a module

### ISSUE THREAD

**Issue by miguelcobain** [FasterXML/jackson-databind#788]
Given an arbitrary Object hierarchy i want to output JSON that is wrapped in a root value.
I'm developing a module, so I'm not allowed to change the domain classes or annotations.

Example: 

```java
public class Author {	
	private Long id;
	private String name;
}
```

would output something like:
```json
{
  "author": {
    "id": 1,
    "name": "miguel"
  }
}
```

My module shouldn't work only for `Author` class, but rather for any class. If `Author` has a reference to another author, the referenced one shouldn't be wrapped. Only the root value.

Does Jackson provide an API for this task?

**Comment by cowtowncoder** [comment]
In general I would prefer you asking usage questions on Jackson user list at https://groups.google.com/forum/#!forum/jackson-user.

But as to functionality, `ObjectWriter` does have method `withRootName(String)` which allows specifying wrapping for the root value. Another alternative would be to override method `findRootName(...)` of `AnnotationIntrospector`; you can insert an `AnnotationIntrospector` from module if you want to.

**Comment by miguelcobain** [comment]
Sorry for posting on the wrong place.

`AnnotationIntrospector` would only be a valid option if I were to use an annotation on `Author` class, right?

**Comment by cowtowncoder** [comment]
@miguelcobain Nope. Despite the name, one can create `AnnotationIntrospector` that does not use annotations for anything -- it's just the abstraction layer between core databinding, and configuration aspects that usually are indicated via annotations. Implementation can use any information it wants to, including but not limited to annotations.

**Comment by miguelcobain** [comment]
Sorry for insisting, @cowtowncoder, but looks like `findRootName` never gets called.

ObjectMapper setup:
```java
mapper = new ObjectMapper();
//Not registering the module right now just to make sure that's not interfering
mapper.setAnnotationIntrospector(new CustomAnnotationInstrospector());
```

`CustomAnnotationInstrospector` definition:
```java
public class CustomAnnotationInstrospector extends AnnotationIntrospector {
	
	@Override
	public PropertyName findRootName(AnnotatedClass ac) {
		System.out.println(ac.getRawType().getSimpleName());
		return super.findRootName(ac);
	}

}
```

Serialization code:
```java
Author a = new Author();
a.setId(1L);
a.setName("miguel");
        
String result = mapper.writeValueAsString(a);
```

`findRootName` never gets called.

**Comment by miguelcobain** [comment]
After inspecting the source, I had to turn on root wrapping functionality:

```java
@Override
public void setupModule(SetupContext context) {
	super.setupModule(context);
	
	ObjectMapper mapper = (ObjectMapper) context.getOwner();
	mapper.configure(SerializationFeature.WRAP_ROOT_VALUE, true);
	
	context.insertAnnotationIntrospector(new EmberAnnotationInstrospector());
}
```

Looks like accessing `ObjectMapper` from a module isn't recommended, but it looks like there isn't another way.

**Comment by cowtowncoder** [comment]
Ah. Yes, true, I forgot this part.

As to modules: I think it is fine for cases where developer uses modules, but not recommended when writing shareable modules. Problem is mostly that changes to shared settings are difficult to reconcile, so ordering of calls plays a part.

You can enable/disable root-wrapping on per call basis using `ObjectWriter`:

```java
ObjectWriter w = mapper.writer(SerializationFeature.WRAP_ROOT_VALUE)
    .withRootName("wrapper");
w.writeValue(toWrap);
```

I think there is also a related issue filed:

https://github.com/FasterXML/jackson-annotations/issues/33

which might help here. If support was added, `AnnotionIntrospector` would be asked to see if forced wrapping was to be used.
