### ISSUE TITLE
Help on JsonIdentityInfo for two objects

### ISSUE THREAD

**Issue by vempus** [FasterXML/jackson-databind#791]
I understand that JsonIdentityInfo was used for resolving cyclic/recursive serialization. 

I have and object Order

public class Order{
private String orderId
private User createdBy;
private User lastModifiedBy;
}

@JsonIdentityInfo(
        generator = ObjectIdGenerators.PropertyGenerator.class,
        property = "userId")
public class User{
String userId;
String email;
}

The problem I have is that at first for the Order createdBy and lastModifiedBy refers to the same user object say userId = "123" so the serialization will only add createdBy and for lastModifiedBy only the ide is present. 

Is there a mechanism by which I can use propety name on the parent class also in the id generation something like giving a  context.

**Comment by cowtowncoder** [comment]
Please use mailing list for usage questions. This tracker is for reporting bugs and requesting new features.
