### ISSUE TITLE
Support for annotating enum values

### ISSUE THREAD

**Issue by m1h4** [FasterXML/jackson-databind#798]
Is there any reason why something like this would not be supported:

    public enum DeviceType {
        @JsonPropertyValue("DeviceTypeMobile")
        DEVICE_TYPE_MOBILE,
        @JsonPropertyValue("DeviceTypeDesktop")
        DEVICE_TYPE_DESKTOP
    }

and now when serialising/deserialising the values in the annotations would be used, but in Java you would use the more Java-like enum names.

Is there a technical issue preventing this from being supported or has no one simply addressed this yet?

I am aware of the more complicated, manual, way of achieving this behaviour using @JsonValue and @JsonCreator with custom from/to methods, but it seems this is enough of a common problem (at least for people that want neatly-named enum values) that the above, elegant, solution would be nice to have.

Would be interested in implementing this if need be

**Comment by m1h4** [comment]
I'm ashamed I did not look at past issues before posting, I now see that this exact feature was already discussed in January.

**Comment by cowtowncoder** [comment]
Right, #677 is the original issue I think, so additional comments may be added there. And we should be able to just use `@JsonProperty` to reduce explosion in number of annotations declared.
