### ISSUE TITLE
@JsonView doesn't seem to work with Generic Types

### ISSUE THREAD

**Issue by dennisa** [FasterXML/jackson-databind#804]
I have a class defined as

```java
@JsonTypeInfo(
use = JsonTypeInfo.Id.NAME,
include = JsonTypeInfo.As.PROPERTY,
property = "type")
@JsonSubTypes({
@JsonSubTypes.Type(value = MyEvent.class, name = "myevent"),
})
public abstract class Event<D>
{
private D data;
...
}
```

My event is defined as

```java
public class MyEvent extends Event<User>
{

}
```

And User is defined as

```java
public class User
{
@JsonView({ Views.Meta.class })
private final String username;

private final String first;

private final String last;
}
```

However, in my JaxRS web service the username is still getting serialized out when inside the MyEvent class, but on its won (standalone User) it excludes the serialization of the username.

I also tried this using OBJECT_MAPPER.writerWithView(Views.Meta.class).writeValueAsString(myEventInstance)

And again, it seems to ignore the @JsonView annotation

**Comment by cowtowncoder** [comment]
Ok, first things first. If you can reproduce this outside of JAX-RS, that would be great.
Alternatively, could you include JAX-RS resource end point declaration? Without that it might not be possible to reproduce the issue.

**Comment by cowtowncoder** [comment]
Need a reproducible test case, may be reopened with means to reproduce.
