### ISSUE TITLE
Force support of inconsistent boolean property

### ISSUE THREAD

**Issue by snicoll** [FasterXML/jackson-databind#805]
I want `ObjectMapper` to be able to convert the following object to a `Map<String,Object>` (basically listing the properties):

```java
public class FooImpl implements Foo {
  private Boolean enabled;

  @Override
  public boolean isEnabled() { ... }

  public void setEnabled(Boolean enabled) { this.enabled = enabled; } 
}
```

The `enabled` property is inconsistent as its getter returns a primitive `boolean` while the setter uses a `java.lang.Boolean` wrapper. 

Is there a way to configure the `ObjectMapper` to detect such special cases? Thanks!

**Comment by cowtowncoder** [comment]
Please use mailing lists for questions. Issue tracker is for reporting issues and requesting new features.
