### ISSUE TITLE
JaxbAnnotationIntrospector breaks @JsonTypeInfo

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#808]
Version 2.5.3

If `JaxbAnnotationIntrospector` is registered, @JsonTypeInfo is ignored and the associated property is missing from the serialization. If `JaxbAnnotationIntrospector` is disabled, the property comes back.

Testcase:
```
@JsonTypeInfo(use = JsonTypeInfo.Id.MINIMAL_CLASS, include = JsonTypeInfo.As.PROPERTY, property = "type")
public abstract class GenerationObject {
    private int id;
}

public class Hotel extends GenerationObject {
   private final String name;
   public Hotel(int id, String name) {
        super(id);
        this.name = name;
    }

    public static void main(String[] args) {
        ObjectMapper om = new ObjectMapper();

        om.setAnnotationIntrospector(new JaxbAnnotationIntrospector(TypeFactory.defaultInstance()));
        ObjectWriter writer = om.writer().withDefaultPrettyPrinter();

        Hotel hotel = new Hotel(5, "test");
        String text;
        try {
            text = writer.writeValueAsString(hotel);
            assert (text.contains("type")) : text;
        } catch (JsonProcessingException ex) {
            ex.printStackTrace();
        }
    }
}
```

Our application needs JAXB support, but we also need @JsonTypeInfo. What can we do?

Can you think of a quick workaround?

**Comment by cowtowncoder** [comment]
That code is replacing `JacksonAnnotationIntrospector` with `JaxbAnnotationIntrospector`, so it won't find any Jackson annotations. Two introspectors are unrelated, i.e. neither extends the other.

The usual way to allow use of both annotation is to use `AnnotationIntrospectorPair`, like so:

    AnnotationIntrospector intr = AnnotationIntrospector.pair(primary, secondary);

and depending on which should have precedence (if similar annotations overlap) use JAXB first, or Jackson one first.

Alternatively `Module`s can register additional introspectors with `insert` and `append` calls via `ModuleSetupContext`.

**Comment by cowwoc** [comment]
@cowtowncoder Thanks for the quick response. I suggest clarifying the documentation for `ObjectMapper.setAnnotationIntrospector()` to:

1. Mention the fact that the setter will replace/disable the default introspector.
2. Mention what the default value is.
3. Suggest the use of `AnnotationIntrospector.pair()` if the user wishes to leave the original introspector enabled.

**Comment by cowtowncoder** [comment]
Sounds reasonable.

**Comment by cowwoc** [comment]
@cowtowncoder Was the documentation ever updated (I couldn't find a related commit)?

**Comment by cowtowncoder** [comment]
I did add a note, just not as a separate commit.

**Comment by cowtowncoder** [comment]
... but additional improvements via PR always welcome.
