### ISSUE TITLE
FeatureRequest: Don't assign null

### ISSUE THREAD

**Issue by natnan** [FasterXML/jackson-databind#830]
I'm following a nulless practice (null is evil?), namely the controversial Optional pattern on my REST application. So, in my application I'm counting that the input won't be ever null (except some edge cases where null was inevitable). So, those fields which aren't mandatory are defined like this:

`private Optional<MyObject> myObject = Optional.empty();`

And in some cases I have simply a default value:

`private int port = 443`

So, this works just fine when the json fields are undefined. But if the client sends a `null` value, everything crashes because I don't do null checks everywhere. I have `Optional.isPresent()` for that, and that should suffice. It doesn't break my application's lifecycle (it's not *that* flaky :)) but the request throws NullPointerException which leads to either HTTP 400 or 500 depending on where and that confuses the REST consumers.

Also mentioned here:
http://stackoverflow.com/questions/29176325/give-a-default-value-for-an-attribute-if-the-value-is-null-in-json-by-jackson

So, I was thinking that it would be nice to have a `DeserializationFeature.DONT_ASSIGN_NULLS` or `DeserializationInclusion.NonNull` or something. 

However, having checked the code, I think there might not be a way for that directly. It seems like there is only the `NullProvider` which handles `null`s genericly and it cannot simply **skip** assignment/calling the setter. I can think of two simple solutions:

- Just like `DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES`, there might be `DeserializationFeature.FAIL_ON_NULL` which will give clear message to the REST consumer that explicit `null`s are not OK. Though not optimal, it'd save the day.
- This might be a bit naive to assume that'd work but still: Defining a new exception which would only skip the particular field assignment and continue to the next field, and make the `NullProvider` to throw this exception if the `DeserializationFeature.DONT_ASSIGN_NULLS` is enabled.

If you could guide me to the right direction, I could send a PR.

**Comment by cowtowncoder** [comment]
I am generally supportive of adding new features to support actual usage, so at abstract level this sounds reasonable.
But I am concerned by scope -- you are right in that this is not trivial to support. And specifically to support so that it has zero measurable performance impact for usage that does not care about blocking nulls (I have no issue adding overhead for new features themselves, although do want to minimize that as well). Plus ideally new features should not add tons of complexity in existing code (some is unavoidable, no feature is free).

Now: going back to what you would like to see: what is the optimal handling of a JSON `null` that would be sent? I guess some of choices are:

1. It is not legal to send `null`s, throw exception (could perhaps be even demoted to `jackson-core` level as a `JsonParser.Feature`; possibly simplest and most robust approach)
2. It is legal to send them, but these are to be taken as identical to "not present" case. So skip if seen.
3. Combination of above, allow either behavior (possibly dynamically, on per-call basis?)

and my first impression was that (2) would be what you would like to see. Is this correct?

**Comment by natnan** [comment]
Yes, preferably I'd like (2) but I can live with (1) as well. If the approach for (1) is better for performance and complexity, it makes more sense to go that way of course.

**Comment by cowtowncoder** [comment]
Ok. Technically (2) could perhaps be implemented via wrapper `SettableBeanProperty` that prevents call to actual field/method. It would have to be a `MapperFeature`, and settable just once (that is, can not change back and forth).

But I have one question: given that support for `Optional`s is included in `jackson-datatype-jdk8`, and it converts JSON `null`s into `Optional.absent()` on deserialization, wouldn't this work for your use case?
Any `JsonDeserializer` can actually implement `getNullValue(...)` method, to specify a null replacement value to use, including custom deserializers.

**Comment by natnan** [comment]
Looks like I was confused with the `Optional`s. I'm using `dropwizard`'s java8 bundle which has the `Optional` support. I was having some problems with nulls before because of a bug in afterburner but that's fine now. I was testing some other scenarios with default values and for some reason, I assumed it's the same for `Optional`s. Apparently it's not.

I guess we can ignore the `Optional` use-case then. I think the feature-request is still a valid one though, but maybe not that important since the `Optional` pattern is supported by other means. Still, one should be able to set some default values and expect that it cannot be overridden to null which will break things.

> Any JsonDeserializer can actually implement getNullValue(...) method, to specify a null replacement value to use, including custom deserializers.
For `Optional`s, this approach might work, but it doesn't solve `private int port = 443;`.

**Comment by cowtowncoder** [comment]
I don't know, should one be able to prevent that? I mean if content has `null`, why should it be ignored?
If so, perhaps a setter makes most sense, as it could add such logic. One of main problems in development is to try to limit feature set to commonly needed ones that work well together.

As to `private int port = 443', it should work in same vain; you can override deserializer used for `Integer.TYPE`, and make it use some other value. Although given that it is primitive, this actually already happens and `0` is set.
But perhaps you mean that there is no way to prevent assignment override. Even then, with `Optional`s value, whatever property has, will still be overridden.

I think at this point I will leave this open. Perhaps there is a feature that would be useful.

**Comment by natnan** [comment]
> If so, perhaps a setter makes most sense,

That's true. It's not a very common use-case and can be handled easily by having `if(arg != null)` in the setter or have `@NotNull` for the validation framework when needed.

I wouldn't mind if you want to close this and keep the issues clean :)

**Comment by cowtowncoder** [comment]
@natnan Thanks -- I will keep it open for now, although yes I am tempted to close things to keep issues list short. But perhaps a better way would be to start using tagging, and this could be put in a category of "potential" or "idea" or something. I also don't want to lose discussions for things that have some merit.

Anyway thank you for discussing this through.

**Comment by cowtowncoder** [comment]
This is same/similar to #1269, so closing.
