### ISSUE TITLE
TypeNameIdResolver will not resolve TypeName when no object is passed in

### ISSUE THREAD

**Issue by zoliszel** [FasterXML/jackson-databind#831]
Hi guys,

I am currently working on extending the jackson JAVA to JSON schema generator module to support draft v4 schemas and as part of that work I am looking to enhance the schema generator to take type information into consideration when generating the schema. . (i.e. if jackson will encode type information into the resulting JSON instance the original schema will no longer be valid, the generator will need to create additional structures to ensure the resulting JSON will be valid against the schema).

Ideally I want to reuse the same TypeResolver as what jackson is using to figure out where the type information is encoded but currently the TypeNameIdResolver expects a Java object to be passed along:
```java
  @Override
    public String idFromValueAndType(Object value, Class<?> type) {
        /* 18-Jan-2013, tatu: We may be called with null value occasionally
         *   it seems; nothing much we can figure out that way.
         */
        if (value == null) {
            return null;
        }
        return idFromValue(value);
    }
```
The schema generator will walk the class hierarchy and as such there will be no actual object. When looking deeper to this problem I can see the value is not even used, only the class of it:

```java
@Override
    public String idFromValue(Object value)
    {
        Class<?> cls = _typeFactory.constructType(value.getClass()).getRawClass();
        final String key = cls.getName();
```

meaning with a minor refactor this use case can be accomodated. Do you guys see any issues with such an enhancement?

Cheers,
Zoltan

**Comment by cowtowncoder** [comment]
@zoliszel I don't have an issue with possible enhancements to functionality, although there are couple of obvious concerns:

1. Backwards compatibility: can not change signatures of existing methods, may be able to add new ones (as long as we were using abstract classes), but it is often significant amount of work
2. Overloading to allow passing `Class` might work here, since `Class` itself is never uses as a base type for polymorphic handling.

Another question I have is as to how you are actually handling generation. The expected route is via visitors; is this what you are using? And is information there sufficient? I think the current visitor system is a big mess, unfortunately, but we are quite stuck with it as it is the only thing supported throughout code.

**Comment by zoliszel** [comment]
@cowtowncoder Those are valid concerns indeed. In my local workspace I just introduced a new protected method which resolves the id from the class itself and delegate from the exisiting ones:
```java
 @Override
    public String idFromValue(Object value)
    {
       return idFromClass(value.getClass());
    }

    @Override
    public String idFromValueAndType(Object value, Class<?> type) {
        /* 18-Jan-2013, tatu: We may be called with null value occasionally
         *   it seems; nothing much we can figure out that way.
         */
        if (value == null) {
            return idFromClass(type);
        }
        return idFromClass(value.getClass());
    }

    protected String idFromClass(Class<?> clazz){
        Class<?> cls = _typeFactory.constructType(clazz).getRawClass();
        final String key = cls.getName();
        String name;
        synchronized (_typeToId) {
            name = _typeToId.get(key);
            if (name == null) {
                // 24-Feb-2011, tatu: As per [JACKSON-498], may need to dynamically look up name
                // can either throw an exception, or use default name...
                if (_config.isAnnotationProcessingEnabled()) {
                    BeanDescription beanDesc = _config.introspectClassAnnotations(cls);
                    name = _config.getAnnotationIntrospector().findTypeName(beanDesc.getClassInfo());
                }
                if (name == null) {
                    // And if still not found, let's choose default?
                    name = _defaultTypeId(cls);
                }
                _typeToId.put(key, name);
            }
        }
        return name;
    }
```

The only change in behaviour would be is to send back a type id when no value is provided. It sounds reasonable to me but If it is a big risk we can just add in the idFromClass method and make idFromValue return null if no value is provided. 

On your second question I am using the visitors indeed. I have forked the https://github.com/FasterXML/jackson-module-jsonSchema repo to update it to support draft  v4. I basically copied everything from com.fasterxml.jackson.module.jsonSchema into com.fasterxml.jackson.module.jsonSchemaV4 and enhanced the functionality there. 

The goal is we want to auto generate schema from our Java classes and validate incoming Json messages against it. The current v3 generator is not powerfull enough, it doesn't support polymorphism in schema generation FasterXML/jackson-module-jsonSchema#5 hence the generated schema is quite weak so to speak.

**Comment by cowtowncoder** [comment]
Ah. Ok, yes, I think such a change should be safe, and if all unit tests still pass I would have no problem doing such change or merging a patch.
I would be interested in a simple unit test to verify the fixed behavior if you have something? (i.e. to make NPE disappear for usage you have, in simplified if need be).

Getting schema v4 level generator would be awesome; not sure what'd be the best way would be with respect to module. May need to split into sub-projects, to allow for both be supported at least on short term.

**Comment by zoliszel** [comment]
Pull request created, please let me know if you need anything furhter to this change.

Also on the V4 generator, where do you like it to be packaged? As I said before I am currently having it in a dedicated package but can move out to somewhere else if thats more prefered. Also would really appreciate if you could take a look at it first :-) Have a few goodies implemented...

**Comment by cowtowncoder** [comment]
Ok let me get this change integrated first if possible.

One formality first: we need the Contributor License Agreeement (CLA) from all contributors. It's at:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and we need a copy before the first contribution to any Jackson project, but not after that.
(apologies if I already asked for it and got it, we get a few every week and sometimes I miss additions).

Assuming you haven't sent one yet, it just needs to be printed, filled in, signed; and then usually scanned and sent as email to `info` at fasterxml dot com. Once I store it locally I can merge contribution(s).

**Comment by zoliszel** [comment]
Sure thing, will try to send it over tmrw.

Cheers,
Zoltan


On 23 June 2015 at 20:40, Tatu Saloranta <notifications@github.com> wrote:

> Ok let me get this change integrated first if possible.
>
> One formality first: we need the Contributor License Agreeement (CLA) from
> all contributors. It's at:
>
> https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf
>
> and we need a copy before the first contribution to any Jackson project,
> but not after that.
> (apologies if I already asked for it and got it, we get a few every week
> and sometimes I miss additions).
>
> Assuming you haven't sent one yet, it just needs to be printed, filled in,
> signed; and then usually scanned and sent as email to info at fasterxml
> dot com. Once I store it locally I can merge contribution(s).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FasterXML/jackson-databind/issues/831#issuecomment-114620131>
> .
>

-- 


------------------------------

*IMPORTANT NOTICE*: MahiFX Limited (*MahiFX*), (company no. 2446590) is 
registered in New Zealand. MahiFX is authorised and regulated by the 
Australian Securities and Investment Commission ARBN 152 535 085, AFSL 
414198. This email, its attachments and any rights attaching hereto are 
confidential and intended exclusively for the person to whom the email is 
addressed. If you are not the intended recipient, do not read, copy, 
disclose or use the contents in any way. Please notify the sender by return 
email and destroy the email and attachments immediately. MahiFX does not 
accept any liability for any changes made to this email or attachments 
after sending by MahiFX. You must scan this email and attachments for 
viruses. The opinions expressed are not necessarily those of MahiFX. MahiFX 
accepts no liability for any loss, damage or consequence, whether caused by 
our own negligence or not, resulting directly or indirectly from the use of 
this email and attachments.

For more information about MahiFX Limited see mahifx.com.

**Comment by zoliszel** [comment]
Hi,

the agreement came through today, please find it attached. Let me know if
you need anything further.

Cheers,
Zoltan

On 23 June 2015 at 21:09, Zoltan Szel <zoltan.szel@mahifx.com> wrote:

> Sure thing, will try to send it over tmrw.
>
> Cheers,
> Zoltan
>
>
> On 23 June 2015 at 20:40, Tatu Saloranta <notifications@github.com> wrote:
>
>> Ok let me get this change integrated first if possible.
>>
>> One formality first: we need the Contributor License Agreeement (CLA)
>> from all contributors. It's at:
>>
>> https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf
>>
>> and we need a copy before the first contribution to any Jackson project,
>> but not after that.
>> (apologies if I already asked for it and got it, we get a few every week
>> and sometimes I miss additions).
>>
>> Assuming you haven't sent one yet, it just needs to be printed, filled
>> in, signed; and then usually scanned and sent as email to info at
>> fasterxml dot com. Once I store it locally I can merge contribution(s).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FasterXML/jackson-databind/issues/831#issuecomment-114620131>
>> .
>>
>
>

-- 


------------------------------

*IMPORTANT NOTICE*: MahiFX Limited (*MahiFX*), (company no. 2446590) is 
registered in New Zealand. MahiFX is authorised and regulated by the 
Australian Securities and Investment Commission ARBN 152 535 085, AFSL 
414198. This email, its attachments and any rights attaching hereto are 
confidential and intended exclusively for the person to whom the email is 
addressed. If you are not the intended recipient, do not read, copy, 
disclose or use the contents in any way. Please notify the sender by return 
email and destroy the email and attachments immediately. MahiFX does not 
accept any liability for any changes made to this email or attachments 
after sending by MahiFX. You must scan this email and attachments for 
viruses. The opinions expressed are not necessarily those of MahiFX. MahiFX 
accepts no liability for any loss, damage or consequence, whether caused by 
our own negligence or not, resulting directly or indirectly from the use of 
this email and attachments.

For more information about MahiFX Limited see mahifx.com.

**Comment by cowtowncoder** [comment]
I don't think github handles attachments, unfortunately. :-(

Could you send email directly to `info` at fasterxml dot com instead?

**Comment by cowtowncoder** [comment]
Received the CLA, thanks!

**Comment by cowtowncoder** [comment]
I think this was resolved via another issue or PR.
