### ISSUE TITLE
Where is the mailing list?

### ISSUE THREAD

**Issue by soulmachine** [FasterXML/jackson-databind#832]
Sorry for the spam, but I find that the mailing list on the [project home page](http://wiki.fasterxml.com/JacksonHome) is obsoleted.

Could anybody be so kind to tell me the mailing list address?

**Comment by cowtowncoder** [comment]
I updated main Jackson portal at:

https://github.com/FasterXML/jackson

to include links to mailing lists. They are basic google groups, divided similar to old Codehaus lists.

**Comment by soulmachine** [comment]
Thank you!
