### ISSUE TITLE
Serializer doesn't omit synthetic members

### ISSUE THREAD

**Issue by niba** [FasterXML/jackson-databind#833]
Libraries that add synthetic members change the output of serializer. Right now, I have problem with using Jackson and Jacoco together. Jacoco adds two synthetic fields and I dont have any idea how to tell Jackson to dont include them during serialization.

Output from jackson without Jacoco

    {"test":{"type":"long"}}

Output with Jacoco:

    {"test":{"type":"long"},"$jacocoData":{"type":"object"}}},"$jacocoData":{"type":"object"}}

**Comment by cowtowncoder** [comment]
I would need a unit test to reproduce: Jackson introspectors do remove bridge methods, and should also remove synthetic members. But if there are cases this does not happen in, I need to be able to reproduce the specific problem, and to be able to verify the fix works.

**Comment by cowtowncoder** [comment]
I would like to resolve this, but without reproducible use case there is little I can do, unfortunately.
May be reopened with reproducible test case, code snippet, or some other way to reproduce the problem.
