### ISSUE TITLE
Preserve object references among multiple deserializations

### ISSUE THREAD

**Issue by bojanv55** [FasterXML/jackson-databind#834]
I can use this stuff @JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="@id") to serialize objects and during deserialization, Java preserves object references.

Can this thing be done during multiple deserializations, so somehow to reuse deserialization cache or something that is there? Usually, I have same objects there, but during multiple deserializations they are not referenced by created as new.

Thanks!

**Comment by cowtowncoder** [comment]
Not currently, with exception of new (2.5) `ObjectWriter.writeValues()` method (and `ObjectReader.readValues()`), which use a single context object.

In future I hope we can add easier customization of Object Id handling, to add custom resolvers. And those could conceivably allow use of same stateful resolver. But right now there is nothing out of the box to support such thing.

**Comment by bojanv55** [comment]
I don't know if this is OK, but found out how to do it... Just this 3 edits in 2 classes...

public class SimpleObjectIdResolver implements ObjectIdResolver {
    protected **static** Map<IdKey,Object> _items;

...

**/* else if (_items.containsKey(id)) {
            throw new IllegalStateException("Already had POJO for id (" + id.key.getClass().getName() + ") [" + id
                    + "]");
        }*/**

public class PropertyValueBuffer
{

public Object handleIdValue(final DeserializationContext ctxt, Object bean) throws IOException
    {
        if (_objectIdReader != null) {
            if (_idValue != null) {
                ReadableObjectId roid = ctxt.findObjectId(_idValue, _objectIdReader.generator, _objectIdReader.resolver);
							**if(roid.resolve()!=null) {
								bean = roid.resolve();
							}**

**Comment by bojanv55** [comment]
I kinda got this functionality by editing 3 lines in 2 classes:

static map and commented code for same key

    public class SimpleObjectIdResolver implements ObjectIdResolver {
    protected static Map<IdKey,Object> _items;

    public SimpleObjectIdResolver() { }

    @Override
    public void bindItem(IdKey id, Object ob)
    {
        if (_items == null) {
            _items = new HashMap<ObjectIdGenerator.IdKey,Object>();
        }/* else if (_items.containsKey(id)) {
            throw new IllegalStateException("Already had POJO for id (" + id.key.getClass().getName() + ") [" + id
                    + "]");
        }*/
        _items.put(id, ob);
    }


And this one (added if(roid.resolve()) condition)


    public class PropertyValueBuffer
    {
    ...
    public Object handleIdValue(final DeserializationContext ctxt, Object bean) throws IOException
    {
        if (_objectIdReader != null) {
            if (_idValue != null) {
                ReadableObjectId roid = ctxt.findObjectId(_idValue, _objectIdReader.generator, _objectIdReader.resolver);
							if(roid.resolve()!=null) {
								bean = roid.resolve();
							}
                            roid.bindItem(bean);

**Comment by bojanv55** [comment]
Infact, instead of making that first 2 modifications, I created new class for annatiation that can be used like this:

    @JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, resolver = CommonObjectIdResolver.class ,property="@id")

And class is (weak hash map used to remove unused objects after strong references are removed):


    import com.fasterxml.jackson.annotation.ObjectIdGenerator.IdKey;
    import com.fasterxml.jackson.annotation.ObjectIdResolver;

    import java.util.Map;
    import java.util.WeakHashMap;

    public class CommonObjectIdResolver implements ObjectIdResolver {

    private static class LazyHolder{
        private static final ObjectIdResolver INSTANCE = new CommonObjectIdResolver();
    }

    protected Map<IdKey,Object> _items = new WeakHashMap<IdKey, Object>();

    @Override
    public void bindItem(IdKey id, Object pojo) {
        _items.put(id, pojo);
    }

    @Override
    public Object resolveId(IdKey id) {
        return (_items == null) ? null : _items.get(id);
    }

    @Override
    public ObjectIdResolver newForDeserialization(Object context) {
        return LazyHolder.INSTANCE;
    }

    @Override
    public boolean canUseFor(ObjectIdResolver resolverType) {
        return resolverType.getClass() == getClass();
    }
}

**Comment by cowtowncoder** [comment]
This is good to share for others, but anything that is static will unfortunately not work as solution from core Jackson perspective. Biggest allowed scope is within an `ObjectMapper`, since otherwise things go haywire for bigger systems.

But that does not mean that such a solution could not be useful for anyone implementing functionality for their own specific needs, where this is not problematic.

**Comment by bojanv55** [comment]
Is it possible then to add this line in PropertyValueBuffer class, since this cannot be changes without project modification? I'm not sure if it will create problems for the rest of the code, but I hope you can run tests to check it out.

**Comment by cowtowncoder** [comment]
@bojanv55 Ok, which line?

**Comment by bojanv55** [comment]
In PropertyValueBuffer in method handleIdValue (my 2nd post):

Object res = roid.resolve(); if(res != null) { bean = res; }

Dont know if this could have sideeffescts. Tested it and it should be ok.
