### ISSUE TITLE
Speed inconsistencies (Android: Parcelable & Modules)

### ISSUE THREAD

**Issue by zoltish** [FasterXML/jackson-databind#837]
**Context**: I read in my model objects from a file where theyre stored as json, the whole file being an array with objects from the jackson point of view. 

**Problem**: If my model objects implement the Parcelable interface, they take 100-200% longer to parse in. Moreover, it seems that the exact same problem occurs if the model objects reside in a different module from the one where the Jackson code is run. 

Ive put up a post on StackOverflow about the issue, please refer to it for code and more details:
http://stackoverflow.com/questions/30967774/why-does-the-parcelable-creator-field-decrease-jackson-performance-dramatically

**Comment by cowtowncoder** [comment]
Jackson has no dependencies to Android-specific classes, and does not know or use Parcerables, for what that is worth. Neither is standard JDK serialization (java.io.Serializable) used (which could use Parcelable under the hood).
Maybe profiler could help figuring out who is calling these methods. I am guessing that maybe Android SDK's Reflection calls do additional work for such cases.

**Comment by cowtowncoder** [comment]
Unfortunately I can not say why this would occur. I don't see `Parcelable` or `Parcelable.Creator` having getters or setters to make that even work with default Jackson settings, but perhaps actual implementations have setters/getters, or define 1-string-argument constructor.
So I am not even sure how it would work, without more code.

But perhaps more importantly, it is difficult to know what would slow things down. If location of classes matters, it sounds like Android SDK has expensive access checks for calls to non-public methods.
I have learnt over time that Google's Android implementation is really uneven wrt quality; and areas that are not (thought to be) commonly used are full of various holes, sometimes things not working, other times having sub-par performance. Access via reflection, and especially access to annotation information is particularly inefficient; and Dalvik VM essentially has no support for weak or soft references.
That is to say, I fear that the performance problem itself would lie within SDK.

**Comment by cowtowncoder** [comment]
Not sure what to work on here, unfortunately.
