### ISSUE TITLE
Jackson-mvc polymorphism problem

### ISSUE THREAD

**Issue by tolgatanriverdi** [FasterXML/jackson-databind#843]
Hi
I'm new to jackson  and I'm using it with my spring mvc web server
I've a class structure like below and what I want to achive is when I receive a json request:

If the type parameter of CoreOrder class is equals to ScrollOrder it should be cast to ScrollOrder class, if the type parameter of CoreOrder class is equals to SliderOrder it should be cast to SliderOrder class.
How can I do that with JsonSubType annotations or something like that?

[code]
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.WRAPPER_OBJECT, property = "objectType")
@JsonSubTypes({
        @Type(value = ScrollOrder.class),
        @Type(value = SliderOrder.class)
})

public class CoreOrder 
{
	public String type; //Button, TextField, PasswordField, Combobox, Table vs
	public String name;
	public int executeOrder;
	public MTOSClickOrder clickToElement;
}

public class ScrollOrder extends CoreOrder
{
	public scrollDirection scrollToDirection;
	public String scrollToElementWithName;
}

public class SliderOrder extends CoreOrder 
{
	public double sliderValue;
}
[/code]

**Comment by cowtowncoder** [comment]
You get the answer by posting to mailing list:

https://groups.google.com/forum/#!forum/jackson-user

and not filing an issue at issue tracker. Issue tracker is for reporting problems and requesting features.
