### ISSUE TITLE
ISO8601 format with time zone not deserialized

### ISSUE THREAD

**Issue by chrylis** [FasterXML/jackson-databind#847]
This may be a configuration issue, but I believe this case ought to Just Work with 2.4.6.

I'm trying to deserialize the property

   "iso_date_created":"2011-06-07T22:09:30.0000-00:00"

into a `java.util.Date`, and I'm getting the error 

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.util.Date from String value '2011-06-07T22:09:30.0000-00:00': not a valid representation (error: Failed to parse Date value '2011-06-07T22:09:30.0000-00:00': Can not parse date "2011-06-07T22:09:30.0000-00:00": not compatible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSZ", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd"))
```

I see that the with-time-zone format is not listed, but as [the docs](http://wiki.fasterxml.com/JacksonFAQDateHandling) explicitly give that format as the example for ISO8601, it seems that it ought to be supported.

**Comment by cowtowncoder** [comment]
Is that valid as per ISO-8601? Specifically, 4th digit for second fractions (instead of 3)?
It seems to me like that would be the only deviation from formats explicitly listed.

**Comment by chrylis** [comment]
Aha. Good catch, reporting upstream. Interestingly, manually specifying `SSSSXXX` does work.

**Comment by cowtowncoder** [comment]
FWIW, decimal fraction is acceptable for all units of time (even hours), but only the lowest unit can have it (that is, fractional hours ok if no minutes or seconds specified).
On decimal fractions, says (https://en.wikipedia.org/wiki/ISO_8601):

"There is no limit on the number of decimal places for the decimal fraction. However, the number of decimal places needs to be agreed to by the communicating parties."

So specifying custom format to accept more digits is fine.

But in case of Java, pre-Java8, more than 3 digits is of limited use as milliseconds is the smallest unit.

Anyway, I think things work acceptably.

**Comment by chrylis** [comment]
This is coming out of an EXIF timestamp, which only has seconds anyway, so upstream just knocked off the fractional part entirely, and all is right with the world.
