### ISSUE TITLE
@JSONProperty(required=true) ignored during deserialization

### ISSUE THREAD

**Issue by svenwb** [FasterXML/jackson-databind#858]
I would expect that required=true means, that the JSON string has to contain a key for this property:

Example:

`public class Example {
    @JsonProperty(required=true)
    int count;
    String name;
}`

If I am trying to deserialize this JSON I would expect an exception as count is not defined.

`{"name":"abc"}`

Any comments?

Thanks,
Sven

**Comment by cowtowncoder** [comment]
See #230 for full explanation. TL;DNR;: Jackson 2.6 will actually support verification for creator parameters (arguments of constructor or factory method annotated with `@JsonCreator`), but for other properties this annotation is only provided as metadata for introspection, and used for things like JSON Schema generation.

**Comment by operatiay** [comment]
2.6.0-rc4 doesn't work for me.

I've added
```objectMapper.configure(DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES, true);```
without any effect.

**Comment by cowtowncoder** [comment]
@operatiay If so, a new issue with reproducible unit test would make sense.
