### ISSUE TITLE
FAIL_ON_UNRESOLVED_OBJECT_IDS has no effect when using ObjectReader

### ISSUE THREAD

**Issue by bennesher** [FasterXML/jackson-databind#864]
More specifically, the method DefaultDeserializationContext#checkUnresolvedObjectId() does not appear to be invoked when using an ObjectReader rather than the ObjectMapper.  I encountered this problem when using Restlet's JacksonRepresentation.

From my basic debugging of the problem, it looks like ObjectReader#_bindAndClose should invoke this method, in a manner analogous to ObjectMapper#_readMapAndClose.

**Comment by cowtowncoder** [comment]
That would be a problem. I can try to add a separate unit test that uses ObjectReader; I assume your suggestion on root cause is correct.
Thank you for reporting this!

**Comment by cowtowncoder** [comment]
Hmmh. Looking at `TestObjectIdDeserialization.testUnresolvableAsNull()`, code does actually use `ObjectReader`. So I think I need code to reproduce the issue.

**Comment by cowtowncoder** [comment]
Can not reproduce; may be reopened with a reproducible test case or instructions for reproducing.
