### ISSUE TITLE
Jackson Object Mapper Versioned issue from Java 7 to Java 8

### ISSUE THREAD

**Issue by nitin88** [FasterXML/jackson-databind#872]
I am trying to upgrade Java version from 1.7 to 1.8. Didn't change any code apart setting Maven Java version to 1.8. I am getting below error while compilation

"Error: cannot access Versioned."

Source:
private ObjectMapper mapper = new ObjectMapper();
return mapper.writeValueAsString(data);

Couldn't find any documentation anywhere in the internet. I thought 1.8 should be completely backward compatible.

Reference: http://stackoverflow.com/questions/31555751/jackson-object-mapper-versioned-issue-from-java-7-to-java-8

**Comment by cowtowncoder** [comment]
This is not a known problem, and Jackson should indeed work without problems with both Java 7 and Java 8.

`Versioned` is auto-generated as part of the build.

Are you running on an OSGi container by any chance?

**Comment by nitin88** [comment]
No. I am not using any OSGi container.
Let me know if you need any more info

**Comment by cowtowncoder** [comment]
As per StackOverflow question, answers, this certainly sounds like a version incompatiblity between compoenents in classpath.
Of Jackson 1.x versions the only one supported at this point is 1.9, for what that is worth. Problems reported against older versions will not be investigated further, but I hope you will be able to resolve versioning issue.
