### ISSUE TITLE
Extending com.fasterxml.jackson.databind.introspect.NopAnnotationIntrospector to restrict attributes for serialization

### ISSUE THREAD

**Issue by ariens** [FasterXML/jackson-databind#880]
I'm trying to reverse the logic associated to to  identifying which attributes are included in serialization and de-serialization with an Annotation Introspector.  Instead of the default mapper options available (withFieldVisibility, withGetterVisibility, withSetterVisibility, withCreatorVisibility) I'd like to only include attributes with a specific annotation by setting this [introspector](https://gist.github.com/ariens/55f8830ec8144f6c6b25) on my mapper however the resulting JSON string is empty whenever it's used.

I expect this is because in the nested object hierarchy a false is returned at a higher level and the entire object's ignored but I wasn't able to waste enough time on other options.

**Comment by cowtowncoder** [comment]
Instead of extending `NopAnnotationIntrospector` try extending `JacksonAnnotationIntrospector`.

Also: in future please ask these kinds of questions on the mailing list (https://groups.google.com/forum/#!forum/jackson-user) -- not all/many users and developers follow issues list updates.
