### ISSUE TITLE
ArrayIndexOutOfBoundException in 2.6.0

### ISSUE THREAD

**Issue by alterGauner** [FasterXML/jackson-databind#884]
Hi, it's my first time that i report an issue for jackson-databind and i didn't find any other reporting possibility for bugs.

Short story: After updating to jackson-databind 2.6.0 i receive an ArrayindexOutOfBoundException in one of my testcases. Downgrade is not an option, because 2.6.0 fixes another bug...

I documented this bug here: http://stackoverflow.com/questions/31761225/jackson-databind-arrayindexoutofboundexception-version-2-6-0 (better layout possibilities).

kr

**Comment by cowtowncoder** [comment]
This is indeed the right place to report the bug, thank you for reporting it!
We will figure out what is going on and fix it for 2.6.1 -- obviously this was not found by our own regression test suites, or during release candidates. So it's good to get it at least reported now.

**Comment by cowtowncoder** [comment]
Unfortunately example at SO is incomplete: I do need the full POJO definitions. While number of fields is helpful, actual field names may matter as well; and definitely annotations that indicate use of `@JsonIdentityInfo`.

**Comment by alterGauner** [comment]
Here is a eclipse project which reproduces the bug. Just download this "picture", it's a 7z archive ;-) If it doesn't work, please give me a mailaddress or another upload possibility.
![jacksonreproduceerrorproject](https://cloud.githubusercontent.com/assets/10708195/9069417/667aba18-3ae9-11e5-8318-a73be65a3f21.png)

**Comment by cowtowncoder** [comment]
Thanks! I was able to figure out the root cause and fix it, with the test case. Much appreciated.

**Comment by alterGauner** [comment]
Great job, thumbs up!
