### ISSUE TITLE
RFE: Support Multiple Mix-Ins 

### ISSUE THREAD

**Issue by ariens** [FasterXML/jackson-databind#887]
I have an abstract class that currently contains a slew of logic for serializing and de-serializing objects to/from ZooKeeper using Jackson.

This abstract class contains all the various methods for `get()`, `getAll()`, `save()`, in addition there's a concept of access levels.  Access levels are really just a basic `Map<String, Map<Class, Class>>` where the String represents the access level and Map<Class, Class> represents a mix-in that get's applied to a class. 

``` java
public String toJSON(String role) 
     throws JsonProcessingException, InvalidUserRoleException {
    if (!roleToMixInMapping.containsKey(role)) {
        throw new InvalidUserRoleException(String.format(
             "The role %s does not apply to %s", role, getClass()));
    }       
    ObjectMapper mixinMapper = getNewMapper();
    for (Class objClass : roleToMixInMapping.get(role).keySet()) {
        mixinMapper.addMixIn(objClass, roleToMixInMapping.get(role).get(objClass));         
    }
    return mixinMapper.writeValueAsString(this);        
}

public JsonNode toJsonNode(String role) 
     throws IOException, JsonProcessingException, InvalidUserRoleException {
    return mapper.readTree(toJSON(role));
}
```

There's a Dropwizard  application that currently our public facing API that `GET`s, `PUT`s, `POST`s these various objects based on their role.  

This works great with the exception that a given object class cannot have more than one mix-in associated to it.  Jackson doesn't complain if there's already a mix-in associated to an object class yet the existing mix-ins functionality is replaced.

I'm currently working around this by having my mix-ins extend each other, but that hierarchy mess is going to get complicated over time.

Perhaps you could make the mix-ins associated to a object class a collection and whatever method you use to make the object class inherit the abstract mix-in class you could use to have subsequent mix-ins for the same object class inherit the previously added mix-in?

It would be fantastic if this test could pass (see: "This test should pass").  

``` java
@Test 
public void testApplyRole() throws IOException, JsonProcessingException, InvalidUserRoleException {
    TestObject testObject = getTestObject();        
    testObject.setSensitive1("This text should not be serialized if protected by 1");
    testObject.setSensitive2("This text should not be serialized if protected by 2");

    testObject.registerMixIn("protectedBy1", TestObject.class, TestObjectProtected1.class);
    testObject.registerMixIn("protectedBy2", TestObject.class, TestObjectProtected2.class);

    // No role: Both sensitive fields should exist
    assertEquals(testObject.toJsonNode().has("sensitive1"), true);
    assertEquals(testObject.toJsonNode().has("sensitive1"), true);

    // protectedBy1 role: sensitive1 should not exist, sensitive 2 should exist
    assertEquals(testObject.toJsonNode("protectedBy1").has("sensitive1"), false);
    assertEquals(testObject.toJsonNode("protectedBy1").has("sensitive2"), true);

    // Role: protectedBy2, neither sensitive fields should exist
    assertEquals(testObject.toJsonNode("protectedBy2").has("sensitive1"), false); // This test should pass
    assertEquals(testObject.toJsonNode("protectedBy2").has("sensitive2"), false);

    assertEquals(testObject.toJsonNode().get("pojoList").get(0).has("protectedString"), true);

    testObject.registerMixIn("pojoProtected", Pojo.class, PojoProtected1.class);

    testObject.getPojoList()[0].setProtectedString("This text should not be serialized if protected by PojoProtected1");
    assertEquals(testObject.toJsonNode("pojoProtected").get("pojoList").get(0).has("protectedString"), false);
} 
```

**Comment by cowtowncoder** [comment]
No plans to implement, closing.
