### ISSUE TITLE
Is property _readOnlyMap of com.fasterxml.jackson.databind.ser.SerializerCache useless?

### ISSUE THREAD

**Issue by jicahoo** [FasterXML/jackson-databind#892]
In SerializerCache, there is one property with name '_readOnlyMap'. I believe it should be used as cache. However, I cannot see any call for getting data from this map. What I saw in the code is only 1. create the instance of ReadOnlyClassToSerializerMap; and 2. _readOnlyMap.set(null). Or I missed something?

Thank you!

**Comment by cowtowncoder** [comment]
There is this method

```java
    public ReadOnlyClassToSerializerMap getReadOnlyLookupMap()
    {
        ReadOnlyClassToSerializerMap m = _readOnlyMap.get();
        if (m != null) {
            return m;
        }
        return _makeReadOnlyLookupMap();
    }
```

which is used by `SerializerProvider`; that's how this cache object is used. Code I am looking at is `master`, at version 2.6.1.

**Comment by jicahoo** [comment]
Got it.Thank you @cowtowncoder
