### ISSUE TITLE
Is this a bug???

### ISSUE THREAD

**Issue by rocky-peng** [FasterXML/jackson-databind#893]
i have a pojo , like this:
```
public class Profile {

    private boolean is_default;

    public boolean is_default() {
        return is_default;
    }
    public void setIs_default(boolean is_default) {
        this.is_default = is_default;
    }

}
```
and i handle a instance of class Profile like this:
```
Profile p = new Profile();
String s = new ObjectMapper().writeValueAsString(p);
sout s;
```
the value of  variable s  is :  //pay attention 
```
{
  "_default" : false
}
```
the prefix "is" is missing.

Is this a bug?

and i have saw the source code and found this code in class com.fasterxml.jackson.databind.util.BeanUtil :
```
public static String okNameForIsGetter(AnnotatedMethod am, String name)
{
    if (name.startsWith("is")) {
        // plus, must return boolean...
        Class<?> rt = am.getRawType();
        if (rt != Boolean.class && rt != Boolean.TYPE) {
            return null;
        }
        return manglePropertyName(name.substring(2));   
    }
    // no, not a match by name
    return null;
}
```
and i have know the reason :  substring(2) ,   Is this right???

**Comment by cowtowncoder** [comment]
Please do not spam multiple forums.

No, this is not a bug, as per email on user list.

**Comment by rocky-peng** [comment]
Sorry ,there is no response when  i submitted  this in google group ,so i thought i have not submit it successfully.
