### ISSUE TITLE
When using withFactory on ObjectMapper, the created Factory has a TypeParser which still has the original Factory

### ISSUE THREAD

**Issue by lufe66** [FasterXML/jackson-databind#894]
The result of this situation is that the ClassLoader which is passed to the new Factory is not used by TypeParser (who has the original ClassLoader-less factory still), resulting on failure to find the classes on TypeParser even though the new Factory has the correct ClassLoader. I'm sending a pull request to change this.

**Comment by cowtowncoder** [comment]
Ok, I solved the problem using the idea, just slightly different form. I hope I did not miss anything; please let me know if I did overlook something.
