### ISSUE TITLE
ObjectMapper.convertValue(Object,Class<T>) to the same class is not functionally equivalent to serializing and then deserializing

### ISSUE THREAD

**Issue by jishi9** [FasterXML/jackson-databind#897]
The javadoc for `ObjectMapper.convertValue(Object fromValue, Class<T> toValueType)` states:

>This is functionality equivalent to first serializing given value into JSON, then binding JSON data into value of given type, but may be executed without fully serializing into JSON.

However this is not the case when `toValueType` is of the same type as `fromValue`, which should be usable for deep copying an object. The returned object must be distinct from `fromValue`, such that mutating either of `fromValue` or the returned object does not mutate the other.

This bug occurs due to this snippet from `ObjectMapper._convert`:

    protected Object _convert(Object fromValue, JavaType toValueType)
            throws IllegalArgumentException
        {        
            // also, as per [Issue-11], consider case for simple cast
            /* But with caveats: one is that while everything is Object.class, we don't
             * want to "optimize" that out; and the other is that we also do not want
             * to lose conversions of generic types.
             */
            Class<?> targetType = toValueType.getRawClass();
            if (targetType != Object.class
                    && !toValueType.hasGenericTypes()
                    && targetType.isAssignableFrom(fromValue.getClass())) {
                return fromValue;  // the object should be cloned, not be returned as-is
            }

**Comment by cowtowncoder** [comment]
Sounds like I should update the javadoc to reflect this, then, given that the behavior has been unchanged since 2.0.

Thank you for reporting the discrepancy.

**Comment by cowtowncoder** [comment]
Updated javadoc description to indicate that conversion only occurs if type of incoming value is not assignable to target type. Also added bit more description on differences, and removed claim that this is strictly identical write-then-read approach.
