### ISSUE TITLE
ObjectMapper.getSerializerProvider().findValueSerializer(…) throws NullPointerException

### ISSUE THREAD

**Issue by olivergierke** [FasterXML/jackson-databind#898]
I need to find the `JsonSerializer` for a given type and naïvely tried:

```java
ObjectMapper mapper = … // obtained
mapper.getSerializerProvider().findValueSerializer(…);
```

The last call throws a `NullPointerException` as `SerializerProvider` accesses `_knownSerializers` without a guard although it can be `null`.

Am I using the API in a wrong way? What's the proposed way of obtaining a serializer for a given type?

**Comment by cowtowncoder** [comment]
The short answer is that you are not supposed to access serializers or deserializers via `ObjectMapper`.
Rather, they should be dynamically accessed via `SerializerProvider` / `DeserializationContext` that are passed during processing.

Access is usually done from `Contextual[De]Serializer.createContextual()` (when resolving (de)serializers you need to delegate to), or directly from `serialize()` / `deserialize()` methods of `JsonSerializer` / `JsonDeserializer`.
There are other possible mechanism too but these two cover most usage by Jackson's default serializers.

There is still the question of whether `SerializerProvider` should be exposed at all by `ObjectMapper`.
I forget why it is exposed; this may be 1.x leftovers.

Also: if you really do want go the route of using it directly, you can look at initialization that `ObjectMapper` does; I think it's just a matter of calling a method to create usable instance, out of "blueprint" provider object.
It might also make sense to handle such initialization, if the method is called. This could lead to other problems (considering that the use of this method is discouraged), but it is a possibility.

**Comment by olivergierke** [comment]
I basically need to access the serializer outside the scope of a serialization. We're building custom infrastructure to expose a JSON Schema with Spring Data REST and would like to  use a potentially registered custom serializer to also expose custom schema tweaks. E.g. [This class](https://github.com/olivergierke/spring-restbucks/blob/master/src/main/java/org/springsource/restbucks/JacksonCustomizations.java#L117) serializes a `Money` instance in a custom format, and by implementing `JsonSchemaPropertyCustomizer ` we can expose a regex for that format. It's kind of neat to combine both these aspects (the serialization customization and the necessary schema tweaks) in a canonical place.

I found [this workaround](https://github.com/spring-projects/spring-data-rest/blob/master/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/json/JacksonMetadata.java#L158) working.

**Comment by cowtowncoder** [comment]
Ok. It it is not unreasonable thing to want to do, but just need to figure out how access should ideally work, considering that normally context is established first and so on. But it should be doable.

And the workaround looks good to me; casting is necessary as instance creation is purposefully hidden at this point.

Anwyay, I am open to improvement ideas here.

**Comment by cowtowncoder** [comment]
Ok: I'll go ahead and add `ObjectMapper.getSerializerProviderInstance()` that will get `SerializerProvider`, call `createInstance(config)` on it, and return result. This will give safe(r) access to necessary functionality without exposing internal details.

**Comment by olivergierke** [comment]
@cowtowncoder - Awesome, thanks for that! :)
