### ISSUE TITLE
ObjectMapper.readValue(InputStream src, JavaType valueType) raises an exception on empty source

### ISSUE THREAD

**Issue by konmik** [FasterXML/jackson-databind#907]
But it should return null.

```
 Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
        at [Source: retrofit.ExceptionCatchingTypedInput$ExceptionCatchingInputStream@b40385a8; line: 1, column: 1]
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3095)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3036)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2206)
```

**Comment by cowtowncoder** [comment]
First of all, I do agree in that it would be good to have a way to do read where lack of content would not lead to an exception.

But I am not sure returning `null` would make sense, given that it would lead to ambiguity between explicit `null` JSON value, which Jackson does support. It would also change observed behavior and possibly breaking existing functionality; many users are strict about handling of error conditions. This may not be common, but backwards compatibility has been the biggest on-going issue with 2.x development, so I would like to be careful with changing behavior.

I think a better way might be to add a new method(s) in `ObjectReader` to allow "read if content exists, `null` if not". It is also possible to use `ObjectReader.readValues()` to do this (I think), but that is bit verbose.

**Comment by konmik** [comment]
There is a connected issue: https://github.com/FasterXML/jackson-jaxrs-json-provider/issues/4

**Comment by cowtowncoder** [comment]
Having thought this over, I think that current behavior is correct: if there is no content to map, throwing exception should occur, as `null` is returned for JSON "null" literal.
To avoid exception, there are two main mechanisms:

1. Construct `JsonParser` separately, call `JsonParser.nextToken()` to see if a token is available; if not, process "no content", if there is, call `readValue()` passing `JsonParser` as source, OR
2. Use `ObjectReader.readValues()` and use `MappingIterator.hasNextValue()` for checking.

Now: although I am not changing existing behavior, I am open to future work, for example:

* Add a new `DeserializationFeature`, something like `MAP_NO_CONTENT_TO_NULL`, which would then return `null`

If that sounds like useful feature, please file a new issue for that work: I prefer that over changing title and description of this issue.
