### ISSUE TITLE
Rename PropertyNamingStrategy CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES to standard SNAKE_CASE?

### ISSUE THREAD

**Issue by marcottedan** [FasterXML/jackson-databind#909]
Hi,

There is a standard naming convention for "lower_case_with_underscore" it's called snake_case : https://en.wikipedia.org/wiki/Snake_case

Would it be possible to duplicate the existing PropertyNamingStrategy to add the PropertyNamingStrategy.CAMEL_CASE_TO_SNAKE_CASE or deprecated the existing one?

**Comment by cowtowncoder** [comment]
That sounds reasonable from technical perspective.

But I would like to get this discussed on jackson developer list (https://groups.google.com/forum/#!forum/jackson-dev), to make sure it is something developers agree on.
Could you suggest this on the mailing list? I can make the change if there is consensus for this.

**Comment by marcottedan** [comment]
I've just registered to jackson-dev and posted it. Let's see what happens next!

Thank you for your time!
