### ISSUE TITLE
ISO8601 Date Time does not require colon in time zone designators

### ISSUE THREAD

**Issue by kristofferpeterhansel** [FasterXML/jackson-databind#919]
Working on handling ISO8601 date time formats in our application I have been looking a bit on how various projects handle it (mainly to see if someone else already implemented it so I didn't have to 😃)

And I noticed that while the ISO8601Utils class of Jackson supports most of it. It skips the time zone designator format without the colon.

According to the [Wikipedia Page] (https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) there are 4 permutations:
```
<time>Z
<time>±hh:mm
<time>±hhmm
<time>±hh
```
But as far as I can tell the implementation in Jackson only supports the first 2?

**Comment by cowtowncoder** [comment]
This sounds plausible. Trying to support full variation of ISO-8601 has been a gift that keeps on giving... :)

I hope I will have time to improve this; or anyone else with time and itch.

**Comment by kristofferpeterhansel** [comment]
Indeed. Turns out the Joda Time ISODateTimeFormat class appears to have a fully functional one (as least it has eaten everything I have thrown at it so far). But I suppose that is an optional dependency for Jackson. So delegating to that isn't really an option.

**Comment by cowtowncoder** [comment]
Right, we want to keep core databind with minimal external dependencies.

So a fix to iso-8601 utils would be most welcome, whoever gets there first.

**Comment by cowtowncoder** [comment]
Actually I think all of those should be handled. A fix was applied in 2.5.1 I think; could it be that you might be using an older version? I see the handling in utils class, as well as couple of cases of colons missing (and just using hour) in Date deserialization tests.
