### ISSUE TITLE
@JsonCreator not working on a factory with multiple arguments for a enum type

### ISSUE THREAD

**Issue by logic-1** [FasterXML/jackson-databind#929]
Using a factory method having multiple arguments annotated with @JsonCreator works normally when the factory is for a class type, but fails if the factory is for an enum type.

jackson-databind v 2.5.1
jackson-annotations v 2.5.0

e.g. code 

```java
String json = "{\"intProp\":1,\"stringProp\":\"first\"}";
ObjectMapper mapper = new ObjectMapper();

MyClass classValue = mapper.readValue(json, MyClass.class); //works
MyEnum enumValue = mapper.readValue(json, MyEnum.class); //fails 
```

both MyClass and MyEnum has a method like 

```java
@JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
public static MyClass/MyEnum forValues(@JsonProperty("intProp") int intProp, @JsonProperty("stringProp") String stringProp){
        
        /// logic to create an instance with params using int
        // in case of enum find the appropriate object. 
        return object; 
}
```

**Comment by cowtowncoder** [comment]
I can confirm this. Support for multi-argument creators does not yet exist; exception is thrown with "Unsuitable method <method> decorated with @JsonCreator (for Enum type <enumtype>)".
Would be good to add support.

**Comment by ralfstuckert** [comment]
+1 for this issue. I prefer serialization either as a simple value (using @JsonValue), or as "an Object" instead of standard enum values. By doing so you are giving the consumer side the chance to use regular (non-enum) classes. Having to use enums on "both sides" introduces undesirable tight coupling.
