### ISSUE TITLE
Regression in Jackson 2.6.x: missing @type

### ISSUE THREAD

**Issue by jloisel** [FasterXML/jackson-databind#930]
Hi,

There is a regression in Jackson 2.6.x. The following Gist contains a JUnit test which works fine with Jackson 2.5.x but fails with Jackson 2.6.x:

https://gist.github.com/jloisel/3e21cc14fb5779c2b1d3

It seems like a type inference issue with Generics.

**Comment by cowtowncoder** [comment]
Sounds like potential bug. But if I am not mistaken, it is related to Java8 `Optional`, so I will move this to JDK8 module.

**Comment by cowtowncoder** [comment]
Actually I think this was already reported as https://github.com/FasterXML/jackson-datatype-jdk8/issues/14.

Thank you for reporting this -- I hope to resolve it for 2.6.2.

**Comment by jloisel** [comment]
Thanks :)

I submitted it here because i got no response from the other report. I wasn't sure you were aware of. It happens with Guava's Optional too.

**Comment by cowtowncoder** [comment]
@jloisel I am slowly going through backlog of things from my vacation. :)
