### ISSUE TITLE
unexpected subtype serialization problem when using @JsonValue

### ISSUE THREAD

**Issue by elucash** [FasterXML/jackson-databind#937]
When using `@JsonSubTypes` serialization is used with `@JsonValue` then type id is written as a type of synthetic substitute value's type rather that original object's type, so it is impossible to deserialize back original type.
Please advise if it is a bug or improper usage?
Originally reported as immutables/immutables#175

**Comment by cowtowncoder** [comment]
It should be type id of the actual value returned by `@JsonValue` annotated method, yes. It is not currently possible to internally to separate type and value handling, which would be needed if type id was to be based on original value, but value serialization on synthetic value.

If different logic was needed, perhaps it would be possible to add an annotation property in `@JsonValue` (serializeOriginalType=true? or something) to indicate that a hybrid approach was needed.

**Comment by elucash** [comment]
Thank you for the explanation! At this point I would not pursue making a feature request for this, while this is, probably, really minor use case for lots of internal changes required.
We'll try to mitigate this on our side.

**Comment by cowtowncoder** [comment]
Sounds good. I'll keep the idea in mind, just in case someone else bumps into same issue.
