### ISSUE TITLE
Incorrect serialization of enum map key 

### ISSUE THREAD

**Issue by bimargulies** [FasterXML/jackson-databind#943]
https://github.com/bimargulies/jackson-enum-tc

I have a module with a key serializer for the enum class TestEnum. When I serialize from a map to a tree, where one of the map values it a map with a key of this enum type, the key serializer is not called.

**Comment by cowtowncoder** [comment]
Does it only fail as part of regular `Map`? That is, works when serializing enum itself?

**Comment by bimargulies** [comment]
Yea, it works for all kinds of other cases with that enum. The nested map is the first failure I've seen.

**Comment by cowtowncoder** [comment]
Ok, that makes some sense, wrt finding the root cause.

**Comment by cowtowncoder** [comment]
After tackling other issues (such as much simpler #749), I hope to solve the issue of custom key serializer for "untyped" Maps (ones where key type is loose, usually `java.lang.Object`), which most commonly manifests itself as problem for root Map values. But it can also occur for other kinds of heterogenous `Map`s.

**Comment by cowtowncoder** [comment]
FWTW, the useful caching-helper class is `PropertySerializerMap`, and given that key serializers are still instances of `JsonSerializer`, it should actually work as is. The main question will just be how to integrate the thing, wrt lookups. It may be easiest to hide this within new general-purpose key serializer instead of further complicating, say, `MapSerializer`. I hope to tackle this issue tomorrow.

**Comment by cowtowncoder** [comment]
Was able to implement a dynamic key serializer based on ideas bounced on dev list. Key serializer is used if nominal type is detected as `Object.class`; assumption (for now) being that if a more specific type is passed, there is a reason for that. That part of the logic may be improved later on if and as needed.
For now local caching (within serializer) is done using `PropertySerializerMap`, but I also created an issue for possible adding a higher-level caching, similar to existing value serializer caches. This would help with the cases where `Map`s exist where number of distinct types for keys is large, and where `PropertySerializerMap` does not perform well (it is designed for lowish number of choices).
