### ISSUE TITLE
Ignore property during deserialization but retain in serialization not working

### ISSUE THREAD

**Issue by nezda** [FasterXML/jackson-databind#95]
Using `com.fasterxml.jackson.core:jackson-{core,annotations,databind} 2.1.0`, I think the code below to ignore a computed property (i.e., no field) during deserialization (property `zip`), but include it in serialization used to work, but now it doesn't.  I also tried removing class level `@JsonIgnoreProperties({"zip"})` and adding `@JsonIgnore` along with `@JsonProperty("zip")` but that didn't work either.

The variant with a field still works: https://gist.github.com/2510887 .

``` java
	@JsonIgnoreProperties({"zip"})
	public static class Foo {
		private final int bar;


		public Foo(@JsonProperty("bar") final int bar) {
			this.bar = bar;
		}


		public int getBar() {
			return bar;
		}


		@JsonProperty("zip")
		public int getZip() {
			return bar * 2;
		}


		static <T> T fromJson(final String json, final Class<T> clazz) {
			try {
				return new ObjectMapper().readValue(json, clazz);
			} catch (final IOException ioe) {
				throw Throwables.propagate(ioe);
			}
		}


		static String asJson(final Object obj) {
			try {
				return new ObjectMapper().writeValueAsString(obj);
			} catch (final IOException ioe) {
				throw Throwables.propagate(ioe);
			}
		}
	}


	@Test
	public void testIgnoreDuringDeserializationButNotSerialization() {
		final Foo foo = new Foo(1);
		final String json = Foo.asJson(foo);
		// json does not include zip computed property
		LG.info("foo: {}", json);
		final Foo reconstituted = Foo.fromJson(json, Foo.class);
	}
```

**Comment by kamkie** [comment]
+1

**Comment by herau** [comment]
:+1:

**Comment by lorrin** [comment]
+1 Would be nice to handle the `@JsonCreator` use case too. E.g. have getter that returns computed property, don't want to include property in the constructor argument list.

**Comment by apajaros** [comment]
+1

**Comment by tostrowski** [comment]
+1

**Comment by tonypiazza** [comment]
+1

**Comment by cowtowncoder** [comment]
Ok: I ended up adding new properties `allowGetters` and `allowSetters` (defaulting to `false`).
So, to support "read-only" properties with `@JsonIgnoreProperties`, you can use:

```java
@JsonIgnoreProperties(value={ "computed" }, allowGetters=true)
public class Stuff {
   // other accessors first...

   // and then pseudo-property with just getter, no matching setters
   public int getComputed() { return 42; }
}
```

**Comment by Reeska** [comment]
Thank you very much guys this is the thing that really helped me 👍

**Comment by vkrishna17** [comment]
I have tried `@JsonIgnoreProperties(value = "fieldName", allowGetters=true)`. This worked for me. 
But if try `@JsonProperty(access = JsonProperty.Access.READ_ONLY)` on getter method, doesn't works.

**Comment by cowtowncoder** [comment]
@vkrishna17 This is a closed issue to if have remaining issues it makes sense to file a new issue with specific remaining problem(s).
