### ISSUE TITLE
Direct access of Tree Model node

### ISSUE THREAD

**Issue by Norcoen** [FasterXML/jackson-databind#950]
I'm trying to use a json file as my applications configuration file with deep nesting

Example:
```json
{
  "login": {
    "username": {
      "name": "username",
      "value": "MyUsername"
    }
}
``` 

I thought using jacksons tree model would be a good approach, but I can't figure out how to access nested values directly.

Let's say my application needs the username value, I'd like to access it kinda like this:
``` java
String username = config("login.username.value");
```
right now the only thing I figured out was to use chained functions
```java
String username = rootNode.path("login").path("username").path("value").textValue();
```
Is what I'm trying to do possible or am I maybe looking in the wrong direction?

Kind regards,
Frank

**Comment by cowtowncoder** [comment]
You can use Json Pointer functionality, something like:

    String username = node.at("/lgin/username/value/").textValue();

In future, please use the mailing list for questions: issue tracker is for reporting issues.
