### ISSUE TITLE
Date formatting behaviour change between 2.6.0 and 2.6.1

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-databind#954]
I believe this is the same problem as https://github.com/FasterXML/jackson-module-scala/issues/222 but I'm opening an issue here as it does not appear to be specific to Scala.

This code behaves differently on 2.6.0 vs 2.6.1:

```java
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));
System.out.println(objectMapper.writeValueAsString(new Date()));
```

2.6.0 outputs `"2015-10-01 14:32:08"` whereas 2.6.1 outputs `"2015-10-01 13:33:01"`. My system timezone is set to BST. 2.6.0 produces the correct time for that timezone.

**Comment by cowtowncoder** [comment]
@wilkinsona Thank you for reporting this. I have fixed at least one bug that may be close related (or same), regarding handling of configured time zone. If you can test 2.6.3-SNAPSHOT (either built locally from 2.6 branch; or from Sonatype snapshot repo), that could be helpful.

**Comment by wilkinsona** [comment]
2.6.3-SNAPSHOT (from the Sonatype repo) looks good to me; it produces the same output as 2.6.0. Thanks.
