### ISSUE TITLE
XML Empty tag to Empty string in the object during xml deserialization

### ISSUE THREAD

**Issue by thefalconfeat** [FasterXML/jackson-databind#956]
If an empty tag is available in the xml and the respective field in the object is a string, it would be nice to have jackson populate the field with empty string rather than with null value.

Ex: 

```java
Object;
public class Name {
private String first;
private String last;
}
```

```xml
xml: 
<name>
<first>Ryan</first>
<last></last>
</name>
```

I would expect 
Name name = mapper.readValue(xml, Name.class)

name.getLast().equals("") to return true but name.getLast() ends up being null.

Any help would be appreciated.

**Comment by cowtowncoder** [comment]
And is this with 2.6.2? I thought this coercion already happened.

**Comment by thefalconfeat** [comment]
yes, this is happening with 2.6.2 as well.
I am using jackson-dataformat-xml:2.6.2

**Comment by cowtowncoder** [comment]
Ok. Oh, this actually needs to be filed at:

https://github.com/FasterXML/jackson-dataformat-xml/issues

as it is specific to XML format handling.

**Comment by thefalconfeat** [comment]
okay, will do.. thanks for your response.
