### ISSUE TITLE
`@JsonCreator` not working on a factory with no arguments for ae enum type

### ISSUE THREAD

**Issue by ajonkisz** [FasterXML/jackson-databind#960]
Using a singleton pattern as described [here](http://www.drdobbs.com/jvm/creating-and-destroying-java-objects-par/208403883?pgno=3) by Joshua Block results in `IllegalArgumentException` from `BasicDeserializerFactory:1252`. An example:

```java
public enum  MyEnum {
    INSTANCE;
    
    @JsonCreator
    public static MyEnum getInstance() {
        return INSTANCE;
    }   
}
```

A dirty workaround is to add an ignored parameter like:
```java
@JsonCreator
public static MyEnum getInstance(String ignored) {
    return INSTANCE;
}
```

This issue is related to [issue 929](https://github.com/FasterXML/jackson-databind/issues/929)

**Comment by cowtowncoder** [comment]
Yes, I think it is essentially a variation of #929. Thank you for reporting this.
