### ISSUE TITLE
dependencies conflict when using play-services:8.1.0 with jackson-databind:2.6.2

### ISSUE THREAD

**Issue by MuhammadShaker** [FasterXML/jackson-databind#961]
Hi,
When I'm trying to update play service to latest version {8.1.0} I get the following problem while I'm running the app
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

But when I use play-services:7.0.0 I don't get any problem!

**Comment by cowtowncoder** [comment]
Unfortunately this does not give much information as to what might be going wrong.

**Comment by MuhammadShaker** [comment]
My gradle file is
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
    }

    defaultConfig {
        applicationId "com.feedsflow.moontyapp"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23+'
    compile 'com.android.support:support-v4:23+'
    compile 'com.android.support:cardview-v7:23+'
    compile 'com.android.support:recyclerview-v7:23+'
    compile 'com.android.support:design:23+'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'com.google.android.gms:play-services:7.0.0'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.6.2'
    compile 'com.fasterxml.jackson.core:jackson-core:2.6.2'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.6.2'
}

When I'm trying to use latest version of play services  {compile 'com.google.android.gms:play-services:8.1.0'} instead of {compile 'com.google.android.gms:play-services:7.0.0'} I get this error

com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

I didn't change any thing else in my code

**Comment by cowtowncoder** [comment]
Unfortunately I don't know anything about Play framework (or used it). I hope developers/users of Play can help you further. What you have above does not point to any problem with Jackson, so there is nothing I can do with it.
