### ISSUE TITLE
Add PropertyNameStrategy `KEBAB_CASE`

### ISSUE THREAD

**Issue by danielmischler** [FasterXML/jackson-databind#963]
With json api (jsonapi.org) as a possible standard way to exchange json data between applications it would be great to have its recommended property naming strategy added to jackson:
http://jsonapi.org/recommendations/#naming
http://guides.emberjs.com/v2.1.0/models/customizing-serializers/#toc_json-api-document

It seems to be CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES just with underscores replaced by dashes :-)

**Comment by cowtowncoder** [comment]
I think this is what was dubbed somewhere as "kebab-case"? (https://en.wikipedia.org/wiki/Snake_case).
Sounds reasonable.

There was also a brief discussion on dev list about renaming existing choices (or, rather, adding new replacements, deprecating existing ones), so maybe worth mentioning there.
