### ISSUE TITLE
Marshmallow update = com.fasterxml.jackson.databind.JsonMappingException: Can not access private java.lang.reflect.Field() (from class java.lang.reflect.Field; failed to set access: Can't make field constructor accessible

### ISSUE THREAD

**Issue by marwfair** [FasterXML/jackson-databind#964]
I just updated to Marshmallow, now I am getting this error when trying to deserialize json: "com.fasterxml.jackson.databind.JsonMappingException: Can not access private java.lang.reflect.Field() (from class java.lang.reflect.Field; failed to set access: Can't make field constructor accessible". It happens on this line
getObjectMapper().readValue(jsonObject, clazz); 

All of the fields in my models are marked as private, and using getters and setters to set the value. I'm not sure if that is related to this error.

Everything still works great on pre-Marshmallow devices.

Any ideas?

**Comment by cowtowncoder** [comment]
Unfortunately no. Perhaps it's a bug in Marshmallow; or perhaps it is a misguided fix of some kind?
Without means to reproduce this, or possible workarounds, it is difficult.

As a work-around, maybe try setting fields as `protected` and see if that gets around whatever the problem is.

**Comment by marwfair** [comment]
@cowtowncoder I set all of the fields to protected, and even tried public, but still getting the same error.

**Comment by cowtowncoder** [comment]
Ah. It's actually trying to set access since that reduces call overhead a lot on JavaSE, and not just because it is (also) needed to access non-public fields, methods and constructors.
There is a `MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS`, disabling of which should prevent call to `setAccess()`. But it will probably also make it impossible to access non-public members; if your setters/getters are public, that may be ok.

**Comment by marwfair** [comment]
Adding MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS and setting it false worked. Thank you so much!

**Comment by cowtowncoder** [comment]
@marwfair Glad it works! I hope the underlying problem can be solved at some point, but it is good to have a work-around for now.
