### ISSUE TITLE
Jackson 1.x Documentation

### ISSUE THREAD

**Issue by alexan** [FasterXML/jackson-databind#967]
Hello,
I'm searching for the Documentation of Jackson 1.x
the link from the [Wiki](http://wiki.fasterxml.com/JacksonHome)
http://jackson.codehaus.org/ requires htaccess password.
Where can I find the documentaiton?

**Comment by cowtowncoder** [comment]
(in the future, please use user mailing list for questions -- but I'll answer this one here as it's likely to be reported/asked by others)

Right, Codehaus closed a while ago, as per:

https://julien.ponge.org/blog/farewell-to-codehaus/

and there isn't real replacement. Are you specifically looking for javadocs?
They would be available via Maven Central:

http://repo1.maven.org/maven2/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13-javadoc.jar

for example. Although I guess I could also copy some of those under this project.
So I will try to do that actually.

**Comment by cowtowncoder** [comment]
Ok; added 1.9 javadocs, see:

http://fasterxml.github.io/jackson-databind/javadoc/1.9/

and modified links there from github projects, old FasterXML wiki.
