### ISSUE TITLE
Change in timezone handling for Date created from Joda DateTime between 2.6.2 and 2.6.3

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-databind#973]
In 2.6.3, I'm seeing a DateTime that's in UTC move into BST (my timezone) when it's converted into a Date and written as a String. In 2.6.1 and 2.6.2 it stays in UTC. This code reproduces the problem:

```java
	public static void main(String[] args) throws JsonProcessingException {
	    ObjectMapper objectMapper = createObjectMapper();
		DateTime dateTime = new DateTime(1988, 6, 25, 20, 30, DateTimeZone.UTC);
		System.out.println(objectMapper
	            .writeValueAsString(dateTime));
		Date date = dateTime.toDate();
		System.out.println(objectMapper
	            .writeValueAsString(date));
	}

	private static ObjectMapper createObjectMapper() {
	    ObjectMapper mapper = new ObjectMapper();
	    mapper.registerModule(createJodaModule());
	    mapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss ZZZ"));
	    return mapper;
	}

	private static SimpleModule createJodaModule() {
	    SimpleModule module = new SimpleModule();
	    module.addSerializer(DateTime.class, new DateTimeSerializer(
	            new JacksonJodaDateFormat(DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss ZZZ")
	                    .withZoneUTC())));
	        return module;
	}
```

The output for various versions of Jackson:

##### 2.6.1

```
"1988-06-25 20:30:00 UTC"
"1988-06-25 20:30:00 +0000"
```

##### 2.6.2

```
"1988-06-25 20:30:00 UTC"
"1988-06-25 20:30:00 +0000"
```

##### 2.6.3

```
"1988-06-25 20:30:00 UTC"
"1988-06-25 21:30:00 +0100"
```

**Comment by cowtowncoder** [comment]
Could you please re-file this at https://github.com/FasterXML/jackson-datatype-joda/issues as this handling is by Joda? I would transfer it but I don't think github has any easy means to do that.

**Comment by philwebb** [comment]
@cowtowncoder Raised here: https://github.com/FasterXML/jackson-datatype-joda/issues/76

GitHub indeed doesn't have a way to transfer issues. When I need to do that I usually edit the original comment, copy the raw markdown then paste it into a new issue.

**Comment by cowtowncoder** [comment]
Thanks -- yes, this is unfortunate omission from github.
