### ISSUE TITLE
ObjectNode set and setAll methods should have ObjectNode return type

### ISSUE THREAD

**Issue by lightoze** [FasterXML/jackson-databind#974]
They return `this` for chaining.

**Comment by cowtowncoder** [comment]
Ideally, yes. Method signatures are sub-optimal.

But since such a change would be binary incompatible change, breaking any code that uses these methods, unless code is recompiled. So such change is very unlikely to be made for Jackson 2.x.

**Comment by lightoze** [comment]
Oh that's right.
