### ISSUE TITLE
ObjectMapper#canSerialize(Object.class) returns false even though FAIL_ON_EMPTY_BEANS is disabled

### ISSUE THREAD

**Issue by flexfrank** [FasterXML/jackson-databind#978]
Version: 2.5.x, 2.6.x

When `FAIL_ON_EMPTY_BEANS` is disabled, `ObjectMapper#writeValueAsString(new Object())` succeeds.
However, `ObjectMapper#canSerialize(Object.class)` returns false.
 
```java
ObjectMapper mapper = new ObjectMapper();
mapper.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
System.err.println(mapper.canSerialize(Object.class));
System.err.println(mapper.writeValueAsString(new Object()));
```

```
false
{}
```

I suppose https://github.com/FasterXML/jackson-databind/commit/152aabb7399df1d3178418062c7fa580f3533d4e caused this problem.

**Comment by flexfrank** [comment]
I created two possible solutions:
https://github.com/FasterXML/jackson-databind/pull/979
https://github.com/FasterXML/jackson-databind/pull/980

**Comment by cowtowncoder** [comment]
Did you run full unit test suite with both possible fixes? It would seem like changes could have side effects.

**Comment by flexfrank** [comment]
I ran `mvn test` and both pass all tests.

```
Results :

Tests run: 1478, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by cowtowncoder** [comment]
Looks like there is bit of prior art wrt #703. But I think that mostly refers to case of "fail on empty" being true, whereas this is for it being false.
