### ISSUE TITLE
Reading data shortly after writing it throws exceptions

### ISSUE THREAD

**Issue by zoltish** [FasterXML/jackson-databind#981]
Hello.

Basically, I save data with Jackson to a file, and moments later I read it back in another activity of mine. This works most of the time, however - once in a thousand or so, it doesnt. 

From my experiments I can see that it happens because the time in between writing and reading is too short, so my issue is both letting you know about this, and asking if theres anything I can do about it (other than delaying the read back time)?

Exception:

```
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input 
 at [Source: /storage/emulated/0/Android/data/package.name/data.json; line: 1, column: 1] 
 at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:348)
 at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1426)
 at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1123)
 ```

Thanks!

**Comment by cowtowncoder** [comment]
There is nothing Jackson does that should cause this (nothing I can think of that is). My guess would be that it would be OS/file-system level caching. Jackson does close the underlying `File` (or, if given a stream, flushes contents to it).

From Java code you can perhaps try force file-system level sync(); I have not done that, and it is potentially expensive as it tends to force flushing of all OS-level disk caches. Or perhaps specific filesystem/platform exposes other ways.

Out of curiosity: what platform/filesystem combination is this on?
