### ISSUE TITLE
Deserializing Json having unknown properties produces strange result

### ISSUE THREAD

**Issue by Xnyle** [FasterXML/jackson-databind#987]
Please take a look at the following test, it produces 3 List entries instead of one.

```java

public class DeserializedObject {

		public DeserializedObject() {

		}

		String aProperty;

		public String getaProperty() {
			return aProperty;
		}

		public void setaProperty(String aProperty) {
			this.aProperty = aProperty;
		}

	}

```

```java

@Test
	public void test001Deserialize()  {

		ObjectMapper jsonMapper = new ObjectMapper();
		jsonMapper.addHandler(new DeserializationProblemHandler() {
			@Override
			public boolean handleUnknownProperty(DeserializationContext ctxt, JsonParser jp, JsonDeserializer<?> deserializer, Object beanOrClass, String propertyName) throws IOException, JsonProcessingException {
				return true;
			}
		});

		String input = "[{\"aProperty\":\"x\",\"unknown\":{\"unknown\":{}}}]";
		ArrayList<DeserializedObject> deserializedList = jsonMapper.readValue(input, new TypeReference<ArrayList<DeserializedObject>>() {
		});

		Assert.assertEquals(1, deserializedList.size());
	}

```

**Comment by cowtowncoder** [comment]
And just to make sure, is this with Jackson 2.6?

**Comment by Xnyle** [comment]
I guess 2.5, will have to check on Friday.

Mit freundlichen Grüßen
Björn Schmidt


Am 28. Oktober 2015 18:50:43 MEZ, schrieb Tatu Saloranta <notifications@github.com>:

**Comment by cowtowncoder** [comment]
Actually the problem is with your `DeserializationProblemHandler`: it does not properly skip structured values, leaving unprocessed token in the stream read by `JsonParser`. The fix there is to add

    jp.skipChildren();

in handler, as suggested by javadocs of `DeserializationProblemHandler`.

**Comment by Xnyle** [comment]
Thx, I didn't get that, and thx for adding the notice to the docs ;-)
