### ISSUE TITLE
JacksonAnnotationIntrospector not properly checking for null JsonProperty

### ISSUE THREAD

**Issue by philnate** [FasterXML/jackson-databind#991]
This is actually no real bug, as the application works, but it makes debugging harder as you potentially have lots of breaks on this NPE being raised, while you're actually hunting some other NPE.
Code in question is JacksonAnnotationIntrospector around line 75

```
try {
    // We know that values are actually static fields with matching name so:
    Field f = value.getClass().getField(value.name());
    if (f != null) {
        JsonProperty prop = f.getAnnotation(JsonProperty.class);
        String n = prop.value();
        if (n != null && !n.isEmpty()) {
            return n;
        }
    }
} catch (Exception e) {
    // no such field, or access; neither which we can do much about
}
```
After the annotation JsonProperty has been looked up it's no validated that we actually found such an annotation, thus the following prop.value() might throw an NPE, which is correctly catched. But still this feels avoidable to me.

Version affected is at least 2.6.1

**Comment by cowtowncoder** [comment]
I think this is actually fixed in a later version, but I am not sure if it's in 2.6[.3] or just in `master`.
I agree in that it's silly not to check for a null as that's a cheap check, and then instead catch all exceptions.

**Comment by cowtowncoder** [comment]
Verified: null check exists in 2.6.3 at least, as well as `master` branch. Similarly, exception catching more granular so will not swallow all `Exception`s.
