### ISSUE TITLE
JsonTypeInfo can not be overide in implemented classes

### ISSUE THREAD

**Issue by breizh31** [FasterXML/jackson-databind#996]
It seems that @JsonTypeInfo can not be overriden in the implemented classes of an interface.

I have an interface:
> @JsonTypeInfo (use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.WRAPPER_OBJECT)
   @JsonSubTypes ({@JsonSubTypes.Type (value = ElasticBooleanQuery.class, name = "bool"),
                                 @JsonSubTypes.Type (value = ElasticRegexpQuery.class, name = "not")})
> public interface IElasticQuery { 
> }

This interface is implemented by 3 classes ElasticBooleanQuery, ElasticRegexpQuery and ElasticMatchQuery. This last is not declared as @JsonSubTypes.

I want to serialize a list of IElasticQuery which contains ElasticBooleanQuery, ElasticRegexpQuery and ElasticMatchQuery.

I want to serialize the name from ElasticBooleanQuery (bool) and ElasticRegexpQuery (not) but not for ElasticMatchQuery.

In order to do this, i define ElasticMatchQuery like this:
> @JsonTypeInfo (use = JsonTypeInfo.Id.NONE)
> @JsonInclude (Include.NON_EMPTY)
> public class ElasticMatchQuery implements IElasticQuery {
>    private SimpleEntry<String, Object> match;
> }

But whereas JsonTypeInfo is NONE, the name ElasticMatchQuery always appears in my JSON.

How to do ?

Thanks

**Comment by cowtowncoder** [comment]
That use case is not supported: all subtypes of a base type are to include type info, or none.
Behavior is undefined if subtypes have different type info declarations.

So: there is no official way to do what you want, and no plans to try to do that. It is not the way this feature is intended to be used.

**Comment by breizh31** [comment]
I'm sad to read this. I'll find a dirty way to do what i want.

Thanks for your answer.
